### ISSUE TITLE
Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)

### ISSUE THREAD

**Issue by badigeranand007** [helm/helm#11399] opened 2022-09-29 19:12 UTC
Output of `helm version`:
root@144-8-225-229:/apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service # helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

Output of `kubectl version`: kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

root@144-8-225-229:/apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service # helm upgrade --install --wait --timeout 1200s --history-max 10 --debug appointment-availability-service-ple ./ --namespace ontv-vzontime-ple -f=.//values_ple.yaml --set-string global.build.env=ple --kubeconfig=/root/kubeconfig_ple_EAST
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/kubeconfig_ple_EAST
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/kubeconfig_ple_EAST
history.go:56: [debug] getting history for release appointment-availability-service-ple
Release "appointment-availability-service-ple" does not exist. Installing it now.
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service

Error: create: failed to create: the server responded with the status code 413 but did not return more information (post secrets)
helm.go:84: [debug] the server responded with the status code 413 but did not return more information (post secrets)
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
        helm.sh/helm/v3/pkg/storage/driver/secrets.go:164
helm.sh/helm/v3/pkg/storage.(*Storage).Create
        helm.sh/helm/v3/pkg/storage/storage.go:69
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:340
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:278
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:122
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_amd64.s:1571
root@144-8-225-229:/apps/opt/jenkins/83-aws-us-east-1-ontv-vzontime-ple-appointment-availability-service # helm versiob
Error: unknown command "versiob" for "helm"

Did you mean this?
        version

Run 'helm --help' for usage.

**Comment by joejulian** [comment] 2022-09-29 23:25
Duplicate of #11398

**Closed by joejulian** 2022-09-29 23:25 UTC
