### ISSUE TITLE
Show app version in history

### ISSUE THREAD

**Issue by jaipradeesh** [helm/helm#5205] opened 2019-01-24 09:55 UTC
At the moment, `helm history` returns

```
REVISION	UPDATED                 	STATUS    	CHART    	DESCRIPTION     
```

.. is there a way to display `APP VERSION` column?

== Meta ==

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by hickeyma** [comment] 2019-02-28 15:56
If its ok, I'll work on this

**Comment by bacongobbler** [comment] 2019-02-28 16:02
I'd hold off until the main refactoring for the action package is done for v3 (#5365) as much of the work will likely have to be re-done within the action package. Asides that, go for it!

**Comment by hickeyma** [comment] 2019-02-28 16:15
ok sure, thanks @bacongobbler.

**Comment by hickeyma** [comment] 2019-04-02 16:29
@bacongobbler Now that #5365 is merged, I have opened PR #5538 for this feature.

**Comment by hickeyma** [comment] 2019-04-03 07:02
@bacongobbler should this be made a duplicate of #5044 or do we maintain the issues with this for v3 and the other for v2?

**Comment by hickeyma** [comment] 2019-04-30 08:25
PR #5538 now merged.

**Closed by hickeyma** 2019-04-30 08:25 UTC
Labels: feature, v3
