### ISSUE TITLE
Invalid image name when use image with tag is number

### ISSUE THREAD

**Issue by khainguyen95** [helm/helm#5768] opened 2019-05-21 07:18 UTC
**Describe the bug**
I tried to deploy my image with tag is number. Causing Kubernetes pod status to be InvalidImageName

**Version of Helm and Kubernetes**:
Helm version:
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**What happened**:
Image:
```
khainguyendinh/dotnet:45980468
```
Output:
```
NAME                   READY     STATUS             RESTARTS   AGE
dotnet-dddb74c6d-9n48w   0/1       InvalidImageName   0          5m
```
Describe pod:
```
Events:
  Type     Reason          Age                From                                             Message
  ----     ------          ----               ----                                             -------
  Normal   Scheduled       6m                 default-scheduler                                Successfully assigned test/dotnet-dddb74c6d-9n48w to gke-demo-ci-default-pool-62e9718a-z0
x4
  Normal   SandboxChanged  6m                 kubelet, gke-demo-ci-default-pool-62e9718a-z0x4  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          4m (x12 over 6m)   kubelet, gke-demo-ci-default-pool-62e9718a-z0x4  Error: InvalidImageName
  Warning  InspectFailed   56s (x27 over 6m)  kubelet, gke-demo-ci-default-pool-62e9718a-z0x4  Failed to apply default image tag "khainguyendinh/dotnet:4.5980468e+07": couldn't parse i
mage reference "khainguyendinh/dotnet:4.5980468e+07": invalid reference format
```
**What you expected to happen**:
Support image with tag is number.

**Comment by jdolitsky** [comment] 2019-05-22 01:09
I've confirmed this using "helm template". I've also verified this is a Helm issue (not kubectl etc)

**Comment by karuppiah7890** [comment] 2019-05-27 16:29
Even I am able to reproduce the issue with this chart - [issue-5768.tar.gz](https://github.com/helm/helm/files/3224462/issue-5768.tar.gz) , by doing `helm template`

I am able to reproduce with v2 and v3 too - 

```
$ helm version --client
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

```
$ helm3-alpha version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

**Comment by karuppiah7890** [comment] 2019-06-02 17:16
@khainguyen95 @jdolitsky I don't know if I can entirely say this is a helm issue. Like, when I use the number `459804`, the tag number comes correctly, but when I put `45980468` the image name along with tag shows up as `khainguyendinh/dotnet:4.5980468e+07`. 

I think there's been some mishandling of the values.yaml when numbers are big - variables not being able to store big numbers as is? so they are being stored in scientific notation?

I have a small solution to this actually, instead of trying to make changes in helm, if we put the tag in quotes, then it works! That is, like this:

```
image:
  repository: khainguyendinh/dotnet
  tag: "45980468"
```

This way, the tag is treated as a string and not a number, and hence it's not represented in scientific notation (using `e+` and stuff)

@khainguyen95 @jdolitsky Let me know what you think about this!

**Comment by bacongobbler** [comment] 2019-06-02 18:40
At first glance, this appears to be a duplicate of #1707. Can you check and confirm if that's the case here?

**Comment by karuppiah7890** [comment] 2019-06-03 01:27
@bacongobbler yes, that's the issue - number getting converted to scientific notation representation. But idk where the values is coming from in this issue, `--set` or `--values`

**Comment by hickeyma** [comment] 2019-06-04 07:33
@karuppiah7890 Thanks for the confirmation. Closing this issue as a duplicate of #1707.

**Closed by hickeyma** 2019-06-04 07:33 UTC
Labels: bug
