### ISSUE TITLE
Why did helm3 status remove resources

### ISSUE THREAD

**Issue by koulq** [helm/helm#9250] opened 2021-01-19 08:34 UTC
Output of `helm version`: helm 3.5

Output of `kubectl version`: v1.14.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Why did helm3 status remove resources?
For example: helm status app-5t72h -n klq-test
![image](https://user-images.githubusercontent.com/18571340/105008264-f69aa180-5a73-11eb-8670-f82390581997.png)

If it's helm2
![image](https://user-images.githubusercontent.com/18571340/105008461-38c3e300-5a74-11eb-8a16-68ee8159f59f.png)

**Comment by mattfarina** [comment] 2021-01-19 14:27
This is a bug. A change in client-go, if I remember right, caused this. It was fixed in 2.x but not yet fixed in 3.x.

**Comment by bacongobbler** [comment] 2021-01-19 16:24
See https://github.com/helm/helm/pull/7728.

Closing as a duplicate of https://github.com/helm/helm/issues/5952.

**Closed by bacongobbler** 2021-01-19 16:24 UTC
Labels: bug
