### ISSUE TITLE
[helm dep] update and build don't recognize local dependency charts

### ISSUE THREAD

**Issue by YingjunHu** [helm/helm#5531] opened 2019-03-29 20:32 UTC
Output of `helm version`: 
`Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}`

Output of `kubectl version`:
`Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Tested on Minikube and EKS

**BUG**: 
helm dependency won't recognize the local dependency charts. Say I have an umbrella chart A which contains subcharts B and C. When listing B and C as dependencies of A without field `repository`, the command `helm dep update` and `helm dep build` will fail and complaining `Error: no 'repository' field specified for dependency: "B or C"`.
But `helm dep list` can successfully find the subcharts and the status is `unpacked`

This bug is existed for a long time, I've seen the similar issue raised in #3742. I've even seen people tried to fix the bug in #3987 and #3422. But for some reason, they never get the luck to be merged. 

I would consider this should be a major bug since a lot of projects e.g. Istio is using requirements.yaml to enable/disable the subcharts. Although the functionality of enabling/disabling is no problem, it's still major since I think any good pipeline should run `helm dep update/build` before we actually deploy the project.

**How to reproduce**:
Create a chart A, create a folder `charts` and create subcharts B and C there. Edit `requirements.yaml` file to be 
```dependencies:
  - name: B
    version: 1.0.0 # or the version of B and C defined
    condition: B.enabled
```
Then run `helm dep build` or `helm dep update`

**Comment by bacongobbler** [comment] 2019-03-29 21:45
Hey there, is this a duplicate of #3742? We try to close duplicate tickets so the issue queue is easier to triage and users can more easily search for information on issues. Thanks!

**Comment by YingjunHu** [comment] 2019-03-30 04:22
@bacongobbler Well technically yes.. But that issue was from April 2018 and I haven't seen more comments from the team so I guess I should raise another issue. It's fine if we close this but I would appreciate if we can address this issue sooner..

**Comment by bacongobbler** [comment] 2019-03-30 05:00
I'll have a look at #3987. Thanks.

**Closed by bacongobbler** 2019-03-30 05:00 UTC
