### ISSUE TITLE
helm template --show-only fails if no template is rendered

### ISSUE THREAD

**Issue by gregsidelinger** [helm/helm#8204] opened 2020-05-26 19:31 UTC
Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Helm template returns an error when show-only is passed in if template does not return any rendered text. For example he ingress.enabled was set to false. Here are steps to reproduce.

```
helm create sample

helm template --show-only templates/ingress.yaml  --set ingress.enabled=true  sample
---
# Source: sample/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: RELEASE-NAME-sample
  labels:
    helm.sh/chart: sample-0.1.0
    app.kubernetes.io/name: sample
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:

helm template --show-only templates/ingress.yaml  --set ingress.enabled=false  sample
Error: could not find template templates/ingress.yaml in chart
```

This used to not cause errors in helm 2 when using the -x flag.
```
 helm template -x templates/ingress.yaml  --set ingress.enabled=false  sample
---
# Source: sample/templates/ingress.yaml
```

**Comment by bacongobbler** [comment] 2020-05-26 19:47
Duplicate of https://github.com/helm/helm/issues/7295. Please search for existing issues before opening a new one. Thanks.

**Closed by bacongobbler** 2020-05-26 19:47 UTC
