### ISSUE TITLE
merge and mergeOverwrite template functions doesn't override a boolean property with the false value

### ISSUE THREAD

**Issue by lorf** [helm/helm#9591] opened 2021-04-12 08:16 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:47:43Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

On premise.

# Should be
When merging several objects with `merge` (or `mergeOverwrite`) boolean properties in the object with higher precedence override boolean properties in the object with lower precedence.

# As is (the bug)
Boolean properties in the object with higher precedence, that contain the value `false`, don't override properties in the objects with lower precedence. The string properties gets overridden as expected.

# Reproduction
To demonstrate, here is the sample template:
```
{{- $default := dict "boolProp" true "stringProp" "Override me" }}
{{- $explicit := dict "boolProp" false "stringProp" "String value is overriden, but bool value is not!" }}

$default:
  {{- $default | toYaml | nindent 2 }}
$explicit:
  {{- $explicit | toYaml | nindent 2 }}

# Here is the bug: `boolProp` can't be overriden with a `false` value by
# `merge`. `boolProp` should be false here (the first argument to `merge` has
# precedence, according to helm docs)
merge $explicit $default:
  {{- merge $explicit $default | toYaml | nindent 2 }}

# `mergeOverwrite` also cannot deal with bools
mergeOverwrite $default $explicit:
  {{- mergeOverwrite $default $explicit | toYaml | nindent 2 }}
```
And here is the result of running `helm template .`:
```
---
# Source: merge-bool-bug/templates/merge.yaml
$default:
  boolProp: true
  stringProp: Override me
$explicit:
  boolProp: false
  stringProp: String value is overriden, but bool value is not!

# Here is the bug: `boolProp` can't be overriden with a `false` value by
# `merge`. `boolProp` should be false here (the first argument to `merge` has
# precedence, according to helm docs)
merge $explicit $default:
  boolProp: true
  stringProp: String value is overriden, but bool value is not!

# `mergeOverwrite` also cannot deal with bools
mergeOverwrite $default $explicit:
  boolProp: true
  stringProp: String value is overriden, but bool value is not!
```
Reproduced with helm v3.4.2 and v.3.5.3. Here is the complete helm chart: 
[merge-bool-bug-0.1.0.tar.gz](https://github.com/helm/helm/files/6294952/merge-bool-bug-0.1.0.tar.gz)

# Related
There are similar issues #5238 and #7313, but they are closed. There is similar issue #9587, but it only happens on helm v3.5.x, so it seems to be a different issue.

**Comment by lorf** [comment] 2021-04-12 08:56
The same behavior when higher precedence property has a value of `null`. Here is updated chart that contains the test with `null`:
[merge-bool-bug-0.1.1.tar.gz](https://github.com/helm/helm/files/6295216/merge-bool-bug-0.1.1.tar.gz)

**Comment by bacongobbler** [comment] 2021-04-14 22:58
This is a known and documented issue. Consider that there is no way to determine whether a boolean value is unset or false. You can only have two values: true and false.

In other words, the following two YAML files are identical in their intent:

```yaml
name: foo
enabled: false
```

```yaml
name: foo
```

In these particular cases, it is unclear whether the user actually wishes to change a value from `true` to false. The parser library responsible for this logic cannot determine how these values should be merged. Therefore the merge and mergeOverwrite perform a boolean OR in these cases.

FYI, the library responsible for this behaviour can be found here: https://github.com/imdario/mergo

Hope this helps.

**Comment by lorf** [comment] 2021-04-16 04:32
Thanks for the clarification!

Found the relevant Golang docs: https://golang.org/ref/spec#The_zero_value

To clarify it father - is it correct to say that Helm internally maps incoming YAML structure in values.yaml to a Golang structure, which doesn't support the YAML null/false features directly, and this may cause unexpected results when using merge/mergeOverwrite functions?

Is this considered a bug or just an inconvenience?

Anyway, I implemented a workaround by "inventing" my own "boolean" string based type. Not the wisiest, but works. But it's still not possible to undefine YAML map by overriding it with 'null' using mergeOverwrite.

The other workarounds would be:
* use [YAML merge](https://yaml.org/type/merge.html). But YAML merge doesn't deeply (recursively) merge maps;
* perform the merges outside of the Helm, e.g. using https://github.com/mikefarah/yq (see [this tip](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#merge-combine-all-documents-into-one)).

**Comment by bacongobbler** [comment] 2021-04-16 05:13
> is it correct to say that Helm internally maps incoming YAML structure in values.yaml to a Golang structure

correct.

> Is this considered a bug or just an inconvenience?

It's not a bug, it's a feature! :P

**Closed** 2021-04-19 02:22 UTC
Labels: question/support

**Comment by Antiarchitect** [comment] 2024-06-14 18:19
It shouldn't be a feature or the correct behavior. Absence of key in map, null value of the key and false value of the key are three separate cases IMHO.

**Comment by Antiarchitect** [comment] 2024-06-17 13:09
Moreover. According to sprig's [dict_test.go](https://github.com/Masterminds/sprig/blob/v3.2.3/dict_test.go#L250) mergeOverwrite should work as I expect it to work. But neither `merge` nor `mergeOverwrite` in helm doesn't work as expected: https://helm-playground.com/#t=LQhQG92ACASATApgMwIYFcA2AXaAuAXmngEsBjXAIgFsBPAIwHtHNLpsAndRaAX14hQ4ABw6N4%2BIqQrQaDZq2hpMAZx79Q1RBwDmiPNEgwAFEkTCAwo2G04SNFlwAfaFt09Yo8QEoAdHSYWPgE3PQB5ADdtAHcOEmx9QyFjUMRImLiE6FNybG9ss0trWwQUDBx800RzKxsRMXhvPwCFYNAgA&v=LQhQQ

Do anybody knows what is going on?
