### ISSUE TITLE
Helm breaks when trying to install a package with a version number that has a dash ('-')

### ISSUE THREAD

**Issue by huang-jy** [helm/helm#5399] opened 2019-03-05 11:44 UTC
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-gke.1", GitCommit:"5c4fddf874319c9825581cc9ab1d0f0cf51e1dc9", GitTreeState:"clean", BuildDate:"2018-11-30T16:18:58Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE

I encountered this while using a self-hosted repo (it's basically a httpd pod on GKE).

If you create a helm package that has a version number that has a dash (for example, 1.0.0-1) which is permitted by the semver convention (e.g. https://semver.org/#spec-item-9) , and doesn't fail `helm lint`, then when you deploy that onto a repo that serves the packages, helm just gives up:

```
$ helm search helm-charts
NAME                      	CHART VERSION	APP VERSION	DESCRIPTION                
helm-charts/httpd-dash  	1.0.0-1         	1.0             	A Helm chart for Kubernetes                              
helm-charts/httpd-plus  	1.0.0+1         	1.0             	A Helm chart for Kubernetes                              
helm-charts/httpd-std   	1.0.0           	1.0             	A Helm chart for Kubernetes                              
```

```
$ helm install "helm-charts/httpd-dash" --name test --debug --dry-run
[debug] Created tunnel using local port: '46171'

[debug] SERVER: "127.0.0.1:46171"

[debug] Original chart version: ""
Error: chart "httpd-dash" matching  not found in helm-charts index. (try 'helm repo update'). No chart version found for httpd-dash-
```

But it is actually in the index (otherwise it wouldn't show up on the search)

Attempting to run an install on the version with the "+" version chart doesn't have an issue, proving the config is good:

```
$ helm install "helm-charts/httpd-plus" --name test --debug --dry-run
[debug] Created tunnel using local port: '33331'

[debug] SERVER: "127.0.0.1:33331"

[debug] Original chart version: ""
[debug] Fetched helm-charts/httpd-plus to /home/user/.helm/cache/archive/httpd-plus-1.0.0+1.tgz

[debug] CHART PATH: /home/user/.helm/cache/archive/httpd-plus-1.0.0+1.tgz

.... (yaml output here)
```

All three charts here (httpd-dash, httpd-plus and httpd-std) are just skeleton charts with only the version being different.

It seems like helm can't recognise the dashed version for some reason.

Here's the snippet from index.yaml generated by helm (have tweaked the url):

```
httpd-dash:
- apiVersion: v1
  appVersion: "1.0"
  created: 2019-03-05T11:20:03.26139635Z
  description: A Helm chart for Kubernetes
  digest: 1ce8dd493cd99eaabdaf1953d8acc700f423f8123225c3020ae0c1386e9f0db7
  name: httpd-dash
  urls:
  - http://local-network-host/httpd-dash-1.0.0-1.tgz
  version: 1.0.0-1
httpd-plus:
- apiVersion: v1
  appVersion: "1.0"
  created: 2019-03-05T11:20:03.261741732Z
  description: A Helm chart for Kubernetes
  digest: 5c9bd9d5ccf65b2092962426285c84c5dd6ab1c747873b3041ca92dbec520518
  name: httpd-plus
  urls:
  - http://local-network-host/httpd-plus-1.0.0+1.tgz
  version: 1.0.0+1
httpd-std:
- apiVersion: v1
  appVersion: "1.0"
  created: 2019-03-05T11:20:03.262010054Z
  description: A Helm chart for Kubernetes
  digest: 72fba7e71c1ecdc63e9a6c9dfaaadf615927fe7080bc8ec2e3ac8bc7e6f88593
  name: httpd-std
  urls:
  - http://local-network-host/httpd-std-1.0.0.tgz
  version: 1.0.0
```

Anyone else encountered this?

**Comment by bacongobbler** [comment] 2019-03-05 20:42
Version numbers with a hyphen in the string are considered pre-release versions. We decided to not install pre-releases unless the `--devel` flag is provided.

Closing as a duplicate of https://github.com/helm/helm/issues/2797. Thanks!

**Closed by bacongobbler** 2019-03-05 20:42 UTC
Labels: question/support

**Comment by huang-jy** [comment] 2019-03-06 07:30
Thanks. This does make sense but can I propose a few changes?

1. When `helm lint`ing, the command should report back saying something along the lines of "this looks like a pre-release version number, you'll need to use `--devel` to install it"
2. When doing `helm search`, only present the pre-release versions if `--devel` is set. *Or* present those ones differently (e.g. with a Asterisk or with a "(P)" or some other kind of identifier). Case in point, in the case of the httpd-dash one, it was presented on `helm search` even though it was "prerelease". So it was misleading me into thinking I could install it without needing to use `--devel`
