### ISSUE TITLE
Helm3.8 needs to use go 1.17 or above? 

### ISSUE THREAD

**Issue by ypf-bendan** [helm/helm#10691] opened 2022-02-19 10:20 UTC
Output of `helm version`:

Output of `kubectl version`:
1.23.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

The go mod file of helm3.8 still suggests version 1.16

**Comment by bacongobbler** [comment] 2022-02-19 14:38
Duplicate of https://github.com/helm/helm/issues/10580.

**Closed by bacongobbler** 2022-02-19 14:38 UTC
