### ISSUE TITLE
helm list panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wangguoyan** [helm/helm#9912] opened 2021-07-06 02:43 UTC
Output of `helm version`:

> version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`:

> Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

> [root@global-master-1 deploy]# helm list
> WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
> WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a992c4]
> 
> goroutine 1 [running]:
> main.newReleaseListWriter(0xc00067e700, 0x15, 0x20, 0x0, 0x0, 0x0)
>         helm.sh/helm/v3/cmd/helm/list.go:160 +0x124
> main.newListCmd.func1(0xc0004ee780, 0x2f4ee98, 0x0, 0x0, 0x0, 0x0)
>         helm.sh/helm/v3/cmd/helm/list.go:111 +0x4ed
> github.com/spf13/cobra.(*Command).execute(0xc0004ee780, 0x2f4ee98, 0x0, 0x0, 0xc0004ee780, 0x2f4ee98)
>         github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a7400, 0xc00049ae00, 0x1, 0xc0006c9f60)
>         github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         github.com/spf13/cobra@v1.1.3/command.go:897
> main.main()
>         helm.sh/helm/v3/cmd/helm/helm.go:80 +0x25b

**Comment by yxxhero** [comment] 2021-07-06 11:18
@wangguoyan Do you remember how many releases you had?

**Comment by mattfarina** [comment] 2021-07-06 13:47
First, I'm marking this as a bug because there was a panic. Those should all be caught and a useful error message should be displayed or the fault should be handled.

@wangguoyan could you please try running `helm --debug -v 10 list` and reproduce the same problem. This will tell Helm to display debug output and tell the underlying kubernetes packages to provide the most verbose output. This will help identify where the issue is happening.

**Comment by wangguoyan** [comment] 2021-07-07 02:18
> @wangguoyan Do you remember how many releases you had?
When I use the code to get realases, I find a special release：
![image](https://user-images.githubusercontent.com/43570712/124689698-8beafe80-df0b-11eb-9373-4d23a4d3edb7.png)

Is this the cause of the problem ? As the same time, I try to  exec `helm get all `  

>  helm get all happy-panda8
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /root/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /root/.kube/config
NAME: happy-panda8
LAST DEPLOYED: Fri Apr 16 08:03:09 2021
NAMESPACE: default
STATUS: deployed
REVISION: 3
TEST SUITE: None
USER-SUPPLIED VALUES:
chart: test-artifact-name
config: ""
path: ""
repository: ""
version: test-appversion1.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1780ff7]
goroutine 1 [running]:
helm.sh/helm/v3/pkg/chartutil.coalesceValues(0x0, 0xc0002a9140)
        helm.sh/helm/v3/pkg/chartutil/coalesce.go:149 +0x37
helm.sh/helm/v3/pkg/chartutil.coalesce(0x0, 0xc0002a9140, 0x1c93220, 0xc0002a8ed0, 0x1c93220)
        helm.sh/helm/v3/pkg/chartutil/coalesce.go:55 +0x35
helm.sh/helm/v3/pkg/chartutil.CoalesceValues(0x0, 0xc0002a8ed0, 0x0, 0x0, 0x0)
        helm.sh/helm/v3/pkg/chartutil/coalesce.go:48 +0x89
main.statusPrinter.WriteTable(0xc0006ba1c0, 0x7f5b15950001, 0x21a4e60, 0xc00013c008, 0xc000753cb0, 0xc000060400)
        helm.sh/helm/v3/cmd/helm/status.go:154 +0xbe8
helm.sh/helm/v3/pkg/cli/output.Format.Write(0x1f1e3e2, 0x5, 0x21a4e60, 0xc00013c008, 0x21de1d0, 0xc0007279c0, 0x1f1c762, 0x4)
        helm.sh/helm/v3/pkg/cli/output/output.go:66 +0x142
main.newGetAllCmd.func2(0xc0005e8780, 0xc0005c9970, 0x1, 0x1, 0x0, 0x0)
        helm.sh/helm/v3/cmd/helm/get_all.go:62 +0x1df
github.com/spf13/cobra.(*Command).execute(0xc0005e8780, 0xc0005c9950, 0x1, 0x1, 0xc0005e8780, 0xc0005c9950)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005faf00, 0xc00038d340, 0x1, 0xc00071ff60)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        helm.sh/helm/v3/cmd/helm/helm.go:80 +0x25b

**Comment by wangguoyan** [comment] 2021-07-07 02:38
After I delete this release, the helm list works normally。

**Comment by yxxhero** [comment] 2021-07-07 03:10
@wangguoyan PR is welcome! can you fix it?

**Comment by wangguoyan** [comment] 2021-07-07 11:47
> @wangguoyan PR is welcome! can you fix it?



> @wangguoyan PR is welcome! can you fix it?

I would  try to fix it

**Comment by wangguoyan** [comment] 2021-07-07 12:01
> > @wangguoyan PR is welcome! can you fix it?
> 
> I will try to fix it

**Comment by yxxhero** [comment] 2021-07-07 12:07
@wangguoyan I already fix it.  you can test it. I will create a PR later.

**Comment by yxxhero** [comment] 2021-11-17 01:10
closed by https://github.com/helm/helm/pull/1349
This pr fix thie issue.

**Closed by yxxhero** 2021-11-17 01:10 UTC
Labels: bug
