### ISSUE TITLE
Helm dependency download the same chart every single time

### ISSUE THREAD

**Issue by Lord-Y** [helm/helm#6893] opened 2019-11-06 17:25 UTC
Output of `helm version`: v2.14.1

Output of `kubectl version`: v1.16.1

Cloud Provider/Platform: GKE

In my helm depencencies, I have the same chart definied 17 times for differents purposes and when building the dependencies, the same charts is downloaded every single time:

`helm dependency build
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "xxxxx" chart repository
...Successfully got an update from the "incubator" chart repository                 
...Successfully got an update from the "banzaicloud-stable" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.                                       
Saving 17 charts                                                                                                                      
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com 
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Downloading xxxxxxxx from repo https://xxxxxxxx.storage.googleapis.com
Deleting outdated charts
`
I think we can have some improvements here. Is that possible?

**Comment by bacongobbler** [comment] 2019-11-06 17:37
duplicate of https://github.com/helm/helm/issues/4618

**Closed by bacongobbler** 2019-11-06 17:37 UTC
Labels: feature
