### ISSUE TITLE
Lot of mess to clean up 

### ISSUE THREAD

**Issue by vikramkhatri** [helm/helm#4673] opened 2018-09-19 18:39 UTC
Platform: `IBM Cloud Private`

```
# helm version --tls
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}
```

kubectl version

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp-ee", GitCommit:"5803c3b1f9422c43a963e0610b3a4cad565e127e", GitTreeState:"clean", BuildDate:"2018-09-04T09:29:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

I am trying to install a big chart. The command is:

```
helm upgrade --tls --install --force --timeout=600 --namespace=metoo -f metoo.yaml metoo metoo.tgz
```

The problem is that it fails and the chart is not created in any failed state with a result that lots of orphan artifacts are created, which I have to clean-up manually. The problem is that it starts 100s of PVCc creation and those I have to delete manually and as we all know Gluster / Heketi are very sensitive and I need to spend more than 30 minutes to clean them. Start the install again and then it fails.
 
I thought that the `--force` is supposed to remove orphan objects this does not seem to be the case.

For example: I cleaned all orphan and I get the error:
```
helm upgrade --tls --install --force --timeout=600 --namespace=metoo -f metoo.yaml metoo metoo.tgz
Release "metoo" does not exist. Installing it now.
Error: release metoo failed: clusterroles.rbac.authorization.k8s.io "metoo-role" already exists
```

I am looking for this `--force` which is like a cop who does nothing. How can I make to work?

**Comment by bacongobbler** [comment] 2018-09-19 19:07
Hey, I can't seem to verify that the version of Tiller you're testing came from something we support. From your `helm version` output, I see this:

```
Server: &version.Version{SemVer:"v2.9.1+icp", GitCommit:"843201eceab24e7102ebb87cb00d82bc973d84a7", GitTreeState:"clean"}
```

And I can't find any information on commit 843201eceab24e7102ebb87cb00d82bc973d84a7, and `v2.9.1+icp` seems like there's custom build metadata so I'm assuming this is a private fork of Helm from IBM Private Cloud. Because it's a fork, we can't really help you out here with specific questions.

Can you please try again with an official release of Tiller?

To answer your particular question:

> I thought that the `--force` is supposed to remove orphan objects this does not seem to be the case.

If this is the first time a release is being installed (as shown in your output), it will not delete resources that are not under Tiller's control. If an *upgrade* fails, however, it will delete those resources.

This was an intentional design decision where we did not want Tiller to take ownership of resources it did not create. After a resource has been created through a release, Tiller assumes ownership over the object and upgrades it accordingly.

**Comment by bacongobbler** [comment] 2018-09-19 19:19
closing as intended via https://github.com/helm/helm/issues/4423#issuecomment-410402213

**Closed by bacongobbler** 2018-09-19 19:19 UTC
Labels: question/support

**Comment by vikramkhatri** [comment] 2018-09-19 22:35
Thank you for the explanation. It helps to know why it was not deleting. One thing that I was observing that when `helm upgrade --tls --install` failed (the chart is really big), the objects that it created - they did not get reused with `--force` even though they were created by the tiller. That is where the time was spent in manual clean-up and especially PVCs - that is the painful part - just to make sure that Gluster / Heketi are still happy. But that is OK - lots of thoughts much have gone into the design.

Finally - after I deleted every objects (that I did not know before like role, cluster binding etc.), - the chart finally did not complain for any existing objects but it did not succeed. The objects are being created and I do not see chart release in `helm ls --tls`. This was the output - 

```
# helm upgrade --tls --install --force --timeout=600 --namespace=metoo --version 2.7.3 -f metoo.yaml metoo metoo.tgz
Release "metoo" does not exist. Installing it now.
NAME:   metoo
E0919 15:36:20.949488   28890 portforward.go:303] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:38069->127.0.0.1:37560: write tcp4 127.0.0.1:38069->127.0.0.1:37560: write: broken pipe
Error: getting deployed release "metoo": release: "metoo" not found
```
But the installation is going on - it takes several hours to complete.

I guess that since this is the private fork - so you may not have an answer. I will circle back with the folks in IBM. Thank you being very responsive.
