### ISSUE TITLE
Helm force with deployment doesn't update code

### ISSUE THREAD

**Issue by sawpresto** [helm/helm#7192] opened 2019-12-09 17:33 UTC
I'm using Helm and the Helm Deploy task in Azure Pipelines (have submitted a bug for a task-specific issue already) to deploy to GKE, and I'm running into an issue where it seems like the code isn't updated in helm even though running `helm ls` shows the latest deployment. It seems like something changed in Helm itself and separately with the task which is causing errors.

1. I have a Helm chart that I deploy to a cluster in the flow of: Make a code change, deploy the Helm chart, make a new code change, update the Helm chart. 
2. In the task, I've needed to enable `--force` for this error (found similar issue at https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/848): 
```
2019-12-09T16:49:04.1783079Z [command]/opt/hostedtoolcache/helm/3.0.1/x64/linux-amd64/helm upgrade --install --values /home/vsts/work/r1/a/_MyHealth.AKS.build-Azure/deploy/my-app-demo/values.release.yml --wait my-app-dev-website /home/vsts/work/r1/a/_MyHealth.AKS.build-Azure/deploy/my-app-demo
2019-12-09T16:49:06.4251436Z Error: UPGRADE FAILED: cannot patch "my-app-dev-website-mhc-front" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-front" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-front", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels` && cannot patch "my-app-dev-website-mhc-data" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-data" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-data", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels` && cannot patch "my-app-dev-website-mhc-back" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-back" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-back", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels`
2019-12-09T16:49:06.4316569Z ##[error]Error: UPGRADE FAILED: cannot patch "my-app-dev-website-mhc-front" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-front" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-front", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels` && cannot patch "my-app-dev-website-mhc-data" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-data" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-data", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels` && cannot patch "my-app-dev-website-mhc-back" with kind Deployment: Deployment.apps "my-app-dev-website-mhc-back" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"mhc-back", "chart":"my-app-demo-0.1.0", "release":"my-app-dev-website", "version":"1.0.0.70"}: `selector` does not match template `labels`
```
3. A little more than a month ago, everything worked fine with the task (including having namespace blank to default to kube-system), but now when running the task, I get this message:
```
19-12-09T16:52:41.7396099Z ##[section]Starting: helm upgrade
2019-12-09T16:52:41.7401406Z ==============================================================================
2019-12-09T16:52:41.7401749Z Task         : Package and deploy Helm charts
2019-12-09T16:52:41.7401872Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2019-12-09T16:52:41.7402525Z Version      : 0.161.0
2019-12-09T16:52:41.7402598Z Author       : Microsoft Corporation
2019-12-09T16:52:41.7402725Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/helm-deploy
2019-12-09T16:52:41.7402809Z ==============================================================================
2019-12-09T16:52:41.9846029Z [command]/opt/hostedtoolcache/helm/3.0.1/x64/linux-amd64/helm upgrade --install --force --values /home/vsts/work/r1/a/_MyApp.AKS.build-Azure/deploy/my-app-demo/values.release.yml --wait my-app-dev-website /home/vsts/work/r1/a/_MyApp.AKS.build-Azure/deploy/my-app-demo
2019-12-09T16:53:24.4964174Z client.go:399: Replaced "my-app-dev-website-mhc-back" with kind Deployment for kind Deployment
2019-12-09T16:53:24.4964600Z Release "my-app-dev-website" has been upgraded. Happy Helming!
2019-12-09T16:53:24.4966084Z client.go:399: Replaced "my-app-dev-website-mhc-front" with kind Deployment for kind Deployment
2019-12-09T16:53:24.4966463Z NAME: my-app-dev-website
2019-12-09T16:53:24.4967442Z client.go:399: Replaced "my-app-dev-website-mhc-data" with kind Deployment for kind Deployment
2019-12-09T16:53:24.4967594Z LAST DEPLOYED: Mon Dec  9 16:52:43 2019
2019-12-09T16:53:24.4967972Z NAMESPACE: default
2019-12-09T16:53:24.4968161Z STATUS: deployed
2019-12-09T16:53:24.4968377Z REVISION: 5
2019-12-09T16:53:24.4968534Z NOTES:
2019-12-09T16:53:24.4968750Z 1. Get the application URL by running these commands:
2019-12-09T16:53:24.4968977Z      NOTE: It may take a few minutes for the LoadBalancer IP to be available.
2019-12-09T16:53:24.4969690Z            You can watch the status of by running 'kubectl get --namespace default svc -w my-app-dev-website-my-app-demo'
2019-12-09T16:53:24.4970743Z   export SERVICE_IP=$(kubectl get svc --namespace default my-app-dev-website-my-app-demo -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
2019-12-09T16:53:24.4971056Z   echo http://$SERVICE_IP:80
2019-12-09T16:53:24.5042118Z ##[error]client.go:399: Replaced "my-app-dev-website-mhc-back" with kind Deployment for kind Deployment
```
Ignoring the error message, I assumed it deployed correctly anyway, and looking at the releases in helm, it shows that deployment 5 is in status deployed but the code isn't updated at all (even after waiting a few minutes to make sure).

The only way to work around this is to delete the release before every deployment in Helm but that will reset everything too.

Is there something I'm missing with this or did something change recently with Helm for force?

Output of `helm version`: version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:31:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bacongobbler** [comment] 2019-12-09 17:37
duplicate of #7082

**Closed by bacongobbler** 2019-12-09 17:37 UTC

**Comment by sawpresto** [comment] 2019-12-09 17:51
@bacongobbler Thanks for pointing to the open feature. As a temporary workaround, if I uninstall Helm 3 and install Helm 2, should that work to avoid this specific issue?

**Comment by bacongobbler** [comment] 2019-12-09 17:54
Unfortunately, the storage backends are incompatible with each other. If you're starting from scratch, it's possible. If you want to take a crack at implementing the `--recreate` flag for Helm 3, that would be a good contribution to get started since that'd directly impact your work.
