### ISSUE TITLE
Helm v2.14.3 does not support K8s 1.16.0

### ISSUE THREAD

**Issue by alanpeng** [helm/helm#6458] opened 2019-09-19 04:53 UTC
Output of `helm version`:

Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm

Error:
[root@master01 ~]# helm init
$HELM_HOME has been configured at /root/.helm.
Error: error installing: the server could not find the requested resource

**Comment by JavierAbrego** [comment] 2019-09-19 10:07
the same is happening to me

**Comment by oke-py** [comment] 2019-09-19 10:08
the same is happening for minikube v1.3.1.

**Comment by PierreF** [comment] 2019-09-19 10:10
It probably happen due to the deployment using beta extension:
```
$ helm init --service-account tiller --wait --debug
apiVersion: extensions/v1beta1
kind: Deployment
[...]
```

Kubernetes 1.16 removed beta and Deployment should be created with "apiVersion: extensions/v1"

**Comment by hickeyma** [comment] 2019-09-19 10:25
Thanks @alanpeng for raising this. Going to close this as duplicate of #6374.

**Closed by hickeyma** 2019-09-19 10:25 UTC
