### ISSUE TITLE
CRDs get deleted when moving them from templates/ to crds/

### ISSUE THREAD

**Issue by John-Athan** [helm/helm#8163] opened 2020-05-19 14:06 UTC
## Description
Assume a CRD that is first declared as a template. This CRD then gets moved to the crds directory (with all templating removed). Now, when doing a Helm upgrade, all CRDs will get removed. If many custom resources are connected to this CRD, the upgrade will basically shut most of the cluster down. Is this intentional? Is there a way to work around this?

## Steps to reproduce
1. Install a chart that declares CRDs using templating, for example [Strimzi Kafka Operator](https://github.com/strimzi/strimzi-kafka-operator/tree/master/helm-charts)
2. Move the CRDs to the crds/ folder
3. Do a helm upgrade

## Versions
Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

**Comment by bacongobbler** [comment] 2020-05-19 14:22
If a resource is removed from the templates directory, the resource is removed. This seems in line with the expected behaviour.

**Comment by bacongobbler** [comment] 2020-05-19 15:26
Duplicate of https://github.com/helm/helm/issues/7279. See the following for more information:

https://github.com/helm/helm/issues/7279
https://github.com/helm/helm/pull/7320
https://github.com/helm/helm/issues/7505
https://github.com/helm/helm/pull/7571

**Closed by bacongobbler** 2020-05-19 15:26 UTC
