### ISSUE TITLE
helm v3 unable to force recreate immutable resource

### ISSUE THREAD

**Issue by tatchiuleung** [helm/helm#7168] opened 2019-12-05 19:48 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

In Helm v2, I used to be able to do `helm upgrade --force` to upgrade helm charts with immutable resources, such as Job. For example, if the docker image tag is changed, the helmv2 upgrade with `--force` will recreate the resource.

Now in Helm v3, I can no longer do this anymore. It says the Job.template is immutable and Helmv3 cannot force the upgrade.

**Comment by tatchiuleung** [comment] 2019-12-05 19:49
The error in helm v3 is
```
Error: UPGRADE FAILED: an error occurred while cleaning up resources. original upgrade error: cannot patch "job-test-0" with kind Job: Job.batch "job-test-0" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"
..........
```

**Comment by tatchiuleung** [comment] 2019-12-05 19:50
The workaround is to run `helm uninstall <release>` and deploy, but this involves manual intervention which I didn't have to in helm v2.

**Comment by bacongobbler** [comment] 2019-12-05 20:07
duplicate of https://github.com/helm/helm/issues/7082

**Closed by bacongobbler** 2019-12-05 20:07 UTC
