### ISSUE TITLE
[feature-request] Introduce `chart://` url scheme for loading extra values files from inside the chart

### ISSUE THREAD

**Issue by philomory** [helm/helm#11282] opened 2022-08-28 20:47 UTC
Although only the file `values.yaml` within the chart has any special meaning, it is possible to include other arbitrary files inside the packaged chart (and indeed by default, in the absence of a `.helmignore` file, _all_ files in the chart directory are included in the packaged chart). By default, these extra files have no purpose, but they can be extracted by end users who `helm pull` the packaged chart and then untar it.

Among other things, this mechanism can be used to provide extra values files that group several related changes together. For example, the `linkerd-control-plane` chart includes a file, `values-ha.yaml`, that includes a variety of non-default values which, when used together, configure Linkerd in a highly-available manner. However, to make use of `values-ha.yaml`, the end user has to `helm pull` the chart, untar it, and then manually pass the local path to `values-ha.yaml` to their `helm install` or `helm upgrade` invocation.

I propose that Helm be adjusted to accept URLs with the scheme `chart://` when passed to `--values`/`-f` flag of `helm install`, `helm upgrade`, `helm template`, and other similar commands, to allow passing as a values file a file which is bundled within the chart itself; for example, `helm install linkerd-control-plane linkerd/linkerd-control-plane -f chart://values-ha.yaml` would use the values from the `values-ha.yaml` file inside of the `linkerd-control-plane` chart.

This option would have several advantages over the currently available methods:
1. It would play more nicely with other tools such as Helmfile, which work with Helm charts but don't necessarily expose easy ways to run arbitrary shell commands in the midst of their Helm automation.
2. It would be easier for chart authors to document for end users.
3. It would simply be more convenient than doing everything manually.

**Comment by joejulian** [comment] 2022-11-12 07:01
closing as duplicate of https://github.com/helm/helm/issues/4782

**Closed by joejulian** 2022-11-12 07:01 UTC
Labels: feature
