### ISSUE TITLE
Helm exit silently if kube config is directory

### ISSUE THREAD

**Issue by StupidScience** [helm/helm#7271] opened 2019-12-19 15:30 UTC
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Make directory `~/.kube/config`. Try to run even just `helm version`. Got exit code 1 without any errors.

For example `kubectl` provide the following error message:
`error: error loading config file "~/.kube/config": read ~/.kube/config: is a directory`

**Comment by hickeyma** [comment] 2019-12-19 15:51
Error is shown in debug as follows:

```console
$ export HELM_DEBUG=true

$ helm3 version
helm.go:71: [debug] error loading config file "/root/.kube/config": read /root/.kube/config: is a directory
```

Closing as a duplicate of #6863

**Comment by hickeyma** [comment] 2019-12-19 15:53
Duplicate of #6863

**Closed by hickeyma** 2019-12-19 15:53 UTC
Labels: bug
