### ISSUE TITLE
Question: Helm multitenant support

### ISSUE THREAD

**Issue by roldancer** [helm/helm#4163] opened 2018-06-02 18:24 UTC
Hi All, I would like to know if Helm support chart installation on different namespaces based on the client permission, we have several namespaces, each namespace has an admin user.

Any idea?

Thanks.

**Comment by PureWhiteWu** [comment] 2018-06-07 04:57
You can install multi tillers, one per namespace.
That's the multitenant solution for me.

**Comment by SlickNik** [comment] 2018-06-07 06:55
Hi @roldancer -- good question! Like @PureWhiteWu mentions above, one common way to achieve this is by installing a separate tiller for each namespace. The blog post at http://technosophos.com/2017/11/20/securing-helm.html (esp. point 4) talks a little about how to go about doing this.

Let us know if you have any further questions!

**Comment by PureWhiteWu** [comment] 2018-06-07 06:58
@SlickNik Thank you for confirming this!

**Comment by roldancer** [comment] 2018-06-08 19:12
Hi @SlickNik @PureWhiteWu I think that having a tiller for each namespace is ok for a cluster with few namespaces, but if you have 300 (my case) or more namespaces it would be much more efficient (memory usage) to have just one tiller for all the kubernetes cluster and that's from my point of view multitenant support.

Thanks.

**Comment by PureWhiteWu** [comment] 2018-06-08 19:47
If you need 300 or more namespaces, then you must have 300 or more other services which all namespaces have. Tiller will only use a little memory, which is not  worth mentioning comparing with your other services.

**Comment by bacongobbler** [comment] 2018-06-08 19:48
@roldancer the blog post @SlickNik linked to mentions how to do this, though it doesn't explicitly explain how to grant Tiller access to deploy to multiple namespaces. The blog post demonstrates how you can deploy Tiller to one namespace (`staging-tiller`) while managing resources in another namespace (`staging`), but you can add as many namespaces you wish Tiller can deploy to by granting multiple Roles and RoleBindings to the tiller service account.

[The RBAC documentation around deploying Tiller in one namespace, restricted to deploying resources in another namespace](https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-in-another-namespace) can be expanded by taking the example Role and RoleBindings and creating one Role and one RoleBinding for each namespace you want your tiller instance to deploy to, binding the RoleBinding to the service account Tiller is bound to.

It's a little clumsy, but hey, that's Kubernetes RBAC for ya ;)

Does that help answer your question?

**Comment by bacongobbler** [comment] 2018-06-08 20:01
Here's an expanded example: deploying Tiller to `foo-system` with the ability to deploy resources in namespaces foo, bar, car and star:

```
$ kubectl create namespace foo-system
namespace "foo-system" created
$ kubectl create serviceaccount tiller --namespace foo-system
serviceaccount "tiller" created
```

Then, let's create the Roles and RoleBindings.

In `tiller-roles.yaml`:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: foo
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: bar
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: car
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager
  namespace: star
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
```

```
$ kubectl create -f tiller-roles.yaml
role "tiller-manager" created
role "tiller-manager" created
role "tiller-manager" created
role "tiller-manager" created
```

In `tiller-rolebindings.yaml`:

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: foo
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: bar
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: car
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-binding
  namespace: star
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: foo-system
roleRef:
  kind: Role
  name: tiller-manager
  apiGroup: rbac.authorization.k8s.io
```

```
$ kubectl create -f tiller-rolebindings.yaml
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
rolebinding "tiller-binding" created
```

Follow through the rest of https://docs.helm.sh/using_helm/#example-deploy-tiller-in-a-namespace-restricted-to-deploying-resources-in-another-namespace as described in the docs.

Hope this helps!

**Comment by roldancer** [comment] 2018-06-09 08:57
Hi @bacongobbler many thanks for that information !!!! if I follow your suggested role/binding strategy I would have something like this:

1) A tiller's service account with role tiller-manager with complete access to these namespaces:
     - bar
     - car 
     - star

2) I have the following namespaces owners/admin
     - User A has a "Admin" role for namespace "bar"
     - User B has a "Admin" role for namespace "car"
     - User C has a "Admin" role for namespace "star"
    
Question:

How can you ensure that user "A" using the helm cli is not allowed to deploy charts on namespaces "car" and "star" ?
 
Thanks.

**Comment by bacongobbler** [comment] 2018-09-05 22:53
That permission is locked down by tiller. If User A using the Helm CLI asks to deploy resources in namespace `car` and Tiller does not have the right permissions to deploy in namespace `car`, Tiller will inform the user that it cannot deploy resources in namespace `car`.

I'm going to close this ticket as answered but please feel free to re-open if you have more questions that the documentation can't provide. Thanks! :)

**Closed by bacongobbler** 2018-09-05 22:53 UTC
Labels: question/support

**Comment by pc-rshetty** [comment] 2018-10-12 16:56
I have 1 tiller for multiple namespaces. Which i really like. But the problem is when i see the history it never differentiates which namespace i have deployed it to . so lets say i want to deploy istio on 2 namespaces QA and DEV it is possible to deploy but history shows this 

`helm history istio --tls --tls-ca-cert ca.cert.pem --tls-cert helm.cert.pem --tls-key helm.key.pem --tiller-namespace tiller-world
REVISION	UPDATED                 	STATUS  	CHART      	DESCRIPTION
1       	Tue Oct  9 22:43:45 2018	DEPLOYED	istio-1.0.1	Install complete`

**Comment by ramukima** [comment] 2019-05-14 17:25
@bacongobbler Following your suggestions, I am unable to enforce "How can you ensure that user "A" using the helm cli is not allowed to deploy charts on namespaces "car" and "star" ?"... 

Since a single instance of Tiller has been given permissions to deploy in "bar, car, star" namespace, when user "A" (who should only be allowed to deploy things in namespace "bar") runs "helm install nginx --namespace car --tiller-namespace helm-system", Tiller in helm-system namespace does not validate whether 'user A' is allowed to deploy charts in namespace "car" or not.

Am I missing something here ?
