### ISSUE TITLE
Feature Request: Templates should detect if tiller is running on minikube

### ISSUE THREAD

**Issue by marcosdiez** [helm/helm#5050] opened 2018-12-12 19:51 UTC
Output of `helm version`:
`Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
`
Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`Minikube`

It would be great if templates could know if their node is minikube or not. Something like `.Capabilities.TillerVersion.NodeName`. This may seem evil at first, but when developing locally one may want to use a special NFS server or a special DB or something else different that on a real Kubernetes cluster.

Or maybe a way for the template to query an existing configmap on the cluster itself.

**Comment by bacongobbler** [comment] 2018-12-12 20:55
Dupe of https://github.com/helm/helm/issues/2055

**Closed by bacongobbler** 2018-12-12 20:55 UTC
