### ISSUE TITLE
helm list -n Parameter failure

### ISSUE THREAD

**Issue by qist** [helm/helm#5949] opened 2019-06-27 08:18 UTC
Output of `helm version`: version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube 
helm list -n Parameter failure
[root@jenkins linux-amd64]#  helm list -n kube-system
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART         
redis   default         1               2019-06-27 16:03:38.082153822 +0800 CST deployed        redis-ha-2.0.1

**Comment by bacongobbler** [comment] 2019-06-27 09:22
What is the expected output? I can't tell from the information provided what I should expect to see, as well as how to reproduce the issue. If you can provide that information then perhaps we can better understand the problem you are seeing.

**Comment by bacongobbler** [comment] 2019-06-27 09:23
Oh. I see now.

Closing as a duplicate of #5628. Please make sure to check the issue queue first before opening an issue. Thanks.

**Closed by bacongobbler** 2019-06-27 09:23 UTC
