### ISSUE TITLE
Providing CA for Kubernetes cluster

### ISSUE THREAD

**Issue by AdarShaked** [helm/helm#8883] opened 2020-10-13 14:58 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-30T19:31:27Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: dial tcp 34.123.57.46:443: i/o timeout

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I want to pass CA for using  TLS with my kubernetes cluster when executing `helm install`
There is such a flag?
I understand that `--ca-file` is only for repos download?

**Comment by mattfarina** [comment] 2020-10-13 15:37
Helm will use your kubeconfig. It will will try the default location on your system where `kubectl` keeps it. Otherwise you can pass a location to a file using a flag. If you run `helm help install` you will find a list of global flags you can use.

The CA handling is part of that configuration. This way it works with existing tools that configure your system for a kubernetes cluster.

**Comment by AdarShaked** [comment] 2020-10-13 15:59
Lets say I don't have kubeconfig.
What is the flag that i can pass  ca path for TLS with kubernetes cluster?
There is such a flag?can you point on it ?
 I uderstood that `--ca-file` is not for kubernetes cluster TLS . only for chart downloading.
Didnt find something helpful with `helm help install`

**Comment by bacongobbler** [comment] 2020-10-13 17:06
What you're looking for is a `--kube-ca-file` flag, which does not exist currently. @mattfarina's suggestion of setting it in your kube config file will work around this issue.

Marking this as a feature request, as I've seen several tickets asking for this particular feature (#8549 being one such example).

**Comment by AdarShaked** [comment] 2020-10-13 17:20
Thanks it will be awesome to have!

**Comment by bacongobbler** [comment] 2020-10-13 17:58
closing as a duplicate of https://github.com/helm/helm/issues/8487.

**Closed by bacongobbler** 2020-10-13 17:58 UTC
Labels: feature
