### ISSUE TITLE
helm install fails customresource definition already exists

### ISSUE THREAD

**Issue by movikbence** [helm/helm#5964] opened 2019-07-03 07:05 UTC
I am trying to deploy two instances of a service in separate namespaces in a kubernetes cluster.
The helm chart contains CustomResourceDefinition, which as I know can not be deployed in a namespace, just the custom resource as described here:
https://stackoverflow.com/questions/51424073/why-are-kubernetes-custom-resource-definitions-cluster-wide
However the first installation succeeds, the second fails with: 

Error: release service failed: customresourcedefinitions.apiextensions.k8s.io "ingressroutes.contour.heptio.com" already exists

I tried to deploy it again (after helm del --purge service), and it succeeds by redeploying the same exact CRD.
I understand that the the CRDs are clusterwide resources, but somehow I would like both of the services to be deployed with helm.

I would like to know if that is the expected behaviour from helm, that it fails if the CRD which I would like to add already exists.

An another issue from the perspective of my use-case:
When I delete one of the services, the CRD will also be deleted from the k8s cluster, so the other service will work from that point without CRD, too.

I have another question about the CRD namespace (which does not exist in theory), when I check the deployed CRD I see this:

kubectl describe crd tlscertificatedelegations.contour.heptio.com
Name:         tlscertificatedelegations.contour.heptio.com
Namespace:  
So there is a namespace field, but anyway I can not edit it, then why is it there?

thanks in advance

Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.2", GitCommit:"83d618b08677094566ad3b4967be0f96b0e53b78", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-12T09:58:44Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Bare Metal

**Comment by bacongobbler** [comment] 2019-07-03 07:08
Seems like a good discussion point for #5871. Use cases such as this one are being discussed in that ticket. We'd love to hear your thoughts and to help weigh in there.

I'm going to close this as a duplicate of that issue. If you wouldn't mind weighing in on the discussion, that would be great. Thanks!

**Closed by bacongobbler** 2019-07-03 07:08 UTC

**Comment by bacongobbler** [comment] 2019-07-03 07:12
see also https://github.com/helm/helm/issues/5935
