### ISSUE TITLE
How to provide files to a subchart from a parent

### ISSUE THREAD

**Issue by macon** [helm/helm#4994] opened 2018-12-02 18:36 UTC
Output of `helm version`:
`
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
`

Output of `kubectl version`:
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Minikube

I'm using postgresql as a subchart with the following `requirements.yaml`

```yaml
dependencies:
  - name: postgresql
    version: 2.7.6
    repository: https://kubernetes-charts.storage.googleapis.com/
```
Posgresql chart allows us to add db initialisation scripts to the chart folder `files/docker-entrypoint-initdb.d`. I want to provide these files from the parent chart but the `files/docker-entrypoint-initdb.d` seems to be in the context of the child chart (which is an archive in my parent's `/charts` folder). If I add a `files/docker-entrypoint-initdb.d` to my parent chart the files don't get picked up.

Is there any way to do this without fetching and unpacking the postgresql subchart in my parent's chart?

**Comment by victornoel** [comment] 2018-12-06 14:04
See #1892 for a related issue (without solution)

**Comment by melissapalmer** [comment] 2019-02-26 20:05
@macon  did you find a solution as to how to do this at all? Thanks in advance.

**Comment by bacongobbler** [comment] 2019-12-09 20:04
duplicate of #1892.

**Closed by bacongobbler** 2019-12-09 20:04 UTC
Labels: question/support
