### ISSUE TITLE
Getting the NOTES.txt data from a subchart

### ISSUE THREAD

**Issue by dfee** [helm/helm#2751] opened 2017-08-02 00:37 UTC
Let's say I've got a dependency on `postgresql`:
```
dependencies:
  - name: postgresql
    version: 0.7.1
    repository: https://kubernetes-charts.storage.googleapis.com
```

If I install my chart (`helm install .`), it doesn't seem possible to get the (rather helpful) notes from the postgresql subchart. I.e. `helm status my-chart` does not list the notes for `postgresql`, only what's listed in `templates/NOTES.txt`.

Is there a workaround?

**Comment by jeff-knurek** [comment] 2017-08-02 12:27
I'm annoyed by this apparent _"lack of functionality"_ too. 
I also couldn't find any solutions in the helm-users Slack channel, but I did find this PR https://github.com/kubernetes/helm/pull/1409 that seemed to make it so only the parent's NOTES is shown.

**Comment by jascott1** [comment] 2017-08-03 18:13
Related to (but not a duplicate of) #2742 feature request "refetch notes".

**Comment by iamrandys** [comment] 2017-11-01 14:08
👍

**Comment by sylus** [comment] 2017-12-19 02:38
Tripped me up as well today, glad to know is an issue :)

**Comment by kiich** [comment] 2018-01-05 13:36
+1 for this issue - we have our "main" chart which all of our charts depend on and would be good to just change the NOTES.txt in that one place.

**Comment by bacongobbler** [comment] 2018-04-27 15:48
We'd happily accept a PR if someone wants to take this on. This would be a great feature to have, and it shouldn't be too much work. I'll leave this one open as an open opportunity for someone who wants to get their feet wet with Helm.

**Comment by mattfarina** [comment] 2018-05-16 23:30
@teaguecole Did you start working on this one?

**Comment by teaguecole** [comment] 2018-05-16 23:33
@mattfarina I have not... I was going to, but I probably have taken too much on my plate from another SIG... If you want to snatch it from me, you can take it.  Thanks for reminding me, I was going to release it to the wild in case others want to jump on it.

**Comment by teaguecole** [comment] 2018-05-16 23:34
I am not opposed to working on it, I would just need guidance as it would be my first PR and I am not familiar with the code base.

**Comment by jgleonard** [comment] 2018-05-31 12:38
@bacongobbler can you take a look at #4088 for this?  Realizing that the patch is in Tiller, it may need some other changes for Helm3... Thoughts?

**Closed** 2019-01-16 17:16 UTC
Labels: feature, good first issue

**Comment by jgleonard** [comment] 2019-09-26 18:54
Looks like this one needs porting to v3, not sure how to add a label...

**Comment by hickeyma** [comment] 2019-09-27 10:51
Ported in #6512

**Comment by abdennour** [comment] 2022-08-17 03:42
Any news?

**Comment by abdennour** [comment] 2022-08-17 03:46
FYI ! 
Got it! You have to use `--render-subchart-notes` when you run `helm install` or `helm upgrade`. Then, when you run `helm get note` or `helm status`, it should render notes of subcharts as well.
