### ISSUE TITLE
helm 3.0.0-beta4: --debug flag gives error when trying to install non-existing chart

### ISSUE THREAD

**Issue by invidian** [helm/helm#6618] opened 2019-10-09 11:48 UTC
Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output:
```
$ helm install test foo/bar
Error: failed to download "foo/bar" (hint: running `helm repo update` may help)
$ helm install test foo/bar --debug
install.go:148: [debug] Original chart version: ""
Error: repo foo not found
helm.go:81: [debug] repo foo not found
helm.sh/helm/v3/pkg/downloader.pickChartRepositoryConfigByName
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:308
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:203
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/home/circleci/helm.sh/helm/pkg/action/install.go:664
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:160
main.newInstallCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/install.go:115
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

I couldn't find existing issue for that, hence new issue. Feel free to close if that's a duplicate of something already reported.

**Comment by invidian** [comment] 2019-10-09 11:58
`show` gives pretty much the same result (that's the same code, but point is that more debug functionality can be affected by this):
```
$ helm show foo/bar
Error: failed to download "foo/bar" (hint: running `helm repo update` may help)
$ helm show foo/bar --debug
Error: repo foo not found
helm.go:81: [debug] repo foo not found
helm.sh/helm/v3/pkg/downloader.pickChartRepositoryConfigByName
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:308
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:203
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	/home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:87
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	/home/circleci/helm.sh/helm/pkg/action/install.go:664
main.newShowCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/show.go:61
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by karuppiah7890** [comment] 2019-10-09 16:34
@invidian Do you mean to say that `install` should show the same and correct error as debug? I do understand that `foo` is an invalid repo

Also, this issue exists in helm v2 too. Just now tried it out. Will look into the discrepancy

**Comment by karuppiah7890** [comment] 2019-10-09 16:59
Thanks for the feedback! To start with, I would like to get the error
message discrepancy fixed. About UX, and logs about what's happening or
what's being tried out by the program, yes, we can add more. I'm sure
there's reason as to why it's currently like the way it is, very minimal
and not too verbose.

I would like to see some more people put their thoughts here before
implementing anything

@hickeyma @bacongobbler

**Comment by bacongobbler** [comment] 2019-10-30 22:07
From looking at the code, this is working as intended. `helm --debug` prints a stack trace when an error is detected to display where exactly the error came from. This is for debugging purposes, and it is intended to work that way.

We could eventually consolidate the `-v` and `--debug` flags together, in which case `-v 1` could be used for slight more informational messages than what is currently available with `--debug`. I don't see `--debug` becoming less chatty; in fact it's much more likely that if we consolidate `--debug` and `-v`'s code bases, `--debug` will likely become equivalent to a `helm -v 5` and would continue printing stack traces to stdout

Closing this for now as a wontfix for the `--debug` flag. We can consider merging --debug and -v in the future, but that would be a separate discussion than the discussion brought up here. I'll open a new ticket.

Thanks!

**Closed by bacongobbler** 2019-10-30 22:07 UTC
Labels: bug, v3.x

**Comment by invidian** [comment] 2019-10-30 22:09
All right. Maybe it could be documented somewhere, so it's not a surprise for other users too?
