### ISSUE TITLE
Proposal: support customized labels for storage like secret, configmap

### ISSUE THREAD

**Issue by liuming-dev** [helm/helm#8098] opened 2020-05-12 13:16 UTC
This proposal is inspired by issue #7007。There are probably some cases that users what to  customize the labels of secret/configmap for convenient application management。

For one release the storage labels are set from the installation, and the labels will be retrieved where upgrading or rollback to keep labels consistency. Therefore, adding `--set-label`( `-l` in short) flag to `install` command。

**Comment by bacongobbler** [comment] 2020-05-12 16:16
Closing as a duplicate of #7007. Please keep the discussion in one ticket. That way we don't have to track the discussion over several tickets. Thanks.

**Closed by bacongobbler** 2020-05-12 16:16 UTC
Labels: feature, proposal
