### ISSUE TITLE
Helm 3.x on Windows does not provide any output

### ISSUE THREAD

**Issue by miracle152004** [helm/helm#7268] opened 2019-12-19 13:21 UTC
Output of `helm version`: nothing (should display 3.0.2)

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}

Installing an using Helm3 on Windows does not return any output. (i.e. version, help, list, etc.)
Using Helm2 it works and displays output accordingly.

Could you please help.
Thanks

Best regards
miracle152004

**Comment by perezjasonr** [comment] 2019-12-19 22:52
helm 3.02 linux-amd64 on linux is also not providing any input. i tried version, help etc...

**Comment by bacongobbler** [comment] 2019-12-20 01:19
possibly related to https://github.com/helm/helm/issues/6863.

**Comment by bacongobbler** [comment] 2019-12-20 01:20
What happens if you add the `--debug` flag?

**Comment by miracle152004** [comment] 2019-12-20 13:23
yeah is the same issue:
D:\Temp>helm3.exe --debug
helm.go:71: [debug] error loading config file "[Userdirectory]/.kube/config": yaml: line 6: found a tab character that violates indentation

**Comment by perezjasonr** [comment] 2019-12-20 13:53
Thank you, that was essentially the issue. Running with --debug got me "permission denied"
on my kubeconfig file. So almost the same thing. I woulda never guessed permission denied since I thought that would show up for sure. I thought the binary was just being unresponsive.

**Comment by bacongobbler** [comment] 2019-12-20 15:08
closing as a duplicate of #6863.

**Closed by bacongobbler** 2019-12-20 15:08 UTC
