### ISSUE TITLE
Template file parsing failed with dictionnary name including '-' character

### ISSUE THREAD

**Issue by ruddy32** [helm/helm#7353] opened 2020-01-08 17:51 UTC
Output of `helm version`: 3.0.2

Hi,

Go template fail when using variable from dictionary including '-' in name.

Helm output :

> in ./helmfile.yaml: failed processing release observations-sbo: helm exited with status 1:
>   Error: Failed to render chart: exit status 1: coalesce.go:165: warning: skipped value for annotations: Not a table.
>   coalesce.go:165: warning: skipped value for annotations: Not a table.
>   coalesce.go:165: warning: skipped value for annotations: Not a table.
>   coalesce.go:165: warning: skipped value for annotations: Not a table.
>   Error: template: ... bad character U+002D '-'

Template line :

> observations.couchdb.url=https://{{ printf "%s-svc-couchdb-esp" .Release.Name | trunc 63 | trimSuffix "-" }}.{{ printf "%s" .Release.Namespace | trunc 63 | trimSuffix "-" }}.svc:{{ .Values.**couchdb-esp**.service.externalPort }}

Regards,
Ruddy

**Comment by bacongobbler** [comment] 2020-01-09 16:30
closing as a duplicate of https://github.com/helm/helm/issues/2192.

**Closed by bacongobbler** 2020-01-09 16:30 UTC
