### ISSUE TITLE
Helm3 beta3 template require cluster access (regression from helm3 beta2)

### ISSUE THREAD

**Issue by MichaelVL** [helm/helm#6522] opened 2019-09-28 09:34 UTC
Running the following command:

  helm template nfs-storage nfs-server-provisioner --repo https://kubernetes-charts.storage.googleapis.com

 results in the error:

  Error: Kubernetes cluster unreachable

The helm3 beta2 version did not require cluster access.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
NAN (not present)

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NAN ('helm template' should run locally)

**Comment by marckhouzam** [comment] 2019-09-28 10:30
Thanks for the report.
This is a duplicate of #6417 (which is a dup of #6404).
They have very recently been fixed by #6425.

**Closed** 2019-09-28 18:45 UTC
