### ISSUE TITLE
Proposal: repair command to reset resources have been changed outside helm

### ISSUE THREAD

**Issue by joelanford** [helm/helm#6280] opened 2019-08-24 06:27 UTC
If a release's resources are changed outside of Helm, it is desirable to repair them, effectively resetting them back to the latest release manifest without actually performing an upgrade or otherwise changing the release state. This has the nice property of being idempotent.

I found #3805, saw that `helm upgrade` was updated to use a strategic three-way merge in #6124, and remembered that I had discussed the `repair` use case with @bacongobbler a few months ago.

I've written a plugin based on the `action` Helm 3 package that implements this feature (see https://github.com/joelanford/helm3-repair-plugin). We use a similar approach for the Helm-based operator in Operator SDK, but it seems like this `repair` command could be widely applicable to all Helm users.

It works by fetching the latest release and iterating its resources. For each resource it:
1. Fetches the current resource from the cluster
2. If not present, it re-creates it from the manifest.
3. If present, it generates a three-way merge patch.
    - Base: manifest resource
    - Target: manifest resource
    - Current: fetched resource
4. If the patch is empty, there's nothing to do, so no write request is made to the k8s API.
5. If the patch is non-empty, it applies the patch to the resource.

@sboardwell is this what you had in mind with [this comment](https://github.com/helm/helm/issues/3805#issuecomment-477370276)?

What do folks think about the approach?

**Comment by sboardwell** [comment] 2019-09-02 16:13
Hi @joelanford, sorry, got caught up in other things. Yes, this is what I had in mind, although I would like to see a `--dry-run` or `--report-only` flag to identify the changes without repairing them. This  would allow people to actually see what was wrong before repairing (maybe the change is a legitimate one that needs to be reflected in the `values.yaml` for the next deployment)

**Comment by joelanford** [comment] 2019-09-04 18:03
@sboardwell No worries! Thanks for the feedback. A `--dry-run` flag makes total sense, so I just added support for that. Now the plugin will always print a unified diff and will skip applying the patch when `--dry-run` is `true`.

**Comment by sboardwell** [comment] 2019-09-04 20:19
@joelanford 
Brilliant, thanks a lot. As a side note, does anyone know how far Helm3 is away from GA or even beta, or how stable the current alpha is?

**Comment by bacongobbler** [comment] 2019-09-04 23:04
The first beta release of Helm 3 was released a little over a week ago. We've since released helm 3.0.0-beta.2, and we may be releasing beta.3 next week. 3.0.0 will be released when we feel comfortable that we've fixed all the regressions, ported over features from Helm 2 ever since we forked from master, and when we have a well-tested migration plan in place. That may take some time.

**Comment by bacongobbler** [comment] 2020-08-14 20:15
As I understand it, this use case can be handled already with `helm rollback` as it will reset back to the target state, even if objects have been modified with `kubectl edit`. If you want to *really* force an update, use `helm rollback --force`.

More info here: https://helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches

Hope this helps!

**Closed by bacongobbler** 2020-08-14 20:15 UTC
Labels: proposal, v3.x
