### ISSUE TITLE
docker-for-mac - cannot parse dnsName "kubernetes.default.svc." on helm init

### ISSUE THREAD

**Issue by esetnik** [helm/helm#3873] opened 2018-04-11 17:04 UTC
❯ helm init
Creating /Users/x/.helm
Creating /Users/x/.helm/repository
Creating /Users/x/.helm/repository/cache
Creating /Users/x/.helm/repository/local
Creating /Users/x/.helm/plugins
Creating /Users/x/.helm/starters
Creating /Users/x/.helm/cache/archive
Creating /Users/x/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /Users/x/.helm.
Error: error installing: Post https://localhost:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: tls: failed to parse certificate from server: x509: cannot parse dnsName "kubernetes.default.svc."

Output of `helm version`:
❯ helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Docker-for-mac Version 18.04.0-ce-rc2-mac61 (23890)

Likely related to:

- https://github.com/istio/istio/issues/4847
- https://github.com/kubernetes/ingress-nginx/issues/2188

**Comment by bacongobbler** [comment] 2018-04-11 17:19
We've seen this across the ecosystem. I'd suggest using minikube instead for the time being.

**Comment by jonaseck2** [comment] 2018-04-12 16:56
Downgrading to 18.03.0-ce-mac58 resolves the issue:
```
brew cask uninstall docker-edge
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-versions/36c418b5e6fdcb823b8a06d698bbf6d7d4f38ee0/Casks/docker-edge.rb
```

**Comment by lox** [comment] 2018-04-14 01:54
Is there a https://github.com/docker/for-mac/issues for this?

**Comment by outsideris** [comment] 2018-04-14 06:40
I download [18.03.0-ce-mac58](https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-community-edition-18040-ce-rc2-mac61-2018-04-09) and reinstall it to downgrade docker for mac.

**Comment by koalalorenzo** [comment] 2018-04-15 08:02
The downgrade works for me as well. Not sure if it is a docker or helm issue. both? 😕

**Comment by bacongobbler** [comment] 2018-04-15 15:29
Docker issue

**Comment by edburns** [comment] 2018-04-17 11:38
I am experiencing this as well.

**Comment by esetnik** [comment] 2018-04-17 11:56
@koalalorenzo opened https://github.com/docker/for-mac/issues/2811 to track this issue

**Comment by edburns** [comment] 2018-04-17 12:11
I can also confirm that downgrading to 18.03.0-ce-mac58 worked for me.

**Comment by technosophos** [comment] 2018-04-20 22:25
The root cause seems to be a recent change to Go''s SSL library and the way D4M sets the dnsName field in the x509 cert: https://github.com/golang/go/issues/23995

**Comment by tedmiston** [comment] 2018-04-30 18:37
This fix doesn't seem to be working for me using the latest Helm (2.9.0).

```
t-mbp:~ taylor$ helm init --upgrade
$HELM_HOME has been configured at /Users/taylor/.helm.
Error: error installing: Post https://localhost:6443/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:6443: connect: connection refused
```

**Comment by bacongobbler** [comment] 2018-05-28 18:03
This seems related to #3384, where the bottled formula of Helm is compiled against an older release of Go. If you try using the "official" release artifacts rather than `brew install` you shouldn't see this issue. [GoFish](https://www.gofi.sh/) fetches down the release binaries if you prefer using a package manager.

**Comment by bacongobbler** [comment] 2018-05-28 18:07
Yeah, downgrading to Helm 2.8.2 will also work because it's compiled against Go 1.8, bypassing the breaking change Go 1.9 introduced as @technosophos mentioned .:)

**Comment by edburns** [comment] 2018-06-05 19:02
As far as I know, one still  needs to use Docker for Mac Edge Version 18.03.0-ce-mac58 (23607) to have this not be a problem.

**Comment by tedmiston** [comment] 2018-06-05 19:06
I haven't tried upgrading to latest yet myself since this.  Each upgrade so far has broken my Kubernetes setup and required rebuilding the cluster.  It can be time-consuming when one has deadlines to hit.

**Comment by edburns** [comment] 2018-07-25 16:17
I'd love to get some word that this has been fixed or not.  Every time I get pestered by a new Docker for Mac upgrade, from 18.03.0-ce-mac58, I check and every time it's not fixed.  Anyone else have any status on this?

**Comment by tedmiston** [comment] 2018-07-26 20:16
I haven't tried them yet, but there were new releases of both stable and edge yesterday.

Stable 18.06.0-ce-mac70 - https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18060-ce-mac70-2018-07-25

Edge 18.06.0-ce-mac69 - https://docs.docker.com/docker-for-mac/edge-release-notes/#docker-community-edition-18060-ce-mac69-2018-07-25

**Comment by clanesf** [comment] 2018-08-09 19:40
Getting this smae issue on Edge 18.06.0-ce-mac

**Comment by adamalex** [comment] 2018-08-09 20:03
Same issue with latest stable Docker on Mac:

![image](https://user-images.githubusercontent.com/50389/43922756-a5e6a0aa-9bed-11e8-886c-056fe95cf079.png)

**Comment by adamalex** [comment] 2018-08-09 20:04
For anyone that saw my post from a minute or so, please disregard

**Comment by edburns** [comment] 2018-08-10 00:28
I am happy to report that with Docker for Mac Stable 18.06.0-ce I am able to do `helm init` successfully.  I performed the following steps to get there.
* Using Docker preferences, factory reset
* Using Docker preferences, uninstall docker
* Using appcleaner, delete Docker from applications
* Empty trash
* Reboot
* Download fresh `.dmg` of Docker for Mac 18.06.0-ce.  
* Doubleclick the installer
* Install docker
* Using Docker preferences, select "Kubernetes" instead of "Swarm"
* Using Docker preferences, enable Kubernetes, waiting for it to successfully start
* Using homebrew, upgrade `kubernetes-helm`, waiting for it to install
* Finally, I can do `helm init`. 

I did not observe the "cannot parse dnsName" error.  From my perspective, this issue can be closed.

**Comment by bacongobbler** [comment] 2018-08-10 03:13
Woop! I believe @technosohos also indicated that he was able to get this working today. Closing!

**Closed by bacongobbler** 2018-08-10 03:13 UTC
Labels: question/support
