### ISSUE TITLE
Helm v3 - upgrade fails to apply value changes

### ISSUE THREAD

**Issue by PsyonixBarrett** [helm/helm#5792] opened 2019-05-23 21:28 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

## What happens
When running `helm upgrade --set foo=bar RELEASE CHART` the upgrade process does not take into account the newly set values of `foo: bar`.

## How to reproduce
1. Install a chart with `helm install RELEASE CHART` with any values you want.
2. Run an upgrade with a new values.yaml with `-f new-values.yaml` or by passing values in the command line `--set foo=bar`.
3. Check the values with `helm get values RELEASE` and see `null` as the return value or with `helm get values RELEASE -a` and see the previous values from the install without the new `foo` value. You can also verify the chart output with `--dry-run --debug` when modifying a value that is used within the chart as you'll see that the value isn't updated.

Interestingly enough, if you were to modify the values in the original chart repository (for local charts) and run the upgrade with `helm upgrade RELEASE CHART -f CHART/values.yaml` it will work as intended.

**Comment by lijian-ruckus** [comment] 2019-05-24 07:54
I am facing the same issues with the same helm version.

I tried "helm  upgrade --set" with "--reset-values" in vain.

But "helm install" works with --set key=value to override values.

**Comment by karuppiah7890** [comment] 2019-05-27 16:07
Thanks @PsyonixBarrett and @lijian-ruckus for reporting this issue!

I am able to reproduce the issue with this chart - [issue-5792.tar.gz](https://github.com/helm/helm/files/3224416/issue-5792.tar.gz) and I used this values.yaml to install - 

issue-5792-values.yaml
```
replicaCount: 2
```

and this one to upgrade - 

issue-5792-new-values.yaml
```
replicaCount: 4
```

On upgrade, the replica count of the deployment didn't change, which confirms that the values wasn't updated. These are the logs that come up:

```
$ helm upgrade issue-5792 issue-5792-chart/ --values issue-5792-new-values.yaml --debug
upgrade.go:77: [debug] preparing upgrade for issue-5792
upgrade.go:273: [debug] copying values from issue-5792 (v3) to new release.
upgrade.go:86: [debug] creating upgraded release for issue-5792
upgrade.go:92: [debug] performing update for issue-5792
client.go:161: [debug] building resources from updated manifest
client.go:169: [debug] checking 1 resources for changes
client.go:340: [debug] Looks like there are no changes for Deployment "issue-5792-issue-5792-chart"
upgrade.go:99: [debug] updating status for upgraded release for issue-5792
NAME: issue-5792
LAST DEPLOYED: 2019-05-27 21:32:15.619698 +0530 IST m=+0.128743553
NAMESPACE: default
STATUS: deployed

Release "issue-5792" has been upgraded. Happy Helming!
NAME: issue-5792
LAST DEPLOYED: 2019-05-27 21:32:15.619698 +0530 IST
NAMESPACE: default
STATUS: deployed
```

It's weird to see this log:

```
client.go:169: [debug] checking 1 resources for changes
client.go:340: [debug] Looks like there are no changes for Deployment "issue-5792-issue-5792-chart"
```

as it says that there are no changes for the deployment, when in fact there are changes as I put the values.yaml. @PsyonixBarrett could you explain how it worked as intended when you changed the default values.yaml inside the chart? That didn't work for me actually. I could never update the values and change the replica count with the above chart. Please help understand in which cases it worked for you, and I will also look at the code to see why it said there are no changes in the logs and why there was no update

**Comment by hickeyma** [comment] 2019-05-27 16:36
I can confirm this as follows:

```console
$ cat chrt-5792/values.yaml 
favoriteDrink: coffee

$ cat chrt-5792/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}

$ helm install chrt-5792 chrt-5792/ --set favoriteDrink=tea
NAME: chrt-5792
LAST DEPLOYED: 2019-05-27 17:26:44.419862911 +0100 IST m=+0.082390919
NAMESPACE: new-ns
STATUS: deployed

$ kubectl get configmap
NAME                  DATA   AGE
chrt-5792-configmap   2      61s

$ kubectl get configmap -o yaml chrt-5792-configmap
apiVersion: v1
data:
  drink: tea
  myvalue: Hello World
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-27T16:26:45Z"
  name: chrt-5792-configmap
  namespace: new-ns
  resourceVersion: "7536"
  selfLink: /api/v1/namespaces/new-ns/configmaps/chrt-5792-configmap
  uid: 37f3c238-809c-11e9-b2b8-220bd08d6dd3

$ helm upgrade chrt-5792 chrt-5792/ --set favoriteDrink=water
Release "chrt-5792" has been upgraded. Happy Helming!
NAME: chrt-5792
LAST DEPLOYED: 2019-05-27 17:29:41.251054843 +0100 IST
NAMESPACE: new-ns
STATUS: deployed

$ kubectl get configmap
NAME                  DATA   AGE
chrt-5792-configmap   2      3m5s

$ kubectl get configmap -o yaml chrt-5792-configmap
apiVersion: v1
data:
  drink: tea
  myvalue: Hello World
kind: ConfigMap
metadata:
  creationTimestamp: "2019-05-27T16:26:45Z"
  name: chrt-5792-configmap
  namespace: new-ns
  resourceVersion: "7536"
  selfLink: /api/v1/namespaces/new-ns/configmaps/chrt-5792-configmap
  uid: 37f3c238-809c-11e9-b2b8-220bd08d6dd3
```

**Comment by karuppiah7890** [comment] 2019-06-02 17:57
@rokii has he found the bug and raised a PR #5824 for this! 😄  Looks like we will be closing this issue soon! 🎉

**Closed** 2019-06-04 20:55 UTC
Labels: bug, v3
