### ISSUE TITLE
helm 3 beta 5 list release from another user as cluster-admin

### ISSUE THREAD

**Issue by antoineozenne** [helm/helm#6774] opened 2019-10-24 11:59 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.5", GitCommit:"509a8819b7e8dba86b7982c006fce22628aeea28", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise platform.

My friend, who is simple kubernetes user, create a helm release in the namespace `test`. I'm cluster-admin, and I don't see his release when I run `helm list --all --all-namespaces`. However, I can see his release when I run `helm list --all -n test`. Is it a bug ? I think as cluster-admin, I should see all releases when I run `helm list --all --all-namespaces`.

In addition, I can `helm upgrade` the release. Then the situation is the same.

**Comment by bacongobbler** [comment] 2019-10-24 15:25
https://v3.helm.sh/docs/intro/rbac/#example-grant-a-user-read-only-access-at-the-cluster-scope

**Comment by antoineozenne** [comment] 2019-10-24 17:03
Thank you baconglobber, I read this documentation and follow instructions. My question is about cluster-admin clusterrole. Cluster-admin clusterrole has all rights in the cluster, so cluster-scoped read access. So why can't it list helm releases too ? I can't test now if a cluster-admin clusterrole needs a secret-reader clusterrole in addition to list helm release, but I think a cluster-admin clusterrole should list helm releases by nature. Am I clear ?

**Comment by bacongobbler** [comment] 2019-10-24 17:44
Yes. If you attached a ClusterRoleBinding with cluster-admin, the user should be able to view releases with `helm list --all-namespaces`.

If you can please share your setup, that would be helpful to reproduce your issue locally to see if there are additional documentation we can add. Thanks,

**Comment by antoineozenne** [comment] 2019-10-24 18:03
I'll share that tomorrow. Thank you.

**Comment by antoineozenne** [comment] 2019-10-25 06:43
So, with the user A, which are only admin in namespace osm :
```sh
helm list -a -n osm
# NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART   APP VERSION
helm upgrade --install test test --namespace=osm --set ingress.host=test.fr
# Release "test" does not exist. Installing it now.
# NAME: test
# LAST DEPLOYED: Fri Oct 25 08:34:58 2019
# NAMESPACE: osm
# STATUS: deployed
# REVISION: 1
# TEST SUITE: None
helm list -a -n osm
# NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
# test            osm             1               2019-10-25 08:34:58.3168085 +0200 CEST  deployed        test-0.0.1
```
Then, with a cluster-admin user :
```sh
helm list -a -n osm
# NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
# test            osm             1               2019-10-25 08:34:58.3168085 +0200 CEST  deployed        test-0.0.1
helm list -a --all-namespaces
# NAME                            NAMESPACE                       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
# other                           other                           7               2019-10-24 22:21:25.728539113 +0000 UTC deployed        other-0.0.1
# ...
```
But there is no release "test" in this last list.
Are you agree I should see my release "test" ?
Do you need further information ?

**Comment by bacongobbler** [comment] 2019-10-25 10:46
Can you please share the (cluster)roles and (cluster)rolebindings bound to these accounts? Thanks.

**Comment by antoineozenne** [comment] 2019-10-25 11:42
First, I create the osm namespace with a cluster-admin user with the following RBAC (he is in the ldap:k8s:dev:profile:cluster-admin group) :
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-10-23T16:13:06Z"
  name: ldap:k8s:dev:profile:cluster-admin
  resourceVersion: "12491002"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/ldap%3Ak8s%3Adev%3Aprofile%3Acluster-admin
  uid: ff594c4b-f5af-11e9-8f5b-0050569de558
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ldap:k8s:dev:profile:cluster-admin
```

Then to deploy the helm release, I use a basic user with the following RBAC (he is in the ldap:k8s:dev:profile:developer group) :
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2019-10-23T16:13:06Z"
  name: ldap:k8s:dev:profile:developer
  resourceVersion: "12491005"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/ldap%3Ak8s%3Adev%3Aprofile%3Adeveloper
  uid: ff595623-f5af-11e9-8f5b-0050569de558
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ldap:k8s:dev:profile:developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2019-10-23T16:13:06Z"
  name: ldap:k8s:dev:profile:developer_osm
  namespace: osm
  resourceVersion: "12491016"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/osm/rolebindings/ldap%3Ak8s%3Adev%3Aprofile%3Adeveloper_osm
  uid: ff611c88-f5af-11e9-8f5b-0050569de558
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ldap:k8s:dev:profile:developer
```

Finally, to list the helm release, I use the cluster-admin user (the same as the first).

**Comment by thomastaylor312** [comment] 2019-10-28 17:59
@bacongobbler could this be related to the bug fixed in #6756, but is not yet released?

**Comment by bacongobbler** [comment] 2019-10-28 18:23
It looks like the release names are named differently in @antoineozenne's examples, so that should be fine.

If you can break down a very basic example @antoineozenne on how others can reproduce the issue you're seeing, that would be helpful. For example:

1. Helm version: 3.0.0-beta.5
1. Kubernetes version: 1.13.2
1. create a new user, following these steps: (INSERT LINK HERE)
1. attach the `cluster-admin` role using the following rolebindings: `kubectl create clusterrolebinding ...`
1. create the following namespaces with `kubectl create namespace`: (INSERT NAMES HERE)
1. create the following releases using the chart provided by `helm create test`

Thanks.

**Comment by antoineozenne** [comment] 2019-10-29 08:20
I'm sorry, but I think it's a mistake. In my last example, I replaced release names by test to provide information here. But in reality, the release name was the same as another in another namespace. So I think the problem was due to this bug : it's a duplicate of [#6756](https://github.com/helm/helm/pull/6756). Sorry.

**Comment by hickeyma** [comment] 2019-10-29 10:00
That's ok @antoineozenne. Closing as duplicate of #6756

**Closed by hickeyma** 2019-10-29 10:00 UTC
Labels: question/support
