### ISSUE TITLE
Helm --upgrade --debug - hide configuration values in output

### ISSUE THREAD

**Issue by sebolabs** [helm/helm#7595] opened 2020-02-14 10:47 UTC
Is there any option to run `helm upgrade --install --debug` in a way that DOES NOT output:
* USER-SUPPLIED VALUES
* COMPUTED VALUES
* HOOKS
* MANIFESTS

I'd only like to see things like:
```
history.go:52: [debug] getting history for release
upgrade.go:79: [debug] preparing upgrade for xxx
[...]
client.go:400: [debug] Looks like there are no changes for ConfigMap "zzz"
[...]
wait.go:199: [debug] Deployment is not ready: xxx/yyy. 0 out of 1 expected pods are ready
[...]
upgrade.go:94: [debug] updating status for upgraded release for xxx
```
which I find super useful as they tell what's happening and which parts haven't changed etc., however, because of reasons I don't want to make any configuration details visible (to other people).
To see the values I'd rather use the `--dry-run` option before applying anything.

Output of `helm version`: 3.0.3

**Comment by towolf** [comment] 2020-02-18 13:09
Thanks for filing this issue, I had the same peeve today with the output.

My workaround so far is adding this: `helm ... | sed --unbuffered '/USER-SUPPLIED VALUES/,$d'`

**Comment by bacongobbler** [comment] 2020-02-28 22:16
Duplicate of https://github.com/helm/helm/issues/7275.

**Closed by bacongobbler** 2020-02-28 22:16 UTC
Labels: feature
