### ISSUE TITLE
Helm3-beta4: Upgrade operation fails with some specific chart versions 

### ISSUE THREAD

**Issue by jkrayl** [helm/helm#6664] opened 2019-10-14 13:01 UTC
Hi,

when I try to do an up/downgrade from some chart versions to newer/older versions the upgrade operation fails. For example the downgrade from grafana chart from the chart version 3.8.15 to 3.8.14 I get an error `419 conflict`:
```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Deployment, namespace: default, name: grafana
```
Install call:
```
helm install grafana stable/grafana --version 3.8.15 --namespace default
```
Upgrade call:
```
helm upgrade grafana stable/grafana --version 3.8.14 --namespace default
```
This makes a downgrade from a version >= 3.8.15 to a version <= 3.8.14 impossible

---
When I try the same operation with helm2 it works fine:
Installation call:
```
helm install stable/grafana --name grafana-test --version 3.8.15 --namespace default
```

Upgrade call:
```
helm upgrade grafana-test stable/grafana --version 3.8.14 --namespace default 
```
I compared the two helm charts and it seems like that the `apiVersion` of the deployment and podsecurity template changed from `apps/v1beta2` to `apps/v1`. Maybe this caused this incident.

---
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:07Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AKS`

**Comment by karuppiah7890** [comment] 2019-10-14 13:12
Thanks for reporting this bug! I'll try reproducing it. We could also work on a fix - Would you be interested in working on a fix for this issue ? :)

**Comment by hickeyma** [comment] 2019-10-14 15:21
This is reproducible as follows with latest `dev-v3`:

```console
$ helm install grafana stable/grafana --version 3.8.15 --namespace default
NAME: grafana
LAST DEPLOYED: Mon Oct 14 16:02:07 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
[.....]

$ helm ls
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
grafana	default  	1       	2019-10-14 16:02:07.121725344 +0100 IST	deployed	grafana-3.8.15	6.3.5    

$ helm upgrade grafana stable/grafana --version 3.8.14 --namespace default
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: PodSecurityPolicy, namespace: , name: grafana
```  

I tested with latest `master` for v2:

```console
$ helm install --name grafana stable/grafana --version 3.8.15 --namespace default
NAME:   grafana
LAST DEPLOYED: Mon Oct 14 16:06:57 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                 AGE
grafana-clusterrole  2s
[....]

$ helm upgrade grafana stable/grafana --version 3.8.14 --namespace default
Release "grafana" has been upgraded.
LAST DEPLOYED: Mon Oct 14 16:08:12 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
[...]

$ helm history grafana
REVISION	UPDATED                 	STATUS    	CHART         	APP VERSION	DESCRIPTION     
1       	Mon Oct 14 16:06:57 2019	SUPERSEDED	grafana-3.8.15	6.3.5      	Install complete
2       	Mon Oct 14 16:08:12 2019	DEPLOYED  	grafana-3.8.14	6.3.5      	Upgrade complete
```

**Comment by hickeyma** [comment] 2019-10-14 15:25
Thanks for finding this @jackgr

**Comment by jkrayl** [comment] 2019-10-15 07:10
Thanks for working on this so quickly @karuppiah7890 @hickeyma 
Right now I'm kept on my toes by some other topics but maybe in the future :)

**Comment by masterkain** [comment] 2019-10-28 20:06
is there a way to solve this and proceed with chart reinstallation?

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: PodSecurityPolicy, namespace: , name: linkerd-linkerd-control-plane
```

**Comment by bacongobbler** [comment] 2019-10-30 19:41
Closing as a duplicate of https://github.com/helm/helm/issues/6646. A larger explanation of this behaviour was described in [this comment](https://github.com/helm/helm/issues/6646#issuecomment-547650430). Thanks!

**Closed by bacongobbler** 2019-10-30 19:41 UTC
Labels: bug, v3.x
