### ISSUE TITLE
--kube-context not work

### ISSUE THREAD

**Issue by zyf0330** [helm/helm#5052] opened 2018-12-13 07:32 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Self set up

I use `--kube-context` option to specify one context, and switch to swcond context to do something with helm. But `helm install` creates everything in second context.

**Comment by bacongobbler** [comment] 2018-12-13 19:10
What was the expected behaviour?

**Comment by zyf0330** [comment] 2018-12-14 01:44
No doubt, they should be created in first context specified by `--kube-context`.

**Comment by mortent** [comment] 2018-12-16 22:13
Could you provide some more details about what you are doing and where the behavior is not what you expected?

I'm able to set up a second cluster (on GKE), use kubectl to set the default context to the new cluster, install tiller and a chart into the newly created cluster, then use kubectl to switch the default context back to my old cluster. If I run `helm --kube-context <new cluster> ls`, I see the newly installed chart in my new cluster. Running just `helm ls` gives me data from my old cluster. This is the behavior I would expect.

If you are running in a tillerless setup, then the `--kube-context` flag doesn't seem to work, but I think that is expected.

**Comment by zyf0330** [comment] 2018-12-17 01:34
What is tillerless setup? I start up tiller at localhost not kube cluster.

**Comment by mortent** [comment] 2018-12-17 18:30
By tillerless I mean running Helm without Tiller installed in the cluster. You seem to be running this setup.

I'm not sure how you set up Helm to find the Tiller instance you have running at localhost, but I assume you use either the `--host` flag or use the `HELM_HOST` environment variable. These setting override any value you use for `--kube-context` since you have already told Helm directly where to find Tiller. Tiller will connect to the Kubernetes cluster it finds in the kubeconfig file.

I haven't tried to switch the kubernetes context while Tiller is running, but I don't think it picks up those changes without a restart.

**Comment by bacongobbler** [comment] 2018-12-17 18:51
If there was functionality available for switching kube contexts via a feature flag, then you could spawn a new tiller process listening on a different port with the `--kube-context` flag, though [that doesn't seem to exist for tiller](https://github.com/helm/helm/blob/6e5c2d5706a5d37113bba9f0eaaa10e11686a7be/cmd/tiller/tiller.go#L77-L87).

Fell like taking a crack at a PR? :)

**Comment by zyf0330** [comment] 2018-12-18 02:20
Thanks @mortent @bacongobbler ! I didn't know about this. But is there any doc about this?

**Comment by mortent** [comment] 2018-12-19 07:42
Sure, I can do a PR to add support for `--kube-context` in Tiller.

**Comment by zyf0330** [comment] 2018-12-19 08:40
@mortent Appreciate for this!

**Comment by tonsV2** [comment] 2019-04-22 09:39
Is there any progress on this one? Currently I'm switching context by updating ~/.kube/config which isn't ideal

**Comment by bacongobbler** [comment] 2019-12-09 20:07
We are no longer accepting new features for Helm 2. With the removal of Tiller in Helm 3, this is no longer needed. Closing!

**Closed by bacongobbler** 2019-12-09 20:07 UTC
Labels: question/support
