### ISSUE TITLE
[Question] How to handle pending-upgrade state

### ISSUE THREAD

**Issue by bbkgh** [helm/helm#9923] opened 2021-07-07 14:57 UTC
Hi. We use helm3 as our main tool in ci/cd for applying changes to applications. Sometimes connection issues between helm client and destination kubernetes cluster leaves release in pending-upgrade state. fixing this issue manually is so time-consuming and painful for us (we have many releases and deploys/day). Now we rollback pending release and re-run helm upgrade (also this method is dangerous in some situations). What is your suggestion for this situation?
We also tried to change latest `sh.helm.release.v1` secret's labels.status to `deployed` but we found that helm doesn't read revision status from this label and it's sealed in secret's data.release (what is purpose of this labels?). Is there any tool/method/script/subcommand for changing status of a revision?
thanks

**Comment by bacongobbler** [comment] 2021-07-07 15:22
This seems like a duplicate of #7139, as you're asking for advice on how to handle issues when Helm enters an erroneous state during a timeout.

Have you had a chance to read through that thread as well as [the latest comment in that thread](https://github.com/helm/helm/issues/7139#issuecomment-871637270)?

**Comment by bacongobbler** [comment] 2021-07-07 15:23
err, rather this is a duplicate of https://github.com/helm/helm/issues/4558.

**Closed** 2021-07-07 15:27 UTC
Labels: question/support
