### ISSUE TITLE
AMD64 Checksum displayed doesn't match the one in the linked file

### ISSUE THREAD

**Issue by smoyer64** [helm/helm#5777] opened 2019-05-22 12:02 UTC
Output of `helm version`:

2.14.0

Output of `kubectl version`:

N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

N/A

The contents of the checksum file is:

```
b5f6a1e642971af1363cadbe1f7f37c029c11dd93813151b521c0dbeacfbdaa9
```

But the checksum displayed on the release page is:

```
15eca6ad225a8279de80c7ced42305e24bc5ac60bb7d96f2d2fa4af86e02c794
```

As an aside, I appreciate that you're thinking about putting the checksums in the release notes as text since I'm upgrading systems using Ansible.

**Comment by jdolitsky** [comment] 2019-05-23 14:43
@smoyer64 thanks we'll take a look

**Comment by jdolitsky** [comment] 2019-05-23 14:53
Issue well defined in #5787
Closing as this is duplicate of that

**Closed by jdolitsky** 2019-05-23 14:53 UTC
Labels: release note required
