### ISSUE TITLE
Helm fails with <.Capabilities.APIVersions.Has>: can't evaluate field capabilities in type string

### ISSUE THREAD

**Issue by KlavsKlavsen** [helm/helm#8974] opened 2020-11-03 11:05 UTC
Output of `helm version`: 3.4.0
Output of `kubectl version`: 1.11 (running Openshift 3.11)
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Openshift 3.11 on own nodes.

This change in Prometheus chart https://github.com/prometheus-community/helm-charts/commit/0440ced5800af9106aec45650a64f4c8e70eab0b
introduces the use of this function - but we can see that this does not work - even with latest helm 3 version - most likely due to our older Kubernetes cluster :+1: 

if I list: kubectl api-versions - that works fine.. so its rather odd that Helm can't do it ?

**Comment by mattfarina** [comment] 2020-11-03 15:02
Have you tried kubectl 1.19 for the api-versions call?

Kubernetes 1.11 came out more than 2 years ago and is no longer supported by the community. While Kubernetes has semantic-ish version strings it often does not follow strict semver. Some features end up being deprecated and removed.

Helm v3.4 is using Kubernetes 1.19 libraries to interact with the cluster. I have not looked but, if the feature changed in a breaking way (which happens) then Helm will not work due to Kubernetes libraries not working.

This is why Helm has [a version support policy](https://helm.sh/docs/topics/version_skew/#supported-version-skew). Often Helm will work outside of that policy but it's not guaranteed because of the way Kubernetes is changing things under the hood.

**Comment by bacongobbler** [comment] 2020-11-06 02:59
Closing as this falls out of our support version matrix. If you can reproduce this with a more recent version of Kubernetes, we'd be happy to look into this further. Thanks.

**Closed by bacongobbler** 2020-11-06 02:59 UTC
Labels: question/support
