### ISSUE TITLE
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.16.3"

### ISSUE THREAD

**Issue by SDedik** [helm/helm#10083] opened 2021-08-31 11:32 UTC
Hello,

Helm version 2.16.3. is still used on some of our Kubernetes clusters.

Since recently, tiller pods cannot start due to the:

`Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.16.3": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/kubernetes-helm/tiller:v2.16.3": failed to resolve reference "gcr.io/kubernetes-helm/tiller:v2.16.3": unexpected status code [manifests v2.16.3]: 401 Unauthorized`

**Comment by hickeyma** [comment] 2021-08-31 11:57
@SDedik Check out [Tiller installations stopped working and access is denied](https://helm.sh/docs/faq/troubleshooting/#tiller-installations-stopped-working-and-access-is-denied) but in a nutshell the place where Helm 2 binaries has changed.

**Comment by hickeyma** [comment] 2021-08-31 11:57
Duplicate of #10069

**Comment by hickeyma** [comment] 2021-08-31 11:57
Closing as a duplicate.

**Closed by hickeyma** 2021-08-31 11:57 UTC
