### ISSUE TITLE
This construct for checking existence of a nested key works prior to 3.3, fails in 3.3

### ISSUE THREAD

**Issue by kraney** [helm/helm#8628] opened 2020-08-20 17:28 UTC
Prior to Helm 3.3, this check returned true if either of foo.dev.source or bar.dev.source were defined

{- if ((.Values.foo.dev) and (.Values.foo.dev.source)) or ((.Values.bar.dev) and (.Values.bar.dev.source))}}
{{ end }}

In 3.3, both helm lint and helm upgrade fail with this error

[ERROR] templates/: template: foo/templates/bar.yaml:120:13: executing "foo/templates/bar.yaml" at <((.Values.foo.dev) and (.Values.foo.dev.source)) or ((.Values.bar.dev) and (.Values.bar.dev.source))>: can't give argument to non-function (.Values.foo.dev) and (.Values.foo.dev.source)

I might consider this a "change in behavior" rather than a bug, except I can't find a way to achieve a similar result. If you need to check for existence of a key more than one level deep in nested maps, there seems to be no way to pass helm lint.

Output of `helm version`:
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.6"}

**Comment by mattfarina** [comment] 2020-08-20 18:53
While I can't speak to why lint didn't pick it up before 3.3.0, I so see a problem. `and`, `or`, and similar logic are functions that take arguments. It's a little different from what we are used to. You can see them at https://helm.sh/docs/chart_template_guide/function_list/#logic-and-flow-control-functions.

So, here is an example...

```
{{ and $arg1 $arg2 }}
```

I think your logic needs to be rewritten as something like...

```
{- if or (and .Values.foo.dev .Values.foo.dev.source) (and .Values.bar.dev .Values.bar.dev.source) }}
```

**Comment by kraney** [comment] 2020-08-20 19:05
Using that structure changes the error:

[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: quasar/templates/foo.yaml:120:55: executing "foo/templates/bar.yaml" at <.Values.foo.dev.source>: nil pointer evaluating interface {}.source

It still has the issue that it's trying to check a key in an unset map, where before it would short-circuit out of the later check based on the failure of the earlier check

**Comment by bacongobbler** [comment] 2020-08-20 19:09
This was a change that was recently introduced to Go 1.14, which is why it was picked up in newer versions of Helm that were compiled against Go 1.14.

> The text/template package now correctly reports errors when a parenthesized argument is used as a function. This most commonly shows up in erroneous cases like {{if (eq .F "a") or (eq .F "b")}}. This should be written as {{if or (eq .F "a") (eq .F "b")}}. The erroneous case never worked as expected, and will now be reported with an error can't give argument to non-function.

From https://golang.org/doc/go1.14.

See also https://github.com/helm/helm/issues/7711.

@mattfarina's suggestion is the correct way to fix that particular error. Not sure what's causing your second error, but hopefully that helps clarify the original issue.

EDIT: try checking your values.yaml file and make sure those values are set. It occurs when a child object is unset. See https://github.com/helm/helm/issues/8026.

**Comment by kraney** [comment] 2020-08-20 20:47
Those values are definitely NOT set, and are intended to be allowed to be unset. The presence of a value changes the behavior. That's what the statement attempts to do (and has been successfully been doing up to 3.3)

**Comment by kraney** [comment] 2020-08-20 22:48
To put it another way, the issue I'm trying to report is that there is no way to check whether foo.dev.source exists if foo.dev might also not exist. The other thing relating to and & or as functions is a distraction, it's unfortunate that I brought it into the bug report.

**Comment by kraney** [comment] 2020-08-20 23:50
This ticket may be duplicate or at least closely related to #8026

**Comment by bacongobbler** [comment] 2020-08-21 01:30
yeah, this is a duplicate of #8026. Let's close this and continue the conversation there.

**Closed by bacongobbler** 2020-08-21 01:30 UTC
Labels: question/support
