### ISSUE TITLE
Helm3 RC3: Unsigned executable not runnable on macOS Catalina

### ISSUE THREAD

**Issue by fuel-wlightning** [helm/helm#6927] opened 2019-11-09 15:39 UTC
Output of `helm version`:
```
N/A - Downloaded https://github.com/helm/helm/releases/tag/v3.0.0-rc.3
https://get.helm.sh/helm-v3.0.0-rc.3-darwin-amd64.tar.gz
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Docker For Mac Kubernetes
```

After downloading the Helm3 RC3 binary and placing it in a bin directory. Upon running it, macOS pops a dialog saying:
```
"helm" cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

Chrome downloaded this file today at 7:27am from github.com
```
with options of "Move to Trash" or "Cancel"

if cancel is clicked, the console output is:
```
Killed: 9
```

My guess is this is related to: https://developer.apple.com/news/?id=09032019a
I'm hoping this signing action can be added as part of CI

**Comment by bacongobbler** [comment] 2019-11-09 16:02
closing as a duplicate of https://github.com/helm/helm/issues/6615.

**Closed by bacongobbler** 2019-11-09 16:02 UTC
