### ISSUE TITLE
helm --dry-run does not detect invalid values of metadata.labels

### ISSUE THREAD

**Issue by oveits** [helm/helm#5836] opened 2019-06-04 07:43 UTC
Output of `helm version`:
---------------------------
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`:
------------------------------
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
--------------------------------------------------------
native kubeadm installation on CentOS at Hetzner Cloud

Problem:
----------
helm --dry-run does not detect invalid values of metadata.labels. In my case, a metadata.label was calculated to be "8.880525e+06" and "+" signs are not allowed. I would have expected `helm upgrade --install --dry-run` to verify the syntax of the metadata.labels according to the regexp `(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?`. However, it says, `Release "my-release" has been upgraded. Happy Helming!`

Shouldn't the `helm upgrade --dry-run` detect the problem? Is this a bug or a feature request?

How to reproduce:
---------------------
take an existing chart with a Deployment and add a label
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myname
  labels:
    commit: "{{ .Values.wrongValue }}"
```
then run
```
helm upgrade --install --force myname --set 'wrongValue=8.880525e+06'
```
This should produce an `metadata.labels: Invalid value` error, but 
```
helm upgrade --install --dry-run --force myname --set 'wrongValue=8.880525e+06'
```
does not. I would expect the dry-run to throw the same error.

Alternative:
------------
Alternatively, you can work on my open source croc-hunter project on https://github.com/oveits/croc-hunter/commit/888052589b45f67f4e2c1fdcd69c31e9e242adea. E.g. 
```
git clone https://github.com/oveits/croc-hunter
git checkout -b 8880525
```
Then perform a helm upgrade without dry-run, I get a `metadata.labels: Invalid value` error:
```
helm upgrade --install --force croc-hunter ./croc-hunter/charts/croc-hunter --set 'imageTag=prod-8880525,replicas=3,cpu=10m,memory=128Mi,ingress.enabled=true,ingress.hostname=crochunter.voco  n-it.com,imagePullSecrets.name=croc-hunter-secrets,imagePullSecrets.repository=docker.io,imagePullSecrets.username=****,imagePullSecrets.password=****,test.seleniumHubUrl=http://selenium-selenium-hub.selenium.svc.c  luster.local:4444/wd/hub,test.ingressHostname=crochunter.vocon-it.com,test.imageTag=prod-8880525,test.releaseName=croc-hunter' --set 'commit.sha=8880525,' '--namespace=croc-hunter' --wait
Error: UPGRADE FAILED: failed to create resource: Deployment.apps "croc-hunter-croc-hunter" is invalid: metadata.labels: Invalid value: "8.880525e+06": a valid label must be an empty string or consist of alphanumer  ic characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

If I run a dry-run, I would have expected to get the same `metadata.labels: Invalid value` error, but there is none:
```
helm upgrade --install --dry-run --force croc-hunter ./croc-hunter/charts/croc-hunter --set 'imageTag=prod-8880525,replicas=3,cpu=10m,memory=128Mi,ingress.enabled=true,ingress.hostname=crochunter.vocon-it.com,imagePullSecrets.name=croc-hunter-secrets,imagePullSecrets.repository=docker.io,imagePullSecrets.username=****,imagePullSecrets.password=****,test.seleniumHubUrl=http://selenium-selenium-hub.selenium.svc.cluster.local:4444/wd/hub,test.ingressHostname=crochunter.vocon-it.com,test.imageTag=prod-8880525,test.releaseName=croc-hunter' --set 'commit.sha=8880525,' '--namespace=croc-hunter' --wait
Release "croc-hunter" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Jun  4 08:46:26 2019
NAMESPACE: croc-hunter
STATUS: FAILED
```

I would have expected the dry-run to throw the same error as the run without the `--dry-run` option does. In this case, `--dry-run` should have verified the metadata.labels and it should have detected the invalid value: "8.880525e+06" that my chart has created from a large integer. 

Note: the incorrect conversion of the large integer itself is resolved within https://github.com/helm/helm/issues/1707. However, I had noticed that the `helm upgrade` fails, but the `helm upgrade --dry-run` does not detect the problem. Should it?

**Comment by hickeyma** [comment] 2019-06-04 10:20
@oveits I reproduced this issue and it looks like a bug.  Thanks for finding this.

Here is how I investigated it by creating a scaffold chart (`helm create`). I then added `commit: "{{ .Values.wrongValue }}"` to the deployment template and did a `--dry-run` and `install`. Findings shown below.

```console
$ cat chrt-5836/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chrt-5836.fullname" . }}
  labels:
{{ include "chrt-5836.labels" . | indent 4 }}
    commit: "{{ .Values.wrongValue }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
[.....]

$ helm install --name chrt-5836 chrt-5836/ --debug --dry-run --set 'wrongValue=8.880525e+06'
[debug] Created tunnel using local port: '33709'

[debug] SERVER: "127.0.0.1:33709"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/chrt-5836
[....]
COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
[...]
service:
  port: 80
  type: ClusterIP
tolerations: []
wrongValue: "8.880525e+06"
HOOKS:
---
[...]
---
# Source: chrt-5836/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrt-5836
  labels:
    app.kubernetes.io/name: chrt-5836
    helm.sh/chart: chrt-5836-0.1.0
    app.kubernetes.io/instance: chrt-5836
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
    commit: "8.880525e+06"
spec:
  replicas: 1
[....]

$ helm install --name chrt-5836 chrt-5836/ --set 'wrongValue=8.880525e+06'
Error: release chrt-5836 failed: Deployment.apps "chrt-5836" is invalid: metadata.labels: Invalid value: "8.880525e+06": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**Comment by codebind-luna** [comment] 2019-06-05 20:57
@hickeyma is anyone working on it?

**Comment by bacongobbler** [comment] 2019-06-05 20:59
not that I'm aware of no. This may be fixed with the 2.14.1 release as this seems to be a side-effect of #5750.

**Comment by hickeyma** [comment] 2019-06-06 06:09
@codebind-luna Go ahead and work on it if it is still a bug in master as @bacongobbler mentioned in https://github.com/helm/helm/issues/5836#issuecomment-499253464.

**Comment by codebind-luna** [comment] 2019-06-07 17:06
@hickeyma here I am posting my findings with the latest master
`helm version`
`Client: &version.Version{SemVer:"v2.14+unreleased", GitCommit:"2ca025d48222d6fa188653e2ca5eda6ed799145c", GitTreeState:"dirty"}
Server: &version.Version{SemVer:"canary+unreleased", GitCommit:"2ca025d48222d6fa188653e2ca5eda6ed799145c", GitTreeState:"clean"}`

**Comment by hickeyma** [comment] 2019-06-10 09:29
@codebind-luna Feel free to push a PR then.

**Comment by bacongobbler** [comment] 2020-08-14 19:18
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2020-08-14 19:18 UTC
Labels: bug
