### ISSUE TITLE
Docker Image for Helm 3

### ISSUE THREAD

**Issue by ResDiaryLewis** [helm/helm#8957] opened 2020-10-29 14:48 UTC
Is the Helm project planning to publish an official Docker image?
For Helm 2, our build scripts used Dockerfiles based on the `gcr.io/kubernetes-helm/tiller:v2.17.0` image, however I can't find an official Helm 3 Docker image. An unofficial image appears to exist [here](https://hub.docker.com/r/alpine/helm).

**Comment by bacongobbler** [comment] 2020-10-29 14:57
duplicate of https://github.com/helm/helm/issues/7522.

**Closed by bacongobbler** 2020-10-29 14:57 UTC

**Comment by ResDiaryLewis** [comment] 2020-10-29 15:17
Hi @bacongobbler, you've marked this as a duplicate of #7552 and closed both issues. Was that intentional?

**Comment by bacongobbler** [comment] 2020-10-29 15:28
Yes. We do not plan on supporting a, "official" Helm 3 docker image due to the amount of maintenance hassle required when maintaining the old tiller image. There are several community members working on a community-owned image including the one listed in #7522.
