### ISSUE TITLE
Helm template less functional in helm 3

### ISSUE THREAD

**Issue by derrickburns** [helm/helm#7463] opened 2020-01-24 16:32 UTC
The new helm template performs validation and rejects templates that fail validation. The error messages returned are often not helpful, eg when a template fails on input such as:

x: x:

The helm2 version of the template engine would not do validation, but would show the rendered template. This allowed one to inspect the results. 

Please add the ability to render a template, even if it fails validation.

**Comment by mattfarina** [comment] 2020-01-24 20:32
@derrickburns In this case are you using the `helm template` command?

**Comment by derrickburns** [comment] 2020-01-24 20:54
Yes

**Comment by unguiculus** [comment] 2020-01-28 10:47
I'd also appreciate getting the old behavior back. The fact that `helm template` could render invalid YAML helped a lot identifying YAML issues during chart development which is now no longer possible. At least we should get an option to turn validation off.

`helm template` does have a `--validate` flag which suggests that validation is off by default. However, this flag doesn't seem to have any effect. Validation is always on. Maybe this issue should be labeled as bug then.

**Comment by unguiculus** [comment] 2020-02-07 14:09
I looked at the sources and realized that `template` now uses the same code as `install` which involves YAML parsing. In Helm 2 `template` would just render the files and spit them out as is.

The refactoring was done in #5365.

@bacongobbler Can we somehow get the old behavior back? Maybe only do YAML parsing if the `--validate` flag is set?

**Comment by bacongobbler** [comment] 2020-02-07 15:49
Yes. Happy to look at PRs to implement this.

**Comment by bacongobbler** [comment] 2020-02-07 15:54
please give #7094 a try.

**Comment by bacongobbler** [comment] 2020-02-07 16:09
duplicate of #7088.

**Closed by bacongobbler** 2020-02-07 16:09 UTC
Labels: feature
