### ISSUE TITLE
Helm ls performance degradation with many releases 

### ISSUE THREAD

**Issue by Stono** [helm/helm#4821] opened 2018-10-22 18:56 UTC
Hey folks, 
We're using helm quite extensively and some operations (primarily helm ls) are really starting to grind now.

GKE 1.10.7, helm 2.10.

With 122 releases, the `ls` takes around 15 seconds.  We plan to be floating around the 500 mark on this particular cluster.

```
❯ time helm ls | wc -l
     122
helm ls  0.32s user 0.25s system 3% cpu 14.760 total
wc -l  0.00s user 0.00s system 0% cpu 14.759 total
```

Looking at the resource use, doesn't seem to be a CPU thing... so guessing it's just making a hell of a lot of calls to the kubernetes API.

<img width="1614" alt="screen shot 2018-10-22 at 19 55 17" src="https://user-images.githubusercontent.com/1486729/47312501-72f36f80-d634-11e8-975d-6dc4163b486d.png">

Just wondering if I should be worrying about using this at scale?  Are there any notable improvements in 2.11?

**Comment by bacongobbler** [comment] 2018-10-22 21:42
I don't think any patches were merged that changed how `helm ls` works internally. A check to confirm would never hurt.

Are you able to identify what API calls are being made between Tiller and the Kubernetes API? That way it'd be easier to identify where we'd need to make changes.

**Comment by bacongobbler** [comment] 2018-10-22 21:43
another related issue is #4543, though I don't think anyone from the community has identified the root problem either.

**Comment by mortent** [comment] 2018-10-23 05:52
@Stono Can you check how many ConfigMaps you actually have in etcd that belongs to Helm? This command should give you the count:
```
kubectl -n kube-system get cm --no-headers -l OWNER=TILLER | wc -l
```
Based on just a quick look at the code, it seems like pretty much all filtering, including the size limit, is enforced in Tiller and not in the ApiServer/etcd. So you could potentially be pulling in a large number of ConfigMaps from the ApiServer.

**Comment by whereisaaron** [comment] 2019-02-13 17:55
We are seeing performance degradation over time on older clusters. Every execution of `helm upgrade` or `helm list` is churning the API servers and causes 1-2 GB additional RAM use. Chaining command just keeps allocating more RAM. Waiting a decent period of time allows some RAM to be released.

This command a one cluster took a while and there are 3.5k ConfigMaps. Each is 1MB max, so up to 3.5GB data. The most frequently deployed application has >1000 revisions.
```
$ kubectl -n kube-system get cm --no-headers -l OWNER=TILLER | wc -l
3417
```

How can we prune ConfigMaps for older revisions of deployments with out deleting deployed, in-production applications?

**Comment by bacongobbler** [comment] 2019-02-13 18:57
closing as a duplicate of #4543. Let's keep the discussion in the same ticket as they seem to be both pointing at the same issue @mortent is alluding to.

**Closed by bacongobbler** 2019-02-13 18:57 UTC
Labels: bug
