### ISSUE TITLE
Helm Tiller Crash (SIGSEGV) when Upgradig Release

### ISSUE THREAD

**Issue by mitchellmaler** [helm/helm#4672] opened 2018-09-19 17:26 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher 2 Openstack

```
[main] 2018/09/19 17:17:30 Starting Tiller v2.10.0 (tls=false)
[main] 2018/09/19 17:17:30 GRPC listening on :44134
[main] 2018/09/19 17:17:30 Probes listening on :44135
[main] 2018/09/19 17:17:30 Storage driver is ConfigMap
[main] 2018/09/19 17:17:30 Max history per release is 0
[tiller] 2018/09/19 17:18:48 getting history for release develop
[storage] 2018/09/19 17:18:48 getting release history for "develop"
[tiller] 2018/09/19 17:18:48 preparing update for develop
[storage] 2018/09/19 17:18:48 getting deployed releases from "develop" history
[storage] 2018/09/19 17:18:48 getting last revision of "develop"
[storage] 2018/09/19 17:18:48 getting release history for "develop"
[tiller] 2018/09/19 17:18:48 rendering dotnetcoredemo chart using values
[storage] 2018/09/19 17:18:48 getting last revision of "develop"
[storage] 2018/09/19 17:18:48 getting release history for "develop"
[storage] 2018/09/19 17:18:48 getting release history for "develop"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e7028]

goroutine 92 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc4203d57a0, 0xc4200c0b90, 0x0, 0x0, 0x17b50a0)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc4203d57a0, 0x17d5e00, 0xc42087c240, 0xc4200c0b90, 0xc4203d57a0, 0x16b70a5, 0xd)
	/go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d5e00, 0xc42087c240, 0x1603f20, 0xc4200c0b90, 0x32, 0xc4200c1450, 0xc4200c0b01, 0x0)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d5e00, 0xc42087c240, 0x1603f20, 0xc4200c0b90, 0xc4208a2240, 0xc4208a2280, 0x48, 0xc4208a21c0, 0xc420867a40, 0x4108c8)
	/go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d5e00, 0xc42087c240, 0x1603f20, 0xc4200c0b90, 0xc4208a2240, 0xc4208a2280, 0xc420525ab0, 0x4108c8, 0x50, 0x15d6360)
	/go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x163dd60, 0xc4203d57a0, 0x17d5e00, 0xc42087c240, 0xc4200c0af0, 0x1712cd8, 0x0, 0x0, 0x43317c, 0xc4204a6900)
	/go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420346000, 0x17de900, 0xc420324160, 0xc420956000, 0xc4203d5860, 0x215fcf0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420346000, 0x17de900, 0xc420324160, 0xc420956000, 0x0)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420864040, 0xc420346000, 0x17de900, 0xc420324160, 0xc420956000)
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1
```

**Comment by bacongobbler** [comment] 2018-09-19 17:52
related comment: https://github.com/helm/helm/issues/3625#issuecomment-422542190

**Comment by bacongobbler** [comment] 2018-09-19 18:34
dupe of #4585 which was fixed in #4630. I'm in the process of cutting a new release candidate with the fix. Thanks!

**Closed** 2018-09-19 18:34 UTC
Labels: bug

**Comment by tonyxiao** [comment] 2018-09-19 23:10
@bacongobbler is there any way to use this fix before release candidate is cut? Or workaround in the command line to successfully upgrade without crashing tiller?

**Comment by bacongobbler** [comment] 2018-09-26 17:09
Note: the above comment turned out to be untrue. See https://github.com/helm/helm/issues/4681

**Comment by frankh** [comment] 2018-09-26 17:37
@bacongobbler thanks - I deleted the inaccurate comment
