### ISSUE TITLE
Non-determinism with multiple objects per file

### ISSUE THREAD

**Issue by cristiklein** [helm/helm#7115] opened 2019-11-29 15:00 UTC
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  **No provider required to trigger bug.**

It seems like `helm template` is non-deterministic if multiple objects are defined in a single file (i.e., YAML seperated by `---`). See [this commit](https://github.com/cristiklein/helm/commit/fc4d1f51b4d0c9e5e0ddda6ef7ca9d6283a424d9) for a new test that triggers this bug.

Is this use-case supported? Should I spend some time fixing this or rather document that this use-case is unsupported?

**Comment by bacongobbler** [comment] 2019-11-29 15:09
Closing as a duplicate of #6843. In the future, please make sure to check for existing issues first before opening a new ticket. Thanks!

**Closed by bacongobbler** 2019-11-29 15:09 UTC
