### ISSUE TITLE
Helm v3.5.4 removes newlines from input files, compared to v2.11

### ISSUE THREAD

**Issue by davidmichaelkarr** [helm/helm#9711] opened 2021-05-18 00:10 UTC
I work on build system that currently uses Helm v2.11.0.  I'm working on upgrading to v3.5.4 (or something closer to latest).

The first thing I wanted to examine was whether our existing command line produced the same output in both versions.  This experiment showed differences, which I need to understand.  The differences were in white space, but this could be very significant.  I don't know if what I'm seeing is a misunderstanding, but I have to clear that up before I move forward with this.

This is a very short excerpt from one of our input files, a yaml file:

>  system.properties: "# If the environment property system_properties_path contains
>    a path to a file  , System properties created using the file. If the environment

However, I'm not sure whether what you're seeing when you view this represents reality.  The first line begins with two spaces, and the second line begins with four spaces. However, you can clearly see there is a newline at the end of the first line.

When I run "helm template", the converted version of this looks like this:

>   system.properties: "# If the environment property system_properties_path contains a path to a file  , System properties

This renders the entire value in a single line, with all the newlines removed.  I did not show the entire line here, as it ends up being much longer than this.

This is not fatal for certain kinds of values, but it is very fatal for things like Java properties files. This sample effectively results in a file with a single line, which is commented.

What's curious is that I tried installed "yq" to make it convenient to look at inputs and outputs, and the result was somewhat surprising, perhaps not.  I tried just running "yq" on my original input file, the one with newlines, and what it produces is what Helm v3.5.4 produces, removing all of the newlines.

I have not tried to do something like a "git bisect" to see if I could find the last version where newlines are preserved.  I could do that if necessary.

**Comment by bacongobbler** [comment] 2021-05-18 00:20
I was unable to reproduce the issue. I attempted to create a helm chart following your example, and received the same output using both Helm 2.17 and 3.5.4. In both cases, whitespace was preserved.

```
><> cd /tmp/
><> gofish install helm2
==> Installing helm@2...
🐠  helm@2 2.17.0: installed in 1.4172225s
><> helm version
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Error: could not find tiller
><> helm create test-9711
Creating test-9711
><> cd test-9711/
><> l templates/
NOTES.txt  _helpers.tpl  deployment.yaml  ingress.yaml  service.yaml  serviceaccount.yaml  tests
><> rm -rf templates/*
><> vim templates/foo.yaml
><> helm template .
---
# Source: test-9711/templates/foo.yaml
  # this is
    a test
><> gofish unlink helm2
><> gofish link helm
><> helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
><> helm template . --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /tmp/test-9711

---
# Source: test-9711/templates/foo.yaml
  # this is
    a test
[...]
```

**Comment by bacongobbler** [comment] 2021-05-18 00:26
Looking at your example, it looks like you are wrapping a "comment" in double quotations. If this is meant to be a multi-line string, use multi-line syntax:

```
  system.properties: |
    # If the environment property system_properties_path contains
    a path to a file , System properties created using the file. If the environment
```


Unfortunately per the YAML 1.2 spec "Comments must not appear inside scalars" which is exactly the case here. There's no way in YAML to escape the octothorpe symbol (#) so within a multi-line string there's no way to disambiguate the comment from the raw string value.

However if the comment is insignificant, then this should work fine for your case.

Hope this helps.

**Comment by bacongobbler** [comment] 2021-05-18 03:57
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Closed by bacongobbler** 2021-05-18 03:57 UTC
Labels: question/support

**Comment by davidmichaelkarr** [comment] 2021-05-21 16:39
I'm going to create a new issue asking about the last issue there.
