### ISSUE TITLE
Download helm too slow

### ISSUE THREAD

**Issue by Cyberhan123** [helm/helm#9613] opened 2021-04-16 08:04 UTC
The dowload server is https://helm.sh/ ,but it's too slow to download ,can U give some advise?

**Comment by bacongobbler** [comment] 2021-04-20 22:47
Hi @Cyberhan123! This appears to be a duplicate of another issue: https://github.com/helm/helm/issues/7028. Have you had a chance to look at that one yet and see if it's relevant to your issue?

**Comment by Cyberhan123** [comment] 2021-04-21 05:58
> 嗨@ Cyber​​han123！这似乎是另一个问题的重复：[＃7028](https://github.com/helm/helm/issues/7028)。您是否有机会查看过那个问题，看看它是否与您的问题有关？

yeah, I see but can official give an other way to download ? I use  ```choco``` or ```brew``` to install ,It was a very simple thing, but became so complicated and unfriendly

**Comment by bacongobbler** [comment] 2021-04-21 21:05
Do you have any suggestions how we should proceed? What CDN services are available within China?

As I understand it, Azure CDN China is a completely separate service.

https://docs.microsoft.com/en-us/azure/cdn/cdn-china-delivery

An alternative is to use the Huawei mirror, making sure to check the release asset's PGP signatures against the attached signatures in the release page. That way you can ensure that the release assets have not been tampered with.

https://github.com/helm/helm/releases/tag/v3.5.4

**Comment by Cyberhan123** [comment] 2021-04-22 05:29
Thank you for your patience.

Can official wirte some notie or guide on readme?The easiest way is to give a reminder.I can do it if you like.

 emmm, https://www.cloudflare.com/ looks good , At least most of the people in China can visit,and it's a global CDN

**Comment by bacongobbler** [comment] 2021-04-22 05:46
Thank you for your thoughts. Let’s close this ticket and continue the conversation in #7028. I re-opened the ticket. Thanks!

**Closed by bacongobbler** 2021-04-22 05:46 UTC
Labels: question/support
