### ISSUE TITLE
Push a `v2.11` tag for the `tiller` container

### ISSUE THREAD

**Issue by LorenzoFernando** [helm/helm#4902] opened 2018-11-11 00:29 UTC
`helm init` configures a `tiller` deployment that expects the image `gcr.io/kubernetes-helm/tiller:v2.11` to exist. 

Navigating to to [container repository]() shows that only the `v2.11.0` tag exists. This is easily fixable by editing the tiller deployment, but ideally tiller would work out of the box. 

Thanks!

![screen shot 2018-11-10 at 7 27 30 pm](https://user-images.githubusercontent.com/5794835/48307630-e34c2d00-e51e-11e8-8d75-0289588ed0e6.png)

**Comment by bacongobbler** [comment] 2018-11-11 00:31
dupe of https://github.com/helm/helm/issues/3770.

**Closed by bacongobbler** 2018-11-11 00:31 UTC
