### ISSUE TITLE
Helm template silently ignores namespace flag

### ISSUE THREAD

**Issue by kav** [helm/helm#7774] opened 2020-03-17 21:24 UTC
When using `helm template` with the `-n`/`--namespace` flag the flag is silently ignored rather than injecting a namespace into the metadata of the appropriate resources.

Output of `helm version`: `{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}`

**Comment by bacongobbler** [comment] 2020-03-17 21:29
duplicate of #3553.

**Closed by bacongobbler** 2020-03-17 21:29 UTC

**Comment by kav** [comment] 2020-03-17 21:41
Any chance to at least fail loudly? All of the helm command line help implies this will work.

**Comment by xjantoth** [comment] 2020-06-29 08:51
Hi there, we are also facing this unpleasant issue with `helm template --namespace xyz ...` command. For us it's kind of ciritcal, because the only one resource out of like 5 from **templates/** folder gets rendered correctly. Iam wondering because `helm install ...` command deploys **Rancher** helm chart just right. It would be awesome to fix this issue. We are using **helm v3.2.3**
