### ISSUE TITLE
helm lint: "No template associated with template gotpl" when linting subcharts

### ISSUE THREAD

**Issue by payparain** [helm/helm#11260] opened 2022-08-24 00:06 UTC
Output of `helm version`: `version.BuildInfo{Version:"v3.9.3", GoVersion:"go1.17.13"}`

Output of `kubectl version`:
```
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.11
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): `AKS`

---
Hi,

I'm attempting to lint my umbrella chart but running into this persistent error surrounding the use of parent templates within the child charts templates. I can recreate this with a minimal example using just `helm create`. Suppose we have the following directory structure (generated by running `helm create` twice):

```
parent/
├── Chart.yaml
├── charts/
│   └── child/
│       ├── Chart.yaml
│       ├── charts/
│       ├── templates/
│       │   ├── _helpers.tpl
│       │   └── configmap.yaml
│       └── values.yaml
├── templates/
│   └── _helpers.tpl
└── values.yaml
```

The chart `parent` has a dependency on the chart `child`, as specified in it's `Chart.yaml`:

```
apiVersion: v2
name: parent
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: "child"
    version: 0.1.0
```

Within `parent`'s `_helpers.tpl` file, we have the following definition:
```
{{/*
Test template
*/}}
{{- define "parent.emotions" -}}
"Happy"
{{- end }}
```

... and within `child`'s `configmap.yaml`:
```
apiVersion: v1
kind: ConfigMap
data:
  myvalue: {{ include "parent.emotions" . }}
```

When we run `helm template .` from the root parent directory we get:
```
helm template . 
---
# Source: parent/charts/child/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
data:
  myvalue: "Happy"
 ```
Indicating that this _is_ a valid use of templates in the umbrella chart. However, when we run `helm lint --with-subcharts` from the same directory:
```
helm lint . --with-subcharts
==> Linting .
[INFO] Chart.yaml: icon is recommended

==> Linting charts/child
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: child/templates/configmap.yaml:4:14: executing "child/templates/configmap.yaml" at <include "parent.emotions" .>: error calling include: template: no template "parent.emotions" associated with template "gotpl"

Error: 2 chart(s) linted, 1 chart(s) failed
```

## Expected result
I would expect `helm lint . --with-subcharts` to succeed as this _is_ a [valid use of templates ](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/). Am I doing something wrong with Umbrella charts?

Any help appreciated!

**Comment by samueljim** [comment] 2022-08-26 11:07
lgtm

**Comment by joejulian** [comment] 2022-09-09 00:48
That is awkward. A chart is expected to be able to be installed stand-alone. You should be able to drill down into that subchart and install it without its parent. Yet the documentation reads otherwise on that page https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart .

This is confusing and could use some direction from the @helm/helm-core-maintainers . I suspect this is going to end up being a documentation bug.

**Comment by rvarun11** [comment] 2022-12-21 22:38
Any update on this issue?

**Comment by felipecrs** [comment] 2022-12-22 00:06
Well, it can **also** be a documentation bug. But certainly something else is wrong since `helm template` and `helm install` properly takes the gotpl function from the parent when called from the subchart. The only issue is with `helm lint`.

**Comment by tom-mckay** [comment] 2022-12-22 14:36
As @joejulian pointed out earlier, the same document that shows you how to share named templates with subcharts also states:
> A subchart is considered "stand-alone", which means a subchart can never explicitly depend on its parent chart.

These seem to conflict, as I don't think a subchart that depends on a parent chart defining a named template can be "stand-alone".

I recognize that Helm currently works this way for `helm template` and `helm install`. Was Helm intentionally designed this way? Should named templates defined in the parent be available in the subchart? Which part of the documentation is incorrect?

**Comment by joejulian** [comment] 2022-12-24 08:12
Well named templates all exist in the same namespace. If you define a template in a chart and subchart(s), which named template you actually get is undefined.

**Comment by felipecrs** [comment] 2022-12-24 14:19
> which named template you actually get is undefined

Yeah, I also observed such unreliable behavior. But that's a different issue than the one being reported here.

**Comment by joejulian** [comment] 2023-01-07 01:31
Oh, I see. It's not that you're trying to override a subchart value, it's that your subchart is using a template that's defined in the parent chart. I totally misread that the first time, sorry.

As @tom-mckay points out, the rules are pretty explicit that a subchart must be stand-alone. The linter is correctly pointing out that it's not.

The linter is working as intended. Perhaps the chart renderer is not, but changing it now would break [hip-0004](https://github.com/helm/community/blob/main/hips/hip-0004.md).

I'm closing this as "works as intended".

**Closed by joejulian** 2023-01-07 01:31 UTC
Labels: question/support

**Comment by thernstig** [comment] 2023-07-21 12:40
The problem I have had with this is that I have not found a way for a fallback for a named template. I tried to search the docs without finding it.

E.g. this is not possible.

```yaml
{{- define "child.foo" -}}
{{- if (include "parent.version" .) -}}
include "parent.version" .
{{- end -}}
```

Is there a way to check if a named template exists with conditionals?

**Comment by mathe-matician** [comment] 2024-04-10 21:15
@joejulian 

> Oh, I see. It's not that you're trying to override a subchart value, it's that your subchart is using a template that's defined in the parent chart. I totally misread that the first time, sorry.

Is this the same for library charts? For example, I see this same inconsistent behavior when I try to run `helm template` or `helm install` where `service1` below uses `library-chart`.

```
parent/
├── Chart.yaml
├── charts/
│   └── service1/
│       ├── Chart.yaml
│       ├── templates/
│       │   └── deployment.yaml
│       └── values.yaml
│   └── library-chart/
│       ├── Chart.yaml
│       ├── templates/
│       │   └── _deployment.yaml
└── values.yaml
```

**Comment by soul2zimate** [comment] 2024-11-19 07:07
>You may need to run `helm dependency build` to fetch missing dependencies:
