### ISSUE TITLE
`helm template` command with `--validate` option fails when the resource exists

### ISSUE THREAD

**Issue by yoichiwo7** [helm/helm#6663] opened 2019-10-14 03:13 UTC
Output of `helm version`: v3.0.0-beta.4

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

#### Problem

helm v3.0.0-beta.4 fails to generate template output when executing `helm template` command with `--validate` option if the same kubernetes resources already exits. 

The error message is like following:

`Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ServiceAccount, namespace: default, name: hello-world`

#### Expected behavior

`helm template` command with `--validate` must succeed to generate the template output even if the same kubernetes resources already exists.

#### Reproduce the problem

You can run following scripts to reproduce the problem. `helm v3.0.0-beta.4` fails and `helm v3.0.0-beta.3` succeeds.

```bash
#!/bin/bash
set -x

# Check version
helm version

# helm init
helm create hello

# 1st
helm template --validate hello-world hello  > hello.yaml
kubectl apply -f hello.yaml
sleep 10
kubectl get all

# 2nd (Succeeds on beta3, fails on beta4)
helm template --validate hello-world hello  > hello2.yaml

# cleanup
kubectl delete -f hello.yaml
rm -rf hello hello*.yaml
```

The result of the `helm v3.0.0-beta.4`:

```
+ helm version
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
+ helm create hello
Creating hello
+ helm template --validate hello-world hello
+ kubectl apply -f hello.yaml
serviceaccount/hello-world created
service/hello-world created
deployment.apps/hello-world created
pod/hello-world-test-connection created
+ sleep 10
+ kubectl get all
NAME                               READY   STATUS    RESTARTS   AGE
pod/hello-world-76cf477bc8-js6qg   1/1     Running   0          10s
pod/hello-world-test-connection    0/1     Error     0          10s

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/hello-world   ClusterIP   10.101.13.206   <none>        80/TCP    10s
service/kubernetes    ClusterIP   10.101.0.1      <none>        443/TCP   8d

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   1/1     1            1           11s

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-76cf477bc8   1         1         1       11s
+ helm template --validate hello-world hello
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ServiceAccount, namespace: default, name: hello-world
+ kubectl delete -f hello.yaml
serviceaccount "hello-world" deleted
service "hello-world" deleted
deployment.apps "hello-world" deleted
pod "hello-world-test-connection" deleted
+ rm -rf hello hello.yaml hello2.yaml   
```

The result of the `helm v3.0.0-beta.3`:

```
+ helm version
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
+ helm create hello
Creating hello
+ helm template --validate hello-world hello
+ kubectl apply -f hello.yaml
service/hello-world created
deployment.apps/hello-world created
+ sleep 10
+ kubectl get all
NAME                              READY   STATUS    RESTARTS   AGE
pod/hello-world-6d554ff9f-4mfx9   0/1     Running   0          11s

NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/hello-world   ClusterIP   10.101.11.215   <none>        80/TCP    11s
service/kubernetes    ClusterIP   10.101.0.1      <none>        443/TCP   8d

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   0/1     1            0           11s

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-6d554ff9f   1         1         0       11s
+ helm template --validate hello-world hello
+ kubectl delete -f hello.yaml
service "hello-world" deleted
deployment.apps "hello-world" deleted
+ rm -rf hello hello.yaml hello2.yaml
```

**Comment by yoichiwo7** [comment] 2019-10-14 06:12
I have checked related codes.

`helm template` command calls `Install.Run` function in dry-run mode. But the following resource conflict check in `Install.Run` function runs even in dry-run mode. Maybe we need to add another parameter or flag so that we can skip resource conflict check when called by `helm template`? 

https://github.com/helm/helm/blob/1e20ebae35d17c94e77051044fee79913c2719ff/pkg/action/install.go#L233-L249

> Note: I'm not sure whether the resource conflict check can be skipped for all other helm sub-commands in dry-run mode. Just skipping the resource conflict check for all sub-commands may cause regression bugs.

**Comment by hickeyma** [comment] 2019-10-14 15:44
@yoichiwo7 This maybe related to issue #6664

**Comment by Dean-Coakley** [comment] 2019-10-17 13:30
@yoichiwo7 Are you working on this or can I give it a try?

**Comment by yoichiwo7** [comment] 2019-10-17 14:52
@Dean-Coakley 
Not yet.
If you can give it a try, that would be great.

**Comment by thomastaylor312** [comment] 2019-10-29 17:01
So I've been digging in to these template issues a bunch over the past couple days. I believe that `--validate` _shouldn't_ ignore a resource already existing in the cluster. Basically, having validation means you are validating it against _that specific cluster_, not a generic "is this valid in Kubernetes" way. By specifying validate, you are asking "would this chart install in the cluster I am pointing at?" and it definitely should return an error if one of your resources already exist. I am not opposed to adding more generic schema validation, but it should be behind a different flag and have a well-considered implementation (because every cluster's schema is different due to CRDs and other API extensions). Any thoughts from others on this?

As a note: CRDs in the `crds/` directory, should be taken into consideration for the `--validate` flag as they are part of the chart and will be installed in the cluster you are pointing at

**Comment by bacongobbler** [comment] 2019-10-30 19:39
Closing as working as intended.

**Closed by bacongobbler** 2019-10-30 19:39 UTC
Labels: bug, v3.x

**Comment by yoichiwo7** [comment] 2019-10-31 00:57
@thomastaylor312 
Thanks for the comment. Let me recap it.

- `helm v3.0.0-beta.3` does schema validation.
    - Wrong/unintended behavior.
- `helm v3.0.0-beta.4` does schema validation **and resource states validation**.
    -  Correct/intended behavior.

If that's the case, the help description is misleading because it clearly states "for schema validation". I think it's almost impossible to decipher that "schema validation" includes the checking of the current resource states.

```
--validate
establish a connection to Kubernetes for schema validation
```

Unless "schema validation" is replaced with "install validation" or something else, I'm not really convinced that `--validate` is working as intended.

**Comment by thomastaylor312** [comment] 2019-10-31 15:17
That is a good point. I'll go update the help text to better reflect it
