### ISSUE TITLE
Helm is awfully slow on large enough installations

### ISSUE THREAD

**Issue by cristim** [helm/helm#3500] opened 2018-02-12 13:45 UTC
Some helm commands are really slow, on our environment with multiple installed charts it can take a lot of time for even a simple `helm list` operation:
```
time helm list
[...]
helm list  1.33s user 1.70s system 6% cpu 43.780 total
```

**Comment by xamox** [comment] 2018-02-13 03:19
Seeing the same thing:

```
$ time helm list | wc -l
83
helm list  0.84s user 0.87s system 6% cpu 25.887 total
wc -l  0.00s user 0.00s system 0% cpu 25.887 total
```

```
$ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.0", GitCommit:"14af25f1de6832228539259b821949d20069a222", GitTreeState:"clean"}
```

Also the cluster is not over utilized.
```
$ k top nodes        
NAME                                        CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%   
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-0qwb   3907m        24%       56387Mi         58%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-1l10   2024m        12%       62804Mi         64%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-1l3b   4271m        26%       61411Mi         63%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-2hhj   2930m        18%       45001Mi         46%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-468p   2273m        14%       50868Mi         52%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-76l4   2444m        15%       45357Mi         46%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-9xbb   5227m        32%       48432Mi         50%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-b4wk   3617m        22%       44273Mi         45%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-b6hg   1352m        8%        34025Mi         35%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-blbs   2445m        15%       51513Mi         53%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-btlm   2693m        16%       37291Mi         38%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-cb0n   4007m        25%       54388Mi         56%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-gqrz   1678m        10%       40019Mi         41%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-j35r   1842m        11%       50619Mi         52%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-l2db   2156m        13%       22842Mi         23%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-npvr   3721m        23%       67878Mi         70%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-nxt9   1934m        12%       49836Mi         51%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-plmj   2999m        18%       39545Mi         40%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-pvj7   2265m        14%       50151Mi         51%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-qwzm   5824m        36%       20082Mi         20%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-rwx9   4247m        26%       61047Mi         63%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-v520   4001m        25%       47561Mi         49%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-wjln   3653m        22%       30066Mi         31%       
gke-k8s-uw1-gcp-pd-ssd-pool-7aca2a33-zb1q   2140m        13%       32916Mi         34% 
```

**Comment by stephenakcegroup** [comment] 2018-02-14 11:43
I noticed a slow down too since upgrading to helm 2.8. 

Helm upgrade is taking 2 - 3 mins and sometimes times out.

**Comment by asherlporetz** [comment] 2018-04-20 02:26
We're having a problem too with a big installation. It's the same performance for v2.8.2 and v2.9.0-rc4. It seems there's a lot of unnecessary transfer of data. For a release with 200 versions and the kube-system having 3000 configmaps this is the flow of data:

etcd => (3000 configmaps) => kube-api => (200 configmaps) => tiller => (release data for latest version)

Perhaps a tiller storage driver that accesses the etcd directly for the release configmaps can speed things up. If kube-api is the cpu and etcd is the disk, then this is similar in concept to Direct Memory Access. Note that tiller will still use kube-api to create objects including the configmaps specified in a chart.

operation|data flow
-|-
write/read kubernetes objects | etcd <=> kube-api <=> tiller
write/read tiller release configmap | etcd <=> tiller 

Ideally we want the current driver "ConfigMap" to be interchangeable with this new driver "DirectConfigMap" and we can switch between the two anytime in an active cluster with no issues whatsoever. And this will become the more efficient data flow:

etcd => (fetch keys-only for prefix /registry/configmaps/{namespace}/{release}.v) => tiller
etcd => (1 configmap for the latest release) => tiller  => (release data for latest version)

**Comment by bacongobbler** [comment] 2018-04-20 03:45
@asherlporetz that seems like an interesting idea, but do you have benchmarks or something to back up the claim that the Kube API is the bottleneck?

Perhaps some telemetry from real scenarios would be good to grab.

**Comment by asherlporetz** [comment] 2018-04-20 19:00
[trace-helm-list.out.gz](https://github.com/kubernetes/helm/files/1933265/trace-helm-list.out.gz)
@bacongobbler Attached is a trace of tiller while doing this on v2.6.1 (helm v2.8.2 listing breaks, see #3782, but in my other partial benchmarks which included v2.9.0-rc4 their speed is more or less similar):
```bash
time helm list
real	0m 6.39s
user	0m 0.43s
sys	0m 0.35s
```
for which I reckon is this flow:
etcd => (1936 configmaps totalling 66.7MB) => kube-api => (1920 configmaps for -lOWNER=TILLER) => tiller => helm list for 203 releases

Once you `go tool trace trace-helm-list.out` you'll see that:
- CPU in "Scheduler latency profile" accounted for 175ms
- Network reading in "Network blocking profile" accounted for 6.16 seconds

**Comment by asherlporetz** [comment] 2018-04-24 01:56
It would also be great if all the filtering and processing for the following operations be pushed to tiller instead of getting more than 20MB of data to display two screenful of text information. Let tiller just return the output needed and nothing more. I have a feeling a lot of "helm list is slow complaints" will be solved by this more than the "DirectConfigMap" idea above.
{code:bash}
helm get
helm history
helm list
helm status
{code}

**Comment by hugohenley** [comment] 2018-06-14 14:10
We're facing the same issue here:
`helm list  0.24s user 0.16s system 0% cpu 48.597 total`

The cluster has 2027 revisions considering all the charts. Would be possible to keep only the last 10 revisions or something like that?

**Comment by Pharb** [comment] 2018-09-06 14:51
It is now possible to limit the number of revisions in the history with e.g. `helm init --history-max 100` (see #2332).

The default value for `history-max` is still unlimited. It might be a good idea to change this sometime?

Also changing `history-max` does not have any immediate effect. You would need to delete Tiller first with `helm reset -f` and then on the next release the history is cleaned up.

**Comment by hugohenley** [comment] 2018-09-06 14:57
Yes, that's what I did. Would be interesting to change it on the fly or even limit the history size by default.

**Comment by ajfriesen** [comment] 2018-11-29 16:22
I have 81 releases installed in my cluster.

There are 140 configmaps in kube-system

```helm ls``` is taking 3m

I think this is pretty long.

Is there something I can do about that?

Logs from tiller seem to be fine:

```
[tiller] 2018/11/29 12:46:06 performing install for test-museum
[tiller] 2018/11/29 12:46:06 executing 0 crd-install hooks for test-museum
[tiller] 2018/11/29 12:46:06 hooks complete for crd-install test-museum
[tiller] 2018/11/29 12:46:06 executing 0 pre-install hooks for test-museum
[tiller] 2018/11/29 12:46:06 hooks complete for pre-install test-museum
[storage] 2018/11/29 12:46:06 getting release history for "test-museum"
[storage] 2018/11/29 12:46:06 creating release "test-museum.v1"
[kube] 2018/11/29 12:46:06 building resources from manifest
[kube] 2018/11/29 12:46:06 creating 4 resource(s)
[tiller] 2018/11/29 12:46:06 executing 0 post-install hooks for test-museum
[tiller] 2018/11/29 12:46:06 hooks complete for post-install test-museum
[storage] 2018/11/29 12:46:06 updating release "test-museum.v1"
[storage] 2018/11/29 12:46:06 getting last revision of "test-museum"
[storage] 2018/11/29 12:46:06 getting release history for "test-museum"
[kube] 2018/11/29 12:46:06 Doing get for Secret: "test-museum-chartmuseum"
[kube] 2018/11/29 12:46:06 get relation pod of object: chartmuseum/Secret/test-museum-chartmuseum
[kube] 2018/11/29 12:46:06 Doing get for Service: "test-museum-chartmuseum"
[kube] 2018/11/29 12:46:06 get relation pod of object: chartmuseum/Service/test-museum-chartmuseum
[kube] 2018/11/29 12:46:06 Doing get for Deployment: "test-museum-chartmuseum"
[kube] 2018/11/29 12:46:06 get relation pod of object: chartmuseum/Deployment/test-museum-chartmuseum
[kube] 2018/11/29 12:46:06 Doing get for Ingress: "test-museum-chartmuseum"
[kube] 2018/11/29 12:46:07 get relation pod of object: chartmuseum/Ingress/test-museum-chartmuseum
[storage] 2018/11/29 14:29:26 listing all releases with filter
[tiller] 2018/11/29 14:29:27 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:32:08 listing all releases with filter
[tiller] 2018/11/29 14:32:08 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:33:23 listing all releases with filter
[tiller] 2018/11/29 14:33:23 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:35:14 listing all releases with filter
[tiller] 2018/11/29 14:35:14 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:42:11 listing all releases with filter
[tiller] 2018/11/29 14:42:12 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:43:57 listing all releases with filter
[tiller] 2018/11/29 14:43:58 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:45:50 listing all releases with filter
[tiller] 2018/11/29 14:45:50 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:48:45 listing all releases with filter
[tiller] 2018/11/29 14:48:45 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:49:13 listing all releases with filter
[tiller] 2018/11/29 14:49:14 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:53:18 listing all releases with filter
[tiller] 2018/11/29 14:53:18 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 14:59:12 listing all releases with filter
[tiller] 2018/11/29 14:59:13 partitioned at 20914200 with 81 releases (cap=20971516)
[storage] 2018/11/29 15:09:10 listing all releases with filter
[tiller] 2018/11/29 15:09:10 partitioned at 20914200 with 81 releases (cap=20971516)
```

**Comment by whereisaaron** [comment] 2019-02-13 19:21
We are seeing performance degradation over time on older clusters. Every execution of `helm upgrade` or `helm list` is churning the API servers and causes 1-2 GB additional RAM use. Chaining command just keeps allocating more RAM. Waiting a decent period of time allows some RAM to be released.

This command a one cluster took a while and there are 3.5k ConfigMaps. Each is 1MB max, so up to 3.5GB data. The most frequently deployed application has >1000 revisions.
```
$ kubectl -n kube-system get cm --no-headers -l OWNER=TILLER | wc -l
3417
```

It sounds like redeploying with something reasonable for `--history-max` is out best option to stabling these clusters.

**Comment by bacongobbler** [comment] 2019-02-13 19:33
Closing as a duplicate of #4543 so we can keep the conversation in one ticket. Thanks.

**Closed by bacongobbler** 2019-02-13 19:33 UTC
Labels: question/support

**Comment by rvgud** [comment] 2020-05-10 05:02
This might help if anyone facing such issue: -https://medium.com/@ravindrashekhawat5876/helm-tiller-timeout-issue-be5faed6ecea
