### ISSUE TITLE
Question: is it possible for `helm ls --failed` to not look at history ?

### ISSUE THREAD

**Issue by eddycharly** [helm/helm#8319] opened 2020-06-16 11:35 UTC
I use helm v3 (v3.2.4) and when i look at the history of a release:

```
REVISION	UPDATED                 	STATUS    	CHART     	APP VERSION	DESCRIPTION                                               
1       	Tue Jun 16 13:02:35 2020	superseded	toto-0.1.0	1.16.0     	Install complete                                          
2       	Tue Jun 16 13:03:59 2020	failed    	toto-0.1.0	1.16.0     	Upgrade "toto" failed: timed out waiting for the condition
3       	Tue Jun 16 13:04:59 2020	superseded	toto-0.1.0	1.16.0     	Rollback to 1                                             
4       	Tue Jun 16 13:06:31 2020	failed    	toto-0.1.0	1.16.0     	Upgrade "toto" failed: timed out waiting for the condition
5       	Tue Jun 16 13:11:32 2020	superseded	toto-0.1.0	1.16.0     	Rollback to 3                                             
6       	Tue Jun 16 13:12:13 2020	failed    	toto-0.1.0	1.16.0     	Upgrade "toto" failed: timed out waiting for the condition
7       	Tue Jun 16 13:17:13 2020	deployed  	toto-0.1.0	1.16.0     	Rollback to 5                                             
```

Running `helm ls --failed` shows the release though it's not in failed state but in the deployed state:

```
NAME	NAMESPACE	REVISION	UPDATED                              	STATUS	CHART     	APP VERSION
toto	default  	6       	2020-06-16 13:12:13.481543 +0200 CEST	failed	toto-0.1.0	1.16.0     
```

Is this possible to get the list of releases in failed state only for the latest revision ?

I also tried setting `--max 1` but it doesn't change the result.

**Comment by hickeyma** [comment] 2020-06-16 12:02
@eddycharly Can you show the output of `helm ls --failed` as the output shown above is 

```
NAME	NAMESPACE	REVISION	UPDATED                              	STATUS	CHART     	APP VERSION
toto	default  	6       	2020-06-16 13:12:13.481543 +0200 CEST	failed	toto-0.1.0	1.16.0     
```

which is failed

**Comment by eddycharly** [comment] 2020-06-16 12:05
This is the output of `helm ls --failed`:

```
NAME	NAMESPACE	REVISION	UPDATED                              	STATUS	CHART     	APP VERSION
toto	default  	6       	2020-06-16 13:12:13.481543 +0200 CEST	failed	toto-0.1.0	1.16.0     
```

But as you can see it's revision `6`, the real release status is `deployed` (revision 7).

**Comment by hickeyma** [comment] 2020-06-16 12:08
Sorry but I am confused. You are passing `--failed` flag and getting a failed revision which is 6. Is that what should happen or am I not getting your point?

**Comment by eddycharly** [comment] 2020-06-16 12:14
Sorry, maybe i'm not clear.

I don't consider the release to be in failed state as it is at revision 7 and the status is `deployed`.

Though when i `helm ls --failed`, the release shows up because it failed at revision 6 but i don't mind the past revisions, i just want to know what releases are in failed state now.

Does it make sense ? What's the point of showing a release that is now in a non failed state but that failed in the past ?
And do we have a way to tell `helm ls` to ignore past revisions ?

**Comment by eddycharly** [comment] 2020-06-16 12:48
@hickeyma i am pretty sure it didn't behave this way in helm v2.

**Comment by hickeyma** [comment] 2020-06-16 13:13
That is what the `failed` flag is for:

```
--failed           show failed releases
```

Otherwise, without flags `helm ls` will show the latest deployed or failed release. By using the flag, you are asking to show the last failed release.

**Comment by eddycharly** [comment] 2020-06-16 13:21
Ok, thanks.
I  found it very confusing because it takes past revisions into account and i didn't expect that. I had the feeling that working with past revisions would be a job for `helm history`.

Now it seems to be quite hard to tell if a specific release is currently in failed state (in a bash script). I used to `helm ls --failed --filter ^toto$` and if it returned nothing it was not in failed state.

**Comment by marckhouzam** [comment] 2020-06-17 23:55
This looks like a duplicate of #7495 and a PR addressing it was posted in #8282

**Comment by hickeyma** [comment] 2020-06-18 07:37
Duplicate of #7495

**Comment by hickeyma** [comment] 2020-06-18 07:38
Thanks for heads up @marckhouzam.

@eddycharly I will close this issue as a duplicate of #7495. If you want to comment further add it to that issue. Thanks.

**Closed by hickeyma** 2020-06-18 07:38 UTC
Labels: question/support

**Comment by eddycharly** [comment] 2020-06-18 10:40
Thanks !
Nice to know it is actually an issue and not the expected behavior.

**Comment by hickeyma** [comment] 2020-06-18 11:13
Sorry @eddycharly, I meant to get a response back to you that you were right that the flag seemed to be working incorrectly. Just got distracted. Its good Marc got in here.
