### ISSUE TITLE
Error when creating custom resource instance from post-install hook 

### ISSUE THREAD

**Issue by j-kaplan** [helm/helm#3396] opened 2018-01-25 20:07 UTC
I have a helm chart that creates an instance of a previously registered custom resource definition which fails with an error only when creating it as a post-install hook. 

> Error: unable to decode "": no kind "RabbitRestore" is registered for version "rabbit.my.domain.com/v1alpha1"

This results in a release marked as failed. However the custom resource object **does** get created successfully in Kubernetes.

This error does not occur if I remove the hook annotation from the resource template.

You can see that the api version is properly registered:
```
$ kubectl api-versions
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1beta1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
policy/v1beta1
rabbit.my.domain.com/v1alpha1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
servicecatalog.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

This happens on Helm v2.7.2 and v2.8.0 with K8s v1.8.5 and v.1.9.1.

**Comment by j-kaplan** [comment] 2018-01-25 21:31
Relevant tiller logs:

> [storage] 2018/01/24 23:25:37 creating release "sartorial-dingo.v1"
> [kube] 2018/01/24 23:25:37 building resources from manifest
> [kube] 2018/01/24 23:25:37 creating 7 resource(s)
> [tiller] 2018/01/24 23:25:38 executing 1 post-install hooks for sartorial-dingo
> [kube] 2018/01/24 23:25:38 building resources from manifest
> [kube] 2018/01/24 23:25:38 creating 1 resource(s)
> [tiller] 2018/01/24 23:25:38 warning: Release sartorial-dingo post-install rabbitmq-ha/templates/restore.yaml could not complete: unable to decode "": no kind "RabbitRestore" is registered for version "rabbit.my.domain.com/v1alpha1"
> [tiller] 2018/01/24 23:25:38 warning: Release "sartorial-dingo" failed post-install: unable to decode "": no kind "RabbitRestore" is registered for version "rabbit.my.domain.com/v1alpha1"
> [storage] 2018/01/24 23:25:38 updating release "sartorial-dingo.v1"
> [tiller] 2018/01/24 23:25:38 failed install perform step: unable to decode "": no kind "RabbitRestore" is registered for version "rabbit.my.domain.com/v1alpha1"

**Comment by j-kaplan** [comment] 2018-01-26 00:24
I have created a example CRD + chart that shows the failure when using a hook, as well as the successful creation without the hook: https://github.com/j-kaplan/test-chart

**Comment by bacongobbler** [comment] 2018-01-31 09:23
Closing this as a duplicate of #2994.

**Comment by j-kaplan** [comment] 2018-01-31 15:33
@bacongobbler I do not believe this to be a duplicate of #2994. I saw that issue previously and that is a timing issue related to registering a new CRD and attempting to create an instance of that resource in the same chart. In my scenario the CRD is already registered in Kubernetes, prior to calling helm, and the chart simply creates a new instance of that resource (like it was any other built-in resource in K8s). 

Can we reopen this issue?

**Comment by clement-buchart** [comment] 2018-04-04 09:36
Hello, 

I encountered the same issue with another CRD
`Error: unable to decode "": no kind "Recovery" is registered for version "stash.appscode.com/v1alpha1"`

Just wanted to add that manually creating the ressource from the yaml generated from a helm install --dry-run works successfully.

**Comment by clement-buchart** [comment] 2018-04-04 09:54
Apparently fixed by https://github.com/kubernetes/helm/pull/3736

**Comment by rtnpro** [comment] 2019-02-08 18:05
This issue is still persistent.

**Comment by HarishHothi** [comment] 2019-05-03 07:27
Hi @rtnpro Which helm version are you using? I was facing similar issue in helm 2.11.X. On Tiller upgrade to v2.13.1 it fixed the issue. You can try by upgrading tiller to 2.13.1
`export TILLER_TAG=v2.13.1
kubectl --namespace=kube-system set image deployments/tiller-deploy tiller=gcr.io/kubernetes-helm/tiller:$TILLER_TAG
`

**Comment by bacongobbler** [comment] 2019-12-09 17:14
Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!

**Closed by bacongobbler** 2019-12-09 17:14 UTC
Labels: question/support

**Comment by bacongobbler** [comment] 2019-12-09 17:16
Note: use the `crd-install` hook for Helm 2, or the `crds/` directory in Helm 3 when installing CRDs going forward. These features handle some of the odd edge cases around CRD creation that pre-install hooks cannot accomodate.
