### ISSUE TITLE
Helm Test should offer the option of returning pod logs

### ISSUE THREAD

**Issue by alanmeadows** [helm/helm#5169] opened 2019-01-15 18:19 UTC
It is generally desirable to run helm tests using --cleanup, especially in an automated environment.

This helps ensure that all tests are properly removed after they have been executed.

The one drawback to this option is that you cannot retrieve the pod logs for failed tests - which is effectively a requirement where development is occurring.  You need to know why the test failed and the pod logs are paramount.

I am confused why do we direct the end user to go and retrieve the logs when a test has failed, e.g.: 

https://github.com/helm/helm/blob/master/pkg/releasetesting/environment.go#L98-L100

Couldn't we simply `env.KubeClient` fetch the logs and return them right here on their behalf? This would allow users who are interested in the logs to use --cleanup which would be an optimal setup for how automated systems would use `helm test`

**Comment by alanmeadows** [comment] 2019-01-15 20:18
Looks like this is already covered in https://github.com/helm/helm/issues/3279

**Comment by hickeyma** [comment] 2019-01-16 09:32
> Looks like this is already covered in #3279

As you have mentioned, I think your use case is covered.

@alanmeadows Can this issue be close as a duplicate of #3279 ?

**Closed** 2019-01-17 00:37 UTC

**Comment by SlickNik** [comment] 2019-01-17 00:39
Closing this as a duplicate of #3279 
@alanmeadows Thanks for reporting this, and let us know if there's something that isn't covered by #3279, for which you'd like this issue re-opened. Thanks!
