### ISSUE TITLE
Helm fails to fetch a chart on a different drive

### ISSUE THREAD

**Issue by EPinci** [helm/helm#8003] opened 2020-04-27 08:38 UTC
Latest helm fails to fetch a chart to a local folder on a drive different that the one with the user home folder.

```
PS D:\K> helm fetch stable/nginx-ingress
Error: rename C:\Users\User\AppData\Local\Temp\nginx-ingress-1.36.3.tgz359178311 nginx-ingress-1.36.3.tgz: The system cannot move the file to a different disk drive.       
```

Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS (not relevant)

**Comment by bacongobbler** [comment] 2020-04-27 13:42
Duplicate of #7987.

**Closed by bacongobbler** 2020-04-27 13:42 UTC
