### ISSUE TITLE
Helm repo information should be part of the release metadata

### ISSUE THREAD

**Issue by dabde** [helm/helm#8728] opened 2020-09-14 14:20 UTC
hi,

didn't found any related open issue for that.

Short: A reference to the origin chart repo would be nice in the release metadata.

Issue: It's currently not possible to track back the repo, where the installed chart comes from. If you working with multiple repo's, you can't automate check if your chart is maybe outdated, related to chart name collisions.

h2. Example:
Chart: elasticsearch
Repos: 
* Bitnami --> bitnami/elasticsearch         	12.6.3
* elastico --> elastic/elasticsearch         	7.9.1
* default --> stable/elasticsearch         	1.32.5

If you now installing the elastico chart, want to know after some time, if you should update to a newer version. You maybe get a false catch with the bitnami one. If you automate this process, like in https://github.com/fabmation-gmbh/helm-whatup ... it's now with helm3 impossible.

I also didn't find yet another way to doing this, without complicating everything. So would be nice if we can add the repo as additional metadata file to a release.

Thanks.

**Comment by bacongobbler** [comment] 2020-09-14 15:38
duplicate of https://github.com/helm/helm/issues/4256.

**Closed by bacongobbler** 2020-09-14 15:38 UTC
