### ISSUE TITLE
Incorrect casting of values contained in YAML files provided via install/upgrade --values flag

### ISSUE THREAD

**Issue by joeauty** [helm/helm#4541] opened 2018-08-27 22:50 UTC
Hello, it looks like Helm needs a way to ensure string parsing for values stored in YAML and read via the `-f` install/upgrade flag. For example, a git commit such as `01443e5` represented in a values.yaml file is being interpreted as `1.443e+08`.

It looks like YAML such as:

```
tag: 01443e5
```

is perfectly legal YAML, but it seems to throw the Helm 2.9.1 YAML parser.

**Comment by bacongobbler** [comment] 2018-08-27 23:39
Can you try using the `--set-string` flag instead? There's a known parser bug that coerces integers into scientific notation (see #1707).

Closing as a duplicate of #1707 but please let me know if I'm mistaken and I'll happily re-open this. Thanks!

**Comment by joeauty** [comment] 2018-08-28 01:02
--set-string is working fine for me, but I was hoping to read the values directly from my YAML file, i.e.:

`helm upgrade <release name> -f /path/to/value/overrides.yml`

**Comment by joeauty** [comment] 2018-08-28 15:43
@bacongobbler sorry to bother you, but providing this description makes sense I'd love to have this re-opened because it would be lovely to fix this. I'm not happy with my hack workarounds!

**Comment by bacongobbler** [comment] 2019-12-09 19:36
Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!

**Closed by bacongobbler** 2019-12-09 19:36 UTC
Labels: question/support
