### ISSUE TITLE
Error validating routes

### ISSUE THREAD

**Issue by GolanTrevize10** [helm/helm#7041] opened 2019-11-21 10:26 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-02-22T07:05:30Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift on prem

When I try to run helm upgrade I am getting this error

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route

With the beta version it works.

**Comment by SLepUbIn** [comment] 2019-11-21 14:06
got the same here : 

version is : 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Validation failed on weight and status : 
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Route.spec.to): missing required field "weight" in com.github.openshift.api.route.v1.RouteTargetReference, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]
helm.go:76: [debug] error validating "": error validating data: [ValidationError(Route.spec.to): missing required field "weight" in com.github.openshift.api.route.v1.RouteTargetReference, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]
helm.sh/helm/v3/pkg/kube.scrubValidationError
	/home/circleci/helm.sh/helm/pkg/kube/client.go:520
helm.sh/helm/v3/pkg/kube.(*Client).Build
	/home/circleci/helm.sh/helm/pkg/kube/client.go:135
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:229
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:209
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:111
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:231
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:209
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:111
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by bacongobbler** [comment] 2019-11-22 19:22
It looks like those fields are required as per openshift's OpenAPI specification. I'd open an issue over with OpenShift, asking whether these fields are required for manifests to provide.

**Comment by bacongobbler** [comment] 2019-11-22 19:28
reference documentation for a `v1.Route` can be found here: https://docs.openshift.com/container-platform/3.5/rest_api/openshift_v1.html#v1-route

**Comment by SLepUbIn** [comment] 2019-11-25 08:31
Thanks @bacongobbler , actually an issue for this has already been opened on openshift's side https://github.com/openshift/origin/issues/24060

**Comment by bacongobbler** [comment] 2019-11-25 08:39
thanks! Closing as a duplicate of https://github.com/helm/helm/issues/6830.

**Closed by bacongobbler** 2019-11-25 08:39 UTC
Labels: question/support
