### ISSUE TITLE
CRD added in crd-install hook may not exist before manifest validation

### ISSUE THREAD

**Issue by jarekgorski** [helm/helm#5093] opened 2018-12-21 09:27 UTC
Helm install with CRD in crd-install hook sometimes fails because manifest validation occurs immediately after requesting CRD creation in K8S. 
Sometimes K8S API server still processes the requests and there is a race condition - since we cannot watch CRD creation before manifest validation and resources may not be created yet.
The proposal is to check if CRD exists (not through watch but in a different way) before manifest validation.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
OpenStack

**Comment by bacongobbler** [comment] 2019-01-11 20:07
dupe of #4925 which is being fixed via #5112. Thanks!

**Closed by bacongobbler** 2019-01-11 20:07 UTC
