### ISSUE TITLE
helm version  error  Permission denied

### ISSUE THREAD

**Issue by anstns** [helm/helm#8303] opened 2020-06-12 03:24 UTC
Output of `v2.16.8`:

Output of `v1.17.2`:

Cloud Provider/Platform RKE-Rancher: 

helm version  error

0612 11:21:07.594572     186 portforward.go:400] an error occurred forwarding 55924 -> 44134: error forwarding port 44134 to pod 63de3e31198340b2492072e7fbb71cd0676722eef6ac9e895118a2673d0d4166, uid : exit status 1: 2020/06/12 03:21:07 socat[143048] E connect(5, AF=2 127.0.0.1:44134, 16): Permission denied

**Comment by bridgetkromhout** [comment] 2020-06-15 20:12
Hi, @anstns! It sounds like you are using Helm 2 and getting a tiller error. It looks like Rancher is recommending Helm 3 at this point, but this might help with Helm 2: https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/

Usually an error like this means that you're not successfully passing traffic via socat. I suggest checking the RKE docs for their recommended configuration.

**Comment by bacongobbler** [comment] 2020-06-24 21:28
duplicate of https://github.com/helm/helm/issues/1371.

**Closed** 2020-06-24 21:28 UTC
Labels: question/support, v2.x

**Comment by bacongobbler** [comment] 2020-06-24 21:31
closing as an issue related to the setup documentation for rancher. There's nothing we can do on our end here. Please have a look at the link @bridgetkromhout recommended and reach out to the rancher folks if you're having further issues. Thanks.
