### ISSUE TITLE
Helm 3.16.0 broke 'dep up' for charts.jetstack.io / cert-manager

### ISSUE THREAD

**Issue by MaxWinterstein** [helm/helm#13325] opened 2024-09-12 14:16 UTC
Since `3.16.0` I can't use a local chart that depends on a chart from @jetstack - which worked well before.

Error:
```
...Successfully got an update from the "https://charts.jetstack.io" chart repository
Saving 1 charts
Downloading cert-manager from repo https://charts.jetstack.io
Save error occurred:  could not download charts/cert-manager-v1.15.3.tgz: repo charts not found
Error: could not download charts/cert-manager-v1.15.3.tgz: repo charts not found
```

I don't know where the difference is for that particular repo, all others work fine for us.

The `index.yaml` seems to be fine at least:

```bash
# curl -s https://charts.jetstack.io/index.yaml | head
apiVersion: v1
entries:
  cert-manager:
  - annotations:
      artifacthub.io/category: security
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "true"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
```

I can reproduce this easy 

```Dockerfile
FROM ubuntu as base

RUN apt update && apt install -y curl
COPY <<EOF /tmp/Chart.yaml
apiVersion: v2
name: my-cert-manager
version: 1.16.0

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.15.3
EOF

WORKDIR /tmp

FROM base as working

RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | DESIRED_VERSION=v3.15.4 bash
RUN helm dep up

FROM base as broken

RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | DESIRED_VERSION=v3.16.0 bash
RUN helm dep up
```

**Comment by mattfarina** [comment] 2024-09-12 14:26
The change that caused the regression was https://github.com/helm/helm/pull/11726

**Comment by mattfarina** [comment] 2024-09-12 15:09
This is a duplicate of #13324. Closing as that one is the primary issue.

Note, a PR has already been created to fix the issue and we are planning an emergency release to fix the regression.

**Closed by mattfarina** 2024-09-12 15:09 UTC
