### ISSUE TITLE
Support for using {{ values }} within values.yaml

### ISSUE THREAD

**Issue by DrEsteban** [helm/helm#2133] opened 2017-03-17 02:19 UTC
For example:

**values.yaml**
```
myApp:
  fooServiceName: {{ .Release.Name }}-foo-service
```

It seems like it would be a common pattern to incorporate {{ .Chart.Name }} or {{ .Release.Name }} into some variables.  I got the following when I tried this:

```
error converting YAML to JSON: yaml: line 15: did not find expected key
```

### Edit
To better illustrate my issue, consider a Chart with the following structure:

**serviceA Chart directory structure:**
```
charts/
    serviceB/
        templates/
            serviceB.yaml
        Chart.yaml
templates/
    serviceA.yaml
Chart.yaml
<etc...>
```

**serviceB.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: <b><i>{{ .Release.Name }}-service-b</i></b>
spec:
  <...spec...>
</pre>

--------------
Now, currently if I want `serviceA` to make calls to `serviceB`, I would have to do something like this:
**serviceA.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  containers:
    - env:
        - name: SERVICE_B_HOSTNAME
          value: <b><i>{{ .Release.Name }}-{{ .Values.serviceB }}</i></b>
</pre>
**values.yaml**
<pre>
serviceB: <b><i>service-b</i></b>
</pre>
--------------
When I'd _like_ to be able to do something like this:
**serviceA.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  containers:
    - env:
        - name: SERVICE_B_HOSTNAME
          value: <b><i>{{ .Values.serviceB }}</i></b>
</pre>
**values.yaml**
<pre>
serviceB: <b><i>{{ .Release.Name }}-service-b</i></b>
</pre>
--------------

**Comment by technosophos** [comment] 2017-03-17 19:38
We have talked about supporting these as environment variables (e.g. `$RELEASE_NAME`, `$CHART_NAME`, etc). 

However, the file that is passed into the template engine as a source of data for templates is itself not passed through the template engine. We almost definitely will not do that because it gets very confusing for users. It also breaks both standard YAML compatibility and backward compatibility with all existing Helm versions.

**Comment by thomastaylor312** [comment] 2017-03-30 03:15
@DrEsteban Did you have anything else you wanted to discuss or anything that @technosophos didn't address? If not, we are going to close this

**Comment by DrEsteban** [comment] 2017-03-30 17:38
@thomastaylor312 Apologies, yes one more question.

@technosophos Makes sense, thanks for the reasoning. As for the "environment variables support", do you mean automatically including `$RELEASE_NAME` or `$CHART_NAME` in the list of environment variables for a pod? Or something else? I'm just trying to determine how it relates to this issue of being able to specify values-within-values.

To better illustrate my issue, consider a Chart with the following structure:

**serviceA Chart directory structure:**
```
charts/
    serviceB/
        templates/
            serviceB.yaml
        Chart.yaml
templates/
    serviceA.yaml
Chart.yaml
<etc...>
```

**serviceB.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: <b><i>{{ .Release.Name }}-service-b</i></b>
spec:
  <...spec...>
</pre>

--------------
Now, currently if I want `serviceA` to make calls to `serviceB`, I would have to do something like this:
**serviceA.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  containers:
    - env:
        - name: SERVICE_B_HOSTNAME
          value: <b><i>{{ .Release.Name }}-{{ .Values.serviceB }}</i></b>
</pre>
**values.yaml**
<pre>
serviceB: <b><i>service-b</i></b>
</pre>
--------------
When I'd _like_ to be able to do something like this:
**serviceA.yaml**
<pre>
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  containers:
    - env:
        - name: SERVICE_B_HOSTNAME
          value: <b><i>{{ .Values.serviceB }}</i></b>
</pre>
**values.yaml**
<pre>
serviceB: <b><i>{{ .Release.Name }}-service-b</i></b>
</pre>
--------------

It means the templates of parent charts _must_ adhere to/adopt the naming conventions of child charts, rather than allowing the parent templates to be independent of child naming conventions, and allowing Values.yaml to configure the entirety.  If I decide to deploy serviceB separately from serviceA, I must edit the actual serviceA.yaml template to remove the `{{ .Release.Name }}` section instead of simply editing the values passed in.

Would the proposed "environment variables support" do anything to help with that?

**Comment by DrEsteban** [comment] 2017-03-31 15:52
@thomastaylor312 Apologies, yes one more question.

@technosophos Makes sense, thanks for the reasoning. As for the "environment variables support", do you mean automatically including those in the list of environment variables for a pod? Or something else? I'm just trying to determine how it relates to

**Comment by DrEsteban** [comment] 2017-03-31 15:55
Oops, clicked the wrong button...

**Comment by markpundsack** [comment] 2017-05-15 19:37
Sharing variables between parent and child is bad enough,  but it gets worse when you have a dependency tree with children that need to share variables between them as peers. 

e.g. for `gitlab-bundle`, I want a `values.yaml` something like":

```
baseDomain: your-domain.com
gitlab:
  ingress:
    hosts:
      - gitlab.{{ .Values.baseDomain }}
      - registry.{{ .Values.baseDomain }}
      - mattermost.{{ .Values.baseDomain }}
      - prometheus.{{ .Values.baseDomain }}
gitlab-runner:
  gitlabUrl: http://gitlab.{{ .Values.baseDomain }}
```

**Comment by dsanders1234** [comment] 2017-08-18 23:14
I hit this problem trying to configure a default prometheus datasource for grafana using the charts under "stable".  Grafana expects a url to the service, but I have no way of providing a release name prefix to the service name in the values yaml.

**Comment by mkjpryor-stfc** [comment] 2017-08-21 08:11
@dsanders1234 I have exactly the same problem.

In fact, this is a problem any time you try to build a meta-package with packages from other repositories as requirements, as they tend to use `{{ .Release.Name }}` in their service names. This means you can't automatically configure the linkages.

It would be really nice to at least be able to access the release name and namespace in `values.yaml`. Without it, building meta-packages is pretty much impossible...

**Comment by paulczar** [comment] 2017-09-26 15:01
I have similar issues as well.  I am trying to pass in a k8s dns for cassandra child package which is dependent on {{ .Release.Name }} and {{ .Release.Namespace }}.

**Comment by hobti01** [comment] 2017-10-06 08:31
We are also having this issue to create "fully qualified" names for subcharts that are known to the parent and child.  We can workaround this by (re)creating all the charts ourselves, but this defeats the purpose of packaged and shared charts.

**Comment by jrefi** [comment] 2017-10-23 19:17
This issue is also affecting me in a similar manner to those above. I am trying to create a meta-package and need to pass a base host name to all subcharts to use to define their Ingress resources. Looks like I will have to rewrite all the charts I want to use myself.

**Comment by tlyng** [comment] 2017-10-26 08:29
Also affecting me. I am having nginx-ingress as a dependency for one of my charts and I want to set up tcp forwarding, but the nginx-ingress require to know the service name upfront which I am not able to provide in values.yaml.

**Comment by zdannar** [comment] 2018-01-12 16:30
+ 1 for this feature.  Having to hard code values into additional templates for service discovery seems wrong.  I am integrating vault with consul and need to know the consul service name which is set to <release>-consul by the stable/consul chart.

**Comment by mkjpryor-stfc** [comment] 2018-01-17 18:40
@swed: I am aware of YAML anchors, and have used them in the past for repeated bits of config. However, they don't help you with the main reason for this issue which is to get things like the release name without having to hard code it.

**Comment by ralekseenkov** [comment] 2018-02-06 18:36
We actually hit the same limitation and ended up implementing our own layer around Helm to glue services together. You can traverse the entire service tree by using `{{ .Discovery }}` variable and get access to dependent & peer services' data.

If you want to take a look, here is an example that brings up multiple instances kafka, spark, hdfs, zookeeper and twitter-based analytics around them. All from Helm charts:

* here is how "serviceA" can expose a variable:
https://github.com/Aptomi/aptomi/blob/master/examples/twitter-analytics/policy/Frank/kafka.yaml#L17

* here is how "serviceB" can rely on a variable exposed by "serviceA":
https://github.com/Aptomi/aptomi/blob/master/examples/twitter-analytics/policy/John/twitter_stats.yaml#L38

* demo:
https://asciinema.org/a/k8ZpQTazoSaDV24fiLbG7DfT9?speed=2

**Comment by bradenwright** [comment] 2018-03-19 04:38
I think this is the same as: https://github.com/kubernetes/helm/issues/2492 and it looks like there is a pr mentioned over there: https://github.com/kubernetes/helm/pull/3252

**Comment by bacongobbler** [comment] 2018-08-14 16:37
closing as a duplicate of #2492.

**Closed by bacongobbler** 2018-08-14 16:37 UTC
Labels: proposal

**Comment by DrEsteban** [comment] 2018-08-14 17:27
Interesting that _my_ issue, filed several months earlier, was the "duplicate" ;)  I understand... #2492 is a lot better described.

**Comment by cep21** [comment] 2020-02-12 06:11
@markpundsack Did you ever get a solution for https://github.com/helm/helm/issues/2133#issuecomment-301581084 ? I'm sorry to resurrect this issue, but it's exactly the problem I have and I can't find a solution in this thread or https://github.com/helm/helm/issues/2492

**Comment by markpundsack** [comment] 2020-02-18 20:34
@cep21 I never found a solution that worked well.

**Comment by MilanMasek** [comment] 2020-02-21 15:14
:) Thankfully, latest Helm manual says how to achieve this.
https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function

The trick is enclosing variable in `"` or in yaml block `|-`, and than referencing it in a template as `{{ tpl .Values.variable . }}`
This seems to make Helm happy.

Example:
```
$ cat Chart.yaml | grep appVersion
appVersion: 0.0.1-SNAPSHOT-d2e2f42


$ cat platform/shared/t/values.yaml | grep -A2 image:
image: 
  tag: |-
    {{ .Chart.AppVersion }}


$ cat templates/deployment.yaml | grep image:
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"


$ helm template . --values platform/shared/t/values.betradar.yaml | grep image
          image: "docker-registry.default.svc:5000/namespace/service:0.0.1-SNAPSHOT-d2e2f42"
          imagePullPolicy: Always
      image: busybox
```

Otherwise there is an error thrown..
```
$ cat platform/shared/t/values.yaml | grep -A1 image:
image: 
  tag: {{ .Chart.AppVersion }}

1 $ helm template . --values platform/shared/t/values.yaml | grep image
Error: failed to parse platform/shared/t/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.AppVersion":interface {}(nil)}
```

**Comment by TBBle** [comment] 2020-03-13 10:37
@MilanMasek 's solution won't work in general for subcharts, because the context `.` passed into `tpl` will have the subchart's values, not the parent chart's values.

It happens to work in the specific example this ticket was opened for, because `.Release.Name` should be the same in all the subcharts. It won't work for `.Chart.AppVersion` as in the `tpl` example.

There was a proposal to support `tval` in #3252 for interpolating templates in values files, but that was dropped in favour of a lua-based Hook system which has been proposed for Helm v3: https://github.com/helm/helm/issues/2492#issuecomment-413635332

**Comment by zhangpengchen** [comment] 2020-07-29 14:40
> See also #2514.
> 
> :) Thankfully, latest Helm manual says how to achieve this.
> https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
> 
> The trick is enclosing variable in `"` or in a yaml block `|-`, and than referencing it in a template as `{{ tpl .Values.variable . }}`
> This seems to make Helm happy.
> 
> Example:
> 
> ```
> $ cat Chart.yaml | grep appVersion
> appVersion: 0.0.1-SNAPSHOT-d2e2f42
> 
> 
> $ cat platform/shared/t/values.yaml | grep -A2 image:
> image: 
>   tag: |-
>     {{ .Chart.AppVersion }}
> 
> 
> $ cat templates/deployment.yaml | grep image:
>           image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
> 
> 
> $ helm template . --values platform/shared/t/values.betradar.yaml | grep image
>           image: "docker-registry.default.svc:5000/namespace/service:0.0.1-SNAPSHOT-d2e2f42"
>           imagePullPolicy: Always
>       image: busybox
> ```
> 
> Otherwise there is an error thrown..
> 
> ```
> $ cat platform/shared/t/values.yaml | grep -A1 image:
> image: 
>   tag: {{ .Chart.AppVersion }}
> 
> 1 $ helm template . --values platform/shared/t/values.yaml | grep image
> Error: failed to parse platform/shared/t/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.AppVersion":interface {}(nil)}
> ```

Thanks @MilanMasek that quote save my hours.

**Comment by TBBle** [comment] 2020-07-29 14:56
For people still tracking this request, the current way forward appears to be #6876, which is apparently under review.

**Comment by TBBle** [comment] 2020-08-29 02:20
There's also #8580 which is a similar approach to the problem as #6876. See #8576 for some discussion on the differences.

**Comment by ramandeep-singh-1983** [comment] 2020-09-22 13:54
I was facing the same issue i.e. passing a value set by user using --set to subchart. This came to my rescue:
`helm install --set subchartname.subchartkey=myvalue`

**Comment by bluebrown** [comment] 2022-02-15 20:35
> See also #2514.
> 
> :) Thankfully, latest Helm manual says how to achieve this. https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function
> 
> The trick is enclosing variable in `"` or in a yaml block `|-`, and than referencing it in a template as `{{ tpl .Values.variable . }}` This seems to make Helm happy.
> 
> Example:
> 
> ```
> $ cat Chart.yaml | grep appVersion
> appVersion: 0.0.1-SNAPSHOT-d2e2f42
> 
> 
> $ cat platform/shared/t/values.yaml | grep -A2 image:
> image: 
>   tag: |-
>     {{ .Chart.AppVersion }}
> 
> 
> $ cat templates/deployment.yaml | grep image:
>           image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
> 
> 
> $ helm template . --values platform/shared/t/values.betradar.yaml | grep image
>           image: "docker-registry.default.svc:5000/namespace/service:0.0.1-SNAPSHOT-d2e2f42"
>           imagePullPolicy: Always
>       image: busybox
> ```
> 
> Otherwise there is an error thrown..
> 
> ```
> $ cat platform/shared/t/values.yaml | grep -A1 image:
> image: 
>   tag: {{ .Chart.AppVersion }}
> 
> 1 $ helm template . --values platform/shared/t/values.yaml | grep image
> Error: failed to parse platform/shared/t/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Chart.AppVersion":interface {}(nil)}
> ```

Can you do that with third party charts? I would assume this requires said third party to call tpl on the value you are using template syntax with, which is unlikely. If I am in control of the chart myself. Id probably had a number of other fixes.

**Comment by TBBle** [comment] 2022-02-15 20:52
Yes, that depends on the third party chart to be calling `tpl` on various values it receives. I've noticed for example that the Bitnami charts are quite liberal in doing that, I guess partly because they are built using a lot of templates anyway.

So if you find a third-party chart that doesn't call `tpl` on a value you need it to call `tpl` on, perhaps open it with them as a feature request.

**Comment by lazychanger** [comment] 2022-10-14 03:04
I submitted a plugin to override values.yaml with additional templates.

[helm-viv](https://github.com/lazychanger/helm-viv)
[example](https://github.com/lazychanger/helm-viv/tree/master/example/simple-example)

**Comment by edmondop** [comment] 2022-12-28 02:31
This won't work however when you try to pass value down to children charts https://github.com/helm/helm/issues/2133#issuecomment-1040766731

**Comment by antyung148** [comment] 2023-01-27 14:40
ChatGPT tells me it doesn't work

<img width="806" alt="Screenshot 2023-01-27 at 10 38 05 PM" src="https://user-images.githubusercontent.com/117553596/215113160-dd162d4c-f77a-4cba-af33-1e61d767ae29.png">

**Comment by venkatesh3889** [comment] 2023-07-05 06:11
any suggestion how we can handle "{{ .Values.images.abc-load-test }}"  hyphen(-). it's failing.

**Comment by TBBle** [comment] 2023-07-05 07:15
You'll have to use something like [`{{ get $Values.images "abc-load-test" }}`](https://helm.sh/docs/chart_template_guide/function_list/#get). If you get more complicated, e.g., the hyphenated-key is a dictionary too, you can use [`{{ $Values | dig "images" "abc-load-test" "subkey" }}`](https://helm.sh/docs/chart_template_guide/function_list/#dig) to make things more readable than nested gets.

**Comment by venkatesh3889** [comment] 2023-07-06 05:20
i am little confused here, can you give me some examples if possible? Thanks

**Comment by TBBle** [comment] 2023-07-06 07:42
I'd suggest opening a new ticket if you need further help, since this is a closed ticket and not actually related to your question. In that ticket, you can post more details of what you're trying to do, including an example of what isn't working, and you should be able to get more-detailed help.
