### ISSUE TITLE
helm upgrade failed with error has no deployed releases

### ISSUE THREAD

**Issue by damodhar22** [helm/helm#7160] opened 2019-12-05 11:35 UTC
I tried to do an helm upgrade it failed saying: has no deployed releases. The expected behavior is that it should install the chart as the option **--install** is provided

**helm upgrade --install --force myapp ./test
Error: UPGRADE FAILED: "myapp" has no deployed releases**

Output of `helm version`:v3.0.0

Output of `kubectl version`:v1.15.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by marckhouzam** [comment] 2019-12-05 13:09
I've seen this when there is a failed release. Try doing: `helm list --all-namespaces -a`
That -a flag is important.

**Comment by aaronmell** [comment] 2019-12-08 16:22
I'm curious if this is the correct behavior. If a release is in a failed state it cannot be upgraded. This seems to differ from helm v2, where it was possible to upgrade a failed release. 

Upgrading a release calls this code
https://github.com/helm/helm/blob/65bdd0c48ec77918060aaccb1223d58977eb94ea/pkg/storage/storage.go#L133

and it only queries for releases in a deployed state. So any releases in a failed state would not be returned, and helm will error with the "no deployed releases" message.

**Comment by damodhar22** [comment] 2019-12-09 13:11
> I'm curious if this is the correct behavior. If a release is in a failed state it cannot be upgraded. This seems to differ from helm v2, where it was possible to upgrade a failed release.
> 
> Upgrading a release calls this code, and always passes
> `"status": "deployed",`
> 
> https://github.com/helm/helm/blob/65bdd0c48ec77918060aaccb1223d58977eb94ea/pkg/storage/storage.go#L133
> 
> So any releases in a failed state would not be returned, and helm will error with the "no deployed releases" message.

If upgrading a failed state is not a correct behavior, it should allow install the release as we are giving the option --install

**Comment by mgcrea** [comment] 2019-12-12 14:06
Encountering this as well today, I have a release deployed through helm a few weeks ago and today the release can't be found. Nothing in `helm list --all-namespaces -a`, but the release is properly running.

**Comment by marckhouzam** [comment] 2019-12-12 19:25
@mgcrea did you deploy your release with helm 3 or helm 2?  Helm 3 doesn't see the releases of helm 2, or vice versa.

**Comment by mgcrea** [comment] 2019-12-12 19:27
@marckhouzam it was with helm 3, maybe I did something funky trying to upgrade it. Had a release name === namespace name, not sure if it can cause such kind of issues.

**Comment by hickeyma** [comment] 2019-12-13 08:33
@mgcrea There are breaking changes if releases were deployed using pre GA versions of Helm 3 like alphas, betas, rcs

**Comment by bacongobbler** [comment] 2019-12-17 20:38
closing as a duplicate of https://github.com/helm/helm/issues/5595.

**Closed by bacongobbler** 2019-12-17 20:38 UTC
Labels: question/support

**Comment by abdennour** [comment] 2020-09-29 14:27
fixed by `kubectl -n $namespace delete secret -lstatus=pending-upgrade`
Run now helm again.

**Comment by sajtrus** [comment] 2020-10-20 14:54
I had issues with `helm upgrade` and it lead me here. It was solved by adding `-n <namespace>`. Maybe it will help someone out there.

**Comment by AlbinoDrought** [comment] 2020-10-27 23:18
Similar to @abdennour , `kubectl -n $namespace delete secret -lstatus=pending-install` for me after installing a chart with broken pre-install hooks

**Comment by qb14cj** [comment] 2021-01-14 18:07
@sajtrus Thanks for comment. Added the namespace, and my upgrade executed. @mgcrea Apparently helm runs same as kubectl. To get helm list for a specific namespace, include -n <namespace>. In both cases, for default namespace, leave blank.

**Comment by wasim-nihal** [comment] 2022-09-09 12:32
I had the same issue while trying to upgrade my helm chart using helm client-go package. I was getting the below error each time while trying to upgrade using `func (helmclient.Client).InstallOrUpgradeChart` function of helm client.
`**my-chart-test" has no deployed releases**`

When I did helm list on my namespace, my chart was not listed there. So, I has to explicitly trigger a `helm uninstall my-chart-test -n my-namespace` and install again.
