### ISSUE TITLE
Find repoURL from the  chart or release 

### ISSUE THREAD

**Issue by kgunjikar** [helm/helm#8976] opened 2020-11-03 18:29 UTC
I'm trying to figure out how to get the repoURL given the release . I'm using this sample code 
```


 settings := cli.New()

    actionConfig := new(action.Configuration)
    // You can pass an empty string instead of settings.Namespace() to list
    // all namespaces
    if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), log.Printf); err != nil {
        log.Printf("%+v", err)
        os.Exit(1)
    }

    client := action.NewList(actionConfig)
    // Only list deployed
    client.Deployed = true
    results, err := client.Run()
    if err != nil {
        log.Printf("%+v", err)
        os.Exit(1)
    }

    for _, rel := range results {
```

Looks like Chart.Metadata has "Sources" field but isn't there a back reference to the repoURL? I'm helm noob. 

I'm trying to write a module that will "watch" for new helm charts and try to gather some information on them and report them to a central cluster. 

Output of `helm version`: version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  NA

**Comment by mattfarina** [comment] 2020-11-04 16:00
This is a good question.

A Helm chart is not tied to any remote location. It is entirely possible to take a public chart and copy it into a local location as part of security practices. Some companies do that. Some companies have long kept local copies of packages (like debian and yum ones).

In fact, you can install a release from a chart in one location and upgrade the release from a chart in another location (e.g. a fork).

The `sources` is something you can find in the _Chart.yaml_ file in a chart. It points to application and/or chart source code.

**Comment by mattfarina** [comment] 2020-11-04 16:00
What is it you are trying to do?

**Comment by kgunjikar** [comment] 2020-11-04 17:49
I'm working in a multi-cluster environment and I have to achieve two things

a. Keep track of the charts on the slave cluster by sending all slave cluster chart information to master cluster
b. if required the "admin" on the master cluster migrates this app to another cluster. 

**Constraints**:  User workflows cannot be changed. That means they just launch their apps like they have been given a k8s cluster to work with. 

To migrate an app I need values, version and the repoURL. I can get values and version but looks like repoURL is not there in the chart/release. If I can get the repoURL from the chart then the "admin" on master cluster can "migrate/replicate" this app to other cluster(s) when required.

The module I'm writing is to monitor these charts and send the required information to the master cluster.

**Comment by rimusz** [comment] 2020-11-04 17:54
Storing of repoURL in the helm release is not supported, but what you can do create a new value `repoURL: chart repo url`
then you can fetch it e.g. `helm get values ...` and etc

**Comment by kgunjikar** [comment] 2020-11-04 20:10
Would it a violation of the design principles to add a repourl field to the chart metadata?

**Comment by bacongobbler** [comment] 2020-11-05 01:38
duplicate of https://github.com/helm/helm/issues/4256.

**Closed by bacongobbler** 2020-11-05 01:38 UTC
Labels: question/support

**Comment by rimusz** [comment] 2020-11-05 11:56
> Would it be a violation of the design principles to add a repourl field to the chart metadata?

No violation, you are free to use any values which suite you.
Even if you are using some upstream chart you can add extra values with some `override-values.yaml` file and pass it with `-f` to helm install/upgrade

**Comment by xeberth** [comment] 2023-08-17 21:38
You can get the repo details from an installed helm release by getting the secret for that release stored in your cluster:

1.- Get all helm related secrets from all namepsaces in your cluster with:

`kubectl get secrets -A | grep -i helm`

2.- Once you find the name of your helm release secret , get the secret metadata with:
 
```
kubectl get secret SECRET_NAME -o json | jq .data.release \
  | tr -d '"' | base64 -d | base64 -d | gzip -d \
  | jq '.chart.metadata'
```

Now you can see all the information regarding the repository used to install the release of your chart.
