### ISSUE TITLE
Helm autocompletion not working with bash alias

### ISSUE THREAD

**Issue by kostrahb** [helm/helm#4891] opened 2018-11-07 15:18 UTC
After creating alias, enabling autocompletion for it and writing `h <tab>` bash completes `h helm` instead of waiting for another `<tab>` to display available commands.

Following lines are in my `.bashrc` file
```bash
alias h='helm'
source <(helm completion bash)
complete -o default -F __start_helm h
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by glb** [comment] 2018-11-13 15:01
Reproducible in v2.11.0 as well.

It worked in 2.9.1:

```
$ alias h='helm'

$ source <(helm completion bash)

$ complete -o default -F __start_helm h

$ h[tab]
[redacted; system-wide list of commands starting with 'h']

$ h [tab] 
completion  get         install     repo        status      version
create      history     lint        reset       template    
delete      home        list        rollback    test        
dependency  init        package     search      upgrade     
fetch       inspect     plugin      serve       verify      

$ h version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Does *not* appear to be fixed by upgrading to latest `spf13/cobra` as in #4913.

**Comment by glb** [comment] 2018-11-13 15:22
There are differences in the output of `helm completion bash` between 2.9.1 (working) and 2.11.0 (not working).

```
$ git diff v2.9.1..v2.11.0 -- glide.yaml
 - package: github.com/spf13/cobra
-  version: f62e98d28ab7ad31d707ba837a966378465c7b57
+  version: c439c4fa093711d42e1b01acb1235b52004753c1
 - package: github.com/spf13/pflag
-  version: 9ff6c6923cfffbcd502984b8e0c80539a94968b7
+  version: 583c0c0531f06d5278b7d917446061adc344b5cd
```

Seems to be related to https://github.com/spf13/cobra/commit/a1e4933ab784095895e33dbe9f001ba10cfe2060 . 

Does this work for other tools that use `spf13/cobra`?

**Comment by kostrahb** [comment] 2018-11-13 16:18
AFAIK kubernetes and docker both use spf13/cobra and I was able to make the similar aliases `k` and `d` and the completion is working flawlessly.
I suspect, that this behavior might be induced by hardcoded name `helm` in bash function `_helm()` (I do not know where the source is but it might be generated easily by `helm completion bash`)

**Comment by glb** [comment] 2018-11-14 02:51
@kostrahb thanks for the information, it inspired me to re-test, and I have good news! I re-tested with the build for #4913 and it worked! I hadn't properly cleared my environment before testing last time.

@bacongobbler / @michelleN if you can take a look at #4913 I believe it will fix both the original issue and this one.

**Closed** 2018-11-20 16:54 UTC
Labels: question/support
