### ISSUE TITLE
proposal: Add warning when resulting .tgz archive is larger than 1MB to avoid HTTP 413 error

### ISSUE THREAD

**Issue by HenryFBP** [helm/helm#10165] opened 2021-09-21 16:43 UTC
proposal: Add warning when resulting .tgz archive is larger than 1MB.

Reason: HTTP error 413 gets thrown sometimes if your ingress controller limits .tgz upload file sizes. Spent an entire week diagnosing this issue, only to realize I needed to exclude my `.git/` directory by editing `.helmignore` file

This is technically not a helm issue but it would have saved me loads of time if I realized the .tgz file should have been smaller than 1MB. Googling "helm 413 error" brings a decent amount of results. It's also referenced here: https://github.com/helm/helm/issues/8281

Result: It would save a lot of time trying to figure out why "HTTP 413" errors are showing up when running `helm upgrade`

**Comment by bacongobbler** [comment] 2021-09-22 15:25
duplicate of https://github.com/helm/helm/issues/9788.

**Closed by bacongobbler** 2021-09-22 15:25 UTC
