### ISSUE TITLE
UPGRADE FAILED failed decoding reader into objects

### ISSUE THREAD

**Issue by fungiboletus** [helm/helm#5831] opened 2019-06-03 14:03 UTC
```
UPGRADE FAILED
Error: failed decoding reader into objects: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "restartPolicy" in io.k8s.api.core.v1.Container
```

Output of `helm version`:
2.4.0

Output of `kubectl version`:
1.14.1

**Comment by bacongobbler** [comment] 2019-06-03 17:03
Dupe of #5750.

**Closed by bacongobbler** 2019-06-03 17:03 UTC
