### ISSUE TITLE
helm3 pull gives invalid cross-device link error 

### ISSUE THREAD

**Issue by Shobhit29** [helm/helm#8041] opened 2020-05-01 19:12 UTC
Output of `helm version`: `helm 3.2.0`

Output of `kubectl version`: 

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  On premise cluster
I am running a script inside gitlab runner 12.7.1, where I pull the helm chart from one repo and upload it to our prod artifactory. 

In gitlab runner 12.7.1, while performing the helm3 pull causing me an error as below:

```
Command: helm3 pull repo/chart-name --version 2.27.4
 Error: rename /tmp/chart-name.tgz530975623 chart-name.tgz: invalid cross-device link
 helm.go:84: [debug] rename /tmp/chart-name.tgz530975623 chart-name.tgz: invalid cross-device link
```

and the same helm3 pull is working fine with helm3 version 3.1.0, under same gitlab-runner 12.7.1.

**Comment by bacongobbler** [comment] 2020-05-01 19:15
duplicate of #7987.

**Closed by bacongobbler** 2020-05-01 19:15 UTC
