### ISSUE TITLE
helm crash when trying to template or intall an OCI hosted chart

### ISSUE THREAD

**Issue by sereinity** [helm/helm#9294] opened 2021-01-28 15:52 UTC
Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Note: I will concentrate only on `template` subcommand, but the errors also hapend on `install`.

```bash
export HELM_EXPERIMENTAL_OCI=1
CHART=oci://registry.mydomain/group/project/component:0.1.0 # an example

helm chart pull $CHART # success
helm template release $CHART
```

The output of the template command:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15fba23]

goroutine 1 [running]:
helm.sh/helm/v3/internal/experimental/registry.(*Client).PullChart(0x0, 0xc0008cc820, 0xc0008cc820, 0x0, 0x0)
        /home/circleci/helm.sh/helm/internal/experimental/registry/client.go:156 +0x183
helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc0024a5c20, 0xc0024cd560, 0x59, 0xc000561628, 0xc0024cd560, 0x59)
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:52 +0xc5
helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc0024a5c20, 0xc0024cd560, 0x59, 0xc00069c6c0, 0x4, 0x6, 0xc0024a5c20, 0x0, 0x0)
        /home/circleci/helm.sh/helm/pkg/getter/ocigetter.go:36 +0x77
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc0005618d8, 0x7ffd6a6b4561, 0x59, 0x0, 0x0, 0xc0005b1b00, 0x26, 0x20300000000000, 0x7fce82f52fff, 0xc000c07828, ...)
        /home/circleci/helm.sh/helm/pkg/downloader/chart_downloader.go:99 +0x13f
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart(0xc000542148, 0x7ffd6a6b4561, 0x59, 0xc0003900e0, 0x7ffd6a6b4558, 0x8, 0x7ffd6a6b4561, 0x59)
        /home/circleci/helm.sh/helm/pkg/action/install.go:675 +0x40e
main.runInstall(0xc000597c80, 0x2, 0x2, 0xc000542140, 0xc0005344e0, 0x1e32f40, 0xc000182008, 0x8, 0xc000c07a98, 0xc000c07a80)
        /home/circleci/helm.sh/helm/cmd/helm/install.go:185 +0x172
main.newTemplateCmd.func2(0xc000544dc0, 0xc000597c80, 0x2, 0x2, 0x0, 0x0)
        /home/circleci/helm.sh/helm/cmd/helm/template.go:73 +0x134
github.com/spf13/cobra.(*Command).execute(0xc000544dc0, 0xc000597c40, 0x2, 0x2, 0xc000544dc0, 0xc000597c40)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000732000, 0xc00049a218, 0x1, 0xc000979f60)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80 +0x24d
```

I found out that the registry client is `nil` in the `PullChart` function in the case it was called from `template` (or `install`) subcommand.

Note: I also tried with `--version 0.1.0` and some other variants.

**Comment by jdolitsky** [comment] 2021-01-28 17:56
closing as duplicate of https://github.com/helm/helm/issues/9267

**Comment by sereinity** [comment] 2021-01-29 08:54
I'm not talking about a dependency here, and I have no problem on dependencies.

**Comment by jdolitsky** [comment] 2021-01-29 18:40
Yes, but error appear to have same root cause `segmentation violation`

Will re-open in the case these are not closely related

**Comment by bacongobbler** [comment] 2021-02-01 15:44
Looking at both reports, they appear to crash on the exact same line of code: https://github.com/helm/helm/blob/32c22239423b3b4ba6706d450bd044baffdcf9e6/internal/experimental/registry/client.go#L156

**Comment by bacongobbler** [comment] 2021-02-01 15:45
@sereinity can you please demonstrate how you developed and pushed your helm chart to the registry? We need a test sample to reproduce the issue.

**Comment by sereinity** [comment] 2021-02-02 08:47
It's on a private azure container registry (that I can't share here).

I reproduced it on a fresh container (ie: doesn't have any helm config):

```bash
export HELM_EXPERIMENTAL_OCI=1
helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

helm registry login -u myuser https://registry.mydomain
Password:
Login succeeded

helm chart pull registry.mydomain/group/project/component:0.1.0 # success
ref:     registry.mydomain/group/project/component:0.1.0
digest:  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
size:    34.1 KiB
name:    component
version: 0.1.0
Status: Downloaded newer chart for registry.mydomain/group/project/component:0.1.0

helm template release oci://registry.mydomain/group/project/component:0.1.0
panic
```

**Comment by sereinity** [comment] 2021-02-02 09:01
After I took a better look at #9267 I agree that the cause is the same. But I think that solutions aren't, as there is a [workaround](https://github.com/helm/helm/issues/9267#issuecomment-766846575) for #9267, but not here for now.

**Comment by bacongobbler** [comment] 2021-02-26 14:40
Should be solved via #9409. Let us know if that isn’t the case. Closing!

**Closed by bacongobbler** 2021-02-26 14:40 UTC
Labels: bug

**Comment by RTodorov** [comment] 2021-03-25 14:56
Hi there. I'm facing the same issue using latest (3.5.3), did #9409 made it into a release already?

**Comment by glehmann** [comment] 2021-04-27 19:48
@RTodorov no it hasn't (`git tag --contains 158d7df5f5b774770b2eb5ad796f89a2f6c5200a`).

I have the same problem and would love to have an official release :)

**Comment by sereinity** [comment] 2021-04-30 09:53
I tested on the main branch, and indeed, it doesn't panic anymore ; but still no template rendering from an OCI source, even if the chart is already pulled.

current output:
```
Error: failed to download "oci://registry.mydomain/group/project/component:0.1.0" (hint: running `helm repo update` may help)
```

I also tried with `--version` instead of putting the version in the URL: same error.

@bacongobbler As the error changed, do you want another issue, or do we re-open this one?

(to be clear, I test OCI on `template` because it's simpler to test, but my objective is to use `install`/`upgrade`)
