### ISSUE TITLE
 Failed to connect to get.helm.sh port 443: Connection refused

### ISSUE THREAD

**Issue by Dmdv** [helm/helm#9390] opened 2021-02-21 11:05 UTC
Trying to download in Windows
```
helm-v3.5.2-linux-amd64.tar.gzFailed - Network error
```

Trying to install helm in Ubuntu

```
 curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11248  100 11248    0     0  21222      0 --:--:-- --:--:-- --:--:-- 21222
Error: unknown flag: --template
Helm v3.5.2 is available. Changing from version .
Downloading https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
curl: (7) Failed to connect to get.helm.sh port 443: Connection refused
Failed to install helm
        For support, go to https://github.com/helm/helm.
```

**Comment by yxxhero** [comment] 2021-02-22 03:35
In my code. It's ok. Please retry it.

**Comment by mattfarina** [comment] 2021-02-22 17:31
@Dmdv Are you still experiencing the issue? I am unable to reproduce.

**Comment by bacongobbler** [comment] 2021-02-23 23:41
Closing as resolved until disproven otherwise. Likely just a flaky network error.

**Closed by bacongobbler** 2021-02-23 23:41 UTC
Labels: question/support
