### ISSUE TITLE
Helm dependency update ignores build number

### ISSUE THREAD

**Issue by nirroz93** [helm/helm#6764] opened 2019-10-23 17:00 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

also tested with client of latest stable helm (2.15.1) - same problem

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS KOPS

Problem: 
helm dependency update ignores build number in version

Not sure if it's artifactory problem or helm issue, sorry but I don't have other repo to check.

example: 
requirement.yaml:
dependencies:
  - name: my-app
    version: "1.0.0+2"
    repository: "alias:my-artifactory-helm-repo"

after helm dep up latest build number is fetched:
ls charts/:
my-app-1.0.0+4.tgz

helm fetch my-artifactory-helm-repo/my-app --version 1.0.0+2 works as expected (taking correct version)

**Comment by bacongobbler** [comment] 2019-10-30 17:37
@mattfarina according to client requests, https://github.com/helm/helm/pull/6821 is a port of a Helm 2 feature where if an exact version is produced, helm should fetch that exact version.

I get that build metadata should be ignored during a semver comparison, however should it always be ignored if the user requests a specific version? i.e. there's no semver comparison involved, just a lookup.

**Comment by bacongobbler** [comment] 2019-10-30 17:38
See also #6820.

**Comment by bacongobbler** [comment] 2019-10-30 19:37
this should be fixed in #6821 which will be available in the next release candidate. Closing as a duplicate of #6820.

**Closed by bacongobbler** 2019-10-30 19:37 UTC
Labels: bug, v2.x
