### ISSUE TITLE
helm status stopped showing containers

### ISSUE THREAD

**Issue by mshakhmaykin** [helm/helm#6896] opened 2019-11-06 21:55 UTC
Couldn't find it in the latest changelog, but:

before upgrade to 2.16, it used to show more detailed information about running pods. Now I need to run **kubectl -n <namespace> get pods -l app=\<app-name\>** to find out if my containers started and passed the Liveness probes. Previously I could just do **helm status \<release\>**. Any chances to return to the original behavior?

Output of `helm version`: 
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-eks-e9b1d0", GitCommit:"e9b1d0551216e1e8ace5ee4ca50161df34325ec2", GitTreeState:"clean", BuildDate:"2019-09-21T08:33:01Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by hayorov** [comment] 2019-11-07 03:55
After this change, `helm status` is ridiculously useless command, it requires to do kubectl get/describe next.

```
LAST DEPLOYED: Wed Nov  6 20:22:21 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                 AGE
hlf-ord--ord         15h
hlf-orderer-genesis  15h

==> v1/Deployment
NAME     AGE
hlf-ord  15h

==> v1/PersistentVolumeClaim
NAME     AGE
hlf-ord  15h

==> v1/Pod(related)
NAME                      AGE
hlf-ord-655f9d5856-tscnz  2m15s

==> v1/Secret
NAME                   AGE
hlf-orderer-admincert  15h
hlf-orderer-cacert     15h
hlf-orderer-cert       15h
hlf-orderer-key        15h

==> v1/Service
NAME     AGE
hlf-ord  15h

==> v1beta1/Ingress
NAME     AGE
hlf-ord  15h
```

**Comment by bacongobbler** [comment] 2019-11-07 18:22
fixed via #6897 which will be available in 2.16.1.

**Comment by mshakhmaykin** [comment] 2019-11-15 15:34
This didn't help unfortunately.
```
$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
```$ helm status service-app
LAST DEPLOYED: Mon Oct 14 17:40:40 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME        AGE
service-app  31d

==> v1/Pod(related)
NAME                         AGE
service-app-687549b68d-k4wk6  21m
service-app-687549b68d-kz5jp  30d

==> v1/Service
NAME        AGE
service-app  31d```

**Comment by bacongobbler** [comment] 2019-11-15 15:41
It looks like https://github.com/helm/helm/pull/6897/commits/e2894a18ee1d28341aedd5fc786aff4cc7f2c092 was never cherry-picked into the 2.16.1 release branch. #6897 still has the `needs-pick` label attached. 😢

**Comment by bacongobbler** [comment] 2019-11-15 15:44
weird; https://github.com/helm/helm/commit/bbdfe5e7803a12bbdf97e94cd847859890cf4050 is part of the 2.16.1 branch. Perhaps the printer on Kubernetes' end changed again.

Re-opening for further investigation.

**Comment by thuandt** [comment] 2019-11-15 18:15
@bacongobbler I have same issue with 2.16.1

My application used to helm v2.14.3, then I upgraded helm to v2.16.1 pods status has been gone

**Comment by cridam** [comment] 2019-11-29 16:20
Deployment, and Service columns have also disappeared. Will 2.16.2 fix ?
i.e
before 2.16.x
==> v1/Service
NAME              TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)   AGE
mymicroservice  ClusterIP  xxx <none>       8443/TCP  25d
after
==> v1/Service
NAME  AGE
mymicroservice  25d

**Comment by liurd** [comment] 2019-12-13 05:06
Are you going to build 2.16.2 to fix the issue?

**Comment by bacongobbler** [comment] 2019-12-18 07:35
I don't believe #7196 was intended to fix this issue, however if you can demonstrate that #7196 does indeed fix the issue, we'd love to understand why.

**Comment by nickdgriffin** [comment] 2020-01-17 11:09
I'm anxiously awaiting 2.16.2 for https://github.com/helm/helm/pull/7319, is this issue still in scope for the release?

**Comment by bacongobbler** [comment] 2020-03-05 21:53
I'm still seeing the issue present with the HEAD of `dev-v2` with a Kubernetes 1.17 cluster.

> I'm anxiously awaiting 2.16.2 for #7319, is this issue still in scope for the release?

#7319 is irrelevant to this ticket, but yes, It should be in the next patch release.

To get a better understanding of the issue here: `helm status` relies on the same APIs that `kubectl get` relies upon. `k8s.io/kubernetes` has broken backwards compatibility in the past, so it's quite possible it's happened again.

I'm currently looking into *why* it keeps breaking, and assess whether we need to replace it with some other API.

**Comment by bacongobbler** [comment] 2020-03-06 00:49
So... kubernetes did indeed break backwards compatibility. You now have to generate a `metav1.Table` if you want the endpoint to render the same as `kubectl get`. If someone wants to take a closer look at this, I started diving deeper into how `kubectl get` prints objects now in #7728. I don't have time to follow through and fix the issue, but hopefully this helps someone looking at fixing this.

**Comment by mattfarina** [comment] 2020-03-19 01:30
I have a PR coming with a fix for this. It work. Just need to try and clean up the code some more and figure out how to explain the change.

**Comment by mattfarina** [comment] 2020-03-20 16:46
PR just landed that fixes this. Should be in the next 2.16 release.

**Closed by mattfarina** 2020-03-20 16:46 UTC
Labels: bug, v2.x
