### ISSUE TITLE
Expect a int but got a float64 from values.yaml

### ISSUE THREAD

**Issue by Lentil1016** [helm/helm#4982] opened 2018-11-29 07:50 UTC
#### What happened
Hello, I want to take a integer value from values.yaml to control the looping times of a `range` block in my templates. Let's say I set `count: 1` in `values.yaml`. Commonly it should be inferred to a `integer`, but when I run `helm install`, `.Values.count` is envalued to a `float64` type. 

And I have to use pipeline function as a workaround.

```yaml
{{ $count := .Values.count | int }}
{{ range until $count }}
    count to {{.}}
{{ end }}
```

I've checked the [docs](https://docs.helm.sh/chart_template_guide/#scalar-types-in-yaml), but I'm not sure if `values.yaml` applies the same rule. Is that a expected behavior? And if it is, while the pipeline function like `int` is sometimes necessary but not mentioned directly in helm's document. Is that a good idea to add some additional example for it?

#### How to reproduce
```
$ cat test-helm.sh
mkdir -p templates
echo """
apiVersion: v1
description: helm template test
name: helm-template-test
version: 0.1.0
""" > Chart.yaml
echo """
{{- range until .Values.count }}
	test={{.}}
{{- end }}
""" > templates/test.yaml
echo """
count: 3
""" > values.yaml

$ ./test-helm.sh
$ helm install -n test-helm . --dry-run --debug
[debug] Created tunnel using local port: '33823'

[debug] SERVER: "127.0.0.1:33823"

[debug] Original chart version: ""
[debug] CHART PATH: /root/gitlab/cubes/charts/test-helm

Error: render error in "helm-template-test/templates/test.yaml": template: helm-template-test/templates/test.yaml:2:23: executing "helm-template-test/templates/test.yaml" at <.Values.count>: wrong type for value; expected int; got float64
```

Output of `helm version`:

```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment] 2018-11-29 07:56
closing as a duplicate of https://github.com/helm/helm/issues/1707 :) thanks!

**Closed by bacongobbler** 2018-11-29 07:56 UTC

**Comment by cortopy** [comment] 2021-05-25 13:23
change to:

```golang
{{ $count := (.Values.count | int) }}
{{ range until $count }}
    count to {{.}}
{{ end }}
```
