### ISSUE TITLE
helm3 template outputs in random order

### ISSUE THREAD

**Issue by ryan-dyer-sp** [helm/helm#6967] opened 2019-11-14 15:53 UTC
helm v3 is rendering templates in a random order.  With v2 we would render the templates from charts and commit the results; only changes to values.yaml or the actual templates themselves would result in the output being different.  With v3 I can run template without any changes and get different results every time.  This is occurring with the cert-manager helm charts.
```
> helm template test stable/cert-manager > 1.yaml
> helm template test stable/cert-manager > 2.yaml
> diff 1.yaml 2.yaml
120c120
< apiVersion: rbac.authorization.k8s.io/v1
---
> apiVersion: rbac.authorization.k8s.io/v1beta1
123c123
<   name: cert-manager-edit
---
>   name: cert-manager
129,130d128
<     rbac.authorization.k8s.io/aggregate-to-edit: "true"
<     rbac.authorization.k8s.io/aggregate-to-admin: "true"
133,134c131,138
<     resources: ["certificates", "issuers"]
<     verbs: ["create", "delete", "deletecollection", "patch", "update"]
---
>     resources: ["certificates", "certificates/finalizers", "issuers", "clusterissuers", "orders", "orders/finalizers", "challenges"]
>     verbs: ["*"]
>   - apiGroups: [""]
>     resources: ["configmaps", "secrets", "events", "services", "pods"]
>     verbs: ["*"]
>   - apiGroups: ["extensions"]
>     resources: ["ingresses"]
>     verbs: ["*"]
155c159
< apiVersion: rbac.authorization.k8s.io/v1beta1
---
> apiVersion: rbac.authorization.k8s.io/v1
158c162
<   name: cert-manager
---
>   name: cert-manager-edit
163a168,169
>     rbac.authorization.k8s.io/aggregate-to-edit: "true"
>     rbac.authorization.k8s.io/aggregate-to-admin: "true"
166,173c172,173
<     resources: ["certificates", "certificates/finalizers", "issuers", "clusterissuers", "orders", "orders/finalizers", "challenges"]
<     verbs: ["*"]
<   - apiGroups: [""]
<     resources: ["configmaps", "secrets", "events", "services", "pods"]
<     verbs: ["*"]
<   - apiGroups: ["extensions"]
<     resources: ["ingresses"]
<     verbs: ["*"]
---
>     resources: ["certificates", "issuers"]
>     verbs: ["create", "delete", "deletecollection", "patch", "update"]
482c482
< # Finally, generate a serving certificate for the webhook to use
---
> # Generate a CA Certificate used to sign certificates for the webhook
486c486
<   name: cert-manager-webhook-webhook-tls
---
>   name: cert-manager-webhook-ca
494,495c494,495
<   secretName: cert-manager-webhook-webhook-tls
<   duration: 8760h # 1y
---
>   secretName: cert-manager-webhook-ca
>   duration: 43800h # 5y
497,501c497,499
<     name: cert-manager-webhook-ca
<   dnsNames:
<   - cert-manager-webhook
<   - cert-manager-webhook.es
<   - cert-manager-webhook.es.svc
---
>     name: cert-manager-webhook-selfsign
>   commonName: "ca.webhook.cert-manager"
>   isCA: true
504c502
< # Generate a CA Certificate used to sign certificates for the webhook
---
> # Finally, generate a serving certificate for the webhook to use
508c506
<   name: cert-manager-webhook-ca
---
>   name: cert-manager-webhook-webhook-tls
516,517c514,515
<   secretName: cert-manager-webhook-ca
<   duration: 43800h # 5y
---
>   secretName: cert-manager-webhook-webhook-tls
>   duration: 8760h # 1y
519,521c517,521
<     name: cert-manager-webhook-selfsign
<   commonName: "ca.webhook.cert-manager"
<   isCA: true
---
>     name: cert-manager-webhook-ca
>   dnsNames:
>   - cert-manager-webhook
>   - cert-manager-webhook.es
>   - cert-manager-webhook.es.svc
```

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by bacongobbler** [comment] 2019-11-14 15:56
see https://github.com/helm/helm/pull/6842

**Comment by bacongobbler** [comment] 2019-11-14 15:56
duplicate of https://github.com/helm/helm/issues/6843.

**Closed by bacongobbler** 2019-11-14 15:56 UTC
