### ISSUE TITLE
mysql chart version issue

### ISSUE THREAD

**Issue by harsh-2519** [helm/helm#8152] opened 2020-05-16 21:36 UTC
Hi, I am using the Mysql chart in my Kubernetes deployment. Everything is working fine till yesterday. But now I am getting below mentioned error from MySql chart while it is deploying on Kubernetes using terraform.

**Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"**

I think this is an outdated chart and not compatible with Kubernetes version-1.16. Please do update the chart or let me know the alternative way for this chart.

Output of `helm version`:
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T21:
00:06Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"20
20-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS(via terraform) or EKS

**Comment by hickeyma** [comment] 2020-05-18 07:05
Duplicate of #7219

**Comment by hickeyma** [comment] 2020-05-18 07:05
@harsh-2519 This is a known issue with removed Kubernetes APIs. See [Deprecated Kubernetes APIs](https://helm.sh/docs/topics/kubernetes_apis/) for more details.

Closing as a duplicate of #7219.

**Closed** 2020-05-18 07:05 UTC
Labels: bug
