### ISSUE TITLE
[Question] How to show final rendered values in Helm 3 with multiple value files?

### ISSUE THREAD

**Issue by zx8** [helm/helm#6772] opened 2019-10-24 10:12 UTC
With Helm 2, I used the following trick:

* Create a chart called `show-final-values`
* Add a single template `values.yaml.tpl` containing:
```
{{ toYaml .Values }}
```
* Run the following command:
```
$ helm template -f values_1.yaml -f values_2.yaml -f values_3.yaml show-final-values
```

---

With Helm 3, I'm getting the following error (because there happens to be a value defined that is named `apiVersion` and is a mapping rather than a string):

```
Error: YAML parse error on show-final-values/templates/values.yaml.tpl: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field SimpleHead.apiVersion of type string
```

I've tried using `helm show values` but this doesn't seem to support `-f` to specify additional value files.

**Comment by thomastaylor312** [comment] 2019-10-28 18:01
@zx8 `helm get values --all` should show you the final computed values map for a release

**Comment by zx8** [comment] 2019-10-28 22:05
@thomastaylor312 That will get me the values of a release _after_ it's deployed, right? I'm looking for a way to get the values _before_ it's deployed as we use several levels of hierarchy for our value files (tier, environment, etc.) and it's useful to see how these merge together to form the final values file prior to the release, in particular when working on a brand new chart.

**Comment by thomastaylor312** [comment] 2019-10-28 22:44
Yes, it is after install. You can do it before with a `helm install [name] [chart] --dry-run --debug -f <your_values_file>` and the merged list of values will be available in a section called `COMPUTED VALUES:`.  

However, with that said, I dug into things a little more and I was wrong. It looks like we actually have an open PR to fix this with `helm template` that affects other users and some plugins: #6729. So I am going to close this as a duplicate of the original issue #6505. Please follow that issue for any updates

**Closed by thomastaylor312** 2019-10-28 22:44 UTC
Labels: question/support

**Comment by wheelerlaw** [comment] 2024-02-29 22:28
Following up on this. It looks like #6729 was close in favor of #6817 which has been merged. Is there any update on getting a Helm command to show the final computed values before a release/install?

**Comment by tdg5** [comment] 2024-05-06 20:05
It seems worth noting that at least in `helm` `v3.14.0`, the template hack that @zx8 mentioned of creating a template like `{{ toYaml .Values }}` works again for capturing the full set of values.

I think a dedicated CLI command would be a nice option to have, but at least there are a couple of workarounds.

**Comment by chandrashekar27** [comment] 2024-05-19 06:23
@tdg5 Can you please describe how to do this in more detail. I created a template as mentioned above but instead of getting the full set of values, I'm only getting  `global: {}`. Thanks.

**Comment by tdg5** [comment] 2024-05-19 18:40
It seems like the part worth clarifying would be that after creating the template I then run `helm template --show-only templates/template_name.yaml release_name chart_path`

Here's a full example that uses a helm chart that I used to help maintain to try to illustrate the whole process from scratch
```bash
git clone https://github.com/neuralmagic/helm-charts.git
cd helm-charts/charts/nm-vllm-production-monitoring
echo '{{ toYaml .Values }}' > templates/computed-values.yaml
helm dependency update
helm template --show-only templates/computed-values.yaml release-name .
rm templates/computed-values.yaml
```

That works for me with `helm 3.15.0`, I hope you find the same 🤞🏻 , if not, let me know.

It's worth noting that `--show-only` doesn't seem to be required, but certainly helps make it easier to find what you are looking for. 

What `helm` version are you using? I could try to sanity check that version if you like.
