### ISSUE TITLE
Adding --set back to 'helm package'

### ISSUE THREAD

**Issue by sreya92** [helm/helm#7804] opened 2020-03-24 18:27 UTC
`helm package` in v3, for a brief period of time, had a nice feature that allowed you to write sensible defaults into your `values.yaml` that got bundled into the helm package. This made automating helm releases trivial (and extremely nice) since you could specify configuration at build-time without having to worry about committing updates to source-controlled files. It also allowed for a unified path between dev deploys and customer deploys. 

My understanding is that it was removed because it stripped valuable context (in the form of comments) from the `values.yaml` file. It appears that efforts to add this feature back have been [abandoned](https://github.com/helm/helm/issues/3141#issuecomment-585571297). If I were to submit a PR that retained comments when running `helm package --set` would you guys be open to accepting it?

**Comment by bacongobbler** [comment] 2020-03-24 18:32
>  If I were to submit a PR that retained comments when running `helm package --set` would you guys be open to accepting it?

Yes. That's really the only blocking issue preventing us from supporting this workflow. I even mentioned that [in the next comment in that thread](https://github.com/helm/helm/issues/3141#issuecomment-585583283).

Closing as a duplicate of #3141. Let's please keep the conversation in one ticket going forward. Thanks.

**Closed by bacongobbler** 2020-03-24 18:32 UTC
