### ISSUE TITLE
HELM 3: helm install can't scope namespace, always install to default namespace

### ISSUE THREAD

**Issue by tcbjc** [helm/helm#5838] opened 2019-06-04 11:54 UTC
[root@monitorvm ~]# helm install wordpressdemo stable/wordpress -n lab02
NAME: wordpressdemo
LAST DEPLOYED: 2019-06-04 11:42:39.299504225 +0000 UTC m=+1.318797266
NAMESPACE: default
STATUS: deployed

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AKS

**Comment by hickeyma** [comment] 2019-06-04 13:03
Closing this as it is a duplicate of #5628

**Closed by hickeyma** 2019-06-04 13:03 UTC

**Comment by tcbjc** [comment] 2019-06-05 11:55
> Closing this as it is a duplicate of #5628
Got it. Thanks @hickeyma
