### ISSUE TITLE
Deletion of CRD with crd-install and before-hook-creation randomly fails (race condition)?

### ISSUE THREAD

**Issue by micw** [helm/helm#5375] opened 2019-02-28 07:33 UTC
This is a follow-up to #5278 and is possibly related to #4925.

Output of `helm version`:

Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Rancher2 on-premise

Issue description:

I'm installing a helm chart with a CRD and the annotations

```
  annotations:
    helm.sh/hook: crd-install
    helm.sh/hook-delete-policy: before-hook-creation
```

When I Install/remove the chart multiple times, sometimes it fails with the following error:

```
Release "hook-test" does not exist. Installing it now.
Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "tests.my.test.com" already exists
```

A test to reproduce this follows.

**Comment by bacongobbler** [comment] 2019-02-28 07:39
yeah, this appears to be a duplicate of #4925. Can you test https://github.com/helm/helm/pull/5112 and see if that fixes it for you?

**Comment by micw** [comment] 2019-02-28 07:40
Here's a test chart that reproduces this error: https://github.com/micw/helm-hook-test
Just let run_test.sh run - it installs/removes the chart in a loop. On my cluster this fails randomly every 2nd or 3rd run.

**Comment by micw** [comment] 2019-02-28 07:42
@bacongobbler I worked out a test that makes this more or less reproducible. Unfortunately I have no idea how I could verify if this PR solves this issue. How can I obtain a helm binary that contains this fix?

**Comment by bacongobbler** [comment] 2019-02-28 08:06
You'll have to build from source following [the developer guide](https://helm.sh/docs/developers/). Let me know if you run into any issues.

**Comment by micw** [comment] 2019-02-28 10:11
I did it this way: https://gist.github.com/micw/30190083b3e5d7df8dc30bc1526bdb57 ;-)

**Comment by micw** [comment] 2019-02-28 10:43
@bacongobbler Now I have a custom build new helm/tiller version. Unfortunately, the tiller version which is deployed it one from a docker image, not my local one...
I can see no good way how I can easily test this.

**Comment by micw** [comment] 2019-02-28 11:07
I have build and pushed a tiller docker image this way:
https://gist.github.com/micw/30190083b3e5d7df8dc30bc1526bdb57

Then I changed my k8s to use this tiller image (via kubectl patch):

```
bin/helm version
Client: &version.Version{SemVer:"v2.11+unreleased", GitCommit:"57d589fb28c16f0e3418d0967bfb52772adc578e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11+unreleased", GitCommit:"57d589fb28c16f0e3418d0967bfb52772adc578e", GitTreeState:"clean"}
```

Then I changed my test to  use the custom built helm binary.

The issue still exists:

```
Release "hook-test" does not exist. Installing it now.
Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "tests.my.test.com" already exists
```

**Closed** 2019-06-21 16:03 UTC
Labels: bug
