### ISSUE TITLE
--kubeconfig flag is ignored

### ISSUE THREAD

**Issue by Tobag** [helm/helm#6073] opened 2019-07-24 10:46 UTC
Hi,

the --kubeconfig flag is ignored in the helm3 alpha2 release.

Best regards,
Tobi

Output of `helm version`: version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}

**Comment by hickeyma** [comment] 2019-07-24 11:27
This should have been fixed by #6025. @ian-howell could you take a look pls.?

**Comment by Tobag** [comment] 2019-07-24 13:08
I probably should have mentioned that I was using the command
_helm install ... --kubeconfig_

I am not sure if I should have used it with the init command instead.

**Comment by ian-howell** [comment] 2019-07-24 14:05
I'm unable to reproduce. @Tobag could you provide further details?

For reference, here is how I tested this.

Using `~/.kube/config`:
```
$ ./bin/helm ls --kubeconfig ~/.kube/config
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART
$
$ ./bin/helm install first-foo ./foo --kubeconfig ~/.kube/config
NAME: first-foo
LAST DEPLOYED: 2019-07-24 08:57:31.735638435 -0500 CDT m=+0.234861112
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=first-foo" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
$
$ ./bin/helm ls --kubeconfig ~/.kube/config
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART
first-foo       default         1               2019-07-24 08:57:31.735638435 -0500 CDT deployed        foo-0.1.0
```

Using `~/.kube/kind-testing-cluster-config`:
```
$ ./bin/helm ls --kubeconfig ~/.kube/kind-testing-cluster-config
NAME    NAMESPACE       REVISION        UPDATED STATUS  CHART
$
$ ./bin/helm install other-foo ./foo --kubeconfig ~/.kube/kind-testing-cluster-config
NAME: other-foo
LAST DEPLOYED: 2019-07-24 08:57:52.643923965 -0500 CDT m=+0.646890967
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=foo,app.kubernetes.io/instance=other-foo" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
$
$ ./bin/helm ls --kubeconfig ~/.kube/kind-testing-cluster-config
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART
other-foo       default         1               2019-07-24 08:57:52.643923965 -0500 CDT deployed        foo-0.1.0
```

**Comment by Tobag** [comment] 2019-07-24 14:39
Hi @ian-howell ,

I just tried it out again and you are right, the install command is working fine. The upgrade command is the one that is not working correctly:

`
> helm3 list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

> helm3 list --kubeconfig /Users/test/kubeconfig
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

> helm3 upgrade wordpress stable/wordpress -i --kubeconfig=/Users/test/kubeconfig 
Release "wordpress" does not exist. Installing it now.

> helm3 list
NAME     	NAMESPACE	REVISION	UPDATED                              	STATUS  	CHART          
wordpress	asdf     	1       	2019-07-24 16:34:55.696296 +0200 CEST	deployed	wordpress-5.9.0

> helm3 list --kubeconfig /Users/test/kubeconfig
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART`

**Comment by ian-howell** [comment] 2019-07-24 21:46
@Tobag So this was a doozy. There was definitely a problem here. These lines here are working on the persistent flags of the root command: https://github.com/helm/helm/blob/dev-v3/cmd/helm/root.go#L118-L122. The problem is that helm passes all of `os.Args` to this `Parse` function, however that particular `FlagSet` only has the flags added during the call to `settings.AddFlags(flags)`. This causes an error because the parse function will find the `-i` flag, not recognize it, and error out, leaving the remaining flags unparsed. Helm silently ignores the error and continues onward, potentially failing later on.

The solution lies in the `ParseErrorsWhitelist.UnkownFlags` of the Persistent flags. The PR that implements this solution is here: https://github.com/helm/helm/pull/6076

**Comment by hickeyma** [comment] 2019-08-07 10:54
So, from testing this . it seems to be an issues when the install flag `-i` is used with an `upgrade`. Here is some output from my testing:

```console
$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          
chrt-6076 	default  	1       	2019-08-07 11:15:35.918551893 +0100 IST	deployed	chrt-6076-0.1.0
my-release	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0    

$ helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

$ helm --kubeconfig=/home/usr1/.kube/config.bak upgrade chrt-6076 chrt-6076/
Release "chrt-6076" has been upgraded. Happy Helming!
NAME: chrt-6076
LAST DEPLOYED: 2019-08-07 11:29:42.113884198 +0100 IST
NAMESPACE: default
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=chrt-6076,release=chrt-6076" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          
chrt-6076 	default  	2       	2019-08-07 11:29:42.113884198 +0100 IST	deployed	chrt-6076-0.1.0
my-release	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0    

$ helm create chrt-6076-2
Creating chrt-6076-2

$ helm list
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART

$ helm upgrade chrt-6076-2 chrt-6076-2/ -i
Release "chrt-6076-2" does not exist. Installing it now.

$ helm list
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076-2	test     	1       	2019-08-07 11:35:06.869344506 +0100 IST	deployed	chrt-6076-2-0.1.0

$ helm upgrade chrt-6076-2 chrt-6076-2/ -i --kubeconfig=/home/usr1/.kube/config.bak
Release "chrt-6076-2" has been upgraded. Happy Helming!
NAME: chrt-6076-2
LAST DEPLOYED: 2019-08-07 11:36:37.480422228 +0100 IST
NAMESPACE: test
STATUS: deployed

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods -l "app=chrt-6076-2,release=chrt-6076-2" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

$ helm --kubeconfig=/home/usr1/.kube/config.bak list
NAME      	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          
chrt-6076 	default  	2       	2019-08-07 11:29:42.113884198 +0100 IST	deployed	chrt-6076-0.1.0
my-release	default  	2       	2019-08-07 10:36:39.30576271 +0100 IST 	deployed	mysql-1.3.0    

$ helm ls
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART            
chrt-6076-2	test     	2       	2019-08-07 11:36:37.480422228 +0100 IST	deployed	chrt-6076-2-0.1.0
```

**Comment by hickeyma** [comment] 2019-08-07 11:14
Closing as #6076 now merged.

**Closed by hickeyma** 2019-08-07 11:14 UTC
Labels: bug, v3
