### ISSUE TITLE
Helm3.beta4 - failed to install chart: value of type interface {} is not assignable to type string

### ISSUE THREAD

**Issue by costimuraru** [helm/helm#6626] opened 2019-10-09 21:39 UTC
We're trying to install a helm chart, but is not working with helm3 (it works with helm2).
```
❯ helm upgrade --install mychart incubator/raw --version 0.1.0 --namespace default --values myvalues.yaml
Release "mychart" does not exist. Installing it now.
Error: template: raw/templates/resources.yaml:4:12: executing "raw/templates/resources.yaml" at <merge . $template>: error calling merge: reflect.Value.MapIndex: value of type interface {} is not assignable to type string
```

Where (updated) `myvalues.yaml` is:
```
resources:
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: docker-monitoring-release-flb
    stringData:
      .dockerconfigjson: "{\"auths\":{ \"docker2-monitoring-release-local.test.com\":{\"auth\":\"dXNlcjpwYXNzd29yZAo=\"}}}"
```

Chart is here: https://github.com/helm/charts/tree/master/incubator/raw

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

Output of `kubectl version`:
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bacongobbler** [comment] 2019-10-09 23:08
Hmm. I can't seem to figure it out, but something in how the values object is being merged into is causing the error.

Re-transferring back to helm/helm as this may be a regression issue.

Let me know if you're able to find something in helm's code that may be causing the issue.

**Comment by costimuraru** [comment] 2019-10-09 23:58
Thanks, @bacongobbler. Glad that you managed to replicate the issue on your end as well. Not familiar with the helm code base (or `go` for that matter); hope someone can chime in

**Comment by mumoshu** [comment] 2019-10-10 01:59
Probably this is due to possible changes to `fromYaml` that made it to return `map[interface{}]interface{}` nested in `map[string]interface{}` where it had been returning `map[string]interface{}` nested in `map[string]interface{}` in helm v2.

v2:

![image](https://user-images.githubusercontent.com/22009/66533168-ec89b380-eb4c-11e9-9bc5-d31f03a48ef2.png)

v3:

![image](https://user-images.githubusercontent.com/22009/66533129-c82dd700-eb4c-11e9-99e4-edbebdcc22c3.png)

Is anyone aware of such change?

**Comment by mumoshu** [comment] 2019-10-10 11:08
#6630 seems to fix this. Could anyone test it out?

**Comment by hickeyma** [comment] 2019-10-10 15:38
Closing as #6630

**Closed by hickeyma** 2019-10-10 15:38 UTC
Labels: bug, v3.x

**Comment by bacongobbler** [comment] 2019-10-10 15:59
Thank you SO MUCH @mumoshu for identifying the fix, providing a patch, AND adding test cases to cover this case! ❤️
