### ISSUE TITLE
Please release Helm also as Docker container

### ISSUE THREAD

**Issue by monotek** [helm/helm#4397] opened 2018-07-30 10:24 UTC
We're currently use Helm a in our Jenkins pipeline. At the moment we have to download & extract the Helm binary in a additional buildstep.  

Would be nice an official Helm container would be available on DockerHub. 

There are already some inofficial Helm containers available so i think the need is there:

https://hub.docker.com/r/lachlanevenson/k8s-helm/
https://hub.docker.com/r/dtzar/helm-kubectl/

Output of `helm version`: 2.9.1
Output of `kubectl version`: 1.10
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by bacongobbler** [comment] 2018-07-30 14:07
See https://github.com/helm/helm/pull/1929

Dupe of #1320

**Closed by bacongobbler** 2018-07-30 14:07 UTC
