### ISSUE TITLE
Helm v3.3.0+ template rendering error : can't give argument to non-function

### ISSUE THREAD

**Issue by baptiste-dauphin** [helm/helm#8704] opened 2020-09-08 13:38 UTC
After my helm client upgrade. I had to update my unbound deployment, so I issued `helm upgrade` and this happends.
I'm in a folder where I downloaded locally this chart https://hub.helm.sh/charts/stable/unbound/1.0.0
```bash
helm upgrade --install \
unbound \
-n default \
-f path/to/my/values.yaml \
.
```
```
Error: UPGRADE FAILED: template: unbound/templates/deployment.yaml:34:28: executing "unbound/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") $>: error calling include: template: unbound/templates/configmap.yaml:1:7: executing "unbound/templates/configmap.yaml" at <(eq (len .Values.calicoFloatingIpsPool) 0) or (not .Values.oneDeployUnitPerFip)>: can't give argument to non-function eq (len .Values.calicoFloatingIpsPool) 0
```

I tried with `v3.3.1` and `v3.3.0`, both failed.
I solved this rendering error by reverting to `v3.2.4`

Output of `helm version`: 
- `version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}`  
Also this one  
- `version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}`

Output of `kubectl version`:
- `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
- baremetal

**Comment by bacongobbler** [comment] 2020-09-09 00:48
> at <(eq (len .Values.calicoFloatingIpsPool) 0) or (not .Values.oneDeployUnitPerFip)>

Your function arguments are in the wrong order. Use `if or ((eq (len .Values.calicoFloatingIpsPool) 0) (not .Values.oneDeployUnitPerFip))` instead.

Duplicate of https://github.com/helm/helm/issues/7711.

**Closed by bacongobbler** 2020-09-09 00:48 UTC
