### ISSUE TITLE
need help, spring boot microservice app not deploying using helm, guide me through it

### ISSUE THREAD

**Issue by vardans6** [helm/helm#8482] opened 2020-07-18 19:20 UTC
i have spring boot java microservice app want to deploy it through helm into minikube?  But its failing , i have repository of my app at dockerhub as vardans6/gts-rds007:latest  . kindly help me

**Comment by yxxhero** [comment] 2020-07-19 13:50
Duplicate of #8483

**Comment by Cweiping** [comment] 2020-07-20 01:23
Do you have any error logs? Please use `--debug` flag to get some output. Try to describe your chart scene and environment information to better understand your problem.

**Closed** 2020-07-22 16:44 UTC
Labels: question/support
