### ISSUE TITLE
How can one test a template that uses `lookup`?

### ISSUE THREAD

**Issue by dcow** [helm/helm#8436] opened 2020-07-13 06:29 UTC
>Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a `helm template` or a `helm install|update|delete|rollback --dry-run`, so the `lookup` function will return `nil` in such a case.

Is there a way I can test the `lookup` function prior to deploying a chart? If not, is it really necessary to forbid helm from contacting the API server during a dry run? My expectation of a `--dry-run` in other software is that no state is modified but that I can see exactly what *would* happen during a full run. This is not the case if your chart uses lookup to fill in template values.

I would expect that during a dry run helm allows `GET` and `HEAD` requests to API server resources but **not** mutating methods like `PUT`, `PATCH`, and `POST`. If there's a need to have a network-free flow as exists today, perhaps `helm template` could elide the network calls while `helm install|upgrade|delete|rollback --dry-run` would perform the required `lookup`s.

**Comment by bacongobbler** [comment] 2020-07-13 14:30
Duplicate of #8137. Let’s keep the conversation in one ticket. Thanks.

**Closed by bacongobbler** 2020-07-13 14:30 UTC
