### ISSUE TITLE
Feature request: Additional field Cluster in Release object

### ISSUE THREAD

**Issue by katsew** [helm/helm#7775] opened 2020-03-18 02:25 UTC
Hi, I want to add `Release.Cluster` field, which can get by running `kubectl config get-contexts`,  to avoid duplicating the value among clusters.

I'm using helm on GKE with multi-cluster environment.
When I start using helm, I have a single cluster and there is no problem with that.
However, if I deploy the same chart with different clusters, I'm having the problem of duplicated resource on GCP.
For instance, I deploy ingress with annotation `kubernetes.io/ingress.global-static-ip-name` to reserve static ip on GCP, duplicated name is not allowed, so we have to change their name for each clusters.
Currently I workaround by renaming annotation value for each cluster.

If I have the Cluster field in Release object, the resource name will not duplicated.

```
annotations:
  kubernetes.io/ingress.global-static-ip-name: "{{ .Release.Cluster }}-app"
```

**Comment by hickeyma** [comment] 2020-03-18 10:43
Duplicate of #2055

**Comment by hickeyma** [comment] 2020-03-18 10:44
@katsew This looks like a duplicate of #2055. Have a look at that issue and add your comment to it.

I am going to close this as a duplicate. It can be re-opened if need be.

**Closed by hickeyma** 2020-03-18 10:44 UTC
