### ISSUE TITLE
Helm v3 install/upgrade does not list resources like v2

### ISSUE THREAD

**Issue by nodesocket** [helm/helm#9661] opened 2021-04-29 23:05 UTC
Just upgraded from Helm v2 to v3. I know, behind the times. Previously, in Helm v2 when doing `install` or `upgrade` it showed a summary of Kubernetes resources created and modified:

```
ubuntu@kubernetes-master:$ helm install --name postgresql --values values.yaml ./
NAME:   postgresql
LAST DEPLOYED: Thu Apr 29 22:54:28 2021
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Pod(related)
NAME                            AGE
postgresql-postgresql-master-0  0s
postgresql-slave-0              0s
==> v1/Secret
NAME                 AGE
postgresql-password  0s
==> v1/Service
NAME                 AGE
postgresql           0s
postgresql-headless  0s
postgresql-read      0s
==> v1/StatefulSet
NAME                          AGE
postgresql-postgresql-master  0s
postgresql-slave              0s
```

In `v3` this seems to have been removed. Is there anyway to view the created/modified Kubernetes resources when running `install` or `upgrade`?

**Comment by bacongobbler** [comment] 2021-04-30 00:48
This is due to the Kubernetes status API changing between kubernetes releases. #5952 is tracking the issue. https://github.com/helm/helm/pull/7728 provides a solution.

Closing as a duplicate of #5952, but please let me know if this is a separate issue that is not addressed with #7728. Thanks!

**Closed by bacongobbler** 2021-04-30 00:48 UTC
