### ISSUE TITLE
Tests pass when golang function name and comment for docs don't match

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6683] opened 2019-10-17 02:41 UTC
Noticed this in this PR #6661 . The function name was changed to `Map` but comment was unchanged - `DeepCopyMap` and all the tests and checks still passed. Manual review and comment was needed to change this. I would recommend to look into this and fix it. A normal `golint` usually catches this. Somehow our `golangci-lint` missed this

**Comment by bacongobbler** [comment] 2019-11-06 19:17
Filed an issue upstream: https://github.com/golangci/golangci-lint/issues/843

**Comment by jan25** [comment] 2019-11-19 19:57
@bacongobbler should we disable the flag mentioned here https://github.com/golangci/golangci-lint/issues/843#issuecomment-553501108? Strangely golangci ignores this linting case by default

**Comment by technosophos** [comment] 2020-05-01 21:56
Closing, as this seems to be "intended behavior" in upstream right now. Feel free to re-open if there is some concrete fix we want to make to the Helm code base.

**Closed by technosophos** 2020-05-01 21:56 UTC
Labels: bug
