### ISSUE TITLE
Unable to use helm on Raspberry pi armv7l architecture.

### ISSUE THREAD

**Issue by mjnovice** [helm/helm#6784] opened 2019-10-24 21:16 UTC
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0+unreleased", GitCommit:"9668ad4d90c5e95bd520e58e7387607be6b63bb6", GitTreeState:"dirty"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/arm"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Raspberry PI picocluster.

I installed helm, and then initialised tiller, using 
`helm init  --service-account tiller --tiller-image=jessestuart/tiller`

However when I try to do
`helm ls`
I get this error in the tiller pod

```
[storage] 2019/10/24 21:05:00 listing all releases with filter
[storage/driver] 2019/10/24 21:05:30 list: failed to list: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: i/o timeout
```
curl on that url works too,
```
$ curl -k https://10.96.0.1:443/version?timeout=32s
{
  "major": "1",
  "minor": "14",
  "gitVersion": "v1.14.8",
  "gitCommit": "211047e9a1922595eaa3a1127ed365e9299a6c23",
  "gitTreeState": "clean",
  "buildDate": "2019-10-15T12:02:12Z",
  "goVersion": "go1.12.10",
  "compiler": "gc",
  "platform": "linux/arm"
}
```

**Comment by hickeyma** [comment] 2019-10-25 08:37
This might be related to #6227

**Comment by mjnovice** [comment] 2019-10-25 15:30
@hickeyma seems this issue is exactly the same as #6227

**Comment by hickeyma** [comment] 2019-10-25 15:50
ok, going to close this as a duplicate of #6227

**Closed by hickeyma** 2019-10-25 15:50 UTC
Labels: question/support
