### ISSUE TITLE
Validation Error - Not Found

### ISSUE THREAD

**Issue by rnkhouse** [helm/helm#7801] opened 2020-03-24 15:31 UTC
I am getting validation error upon installing any chart.

    helm install stable/jenkins --name jenkins
    Error: validation failed: [secrets "jenkins" not found, configmaps "jenkins" not found, configmaps "jenkins-tests" not found, persistentvolumeclaims "jenkins" not found, serviceaccounts "jenkins" not found, roles.rbac.authorization.k8s.io "jenkins-schedule-agents" not found, rolebindings.rbac.authorization.k8s.io "jenkins-schedule-agents" not found, services "jenkins-agent" not found, services "jenkins" not found, deployments.apps "jenkins" not found]

Output of `helm version`:

    Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}

Output of `kubectl version`:

    Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

    AKS

**Comment by bacongobbler** [comment] 2020-03-24 15:36
duplicate of #7797.

**Closed by bacongobbler** 2020-03-24 15:36 UTC
