### ISSUE TITLE
Consider including repository URI in stored release

### ISSUE THREAD

**Issue by absoludity** [helm/helm#6464] opened 2019-09-20 06:17 UTC
The current format in beta3 for the stored release [1] includes most things about the install chart, but not the repository URI from which the chart was obtained. I'm guessing this is because the client does not need to conflate the origin of the chart with a release, but it would be useful metadata to have stored, for UIs such as Kubeapps or even the helm CLI.

For example, with this, the `[CHART]` option to the `helm upgrade` command could potentially be optional (defaulting to the repo of the current release). (Not saying it should be, but just as an example of a UX decision that would be possible)

Happy to contribute the change, if there is no reason not to store the repository used for a release.

(Originally asked on slack at [2])

[1] https://github.com/helm/helm/blob/v3.0.0-beta.3/pkg/release/release.go#L20
[2] https://kubernetes.slack.com/archives/C51E88VDG/p1568077343137800

**Comment by thomastaylor312** [comment] 2019-09-26 23:05
@absoludity This sounds like it could be useful. Could you write up a bit more here about how you'd want the release object to look like and how it will handle the various use cases? I just wonder about how it will work with non-URL sources and how much it will add to the release object (which we already push up on the size limit for in Kubernetes)

**Comment by absoludity** [comment] 2019-10-01 02:01
Sorry, I should have copied the details I included in the slack thread linked above.

So it would, IMO, be helpful to have a reference to the repository when a release is created. If the release was created with a local chart (ie. without a repository) or otherwise unpublished (local) repository, then saying as much is also useful (ie. an empty value), but if the release was created from a repository, such https://kubernetes-charts.storage.googleapis.com/ or similar, then this is also useful when making UX decisions for a UI (whether command-line or otherwise).

> Could you write up a bit more here about how you'd want the release object to look like,

So just one extra field in the [Release struct](https://github.com/helm/helm/blob/v3.0.0-beta.3/pkg/release/release.go#L22).

> and how it will handle the various use cases?

If a user installs MyApp from the stable repository, but also has the beta repo enabled, then a UI can (a) choose to only display available updates from the same repository, or (b) enable the user to upgrade a release without asking which repository necessarily. If the repository field for the release is empty, the UI can use that to decide to prompt the user to select a repo when upgrading, or similar.

> I just wonder about how it will work with non-URL sources

Other than a direct tar.gz or directory link, the only non-URL source would be a local repository which is not a cache of an online repo? Or are there other non-URL sources? If it's not a repository, I'd use a blank value, but I'm not sure if it would be useful to identify a local-unpublished repository (certainly not any directory locations etc., but just with a `Local` or similar identifier).

> and how much it will add to the release object (which we already push up on the size limit for in Kubernetes)

I don't know the details of the current size issues, but it'd be 10s of bytes?

**Comment by absoludity** [comment] 2019-10-01 23:11
Great, thanks @thomastaylor312 .

**Comment by mattfarina** [comment] 2019-10-04 12:20
This is going to get more complicated when we take OCI registries into account in addition to helm repositories. I would suggest that knowing the difference is taken into account.

I would also suggest the digest be stored as well. Even if the chart is stored in another location the digest will tell us if it's the same chart used to create it. This can be useful for verification and other purposes.

**Comment by thomastaylor312** [comment] 2019-10-04 16:15
@absoludity So I think we are ok with the idea of metadata being added, but we need to do it in such a way that it is extensible and easy to add to later. Once the dev call is uploaded, I'll link to the discussion we had about it. I am thinking we should probably have a full proposal for adding metadata so we know what it will look like and then we can add the URL and digest

**Comment by absoludity** [comment] 2020-05-14 01:56
@thomastaylor312 When you've a chance, can you link to the discussion that was had about this so we know how to move forward? Thanks.

**Comment by liuming-dev** [comment] 2020-05-14 02:25
I think that we can store repository uri in release `values.yaml` by ourselves if Helm is not going to support this feature.

**Comment by absoludity** [comment] 2020-05-14 03:04
> I think that we can store repository uri in release `values.yaml` by ourselves if Helm is not going to support this feature, and this should be more flexible.

Yes, a chart author and user can agree to do that which would help a specific case, but the aim here was to improve the UI (helm CLI or other clients, such as Kubeapps) so that a release can be easily upgraded from the same repo. And the previous comment sounded as though the helm team were ok with the idea :)

**Comment by thomastaylor312** [comment] 2020-05-14 16:29
@absoludity At this point I do not know where that discussion is. I think it would be best to have the full proposal for what metadata would look like and this can be the first "feature" we add to the new metadata functionality

**Comment by CuBiC3D** [comment] 2020-11-20 00:30
Still relevant

**Comment by lindhe** [comment] 2020-11-22 13:33
This would actually be great not only for systems using Helm (like Kubeapps), but for humans too! If I installed the chart not so long ago, I probably know what chart to use during the upgrade. But if it was long ago, or worse till done by someone else, that it might not be trivial to figure out. Having the origin chart annotated somewhere would be very useful to not get into a nasty state during upgrades caused by using the wrong chart...

**Comment by bacongobbler** [comment] 2020-11-22 17:37
Dupe of #4256.

**Closed by bacongobbler** 2020-11-22 17:37 UTC
Labels: feature, v3.x
