### ISSUE TITLE
helm ls -a is giving "kubernetes cluster unreachable"

### ISSUE THREAD

**Issue by sriramkuau1** [helm/helm#11318] opened 2022-09-09 08:07 UTC
Background: Something happened yesterday ( unknown to me ) which led to usage of kubectl commands rendering my macbook unusable ( network/internet breaking and freezing all applications).

I fixed it by using
sriramkumar@Srirams-MacBook-Pro ~ % brew link --overwrite kubernetes-cli

And today I discovered it is helm that is broken, so eg. when I use `helm ls -a`

The error I'm getting is
sriramkumar@Srirams-MacBook-Pro ~ % helm ls -a
Error: Kubernetes cluster unreachable: Get "https://something.ibm.com:25628/version?timeout=32s": dial tcp: i/o timeout

result is, it is breaking network, freezing etc as described above

Details as you need
sriramkumar@Srirams-MacBook-Pro ~ % helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

sriramkumar@Srirams-MacBook-Pro ~ % whereis helm
helm: /usr/local/bin/helm /usr/local/share/man/man1/helm.1

sriramkumar@Srirams-MacBook-Pro Cellar % which helm
/usr/local/bin/helm
sriramkumar@Srirams-MacBook-Pro Cellar % ls -al /usr/local/bin/helm
lrwxr-xr-x  1 sriramkumar  admin  29  9 Sep 17:32 /usr/local/bin/helm -> ../Cellar/helm/3.9.4/bin/helm

sriramkumar@Srirams-MacBook-Pro Cellar % sw_vers
ProductName:    macOS
ProductVersion: 12.5.1
BuildVersion:   21G83

**Comment by hickeyma** [comment] 2022-09-12 09:25
Duplicate of #11306

**Closed** 2022-09-12 09:25 UTC
