### ISSUE TITLE
the gcp auth plugin is deprecated in v1.22+

### ISSUE THREAD

**Issue by RafalSkolasinski** [helm/helm#11069] opened 2022-06-22 09:59 UTC
Recently updated helm and I started seeing a following warning

```
W0622 10:57:31.900375   19803 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:39:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1900", GitCommit:"1f775cfbf564daf2c8f0ba548eff09f58045c4a4", GitTreeState:"clean", BuildDate:"2022-04-13T09:36:54Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

GKE, authed with
```
gcloud container clusters get-credentials <cluster name> --zone <zone> --project <project>
```

**Comment by yxxhero** [comment] 2022-06-25 07:28
@RafalSkolasinski which chart are you using. need more info.

**Comment by RafalSkolasinski** [comment] 2022-06-25 09:54
This seems to be independent from a specific chart as it happens in every helm operation, even just helm list.

But if you think it will be useful I'll provide more detailed example when I get to my workstation

**Comment by yxxhero** [comment] 2022-06-25 09:55
@RafalSkolasinski yes. It is useful.

**Comment by RafalSkolasinski** [comment] 2022-06-25 10:59
So these are the repos I have locally (some of these is just test stuff)
```
helm repo list
NAME                        	URL                                                              
minio                       	https://charts.min.io/                                           
minio-fork                  	https://bkleiner.github.io/minio-charts/                         
kokuwa                      	https://kokuwaio.github.io/helm-charts                           
gitea-charts                	https://dl.gitea.io/charts/                                      
argo                        	https://argoproj.github.io/argo-helm                             
seldonio                    	https://storage.googleapis.com/seldon-charts                     
jaegertracing               	https://jaegertracing.github.io/helm-charts                      
datawire                    	https://www.getambassador.io                                     
bitnami                     	https://charts.bitnami.com/bitnami                               
seldon-models               	https://rafalskolasinski.github.io/seldon-models/                
rafalskolasinski-helm-charts	https://rafalskolasinski.github.io/helm-charts/                  
bitnami-pre-2022            	https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
```

but even now on empty (no charts installed) GKE cluster I get 
```
$ helm list -A
W0625 11:50:04.362009  232884 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

**Comment by RafalSkolasinski** [comment] 2022-06-25 11:00
cluster was just created
```
kubectl get nodes
NAME                                                STATUS   ROLES    AGE     VERSION
gke-rafal-...  Ready    <none>   2m41s   v1.21.11-gke.1900
gke-rafal-...   Ready    <none>   2m41s   v1.21.11-gke.1900
gke-rafal-...   Ready    <none>   2m40s   v1.21.11-gke.1900
```

**Comment by emerout** [comment] 2022-06-26 15:08
As stated here : https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke, `gke-gcloud-auth-plugin` has to be installed:
```gcloud components install gke-gcloud-auth-plugin```

After this install, kubectl do not warn anymore, but helm does.

```helm list -A
W0626 17:00:31.680076    1020 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke```

**Comment by RafalSkolasinski** [comment] 2022-06-26 15:12
My take is that once this is installed, helm should stop throwing warnings?

**Comment by yadkov** [comment] 2022-07-01 12:55
> As stated here : https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke, `gke-gcloud-auth-plugin` has to be installed: `gcloud components install gke-gcloud-auth-plugin`
> 
> After this install, kubectl do not warn anymore, but helm does.
> 
> ```
> helm list -A
> W0626 17:00:31.680076    1020 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
> To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> ```

I have the same experience - after installing gke-gcloud-auth-plugin and kubectl components warnings stopped for kubectl but there is not change for helm.

**Comment by zmeggyesi** [comment] 2022-08-10 08:15
I'm just leaving my two cents here, since I'm also affected by this bug. GCloud is fully up-to-date, `kubectl` works just fine, but Helm cannot authenticate to the cluster, throwing the following:
```
zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
# helm ls --all-namespaces
W0810 10:12:42.502054   18164 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Error: Kubernetes cluster unreachable: Get "https://146.148.33.138/version": dial tcp 146.148.33.138:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions
```

Notably, the same version of 
```
# helm version
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}
```
on MacOS X work just fine and can manipulate the cluster perfectly.

**Comment by sharkymcdongles** [comment] 2022-08-10 13:47
> I'm just leaving my two cents here, since I'm also affected by this bug. GCloud is fully up-to-date, `kubectl` works just fine, but Helm cannot authenticate to the cluster, throwing the following:
> 
> ```
> zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
> # helm ls --all-namespaces
> W0810 10:12:42.502054   18164 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
> To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> Error: Kubernetes cluster unreachable: Get "https://146.148.33.138/version": dial tcp 146.148.33.138:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions
> ```
> 
> Notably, the same version of
> 
> ```
> # helm version
> version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}
> ```
> 
> on MacOS X work just fine and can manipulate the cluster perfectly.

This is incorrect. I tested and it will cause it to fail completely. The problem is the current auth flow uses gcloud directly via kubectl. If you check your GCP config you will see something like this:

```
    auth-provider:
      config:
        access-token: blah
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib64/google-cloud-sdk/bin/gcloud
        expiry: "2021-04-20T16:53:01Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

In 1.25+ this is no longer allowed and you must use the client-go auth flow directly however gcloud only gives you current gcp certificates unless you tell it to or it detects you are on 1.25+ kubectl. To fix this you must set the env var `USE_GKE_GCLOUD_AUTH_PLUGIN=True` before invoking `gcloud container clusters get-credentials`.

Afterward your cert will have this instead:

```
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
```

Be sure you installed gke-gcloud-auth-plugin first or it won't work. 

`gcloud components install gke-gcloud-auth-plugin`

So to me this is not a bug and is a valid warning.

**Comment by bluemalkin** [comment] 2022-08-10 14:30
@sharkymcdongles great find, I can confirm that this fixes it for me too.

**Comment by hickeyma** [comment] 2022-08-10 15:16
@RafalSkolasinski @zmeggyesi Do you mind checking the suggestion by @sharkymcdongles in https://github.com/helm/helm/issues/11069#issuecomment-1210699479?

**Comment by zmeggyesi** [comment] 2022-08-11 08:04
So @sharkymcdongles was right, and I after setting the envvar, my Kubeconfig did change. I'm still getting a `connectex` error: 
```
zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
# set USE_GKE_GCLOUD_AUTH_PLUGIN=True

zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
# gcloud container clusters get-credentials gitlab-runners --zone us-central1-c --project devops-core
Fetching cluster endpoint and auth data.
kubeconfig entry generated for gitlab-runners.

zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
# helm ls --all-namespaces
Error: Kubernetes cluster unreachable: Get "https://146.148.33.138/version?timeout=32s": dial tcp 146.148.33.138:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
```
But at this point, I'm not sure that's Helm's fault...

**Comment by sharkymcdongles** [comment] 2022-08-11 08:37
@zmeggyesi you don't have the auth plugin installed from the looks of it.

Check by running:

`gke-gcloud-auth-plugin --version`

then if not do:

`gcloud components install gke-gcloud-auth-plugin`

**Comment by zmeggyesi** [comment] 2022-08-11 08:52
@sharkymcdongles I seem to have it - I've specifically removed and re-installed the plugin before trying to regenerate the kubenconfig with the `USE_GKE_GCLOUD_AUTH_PLUGIN=True` var set:
```
zmegg@DEVELOP-CORE C:\Users\zmegg\Downloads
# gke-gcloud-auth-plugin --version
Kubernetes v1.23.0-alpha+66064c62c6c23110c7a93faca5fba668018df732
```
Having that `-alpha` in there does not fill me with much confidence, though...

**Comment by sharkymcdongles** [comment] 2022-08-11 10:15
@zmeggyesi do kubectl commands work with this kubeconfig? It seems to me you are possibly running in a container and the port is in use because this error upon Googling is a generic that usually happens due to this.

**Comment by zmeggyesi** [comment] 2022-08-11 11:04
@sharkymcdongles Yeah, that's the weirdest part. Kubectl works like a charm, and I'm running bare metal on my Windows dev machine (Docker was the only lead I found by googling it as well).

Like I said, at this point, I'm not sure if this is Helm's fault, though the question is whose then...

**Comment by mnp** [comment] 2022-08-25 20:55
I'm getting this too on Mac Monterey, just for `helm ls`  Kubectl got happy after doing the plugin and env.

```
$ gke-gcloud-auth-plugin --version
Kubernetes v1.23.0-alpha+66064c62c6c23110c7a93faca5fba668018df732

$ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

$ sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

$ echo $USE_GKE_GCLOUD_AUTH_PLUGIN
True
```

Feel free to ask for other deets.

**Comment by RafalSkolasinski** [comment] 2022-09-01 13:21
After following steps from https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke (which seems pretty much the same as above mentioned I do not see errors anymore).

**Comment by hickeyma** [comment] 2022-09-01 15:05
Thanks for feedback @RafalSkolasinski. Closing as fixed in third party.

**Closed by hickeyma** 2022-09-01 15:05 UTC
Labels: bug
