### ISSUE TITLE
Provide a means of dynamically setting .Chart.AppVersion during install or upgrade without editing Chart.yaml

### ISSUE THREAD

**Issue by Kallevin** [helm/helm#11011] opened 2022-06-02 10:40 UTC
We are looking for a way of setting the Chart.AppVersion in our pipeline in a way that, 'helm history' would return correct app versions.
```
REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION
1       	Mon Jun  8 11:39:51 2020	superseded	spring-1.0.0	1.0.0      	Install complete
2       	Mon Jun  8 12:19:21 2020	superseded	spring-1.0.0	1.0.0      	Upgrade complete
3       	Mon Jun  8 12:20:51 2020	deployed  	spring-1.0.0	1.0.0      	Upgrade complete
```
Currently helm' history' returns similar results as above (loaned from here: https://github.com/helm/helm/issues/8194#issuecomment-640598047) and not the actual app version.
```
helm upgrade --app-version "$variable
```
With command like that we would like to achieve results as below.
```
REVISION	UPDATED                 	STATUS    	CHART       	APP VERSION	DESCRIPTION
1       	Mon Jun  8 11:39:51 2020	superseded	spring-1.0.0	1.0.1      	Install complete
2       	Mon Jun  8 12:19:21 2020	superseded	spring-1.0.0	1.0.2      	Upgrade complete
3       	Mon Jun  8 12:20:51 2020	deployed  	spring-1.0.0	1.0.3      	Upgrade complete
```
Currently we are setting the app version like this:
```
sed -i "s/^version:.*$/version: $(git describe)/" chart/Chart.yaml
sed -i "s/^appVersion:.*$/appVersion: $(git describe)/" chart/Chart.yaml
helm upgrade app ./chart
```

**Comment by bacongobbler** [comment] 2022-06-04 08:14
Closing as a duplicate of #8194. Please keep the discussion to that thread as that is where we are collecting feedback from community members on this subject. The use case you provided has been brought up a few times in that thread.

Thanks.

**Closed by bacongobbler** 2022-06-04 08:14 UTC
