### ISSUE TITLE
helm template generates output not including child chart

### ISSUE THREAD

**Issue by zyf0330** [helm/helm#5239] opened 2019-01-31 03:22 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I use `helm template` to generate k8s configs, and find child charts of dep don't be included in output yaml.

**Comment by bacongobbler** [comment] 2019-02-04 18:46
Seems to work for me.

```
PS C:\Users\me> helm create foo
PS C:\Users\me> cd foo
PS C:\Users\me\foo> code requirements.yaml
PS C:\Users\me\foo> cat .\requirements.yaml
PS C:\Users\me\foo> cat .\requirements.yaml
dependencies:
- name: nginx-ingress
  version: "0.31.0"
  repository: "https://kubernetes-charts.storage.googleapis.com"
PS C:\Users\me\foo> helm dep update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading nginx-ingress from repo https://kubernetes-charts.storage.googleapis.com
Deleting outdated charts
PS C:\Users\me\foo> helm template .
[...]
---
# Source: foo/charts/nginx-ingress/templates/default-backend-deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
```

Did you remember to run `helm dep up` or `helm dep build`?

**Comment by zyf0330** [comment] 2019-02-05 03:09
Maybe I described wrongly.  I mean there is one more dep level inside child
dep chart.

**Comment by hickeyma** [comment] 2019-02-05 10:36
@zyf0330 Can you provide the example so we can troubleshoot your issue?

**Comment by zyf0330** [comment] 2019-02-05 10:37
Ok, maybe next week.

**Comment by zyf0330** [comment] 2019-02-12 02:41
After test, I find that I must do `helm dep build` for every child dep chart to ensure generate full yaml.

**Comment by bacongobbler** [comment] 2019-02-12 02:50
That makes sense. Dependencies are only resolved one level down. Dependencies of dependencies aren't resolved.

I'm going to close this as working as intended.

**Closed by bacongobbler** 2019-02-12 02:50 UTC
Labels: question/support

**Comment by zyf0330** [comment] 2019-02-12 02:52
So I must resolve requirements manually to build dep before `helm template`, right?

**Comment by bacongobbler** [comment] 2019-02-12 02:54
If you rely on sub-subcharts, yes.
