### ISSUE TITLE
Helm 3 template didn't output invalid YAML content during YAML parse error

### ISSUE THREAD

**Issue by wi1dcard** [helm/helm#7397] opened 2020-01-14 09:37 UTC
Helm3 seems not to output the YAML contents when failed to parse YAML to JSON:

```
$ helm template test ./deploy/chart -f ./deploy/values/values.dev.yaml.gotmpl --debug

install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: ...

Error: YAML parse error on admin-api/templates/deployment.yaml: error converting YAML to JSON: yaml: line 25: could not find expected ':'
helm.go:76: [debug] error converting YAML to JSON: yaml: line 25: could not find expected ':'
YAML parse error on admin-api/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/pkg/action/install.go:455
helm.sh/helm/v3/pkg/action.(*Install).Run
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/pkg/action/install.go:214
main.runInstall
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/cmd/helm/install.go:214
main.newTemplateCmd.func1
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/cmd/helm/template.go:63
github.com/spf13/cobra.(*Command).execute
        /private/tmp/helm-20191220-6557-12hg170/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /private/tmp/helm-20191220-6557-12hg170/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /private/tmp/helm-20191220-6557-12hg170/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /private/tmp/helm-20191220-6557-12hg170/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
        /usr/local/Cellar/go/1.13.5/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:1357
```

From my understanding, Helm2 with tillerless would output the rendered YAML although they are invalid and this information was helpful for debugging the issues of my templates.

I also found that:

- #1546 implements this feature in Helm2. But I can not found the same part of codes in Helm3 since the tiller has been removed. 
- In #7088, the guy is facing the same problem. However, people are discussing the issue inside the chart itself, not the different behavior between Helm2 and Helm3.

I'm happy to submit a PR to fix that. Here's a really simple workaround, just replace:

https://github.com/helm/helm/blob/985827d09a0456551e116805a7c41c32800c85c0/cmd/helm/template.go#L65-L67

with:

```go
// Copied from #1546
if err != nil {
	if strings.HasPrefix(err.Error(), "YAML parse error") {
		err = fmt.Errorf("%s\n%s", err, rel.Manifest)
	}
	return err
}
```

and it works fine.

However, I'm not sure - if this is an intentional change? Or there's any other reason we don't print the YAML?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

EKS

**Comment by jurgenweber** [comment] 2020-01-16 00:25
yeah, this is driving me insane also. Just want ot see it and it would be so easy to resolve... instead of guessing.

**Comment by hickeyma** [comment] 2020-01-16 11:57
@wi1dcard Do you mins showing the output when using Helm v2 on this chart?

**Comment by wi1dcard** [comment] 2020-01-16 12:25
@hickeyma  This is regardless of any specific chart. You can reproduce the issue with any chart that includes invalid YAML. For example here are the outputs using Helm v2:

```
/ # helm version
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
/ # helm create dummy
Creating dummy
/ # vi dummy/templates/deployment.yaml
/ # helm template dummy/
---
# Source: dummy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
---
# Source: dummy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dummy
    app.kubernetes.io/instance: release-name

---
# Source: dummy/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-dummy-test-connection"
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-dummy:80']
  restartPolicy: Never

---
# Source: dummy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
asjdasjdh::::aaaaaaaaaaaaaa
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dummy
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-dummy
      securityContext:
        {}

      containers:
        - name: dummy
          securityContext:
            {}

          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}


---
# Source: dummy/templates/ingress.yaml


/ # helm install --dry-run dummy dummy/
Error: This command needs 1 argument: chart name
/ # helm install --dry-run dummy/
Error: YAML parse error on dummy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'

---
# Source: dummy/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "invincible-manatee-dummy-test-connection"
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: invincible-manatee
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['invincible-manatee-dummy:80']
  restartPolicy: Never

---
# Source: dummy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: invincible-manatee-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: invincible-manatee
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
---
# Source: dummy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: invincible-manatee-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: invincible-manatee
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dummy
    app.kubernetes.io/instance: invincible-manatee

---
# Source: dummy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invincible-manatee-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: invincible-manatee
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
asjdasjdh::::aaaaaaaaaaaaaa
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dummy
      app.kubernetes.io/instance: invincible-manatee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dummy
        app.kubernetes.io/instance: invincible-manatee
    spec:
      serviceAccountName: invincible-manatee-dummy
      securityContext:
        {}

      containers:
        - name: dummy
          securityContext:
            {}

          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}


/ #
```

**Comment by wi1dcard** [comment] 2020-01-16 12:34
FYI, Helm v3 outputs (using the same chart which was tested with Helm v2 in the previous comment):

```
/ # helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
/ # helm template dummy dummy/
Error: YAML parse error on dummy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
/ # helm install --dry-run dummy dummy/
Error: YAML parse error on dummy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
/ # helm template --debug dummy/
install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: /dummy

Error: YAML parse error on dummy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
helm.go:76: [debug] error converting YAML to JSON: yaml: line 13: could not find expected ':'
YAML parse error on dummy/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/install.go:455
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:214
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:214
main.newTemplateCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/template.go:63
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
/ # helm install --debug --dry-run dummy dummy/
install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: /dummy

Error: YAML parse error on dummy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
helm.go:76: [debug] error converting YAML to JSON: yaml: line 13: could not find expected ':'
YAML parse error on dummy/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/install.go:455
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:214
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:214
main.newInstallCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/install.go:116
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```

**Comment by hickeyma** [comment] 2020-01-16 13:59
I am trying to understand the output you expect from Helm 2 to Helm 3 and where the issue is. 

Here is the output for successful `helm template` of scaffold chart in Helm 2 and Helm 3:

```console
$ helm2 create chrt-7397-good
Creating chrt-7397-good

$ helm2 template chrt-7397-good
---
# Source: chrt-7397-good/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
---
# Source: chrt-7397-good/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chrt-7397-good
    app.kubernetes.io/instance: release-name

---
# Source: chrt-7397-good/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-chrt-7397-good-test-connection"
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-chrt-7397-good:80']
  restartPolicy: Never

---
# Source: chrt-7397-good/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chrt-7397-good
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrt-7397-good
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-chrt-7397-good
      securityContext:
        {}
        
      containers:
        - name: chrt-7397-good
          securityContext:
            {}
            
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            

---
# Source: chrt-7397-good/templates/ingress.yaml


$ helm3 template chrt-7397-good
---
# Source: chrt-7397-good/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: chrt-7397-good/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chrt-7397-good
    app.kubernetes.io/instance: RELEASE-NAME
---
# Source: chrt-7397-good/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-chrt-7397-good
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chrt-7397-good
      app.kubernetes.io/instance: RELEASE-NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrt-7397-good
        app.kubernetes.io/instance: RELEASE-NAME
    spec:
      serviceAccountName: RELEASE-NAME-chrt-7397-good
      securityContext:
        {}
      containers:
        - name: chrt-7397-good
          securityContext:
            {}
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---
# Source: chrt-7397-good/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "RELEASE-NAME-chrt-7397-good-test-connection"
  labels:
    app.kubernetes.io/name: chrt-7397-good
    helm.sh/chart: chrt-7397-good-0.1.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['RELEASE-NAME-chrt-7397-good:80']
  restartPolicy: Never
```

It looks the same to me.

**Comment by hickeyma** [comment] 2020-01-16 14:06
Here is the output for helm template of scaffold chart with error introduced, in Helm 2 and Helm 3:

```console
$ helm2 create chrt-7397-err
Creating chrt-7397-err

$ helm2 template chrt-7397-err --debug
Error: parse error in "chrt-7397-err/templates/deployment.yaml": template: chrt-7397-err/templates/deployment.yaml:11: function "inc" not defined

$ helm3 template chrt-7397-err --debug
install.go:151: [debug] Original chart version: ""
install.go:168: [debug] CHART PATH: /root/test/helm-charts/v2/chrt-7397-err

Error: parse error at (chrt-7397-err/templates/deployment.yaml:11): function "inc" not defined
helm.go:76: [debug] parse error at (chrt-7397-err/templates/deployment.yaml:11): function "inc" not defined
```

It looks the same. 

I would appreciate if you could show me where the differences are.

**Comment by wi1dcard** [comment] 2020-01-16 14:11
@hickeyma Can you please add a YAML syntax error like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invincible-manatee-dummy
  labels:
    app.kubernetes.io/name: dummy
    helm.sh/chart: dummy-0.1.0
    app.kubernetes.io/instance: invincible-manatee
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
asjdasjdh::::aaaaaaaaaaaaaa
  replicas: 1
```

That would reproduce the issue.

Here are the commands I exactly tried:

```bash
## Helm2 - which outputs all the YAML contents
helm template dummy/
helm install --dry-run dummy/

## Helm3 - which not
helm template --debug dummy/
helm install --debug --dry-run dummy dummy/
```

**Comment by hickeyma** [comment] 2020-01-16 14:31
Ok. Can confirm the difference between Helm 2 and 3 using YAML syntax error in https://github.com/helm/helm/issues/7397#issuecomment-575168418:

```console
$ helm2 template chrt-7397-err --debug
REVISION: 1
RELEASED: Thu Jan 16 14:15:34 2020
CHART: chrt-7397-err-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []

HOOKS:
MANIFEST:

---
# Source: chrt-7397-err/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-chrt-7397-err
  labels:
    app.kubernetes.io/name: chrt-7397-err
    helm.sh/chart: chrt-7397-err-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
---
# Source: chrt-7397-err/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-chrt-7397-err
  labels:
    app.kubernetes.io/name: chrt-7397-err
    helm.sh/chart: chrt-7397-err-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chrt-7397-err
    app.kubernetes.io/instance: release-name

---
# Source: chrt-7397-err/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-chrt-7397-err-test-connection"
  labels:
    app.kubernetes.io/name: chrt-7397-err
    helm.sh/chart: chrt-7397-err-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['release-name-chrt-7397-err:80']
  restartPolicy: Never

---
# Source: chrt-7397-err/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-chrt-7397-err
  labels:
    app.kubernetes.io/name: chrt-7397-err
    helm.sh/chart: chrt-7397-err-0.1.0
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
spec:
asjdasjdh::::aaaaaaaaaaaaaa
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chrt-7397-err
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chrt-7397-err
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-chrt-7397-err
      securityContext:
        {}
        
      containers:
        - name: chrt-7397-err
          securityContext:
            {}
            
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
            

---
# Source: chrt-7397-err/templates/ingress.yaml


$ helm3 template chrt-7397-err --debug
install.go:151: [debug] Original chart version: ""
install.go:168: [debug] CHART PATH: /root/test/helm-charts/v2/chrt-7397-err

Error: YAML parse error on chrt-7397-err/templates/deployment.yaml: error converting YAML to JSON: yaml: line 13: could not find expected ':'
helm.go:76: [debug] error converting YAML to JSON: yaml: line 13: could not find expected ':'
YAML parse error on chrt-7397-err/templates/deployment.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/root/go/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:129
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/root/go/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/root/go/src/helm.sh/helm/pkg/action/install.go:469
helm.sh/helm/v3/pkg/action.(*Install).Run
	/root/go/src/helm.sh/helm/pkg/action/install.go:222
main.runInstall
	/root/go/src/helm.sh/helm/cmd/helm/install.go:216
main.newTemplateCmd.func1
	/root/go/src/helm.sh/helm/cmd/helm/template.go:64
github.com/spf13/cobra.(*Command).execute
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/root/go/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

```

**Comment by hickeyma** [comment] 2020-01-16 14:42
IIRC, this was raised in other issue(s). @bacongobbler do this sound familiar to you?

**Comment by wi1dcard** [comment] 2020-01-16 14:55
> IIRC, this was raised in other issue(s). @bacongobbler do this sound familiar to you?

Perhaps #7088 ?

**Comment by hickeyma** [comment] 2020-01-16 15:03
Thanks the one thanks @wi1dcard.

I am going to close this as a  Duplicate of #7088.

**Comment by hickeyma** [comment] 2020-01-16 15:06
Duplicate of #7088

**Closed** 2020-01-16 15:06 UTC
Labels: question/support

**Comment by aamirmalek** [comment] 2020-09-30 10:17
you guys 👎 

check for the indentation next line 👍
