### ISSUE TITLE
Using `helm install --upgrade --dry-run foo .` wil not result in an error when port name is too long

### ISSUE THREAD

**Issue by MaxKlotz** [helm/helm#12031] opened 2023-04-26 14:37 UTC
I use `helm install --dry-run` to let the server render my template.
When I do it everything is fine and I get the resulting `YAML`.
When I remove the `--dry-run` I am unable to install the chart because a value (in this case the port number for a service) is exceeding the maximum char length (15).
My expectation was, that I get the same error when I let the server render the template, this being the advantage of `--dry-run` vs `template`.

Full error:
`Error: UPGRADE FAILED: failed to create resource: Deployment.apps "foo" is invalid: spec.template.spec.containers[0].ports[0].name: Invalid value: "12345678901234-port": must be no more than 15 characters`

Output of `helm version`:
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by MaxKlotz** [comment] 2023-04-27 07:11
But one thing. The docs for [Debugging Templates](https://helm.sh/docs/chart_template_guide/debugging/) it says
> helm install --dry-run --debug: We've seen this trick already. It's a great way to have the server render your templates, then return the resulting manifest file.

Isn't this documentation misleading, when `--dry-run` does *not* contact the server?

**Comment by joejulian** [comment] 2023-05-09 23:36
Is is indeed. Would you mind filing a docs issue in [helm-www](https://github.com/helm/helm-www/issues)

**Comment by joejulian** [comment] 2023-05-09 23:37
I'm going to go ahead and close this as a duplicate of #8137

**Closed by joejulian** 2023-05-09 23:37 UTC
Labels: question/support

**Comment by MaxKlotz** [comment] 2023-05-13 16:46
Issue is opened. Thank you for the feedback :)
