### ISSUE TITLE
Alow hypen in variable names

### ISSUE THREAD

**Issue by MartinGolding515** [helm/helm#9801] opened 2021-06-14 12:43 UTC
if a subchart has a hypen in the name it will cause errors when trying to use this value elsewhere in the parent chart. I want to reference the overriden  sub-chart variables in the parent chart to avoid duplication of variables. It is not possible to use templating in values.yaml, otherwise I could override the sub-chart variables from another section of values.yaml in the parent.

e.g: from Chart.yaml:
  - name: prometheus-adapter
    version: 2.14.1
    repository:  https://prometheus-community.github.io/helm-charts

in template file of the parent helm chart:
    {{ .Values.prometheus-adapter.}}

**Comment by bacongobbler** [comment] 2021-06-14 16:57
https://github.com/helm/helm/issues/2192#issuecomment-293739257

**Comment by bacongobbler** [comment] 2021-06-14 16:58
closing as a duplicate of #2192.

**Closed by bacongobbler** 2021-06-14 16:58 UTC
