### ISSUE TITLE
helm deployment upgrade failure due to changes in container.env: map

### ISSUE THREAD

**Issue by matth-boise** [helm/helm#4864] opened 2018-10-31 20:56 UTC
Output of `helm version`: 
- minikube and kops cluster1:
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

- kops cluster2:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
- minikube:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

- kops cluster1:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- kops cluster2:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  repro'd in AWS and Minikube

i encountered a failure to upgrade a deployment where the deployment's single container's env map was changed.  (the upgrade essentially added ~9 env vars and removed 1.)  i reproduced this in minikube and on different aws (kops) clusters with different configurations.  i also reproduced this after upgrading helm client.  i was able to create 2 simple charts that reproduce this issue.

it is important to note that re-ordering the environment variables in the upgraded chart or changing the environment variables' names and/or values can make this issue go away - i.e., after making such changes the upgrade succeeds.

helm shows the failure as:
```
Error: UPGRADE FAILED: Deployment.apps "nginx" is invalid: spec.template.spec.containers: Required value
```
tiller shows:
```
2018/10/31 20:11:23 Cannot patch Deployment: "nginx" (Deployment.apps "nginx" is invalid: spec.template.spec.containers: Required value)
2018/10/31 20:11:23 Use --force to force recreation of the resource
[kube] 2018/10/31 20:11:23 error updating the resource "nginx":
	 Deployment.apps "nginx" is invalid: spec.template.spec.containers: Required value
[tiller] 2018/10/31 20:11:23 warning: Upgrade "nginx" failed: Deployment.apps "nginx" is invalid: spec.template.spec.containers: Required value
```
kube-apiserver shows:
```
log:I1031 20:11:23.086510 1 wrap.go:42] PATCH /apis/apps/v1/namespaces/matth/deployments/nginx: (2.394356ms) 422 [[Go-http-client/2.0] 10.100.22.165:49086]
```

the simple charts that show this are here: https://github.com/matth-boise/helm-upgrade-bug

steps to reproduce:
`helm install nginx-1 ; helm upgrade nginx-2`

**Comment by mattfarina** [comment] 2018-11-01 14:56
> it is important to note that re-ordering the environment variables in the upgraded chart or changing the environment variables' names and/or values can make this issue go away

ick. Since this happens with a core object and on upgrade like this I wonder if the problem is with strategic merging.

**Comment by mortent** [comment] 2018-11-04 17:34
I looked into your example in more detail. What seems to cause the error from Kubernetes is that the environment variable `KMS_AVAILABLE` is set twice in both versions of the chart. Removing one of them fixes the problem with the example. 
I don't fully understand why the duplicate env variables cause a problem with this example, cause a simple example with only the two duplicate env variables works. I am still looking into it.

**Comment by matth-boise** [comment] 2018-11-05 18:54
as you pointed out, this is not as simple as having duplicate env var definitions.

if you change the second KMS_AVAILABLE definition in nginx-2/templates/deployment.yaml (line 233)  to have value "foo" 
```
            - name: KMS_AVAILABLE
              value: "foo"
```
the upgrade (or `kubectl apply -f`) **will** work.

if you add a third KMS_AVAILABLE definition to nginx-2/templates/deployment.yaml immediately after the 2nd KMS_AVAILABLE definition 
```
            - name: KMS_AVAILABLE
              value: "foo"
            - name: KMS_AVAILABLE
              value: "foo"
```
the upgrade will **not** work.  (if you add a fourth KMS_AVAILABLE like above ^^ upgrade also fails.  if you add a 4th and 5th definition like ^^, the upgrade also fails.)

**Comment by mortent** [comment] 2018-11-06 05:50
I think your best solution here is to avoid duplicate entries for environment variables. I know adding duplicates doesn't always cause the chart to fail, but it seems like avoiding it will fix the problem. I also don't see any reason why you would want an environment variable defined more than once.

I talked to some of the people in the kubernetes team that works on this part of the code base, and it probably is unlikely that there will be a fix for this anytime soon. The apply/patch functionality is already in the process of being rewritten to fix several known issues with the current solution: https://github.com/kubernetes/enhancements/issues/555

**Comment by bacongobbler** [comment] 2020-05-14 22:20
closing as inactive.

**Closed by bacongobbler** 2020-05-14 22:20 UTC
Labels: bug
