### ISSUE TITLE
helm version is still v0.1.0+abcdefg

### ISSUE THREAD

**Issue by mboersma** [helm/helm#305] opened 2015-12-02 20:18 UTC
Building `helm` from current (post-0.2.0) master embeds a misleading version string:
```console
$ make install
go build -o bin/helm -ldflags "-X main.version=v0.1.0+b2242b3" helm.go
install -d /usr/local/bin/
install -m 755 bin/helm /usr/local/bin/helm
$ helm --version
helm version v0.1.0+b2242b3
$ helm up
[WARN] A new version of Helm is available. You have v0.1.0+b2242b3. The latest is 0.2.0
---> Download version 0.2.0 here: https://github.com/helm/helm/releases/tag/0.2.0
---> Updating charts
---> Done
```
The problem seems to be that the `git` command in the Makefile finds the v0.1.0 tag in preference to the 0.2.0 tag:
```console
$ git tag
0.0.1
0.1.0
0.2.0
v0.1.0
$ git describe --tags --abbrev=0 2>/dev/null
v0.1.0
```

**Comment by adamreese** [comment] 2015-12-02 20:42
@sgoings the leading `v` returns for another round havoc

**Comment by sgoings** [comment] 2015-12-02 20:49
Removed the v0.1.0 tag (as it was a duplicate of 0.1.0 but used to kick off Travis). All is clean again. If you plan on pushing tags (@technosophos, @mboersma), please run:

```
git tag -d v0.1.0
```

**Closed by sgoings** 2015-12-02 20:49 UTC
Labels: bug

**Comment by mboersma** [comment] 2015-12-02 22:30
I had to delete the existing git tags and fetch them again. All happy now.
