### ISSUE TITLE
Helm doesn't respect TLS certificate expiration

### ISSUE THREAD

**Issue by antoniaklja** [helm/helm#5224] opened 2019-01-29 11:16 UTC
It looks like Helm doesn't respect TLS certificate expiration for both the client and the server.

```
kubectl get secret tiller-secret -o "jsonpath={.data.tls\.crt}" | base64 -d > cert.pem
openssl x509 -in cert.pem -text
```
returns that certificate has expired:
```
Validity
  Not Before: Jan  9 13:15:00 2018 GMT
  Not After : Jan  9 13:15:00 2019 GMT
```

then `helm upgrade` doesn't complain that certificate has expired.

I found this in [Using SSL Between Helm and Tiller](https://github.com/helm/helm/blob/master/docs/tiller_ssl.md) but it doesn't solve the acutal problem. Client has to set this flag explicitly(most of the people don't use it), on the other hand, server doesn't verify client certs.

> If I use --tls-verify on the client, I get Error: x509: certificate has expired or is not yet valid

**Comment by bacongobbler** [comment] 2019-02-06 16:07
I'm having a tough time categorizing this one as I can see both sides of the coin here.  On one hand, verifying that the certificate has not expired seems like a common thing that should be checked for regardless of whether `--tls-verify` is enabled or not. On the other hand, this was the exact use case it was designed for: `--tls-verify` will not check that the certificate is valid if disabled. The behaviour here seems completely in line with the intended use case.

I was going to mention that we could change the default value to `true` for Helm 3, but we've removed Tiller so these flags have also been removed.

@technosophos any thoughts on this one? Should we verify the certificate expiry date regardless of whether `--tls-verify` is enabled or not?

**Comment by bacongobbler** [comment] 2019-02-06 16:09
Marking as a general support ticket for the time being until we can figure out whether this was intended by design.

**Comment by SlickNik** [comment] 2019-02-07 07:49
IMHO from inspecting the code, this seems intended. The cert doesn't get validated and certificate details (including details like whether the hostname / IP matched the ones in the SAN, etc) don't get checked unless the `--tls-verify` flag is enabled. @antoniaklja Additionally, for mutual auth (i.e. for tiller to validate the client cert as well) you need to enable the `--tiller-tls-verify` flag on `helm init` when the initial tiller install happens.

**Comment by antoniaklja** [comment] 2019-02-07 08:21
what's the actual difference between the following params?
`--tiller-tls               install Tiller with TLS enabled`
and
`--tiller-tls-verify        install Tiller with TLS enabled and to verify remote certificates`

IMHO `TLS enabled` should support mutual certificate validation out of the box

**Comment by bacongobbler** [comment] 2019-02-07 08:22
Thanks @SlickNik for the double-check. Given that this is intended behaviour and there is no migration path forward (it's been removed in Helm 3), I think this ticket is good to close. Please feel free to reopen if this doesn't address your questions/concerns and we'll be happy to look into it. Thanks!

**Closed by bacongobbler** 2019-02-07 08:22 UTC
Labels: question/support
