### ISSUE TITLE
how could I upgrade crds in helm crds directory ? 

### ISSUE THREAD

**Issue by Uotas** [helm/helm#12344] opened 2023-08-29 05:25 UTC
I put my crds in the 'crds' directory instead of  'template/crds',  but now we need to upgrade our crds and apply some other crds to implement new functions.
Now I get the information that 'crds' directory only take an effect when first install helm. Under this situation, how can I upgrade my crds?

The way I try is: 
I try to move my crds to 'template/crds' but here some errors

`Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "xxxx(one crd name)"  in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "xxxx(helm release name)"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"`

then

I try to use 'pre-upgrade'  hook(put it in template/) to add these information to my crd,  it will output error

`
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: default
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: xxxx(our crd name)
`

`Error: UPGRADE FAILED: pre-upgrade hooks failed: warning: Hook pre-upgrade test_crds/templates/hook/crd-hook.yaml failed: customresourcedefinitions.apiextensions.k8s.io "xxxx(one crd name)" already exists`

How could I upgrade my crds now? or that is impossible？

Output of `helm version`: v3.9.0

Output of `kubectl version`: v1.18.0 

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by wujunwei** [comment] 2023-08-29 09:41
There is a heresy :   adding annotation manually `meta.helm.sh/release-name:(your release name)` `meta.helm.sh/release-namespace: default` to your crds yaml.

**Comment by Uotas** [comment] 2023-08-29 09:47
> There is a heresy : adding annotation manually `meta.helm.sh/release-name:(your release name)` `meta.helm.sh/release-namespace: default` to your crds yaml.

but I could not add them manually, finding an automatically-upgrade way through helm or maybe webhook?

**Comment by Ithrael** [comment] 2023-08-29 13:39
This error message seems to be the result of conflicts between the first and second deployments. You could try deleting the release that was originally successfully deployed in the 'crds' directory (this is to delete the CRD of that release). Then, move your CRD to 'template/crds' and redeploy.

**Comment by Uotas** [comment] 2023-08-29 16:26
> This error message seems to be the result of conflicts between the first and second deployments. You could try deleting the release that was originally successfully deployed in the 'crds' directory (this is to delete the CRD of that release). Then, move your CRD to 'template/crds' and redeploy.

I tried this way , no error occurs, but old crds are not updated.

**Comment by Ithrael** [comment] 2023-09-01 00:57
> > This error message seems to be the result of conflicts between the first and second deployments. You could try deleting the release that was originally successfully deployed in the 'crds' directory (this is to delete the CRD of that release). Then, move your CRD to 'template/crds' and redeploy.
> 
> I tried this way , no error occurs, but old crds are not updated.

I can't reproduce this issue, but if you can provide your charts, I'd be willing to spend more time trying to solve this problem.

**Comment by gogowaiting** [comment] 2023-09-11 09:18
I have the same problem,but my old chart is helmv2 deploy, now i upgrade helm to v3 and convert v2 config app to v3, then pack v3 upgrade package to upgrade

**Comment by scottrigby** [comment] 2023-12-02 19:34
Closing as duplicate of https://github.com/helm/helm/issues/5871. A few more notes: 

Helm v3 does not have any special functionality to upgrade CRDs. See https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

This note from that doc page isn't heavily highlighted, but it's there. And other charts have made use of this method. See https://github.com/bitnami/charts/issues/21088#issuecomment-1821761242
> You can alternatively move the CRDs to their own chart or use helm template instead.

**Closed by scottrigby** 2023-12-02 19:34 UTC
Labels: question/support
