### ISSUE TITLE
latest release was changed to version 2.16.3 instead of 3.1.x

### ISSUE THREAD

**Issue by ozbillwang** [helm/helm#7598] opened 2020-02-14 20:23 UTC
Yesterday or before, it is still pointed to 3.1.0

But today the latest release is 2.16.3

could you please keep the consistant in release? I understand it will be updated, but normally, should be minor or patch version, not backward, especially backward to its preview major version (reference Semantic Versioning)

The latest release are important that we used for reference that which is the best version to follow up.

<img width="795" alt="Screen Shot 2020-02-15 at 7 19 42 am" src="https://user-images.githubusercontent.com/8954908/74564761-e9ec0e80-4fc3-11ea-94c5-54e0d6f24721.png">

**Comment by bacongobbler** [comment] 2020-02-14 20:33
Duplicate of #7597.

**Closed by bacongobbler** 2020-02-14 20:33 UTC
