### ISSUE TITLE
helm install failed if k8s doesn't have metrics api implementation

### ISSUE THREAD

**Issue by neverseek** [helm/helm#6439] opened 2019-09-17 08:36 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
helm.go:81: [debug] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
could not get apiVersions from Kubernetes
helm.sh/helm/pkg/action.(*Configuration).getCapabilities
        /go/src/helm.sh/helm/pkg/action/action.go:100
helm.sh/helm/pkg/action.(*Install).Run
        /go/src/helm.sh/helm/pkg/action/install.go:185
main.runInstall
        /go/src/helm.sh/helm/cmd/helm/install.go:219
main.newInstallCmd.func1
        /go/src/helm.sh/helm/cmd/helm/install.go:109
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main
        /go/src/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by neverseek** [comment] 2019-09-17 08:41
Actually, I was installing stable/prometheus-adapter with helm3 to give k8s a metrics api implementation.

**Comment by djpicard** [comment] 2019-10-04 04:48
I fixed those issues on my cluster by running this:
( GKE 1.14.3-gke.11 )
```
kubectl create clusterrolebinding cluster-admin-binding \
    --clusterrole cluster-admin \
    --user "$(gcloud config get-value account)"
kubectl create -f https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-stackdriver/master/custom-metrics-stackdriver-adapter/deploy/production/adapter.yaml
```

**Comment by bacongobbler** [comment] 2019-10-30 21:45
duplicate of https://github.com/helm/helm/issues/6361.

**Closed by bacongobbler** 2019-10-30 21:45 UTC
Labels: bug, v3.x
