### ISSUE TITLE
[helm3][question] Is there a way to render CRDs during install?

### ISSUE THREAD

**Issue by checorone** [helm/helm#8123] opened 2020-05-14 08:30 UTC
Hello, we are used HELM for a long time for deploying applications into our cloud. 
We have a lot of namespaces into our development cloud with the same custom resource.
We realize that we need a way to separate this resource between namespaces, because multiple devs can do changes into one development version and break something on the other side of the cloud.

We decided to render **Kind** of the resource with target namespace, but we found that it's not possible when CRD is placed into _crds_ directory. We wanted to keep CRD into _template_ directory with **pre-install** hook, but it also not working...

It's not working because pre-install hook happens after building of kubernetes objects, and when building is happens, there is no CRD for our CRs... 
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "cr-dev-resource" in version "company.com/v2"
helm.go:84: [debug] unable to recognize "": no matches for kind "cr-dev-resource" in version "company.com/v2"

```
So the only way to install CRD before build is to place it into _crds_ directory, but how to render it?

There is already implemented CRD rendering with helm template #6930 , but why it's not avilable on install stage?

What do we have now:
```
.
└── helm
    └── application-chart
        ├── Chart.yaml
        ├── templates
        │   ├── crd-template.yaml
        │   ├── cr-template.yaml
        └── values.yaml
```
What do we expect:
```
.
└── helm
    └── application-chart
        ├── Chart.yaml
        ├── crds
        │   └── crd-template.yaml
        ├── templates
        │   ├── cr-template.yaml
        └── values.yaml
```

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.14.2"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-04-23T22:11:11Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Private K8s cluster

**Comment by bacongobbler** [comment] 2020-05-14 19:37
duplicate of https://github.com/helm/helm/issues/7083. Please make sure to search for existing issues before opening a new one. Thanks!

**Closed by bacongobbler** 2020-05-14 19:37 UTC
