### ISSUE TITLE
Reference Library Chart appVersion in template

### ISSUE THREAD

**Issue by SamirHafez** [helm/helm#8047] opened 2020-05-04 13:40 UTC
Lets say I have a _Library Chart_ where I encapsulate logic for creating a Postgres database, like so:

`Chart.yaml`
```
apiVersion: v2
name: postgres
description: A Chart for creating Postgres databases
type: library

version: 0.1.0
appVersion: 9.6-alpine
```

`_dbCreate.yaml` (`Pod` resource shortened for clarity)
```
...
  containers:
    - name: postgres
      image: postgres:{{ $.Chart.AppVersion }}
      command: psql
...
```
Calling `helm template` from an _Application Chart_ that depends on this _Library Chart_ **renders `$.Chart.AppVersion` as the `appVersion` of the _Application Chart_ instead of the _Library Chart_ one.**

Is there a way I can reach the `appVersion` declared in the `Chart.yaml` of the _Library Chart_?

**Comment by bacongobbler** [comment] 2020-05-04 18:34
duplicate of https://github.com/helm/helm/issues/3920.

**Closed by bacongobbler** 2020-05-04 18:34 UTC
