### ISSUE TITLE
Error: Kubernetes cluster unreachable: Get "https://<endpoint>/version?timeout=32s": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by AdarShaked** [helm/helm#8693] opened 2020-09-03 13:26 UTC
Output of `helm version`:version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Hi, Im trying to create a release withoout using kubeconfig file. means i tried using --kube-apiserver --kube-token
(and later aslo added --cert-file) but any time i get:
Error: Kubernetes cluster unreachable: Get "https://35.202.98.186/version?timeout=32s": x509: certificate signed by unknown authority

the token I use is of service accout with cluster-admin role.
the command:
helm install myrelease bitnami/postgresql --kube-apiserver=https://<endpoint> --kube-token=<token> 
--cert-file=<path>
which flags i need to use in order to communicate with my gke cluster?

**Comment by AdarShaked** [comment] 2020-09-03 13:28
Or maybe change any settings on my cluster?

**Comment by bridgetkromhout** [comment] 2020-09-06 04:15
Hi, @AdarShaked - does this FAQ entry help? https://helm.sh/docs/faq/#on-gke-google-container-engine-i-get-no-ssh-tunnels-currently-open

> The issue is that your local Kubernetes config file must have the correct credentials.
>
> When you create a cluster on GKE, it will give you credentials, including SSL certificates and certificate authorities. These need to be stored in a Kubernetes config file (Default: ~/.kube/config so that kubectl and helm can access them.

I understand that you don't want to use a file, but are you using all the correct credentials for your GKE cluster? See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#connection_refused for more ideas. Specifically, `-kube-apiserver=https://` appears to be missing essential details.

**Comment by AdarShaked** [comment] 2020-09-06 05:50
Yes, im using ca certificate, apiserver and token .
do i need to use base64 encoded ca ?

**Comment by bacongobbler** [comment] 2020-09-09 01:08
> --ca-file flag is path to ca? or the ca itself?

--ca-file specifies the file path. This flag is only necessary if your chart repository requires a different certificate chain. Since you're trying to reach out to the bitnami repository, `--ca-file` should not be necessary.

**Comment by AdarShaked** [comment] 2020-09-10 11:34
Thanks,i see there is no way to connect the cluster with --insecure mode? with service account token + endpoint.
i saw this PR:
https://github.com/helm/helm/pull/8622
it is going to be merged soon?

**Comment by diegofps** [comment] 2020-09-10 15:43
Hi @AdarShaked,

I had the same problem when I was configuring helm on a K3S cluster. The error states that helm can't validate the server's certificate and thinks it is an untrusted server.

If you have the server's self-signed certificate you could add it to the system's known certificates like this:

```bash
SERVER="35.202.98.186:443"
sudo cp <path/to/server-certificate.crt> /usr/local/share/ca-certificates/${SERVER}.crt
sudo update-ca-certificates
```

If you don't have it but want to trust the certificate the server is presenting you could obtain it with:

```bash
openssl s_client -showcerts -connect $SERVER < /dev/null &> apiserver.crt
```

Hope it helps

**Comment by AdarShaked** [comment] 2020-10-13 17:22
@bacongobbler  No. Actually this PR:
https://github.com/helm/helm/pull/8622
Solves this issue.Do you know if its going to be merged soon?

**Comment by bacongobbler** [comment] 2020-10-13 17:46
#8622 needs the approval of two core maintainers before it can be merged.

**Comment by bacongobbler** [comment] 2020-10-13 17:54
If #8622 solves this issue, then I'm going to go ahead and close this as a duplicate of https://github.com/helm/helm/issues/8487, as that is the ticket tracking that feature request.

**Closed by bacongobbler** 2020-10-13 17:54 UTC
Labels: question/support
