### ISSUE TITLE
Document extra functions

### ISSUE THREAD

**Issue by kristinnardal2** [helm/helm#7888] opened 2020-04-08 06:38 UTC
Helm defines a few functions of its own in pkg/engine/func.go for serializing and deserializing data
https://github.com/helm/helm/blob/b735abe8371359fcf0b37de8014bfafcceb1bcf8/pkg/engine/funcs.go#L50-L57

I use the `toYaml` function quite a lot but I think the only reason I know that it exists is that the default templates when using `helm create` use this function. The main problem I have is that these functions aren't very discoverable, the only way to know that they exist is to either look through the helm code or see someone else use it.

I suggest we add documentation about these functions along with the [documentation]( https://helm.sh/docs/howto/charts_tips_and_tricks/#know-your-template-functions) for the include, required and template functions as well as in the chart template guide section about [template functions](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#helm).

**Comment by hickeyma** [comment] 2020-04-09 09:57
Duplicate of https://github.com/helm/helm-www/issues/489

**Comment by hickeyma** [comment] 2020-04-09 09:57
Closing as a duplicate of https://github.com/helm/helm-www/issues/489. Details added to that issue.
Thanks for raising this @kristinnardal2 .

**Closed by hickeyma** 2020-04-09 09:57 UTC
