### ISSUE TITLE
Action 'uninstall' doesn't check status of pods under deployment

### ISSUE THREAD

**Issue by Sora233** [helm/helm#7270] opened 2019-12-19 14:37 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Action 'uninstall' delete deployment directly, not pods, and also not check the status of pods.
After deployment deleted, the serviceaccount is deleted too.
And meantime k8s kills the pods, pods catch the SIGTERM signal and try to access serviceaccount to do something. But now the serviceaccount doesn't exist.

**Comment by bacongobbler** [comment] 2019-12-20 18:16
is this a duplicate feature request for #2378? Or is this something else?

**Comment by Sora233** [comment] 2019-12-21 08:26
> is this a duplicate feature request for #2378? Or is this something else?

It looks good.

Is there anyone working on this?

**Comment by bacongobbler** [comment] 2019-12-21 16:25
Not currently, no. Feel free to pick this one up!

Closing as a duplicate of #2378. Thanks!

**Closed by bacongobbler** 2019-12-21 16:25 UTC
Labels: question/support
