### ISSUE TITLE
Incorrect location for helm plugins installation.

### ISSUE THREAD

**Issue by zodiac182** [helm/helm#9942] opened 2021-07-14 08:30 UTC
I have set the environment variables as following.
declare -x HELM_CACHE_HOME="/opt/storage/helm_home/helm3/.cache/"
declare -x HELM_CONFIG_HOME="/opt/storage/helm_home/helm3/.config/"
declare -x HELM_DATA_HOME="/opt/storage/helm_home/helm3/.local/share/"
declare -x HELM_PLUGINS="/opt/storage/helm_home/helm3/.local/share/**helm**/plugins/"

But when doing helm plugin install, new plugins will be installed into /opt/storage/helm_home/helm3/.local/share/plugins/.
And after new plugin have been installed, it could not be listed via "helm plugin list".
"helm plugin list" could show the right plugin list under $HELM_PLUGINS.
"helm plugin uninstall" could remove the right plugin under $HELM_PLUGINS.
But "helm plugin install" could not install plugins to the right location. Seems it would be installed into $HELM_DATA_HOME/plugin/, but not $HELM_PLUGINS.

Output of `helm version`:
v3.6.2
Output of `kubectl version`:
Version: v1.21.0
Platform: linux/amd64

**Comment by yxxhero** [comment] 2021-07-14 08:42
It's similar to https://github.com/helm/helm/issues/9814, It already had a PR. @zodiac182

**Comment by mattfarina** [comment] 2021-07-14 13:49
This is a duplicate of #9814. It is a bug and one I think we should fix in the near future.

**Closed by mattfarina** 2021-07-14 13:49 UTC
