### ISSUE TITLE
helm deletes resources that was not created by helm

### ISSUE THREAD

**Issue by sczachariah** [helm/helm#4388] opened 2018-07-27 05:48 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On Prem Kubernetes installation

Let's say I already have a namespace called "sample" in k8s, which was created using "kubectl create ns".

Now I have a helm chart which has got yaml file for creating a namespace, the idea is that any new installation of my chart should create separate ns for my application to run. I am using variable "namespace" in values.yaml.

>apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

If I execute command : 
`helm install --name blue my-chart/ --set namespace=sample, `
It fails as expected since namespace already exists.
Error: release blue failed: namespaces "sample" already exists

`helm ls blue`
>NAME    REVISION       UPDATED                              STATUS       CHART                 NAMESPACE
blue       1                     Fri Jul 20 08:22:45 2018        FAILED        my-chart-0.1.0     default

Next if I execute:
`helm delete --purge blue`
release "blue" deleted

What I should expect from above helm delete command is that helm should not ideally delete any resources because helm did not create any.

Now the issue, the above helm delete command deleted ns "sample" from k8s. helm deleted ns "sample" even though it was not created by helm.

Kindly please address this serious bug.

**Comment by ivaravko** [comment] 2018-07-27 10:53
@sczachariah I believe you can use `helm install --namespace=sample` without set "namespace" value and delete named template for the Namespace.

**Comment by sczachariah** [comment] 2018-07-27 12:32
@ivaravko That command works if I already have a namespace. What if I want helm to create a new namespace for each new release  ?

**Comment by ivaravko** [comment] 2018-07-27 13:10
@sczachariah I have checked helm create namespace if not present, and reuse exists.

**Comment by sczachariah** [comment] 2018-07-27 13:50
@ivaravko Yea got it. 👍 
How do I implement if I do not want to reuse existing namespace. I would like helm to fail if namespace exists. ?

**Comment by bacongobbler** [comment] 2018-07-27 14:52
`helm install --namespace=sample` will create the namespace for you if it doesn't already exist. I do believe the original bug listed here though is valid. I believe this is a duplicate of another ticket. Lemme see if I can look it up.

**Comment by bacongobbler** [comment] 2018-07-27 15:14
I believe this is technically a duplicate of https://github.com/helm/helm/issues/4328 since the failed deploy failed, but the release was still tracking the namespace on `helm delete`. Is that a fair assumption, @sczachariah?

**Comment by sczachariah** [comment] 2018-07-27 16:36
Yep that’s right. Helm is deleting resource that it did not create.

**Comment by bacongobbler** [comment] 2018-07-27 16:40
sounds good! let's follow up in #4328.

**Closed by bacongobbler** 2018-07-27 16:40 UTC
