### ISSUE TITLE
helm 3.0-beta 3 fails to deploy if a chart is empty

### ISSUE THREAD

**Issue by jstrachan** [helm/helm#6396] opened 2019-09-09 10:44 UTC
helm 2 handles a chart being empty via conditions in the `values.yaml` (e.g. to disable dependent charges in the `requirements.yaml`). 

Trying the same chart with helm 3.0-beta 3 we have to explicitly add a dummy resource template in `templates/*.yaml` to avoid helm 3 silently failing. If you add verbose logging there's a message about `no resources found`

**Comment by hickeyma** [comment] 2019-09-18 13:16
@jstrachan Both v2 and v3 will not deploy/install a chart that does not have release artifacts (i.e. manifests with Kubernetes resources). It does deploy it 'failed'.

Here is output to a test I did using the scaffold chart and I removed all release artifacts except ingress which is disabled because I did not set the flag (`ingress.enabled `) to enable it:

```console
$ helm version
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}

$ helm create mychart
Creating mychart

$ ls mychart/templates/
_helpers.tpl  ingress.yaml

$ cat mychart/templates/ingress.yaml 
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
[....]

$ helm install mychart mychart/ --debug --dry-run
[debug] Created tunnel using local port: '39153'

[debug] SERVER: "127.0.0.1:39153"

Error: This command needs 1 argument: chart name
usr1@test1:~/test/helm-charts$ helm install --name mychart mychart/ --debug --dry-run
[debug] Created tunnel using local port: '38061'

[debug] SERVER: "127.0.0.1:38061"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/mychart

NAME:   mychart
REVISION: 1
RELEASED: Wed Sep 18 13:53:52 2019
CHART: mychart-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: nginx
  tag: stable
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []

HOOKS:
MANIFEST:

$ helm install --name mychart mychart/
Error: release mychart failed: no objects visited

$ helm ls
NAME   	REVISION	UPDATED                 	STATUS	CHART        	APP VERSION	NAMESPACE
mychart	1       	Wed Sep 18 13:54:03 2019	FAILED	mychart-0.1.0	1.0        	default  
```

**Comment by hickeyma** [comment] 2019-09-18 13:21
If you remove all the release artifacts and leave the `test` directory as follows then it will show the pod for it but does not deploy it either:

```console
$  tree mychart
mychart
├── charts
├── Chart.yaml
├── templates
│   ├── _helpers.tpl
│   └── tests
│       └── test-connection.yaml
└── values.yaml

3 directories, 4 files

$ helm install --name mychart-1 mychart/ --debug --dry-run
[debug] Created tunnel using local port: '36215'

[debug] SERVER: "127.0.0.1:36215"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/mychart

NAME:   mychart-1
REVISION: 1
RELEASED: Wed Sep 18 14:04:16 2019
CHART: mychart-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
fullnameOverride: ""
[...]
---
# mychart-1-test-connection
apiVersion: v1
kind: Pod
metadata:
  name: "mychart-1-test-connection"
  labels:
    app.kubernetes.io/name: mychart
    helm.sh/chart: mychart-0.1.0
    app.kubernetes.io/instance: mychart-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Tiller
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args:  ['mychart-1:80']
  restartPolicy: Never
MANIFEST:

$ helm install --name mychart-1 mychart/
Error: release mychart-1 failed: no objects visited
```

**Comment by jstrachan** [comment] 2019-11-01 13:04
@hickeyma I'm using a chart thats already been released and based on the `values.yaml` may include some resources to install or not. With helm 2.x this works fine; helm handles there being no resources. Switching to helm 3.0-rc1 we get an error: `Error: no objects visited'` - its fine for a chart to have no resources to install really.

**Comment by hickeyma** [comment] 2019-11-01 13:59
@jstrachan Can you provide the chart so as to be able to reproduce?

**Comment by bridgetkromhout** [comment] 2020-05-14 22:41
Hi, @jstrachan - we would need the chart to be able to reproduce. I'm closing this issue as we did not get the chart from you, but please let us know if you can provide a chart where it's still happening. Thanks!

**Closed by bridgetkromhout** 2020-05-14 22:41 UTC
Labels: question/support
