### ISSUE TITLE
What is the intention behind helm lint for metadata namespace?

### ISSUE THREAD

**Issue by ChristianWeissCG** [helm/helm#5585] opened 2019-04-10 20:11 UTC
From the comment at the beginning of this function one could think that there is a check related to metadata.namespace, but no related ERROR, WARN or INFO is triggered:
https://github.com/helm/helm/blob/master/pkg/lint/rules/template.go#L96

What is the intention?

**Comment by hickeyma** [comment] 2019-04-11 08:46
It could be an outdated comment. I think this could be included as part of #5584.

**Comment by hickeyma** [comment] 2019-04-11 08:46
Closing as duplicate of #5584.

**Closed by hickeyma** 2019-04-11 08:46 UTC

**Comment by Fantaztig** [comment] 2025-03-20 14:26
The comment is still there today :)
