### ISSUE TITLE
Resource entity too large yet helm template didn't render any large resources

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#8801] opened 2020-09-24 15:21 UTC
It seems like `helm install` for my local chart ended up sending all the content of a file within a folder named `notebooks` to the k8s api-server or similar, because I got a `Request entity too large: limit is 3145728` response while creating my secret.yaml resource in the chart. I got this error even if I slimmed down my secret.yaml template to be withuot any template logic.

Also, I could do `helm template` and manually `kubectl apply` the template output, which makes me confirm there is something fishy going on. Why does `helm` try to send resources outside the templates folder to the API server?

By adding a `.helmignore` file that ignored the `notebooks` folder, the issue went away. I don't think this should make a difference as the rendered templates doesn't change at all.

## Reproduction

1. `helm create crashing-chart && cd crashing-chart`
2. Add a folder named `notebooks` alongside Chart.yaml
3. Add a ~4 MB file or larger in the notebooks folder
4. `helm install dsp-metrics-exporter . --values values.yaml --debug`

## Issue description

```
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/erik/dev/sandvik/dsp/deploy/dsp-metrics-exporter

Error: create: failed to create: Request entity too large: limit is 3145728
helm.go:94: [debug] Request entity too large: limit is 3145728
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
	/home/circleci/helm.sh/helm/pkg/storage/driver/secrets.go:161
helm.sh/helm/v3/pkg/storage.(*Storage).Create
	/home/circleci/helm.sh/helm/pkg/storage/storage.go:66
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:320
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
```

## System info

Output of `helm version`:
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform: GKE

**Comment by bacongobbler** [comment] 2020-09-24 15:35
can you please determine if this is a duplicate of https://github.com/helm/helm/issues/8062? Usually this is caused due to an artifact within the chart directory.

**Comment by bacongobbler** [comment] 2020-09-24 15:37
Ah. I see you have determined the issue being due to the `notebooks` folder in your chart. This is intended; anything within the chart directory is packaged and rendered. Therefore, this is a duplicate of #8062. As you mentioned, adding `notebooks` to your .helmignore file resolves this issue.

The tl;dr is that you should not include artifacts in your chart directory that you do not intend to publish to Kubernetes.

**Closed by bacongobbler** 2020-09-24 15:37 UTC

**Comment by consideRatio** [comment] 2020-09-24 15:44
@bacongobbler ah, I think I understand the situation now.

The error comes from the creation of `sh.helm.release.v1.my-release-name.v1` which get's all the files bundled, even though I'm not using them to render output in a template. This was not at all obvious to me. Is this intentional?

**Comment by mattfarina** [comment] 2020-09-24 15:48
@consideRatio It might be intentional. In order to perform some operations (like rollback) Helm needs to have the information used to build the chart. If something is pulled in it's included in the release object.

**Comment by bacongobbler** [comment] 2020-09-24 15:50
Yep, completely intentional. @mattfarina's got the right idea.

**Comment by consideRatio** [comment] 2020-09-24 15:51
> @consideRatio It might be intentional. In order to perform some operations (like rollback) Helm needs to have the information used to build the chart. If something is pulled in it's included in the release object.

I see, and is it correct that even though the revision didn't consume any of it through its templates given the values passed, it should still be available in the helm secret for that revision?

**Comment by bacongobbler** [comment] 2020-09-24 15:54
yes.

**Comment by consideRatio** [comment] 2020-09-24 17:09
Thank you for the clarifications @bacongobbler and @mattfarina!

I'm considering options to help others avoid this confusion and have some ideas.

1. To add a `--debug` log message about the files package into release storage.
2. To provide clearer information when erroring in a release storage driver, such as the [storage/driver/secrets.go](https://github.com/helm/helm/blob/master/pkg/storage/driver/storage.go) or generally in [storage/storage.go](https://github.com/helm/helm/blob/master/pkg/storage/storage.go). My confusion was that the k8s secrets storage driver made me think a secret resource in the Helm chart had become bloated for some reason.

What do you think about a getting a PR for one of the ideas above?
