### ISSUE TITLE
Helm --dry-run option is not working as expected

### ISSUE THREAD

**Issue by 100daysofdevops** [helm/helm#10286] opened 2021-10-28 18:53 UTC
# Helm dry-run option is not working as expected

- Running helm install is working as expected when the namespace doesn't exist. In the below case namespace prashant doesn't exist it will throw the below exception

```
helm install hello hello/hello -n prashant
Error: INSTALLATION FAILED: create: failed to create: namespaces "prashant" not found
```

- Running the same command with --dry-run option giving the complete output. This should fail to as namespace doesn't exist
```
helm install hello hello/hello -n prashant --dry-run
NAME: hello
LAST DEPLOYED: Thu Oct 28 11:44:59 2021
NAMESPACE: prashant
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: hello/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "hello-test-connection"
  labels:
    helm.sh/chart: hello-0.1.2
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['hello:8080']
  restartPolicy: Never
MANIFEST:
---
# Source: hello/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    helm.sh/chart: hello-0.1.2
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello
---
# Source: hello/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    helm.sh/chart: hello-0.1.2
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello
      app.kubernetes.io/instance: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello
        app.kubernetes.io/instance: hello
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: hello
          securityContext:
            {}
          image: "cloudecho/hello:0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace prashant -l "app.kubernetes.io/name=hello,app.kubernetes.io/instance=hello" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace prashant $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace prashant port-forward $POD_NAME 8080:$CONTAINER_PORT
> helm install hello hello/hello -n prashant

```

Output of helm version: `
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}`

Output of kubectl version: `
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kind(locally deployed)

### Steps to replicate the issue

- Add any repo

```
helm repo add hello https://cloudecho.github.io/charts/
```

- Install the chart with dry-run option and namespace flag which doesn't exist, it should fail

```
helm install hello hello/hello -n prashant --dry-run
```

**Comment by bacongobbler** [comment] 2021-11-12 17:23
An explanation [is provided in the code](https://github.com/helm/helm/blob/b6a04cfbd544f0bbeea449129c1497eec8d99e2b/pkg/action/action.go#L123-L127). Closing as intentional by design.

**Closed by bacongobbler** 2021-11-12 17:23 UTC
Labels: question/support

**Comment by bacongobbler** [comment] 2021-11-12 17:30
See also https://github.com/helm/helm/issues/10335.
