### ISSUE TITLE
Error: create: failed to create: etcdserver: request is too large

### ISSUE THREAD

**Issue by aaron0609** [helm/helm#8088] opened 2020-05-09 02:47 UTC
I found a very strange issue when using helm 3, which is:

`[XXXX@XXXXXXX-01 ditto-1.0.0]$ helm install ditto . --debug
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /home/PATH_TO_MY_PROJECT/ditto-1.0.0

Error: create: failed to create: etcdserver: request is too large
helm.go:84: [debug] etcdserver: **request is too large**
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
        /home/circleci/helm.sh/helm/pkg/storage/driver/secrets.go:161
helm.sh/helm/v3/pkg/storage.(*Storage).Create
        /home/circleci/helm.sh/helm/pkg/storage/storage.go:66
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:315
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357`

I have never seen this error before, and actually it works when using helm 2.
Can anyone help on this?

**Comment by liuming-dev** [comment] 2020-05-09 04:43
cc https://github.com/helm/helm/issues/8062

**Comment by bacongobbler** [comment] 2020-05-11 15:58
duplicate of #8062 and #7264.

**Closed by bacongobbler** 2020-05-11 15:58 UTC
