### ISSUE TITLE
Import helm 3 in go with dep

### ISSUE THREAD

**Issue by harry-uglow** [helm/helm#7195] opened 2019-12-10 16:07 UTC
I'm trying to use this library to install helm charts from a Go application. Our project's dependencies are managed by dep, but since the move from k8s.io to helm.sh, adding any package in this repository to the project fails. For example, when running `dep ensure -add helm.sh/helm/v3/pkg/action` I receive the error:
```
Failed to add the dependencies:

  ✗ could not infer project root from dependency path: helm.sh/helm/v3/pkg/action: unable to deduce repository and source type for "helm.sh/helm/v3/pkg/action": unable to read metadata: unable to parse go-import metadata: XML syntax error on line 1: expected /> in element

adding dependencies failed
```
Importing a package through `k8s.io/helm` also no longer works as code in this repo imports from `helm.sh/helm/v3`.

How can I add this repository as a Go dependency with dep?

**Comment by TBBle** [comment] 2020-06-26 05:10
I think I've just bounced off this problem too, and it looks like the HTTP server is misconfigured.

```
PS> docker run -it golang:1.13
# Everything here is in the same Docker container
root@f82016944491:/go# go get -v helm.sh/helm/v3/pkg/chart/loader
package helm.sh/helm/v3/pkg/chart/loader: unrecognized import path "helm.sh/helm/v3/pkg/chart/loader" (parse https://helm.sh/helm/v3/pkg/chart/loader?go-get=1: no go-import meta tags ())
```

The problem appears to be that there's no metadata served from https://helm.sh/helm/v3/pkg/chart/loader?go-get=1, it just serves a 404. This contrasts with my own local GitLab instance, which will return metadata from any random path under the repo.

However, there is metadata for https://helm.sh/helm/v3?go-get=1
```
root@f82016944491:/go# go get -v helm.sh/helm/v3
get "helm.sh/helm/v3": found meta tag get.metaImport{Prefix:"helm.sh/helm/v3", VCS:"git", RepoRoot:"https://github.com/helm/helm"} at //helm.sh/helm/v3?go-get=1
helm.sh/helm/v3 (download)
package helm.sh/helm/v3: no Go files in /go/src/helm.sh/helm/v3
```

That's because the metadata is served at that URL. e.g.,
```
root@f82016944491:/go# curl https://helm.sh/helm/v3?go-get=1; echo
<!doctype html><html lang=en-us><head><meta charset=utf-8><meta name=go-import content="helm.sh/helm/v3 git https://github.com/helm/helm"><meta name=go-source content="helm.sh/helm/v3 git https://github.com/helm/helm https://github.com/helm/helm/tree/master{/dir} https://github.com/helm/helm/blob/master{/dir}/{file}#L{line}"><meta http-equiv=refresh content="0; url=https://github.com/helm/helm"></head><body>Nothing to see here; <a href=https://github.com/helm/helm>move along</a>.</body></html>
```

And then, having done that, Go now has the relevant metadata and knows how to fetch the packages.
```
root@f82016944491:/go# go get -v helm.sh/helm/v3/pkg/chart/loader
github.com/pkg/errors (download)
get "sigs.k8s.io/yaml": found meta tag get.metaImport{Prefix:"sigs.k8s.io/yaml", VCS:"git", RepoRoot:"https://github.com/kubernetes-sigs/yaml"} at //sigs.k8s.io/yaml?go-get=1
sigs.k8s.io/yaml (download)
helm.sh/helm/v3/pkg/chart
github.com/pkg/errors
sigs.k8s.io/yaml/vendor/gopkg.in/yaml.v2
helm.sh/helm/v3/internal/ignore
helm.sh/helm/v3/internal/sympath
sigs.k8s.io/yaml
helm.sh/helm/v3/pkg/chart/loader
```

So it looks like a workaround for this is to `go get helm.sh/helm/v3` so that Go has the repo available in $GOPATH/src. I haven't used `dep` though, so that might not be enough for it.

It's also possible I'm doing something incorrectly here, as I'm not really fully-across the Go modules discovery mechanisms yet.

----

All the above said, this works without issues if I am using `go get` to add deps to a module, I guess because it looks up the metadata somewhere else in modules mode.

```
PS> docker run -it golang:1.13
# New container compared to the previous tests
root@50ed29c120e6:/go# cd /
root@50ed29c120e6:/# mkdir t
root@50ed29c120e6:/# cd t
root@50ed29c120e6:/t# go mod init mytest
root@50ed29c120e6:/t# go get -v helm.sh/helm/v3/pkg/chart/loader
go: finding helm.sh/helm/v3 v3.2.4
go: finding helm.sh/helm v2.16.9+incompatible
go: downloading helm.sh/helm/v3 v3.2.4
go: downloading helm.sh/helm v2.16.9+incompatible
go: extracting helm.sh/helm/v3 v3.2.4
go: extracting helm.sh/helm v2.16.9+incompatible
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/pkg/errors v0.9.1
go: extracting github.com/pkg/errors v0.9.1
go: extracting sigs.k8s.io/yaml v1.2.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: extracting gopkg.in/yaml.v2 v2.2.8
go: finding github.com/pkg/errors v0.9.1
go: finding sigs.k8s.io/yaml v1.2.0
go: finding gopkg.in/yaml.v2 v2.2.8
helm.sh/helm/v3/pkg/chart
github.com/pkg/errors
gopkg.in/yaml.v2
helm.sh/helm/v3/internal/ignore
helm.sh/helm/v3/internal/sympath
sigs.k8s.io/yaml
helm.sh/helm/v3/pkg/chart/loader
```

**Comment by TBBle** [comment] 2020-06-26 05:16
I note that the top-level path was fixed in https://github.com/helm/helm-www/issues/381 before this issue was filed.

**Comment by TBBle** [comment] 2020-06-26 05:18
Oops, and two days ago the same issue was closed at https://github.com/helm/helm-www/issues/721, it appears Helm only supports modules-based flows now?

**Comment by bacongobbler** [comment] 2020-06-26 13:31
If you have suggestions on how to serve a page on every recursive sub tree with Hugo, we’d welcome a PR.

**Comment by TBBle** [comment] 2020-06-27 07:52
https://github.com/helm/helm-www/pull/733 should fix this, although it can't be fully tested until it goes to the live site, as the hostname needs to match.

**Closed** 2020-06-29 14:27 UTC
Labels: question/support

**Comment by TBBle** [comment] 2020-07-01 00:59
Confirmed fixed.

```
root@5f104dd7c3c5:/go# go get -v helm.sh/helm/v3/pkg/chart/loader
get "helm.sh/helm/v3/pkg/chart/loader": found meta tag get.metaImport{Prefix:"helm.sh/helm/v3", VCS:"git", RepoRoot:"https://github.com/helm/helm"} at //helm.sh/helm/v3/pkg/chart/loader?go-get=1
get "helm.sh/helm/v3/pkg/chart/loader": verifying non-authoritative meta tag
helm.sh/helm/v3 (download)
github.com/pkg/errors (download)
get "sigs.k8s.io/yaml": found meta tag get.metaImport{Prefix:"sigs.k8s.io/yaml", VCS:"git", RepoRoot:"https://github.com/kubernetes-sigs/yaml"} at //sigs.k8s.io/yaml?go-get=1
sigs.k8s.io/yaml (download)
helm.sh/helm/v3/pkg/chart
github.com/pkg/errors
sigs.k8s.io/yaml/vendor/gopkg.in/yaml.v2
helm.sh/helm/v3/internal/ignore
helm.sh/helm/v3/internal/sympath
sigs.k8s.io/yaml
helm.sh/helm/v3/pkg/chart/loader
```
