### ISSUE TITLE
How to : helm upgrade with external yaml files (sidecar.yaml / peerAuthentication.yaml)

### ISSUE THREAD

**Issue by i035249** [helm/helm#10539] opened 2022-01-11 14:28 UTC
Does anyone knows if it possible to use the command  > helm upgrade along with using external files such as sidecar.yaml / peerAuthentication.yaml during the installation? And if so, how to?

**Comment by bacongobbler** [comment] 2022-01-14 18:52
duplicate of #3276.

**Closed by bacongobbler** 2022-01-14 18:52 UTC
Labels: question/support
