### ISSUE TITLE
The output format of the helm template is wrong when the user marks a child chart template with "deprecated"

### ISSUE THREAD

**Issue by Cweiping** [helm/helm#8393] opened 2020-07-03 10:42 UTC
Output of `helm version`:

`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`:

`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"2cc6e0a70a", GitTreeState:"clean", BuildDate:"2020-03-26T04:33:27Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

how to reproduce:
Create a template that contains a sub-chart, and set the sub-chart Chart.yaml  to `deprecated: true`. Use the helm template command to obtain the parsed manifest. At this time, the expected result should be a manifest, but the actual output is as follows:
```
WARNING: This chart is deprecated
---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
......
......
```

I don't think this is in line with expectations. I just expect to get the list of resources. When I want to achieve the following functions, I can't get the expected results.

```shell
helm template demo &> /tmp/demo.yaml && kubectl create --dry-run=client -f /tmp/demo.yaml
```

My Propose:
 1. I didn't install it and suggested that it should ignore the alarm items.
 2. Because it is sub-chart deprecated, users should be prompted with more specific chart information when installing, which has a good experience when there are more sub-charts.

Finally, if you accept my suggestion, I can try to finish it.

**Comment by bacongobbler** [comment] 2020-07-03 13:54
Duplicate of #8262 which was fixed in #8277.

**Closed by bacongobbler** 2020-07-03 13:54 UTC

**Comment by Cweiping** [comment] 2020-07-04 01:26
When the sub-chart Chart.yaml to `deprecated: true`, [this PR](https://github.com/helm/helm/pull/8277) does not solve the problem:
```shell
helm template demo &> /tmp/demo.yaml && kubectl create --dry-run=server -f /tmp/demo.yaml
```
```
error: error validating "/tmp/demo.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

```shell
cat /tmp/demo.yaml
```
```
 WARNING: This chart is deprecated
---
# Source: wordpress/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
......
......
```

The `helm template` should only include manifest, but [the line](https://github.com/helm/helm/pull/8277/files#diff-1dcf80a24ef0460c3dab1363f093d31bR61) is checked by `kubectl` as a resource. @bacongobbler

**Comment by bacongobbler** [comment] 2020-07-04 02:42
Not if it’s displayed on standard error. That’s why #8277 fixes this. A Unix pipe (`|`) strips standard error from the output.

**Comment by Cweiping** [comment] 2020-07-04 03:29
OK, thx.
