### ISSUE TITLE
Helm ignores %KUBECONFIG%

### ISSUE THREAD

**Issue by rmorrise** [helm/helm#6700] opened 2019-10-18 13:49 UTC
`helm` is ignoring my `KUBECONFIG` setting and trying to read from my `%HOMEDRIVE%`, which is not where my config is located.

```
C:\Users\rmorrise>echo %KUBECONFIG%
C:\Users\rmorrise\.kube\config
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not get Kubernetes config for context "": open X:\/.kube/config: Access is denied.
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Docker Desktop for Windows (win 10 x64)

**Comment by rmorrise** [comment] 2019-10-18 14:22
Same issue exists with helm v2.15.0-rc.2

**Comment by rmorrise** [comment] 2019-10-18 14:33
Some additional steps that I've tried...
```
C:\Users\rmorrise>kubectl config current-context
docker-desktop

C:\Users\rmorrise>helm --kubeconfig "C:\Users\rmorrise\.kube\config" init --upgrade
$HELM_HOME has been configured at C:\Users\rmorrise\.helm.
Error: could not get kubernetes client: could not get Kubernetes config for context "": open X:\/.kube/config: Access is denied.
```

**Comment by pho-enix** [comment] 2019-11-05 10:35
Can confirm the behaviour for windows systems.

Strangely it works fine for PowerShell @ Mac.

**Comment by bacongobbler** [comment] 2020-07-09 17:35
Have you tried a more recent version of Helm 2?

Gentle reminder that the support window for bugfixes closes in a month. If nobody works on fixing this, we'll have to close this out and consider this as Helm 2's intended behaviour.

**Comment by bacongobbler** [comment] 2020-08-14 17:06
We are no longer accepting bug fixes for Helm 2. See https://helm.sh/blog/helm-v2-deprecation-timeline/ for more details.

**Closed by bacongobbler** 2020-08-14 17:06 UTC
Labels: bug, v2.x
