### ISSUE TITLE
helm list on Linux mishandles Windows release timestamps

### ISSUE THREAD

**Issue by cjmaloof** [helm/helm#7486] opened 2020-01-29 14:06 UTC
To reproduce: Use `helm install` to deploy a release from Windows 10 Enterprise. In Alpine Linux, run `helm list`. The "updated" timestamp is listed as **2020-01-28 11:10:34.2792443 -0500 -0500** (for EST), with the offset printed twice.

Examining the release secret shows timestamps formatted like `2020-01-28T11:10:34.2792443-05:00`. By contrast, releases deployed from the Linux container show timestamps like `2020-01-27T22:30:19.816038014Z`.

There don't seem to be issues in the other direction. `helm list` on Linux properly handles releases deployed from Linux, and `helm list` on Windows handles releases deployed from either OS.

(We discovered this issue because it breaks Helmsman deployments [here](https://github.com/Praqma/helmsman/blob/master/internal/app/helm_release.go#L42).)

Output of `helm version`: version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment] 2020-01-29 16:05
THanks for the report. Would this be fixed if we merged https://github.com/helm/helm/pull/7024?

**Comment by fsniper** [comment] 2020-01-29 16:13
I am not sure about the TZ changes. If it consolidates the TZ to the local TZ I believe it can solve the issue.

**Comment by cjmaloof** [comment] 2020-01-29 17:02
It seems like #7024 should make the format consistent. Given that the .String() result says it's "[meant for debugging](https://golang.org/pkg/time/#Time.String)" I guess that was the problem. Thanks!

**Comment by cjmaloof** [comment] 2020-01-29 17:08
For our specific use case, it also turns out that Helmsman devs [fixed this last week](https://github.com/Praqma/helmsman/pull/393/commits/33d37d64c2a4413690471cd8180805a295941f9d).

**Comment by technosophos** [comment] 2020-04-21 22:31
I have been trying to hunt this down. My current theory is that there is a timezone file that is missing somewhere on the host OS, but I haven't been able to confirm.

I am closing this as a duplicate of #7700, which is currently more active, so I am closing this in favor of that.

**Closed by technosophos** 2020-04-21 22:31 UTC
Labels: bug
