### ISSUE TITLE
Replicas not updated when applying an upgrade

### ISSUE THREAD

**Issue by micahlmartin** [helm/helm#4872] opened 2018-11-01 20:26 UTC
```
└─ $ ▶ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

```
└─ $ ▶ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.11-docker-8d637ae", GitCommit:"8d637aedf46b9c21dde723e29c645b9f27106fa5", GitTreeState:"clean", BuildDate:"2018-04-26T16:51:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

We noticed an odd behavior (helm 2.9.1) where if you're upgrading a chart and changing the replicas count in a deployment that it doesn't actually scale up or scale or down the pods. When running helm --debug upgrade it's very clear that the replicas: setting is updated in the template but it's basically a no-op on the deployment. If I copy the rendered template and do kubectl apply it scales the deployment properly. Is this expected or documented behavior somewhere?

**Comment by bacongobbler** [comment] 2018-11-01 21:02
dupe of https://github.com/helm/helm/issues/1873. In particular, check out https://github.com/helm/helm/issues/1873#issuecomment-429460214 for the explanation on why the resource was not updated.

Let me know if you have any further questions.

**Closed** 2018-11-01 21:02 UTC
Labels: question/support
