### ISSUE TITLE
Helm does not handle extra whitespace in the command line properly

### ISSUE THREAD

**Issue by sdake** [helm/helm#5863] opened 2019-06-09 11:57 UTC
Output of `helm version`:

(not running tiller - using extensively `template` mode)
```
Stevens-MacBook-Pro:~ sdake$ helm version
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Error: could not find tiller
Stevens-MacBook-Pro:~ sdake$ 
```

Output of `kubectl version`:

```
Stevens-MacBook-Pro:~ sdake$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
helm `template` mode does not use a cloud provider directly.

Extra whitespace in the command line to helm `template` and helm `install` result in broken behavior.  The expectation is that extra whitespace in the command line is discarded between flags.  Instead, the whitespace is in some way parsed, producing incorrect `yaml` files.  This is most prevalent in the documentation when used with a `\ `:

e.g.:
```
helm template $HOME/istio-1.1.6/install/kubernetes/helm/istio --name istio --namespace istio-system \ -f values-istio-minimal.yaml > $HOME/istio-minimal.yaml | grep configSources
```

The two whitespaces instead of one result in an incorrectly rendered manifest.

See https://github.com/istio/istio.io/issues/4121 for more analysis.

**Comment by hickeyma** [comment] 2019-06-17 09:15
@sdake I did some investigation into this using a simple chart. I was unable to reproduce the issue. Here is the output of my testing.

```console
$ cat chrt-5863/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}

$ cat chrt-5863/values.yaml 
favoriteDrink: coffee

$ cat chrt-5863-value.yaml
favoriteDrink: Whiskey

$ helm template --name chrt-5863 chrt-5863/
---
# Source: chrt-5863/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-5863-configmap
data:
  myvalue: "Hello World"
  drink: coffee

$ helm template --name chrt-5863 chrt-5863/ \  -f  chrt-5863-value.yaml
---
# Source: chrt-5863/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-5863-configmap
data:
  myvalue: "Hello World"
  drink: Whiskey

$ helm template --name chrt-5863 chrt-5863/ \  --set   favoriteDrink=water
---
# Source: chrt-5863/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-5863-configmap
data:
  myvalue: "Hello World"
  drink: water
```

**Comment by hickeyma** [comment] 2019-06-17 09:17
@sdake Just wondering what I might be missing here?

**Comment by bridgetkromhout** [comment] 2020-05-14 22:49
Hi, @sdake - thanks for making this bug report. As you may have seen, @hickeyma was unable to reproduce it. If you could provide detail we can use to reproduce it, that would be helpful. Until such a time, I'll close this as not reproducible.

**Closed by bridgetkromhout** 2020-05-14 22:49 UTC
Labels: bug

**Comment by sdake** [comment] 2020-05-15 01:28
@hickeyma thanks for trying to reproduce the issue. I also attempted to reproduce the issue with a slightly more complex manifest for a few hours. The shell escapes ` ` when proceeded by `\` and then passes that as an argv. This is all normal. It appears that in some conditions an empty arg of ` ` causes odd parsing conditions. I believe it may have to do with the fact that `-f` is not honored in some conditions, triggering the bug listed at the top of the issue, but this is just a guess. This is partly user error (bad input), and a bug (helmv2 behaves oddly with bad input). Just evidence that writing CLIs is extremely difficult.

Congratulations on graduation btw. We are using Helmv3 in Istio 1.6 as a building block.

Cheers
-steve
