### ISSUE TITLE
Tiller of helm v2.12.0 s390x can't be installed on minikube

### ISSUE THREAD

**Issue by luyisa** [helm/helm#5197] opened 2019-01-22 09:33 UTC
**CrashLoopBackOff** of tiller pod
And I have tried to compile based on - https://github.com/linux-on-ibm-z/docs/wiki/Building-Helm, still with the same error. 

And I print the log - 
standard_init_linux.go:190: exec user process caused "exec format error"

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Error: could not find a ready tiller pod
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/s390x"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/s390x"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
minikube version: v0.26.1

**Comment by hickeyma** [comment] 2019-01-22 09:52
Hey. Just trying to get some more details. 
Where did you download the s390x binary release from and what was the filename? What command did you use to install Tiller and what was the output of the command?

**Comment by luyisa** [comment] 2019-01-22 10:00
Two ways I have tried:
1. Get from https://storage.googleapis.com/kubernetes-helm/helm-v2.12.0-linux-s390x.tar.gz
-- run `helm init` to install tiller, no error returns
2. Compile following the guide - https://github.com/linux-on-ibm-z/docs/wiki/Building-Helm 
-- run `helm init --tiller-image gcr.io/kubernetes-helm/tiller:canary`

tiller pod got the same error

**Comment by hickeyma** [comment] 2019-01-22 10:04
Ok, so `helm init` command is not returning any error but the Tiller pod fails? Can you attach the full log for the Tiller pod after you install using the binary release?

**Comment by luyisa** [comment] 2019-01-22 10:11
Hi @hickeyma 
`standard_init_linux.go:190: exec user process caused "exec format error"`

Only one line log displays...

**Comment by luyisa** [comment] 2019-01-22 10:18
And one more info - we re-compiled minikube with s390x 

they are all installed s390x vm.

**Comment by hickeyma** [comment] 2019-01-22 10:23
The error you are getting appears sometimes when using binaries, images etc. that are for a different architecture. Can you check that your environment is all s390x?

**Comment by cwsolee** [comment] 2019-01-22 15:56
I didn't try installing as I don't have kub env right now but I tried the build instruction to build helm and tiller images, looks ok though. 
The "standard_init_linux.go:190: exec user process caused "exec format error"" usually means wrong architecture, wonder whether that might be the case.

**Comment by bacongobbler** [comment] 2019-01-22 16:33
All versions of Tiller are of amd64 architecture. We don't have any s390x tiller images, just s390x helm clients. Basically you're using the s390x release of the helm client, but when you call `helm init --tiller-image gcr.io/kubernetes-helm/tiller:canary`, you're asking Helm to install an amd64 architecture Tiller on your cluster, hence the error.

If you want to install tiller on a Kubernetes cluster running on 390x architecture you'll need to compile tiller from source with support for that architecture, then provide that image name using `helm init --tiller-image`. Have a look at the [tiller-multiarch](https://github.com/jessestuart/tiller-multiarch) project for some guidance on how to do this.

Closing as a duplicate of https://github.com/helm/helm/issues/4636 as the TODO action item for this issue. Thanks!

**Closed by bacongobbler** 2019-01-22 16:33 UTC

**Comment by bacongobbler** [comment] 2019-01-23 05:30
Right. Like I mentioned previously, the docs you are following instruct you how to compile the helm client against s390x, but not tiller. You need to compile tiller from source with GOARCH set to your desired architecture, push it up to a public registry then call `helm init --tiller-image ...`. Please have a look at the link I mentioned above. That will be more helpful.

**Comment by diederichm** [comment] 2019-03-14 13:35
Ok, i made this work for me - 
downloaded and extracted https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-s390x.tar.gz

docker build using this Dockerfile :
`FROM alpine:3.7

RUN apk update && apk add ca-certificates socat && rm -rf /var/cache/apk/*

ENV HOME /tmp

COPY helm /helm
COPY tiller /tiller

EXPOSE 44134
USER 65534
ENTRYPOINT ["/tiller"]
`
pushed this into my docker repo
ran 
`helm init --tiller-image diederichm/helm213:latest
$HELM_HOME has been configured at /root/.helm.

Tiller (the Helm server-side component) has been installed into your Kubernetes Cluster.

Please note: by default, Tiller is deployed with an insecure 'allow unauthenticated users' policy.
To prevent this, run `helm init` with the --tiller-tls-verify flag.
For more information on securing your installation see: https://docs.helm.sh/using_helm/#securing-your-helm-installation
Happy Helming!
`

**Comment by hickeyma** [comment] 2019-03-14 13:51
@diederichm That's great. Can you add the comment to #5444 as well?
