### ISSUE TITLE
Chart repositiory `cache` value in config is ignored

### ISSUE THREAD

**Issue by Hiruma31** [helm/helm#5703] opened 2019-05-09 19:38 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
NA

Hello !

While trying to configure Helm globally, I stumbled upon an issue with the cache directory.

```
/etc/helm/conf/repository/repositories.yaml
apiVersion: v1
repositories:
- name: test-helm
  [...]
  keyFile: ""
  cache: "/tmp/test-helm-index.yaml"
```

`HELM_HOME=/etc/helm/conf`

All sub-folder exists as generated by helm init, helm repo update creates the -index.yaml file properly in the /tmp folder (with the exception of #5517 ) but when I try to fetch a chart, I get
```
Error: no cached repo found. (try 'helm repo update'). open /etc/helm/conf/repository/cache/test-helm-index.yaml: no such file or directory
```

I believe I narrowed it down to here:
https://github.com/helm/helm/blob/master/pkg/helm/helmpath/helmhome.go#L61

With Helm not actually parsing the`cache:` entry in the config as it should, but deriving it from `HELM_HOME` by appending `/repository/cache`.

Thank you for your time !

**Comment by hickeyma** [comment] 2019-05-10 09:41
@Hiruma31 What steps/doc did you use to configure Helm globally?

**Comment by Hiruma31** [comment] 2019-05-14 18:51
@hickeyma Surprisingly there is no doc I am aware of. It seems like I didn't detailed the initial part in the end but basically I ran `helm init --client-only`, looked at what was created in `.helm/`, and tried to move all of it by mimicing it in /etc/helm/conf instead of $HOME/.helm.
Then I tried to tweak a few things to make it work, using the documented env variable and .yaml settings, but realized they aren't properly taken into consideration.

**Comment by hickeyma** [comment] 2019-05-15 12:44
I don't think that this is supported or if it a use case people are setting up.  Maybe someone out there has some details on how to set Helm globally?

**Comment by Hiruma31** [comment] 2019-05-15 14:32
That's the thing, I don't think I'm the only one who would like to setup a global config, much like sources.list or yum repos.
The confusing/broken part I wanted to highlight here is that the settings file has a cache field that's broken, because if you set it to a place out of `$HELM_HOME` and run `helm repo update`, the cache files are properly created into the specified folder (/tmp hear), but when you try to `helm fetch` a chart, it's not taking the config and look to the `$HELM_HOME` path instead. Which defeat the purpose of having the option as a whole...

**Comment by bacongobbler** [comment] 2019-05-15 14:38
This appears to be a duplicate of https://github.com/helm/helm/issues/2839.

**Comment by bacongobbler** [comment] 2019-05-15 14:39
TO work around this, you can use `helm init --client-only --home=/etc/helm/conf`.

**Comment by hickeyma** [comment] 2019-05-15 14:45
Thanks @bacongobbler for the heads up.

**Comment by Hiruma31** [comment] 2019-05-15 14:59
Thank you @bacongobbler :) However that's still not the actual issue. The full use case is that I want to let a config manager provision servers with it. But using helm init or mimicking the whole tree will always lead to the same couple of issues.
The first one being #5517 but that can be worked around, the other one being to give the ability to unprivileged users to update and fetch charts, but I would rather not `chmod 777 /etc/helm/conf/repository/cache/`... hence why I wanted to use `/tmp` for the cache. And yet while the parameter is read properly for `helm repo update`, it is not when using `helm fetch`.
Seeing the referenced issue #2839 and its linked PR #5422, I guess I will wait for it to be merged :smile:

**Comment by bridgetkromhout** [comment] 2020-05-18 21:46
Hi, @Hiruma31 -  Helm 3 now follows the XDG base directory standard, so this issue which existed in Helm 2 is no longer relevant in Helm 3. (Helm 2 is in bugfix-only mode, so we will not be adding features at this point.) Please see https://helm.sh/docs/faq/#how-do-i-put-the-helm-client-files-somewhere-other-than-their-defaults for details. That should let you set the alternate locations you need.

**Closed by bridgetkromhout** 2020-05-18 21:46 UTC
Labels: question/support
