### ISSUE TITLE
"helm completion" command sends warnings, and possibly errors to STDOUT

### ISSUE THREAD

**Issue by sstoyanovucsd** [helm/helm#8781] opened 2020-09-21 18:55 UTC
"helm completion" command (ex. "helm completion bash") sends warning messages and probably errors to STDOUT instead of STDERR.  This leads to the output containing the warning and sourcing into the running shell throws errors.

How to reproduce: Make your ~/.kube/config file group readable, then run "helm completion bash | head -n 10".

Example:
```bash
$ helm completion bash | head -n 10
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/redacted/.kube/config
# bash completion for helm                                 -*- shell-script -*-

__helm_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}
```

...leading to:
```bash
$ source <(helm completion bash)
-bash: WARNING:: command not found
```

Please send warnings and errors to STDERR.
<br>

Output of `helm version`:
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}

Output of `kubectl version`:
lient Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.7-eks-bffbac", GitCommit:"bffbacfd13a805a12d10ccc0ca26205ae1ca76e9", GitTreeState:"clean", BuildDate:"2020-07-08T18:30:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by chornlgscout** [comment] 2020-09-21 19:53
Note that this prevents `-oyaml` from producing valid yaml.

**Comment by bacongobbler** [comment] 2020-09-21 20:07
Please see #8779 for the fix.

Closing as a duplicate of #8776.

**Closed by bacongobbler** 2020-09-21 20:07 UTC
