### ISSUE TITLE
helm 3 fails silently in case of "malformed" kubeconfig

### ISSUE THREAD

**Issue by gorilych** [helm/helm#7385] opened 2020-01-13 03:08 UTC
Helm3 fails silently if it cannot read cluster from kubeconfig file:

```
$ helm3 version; echo $?
1
```

Affected version:

```
$ helm3 --kube-context=gullfaxi version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

I deliberately put `current-context: none` into `~/.kube/config` - this forces me to specify `--kube-context` and `--context` for helm2 and kubectl - this way I have less chances to apply manifests to a wrong cluster. Both helm2 and kubectl produce sane errors if I forgot to specify a context for a command:

```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Error: could not get Kubernetes config for context "": invalid configuration: context was not found for specified context: none
$ kubectl version
Error in configuration: context was not found for specified context: none
```

I expect the same behavior from helm3

W/A: remove `current-context` from kubeconfig

**Comment by marckhouzam** [comment] 2020-01-13 12:58
Yeah, this one has been causing us grief.
It's just been fixed by #6909 It will be part of the next helm patch release.

So this issue is a duplicate of #6863

**Closed by marckhouzam** 2020-01-13 12:58 UTC
