### ISSUE TITLE
helm lint doesnt verify subcharts are well-formed

### ISSUE THREAD

**Issue by antoniogomezalvarado** [helm/helm#4910] opened 2018-11-13 08:31 UTC
Hi,

I have the following chart structure:
```
ls -la ./main_chart

total 16
drwxr-xr-x   7 antoniogomez  staff   238 Nov 13 00:16 .
drwxr-xr-x   5 antoniogomez  staff   170 Jun  6 17:57 ..
-rw-r--r--   1 antoniogomez  staff   333 Apr 24  2018 .helmignore
-rw-r--r--   1 antoniogomez  staff    83 Apr 24  2018 Chart.yaml
drwxr-xr-x  54 antoniogomez  staff  1836 Nov 12 23:49 charts
drwxr-xr-x   6 antoniogomez  staff   204 Oct  3 10:34 roles
drwxr-xr-x   4 antoniogomez  staff   136 Apr 24  2018 templates
```

now if I run ```helm lint ./main_chart -f /tmp/input_values.yaml``` the following is the output:
```
==> Linting ./main_chart/
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist

1 chart(s) linted, no failures
```
Which indicates the `main_chart` is well formed. However, I put a malformed YAML template in one of the charts. If I check that specific chart ( one of the `charts` under `main_chart` dir ) with `helm lint main_chart/charts/sub_chart -f /tmp/input_values.yaml` I get the following:
```
==> Linting sub_chart
[INFO] Chart.yaml: icon is recommended
[INFO] values.yaml: file does not exist
[ERROR] templates/test.yaml: unable to parse YAML
	error converting YAML to JSON: yaml: line 27: did not find expected key
```
So i'm wondering is this by design? Helm lint only checks top level chart? Or is this a bug?

Thanks in advance dear community,

Antonio

Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:19:47Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS with Kops

**Comment by michelleN** [comment] 2018-11-15 14:01
If you were to put a malformed Chart.yaml in the sub chart and run `helm lint` again from the main chart, then it would fail. That leads me to believe that sub charts should also be linted. I think this might be a bug.
cc/ @prydonius - Can you confirm?

**Comment by prydonius** [comment] 2018-11-15 21:04
Yes, I believe `helm lint` currently only lints the top-level chart. I'm not 100% sure about whether it makes sense for it to recursively lint charts. Taking from the language package manager workflow, you typically only lint your own code and not your vendored dependencies. In the Helm case, the sub-chart might not be an upstream dependency but your own chart that you do want to lint (e.g. umbrella chart model), so that logic doesn't always apply. Even in that usecase, you could lint every sub-chart with a simple bash loop over the `./charts` directory.

If we do want to implement this in `helm lint`, my only concern would be that this is a behaviour change where `lint` now depends on sub-charts being checked out (i.e. ensuring `helm dep build` is run prior to linting). This could break existing scripts users are relying on, so we might need to implement this as an optional flag instead (e.g. `--recursive`).

**Comment by arundeepkurni** [comment] 2019-08-07 00:11
any update on this??

**Comment by woodcockjosh** [comment] 2019-08-07 21:44
Need this

**Comment by walterdolce** [comment] 2019-10-15 12:03
I am not in favour of `helm lint` having to chech subcharts. You only test what you own. If you own more than a chart (whether or not those are subcharts), test them in isolation.

If a 3rd party chart causes a failure in your build, send a PR to the upstream repository to fix the problem there :)

Ultimately I am in favour of this:
> you could lint every sub-chart with a simple bash loop over the ./charts directory.

**Comment by woodcockjosh** [comment] 2019-10-15 13:25
You can have subcharts that are not third party and not "external". They are "nested" charts
eg: 
```text
- parentchart
   - charts
      - child1chart
         - templates
      - child2chart
         - templates
   - requirements.yaml
```

with a `requirements.yaml` in the `parentchart` that looks like this:
```yaml
dependencies:
  - name: child1chart
    version: 0.1.1
  - name: child2chart
    version: 0.1.1
```

Right now I have to use a weird bash script to check all the subcharts

**Comment by dvpierce** [comment] 2019-11-22 20:08
I would really like a "--recursive" option as well. I know the child charts are probably fine but I feel very strongly that as part of a CICD workflow, everything should be linted/tested every time anyway. It's just one of those professional paranoia things.

**Comment by hickeyma** [comment] 2020-01-31 11:55
@antoniogomezalvarado @woodcockjosh @dvpierce @raffis @mnkyl I am wondering if issue #4910 is a duplicate of #5767? If so should be close this in favour of #5767? 

FYI, @mnkyl has a PR #7288 currently in review and close to be merged. I understand @raffis that you have just pushed PR #7502 but maybe it makes most sense to go ahead with PR #7288  in the circumstances?

**Comment by raffis** [comment] 2020-01-31 12:00
> FYI, @mnkyl has a PR #7288 currently in review and close to be merged. I understand @raffis that you have just pushed PR #7502 but maybe it makes most sense to go ahead with PR #7288 in the circumstances?

That link would have been useful :), did not see that pr, but yea looks like it does the same. I don't mind to close my pr.

**Comment by hickeyma** [comment] 2020-01-31 12:14
> That link would have been useful :), did not see that pr, but yea looks like it does the same. I don't mind to close my pr.

Ok, thanks for replying @raffis so promptly on this. I have closed out PR #7502 as a duplicate . I will close this issue as a duplicate also.

**Comment by hickeyma** [comment] 2020-01-31 12:15
Duplicate of #5767

**Comment by hickeyma** [comment] 2020-01-31 12:15
Closing issue as duplicate of #5767

**Closed by hickeyma** 2020-01-31 12:15 UTC
Labels: bug
