### ISSUE TITLE
related Job objects won't be deleted when Cronjob object is deleted

### ISSUE THREAD

**Issue by flyer103** [helm/helm#3017] opened 2017-10-07 20:05 UTC
I have created a chart which will run a `CronJob` but after `helm delete`, `Job` objects created by `CronJob` won't be deleted.

The sample chart could be downloaded from [here](https://o6qv1ipxn.qnssl.com/mycronjob.tgz) (The tgz file should be decompressed firstly and then could be installed).

Install the chart:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/829039/31311278-83e947bc-abdb-11e7-80d7-203482e80ee0.png">

Delete the chart:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/829039/31311283-b15cc84a-abdb-11e7-9961-0c1e860bedd2.png">

**Comment by bacongobbler** [comment] 2017-10-11 21:33
Interestingly enough this also appears to be the default behaviour for kubectl:

```

```

I wonder if this was done on purpose, and if so then perhaps this should be filed as an upstream bug.

**Comment by flyer103** [comment] 2017-10-12 02:26
@bacongobbler I have tested the `kubectl delete` behavior on k8s-v1.7.3 and k8s-v1.8.0 and always get the behavior that Job objects are deleted after the CronJob object is deleted until I use `kubectl delete --cascade=false`.

**Comment by bacongobbler** [comment] 2017-10-12 02:50
@flyer103 yeah I rescind that last thought; I also found that same behaviour after a fresh cluster. Must’ve been stale jobs from my `helm delete` testing.

**Comment by bacongobbler** [comment] 2017-10-12 18:00
One other thought that came up - Helm 2.6.2 does not target kubernetes 1.8 support. Perhaps this behaviour will be fixed once #3008 is merged, since after that is merged we will have 1.8 support. I'll test this chart on that branch and verify that thought.

**Comment by bacongobbler** [comment] 2017-10-12 18:22
nope; this is still an issue on master.

```
$ ~/go/src/k8s.io/helm/bin/helm install ./mycronjob
NAME:   pouring-fish
...
$ ~/go/src/k8s.io/helm/bin/helm delete pouring-fish
release "pouring-fish" deleted
><> k get jobs
NAME               DESIRED   SUCCESSFUL   AGE
hello-1507832340   1         1            20s
><> k get pods --show-all
NAME                     READY     STATUS      RESTARTS   AGE
hello-1507832340-wfrhs   0/1       Completed   0          28s
```

Version information for when I tested:

```
$ ~/go/src/k8s.io/helm/bin/helm version
Client: &version.Version{SemVer:"v2.6+unreleased", GitCommit:"13912b3cc0dc495442e68c523561fc564d170308", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6+unreleased", GitCommit:"13912b3cc0dc495442e68c523561fc564d170308", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-10-05T00:41:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by au-phiware** [comment] 2017-11-28 04:17
I have this same issue.
```
$ helm version                        
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+4bc5e7f9a6c25", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"not a git tree", BuildDate:"2017-11-10T02:50:25Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cloudbow** [comment] 2017-12-13 05:53
How do we work around this?

**Comment by innovia** [comment] 2017-12-25 08:14
same issue with kubernetes 1.8 and helm 2.7.2 the PR mentioned above is merged to 2.7.2 

maybe we can use post delete hooks to clean it up?

here's the tiller server logs from the delete:

```
[storage] 2017/12/25 08:13:05 getting release history for "elastic-search-curator-cronjob"
[tiller] 2017/12/25 08:13:05 uninstall: Deleting elastic-search-curator-cronjob
[tiller] 2017/12/25 08:13:05 executing 0 pre-delete hooks for elastic-search-curator-cronjob
[tiller] 2017/12/25 08:13:05 hooks complete for pre-delete elastic-search-curator-cronjob
[storage] 2017/12/25 08:13:05 updating release "elastic-search-curator-cronjob.v1"
[kube] 2017/12/25 08:13:05 Starting delete for "elastic-search-curator-cronjob" CronJob
[kube] 2017/12/25 08:13:05 Starting delete for "elastic-search-curator-cronjob-configmap" ConfigMap
[tiller] 2017/12/25 08:13:05 executing 0 post-delete hooks for elastic-search-curator-cronjob
[tiller] 2017/12/25 08:13:05 hooks complete for post-delete elastic-search-curator-cronjob
[tiller] 2017/12/25 08:13:05 purge requested for elastic-search-curator-cronjob
[storage] 2017/12/25 08:13:05 deleting release "elastic-search-curator-cronjob.v1"
```

**Comment by zhaytee** [comment] 2018-03-28 01:17
I'm seeing this issue with Helm 2.8.2, k8s 1.8.7. When using `kubectl delete` to delete a `CronJob` created by a Helm chart, all child `Job`s are cleaned up. When using `helm delete --purge`, the child `Job`s are left hanging around.

/remove-lifecycle stale

**Comment by davidghiurco** [comment] 2018-06-22 16:31
I can confirm this behavior as well. Except I tried 
`
helm delete $HELM_RELEASE_NAME
helm delete --purge $HELM_RELEASE_NAME
`

and jobs were not cleaned up that way either. I am using kubectl 1.10.3 and helm 2.6.1 (I know, it's an old helm version, I have no choice but to use it since our kubernetes cluster doesn't support newer versions yet)

**Comment by mkj28** [comment] 2018-08-04 00:03
quite surprised to see this issue, but yes - getting it, too
helm v2.9.1, k8s v1.9.8

**Comment by mblhaunted** [comment] 2018-09-11 17:09
surprised to see this myself. +1

**Comment by celamb4** [comment] 2018-10-30 16:16
Same behavior with 

`Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}`

**Comment by bacongobbler** [comment] 2020-05-14 20:39
closing as inactive.

**Closed by bacongobbler** 2020-05-14 20:39 UTC
Labels: bug
