### ISSUE TITLE
Problem Converting strings to int in helm 2.15

### ISSUE THREAD

**Issue by charan478** [helm/helm#6747] opened 2019-10-22 20:04 UTC
Current Setup: 
I am using minikube for local testing and if everything works well, I launch the manifests on GKE. I have to use kube version 1.14.6 in minikube as well becuase our company uses the same verison on GKE. We are trying to build kafka cluster using helm and launch our springboot application which uses Kafka on k8's.
Problem: with helm 2.14 until I upgraded yesterday everything was fine. we are able to convert configurations from value files to ints and use with until function without any problem. but once I have upgraded to 2.15 the int conversion always returns 0 and many of my loops in helm are not giving results they are expected.
For example In my helpers file I am trying to create zookeeper server list to pass while launching and I am setting that as env variable and refering that when launching zookeeper.
This is my logic to create zookeeepr string in required format 

{{- range $idx, $v := until (int .Values.servers) }}
{{- $noop := printf "%s-%d.%s.%s:%d:%d" $name $idx $svcname $namespace (int $serverPort) (int $leaderElectionPort) | append $zk.servers | set $zk "servers" -}}
{{- end }}

This worked perfectly in 2.14 but after upgrading to 2.15 I am getting empty value for serverlist variabe. When I did some digging into this issue I found that in 2.15 the .Values.servers is being rendered as 0 irrespective of actual value. This might me issue with json number unmarshalling I am not sure.

I have to use the following workaround for that

{{- range $idx, $v := until (atoi (printf "%s" .Values.servers)) }}

I am using until in multiple places in my other charts also. I am worried to restart those services as they may break due to this. When I tested kafka chart new version is not launching any persistant volume claims as I used similar logic with until. Using the workaround is not I want as that effects readability.  

Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Testing on minikube and GKE

**Comment by bacongobbler** [comment] 2019-10-22 22:54
duplicate of #6708.

**Closed by bacongobbler** 2019-10-22 22:54 UTC
