### ISSUE TITLE
Feature proposal: Allow referencing values on dependencies archive

### ISSUE THREAD

**Issue by nuno-caro-feedzai** [helm/helm#11539] opened 2022-11-14 18:03 UTC
We are defining a chart that contains several dependencies in order to orchestrate a deployment of a product containing several Kubernetes manifests.

In the umbrella chart, Helm allows us to define multiple values files that we can use to deploy to Kubernetes, but all that gets lost once we package and publish the chart. What is odd is that those alternate values files are still in the archive, but we can't reference them directly.

We can pull dependencies individually, `--untar` them, and the reference the files, but this is cumbersome and error prone.

What would be very nice would be the `--untar` swith on the `helm dependencies update` command, or even better, if we could reference a values file that is within the archive of a chart dependency directly with `-f charts/my-dependency.tgz/staging.yaml`.

Flux does exactly this https://fluxcd.io/flux/components/source/helmcharts/#values-files.

**Comment by joejulian** [comment] 2022-11-15 00:40
closing as duplicate of https://github.com/helm/helm/issues/4782

**Closed by joejulian** 2022-11-15 00:40 UTC
