### ISSUE TITLE
Checksum error seems to be back...

### ISSUE THREAD

**Issue by doctorwu** [helm/helm#10134] opened 2021-09-15 18:54 UTC
Seems to be back...

#9 0.620 Downloading https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
#9 1.467 Verifying checksum... SHA sum of /tmp/helm-installer-gxsftx/helm-v3.7.0-linux-amd64.tar.gz does not match. Aborting.
#9 1.481 Failed to install helm
#9 1.481 	For support, go to https://github.com/helm/helm

_Originally posted by @doctorwu in https://github.com/helm/helm/issues/9460#issuecomment-920292516_

**Comment by bacongobbler** [comment] 2021-09-15 18:55
duplicate of https://github.com/helm/helm/issues/10133.

**Closed by bacongobbler** 2021-09-15 18:55 UTC
