### ISSUE TITLE
Error when adding a repository

### ISSUE THREAD

**Issue by bztech1** [helm/helm#8022] opened 2020-04-29 05:45 UTC
I'm trying to add helm repository but getting the following error

```console
C:\Windows\system32>helm repo add ibm https://raw.githubusercontent.com/IBM/charts/master/repo/stable
Error: read C:\Users\dani\.helm\repository\repositories.yaml: The process cannot access the file because another process has locked a portion of the file.
```

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by hickeyma** [comment] 2020-04-29 09:04
@bztech1 This was fixed in https://github.com/helm/helm/issues/6682

What version of Helm are you using? The fix is available from Helm 2.16.0 and Helm 3.0.0. I would suggest updating to the latest [release](https://github.com/helm/helm/releases) version on Helm v2 or Helm v3.

**Comment by hickeyma** [comment] 2020-04-29 09:05
Duplicate of #6682

**Comment by hickeyma** [comment] 2020-04-29 09:07
Let me know if that fixes the issue.

**Comment by bztech1** [comment] 2020-04-29 12:58
> @bztech1 This was fixed in #6682
> 
> What version of Helm are you using? The fix is available from Helm 2.16.0 and Helm 3.0.0. I would suggest updating to the latest [release](https://github.com/helm/helm/releases) version on Helm v2 or Helm v3.

**Comment by bridgetkromhout** [comment] 2020-04-29 13:11
Hi, @bztech1 - we see your reply with the quote of @hickeyma (https://github.com/helm/helm/issues/8022#issuecomment-621187246), but unfortunately your answer did not come through - can you answer us again? Thanks.

**Comment by bztech1** [comment] 2020-04-29 13:17
the version is helm 2.15.0. I believe V3 and above not supporting teller.  I run the below command upgrade but failing.  [upgrade helm upgrade <realease_name>]
$helm upgrade helm-v2.16.0 command . Error: This command needs 2 arguments: release name, chart path

**Comment by hickeyma** [comment] 2020-04-29 13:26
The `helm upgrade` command is for upgrading a release (deployed chart) and not the Helm version.

Have a look at the instructions in https://v2.helm.sh/docs/using_helm/#installing-helm. You will need to replace the client `helm` and re-initialize Tiller. I suggest getting the latest which is [2.16.6](https://github.com/helm/helm/releases/tag/v2.16.6).

**Comment by hickeyma** [comment] 2020-04-29 13:26
Can you then show the output to `helm version`?

**Comment by bztech1** [comment] 2020-04-29 14:20
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

**Comment by bztech1** [comment] 2020-04-29 14:23
I'm able to install with that version of helm but running on issue when hit the below command 
C:\Windows\system32>helm install ibm/ibm-ace-server-dev --name ace-dev --set license=accept --set persistence.enabled=true
Error: validation failed: unable to recognize "": no matches for kind "Route" in version "route.openshift.io/v1"

C:\Windows\system32>helm search ibm-ace
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
ibm/ibm-ace-dashboard-dev       3.1.0           11.0.0.8-r1     IBM App Connect Enterprise dashboard
ibm/ibm-ace-server-dev          3.1.0           11.0.0.8-r1     This helm chart is used by the IBM App Connect Dashboard ...

**Comment by bacongobbler** [comment] 2020-04-29 14:29
It looks like the original issue has been resolved.

The issues you are experiencing now appear to be related to the chart you are deploying. Please make sure to follow the instructions and prerequisites as described in their documentation: https://github.com/IBM/charts/blob/master/stable/ibm-ace-server-dev/README.md#prerequisites

If you have any further issues, please file against the IBM charts repository. We cannot help you with chart-specific issues.

Closing.

**Closed by bacongobbler** 2020-04-29 14:29 UTC

**Comment by hickeyma** [comment] 2020-04-29 15:07
@bztech1 It is good that you have the latest version of Helm v2 now and is installed correctly. Also, that the `repo add` issue if fixed with this version.

Re the issue installing/deploying chart `ibm-ace-server-dev`, it looks like it is missing some value to be set during install. Try looking at the chart REAMDE for more information or raising an issue with [IBM Cloud Charts Helm Repository](https://github.com/IBM/charts).

Hope this helps.

**Comment by bztech1** [comment] 2020-04-29 15:51
@hickeyma, thank you. thank you all for support.
