### ISSUE TITLE
Persistent Volumes left in Released state after failed atomic rollback

### ISSUE THREAD

**Issue by csuzw** [helm/helm#7644] opened 2020-02-20 13:37 UTC
We are deploying our charts with `helm update --install --atomic`.  We have existing persistent volumes in the kubernetes cluster we are deploying too and the helm chart defines persistent volume claims on them.  When we are deploying for the first time (ie there have been no prior successful deployments) and the deployment fails and so rolls back, the persistent volumes are left in a Released state and subsequent attempts then fail due to the PVCs not being able to bind any more.  The only solution I've found to this is to delete the persistent volumes and recreate them.  If at least 1 successful deployment has been made, then failed deployments roll back fine and the PVs and PVCs are left in a valid state.  Is this a bug or am I doing something wrong?

Output of `helm version`: 3.0.0 (but we've encountered this with several 3.0.x releases)
Output of `kubectl version`: 1.15.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by bacongobbler** [comment] 2020-02-20 17:34
Yes, this is intended behaviour.

Closing as a duplicate of https://github.com/helm/helm/issues/5156

**Closed by bacongobbler** 2020-02-20 17:34 UTC
Labels: question/support

**Comment by csuzw** [comment] 2020-02-20 18:41
It's not clear that this is a duplicate of #5156.  At least the problem being described here is not explicitly described in that issue.  The point of the atomic flag should be that you return to the previous state on failure but this is failing to do that.  I can't see how or why this could be intended behaviour?

**Comment by bacongobbler** [comment] 2020-02-20 18:44
Persistent volumes are ignored during any delete operation, including `--atomic`. #5156 aims to address that by removing PVCs during a delete operation, like a `helm rollback` (which is how the `--atomic` flag works in principle).
