### ISSUE TITLE
[helm3] Support OCI images in `helm install`

### ISSUE THREAD

**Issue by meysholdt** [helm/helm#6990] opened 2019-11-17 09:26 UTC
It would be awesome if I could just run 
```
$ helm3 install --generate-name localhost:5000/simple-pod:0.0.1
```
to install a chart via OCI image.

Currently, this gives me the error on `helm 3.0.0`:
```
Error: failed to download "localhost:5000/simple-pod:0.0.1" (hint: running `helm repo update` may help)
```

My assumption is that `$ helm3 install --generate-name localhost:5000/simple-pod:0.0.1` would check if `localhost:5000/simple-pod:0.0.1` is in `helm chart list`, and if not, do a `helm chart pull`. Then, it would continue with `helm install` as usual. 

This would be equivalent to `docker run <myimage>`, which also pulls images when they can't be found locally.

**Comment by karuppiah7890** [comment] 2019-11-17 09:36
Duplicate of https://github.com/helm/helm/issues/6982

**Closed** 2019-11-17 16:01 UTC
