### ISSUE TITLE
helm api: release.Chart in return value of action.Get.Run is missing dependencies

### ISSUE THREAD

**Issue by pmahoney** [helm/helm#8421] opened 2020-07-08 21:11 UTC
I'm using `helm.sh/helm/v3 v3.2.4` and was hoping to write a tool (to assist with some tests in our CI environment) that could get the chart from a deployed release and then upgrade that release using some new values. What I found however is that the returned release.Chart lacks dependencies, and resources created by those dependencies end up getting deleted when I perform an upgrade.

The release was initially deployed using helm (commandline tool) 3.2.4 and is using the default 'secret' driver.

(error handling deleted for clarity...)

``` golang
package main

import (
	"log"

	"helm.sh/helm/v3/pkg/action"
)

func Upgrade(config *action.Configuration, releaseName string, values map[string]interface{}) {
	get := action.NewGet(config)
	release, _ := get.Run(releaseName)

	log.Printf("this prints zero: %d", len(release.Chart.Dependencies()))

	upgrade := action.NewUpgrade(config)
	upgrade.ResetValues = false
	upgrade.ReuseValues = true

	upgrade.Run(release.Name, release.Chart, values)

	// resources owned by dependencies got deleted
}
```

Is there a way to accomplish this without needing a local copy of the chart (and its dependencies)?

**Comment by hickeyma** [comment] 2020-07-09 09:34
@pmahoney Does `release.Chart.Metadata. Dependencies` return the dependencies?

**Comment by pmahoney** [comment] 2020-07-09 21:31
@hickeyma Yes, it has two dependencies that were enabled, and is missing one that is in `requirements.yaml` but happens to be disabled in this deployment.

I note that manually extracting the JSON from the kubernetes Secret shows all three dependencies, with two marked "enabled" as expected. When I say they are in the JSON, it's only the name/version/repository metadata. The dependent chart's templates are not there.

**Comment by bacongobbler** [comment] 2020-07-21 13:55
duplicate of https://github.com/helm/helm/issues/8480.

**Closed by bacongobbler** 2020-07-21 13:55 UTC
Labels: question/support
