### ISSUE TITLE
Docs - BlobNotFound

### ISSUE THREAD

**Issue by kvolkovich-sc** [helm/helm#4698] opened 2018-09-26 14:30 UTC
https://docs.helm.sh/chart_template_guide/developing_charts

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:0d2de1a1-101e-011b-0aa5-558e74000000 Time:2018-09-26T14:30:01.1295701Z
</Message>
</Error>
```

**Comment by jascott1** [comment] 2018-09-27 06:53
Hi @kvolkovich-sc 

Thanks for reporting this!

**Comment by hickeyma** [comment] 2018-10-02 14:03
Following some investigation into this issue, it would seem to be an issue with the docs LHS menu selection.

It can be reproduced as follows:
1.  Goto the Helm docs: https://docs.helm.sh/
2.  Click on "Developing Templates" from the menu on the LHS
3.  Click the "Developing Templates" menu again to open the sub-menus for "Developing Templates" and then click on a sub-menu, "Built-in Objects" for example
4.  Then right click  on the menu item "Charts" and select to open in a new tab or window
5. The error as specified above in https://github.com/helm/helm/issues/4698#issue-364059702 should be shown

The issue is because the URL for the "Charts" doc in this instance is incorrect. It is "https://docs.helm.sh/chart_template_guide/developing_charts" instead of "https://docs.helm.sh/developing_charts". This is because the base URL is derived from the current menu selected, instead of being based off docs home.

This can be reproduced for other menu selection and right clicking on another doc.

**Comment by hickeyma** [comment] 2018-10-02 14:06
I am willing to looking into fixing this if someone can direct me how the menus are rendered.

**Comment by bacongobbler** [comment] 2018-10-18 22:08
https://github.com/helm/helm-www

**Comment by hickeyma** [comment] 2018-11-28 17:50
The menus that are affected are:
- Using Helm
- Helm Commands
- Charts
- Developing Templates

**Comment by hickeyma** [comment] 2018-11-28 17:51
PR now open: https://github.com/helm/helm-www/pull/160

**Comment by bacongobbler** [comment] 2019-01-10 16:35
can confirm this has been fixed. Closing

**Closed by bacongobbler** 2019-01-10 16:35 UTC
Labels: bug, docs
