### ISSUE TITLE
The helm and tiller binaries provided with Helm v.2.11.0 are incompatible.

### ISSUE THREAD

**Issue by somashekhar** [helm/helm#4730] opened 2018-10-03 10:31 UTC
Hi team,

The helm binary version is 2.11.0 where as tiller binary version is 2.10.0 in the v.2.11.0 Helm release.
https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz 

Due to this we faced version incompatibility issue.
Can you please look into the issue.

ubuntu@kube-master:~$ helm ls
Error: incompatible versions client[v2.11.0] server[v2.10.0]

Thanks
Soma

**Comment by bacongobbler** [comment] 2018-10-03 15:27
Whoops. I'll take a look into this today. Thanks for the report!

**Comment by hickeyma** [comment] 2018-10-03 15:32
I have used downloaded the latest binary from here: https://github.com/helm/helm/releases/tag/v2.11.0

I did an upgrade on tiller and all is ok:
```helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}```

How did you install/upgrade tiller?

**Comment by bacongobbler** [comment] 2018-10-03 16:01
Seems fine to me when running helm and tiller from the release binaries.

```
PS C:\Users\me\Downloads> .\tiller.exe version
[main] 2018/10/03 08:57:00 Starting Tiller v2.11.0 (tls=false)
[main] 2018/10/03 08:57:00 GRPC listening on :44134
[main] 2018/10/03 08:57:00 Probes listening on :44135
[main] 2018/10/03 08:57:00 Storage driver is ConfigMap
[main] 2018/10/03 08:57:00 Max history per release is 0
```

```
PS C:\Users\me\Downloads> $env:HELM_HOST = ":44134"
PS C:\Users\me\Downloads> .\helm.exe version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Closing as not a bug.

**Closed by bacongobbler** 2018-10-03 16:01 UTC
Labels: bug, unconfirmed

**Comment by hickeyma** [comment] 2018-10-03 16:07
fyi, I used `helm-v2.11.0-linux-amd64.tar.gz`.

**Comment by somashekhar** [comment] 2018-10-03 16:56
Below are the steps which landed me into the version incompatible issue,

Downloaded the helm and tiller versions from,
https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz.

Running helm on k8s master node and tiller as a pod in the cluster.
(Created a docker image using tiller binary).

An upgrade on tiller was not done.

**Comment by bacongobbler** [comment] 2018-10-03 17:02
Did you run `helm init --upgrade` after upgrading?

**Comment by somashekhar** [comment] 2018-10-03 17:34
As of now I have switched to v.2.10 binaries and got it working.
Will try an upgrade and test once the k8s cluster is free. 

Our use case is:
1. We download the binaries of the helm and keep in our local repo.
2. Use these binaries from local repo and install in our k8s cluster.
3. The k8s cluster has no external internet access.

So we would face this issue again if we have to use 2.11 version of helm.
Putting tiller binaries of v.2.11 along with helm v.2.11 would help.
