### ISSUE TITLE
helm doesn't remove CRD that created with 'crd-install' hook after delete the chart

### ISSUE THREAD

**Issue by morvencao** [helm/helm#4489] opened 2018-08-19 08:46 UTC
Helm 2.10 introduced a new hook `crd-install` as described here https://docs.helm.sh/developing_charts/#defining-a-crd-with-the-crd-install-hook , and this can make sure all CRDs can be installed first before install other resources and make chart CRD management more easy.

However, there is an issue that the CRDs created with 'crd-install' hook will not be removed after the chart is deleted. 

Not sure if `"helm.sh/hook-delete-policy": "before-hook-creation"` will help to delete these CRDs that created in previous release.

**Comment by bacongobbler** [comment] 2018-08-19 15:26
Yeah, we have this weird case where once you have created a CRD definition, other things on a cluster can become dependent on it -- notably, and CRD instances. So once we've created a CRD, it is risky to delete it. So we implemented CRD installation as a hook, which makes the CRD unmanaged (e.g. Helm doesn't delete it by default)

So if you want to delete it, you need to explicitly tell the chart to delete it:
https://github.com/helm/helm/blob/master/docs/charts_hooks.md#hook-resources-are-not-managed-with-corresponding-releases

CRD deletion is slow, so using a before-hook-creation might not be fast enough though. In general, for things like CRDs it's better to delete in post-delete if possible.

closing as a duplicate of #4440 :)

**Closed by bacongobbler** 2018-08-19 15:26 UTC
