### ISSUE TITLE
Why error message only show in debug ?

### ISSUE THREAD

**Issue by faisalburhanudin** [helm/helm#7218] opened 2019-12-12 13:48 UTC
so today I tried the helmet for the first time, when I ran it didn't output at all, after I checked the code, the output error only came out in debug.

May I know why the error message is only available in debug?

```go
if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), debug); err != nil {
		debug("%+v", err)
		os.Exit(1)
	}

	if err := cmd.Execute(); err != nil {
		debug("%+v", err)
		switch e := err.(type) {
		case pluginError:
			os.Exit(e.code)
		default:
			os.Exit(1)
		}
	}
```

https://github.com/helm/helm/blob/3d04c6c5ce5d019e3a1f58354ab9f67453a83f8a/cmd/helm/helm.go

**Comment by hickeyma** [comment] 2019-12-12 14:05
@faisalburhanudin Can you provide more details what you ran? Did you use the CLI or the SDK? What was the error you got? What version of Helm?

Some more details is helpful in getting an idea of your issue.

FYI, there is PR #6909 opened about this.

**Comment by faisalburhanudin** [comment] 2019-12-12 18:44
So I using minikube without vm

`sudo minikube start` (minikube need root for run without vm)

Then I run helm cli using command such as:

```
$ helm --help
$
```
no output 

than check helm code and run debugger.

![image](https://user-images.githubusercontent.com/5812819/70739008-7a01a380-1d48-11ea-90db-3fdbca190d79.png)

there is error permission, but no error message in console.

so I check debug code

```go
func debug(format string, v ...interface{}) {
	if settings.Debug {
		format = fmt.Sprintf("[debug] %s\n", format)
		log.Output(2, fmt.Sprintf(format, v...))
	}
}
```

and than check `cli.New()` and i found this.

https://github.com/helm/helm/blob/09ebcde05c5331743713af16777768de854ac972/pkg/cli/environment.go#L71

I think error message should show both in debug mode or note

**Comment by marckhouzam** [comment] 2019-12-12 19:18
Duplicate of #6863

**Closed by marckhouzam** 2019-12-12 19:18 UTC
Labels: question/support

**Comment by marckhouzam** [comment] 2019-12-12 19:19
You are right @faisalburhanudin  that the error message should be shown all the time. There is a PR that will soon fix that I hope.

**Comment by marckhouzam** [comment] 2019-12-12 19:22
Sorry @hickeyma, I missed that you had already identified a possible PR for this.
