### ISSUE TITLE
Add option to force ownership of objects

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#10097] opened 2021-09-03 23:03 UTC
It would be nice to add an option to force override to avoid the `rendered manifests contain a resource that already exists` issue when we legitimately want to override resources.

Code: https://github.com/helm/helm/blob/accf82ba1c5fe32a0004f6ec7fd021b77fddf51f/pkg/action/install.go#L292

The alternative is to recommend users something like:
```
KINDS=(service deployment)
RELEASE=my-release
NAMESPACE=my-namespace
for KIND in "${KINDS[@]}"; do
    kubectl --namespace $NAMESPACE --overwrite=true annotate $KIND $RELEASE meta.helm.sh/release-name=$RELEASE
    kubectl --namespace $NAMESPACE --overwrite=true annotate $KIND $RELEASE meta.helm.sh/release-namespace=$NAMESPACE
    kubectl --namespace $NAMESPACE --overwrite=true label $KIND $RELEASE app.kubernetes.io/managed-by=Helm
done
```

But this isn't very user friendly, and in more complex charts can grow unwieldy

**Comment by bacongobbler** [comment] 2021-11-26 17:52
duplicate of #2730.

**Closed by bacongobbler** 2021-11-26 17:52 UTC
Labels: feature
