### ISSUE TITLE
Chart Repository must be added to the Release

### ISSUE THREAD

**Issue by arash-bizcover** [helm/helm#10053] opened 2021-08-24 07:08 UTC
How can I get the chart repository URL from the existing installed release?? 
All I get is chart name and release name:
![image](https://user-images.githubusercontent.com/62287461/130572247-5acbcc3b-3a90-4a2e-94e5-1916163d2e9e.png)

What about the repository of this?

So If I install 10 different 3rd party repositories on my local pc and install helm releases from them. How can someone else later understand/find where the hell is the repository of the currently running helm charts in a cluster to edit ??

**Comment by hickeyma** [comment] 2021-08-25 07:49
@arash-bizcover Thank you for raising this. To try and understand this better, what is the use case for wanting to know what repository that a chart comes from?

**Comment by bacongobbler** [comment] 2021-08-25 13:28
This is not currently possible. See https://github.com/helm/helm/issues/4256 for more details.

closing as a duplicate of #4256.

**Closed by bacongobbler** 2021-08-25 13:28 UTC
Labels: question/support
