### ISSUE TITLE
helm install successfully while resources already exists

### ISSUE THREAD

**Issue by jianzzz** [helm/helm#5878] opened 2019-06-12 11:19 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

Assume I have charts names chart1 and chart2.
Chart1 includes a services named test.
Chart2 includes a services named test.
Chart1 has already been install in namespace, release-name is testC1.
Now we try to install chart2, release-name is testC2.
At first, it outputs "Error: release test failed: services "test" already exists"
We delete it: helm del --purge testC2
Try again, and it is successful!!

This is amazing!!!! 
We can't stand this result. 
It will also affect testC1's reousrces!!!

Why this happens and how to fix?

**Comment by jianzzz** [comment] 2019-06-13 12:23
anyone?

**Comment by bacongobbler** [comment] 2019-06-13 14:29
looks like a duplicate of #3319.

**Closed** 2019-06-14 14:17 UTC
