### ISSUE TITLE
RollingUpdate seems to be ignored

### ISSUE THREAD

**Issue by spaivaras** [helm/helm#10088] opened 2021-09-01 11:06 UTC
Helm version 3.6.3
Kubernetes client: "v1.22.1"
Kubernetes server:  "v1.21.2-eks-0389ca3"

Our custom charts deployment template has a typical strategy for rolling update with surge 25% and unavailable 25%
But whenever we do helm upgrade all pods except 1 are immediately terminated and new ones created. Basically no matter what size the current deployment is, only 1 pod is left running while deployment starts.

Doing rollout restart on the same deployment in Kubernetes works as excepted only 25% of pods initially are terminated.

We did a big jump from helm 2.14.1 to 3.6.3 so can't really provide the exact version this behavior started. But at least with helm 2, Kubernetes deployment strategy was respected

Could this maybe be related to that replica count in deployment is set to 1, but we use HPA manifest with that deployment as well?

UPDATE:
Yes it seems deployment manifest "replicas:" field have an effect on helm deployment. Setting it to example the same value as HPA minReplicas does rolling update a bit better. But to be honest, not sure if this is desirable. What if HPA scales out to max, this would terminate too much of the initial pods. Furthermore, it seems helm2 was not taking replica count into account

**Comment by mattfarina** [comment] 2021-09-01 12:59
You may know some of this but I want to over share just to be sure. Helm generates Kubernetes manifests to upload to Kubernetes. Under the hood, Helm uses the same packages that Kubernetes and kubectl use. We import them and use them. Helm isn't doing anything special to the manifests that get uploaded.

One thing did change that could be a possibility. Helm v3 moved to a [3-way strategic merge patch](https://helm.sh/docs/faq/changes_since_helm2/#improved-upgrade-strategy-3-way-strategic-merge-patches) for updates to core Kubernetes resources. This isn't the case with CRDs/CRs as this functionality is part of a Kubernetes package and wasn't available when Helm v3 launched to use it on CRDs/CRs.

Without seeing your chart and the rendered values currently in your cluster it'll be difficult for me to pinpoint what's going on. I am happy to try to point you at things that might be the cause. The merge patch change is my first thought.

**Comment by spaivaras** [comment] 2021-09-01 13:20
Yes, I totally understand that helm by itself doesn't create/destroy pods, that's why it was strange why changing version changed the way "we have been used to"

I can attach my generated manifests (containers removed, checksums obfuscated), but it's just a basic deployment and HPA manifests:
```
# Source: php-microservicev2/templates/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-software-api
  labels:
    app-type: my-software-api
    app.kubernetes.io/name: my-software
    helm.sh/chart: php-microservicev2-1.0.0
    app.kubernetes.io/instance: my-software
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      # WARNING: These are immutable. Apps will break on change
      app-type: my-software-api
      app.kubernetes.io/name: my-software
      app.kubernetes.io/instance: my-software
  template:
    metadata:
      annotations:
        # roll deployment on ConfigMap update
        checksum/config: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        checksum/secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: '/metrics'
      labels:
        # WARNING: These are immutable. Apps will break on change
        app-type: my-software-api
        app.kubernetes.io/name: my-software
        app.kubernetes.io/instance: my-software
        released-at: 0
    spec:
      priorityClassName: service-high-priority
      terminationGracePeriodSeconds: 60
      volumes:
        - name: nginx-config-volume
          configMap:
            name: my-software-api-nginx-config
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: timeout
            value: "2"
          - name: attempts
            value: "4"
          - name: single-request-reopen
      containers:
        ...
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - my-software-api
                topologyKey: kubernetes.io/hostname
              weight: 50


# Source: php-microservicev2/templates/api-hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-software-api
  labels:
    app.kubernetes.io/name: my-software
    helm.sh/chart: php-microservicev2-1.0.0
    app.kubernetes.io/instance: my-software
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-software-api
  minReplicas: 6
  maxReplicas: 12
  targetCPUUtilizationPercentage: 75
```

Thank you, for hinting 3-way merging, will check that up. For now, I know that I can at least increase deployment replicas, and more or less I get the same old behavior.

**Comment by mattfarina** [comment] 2021-09-01 13:31
I have an idea what might be affecting this. The [Kubernetes docs on rolling updates and HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#autoscaling-during-rolling-update) were of help.

The deployment has `replicas` set to 1. When you modify the Deployment a new ReplicaSet is created based on the Deployment. I wonder if it has a default value of 1 until the HPA catches the change and modifies it back. The 3-way merge could be setting that when an update happens.

**Comment by bacongobbler** [comment] 2021-09-07 11:49
Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Closed by bacongobbler** 2021-09-07 11:49 UTC
Labels: question/support
