### ISSUE TITLE
how to apply  --insecure-skip-tls-verify  flag to helm, Getting cluster unreachable error if i use  --insecure-skip-tls-verify flag it is working in kubernetes but how can i achieve this with the helm

### ISSUE THREAD

**Issue by vishnu123sai** [helm/helm#8729] opened 2020-09-14 15:16 UTC
how to apply  --insecure-skip-tls-verify  flag to helm, Getting cluster unreachable error if i use  --insecure-skip-tls-verify flag it is working in kubernetes but how can i achieve this with the helm

**Comment by bacongobbler** [comment] 2020-09-14 15:36
`--insecure-skip-tls-verify` applies to requests against a Helm chart repository. It does not apply to the Kubernetes client. Please see https://github.com/helm/helm/pull/8622.

Closing as a duplicate of https://github.com/helm/helm/issues/8487.

**Closed by bacongobbler** 2020-09-14 15:36 UTC

**Comment by bekker** [comment] 2022-10-14 05:30
For those who seeking the exact parameter name: `--kube-insecure-skip-tls-verify`
It works for Helm 3.10.0

ex)
```
helm install --kube-insecure-skip-tls-verify <args>
```
