### ISSUE TITLE
When running helm client 2.10.0 with tiller 2.11.0-rc.4, releases are deleted

### ISSUE THREAD

**Issue by frankh** [helm/helm#4681] opened 2018-09-21 16:39 UTC
I upgraded my tiller server to v2.11.0-rc.4 with helm init --upgrade --force-upgrade --tiller-image=gcr.io/kubernetes-helm/tiller:v2.11.0-rc.4

I then attempted to update my release using helm client v2.10.0 and got an error "incompatible helm client for tiller version ..."

This would be fine, except tiller then decided to DELETE my release

My release was then left in an inconsistent state where it was stuck "DELETING" but was only half deleted.

After spending ages trying to fix it, the only solution was to manually delete all .vXX configmaps, manually cleanup every single resource from the release, and deploy again (using helm and tiller v2.10.0)

Sorry for incomplete bug report/lack of logs, but I've been busy trying to get stuff back online

**Comment by bacongobbler** [comment] 2018-09-21 16:55
Hey @frankh, can you try with a sample chart to try and reproduce the issue? I haven't heard of this behaviour occurring before. Some steps to reproduce would be really helpful. Thanks.

**Comment by frankh** [comment] 2018-09-21 17:05
Hi @bacongobbler, I'll try to add more information later, currently my theory is that it caused by doing a `--force` deploy

**Comment by frankh** [comment] 2018-09-21 17:48
If my hunch is correct, a single pod template should be able to reproduce the behaviour by doing a force upgrade with helm 2.10 against tiller 2.11

I imagine the stuck deleting was caused by me panic downgrading tiller mid-delete, and the old tiller did not/could not continue the deletion

I'll attempt to reproduce on Monday

**Comment by bacongobbler** [comment] 2018-09-25 17:00
Okay, so based on what's been dumped here, here's my steps to try and reproduce:

On v2.10.0:

```
$ helm init
$ helm install stable/wordpress
```

Now I have a release called `happy-racoon`:

```
><> helm list
NAME         	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
happy-raccoon	1       	Tue Sep 25 09:55:17 2018	DEPLOYED	wordpress-3.0.1	4.9.8      	default
```

Now the only way to trigger the "incompatible helm client for tiller version" is when I only update the client without updating tiller, so I went and did that:

```
><> ./linux-amd64/helm version
Client: &version.Version{SemVer:"v2.11.0-rc.4", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
><> ./linux-amd64/helm list
Error: incompatible versions client[v2.11.0-rc.4] server[v2.10.0]
```

So, here's me trying to reproduce the error as described in this ticket:

```
><> ./linux-amd64/helm upgrade --force happy-racoon stable/wordpress
Error: UPGRADE FAILED: incompatible versions client[v2.11.0-rc.4] server[v2.10.0]
><> ./linux-amd64/helm list
Error: incompatible versions client[v2.11.0-rc.4] server[v2.10.0]
><> helm list
NAME         	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
happy-raccoon	1       	Tue Sep 25 09:55:17 2018	DEPLOYED	wordpress-3.0.1	4.9.8      	default
```

It doesn't look like the release ever got past the version check, so no upgrade was ever performed.

I'm going to close this as there's not much to go on in this ticket and it looks like there's nothing actionable here, but please go ahead and re-open if you do find an actual issue. Thanks.

**Closed by bacongobbler** 2018-09-25 17:00 UTC
Labels: question/support

**Comment by frankh** [comment] 2018-09-26 09:56
I also was unable to reproduce :/

I'm ok with it being closed - will reopen if i find a cause in the future
