### ISSUE TITLE
Helm Upgrade fails: watch closed before UntilWithoutRetry timeout

### ISSUE THREAD

**Issue by ygnr** [helm/helm#6160] opened 2019-08-04 11:27 UTC
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  `AKS`

Helm upgrade fails with the following error on `post-install` job. It is a long-running job (around 50 min). Everything works well if the job finishes within 30 min. I have set timeout flag to 2 hours though.

```
##[error]Error: watch closed before UntilWithoutRetry timeout
```

**Comment by bacongobbler** [comment] 2019-08-07 06:52
dupe of #2918?

**Closed** 2019-08-14 20:47 UTC
Labels: question/support

**Comment by manisha-tanwar** [comment] 2020-06-23 10:24
I was facing same error 

> "Error: watch closed before UntilWithoutRetry timeout" 

with helm version `"2.12.0"`, 
upgrading it to `"2.16.x"` helped me to fix it!
