### ISSUE TITLE
Helm v2: lint silently ignores non existing packaged charts

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#6537] opened 2019-09-30 18:40 UTC
Related issue: #6428 

```
$ helm lint blah.tgz
==> Skipping blah.tgz
open blah.tgz: no such file or directory

0 chart(s) linted, no failures
```

And it also doesn't throw errors for corrupted charts

```
$ touch blah.tgz

$ helm lint blah.tgz
==> Skipping blah.tgz
EOF

0 chart(s) linted, no failures
```

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**Comment by thomastaylor312** [comment] 2019-09-30 18:42
I confirmed this is happening tarballs that end in `.tgz` but it does not occur for `.tar.gz`

**Comment by karuppiah7890** [comment] 2019-09-30 18:46
We never consider `.tar.gz` as tar ball actually. We consider them as simple directories.

```
$ helm create blah
Creating blah

$ helm package blah
Successfully packaged chart and saved it to: /Users/karuppiahoss/blah-0.1.0.tgz
 
$ helm lint blah-0.1.0.tgz
==> Linting blah-0.1.0.tgz
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures

$ mv blah-0.1.0.tgz blah-0.1.0.tar.gz

$ helm lint blah-0.1.0.tar.gz
==> Skipping blah-0.1.0.tar.gz
No chart found for linting (missing Chart.yaml)

Error: 0 chart(s) linted, 1 chart(s) failed
```

Check this #6535

**Comment by thomastaylor312** [comment] 2019-09-30 18:55
Yeah, I actually just discovered that myself looking in Helm 3 code. Just checking if that is supposed to be the case

**Comment by karuppiah7890** [comment] 2019-09-30 19:01
I don't think that's supposed to be the case. The issue #6535 has been marked as a feature now

**Comment by bacongobbler** [comment] 2020-07-09 17:35
Gentle reminder that the support window for bugfixes closes in a month. If nobody works on this, we'll have to close this out and consider this as Helm 2's intended behaviour.

**Comment by jeff-knurek** [comment] 2020-07-24 10:08
I think this already has been fixed... _(It looks like when #6754 was merged it didn't mark this issue as closed??)_ 

`helm version --client`
```
Client: &version.Version{SemVer:"v2.16.7", GitCommit:"5f2584fd3d35552c4af26036f0c464191287986b", GitTreeState:"clean"}
```
```
$ touch blah.tgz

$ helm lint blah.tgz 
==> Skipping blah.tgz
unable to extract tar ball: EOF

Error: 0 chart(s) linted, 1 chart(s) failed
```

**Closed** 2020-07-24 13:19 UTC
Labels: bug, v2.x
