### ISSUE TITLE
helm uninstall with --keep-history then upgrade --install results in UPGRADE FAILED "chartname" has no deployed releases

### ISSUE THREAD

**Issue by leblancmeneses** [helm/helm#11553] opened 2022-11-17 22:54 UTC
Output of `helm version`:
```
Version:"v3.10.2"
GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58"
GitTreeState:"clean"
GoVersion:"go1.19.3"
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

Context:

I'm creating a dashboard where I want to preserve history for a helm chart.

This would allow me to know when a chart was first installed (after potential uninstalls) using the helm history command.

Reproduce Steps:

```
# initial install
helm -n xyz upgrade --install devactions devactions
# uninstall
helm -n xyz uninstall devactions --keep-history
# install again
helm -n xyz upgrade --install devactions devactions
```

> Error: UPGRADE FAILED: "devactions" has no deployed releases

I can only reinstall if I drop the instance without `--keep-history`.

**Comment by yxxhero** [comment] 2022-11-18 05:11
@leblancmeneses show the debug output by adding --debug flag.

**Comment by yxxhero** [comment] 2022-11-18 05:46
@leblancmeneses I can reproduce this issue. I can't ensure if it is a bug. @joejulian WDYT?

**Comment by yxxhero** [comment] 2022-11-18 05:49
when run `helm -n xyz uninstall devactions --keep-history`, the history release labels is:

```
    modifiedAt: "1668749088"
    name: devactions
    owner: helm
    status: uninstalled
```

but for upgrade, it require:

```
    modifiedAt: "1668749088"
    name: devactions
    owner: helm
    status: deployed
```

**Comment by leblancmeneses** [comment] 2022-11-18 16:50
I used upgrade or install ```upgrade --install```  it should, ?, have been picked up by the install flag.   

```
history.go:56: [debug] getting history for release devactions
upgrade.go:142: [debug] preparing upgrade for devactions
Error: UPGRADE FAILED: "devactions" has no deployed releases
helm.go:84: [debug] "devactions" has no deployed releases
UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:201
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_arm64.s:1172
```

**Comment by joejulian** [comment] 2022-11-22 03:22
Yeah, looks like a bug to me.

**Comment by ColinDabritzQ5id** [comment] 2023-02-08 04:30
Ran into this on 3.11.0 today, is something blocking the fix PR being merged?

**Comment by joejulian** [comment] 2023-02-08 21:04
Yes, it needs reviews from a core maintainer.

**Comment by rsalinas** [comment] 2023-06-23 08:29
I just ran into this bug too. 

It's strange because after a `helm uninstall --keep-history`, the package will not appear in a `helm list` run, but it will appear indeed if `--output=yaml` is specified. 

Please give some priority to the issue. Thanks a lot.

**Comment by slzwgoosen** [comment] 2023-10-19 09:34
This is a blocker for a workflow I need to implement. Any chance a core maintainer can please spare some time to review the PR? It would be appreciated.

**Comment by jacobkrol** [comment] 2023-12-07 17:43
I'm on helm v3.10.2 and had the same error. I found this work-around:

* run `helm history <repo>`
* rollback to latest release before uninstallation
* upgrade to new release

```
$ helm upgrade --install myrepo ./
Error: UPGRADE FAILED: "pulsedev" has no deployed releases

$ helm install myrepo ./
Error: INSTALLATION FAILED: cannot re-use a name that is still in use

$ helm history myrepo
...
149   [DATE]  superseded   myrepo-0.1.0  1.0.0    upgrade to foo
150   [DATE]  uninstalled  myrepo-0.2.0   1.0.0    Uninstallation complete

$ helm rollback myrepo 149
Rollback was a success! Happy Helming!

$ helm upgrade --install myrepo ./
<output of NOTES.txt>

$ helm history myrepo
...
149   [DATE]  superseded   myrepo-0.1.0  1.0.0    upgrade to foo
150   [DATE]  uninstalled  myrepo-0.2.0  1.0.0    Uninstallation complete
151   [DATE]  superseded   myrepo-0.1.0  1.0.0    Rollback to 149
152   [DATE]  deployed     myrepo-0.2.0  1.0.0    upgrade to v0.2.0
```

**Comment by dayeguilaiye** [comment] 2024-01-24 02:57
The `helm uninstall --keep-history` is almost unusable because this issue: when you execute `helm uninstall --keep-history`,  you cannot do upgrade or install anymore, unless you execute `helm uninstall` without `--keep-history` again. But after do this, you can never do `helm rollback` because the history is gone.

This is important to someone who would like to do a rollback after uninstall(keep-history) . Any chance a core maintainer can please spare some time to review the PR? It would be appreciated.

**Closed** 2024-04-10 18:17 UTC
Labels: in progress, bug
