### ISSUE TITLE
Installing helm 3 on a circleci machine, the executable exits with a return code 1

### ISSUE THREAD

**Issue by foux** [helm/helm#7020] opened 2019-11-19 14:54 UTC
When installing helm 3 on a CircleCI machine or docker image, the helm executable will only returns an exit code of 1 with no output, whatever what the arguments are

Output of `helm version`: nothing. Only a return code of 1. But the installed version is 3.0.0

Output of `kubectl version`: 1.6.3, but shouldn't be relevant as no contact with the cluster is made

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  baremetal, but shouldn't be relevant as no contact with the cluster is made

**Comment by karuppiah7890** [comment] 2019-11-19 15:46
Could you give more details regarding the installation? How it was installed and any details you can give. As with the above information isn't enough to debug further 😅

**Comment by foux** [comment] 2019-11-19 19:55
Hi @karuppiah7890 
Sorry for the lack of information.
Helm was installed with the script `curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash`
I reproduced only on CircleCI VMs. Not reproduced on any of my local machines... so I'm really at a loss here ;)

**Comment by bacongobbler** [comment] 2019-11-19 20:12
Is the repository open source? Perhaps we can look into the failed builds to gather more information.

**Comment by foux** [comment] 2019-11-19 20:18
Unfortunately it isn't :/
Here is the command executed : 
```
#!/bin/bash -eo pipefail
if which helm > /dev/null; then
  echo "helm is already installed"
  exit 0
fi
curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
helm version
```

And the result : 
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  6617  100  6617    0     0  37705      0 --:--:-- --:--:-- --:--:-- 37596
Downloading https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm
Exited with code 1
```
The `Exited with code 1` comes from the `helm version` line.

And here is the description of the job : 
```
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
        name: Setup environment
        command: |
          echo 'export HELMVALUES=HELMVALUES_$CIRCLE_BRANCH' >> $BASH_ENV
    - run:
        command: |
          if [[ v1.16.3 == "latest" ]]; then
            # get latest kubectl release
            KUBECTL_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
          else
            KUBECTL_VERSION=v1.16.3
          fi

          PLATFORM="linux"
          if [ -n "$(uname | grep "Darwin")" ]; then
            PLATFORM="darwin"
          fi

          # download kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/$PLATFORM/amd64/kubectl

          [ -w /usr/local/bin ] && SUDO="" || SUDO=sudo

          $SUDO chmod +x ./kubectl

          $SUDO mv ./kubectl /usr/local/bin
        name: Install kubectl
    - run:
        command: |
          if [ -n "${KUBECONFIG}" ]; then
            mkdir -p $HOME/.kube
            echo -n "${KUBECONFIG}" | base64 --decode > $HOME/.kube/config
          fi
        name: Install kubeconfig
    - run:
        command: |
          if which helm > /dev/null; then
            echo "helm is already installed"
            exit 0
          fi
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version
```
Doing the same on another type of machine, or a docker image, produces the same results.

**Comment by foux** [comment] 2019-11-19 20:21
Just FYI, the same works perfectly with Helm 2

**Comment by khos2ow** [comment] 2019-11-26 16:25
I wanted to point out I have the same issue on my laptop too (Ubuntu 19.04), and I actually went ahead and checked out the repo and built the HEAD and the same behavior (`exit 1`) happened there too.

And just to validate I did `docker run -v /path/to/downloaded/helm:/helm ubuntu:latest /helm/helm version` and no issue was observed there.

Let me know if I can provide any more information.

**Comment by khos2ow** [comment] 2019-11-26 16:31
Update: Actually just saw #6863 and with running `HELM_DEBUG=true` I got

**Comment by foux** [comment] 2019-11-26 17:04
@khos2ow that's exactly it, thanks!

**Comment by bacongobbler** [comment] 2019-11-26 17:05
closing as a duplicate of #6863

**Closed** 2019-11-26 17:05 UTC
Labels: question/support
