### ISSUE TITLE
helm delete in a sequence

### ISSUE THREAD

**Issue by swathimocharla** [helm/helm#4246] opened 2018-06-20 05:30 UTC
hi, i have a helm chart where i install zookeeper and kafka. zookeeper is a dependency in this kafka chart that is defined as part of the requirements.yaml.
installing this helm chart is all fine and the pods come up fine. But, delete of this chart is the one that is of concern.
zookeeper is terminated first and then all the kafka pods go into CrashLoopBackOff state as they cant find the zookeeper service. Is there a way to get around this issue?

Output of `helm version`:
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by swathimocharla** [comment] 2018-06-25 09:57
Also, there needs to be a way the user can define sequences in helm, for the life cycle events.

**Comment by krish7919** [comment] 2018-11-23 15:52
Can this be related to #4701?

**Comment by yaminisridaran** [comment] 2019-01-30 08:58
How to assign the priorities in templates. I wanted to delete a resource at the last. how do I achieve this?

**Comment by bacongobbler** [comment] 2019-12-09 19:49
duplicate of #4701.

**Closed by bacongobbler** 2019-12-09 19:49 UTC
Labels: question/support
