### ISSUE TITLE
helm upgrade --dry-run fails with the following error : Error: UPGRADE FAILED: grpc: received message larger than max (36218786 vs. 20971520)

### ISSUE THREAD

**Issue by VarunUmesh** [helm/helm#4973] opened 2018-11-27 03:46 UTC
I am upgrading my services using helm upgrade command and i observe the same behavior for the below commands :

1. helm upgrade --dry-run <service_name> <chart> --set image.tag=xxx -f values.yaml --namespace <ns> --tiller-namespace <tns> --debug

2. helm upgrade  <service_name> <chart> --set image.tag=xxx -f values.yaml --namespace <ns> --tiller-namespace <tns>

Output : Error: UPGRADE FAILED: grpc: received message larger than max (36218786 vs. 20971520)

helm version :
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Could anyone let me know what i might be doing wrong?

**Comment by bacongobbler** [comment] 2018-11-28 20:03
This may be a possible duplicate of one of the other tickets in the queue with a similar error? https://github.com/helm/helm/search?q=received+message+larger+than+max&type=Issues

**Comment by mattnidz** [comment] 2018-12-04 14:01
I have ran into this issue before. There is chart/release that is/was over the limit and To get around the error I had to remove unneeded files and use a .helmignore to ignore large folders such as nodejs packages etc.

**Comment by bacongobbler** [comment] 2019-12-09 20:03
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2019-12-09 20:03 UTC
Labels: question/support
