### ISSUE TITLE
Chart push/pull x509: certificate  verify faild

### ISSUE THREAD

**Issue by aiyijing** [helm/helm#9263] opened 2021-01-22 01:45 UTC
I create a docker register with self signed certificate，
But there was a mistake using this function chart push/pull 。
I hope that helm supports insecureflag, just like `helm registry login --insecure`
```shell
$ helm registry login 192.168.1.101:5000 --insecure
...
$ export  HELM_EXPERIMENTAL_OCI=1
$ helm chart push 192.168.1.101:5000/nginx:0.1.0
The push refers to repository [192.168.1.101:5000/nginx:0.1.0]
ref:     192.168.1.101:5000/nginx:0.1.0
digest:  05760338363e7802344b6e49c99b32fda58bc91a05b8277c45206653615e3fd2
size:    3.5 KiB
name:    nginx
version: 0.1.0
Error: failed to do request: Head "https://192.168.1.101:5000/nginx/blobs/sha256:cbcce8ad7fdaea54f60aeef01f57f2f46f67382b5d391d63d2b55f536195935a": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

Output of `helm version`:
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

**Comment by jdolitsky** [comment] 2021-01-25 14:11
Closing as duplicate of https://github.com/helm/helm/issues/6324

**Closed by jdolitsky** 2021-01-25 14:11 UTC
