### ISSUE TITLE
Helm 3: can not set namespace

### ISSUE THREAD

**Issue by tao12345666333** [helm/helm#5746] opened 2019-05-16 16:17 UTC
I want to deploy my chart https://github.com/tao12345666333/saythx/tree/master/saythx using Helm 3 to local kubernetes cluster.

```
(MoeLove) ➜  saythx git:(master) ✗ helm3 install --namespace=work saythx saythx 
Error: the namespace from the provided object "work" does not match the namespace "default". You must pass '--namespace=work' to perform this operation.
```

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-05-04T18:36:51Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kind

**Comment by bacongobbler** [comment] 2019-05-16 16:24
duplicate of #5628.

**Closed by bacongobbler** 2019-05-16 16:24 UTC
