### ISSUE TITLE
Error: apiVersion 'v2' is not valid. The value must be "v1"

### ISSUE THREAD

**Issue by masterkain** [helm/helm#6753] opened 2019-10-23 02:51 UTC
I'm trying to install some charts but:

Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

```
kain@kain-osx-qemu /tmp % helm install --name appmesh-prometheus eks/appmesh-prometheus \
--namespace appmesh-system \
--set retention=12h \
--set persistentVolumeClaim.claimName=prometheus
Error: apiVersion 'v2' is not valid. The value must be "v1"
```

**Comment by karuppiah7890** [comment] 2019-10-23 03:08
The issue is occurring because the Chart says the apiVersion is v2 - I think the chart maintainers used helm v3 to create it. And apiVersion v2 is understood only by helm v3 which is still in beta

**Comment by karuppiah7890** [comment] 2019-10-23 03:09
You need to raise the issue in the charts repository - https://github.com/aws/eks-charts and ask maintainers to use v1 till helm v3 is stable version. Also, I don't see the chart using any new features from helm v3, that I know of. So, I think they must be okay to put v1 as apiVersion

**Comment by karuppiah7890** [comment] 2019-10-23 03:10
Please close this issue as it's not an issue with helm itself. Helm is working as expected :) this behavior is so that people use helm v3 to install v3 compatible charts, as helm v2 cannot understand them

**Closed** 2019-10-23 03:33 UTC

**Comment by hickeyma** [comment] 2019-10-23 11:07
@masterkain When chart `apiVersion` is set to `v2` it signifies that it is using `v2` formats that are introduced in Helm v3. Therefore, `apiVersion: v2` is not rendered in Helm v2 because of this.
