### ISSUE TITLE
Helm does not wait for subchart pods to be ready

### ISSUE THREAD

**Issue by yellowmegaman** [helm/helm#11404] opened 2022-10-02 17:57 UTC
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+k3s1", GitCommit:"a8e0c66d1a90a2bbc4ffa975129ca35756cc7c14", GitTreeState:"clean", BuildDate:"2022-09-28T16:52:07Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
k3s
```

Repro:
```
helm repo add hashicorp https://helm.releases.hashicorp.com
helm create mainchart
echo -e 'dependencies:\n- name: vault\n  repository: "https://helm.releases.hashicorp.com"\n  version: "0.22.0"' | tee -a mainchart/Chart.yaml
helm upgrade --install --atomic --install --wait --timeout=120s --dependency-update somerelease mainchart
```

Full log:
```
$ rm -rf mainchart/

$ helm repo add hashicorp https://helm.releases.hashicorp.com
"hashicorp" has been added to your repositories

$ helm create mainchart
Creating mainchart

$ echo -e 'dependencies:\n- name: vault\n  repository: "https://helm.releases.hashicorp.com"\n  version: "0.22.0"' | tee -a mainchart/Chart.yaml
dependencies:
- name: vault
  repository: "https://helm.releases.hashicorp.com"
  version: "0.22.0"

$ helm upgrade --install --atomic --install --wait --timeout=120s --dependency-update somerelease mainchart
Release "somerelease" does not exist. Installing it now.
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "hashicorp" chart repository
...Successfully got an update from the "worldr-charts" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading vault from repo https://helm.releases.hashicorp.com
Deleting outdated charts
NAME: somerelease
LAST DEPLOYED: Sun Oct  2 17:54:33 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=mainchart,app.kubernetes.io/instance=somerelease" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

$ k get po
NAME                                               READY   STATUS              RESTARTS   AGE
somerelease-mainchart-57f5b779-6ndrx               1/1     Running             0          15s
somerelease-vault-0                                0/1     ContainerCreating   0          15s
somerelease-vault-agent-injector-c58d65f5b-rc7ww   1/1     Running             0          15s
$
```

Expected result - helm should fail, since subchart's pod is not in READY state

**Comment by joejulian** [comment] 2022-10-04 00:28
If you have a StatefulSet with a replica of 1 and a maxUnavailable of 1, the StatefulSet _is_ ready according to Kubernetes.

**Comment by yellowmegaman** [comment] 2022-10-04 09:57
@joejulian  Nice catch! Thank you

But is consistent with k8s api here?
```
$ k get sts
NAME                READY   AGE
somerelease-vault   0/1     79s
$
```

**Comment by joejulian** [comment] 2022-10-04 23:41
That's correct. If you check the sts status, you'll find that the sts, itself, is ready.

**Comment by felipecrs** [comment] 2022-11-01 17:48
Is there any workaround for the moment?

**Comment by felipecrs** [comment] 2022-11-01 19:32
Ok, here is the LoC:

https://github.com/helm/helm/blob/269dd247d092ebc8f3ed486a4468aac2b48e6aaa/pkg/kube/ready.go#L275

So it's indeed because of the maxunavailable setting, and has nothing to do with subcharts. I suggest we close this issue as duplicate of https://github.com/helm/helm/issues/8660

**Closed** 2022-11-01 21:56 UTC
Labels: question/support
