### ISSUE TITLE
helm latest gives back 2.6.13

### ISSUE THREAD

**Issue by dariuszparys** [helm/helm#7592] opened 2020-02-14 07:58 UTC
If you get the latest helm from 

https://api.github.com/repos/helm/helm/releases/latest

```
{
  "url": "https://api.github.com/repos/helm/helm/releases/23663865",
  "assets_url": "https://api.github.com/repos/helm/helm/releases/23663865/assets",
  "upload_url": "https://uploads.github.com/repos/helm/helm/releases/23663865/assets{?name,label}",
  "html_url": "https://github.com/helm/helm/releases/tag/v2.16.3",
  "id": 23663865,
  "node_id": "MDc6UmVsZWFzZTIzNjYzODY1",
  "tag_name": "v2.16.3",
  "target_commitish": "master",
  "name": "Helm v2.16.3",
  "draft": false,
  "author": {
    "login": "bacongobbler",
    "id": 1360539,
    "node_id": "MDQ6VXNlcjEzNjA1Mzk=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/1360539?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bacongobbler",
    "html_url": "https://github.com/bacongobbler",
    "followers_url": "https://api.github.com/users/bacongobbler/followers",
    "following_url": "https://api.github.com/users/bacongobbler/following{/other_user}",
    "gists_url": "https://api.github.com/users/bacongobbler/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bacongobbler/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bacongobbler/subscriptions",
    "organizations_url": "https://api.github.com/users/bacongobbler/orgs",
    "repos_url": "https://api.github.com/users/bacongobbler/repos",
    "events_url": "https://api.github.com/users/bacongobbler/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bacongobbler/received_events",
    "type": "User",
    "site_admin": false
  },
``` 

you'll retrieve 2.6.13 instead of 3.0.3 or meanwhile 3.1.0

Is this by intension or just a bug?

**Comment by hickeyma** [comment] 2020-02-14 09:55
Duplicate of #7586

**Comment by hickeyma** [comment] 2020-02-14 09:56
Fixed in #7589

**Comment by hickeyma** [comment] 2020-02-14 10:23
Re-opening as this has to do with GitHub assigning "latest release" to the last published release. In this case it is "2.16.3".

**Comment by hickeyma** [comment] 2020-02-14 10:28
it seems the "latest release" is determined from the timestamps on the tags. This is why "2.16.3" is  the latest. Maybe someone know how to change this?

**Comment by bacongobbler** [comment] 2020-02-14 14:58
GitHub does not let a project control what is determined as “latest”. “latest” is equivalent to whichever release was most recently published.

**Closed by bacongobbler** 2020-02-14 14:58 UTC
Labels: question/support
