### ISSUE TITLE
Error: open .helm\repository\cache\local-index.yaml

### ISSUE THREAD

**Issue by Rurouni** [helm/helm#2071] opened 2017-03-06 13:14 UTC
Hi, when I am running `helm dep up` with `file://` dependency I get:

```
Repository from local path: file://components/nats
Hang tight while we grab the latest from your chart repositories...
Writing to .helm\repository\cache\.helm\repository\cache\stable-index.yaml
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
        open .helm\repository\cache\.helm\repository\cache\stable-index.yaml: The system cannot find the path specified.
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
        Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connectex: No connection could be made because the target machine actively refused it.
Update Complete. ⎈Happy Helming!⎈
Error: open .helm\repository\cache\local-index.yaml: The system cannot find the path specified.
```
looking at what` helm init `has created I can see that `local-index.yaml `exist in cache but it's not a file but symlink leading to `<path>\.helm\repository\cache\.helm\repository\cache\local-index.yaml ` that doesn't exists.  As a workaround I can delete `local` repository from `repositories.yaml` and then `helm dep up` works without errors. 

Environment: Win 10, helm:2.2.1

**Comment by technosophos** [comment] 2017-03-07 19:32
Does `helm serve` work?

**Comment by bhaskarduvvuri** [comment] 2017-03-13 14:24
I am on Windows 7, I am facing the same error but while adding a local repo. So, I had to delete the symlink and copy index.yaml to repository\cache\local-index.yaml. After restarting helm serve, it seems to work.

**Comment by technosophos** [comment] 2017-03-15 21:12
I'm going to mark this as a bug and flag it as Helm Wanted.

**Comment by mlushpenko** [comment] 2017-06-24 20:18
I changed `\.helm\repository\cache\stable-index.yaml` in `C:\.helm\rpositories` to `C:\.helm\repository\cache\stable-index.yaml` and update worked. 

`helm serve` didn't complain either I added `C:` in front or not

**Comment by pietromenna** [comment] 2017-10-10 00:08
May I give it a try to this issue?

**Comment by bacongobbler** [comment] 2017-10-10 00:26
Sure. Not sure when I self-assigned this but give it a go :)

**Comment by thomastaylor312** [comment] 2017-10-10 00:49
Removing help wanted since @pietromenna is taking it on

**Comment by bacongobbler** [comment] 2017-12-01 22:13
According to #3219 this was not fixed in v2.7.1. Re-opening this bug to do further investigation.

**Comment by pietromenna** [comment] 2017-12-01 23:01
Hi @bacongobbler ,

I will check in a new machine if there was an environment setting which made the issue not to happen after the changes on 2.7.1

**Comment by mattfarina** [comment] 2018-05-11 17:17
I think I'm able to reproduce this on ubuntu with Helm 2.9.0.

**Comment by wackerman** [comment] 2018-05-22 15:08
I am gettting this error as well
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "cassandra" chart repository
...Unable to get an update from the "stable" chart repository (https://kubernetes-charts.storage.googleapis.com):
	Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 74.125.199.128:443: i/o timeout
Update Complete. ⎈Happy Helming!⎈
helm 2.9.1 on ubuntu

**Comment by bacongobbler** [comment] 2018-05-28 22:12
@wackerman that looks like a separate issue; likely there might've been some downtime on Google Cloud Storage or something. Does it work now?

@mattfarina can you provide steps to reproduce this issue? I thought this was Windows-specific :)

**Comment by bacongobbler** [comment] 2018-06-08 15:59
@mattfarina ping

**Comment by mattfarina** [comment] 2018-07-09 17:49
@bacongobbler I cannot remember how I experienced that or fixed it.

**Comment by bacongobbler** [comment] 2018-08-01 19:10
ok, let's consider this closed this for now but re-open if it comes up again.

**Closed by bacongobbler** 2018-08-01 19:10 UTC
Labels: bug

**Comment by woshifudayun** [comment] 2019-08-29 15:01
I'm experiencing the same issue here. Getting ` open /Users/yun/.helm/repository/cache/local-index.yaml: no such file or directory` even when the file is there as I can find it.

**Comment by gnana03** [comment] 2019-09-05 11:33
Even i am experiencing the same issue when i am trying to deploy ingress controller.
Error : Release "ingress-kube-system" does not exist. Installing it now.
Error: found in requirements.yaml, but missing in charts/ directory: helm-toolkit

any work around on this please share?
