### ISSUE TITLE
invalid path for --kubeconfig parameter causes exit without any output

### ISSUE THREAD

**Issue by nniikkoollaaii** [helm/helm#7125] opened 2019-12-02 13:13 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
irrelevant
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
irrelevant

The following command 
`helm install chartname ./dir/to/chart --kubeconfig kubeconfig-name`
fails without any error output if the path to kubeconfig is invalid.

adding --debug shows:
> helm.go:71: [debug] CreateFile kubeconfig-name: Das System kann die angegebene Datei nicht finden.

(Translated to English: The System cannot find the specified file)

I would expect the helm install command to output a error message if helm can't find the specified file

**Comment by marckhouzam** [comment] 2019-12-02 14:04
Thanks for the report.  
Duplicate of #6863 
There is an attempt at a fix in #6915

**Comment by hickeyma** [comment] 2019-12-02 14:34
Closing as duplicate

**Closed by hickeyma** 2019-12-02 14:34 UTC
