### ISSUE TITLE
helm upgrade --debug --dry-run displays old NOTES.txt

### ISSUE THREAD

**Issue by thomas-riccardi** [helm/helm#3918] opened 2018-04-18 13:52 UTC
# Description
helm upgrade --debug --dry-run displays old NOTES.txt

## Scenario
- `helm install .` OK
- edit `NOTES.txt`
- `helm upgrade --debug --dry-run` 

Expected result:
Renders the new `NOTES.txt`

Actual result:
It renders the old `NOTES.txt`.

# Info
## Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
```
## Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.10-gke.0", GitCommit:"16ebd0de8e0ab2d1ef86d5b16ab1899b624a77cd", GitTreeState:"clean", BuildDate:"2018-03-20T20:21:01Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

## Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

**Comment by jascott1** [comment] 2018-04-23 17:49
Confirmed the issue is that `--dry-run` does not display changes from disk but a normal upgrade command does return the updated notes. Marking as a bug since user expects to see the final output in the dry-run.

**Comment by adshmh** [comment] 2018-05-03 16:12
I have started working on this.

**Comment by adshmh** [comment] 2018-05-03 17:45
This can be fixed on the client side by updating the Notes field from Status (I will submit a PR for this)

As a second option, it seems that tiller could return the latest resource string (which seems to be the only "missing" piece of information) as part of the update response and remove the need for a second tiller call from client side. The downside could be that tiller will need to make an additional call to the api-server as part of update operation (currently, this call is made anyways as the upgrade command requests it from tiller).

If the second option seems preferable, please let me know and I can submit a PR for that instead.

**Comment by bacongobbler** [comment] 2020-05-14 21:30
closing as inactive.

**Closed by bacongobbler** 2020-05-14 21:30 UTC
Labels: bug
