### ISSUE TITLE
Error: grpc: received message larger than max (22988949 vs. 20971520)

### ISSUE THREAD

**Issue by bizso** [helm/helm#8871] opened 2020-10-11 03:10 UTC
Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bizso** [comment] 2020-10-11 03:21
helm install local/onap --name dev --namespace onap
Output of helm version:2.16.6

**Comment by hickeyma** [comment] 2020-10-12 09:13
Duplicate of #7799

**Comment by hickeyma** [comment] 2020-10-12 09:14
@bizso Check if there is any artefacts in your chart directory that shouldn't be there. Your chart size is exceeding the limit.

There are many more such issues like #3512

**Comment by hickeyma** [comment] 2020-10-12 09:15
Closing as a duplicate.

**Closed by hickeyma** 2020-10-12 09:15 UTC
