### ISSUE TITLE
helm dependency update fails even though helm fetch succeeds

### ISSUE THREAD

**Issue by avgalani** [helm/helm#5321] opened 2019-02-16 18:55 UTC
I have harbor installed in a kubernetes cluster. Harbor is set-up with https using a self signed certificate. 
I have added the repository for charts, as per the harbor instructions, pointing to --ca-file when adding it.

`helm repo add --ca-file /path/to/ca.crt --username SuperSecretUsername --password SuperSecretPassword my_repo https://harbor.test/chartrepo/my_charts`

Output of helm repo list:

```
➜  ~ helm repo list
NAME    	URL
my_repo	https://harbor.test/chartrepo/my_charts
```

Output of helm search:

```
➜  ~ helm search
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
my_repo/activemq	1.0.0        	1.10.0     	Apache ActiveMQ configuration
my_repo/registry	1.10.0       	1.10.0     	just a java app
```

I am able to fetch charts using the defined repo, for example helm fetch my_repo/activemq works perfectly! However, if I set another chart to be dependent on ActiveMQ, say for example the below requirements.yaml:

```
dependencies:
  - name: activemq
    version: "1.0.0"
    repository: "@my_repo"
```

when doing helm dependency update I get the following output:

```
➜  registry git:(master) ✗ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "my_repo" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading activemq from repo https://harbor.test/chartrepo/my_charts
Save error occurred:  could not download https://harbor.test/chartrepo/my_charts/charts/activemq-1.0.0.tgz: Get https://harbor.test/chartrepo/my_charts/charts/activemq-1.0.0.tgz: x509: certificate signed by unknown authority
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://harbor.test/chartrepo/my_charts/charts/activemq-1.0.0.tgz: Get https://harbor.test/chartrepo/my_charts/charts/activemq-1.0.0.tgz: x509: certificate signed by unknown authority
```

Am I missing something here?

Output of `helm version`:

```➜  ~ helm version
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment] 2019-02-18 11:56
I wonder is there any correlation between #5179 chartmuseum issue and this issue?

**Comment by hickeyma** [comment] 2019-02-22 16:44
@avgalani Can I close this issue as a duplicate of #5179 ?

**Comment by bacongobbler** [comment] 2019-02-25 21:14
closing as a dupe of #5179

**Closed** 2019-02-25 21:14 UTC
