### ISSUE TITLE
Helm3-beta.1 --dependency-update gives an error ".config/helm/repositories.yaml: no such file or directory"

### ISSUE THREAD

**Issue by NishikaDeSilva** [helm/helm#6531] opened 2019-09-30 07:21 UTC
Output of `helm version`: v3.0.0-beta.1

Output of `kubectl version`: v1.10.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I'm trying to install a chart with NFS dependency with the following command. 

```
helm install {CHART_NAME} {CHART} --dependency-update
```
But this command provides following error:

```
Error: couldn't load repositories file (/home/ubuntu/.config/helm/repositories.yaml): open /home/ubuntu/.config/helm/repositories.yaml: no such file or directory
```
*requirements.yaml* : 
```
dependencies:
  - name: nfs-server-provisioner
    version: "0.3.0"
    repository: "https://kubernetes-charts.storage.googleapis.com"
    tags:
      - internal-nfs
```

**Comment by rimusz** [comment] 2019-09-30 08:52
It looks you did not `stable` repo, which was removed from helm v3 to be set be default.
and please try it with the latest beta 3.

**Comment by hickeyma** [comment] 2019-09-30 09:00
Duplicate of https://github.com/helm/helm/issues/6287. Closing as fixed in beta 2. As @rimusz suggested, can you try the latest release [beta 3](https://github.com/helm/helm/releases/tag/v3.0.0-beta.3).

**Closed by hickeyma** 2019-09-30 09:00 UTC

**Comment by NishikaDeSilva** [comment] 2019-09-30 12:04
That works thanks !!!
