### ISSUE TITLE
requirements.lock will not be updated

### ISSUE THREAD

**Issue by benkeil** [helm/helm#4011] opened 2018-05-03 07:17 UTC
Output of `helm version`: 
```
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-13T22:27:55Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `none`

`helm dependency update .` works like expected and loads the version 2.1.0, but in the `requirements.yaml` is still the old `2.0.2` version written. So its not possible to use `helm dependency build` during CI/CD.

Our `requirements.yaml`:

```
dependencies:
  - name: common
    repository: "@sedo"
    version: ^2.0.0
```

It will also not work with helm `2.7.0`.

**Comment by discostur** [comment] 2018-05-07 16:37
Seeing exact the same issue on our deployments ...

**Comment by technosophos** [comment] 2018-05-09 23:34
I presume that deleting the lock file and rewriting will add the correct version? Sounds like something is not correctly regenerating the lock.

**Comment by benkeil** [comment] 2018-05-10 06:18
Your right. The lock file will also be updated if you change the version.

**Comment by benkeil** [comment] 2018-07-27 08:17
any news on this?

**Comment by bassch** [comment] 2018-08-21 08:15
I'm experiencing the same issue.

**Comment by trthomps** [comment] 2018-11-14 01:01
I'm also experiencing this, working on debugging it and proposing a fix.

**Comment by trthomps** [comment] 2018-11-14 01:11
The issue is here: https://github.com/helm/helm/blob/master/pkg/downloader/manager.go#L159-L163

It checks if the hash of `requirements.yaml` changed, not `requirements.lock` when deciding if it should write `requirements.lock` which doesn't make sense if you run with loose dependencies in `requirements.yaml`; for example we use the format `^N.N.x` to pull in the latest minor release of a chart automatically in our CI/CD environment.  I'll work on a PR to fix this, until then the workaround as mentioned above is to delete `requirements.lock` before run `helm dep up`.

**Comment by bacongobbler** [comment] 2019-06-11 22:52
duplicate of #2731.

**Closed by bacongobbler** 2019-06-11 22:52 UTC
Labels: bug
