### ISSUE TITLE
Helm 3: Not able to install chart with custom resource yaml

### ISSUE THREAD

**Issue by karuppiah7890** [helm/helm#5654] opened 2019-04-28 12:19 UTC
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"1b77848c89e8df414aea055cca5d1a1997a62f0c", GitTreeState:"dirty"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:05:06Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I tried to install a redis chart which has a custom resource and the k8s cluster has the CRD for the custom resource, but I still get this error. Didn't face this issue with helm v2 though

```
$ helm install test-helm3 redis
Error: apiVersion "monitoring.coreos.com/v1" in redis/templates/servicemonitor.yaml is not available
```

```
$ kubectl get crd
NAME                                    CREATED AT
alertmanagers.monitoring.coreos.com     2018-12-31T13:08:14Z                                                  
backendconfigs.cloud.google.com         2018-09-21T10:35:53Z                                                  
prometheuses.monitoring.coreos.com      2018-12-31T13:08:14Z                                                  
prometheusrules.monitoring.coreos.com   2018-12-31T13:08:15Z                                                  
scalingpolicies.scalingpolicy.kope.io   2018-09-21T10:36:22Z                                                  
servicemonitors.monitoring.coreos.com   2018-12-31T13:08:14Z
```

**Comment by karuppiah7890** [comment] 2019-04-28 12:48
I am actually interested to contribute to fix this one! I started navigating the code and found the place where the error occurs and what are the API groups and versions that the client is able to fetch and got this list by doing a `log.Print()` in the code

```
manifest_sorter.go:133: map[admissionregistration.k8s.io/v1beta1:{} apps/v1:{} apps/v1beta1:{} apps/v1beta2:{}
auditregistration.k8s.io/v1alpha1:{} authentication.k8s.io/v1:{} authentication.k8s.io/v1beta1:{} authorization.k8s.io/v1:{} authorization.k8s.io/v1beta1:{} autoscaling/v1:{} autoscaling/v2beta1:{} autoscaling/v2beta2:{} batch/v1:{} batch/v1beta1:{} batch/v2alpha1:{} certificates.k8s.io/v1beta1:{} coordination.k8s.io/v1:{} coordination.k8s.io/v1beta1:{} events.k8s.io/v1beta1:{} extensions/v1beta1:{} networking.k8s.io/v1:{} networking.k8s.io/v1beta1:{} node.k8s.io/v1alpha1:{} node.k8s.io/v1beta1:{} policy/v1beta1:{} rbac.authorization.k8s.io/v1:{} rbac.authorization.k8s.io/v1alpha1:{} rbac.authorization.k8s.io/v1beta1:{} scheduling.k8s.io/v1:{} scheduling.k8s.io/v1alpha1:{} scheduling.k8s.io/v1beta1:{} settings.k8s.io/v1alpha1:{} storage.k8s.io/v1:{} storage.k8s.io/v1alpha1:{} storage.k8s.io/v1beta1:{} v1:{}]
```

Tried to dig more and found the place where this was fetched, which is here:

https://github.com/helm/helm/blob/1b77848c89e8df414aea055cca5d1a1997a62f0c/pkg/chartutil/capabilities.go#L80

But couldn't understand how to solve the problem. Like, how to get all the API groups and versions which includes the CRDs too

**Comment by hickeyma** [comment] 2019-04-29 11:15
@karuppiah7890 To help reproduce this, what redis chart are you installing?

**Comment by karuppiah7890** [comment] 2019-04-29 15:19
This is a custom Redis chart that my team uses. But I can help you with
reproducing this. I will come up with a basic set of steps to reproduce the
exact issue or at least similar

**Comment by karuppiah7890** [comment] 2019-04-30 03:42
Steps to reproduce: 

1. Download this tar ball [test-chart.tar.gz](https://github.com/helm/helm/files/3129883/test-chart.tar.gz) and extract it into a directory

2. cd into the directory

3. Create a CRD

```
$ kubectl apply -f servicemonitor-crd.yaml
```

4. Install the chart with helm

```
$ helm install test test-chart/
```

and this error will pop up:

```
Error: apiVersion "monitoring.coreos.com/v1" in test-chart/templates/servicemonitor.yaml is not available
```

**Comment by karuppiah7890** [comment] 2019-04-30 03:47
I followed the same steps with helm v2 and it worked. Here's the version details 

```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by hickeyma** [comment] 2019-05-02 13:36
@karuppiah7890 The issue here seem similar to the [prometheus-operator chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) and the issue raised https://github.com/helm/charts/issues/9597. Do you mind taking a look and see if it is related to this?

**Comment by karuppiah7890** [comment] 2019-05-05 14:37
@hickeyma in prometheus-operator chart the CRD and the instances of the CRD are installed together and there have been issues around it. In this (#5654) issue, I installed the CRD manually using `kubectl apply` and then tried to create a instance of the CRD using `helm`. So I think it's not related to the prometheus-operator issue which seems to be different. 

And the chart installation didn't work only in v3, but it does work in v2. I have to check how it works in v2 to dig more into this

**Comment by hickeyma** [comment] 2019-05-08 09:16
@karuppiah7890 let me know what you find out from your investigations.

**Comment by karuppiah7890** [comment] 2019-05-15 08:18
I am going to investigate further by checking how it works in v2.13.1. Will post updates when I find something

**Comment by k** [comment] 2019-06-19 03:29
Any update on this? This is likely blocking many users of prometheus-operator from using helm3.

**Comment by bacongobbler** [comment] 2019-07-19 18:12
@karuppiah7890 ping RE: an update on this. I'm currently diving into what's causing the underlying issue but if you have more information to share I'd love to hear about your findings.

**Comment by bacongobbler** [comment] 2019-07-19 20:20
I was able to reproduce the issue with both the cert-manager and prometheus-operator charts, however, it looks like it's just a short-lived temporary error. It takes some time for the CRDs to register with the API server. It took a few minutes on my test cluster. Once they were established, I could install both cert-manager and prometheus-operator.


For cert-manager, I used the following steps: https://github.com/jetstack/cert-manager/issues/1744#issuecomment-513349489

And for the prometheus-operator chart:

```
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/alertmanager.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheus.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/prometheusrule.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/servicemonitor.crd.yaml
kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/podmonitor.crd.yaml
```

Wait a few minutes for the API server to register the CRDs, then

```
helm install prom stable/prometheus-operator
```

I hit a few validation errors, but point still stands :)

**Comment by yhrn** [comment] 2019-07-19 21:08
But there's got to be more to it. I couldn't even run helm template with a CR in my chart.

**Comment by bacongobbler** [comment] 2019-07-20 00:03
`helm template` uses the default APIVersions that are available for a given version of client-go. It doesn't connect to a cluster to determine what APIVersions are available for the chart.

That's the primary reason for https://github.com/helm/helm/pull/6049: it connects to the kubernetes cluster to fetch available GroupVersionKinds (e.g. CRDs registered with the cluster).

**Comment by yhrn** [comment] 2019-07-20 09:00
Ok, but `helm install --dry-run` also failed the same way for me with a CR for which the CRD had been installed in the cluster for days. This was roughly two weeks back and I had just downloaded the latest v3 build.

**Comment by bacongobbler** [comment] 2019-07-28 20:27
If you can provide steps to demonstrate the issues you're experiencing, I can look into it this week. Otherwise I think this issue can be closed.

**Comment by yhrn** [comment] 2019-07-29 09:19
Sorry, but it seems like I got things confused somehow because now it seems to behave like you say - `helm install` (with or without `--dry-run`) works if the CRD is installed but `helm template` fails. 

With alpha 2 `helm template --validate` succeeds though thanks to #6049 but I find it unexpected that `helm template` without `--validate` still fails. In my opinion the expected behavior would be that template without validation should continue to be an offline operation but not fail for unknown resource types and with validation it should behave like it does in alpha 2. But maybe that discussion should be moved somewhere else?

**Comment by bacongobbler** [comment] 2019-07-29 15:20
Feel free to suggest a PR that registers unknown API types with the Kube client. As far as I know that's not possible. I would be happy to be proven wrong.

Closing!

**Closed by bacongobbler** 2019-07-29 15:20 UTC
Labels: question/support
