### ISSUE TITLE
Proposal: Add annotations to all chart manifests

### ISSUE THREAD

**Issue by gadelkareem** [helm/helm#7193] opened 2019-12-10 13:01 UTC
I need to be able to add metadata labels and annotations to all the k8s objects that will be installed with helm from the chart. 
for ex:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/env: prod
```

Is that possible without modifying the chart?

**Comment by gadelkareem** [comment] 2019-12-10 13:03
Might be related to https://github.com/helm/helm/issues/1950

**Comment by bacongobbler** [comment] 2019-12-13 16:44
closing as a duplicate of #1950.

**Closed by bacongobbler** 2019-12-13 16:44 UTC
