### ISSUE TITLE
On upgrade, removing a serviceAccount from a deployment template does not get applied to kubernetes deployment object 

### ISSUE THREAD

**Issue by pv93** [helm/helm#4429] opened 2018-08-03 20:09 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.4", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-06-28T23:30:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Steps to reproduce:

1) Create a chart with a deployment with a pod template that has a `serviceAccount: foo` field.
2) `helm install` a release with this chart
3) Update the chart so that the template no longer has the `serviceAccount: foo` field. 
4) `helm upgrade` this release with new version of chart
5) Observe that the deployment still has the `serviceAccount: foo` field

**Comment by technosophos** [comment] 2018-08-03 23:26
I believe that `serviceAccount` is one of the deployment fields that cannot be modified after creation. The API server will silently ignore the change.

You can verify this by using `kubectl apply` or `kubectl edit` to try to make the same change.

**Comment by pv93** [comment] 2018-08-06 17:57
Hey @technosophos, thanks for the quick response. 

I don't think that it's immutable - I actually ran `kubectl edit` and removed the `serviceAccount` and `serviceAccountName` fields successfully as a workaround for this issue.

Nothing in the API spec about it being immutable either: https://v1-10.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#podspec-v1-core.

**Comment by bilalyasar** [comment] 2018-08-29 10:03
@technosophos , I'm experiencing same issue.
somehow, helm doesn't update service account fields.

**Comment by hickeyma** [comment] 2019-04-10 06:56
Closing this as it is a duplicate of #5473

**Closed by hickeyma** 2019-04-10 06:56 UTC
Labels: question/support
