### ISSUE TITLE
Helm 3 upgrade --install faild has no deployed release

### ISSUE THREAD

**Issue by HamzaK8s** [helm/helm#7257] opened 2019-12-17 18:37 UTC
I'm using Helm 3 to install my chart using the following command :
```
helm upgrade --install project-x --wait --timeout 400s project-x/
```
I got ` Error: UPGRADE FAILED: "project-x" has no deployed releases`
and the output of  `helm ls ` as follows:
```
helm ls
NAME     NAMESPACE    REVISION	UPDATED     STATUS     CHART       APP VERSION                   
project-x	app-dev                1         	2019-12-17    failed        project-x	  0.0.1
```

Output of `helm version`: v3.0.1

Output of `kubectl version`: v1.14.8-gke.17

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Does anyone has an idea ?
Thanks

**Comment by phumberdroz** [comment] 2019-12-17 19:51
I encountered something similar looking at this it seems like it is a first install of a chart.
You can simply `helm delete project-x` and then install again.

**Comment by HamzaK8s** [comment] 2019-12-17 19:56
@phumberdroz in CI/CD we can't simply delete the chart

**Comment by phumberdroz** [comment] 2019-12-17 20:10
Right but this is b/c the first release failed right?

**Comment by HamzaK8s** [comment] 2019-12-17 20:34
@phumberdroz Yes, the first release failed

Is there any future work to change the logic when the initial release ends up in a failed state ?

cc @bacongobbler

**Comment by bacongobbler** [comment] 2019-12-17 20:37
closing as a duplicate of https://github.com/helm/helm/issues/5595.

**Closed by bacongobbler** 2019-12-17 20:37 UTC

**Comment by ryudice** [comment] 2020-01-09 15:24
I'm having this exact issue, but in my case I have no charts installed, the output of helm ls is empty yet I'm getting this error. Any ideas?

**Comment by rodalli** [comment] 2020-02-17 03:15
> I'm having this exact issue, but in my case I have no charts installed, the output of helm ls is empty yet I'm getting this error. Any ideas?

@ryudice My guess would be that your kubeconfig is pointed at another namespace, such that when you issue "helm ls" you see no deployments. But when you issue your helm upgrade command, you're providing the namespace where the release is deployed.

**Comment by abdennour** [comment] 2020-03-10 03:50
same issue as well as upgrading from helm 2 to helm 3. 
`Error: UPGRADE FAILED: "company-services-development" has no deployed releases`
Should we install it from scartch using `helm install` instead of `helm upgrade` ?

**Comment by medmedchiheb** [comment] 2020-08-05 15:03
The problem was, that the previous helm chart stuck on uninstalling state for any reason and you can find it via `helm ls -n std -a | grep whatever`
Deleting the old release fixes the issue.

**Comment by vinayGudi** [comment] 2021-01-05 08:36
@medmedchiheb  yes deleting the release will work but it is not always the good idea. 
in our case we have large dbs running....if we delete the release every time we encounter this problem then always we lose data in pv and need to restore the latest snapshot version :(
