### ISSUE TITLE
helm upgrade --forc --automic, spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by zhb127** [helm/helm#8234] opened 2020-06-01 04:04 UTC
![image](https://user-images.githubusercontent.com/5210208/83374783-333f5d00-a3ff-11ea-99ca-440d3913dfb9.png)

![image](https://user-images.githubusercontent.com/5210208/83374946-ce383700-a3ff-11ea-9816-25e179ee943f.png)

We have not modified the service configuration in chart，but got  Upgrade "drms-admin-web" failed: failed to replace object: Service "drms-admin-web" is invalid: spec.clusterIP: Invalid value: "": field is immutable

`helm version`:
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

`kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-15T01:55:22Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}

Cloud Provider/Platform: 
Alicloud CS

**Comment by bacongobbler** [comment] 2020-06-01 15:41
Duplicate of #6378. I left a comment in that thread that explains the situation in greater detail. Please have a read through that thread and see if anything relates here.

**Comment by bacongobbler** [comment] 2020-06-01 16:45
I noticed in the title you used `--force`. As described in that issue, omitting `--force` resolves the issue. Therefore, closing as a duplicate of #6378.

**Closed by bacongobbler** 2020-06-01 16:45 UTC
Labels: question/support
