### ISSUE TITLE
helm pre-install/hook-weight hook does not wait ready recources of subchart

### ISSUE THREAD

**Issue by patsevanton** [helm/helm#11512] opened 2022-11-05 09:54 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-17T22:25:22Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Yandex Cloud
```

I have main chart and subchart cassandra. Repository: https://github.com/patsevanton/hook-weight-for-subchart

For all recources subchart added annotation:
```
cassandra:
  commonAnnotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
```

But main pod don`t wait of ready cassandra:
```
kubectl get pod -n loggenerator -w
NAME                                       READY   STATUS              RESTARTS   AGE
loggenerat-cassandra-0                     0/1     Pending             0          0s
loggenerat-cassandra-0                     0/1     Pending             0          9s
loggenerat-cassandra-0                     0/1     ContainerCreating   0          9s
loggenerat-loggenerator-6b7dff5fbd-zrwx4   0/1     Pending             0          0s
loggenerat-loggenerator-6b7dff5fbd-zrwx4   0/1     Pending             0          0s
loggenerat-loggenerator-6b7dff5fbd-zrwx4   0/1     ContainerCreating   0          0s
loggenerat-loggenerator-6b7dff5fbd-zrwx4   1/1     Running             0          1s
loggenerat-cassandra-0                     0/1     Running             0          28s
loggenerat-cassandra-0                     1/1     Running             0          90s
```

Helm template: https://gist.github.com/patsevanton/a8abf9af71ece54f1a72973b0802f64a

**Comment by joejulian** [comment] 2022-11-08 21:00
The default value of maxUnavailable is 1. Since you only have 1 replica, Kubernetes reports your statefulset as ready. Closing this as a duplicate of #8660

**Closed by joejulian** 2022-11-08 21:00 UTC
