### ISSUE TITLE
helm repo search giving random results after v2.16.0

### ISSUE THREAD

**Issue by felipecrs** [helm/helm#8865] opened 2020-10-09 01:38 UTC
Every time I search for a chart I receive a random result:

![image](https://user-images.githubusercontent.com/29582865/95531272-854c4c80-09b6-11eb-93a1-2c5c247e322a.png)

If I try with Helm v2.15.2, it works though. Any other version after it (starting from v2.16.0) does not work:

![image](https://user-images.githubusercontent.com/29582865/95531374-b6c51800-09b6-11eb-90ef-6f9ac66625d8.png)

I saw that Helm v2.16.0 has a change in the search command: https://github.com/helm/helm/commit/71fa47f576129e2e18092f1a71b989bfaef7f55b

I wonder if this is because my charts have the build number (after the `+`) . This is compliant with semver.org: https://semver.org/#spec-item-10

I wish I could share the repository so you could test, but it's private. It's an Artifactory though, if it helps, and I already regenerated the `index.yaml` multiple times.

I already checked every single version of this chart in the repository, and all of them matches the format `major.minor.patch+build`.

This can be related to: https://github.com/helm/helm/issues/8295

**Comment by hickeyma** [comment] 2020-10-09 10:59
Thanks for raising the issue @felipecrs. As I cannot reproduce this myself, we will need to try and understand your environment and how to reproduce.

> I already checked every single version of this chart in the repository, and all of them matches the format

What file did you check for this? 

Do you get the same inconsistent output if you run: `helm search river/<>-common`? What is the output if you run: `helm search river/<>-common --devel`?

**Comment by felipecrs** [comment] 2020-10-09 13:52
> What file did you check for this?

All the existing `<>-common-<version>.tgz` files under the `<>-common` folder, in the repo. To make sure, I also deleted the `index.yaml` and regenerated (in the remote repository). Then I manually took a look in the `index.yaml`, and all the versions inside of it seem fine.

> Do you get the same inconsistent output if you run: helm search river/<>-common? 

What do you mean? In Helm v3, the command is `helm search repo <>`, right? And yes, using Helm v2.16, the `helm search <>` does not work, but in Helm v2.15 it does (as I showed in the description.

![image](https://user-images.githubusercontent.com/29582865/95591288-f5c98c80-09fb-11eb-8d7e-850cf8920fe1.png)

**Comment by mattfarina** [comment] 2020-10-09 14:33
@felipecrs Is the version being shown always the same `major.minor.patch` (e.g. `21.0.0`)?

In the [SemVer spec](https://semver.org/#spec-item-10) it says:

> Build metadata MUST be ignored when determining version precedence.

[RFC 2119](https://tools.ietf.org/html/rfc2119), which is referenced in the SemVer spec, for MUST says:

> ... the definition is an absolute requirement of the specification

A tool looking to figure out which is the latest will see multiple records with a version of `21.0.0`. They are all considered equivalent.

Following the code on this will be a bit of work. There were also changes to the underlying YAML packages we use that could impact this that came out in v2.16.0. The sorting code to get the versions in the right order hasn't changed. Because `21.0.0+1` and `21.0.0+2` are seen as the same it's going to depend on the order they are sent into the Helm handling. This will depend on how the YAML holding the data is parsed and turned into objects the sorting acts on.

**Comment by felipecrs** [comment] 2020-10-09 14:45
> @felipecrs Is the version being shown always the same major.minor.patch (e.g. 21.0.0)?

Yes, always.

Okay, so it seems that build metadata is not supported by Helm. Right?

**Comment by mattfarina** [comment] 2020-10-09 14:48
@felipecrs build metadata is NOT supported for determining precedence by the SPEC. Any tool that uses build metadata in determining precedence isn't following SemVer.

**Comment by felipecrs** [comment] 2020-10-09 14:50
I see. So, in fact `21.0.0+2` is not higher than `21.0.0+1`. They're all the same. I think I misunderstood semver.org so, it means that build metadata is purely cosmetic so.

**Comment by mattfarina** [comment] 2020-10-09 15:09
build metadata is like a code comment. It can provide some information about a build but doesn't affect the version itself.

**Comment by bacongobbler** [comment] 2020-10-09 15:57
I'm going ahead and closing this as answered/working as intended. As @mattfarina pointed out, there is no ordering precedence when given two identical version identifiers with differing build metadata, and they should be treated as indeterminate. Putting any form of sort order (in other words, making the results less random) would imply a sorted order and would break compliance with the spec. As far as the specification is concerned, this is the expected and intended behavior.

Thank you for your question.

**Closed by bacongobbler** 2020-10-09 15:57 UTC
Labels: bug, unconfirmed

**Comment by bacongobbler** [comment] 2020-10-09 15:58
FYI, if you want to see all possible versions available for a given chart, `helm search --versions` should give you all available versions of the chart. :)

**Comment by felipecrs** [comment] 2020-10-09 16:07
Thank you very much, guys! :D

**Comment by felipecrs** [comment] 2020-10-09 16:27
I wonder why the `helm fetch` behaves differently than `helm search` when finding the latest version:

![image](https://user-images.githubusercontent.com/29582865/95608185-9c6c5800-0a11-11eb-87db-cfc989abe57d.png)

**Comment by felipecrs** [comment] 2020-10-11 17:04
@bacongobbler @mattfarina should I open a new issue for that?
