### ISSUE TITLE
Helm v3.0.0 : Missing Resources field in command   `helm status <release-name>`

### ISSUE THREAD

**Issue by magicLian** [helm/helm#6963] opened 2019-11-14 02:02 UTC
Helm v3.0.0

`helm status <release-name>`

```
root@lz-ubuntu:/usr/local/bin# helm3 status releasename-100
NAME: releasename-100
LAST DEPLOYED: Thu Nov 14 09:31:40 2019
NAMESPACE: xxxx
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace xxxx -l "app.kubernetes.io/name=sso-bare-metal,app.kubernetes.io/instance=releasename-100" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
```

Missing the Resource field.

**Comment by bacongobbler** [comment] 2019-11-14 02:33
closing as a duplicate of https://github.com/helm/helm/issues/5952. Thanks.

**Closed by bacongobbler** 2019-11-14 02:33 UTC
