### ISSUE TITLE
Support passing token and api server to the cli

### ISSUE THREAD

**Issue by waveywaves** [helm/helm#7292] opened 2019-12-23 15:30 UTC
### Feature Request
It should be possible for us to pass the token and apiserver info to the cli to target execution of commands via tokens and pointing specific clusters or kube masters respectively, as fashioned below
`helm install stable/mariadb --kube-token 1234aasfsadf --kube-server api.openshift.com/1234/qwer:6443`

**Comment by bacongobbler** [comment] 2019-12-30 16:44
duplicate of https://github.com/helm/helm/issues/5159

**Closed by bacongobbler** 2019-12-30 16:44 UTC
Labels: feature
