### ISSUE TITLE
get_helm.sh download server version v2.15.0

### ISSUE THREAD

**Issue by Acidguy** [helm/helm#6760] opened 2019-10-23 10:06 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Private cloud 

running an automated script to download and install Helm which leverages 
get_helm.sh
however post the install i noticed the version is v2.15.0 and not v2.15.1
as per https://github.com/rancher/rancher/issues/23516 i need  v2.15.1
how to get that version using .sh script

**Comment by hickeyma** [comment] 2019-10-23 10:39
@Acidguy It looks like you have the correct client version but the server (Tiller) is not updated. Can you run `helm init --upgrade` and then run ` helm version` to see if it is `2.15.1`?

**Comment by Acidguy** [comment] 2019-10-23 12:43
Yes I have tried that doesn't work

**Comment by hickeyma** [comment] 2019-10-23 12:53
What's the output from `helm init --upgrade`?

**Comment by Acidguy** [comment] 2019-10-23 13:24
early today  it was not updating the server version 
now it succeeeds
root@ansible:/etc/ansible/Anisble_Rancher# helm version
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

**Comment by bacongobbler** [comment] 2019-10-23 14:04
Okay. Without any reproduction steps or error messages to go on, let's close this as resolved for now. If you discover the error again, feel free to reopen this. Thanks.

**Closed by bacongobbler** 2019-10-23 14:04 UTC
Labels: v2.x

**Comment by Acidguy** [comment] 2019-10-24 08:23
close the issue please
