### ISSUE TITLE
helm 2.10.0 vs 2.9.1 -> proxy issues

### ISSUE THREAD

**Issue by ReSearchITEng** [helm/helm#4671] opened 2018-09-19 14:35 UTC
Output of `helm version`:
v2.10.0, on Centos, with working proxy and well tested proxy env settings (https_proxy,http_proxy,no_proxy)
Output of `kubectl version`:
v1.11.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
onprem

In the new helm v2.10.0 (as opposed to v2.9.1 and older) 
`helm init` and `helm repo update` gives this error:

> Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp: lookup kubernetes-charts.storage.googleapis.com on 10.1.2.3:53: **no such host**

Saw 2 other similar issues, but the answer don't cover my case
- #4251 , my error and issue is slightly different (I don't get their "TLS handshake timeout" error, but "no such host")
- #4271 , but in my case all is set ok (with http), and my error is different 

If I try 2.9.1 and older helm versions, works perfect. There is something broken in 2.10.0, but I can't figure out what is going on .
PS: proxy is being used, but this is the case for 2.9.1 as well, and there it works.
Also, manual `wget https://kubernetes-charts.storage.googleapis.com/index.yaml` also works perfectly.

**Comment by bacongobbler** [comment] 2018-09-19 14:38
dupe of #4326

**Closed by bacongobbler** 2018-09-19 14:38 UTC
