### ISSUE TITLE
Lint fails with empty rendered manifests

### ISSUE THREAD

**Issue by cvila84** [helm/helm#8909] opened 2020-10-16 20:05 UTC
As a good practice to avoid unwanted processing of our files by our IDEs, we are used to set `#@formatter:off` at the beginning of our YAML manifests.

A lot of them are also surrounded by conditions that can be changed through provided values.yaml at chart installation, such as:
```
#@formatter:off
{{ if .Values.dbUpgrade }}
...
{{ end }}
```
Which means rendering can lead to YAML manifest only containing the `#@formatter:off` comment

Linting these kind of manifests was working "thanks to" #6418. But now this issue is fixed (enabling again linting all the manifests included in the chart), we get this error:

```
❯ helm lint exploded-chart/xxx
==> Linting exploded-chart/xxx
[ERROR] templates/job-migrate.yaml: object name does not conform to Kubernetes naming requirements: "": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
```

I think we need [here](https://github.com/helm/helm/blob/a61ce5633af99708171414353ed49547cf05013d/pkg/lint/rules/template.go#L116) to prevent the YAML structure checks if we don't have any elements parsed, instead of considering the emptiness of the raw YAML string (once trimmed)

Hope this is clear :)

Output of `helm version`:
`version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}`

**Comment by mattfarina** [comment] 2020-10-19 13:46
You are right that there is an issue. This is a duplicate of #8621 that was previously reported. I'm going to close this as a duplicate.

**Closed by mattfarina** 2020-10-19 13:46 UTC
Labels: bug

**Comment by cvila84** [comment] 2020-10-19 15:39
ok my bad, i should have checked more carefully before logging a new one...

for this issue, do you plan to deliver a 3.3.5 bugfix-only release or shall we now wait for 3.4 ?

thanks !

**Comment by bacongobbler** [comment] 2020-10-19 16:07
there are no current plans for a 3.3.5 release at this time, so I'd wait for 3.4.0.
