### ISSUE TITLE
Helm v2.16.4: nil pointer in kube.getSelectorFromObject after upgrading from v2.16.3

### ISSUE THREAD

**Issue by stephan2012** [helm/helm#7812] opened 2020-03-25 13:33 UTC
Upgrade deployment with Helm 2.16.4 fails:

```
# helm upgrade fluent-bit clusterrepo/fluent-bit --install --atomic --version 0.4.7 --namespace log -f /etc/kubernetes/helm-values-fluent-bit.yaml 
Release "fluent-bit" has been upgraded.
Error: transport is closing
```

The reason for the closed connection is a segmentation violation in Tiller:

```
[storage] 2020/03/25 13:14:38 listing all releases with filter
[storage] 2020/03/25 13:14:38 listing all releases with filter
[storage] 2020/03/25 13:14:40 listing all releases with filter
[storage] 2020/03/25 13:14:42 listing all releases with filter
[tiller] 2020/03/25 13:14:44 getting history for release fluent-bit
[storage] 2020/03/25 13:14:44 getting release history for "fluent-bit"
[tiller] 2020/03/25 13:14:44 preparing update for fluent-bit
[storage] 2020/03/25 13:14:44 getting deployed releases from "fluent-bit" history
[storage] 2020/03/25 13:14:44 getting last revision of "fluent-bit"
[storage] 2020/03/25 13:14:44 getting release history for "fluent-bit"
[tiller] 2020/03/25 13:14:44 rendering fluent-bit chart using values
2020/03/25 13:14:44 info: manifest "fluent-bit/templates/psp.yaml" is empty. Skipping.
[tiller] 2020/03/25 13:14:45 creating updated release for fluent-bit
[storage] 2020/03/25 13:14:45 creating release "fluent-bit.v12"
[storage] 2020/03/25 13:14:45 getting release history for "fluent-bit"
[storage] 2020/03/25 13:14:45 getting deployed releases from "fluent-bit" history
[storage] 2020/03/25 13:14:45 deleting release "fluent-bit.v2"
[storage] 2020/03/25 13:14:45 Pruned 1 record(s) from fluent-bit with 0 error(s)
[tiller] 2020/03/25 13:14:45 performing update for fluent-bit
[tiller] 2020/03/25 13:14:45 executing 1 pre-upgrade hooks for fluent-bit
[tiller] 2020/03/25 13:14:45 hooks complete for pre-upgrade fluent-bit
[kube] 2020/03/25 13:14:45 building resources from updated manifest
[kube] 2020/03/25 13:14:45 checking 5 resources for changes
[kube] 2020/03/25 13:14:45 Looks like there are no changes for ConfigMap "fluent-bit-config"
[kube] 2020/03/25 13:14:45 Looks like there are no changes for ServiceAccount "fluent-bit"
[kube] 2020/03/25 13:14:45 Looks like there are no changes for ClusterRole "fluent-bit"
[kube] 2020/03/25 13:14:45 Looks like there are no changes for ClusterRoleBinding "fluent-bit"
[kube] 2020/03/25 13:14:45 Looks like there are no changes for DaemonSet "fluent-bit"
[kube] 2020/03/25 13:14:45 beginning wait for 5 resources with timeout of 5m0s
[tiller] 2020/03/25 13:14:47 executing 1 post-upgrade hooks for fluent-bit
[tiller] 2020/03/25 13:14:47 hooks complete for post-upgrade fluent-bit
[storage] 2020/03/25 13:14:47 updating release "fluent-bit.v11"
[tiller] 2020/03/25 13:14:47 updating status for updated release for fluent-bit
[storage] 2020/03/25 13:14:47 updating release "fluent-bit.v12"
[storage] 2020/03/25 13:14:47 getting last revision of "fluent-bit"
[storage] 2020/03/25 13:14:47 getting release history for "fluent-bit"
[kube] 2020/03/25 13:14:47 Doing get for ConfigMap: "fluent-bit-config"
[kube] 2020/03/25 13:14:47 Doing get for ServiceAccount: "fluent-bit"
[kube] 2020/03/25 13:14:47 Doing get for ClusterRole: "fluent-bit"
[kube] 2020/03/25 13:14:47 Doing get for ClusterRoleBinding: "fluent-bit"
[kube] 2020/03/25 13:14:47 Doing get for DaemonSet: "fluent-bit"
[kube] 2020/03/25 13:14:47 get relation pod of object: log/ConfigMap/fluent-bit-config
[kube] 2020/03/25 13:14:47 get relation pod of object: log/ServiceAccount/fluent-bit
[kube] 2020/03/25 13:14:47 get relation pod of object: /ClusterRole/fluent-bit
[kube] 2020/03/25 13:14:47 get relation pod of object: /ClusterRoleBinding/fluent-bit
[kube] 2020/03/25 13:14:47 get relation pod of object: log/DaemonSet/fluent-bit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e315f]

goroutine 721 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c01c60, 0xc00015b200, 0xc00015b200, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:925 +0x26f
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc000442e60, 0xc0004aa9a0, 0xc0008d0f90, 0x14e1368, 0xc000000020, 0x1a666f0)
        /go/src/k8s.io/helm/pkg/kube/client.go:1105 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc0004aa9a0, 0x0, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:367 +0xd1
k8s.io/helm/pkg/kube.batchPerform.func1(0xc000304360, 0xc0007857d0, 0xc000897540, 0xc0004aa9a0)
        /go/src/k8s.io/helm/pkg/kube/client.go:753 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
        /go/src/k8s.io/helm/pkg/kube/client.go:752 +0xb8

```

The error persists when forcing the Tiller Pod to another node so it looks like an application issue. After downgrading Helm CLI and Tiller to v2.16.3 the deployment upgrade succeeds without any issues. The error returns after upgrading to v2.16.4 again.  This issue occured on one of two clusters only at the moment and as far as I can tell right now only one deployment is affected (which is enough to let the deployment pipeline fail…).

There are no resource limits configured for Tiller and the Linux kernel does not show any OOM.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.4", GitCommit:"5e135cc465d4231d9bfe2c5a43fd2978ef527e83", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `kubeadm`

**Comment by nickdgriffin** [comment] 2020-03-25 15:43
Beat me to the punch! I think this change introduced it, but I haven't figured out how yet: https://github.com/helm/helm/pull/7785

For us seems to only occur when the release in question has Pods in the same namespace Tiller is in, and can be easily reproduced outside of an upgrade by running "helm status" on the release (which is what is actually failing in the upgrade I believe). We have other releases that are deploying into adjacent namespaces which are absolutely fine.

**Comment by bacongobbler** [comment] 2020-03-25 19:47
can you try #7810 and see if that resolves the issue?

**Comment by bacongobbler** [comment] 2020-03-25 19:52
It might be something else in #7785 that may be causing this issue. cc'ing @mattfarina in case he has any ideas. It's possible that the input to `getSelectorFromObject` changed, and now the selectors are `nil`.

**Comment by technosophos** [comment] 2020-03-27 22:09
I'm taking a look at this.

@stephan2012 Can you drop in the contents of `spec.selector` for your DaemonSet named `fluent-bit`?

@nickdgriffin Can you drop in the contents of `spec.selector` for your Deployment named `chartmuseum-chartmuseum`?

**Comment by technosophos** [comment] 2020-03-27 22:55
I cannot reproduce against `dev-v2`. Here's what I tried:

- Create a new Kubernetes 1.17 cluster using Kind
- Install Helm 2 locally
- `helm repo update`
- Run `kubectl create ns dev`
- `helm init --service-account tiller --tiller-namespace dev`
- `helm install stable/chartmuseum --name chartmuseum --namespace foo --tiller-namespace dev`
- `helm status --namespace dev chartmuseum`
- `helm upgrade --install chartmuseum stable/chartmuseum --namespace dev --atomic --set foo=bar --tiller-namespace dev`

And then, just to make sure the case wasn't only manifesting on `upgrade --install`, I tried:

- `helm2 upgrade --install chartmuseum2 stable/chartmuseum --namespace dev --atomic --set foo=bar --tiller-namespace dev`
- `helm2 upgrade --install chartmuseum2 stable/chartmuseum --namespace dev --atomic --set foo=bar2 --tiller-namespace dev`

Tiller did not crash at all.

So I'll need more info to debug.

**Comment by technosophos** [comment] 2020-03-27 23:19
Update: I also ran this against 2.16.5 to see if the error was there, and could not reproduce with that version of Tiller, either.

**Comment by stephan2012** [comment] 2020-03-28 10:15
> @stephan2012 Can you drop in the contents of `spec.selector` for your DaemonSet named `fluent-bit`?

Sure, here it is:

```yaml
spec:
  selector:
    matchLabels:
      app: fluent-bit
      release: fluent-bit
```

**Comment by seeruk** [comment] 2020-03-30 10:00
I've just hit this with 2.16.5, downgrading to 2.16.3 and everything is fine. In my case, I'm running Helm as part of an automation script to install / upgrade a bunch of stuff in my cluster. I get to upgrading Istio and it fails (after succeeding with 2 other apps):

```
Release "istio-init" has been upgraded.
Error: transport is closing
```

**Comment by nickdgriffin** [comment] 2020-03-30 12:09
@technosophos :
Certainly, here it is:
```
spec:
  selector:
    matchLabels:
      app: chartmuseum
      release: chartmuseum
```
We also had it with two DaemonSets:
```
spec:
  selector:
    matchLabels:
      app: datadog-agent-datadog
```
```
spec:
  selector:
    matchLabels:
      app: kube2iam
      release: kube2iam
```

**Comment by mattfarina** [comment] 2020-03-30 13:46
@technosophos Can you make sure to test against Kubernetes 1.15. This appears to be the Kubernetes version where it was reported from. I've found issues in 1.15 that do not show up in 1.16 or newer around this.

**Comment by mattfarina** [comment] 2020-03-30 15:26
@stephan2012 @nickdgriffin @seeruk and anyone else experiencing this... can you please test #7840.

Note, I am unable to replicate this. I've tried on 1.15 and in various ways. This PR is based on cases where the object would not be available.

**Comment by nickdgriffin** [comment] 2020-03-30 19:16
> @technosophos Can you make sure to test against Kubernetes 1.15. This appears to be the Kubernetes version where it was reported from. I've found issues in 1.15 that do not show up in 1.16 or newer around this.

Except I'm on 1.13.12, so the issue is present there too.

> @stephan2012 @nickdgriffin @seeruk and anyone else experiencing this... can you please test #7840.

I'll see if I can find time to this week.

**Comment by technosophos** [comment] 2020-03-30 22:03
I reviewed the code @mattfarina produced, and will merge it as soon as I can get confirmation that it fixes the issue

**Comment by technosophos** [comment] 2020-03-30 22:22
@nickdgriffin @stephan2012 Okay, we're still hunting this down. Do you happen to have the `apiVersion` fields on the failed Deployment and DaemonSet objects? We are checking whether this is an API conversion failure (which is why it would show up only on very specific combinations of Helm and Kubernetes).

**Comment by stephan2012** [comment] 2020-03-31 07:06
> @stephan2012 @nickdgriffin @seeruk and anyone else experiencing this... can you please test #7840.

@mattfarina: I had trouble to compile from source yesterday. Will provide the apiVersion shortly.

**Comment by stephan2012** [comment] 2020-03-31 09:23
> @nickdgriffin @stephan2012 Okay, we're still hunting this down. Do you happen to have the `apiVersion` fields on the failed Deployment and DaemonSet objects? We are checking whether this is an API conversion failure (which is why it would show up only on very specific combinations of Helm and Kubernetes).

@technosophos:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: "2020-03-20T20:07:35Z"
  generation: 1
  labels:
    app: fluent-bit
    chart: fluent-bit-0.4.7
    heritage: Tiller
    release: fluent-bit
  name: fluent-bit
  namespace: log
```

**Comment by nickdgriffin** [comment] 2020-03-31 10:30
> @nickdgriffin @stephan2012 Okay, we're still hunting this down. Do you happen to have the `apiVersion` fields on the failed Deployment and DaemonSet objects? We are checking whether this is an API conversion failure (which is why it would show up only on very specific combinations of Helm and Kubernetes).

@technosophos:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  labels:
    app: chartmuseum
    chart: chartmuseum-1.8.4
    heritage: Tiller
    release: chartmuseum
  name: chartmuseum-chartmuseum
  namespace: tooling
```
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: datadog-agent-datadog
    chart: datadog-1.32.1
    heritage: Tiller
    release: datadog-agent
  name: datadog-agent-datadog
  namespace: tooling
```

**Comment by jchomat** [comment] 2020-03-31 13:08
Hey,

Just facing this issue when upgrading to 2.16.5 :

apiVersion: extensions/v1beta1 for my deployment.
rolling back to 2.16.3 solved my problem

Hope it can help !

**Comment by mattfarina** [comment] 2020-04-02 14:34
This has been a problem for us to duplicate to fix. Can anyone experiencing this please test https://github.com/helm/helm/pull/7840 and see if it provides a fix.

**Comment by mattfarina** [comment] 2020-04-02 14:35
Note, the developer guide for v2, including compiling and running tiller locally to test, can be found at https://v2.helm.sh/docs/developers/.

**Comment by kingdonb** [comment] 2020-04-02 16:56
@mattfarina This looks like the issue we've seen in teamhephy/workflow#115 new users reporting, affects 2.16.x latest and results in `transport is closing` due to SIGSEGV exactly as it appears in the initial report here. I plan on testing #7840 later today or tomorrow, thanks @bacongobbler for helping us make this connection.

**Comment by technosophos** [comment] 2020-04-02 18:19
That would be great! Please keep us posted on what you discover. We've collectively spent many hours trying to reproduce, track down and fix this, and we're just flummoxed.

**Comment by kingdonb** [comment] 2020-04-02 23:35
"The repro was already inside of the house!" I am not sure why this affected workflow and not much else, glad to be of service...

I can confirm 88e95b0d solves the issue (my fork at kingdonb/helm has this in a merge commit at 26aa1d44, and pushed to `kingdonb/helm:26aa1d44` to use with `--tiller-image`)

Was definitely able to reproduce the crash on v2.16.5, with:

```
$ helm repo add hephy https://charts.teamhephy.com
$ helm repo update
$ helm upgrade --install hephy hephy/workflow --namespace deis --set global.use_rbac=true
Release "hephy" does not exist. Installing it now.
NAME:   hephy
Error: transport is closing
```

It actually seems to process the release, in spite of the error message, but it's not clear what else might have gone wrong based on the output and SIGSEGV.

With the new helm client binary and upgrade tiller to matching image,

```
$ helm upgrade --install hephy hephy/workflow --namespace deis --set global.use_rbac=true
Release "hephy" does not exist. Installing it now.
NAME:   hephy
LAST DEPLOYED: Thu Apr  2 19:15:53 2020
NAMESPACE: deis
STATUS: DEPLOYED
```

... it works again! That was probably my first time ever building helm from source! Except for maybe, indirectly via helm operator. 🍻

**Comment by vindvaki** [comment] 2020-04-09 21:29
@mattfarina 
> This has been a problem for us to duplicate to fix. Can anyone experiencing this please test #7840 and see if it provides a fix.

I believe this caught by our tests while we were looking to upgrade to helm 2.16.5, see all the failures under [this MR](https://gitlab.com/gitlab-org/cluster-integration/auto-deploy-image/-/merge_requests/63).

I set up a [base image with @mattfarina's patch](https://gitlab.com/hfyngvason/helm-install-image) and ran them [against a fork](https://gitlab.com/hfyngvason/auto-deploy-image/pipelines/134577836) and the tests do seem to be passing now.

**Comment by technosophos** [comment] 2020-04-10 00:50
Thanks for the confirmation!

**Comment by bacongobbler** [comment] 2020-04-14 19:22
#7840 has been merged. Closing!

**Closed by bacongobbler** 2020-04-14 19:22 UTC
Labels: bug, v2.x

**Comment by stephan2012** [comment] 2020-04-15 15:12
Thanks for addressing this issue!
