### ISSUE TITLE
how to correctly configure local sub charts with Helm 3.4.0

### ISSUE THREAD

**Issue by dastrobu** [helm/helm#8955] opened 2020-10-29 13:55 UTC
Given a chart with two subcharts with the following structure

```
charts/
 + local-subchart
 + fetched-subchart
Chart.yaml
```
I am not sure how the `dependencies` section in the `Chart.yaml` should look like. 
Up to Helm < 3.4.0 I used
```
dependencies:
  - name: "fetched-subchart"
    version: "1.2.3"
    repository: "@my-repo"
```
simply ignoring the local-subchart, which should not be fetched from any repo. 
Now, Helm 3.4.0 complains when linting this chart.
```
chart metadata is missing these dependencies: local-subchart
``` 

So I added this chart to the dependencies, giving
```
dependencies:
  - name: "local-subchart"
    version: "1.2.3"
  - name: "fetched-subchart"
    version: "1.2.3"
    repository: "@my-repo"
```

This fixes the linting. However, running `helm dependency update` gives an error: 

```
Getting updates for unmanaged Helm repositories...
Error: could not find protocol handler for: 
```

So I am a bit confused. What is the proposed way of configuring subcharts? 

The docs in https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#creating-a-subchart might need some updates on this as well. 

Output of `helm version`:

version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

**Comment by bacongobbler** [comment] 2020-10-29 15:00
duplicate of https://github.com/helm/helm/issues/8940 which will be fixed in Helm 3.4.1.

**Closed by bacongobbler** 2020-10-29 15:00 UTC

**Comment by bacongobbler** [comment] 2020-10-29 15:02
the short answer is that you're doing it right. There's a bug in Helm 3.4.0 causing this error due to an uncaught case. A patch has been applied and we will release Helm 3.4.1 with a fix.

**Comment by bbobrov** [comment] 2021-01-05 10:14
I think that this bug has not been fixed. The fix by @mattfarina handles the case when the dependency is declared without `repository`, but does not handle the case when local subchart is used without any entry in `dependencies`.

I am still getting linting error when i have a simple subchart in `charts/`:
```
$ ./linux-amd64/helm lint mainch                         
==> Linting mainch
[ERROR] /home/bbobrov/src/mainch: chart metadata is missing these dependencies: subch

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Comment by rvernaeshv** [comment] 2021-01-08 21:17
I'm using Helm v3.4.2 and still have this issue.

**Comment by antoniocascais** [comment] 2021-01-11 13:44
Same here.

**Comment by dastrobu** [comment] 2021-01-18 11:01
still an issue with v3.5.0. However, there is an easy workaround now, since `helm dependency update` will now work when adding the unmanaged dependencies to the `Chart.yaml`. So the fix for my original example would be to add to the `Chart.yaml` dependencies section: 
```
dependencies:
  - name: "local-subchart"
    version: "1.2.3"
  - name: "fetched-subchart"
    version: "1.2.3"
    repository: "@my-repo"
```
While this failed in v3.4.0 when doing `helm dependency update`, it works since v3.4.1. 

According to https://github.com/helm/helm/issues/8955#issuecomment-718812366 and https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#creating-a-subchart it should not be required to add stand-alone chart to the dependencies section of the `Chart.yaml`. 

@bacongobbler I would suggest to re-open this issue, or would you prefer creating a new one, since this one is closed already and won't receive any attention from the maintainers.

**Comment by mattfarina** [comment] 2021-01-19 18:30
I was asked about having unmanaged dependencies not being listed in the `dependencies` field. It does not look like that will be easily possible. The `dependencies` property is used in numerous places (e.g., the install process). This is not a simple change. Helm intends to have all dependencies listed in the `dependencies` property, for packaged charts to have the dependencies in the `charts` directory, and for dependent charts to be in the `charts` directory when operations that install occur.

Chart archives, for example, can be pulled from their original location and put into a new location (e.g., vendored or cached). Someone should be able to take that archive, extract it, update dependencies or otherwise modify it, and then use it. This is useful for some organizational use cases.

**Comment by dastrobu** [comment] 2021-01-19 18:43
@mattfarina thanks for clarifying. If I understood you correctly, the proposed workaround is actually the way Helm is supposed to work now (which is fine for me). Still, the documentation should reflect the requirement to always add any dependency to the `Chart.yaml` regardless where it comes from.
