### ISSUE TITLE
helm values file keys should consider flat keys case (parent.key) 

### ISSUE THREAD

**Issue by blabadi** [helm/helm#5803] opened 2019-05-27 20:07 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
openstack

Description:

using `image.tag: 0.0.1` in the values file with the command `helm upgrade -f new-values.yaml .. ` didn't   override the default in the chart values.yaml, and treated each value as different one.

but when I changed it to the following it worked and computed values correctly
```
image:
  tag: 0.0.1
```

**Comment by bacongobbler** [comment] 2019-05-29 16:00
This seems like the intended behaviour. I'm fairly certain that `image.tag` is considered a unique key, and as such isn't equivalent to the latter form.

Closing as working as intended.

**Closed by bacongobbler** 2019-05-29 16:00 UTC
