### ISSUE TITLE
Helm upgrade not working as expected

### ISSUE THREAD

**Issue by roshan-mr** [helm/helm#2735] opened 2017-07-28 09:09 UTC
`Hi,`

I am trying to upgrade one of my packages. But the changes which I  have made in the "deployment.yaml" template in the chart is not there after the upgrade. I added the following lines in the spec of my kubernetes deployment.yaml file
```
spec:
     containers:
     - env:
        - name: LOGBACK_DB_ACQUIRE_INCREMENT
           value: "1"
        - name: LOGBACK_DB_MAX_IDLE_TIME_EXCESS_CONNECTIONS
           value: "10"
        - name: LOGBACK_DB_MAX_POOL_SIZE
           value: "2"
        - name: LOGBACK_DB_MIN_POOL_SIZE
           value: "1"
```
I tried upgrading using the following command

**helm upgrade ironic-molly spring-app-0.1.2.tgz --recreate-pods**

Where "**ironic-molly**" is the release-name and **spring-app-0.1.2.tgz** is my chart with changes.

Helm output says that the package is upgraded , but the changes which i have made is missing in the deployment.yaml . What might be causing this issue.?

Regards,
Muhammed Roshan

**Comment by jascott1** [comment] 2017-08-02 08:23
Hi @roshan-mr,

Thanks for bringing this issue to our attention. Could you please post your Helm and Kubernetes versions so we can make sure we are testing the correct versions?

**Comment by r7vme** [comment] 2017-08-03 11:20
We are experiencing the same behaviour.

### Description

Changed `imagePullSecrets` in template `cluster-service-chart/templates/deployment.yaml`  (not variable)
```
      imagePullSecrets:
      - name: cluster-service-pull-secret
```
then applying new chart with
```
helm upgrade -f some_values.yaml --install cluster-service <NEW_CHART>
```
`helm get cluster-service` shows new deployment, but

### Expected:
`kubectl get deploy/cluster-service -o yaml` will show new imagePullSecrets value

### Actual:
`kubectl get deploy/cluster-service -o yaml` shows old imagePullSecrets value. And whole deployment looks old.

### Version
```
helm version                                                           
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by matthewrj** [comment] 2017-11-10 04:26
We are experiencing similar behaviour.

When changing the image hash in the deployment template:
- helm upgrade succeeds
- tiller manifest shows the new image hash
- kubectl describe shows the old image hash
- the deployment is not updated

```
Client: &version.Version{SemVer:"v2.6.2", GitCommit:"be3ae4ea91b2960be98c07e8f73754e67e87963c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Kubernetes version: 1.8.1-gke.1
```

**Comment by phillydogg28** [comment] 2017-11-10 18:57
We are see the same issue as @matthewrj. It worked with multiple deploys yesterday, but this morning will not deploy. `helm get <deployment> manifest` shows the correct yaml file. We were able to change another item in our template, deployed again and it worked. Not sure why the first update didn't deploy, but changed manifest in helm. 

```
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.6.0", GitCommit:"5bc7c619f85d74702e810a8325e0a24f729aa11a", GitTreeState:"clean"}
```

**Comment by msavlani** [comment] 2017-11-18 02:20
I tested this on latest 2.7.1 and i still see same issue as @phillydogg28

**Comment by matthewrj** [comment] 2017-11-18 21:37
I discovered the issue was we somehow had got into a state where we had 4 releases with the same name. Deleting all of the duplicate releases and recreating the original fixed the problem. Although we have got into the duplicate release state multiple times now.

**Comment by phillydogg28** [comment] 2018-01-15 17:48
@matthewrj Did you find those releases with `helm list`? I checked mine and we do not have duplicate deployments. The issue is the only way we have found to fix the issue is to `helm delete --purge <deployment>` then release it again. This isn't ideal for our production workloads as it causes downtime.

**Comment by bacongobbler** [comment] 2018-01-15 23:06
I believe this issue was fixed via https://github.com/kubernetes/helm/pull/3335 along with some changes made in v2.7.1 via #3097. Can y'all give v2.7.2 or v2.8.0-rc1 a shot and see if that fixes things? Thanks!

**Comment by NathanJiangCS** [comment] 2018-01-29 15:40
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```
Still seeing the same problem as @phillydogg28 and @matthewrj even on v2.7.2. 

We have an already successful release. When attempting to change the image hash of the deployment, the helm upgrade succeeds and the tiller manifest is changed, yet the kubernetes deployment itself is not updated and it is still using the old hash. 

I tried using the `--force` flag; however, that only seems to recreate the pods and not the deployment itself.

**Comment by gauravarora** [comment] 2018-02-22 07:56
I'm also seeing this. `helm get` shows correct output but deployment is never updated.

**Comment by gak** [comment] 2018-03-19 03:53
I'm getting this too.

**Comment by pvalsecc** [comment] 2018-04-18 11:46
Same here when changing an environment variable. With helm 2.8.1

**Comment by bacongobbler** [comment] 2018-04-20 14:25
We still haven't identified the underlying issue that's causing this... Typically we only escalate to a bug once someone has actually pinpointed how to reproduce the problem.

If someone can provide some steps to reproduce this with a public chart that would be helpful to diagnose the issue. Thanks!

**Comment by Strandedpirate** [comment] 2018-04-25 08:58
Easy to duplicate with https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress deployed to an Azuer ACS engine version of Kubernetes and tied to a static load balancer IP.

What I've been seeing for the last 8 months is that any k8s resource "tied" into Azure through the ACS engine will NOT be updated by helm during deployment regardless if the values.yaml has changed or if the checksum annotation's hash mutates. In this case an Azure load balancer is spun up and the static IP assigned.

**custom-values.yaml**
```
controller:
  ingressClass: "common-ingress"
  electionID: "ingress-controller-leader-common"

  service:
    loadBalancerIP: "13.84.132.232"
    externalTrafficPolicy: "Local"

  kind: "DaemonSet"

  # changes to the cpu or memory and re-deploying succeeds but the definition is not actually updated
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
```

`helm upgrade -i live-nginx-ingress-zipkin mycompany/nginx-ingress --namespace live --set environment=live  --values custom-values.yaml`


Note the up-time of these controllers are 39+ days even though I just deployed which means they were not updated even though helm claims they were.
```
kubectl -n live get po

live-nginx-ingress-common-nginx-ingress-controller-6dkds          1/1       Running   135        40d
live-nginx-ingress-common-nginx-ingress-controller-8npgm          1/1       Running   44         39d
live-nginx-ingress-common-nginx-ingress-controller-l5p68          1/1       Running   6          39d
live-nginx-ingress-common-nginx-ingress-controller-scqrs          1/1       Running   10         39d
live-nginx-ingress-common-nginx-ingress-default-backend-99dnhp8   1/1       Running   0          45m
live-nginx-ingress-zipkin-nginx-ingress-controller-lcsbh          1/1       Running   3          40d
live-nginx-ingress-zipkin-nginx-ingress-controller-nf8jr          1/1       Running   5          39d
live-nginx-ingress-zipkin-nginx-ingress-controller-wthtg          1/1       Running   2          40d
live-nginx-ingress-zipkin-nginx-ingress-controller-wvd22          1/1       Running   2          40d
live-nginx-ingress-zipkin-nginx-ingress-default-backend-9db8hx5   1/1       Running   0          44m
```

Resulting yaml of ingress has not changed. Still contains the old cpu and memory limits.
```
kubectl -n live get po live-nginx-ingress-common-nginx-ingress-controller-6dkds -o yaml

apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 7218e23babc64900ba678c5c348d22347610f2275f1177e0c3d05131f3d9c23e
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"live","name":"live-nginx-ingress-common-nginx-ingress-controller","uid":"7b5c4680-28ca-11e8-a7ff-000d3a73b731","apiVersion":"extensions","resourceVersion":"8215546"}}
  creationTimestamp: 2018-03-16T03:31:15Z
  generateName: live-nginx-ingress-common-nginx-ingress-controller-
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.404.0
    chart-version: 0.404.0
    component: controller
    controller-revision-hash: "3665246960"
    environment: live
    heritage: Tiller
    pod-template-generation: "1"
    project: designer
    provider: mycompany
    release: live-nginx-ingress-common
    release-name: pickle-jiggles
  name: live-nginx-ingress-common-nginx-ingress-controller-6dkds
  namespace: live
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: live-nginx-ingress-common-nginx-ingress-controller
    uid: 7b5c4680-28ca-11e8-a7ff-000d3a73b731
  resourceVersion: "15355150"
  selfLink: /api/v1/namespaces/live/pods/live-nginx-ingress-common-nginx-ingress-controller-6dkds
  uid: 7b836f6e-28ca-11e8-b490-000d3a73bdea
spec:
  containers:
  - args:
    - /nginx-ingress-controller
    - --default-backend-service=live/live-nginx-ingress-common-nginx-ingress-default-backend
    - --election-id=ingress-controller-leader-common
    - --ingress-class=common-ingress
    - --configmap=live/live-nginx-ingress-common-nginx-ingress-controller
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0-beta.19
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: nginx-ingress-controller
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 10254
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 500m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-kh8lr
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: k8s-agent-b9a90342-2
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.alpha.kubernetes.io/notReady
    operator: Exists
  - effect: NoExecute
    key: node.alpha.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: default-token-kh8lr
    secret:
      defaultMode: 420
      secretName: default-token-kh8lr
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-03-16T03:31:15Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-04-25T08:04:03Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-03-16T03:31:18Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8c5496d108185c373f50ce15b06dad1a06e29cc2b21c8f4bb383de4ee1cbe259
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0-beta.19
    imageID: docker-pullable://quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:580bbf70930992897c43a439e1e444ae160320c17c517eaf2fe02fdbbaad56c1
    lastState:
      terminated:
        containerID: docker://d9f99a3e4cd7105ed7d5f80a2b15697140ad9f7b6c3e4d7e8b09f78497b9503e
        exitCode: 137
        finishedAt: 2018-04-25T08:03:56Z
        reason: OOMKilled
        startedAt: 2018-04-25T01:46:17Z
    name: nginx-ingress-controller
    ready: true
    restartCount: 135
    state:
      running:
        startedAt: 2018-04-25T08:03:58Z
  hostIP: 10.240.0.7
  phase: Running
  podIP: 10.244.6.76
  qosClass: Guaranteed
  startTime: 2018-03-16T03:31:15Z

```

**Comment by langecode** [comment] 2018-05-08 07:52
Unfortunately I do not know how to reproduce either. However we see a behaviour that seems to also fit this. `helm get` show something different that is actually applied to Kubernetes - seeing this both for deployment and config-map resources.

**Comment by Lavender-Ding** [comment] 2018-08-02 07:45
I'm also seeing the same issue here, I even did delete all things and releases before, and do uninstall and then install with the new configuration rather than upgrade, but it still apply the old configuration to the new deployment. It worked previously but just suddenly started to not working, and couldn't get it back to work again. I'm using `stable/prometheus-postgres-exporter`.

**Comment by mightwork** [comment] 2018-08-27 16:04
Is there any update on this? We are facing the same while updating our resources via ```helm upgrade``` in our brigade pipeline. The values get updated but the resources remain the same. It's a deal breaker and is preventing us from taking brigade and helm to production. Using ```v2.10.0```

**Comment by AneeshSachdeva** [comment] 2018-08-30 23:25
I'm also facing the same issue when installing the stable/jenkins chart using `v2.10.0`. After the initial installation, the kube resources would not reflect the change in `Agent.resources` after calling `helm upgrade -f values.yaml [RELEASE] stable/jenkins`. Calling `helm get values [RELEASE` showed that the values were correctly set in the chart, however the resources do not reflect the change. I also tried adding the `--force` and `--recreate-pods` options to the `helm upgrade` command however produced the same results (`--force` didn't even recreate the deployment). Lastly, I tried manually deleting the jenkins deployment and then calling update again (with those same options), but that did not work. Without being able to change `Agent.resources`, the Jenkins executer dies with an OOM during every build. 

The solution was to entirely delete the chart and reinstall, but this time having my desired values set in `values.yaml` first. Luckily my org was not reliant on Jenkins before I ran into this problem, otherwise this solution would not have been feasible.

`helm upgrade` performs inconsistently; sometimes updated values propagate all the way down to the resources, and sometimes they don't. It's unclear whether this problem is solely within `helm upgrade`, or if it's chart dependent. However it's clear from this thread that the same problem has appeared for various charts and more investigation should be given.

**Comment by ksemaev** [comment] 2018-09-17 17:31
same with me on helm 2.10.0

> values.yaml

```
node:
  image:
    repository: quay.io/image
    tag: v1
```

> statefulset
```
apiVersion: apps/v1
kind: StatefulSet
...
    spec:
      containers:
      - name: container1
        image: {{ index .Values "node" "image" "repository" }}:{{ index .Values "node" "image" "tag" }}
....
      - name: container2
        image: {{ index .Values "node" "image" "repository" }}:{{ index .Values "node" "image" "tag" }}
```

As the result only one (random) container takes value, the other leaves the old one

**Comment by charlesverdad** [comment] 2018-10-31 04:46
Currently experiencing the same issue as https://github.com/helm/helm/issues/2735#issuecomment-319941359 above
versions: 
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by marcindulak** [comment] 2018-10-31 16:26
Maybe related, a self-contained example with kubernetes-dashboard is provided https://github.com/helm/helm/issues/3030

**Comment by iomv** [comment] 2018-11-05 16:06
I am finding myself in the same situation at the moment: when I decided to switch to helm I had a service and deployment configuration applied to my cluster, I then created my own chart that was targeting that very set of service and deployment.
When I had to install it, after reading the docs I opted for the command:
```
helm upgrade --install --force $SERVICE_NAME  $SERVICE_NAME/ -f configs/$SERVICE_NAME/env-configs/dev_config.yml --tls
```
This created the new release with the name I provided, deleted all pods that were running and redeployed them via tiller. 
So far so good, only thing is that when manually changing a resource via the k8s api with `kubectl` - deployment config for example, changing the replicas - helm does not show that the resource has been changed.

Furthermore, as someone stated above, if I do `helm get $SERVICE_NAME` the result is what the original release was, as I would expect, but no matter what command I use, helm won't rollback to the original "source of truth".

**Comment by alexfre** [comment] 2018-11-29 14:49
DaemonSet updates might be related to updateStrategy.type=OnDelete

`kubectl get ds <DS-NAME> -o go-template='{{.spec.updateStrategy.type}}{{"\n"}}'`

See https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

**Comment by YannickteK** [comment] 2019-01-18 15:58
I'm also having this isssue with the keycloak chart. This pretty much breaks helm, making it unusable. At the moment I would advise to not use helm in production. 

Is there a way to get some logs from helm/tiller to provide some more insight?

**Comment by ClementGautier** [comment] 2019-01-21 15:03
Hello there, I'm facing the same issue on v2.12.2.

Is there any known workaround? 
Like, would it be possible to pipe helm get into kubectl apply?

**Comment by ClementGautier** [comment] 2019-01-21 15:23
Thanks, I managed to have a "maybe" safer way by piping helm get in a file, removing the release info on top and applying whats left with kubectl. That kills the whole concept of helm tho :cry:

**Comment by elpadrinoIV** [comment] 2019-02-02 22:39
Same problem here. With `--debug`, the deployment output is correct but `kubectl get deployment -o yaml` shows another thing. Also `helm manifest` shows the expected deployment yaml, but not the one deployed in the k8s cluster.

```
$ helm version
Client: &version.Version{SemVer:"v2.12.2", GitCommit:"7d2b0c73d734f6586ed222a567c5d103fed435be", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

K8s cluster deployed on premise.

**Comment by docteurklein** [comment] 2019-02-18 10:14
careful with `helm template | kubectl apply` because if you have hooks defined, they will be executed as well. (you don't want a rollback job to be executed during an upgrade for example).

**Comment by adharmawan** [comment] 2019-05-24 10:43
```sh
$ helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

Purposely made `helm upgrade` failed by pointing `Deployment` to a non-existent `ConfigMap`.
```yaml
apiVersion: apps/v1
kind: Deployment
...
        envFrom:
          - configMapRef:
              name: templateapi-env1                # non-existent
          - secretRef:
              name: templateapi-secrets
...
```


Even after reverting the commit, and did `helm upgrade` again, it still failed. When I checked the deployment. It is still looking for the non-existent `ConfigMap`. Can't even rollback to last `DEPLOYED` release.

**Comment by adharmawan** [comment] 2019-05-27 04:18
Found a prevention mechanism. The key is to never run `helm upgrade` if latest release is in `FAILED` state. So, let's say your latest release is in `DEPLOYED` state and then you merge a bad PR and run `helm upgrade` causing it to fail. Before you revert the PR and run `helm upgrade` again (roll-forward), do a `helm rollback` to the last DEPLOYED release first and then run `helm upgrade`.

**Comment by KadenLNelson** [comment] 2019-06-04 04:02
Very Sad 😢

**Comment by KadenLNelson** [comment] 2019-06-04 04:12
I was having this issue in the 3.0.0-alpha1 release but solved by installing Helm 2.14.0

**Comment by hlascelles** [comment] 2019-06-06 12:25
We are seeing this with non-errored `DEPLOYED` releases being upgraded with a change in values. Helm says all went well, but the DaemonSet was not updated. Specifically, this was via Weaveworks Flux (some Google keywords there for anyone looking for this problem), and we spent some time thinking it was that that was not pushing on changes.

```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment] 2019-08-14 21:36
consolidating this into #5915. Helm 3 recently has implemented a three-way merge patch strategy which should alleviate some of the issues here. Please follow up with that ticket so we can keep the conversation relevant and all in one place. Thanks!

**Closed by bacongobbler** 2019-08-14 21:36 UTC
Labels: question/support

**Comment by illyaMs** [comment] 2019-11-19 12:29
Not a fair decision IMHO to close this 2.x.x related issue with "see ya in 3.0" resolve message:
1. All the cases here are related to 2.x.x, and I'm far from thinking that everyone is OK to apply this migration right away
2. People using the 2.x.x may search for opened issues and find nothing (though this one still exists in almost all 2.x.x version of helm, at least according to the discussion thread).

@bacongobbler could you please reopen the issue, in order to make the it's state relevant and the issue itself transparent to all people coming to the repo page?

**Comment by KadenLNelson** [comment] 2019-11-20 18:30
> Not a fair decision IMHO to close this 2.x.x related issue with a "see ya in 3.0" resolve message:
> 
> 1. All the cases here are related to 2.x.x, and I'm far from thinking that everyone is OK to apply this migration right away
> 2. People using the 2.x.x may search for opened issues and find nothing (though this one still exists in almost all 2.x.x version of helm, at least according to the discussion thread).
> 
> @bacongobbler could you please reopen the issue, in order to make the it's state relevant and the issue itself transparent to all people coming to the repo page?

I don't think reopening the issue is the appropriate solution here. https://github.com/helm/helm/issues/5915 should be updated to say

```
...
This issue is meant to consolidate is #1844, #3933, and #2735.
```

> 2. People using the 2.x.x may search for opened issues and find nothing (though this one still exists in almost all 2.x.x version of helm, at least according to the discussion thread).

That's the point of the new issue, to group up common issues like this one into #5915. People can still find this issue via google/closed-issues and see the reference to #5915 and continue the discussion there.

**Comment by illyaMs** [comment] 2019-11-21 07:17
@KadenLNelson ok, so do I get it right that #5915 will stay open till we get to a root cause/fix for helm 2.x.x? I mean I agree it makes sense to keep some entry point for these similar `misbehaving upgrade` issues; just not a fan of resolving all of them via `fixed in helm 3.0.0`.

**Comment by KadenLNelson** [comment] 2019-11-21 18:39
> till we get to a root cause/fix for helm 2.x.x?
If that ever happens, this is a community driven project, and most of the resources are going towards making Helm3 a better product and not towards providing backwards compatibility support for Helm2.

**Comment by GloriaPG** [comment] 2020-06-18 22:12
I have had several problems using helm upgrade, including this one, I recommend that you avoid using it, Helm is good for installing a component but not for maintenance.
At the moment I don't know how to solve this, that I don't update my Kubernetes kinds.  In my case the client already has everything designed to use it in this way, I hope we change that soon.
Someone here found a solution? Thanks so much!

**Comment by bacongobbler** [comment] 2020-06-18 22:16
@GloriaPG can you please share what issues you are experiencing, optimally in a new ticket? We need test cases to help verify whether you found a bug, and if we need to clarify something in the documentation or if there's something else we can do to help.

**Comment by GloriaPG** [comment] 2020-06-18 22:19
> @GloriaPG can you please share what issues you are experiencing, optimally in a new ticket? We need test cases to help verify whether you found a bug, and if we need to clarify something in the documentation or if there's something else we can do to help.

Sure, I will, thanks for your reply.
