### ISSUE TITLE
helm upgrade with tests fail when --atomic flag is set

### ISSUE THREAD

**Issue by Zeltserj** [helm/helm#9959] opened 2021-07-20 13:44 UTC
Hi,
I have a chart and a test container (put in `templates/tests/test.yaml`), which looks like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: {{ .Release.Name }}-test
      image: busybox
      command: ["echo","hello, world!"]
  restartPolicy: Never
```
My command:
```
helm upgrade my-release my-chart --atomic 
```

I see that the pod `my-release-test` is Completed, and therefore helm waits for it to be Ready, which does not happen until timeout, and the the upgrade rolls back.
 
running `helm upgrade my-release my-chart && helm test my-release` works.

I think the correct behavior should be that `--atomic` should only fail if the test pod failed.

helm version:
```
version.BuildInfo{Version:"v3.3", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.2"}
```

**Comment by hickeyma** [comment] 2021-07-22 06:49
@Zeltserj I am trying to reproduce the issue. I did the following:

1. Generated a scaffold chart using `helm create`.
2. Installed it 
3. Ran `helm test` on it
4. Did upgrade: `helm upgrade mychart mychart --atomic `
5.  I did not get a timeout or rollback

``` console
$ helm ls -A 

NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART        	APP VERSION
mychart	helm-test	2       	2021-07-22 07:40:22.448285 +0100 IST	deployed	mychart-0.1.0	1.16.0 

$ kubernetes get all

NAME                           READY   STATUS      RESTARTS   AGE
pod/mychart-76677cc888-nl5bn   1/1     Running     0          15m
pod/mychart-test-connection    0/1     Completed   0          40s

NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/mychart   ClusterIP   172.21.20.203   <none>        80/TCP    15m

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mychart   1/1     1            1           15m

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/mychart-76677cc888   1         1         1       15m
```

Maybe I am missing something. Would you be able to provide more information to help troubleshoot it further?

**Comment by Zeltserj** [comment] 2021-07-22 10:59
Are you sure you reverted to the v3.3? While reproducing your steps I still encountered the issue, which is not occurring in v3.5.4
running with `--debug` flag:

```
wait.go:225: [debug] Deployment is not ready: default/tokenizer. 1 out of 2 expected pods are ready
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
wait.go:181: [debug] Pod is not ready: default/mytest-pod
 ...
```

eventually it time outs with upgrade failed


My team will upgrade to v3.5.4.

**Comment by bacongobbler** [comment] 2021-07-22 14:07
Closing as it appears this was fixed in an update. Please upgrade.

**Closed by bacongobbler** 2021-07-22 14:07 UTC
Labels: question/support

**Comment by hickeyma** [comment] 2021-07-22 14:20
@Zeltserj I am using the latest 3.6.3. So, it looks like it is working because of an update since as @bacongobbler. Can you test with the latest when you get a chance and let us know?
