### ISSUE TITLE
Manifests with hooks not getting deleted during helm uninstall

### ISSUE THREAD

**Issue by tomcruise81** [helm/helm#9206] opened 2021-01-07 19:14 UTC
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-04-23T19:49:32Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openshift

I'm trying to facilitate the ability to work with `PodDisruptionBudget` in my chart, and have run into a few things.

1. A `PodDisruptionBudget` in older versions of Kubernetes/Openshift is immutable, and results in the need to do something like https://github.com/kubernetes/kubernetes/issues/45398#issuecomment-478619253:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "app.name" . }}
  release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "post-upgrade, post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
```
2. I've made sure that `"helm.sh/resource-policy": keep` isn't being set
3. Not sure if it's strictly tied to the hooks, but when running `helm uninstall`, the `PodDisruptionBudget` is **NOT** deleted

I feel like I'm missing something obvious about the hooks and how they should be used that's preventing this from deleting successfully, but I can't seem to find any documentation to this effect.

**Comment by tomcruise81** [comment] 2021-01-07 22:29
Tracing things back through the code, I'm guessing `helm uninstall`:

1. Collects the manifests and then sorts them - https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/action/uninstall.go#L180
2. Filters out things that shouldn't be uninstalled - https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/action/uninstall.go#L189

Looking at the [`filterManifestsToKeep`](https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/action/resource_policy.go#L28-L42) method, if I'm not mistaken, there's at least one possibility for manifests to be lost (i.e. not included in either of the returned slices). For instance, if `resourcePolicyType != kube.KeepPolicy`

Maybe I'm misunderstanding this method, shouldn't it end with:
```golang
		...
		resourcePolicyType = strings.ToLower(strings.TrimSpace(resourcePolicyType))
		if resourcePolicyType == kube.KeepPolicy {
			keep = append(keep, m)
			continue
		}

		// Catch-all
		remaining = append(remaining, m)
	}
	return keep, remaining
}
```

Not sure that this is my problem, since my generated manifests don't include the [`helm.sh/resource-policy`](https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/kube/resource_policy.go#L20)

```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    helm.sh/hook: 'post-upgrade, post-install'
    helm.sh/hook-delete-policy: before-hook-creation
    mde/app-version: 0.0.33
    mde/deploy-stage: Sbx
    mde/project-key: JLT
    mde/project-name: Jenkins Library Testing
    mde/repo-name: horizontal-pod-autoscaling-and-pod-disruption-budget
    meta.helm.sh/release-name: rolling-horizontal-pod-autoscaling-and-pod-d-8250fb1a
    meta.helm.sh/release-namespace: jlt-sbx
```

**Comment by tomcruise81** [comment] 2021-01-08 14:19
I guess this all currently boils down to https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle#hook-resources-are-not-managed-with-corresponding-releases

> ## Hook resources are not managed with corresponding releases
> The resources that a hook creates are currently not tracked or managed as part of the release. Once Helm verifies that the hook has reached its ready state, it will leave the hook resource alone. Garbage collection of hook resources when the corresponding release is deleted may be added to Helm 3 in the future, so any hook resources that must never be deleted should be annotated with `helm.sh/resource-policy: keep`.
> Practically speaking, this means that if you create resources in a hook, you cannot rely upon `helm uninstall` to remove the resources. To destroy such resources, you need to either add a custom `helm.sh/hook-delete-policy` annotation to the hook template file, or set the time to live (TTL) field of a Job resource.

Unfortunately, I'm not seeing a combination of `helm.sh/hook-delete-policy` options that will both:

1. Allow for the manifest to be created via:
```yaml
    helm.sh/hook: 'post-upgrade, post-install'
    helm.sh/hook-delete-policy: before-hook-creation
```
2. Allow it to be deleted via:
```yaml
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
```

**Comment by tomcruise81** [comment] 2021-01-08 15:33
Seems similar to https://github.com/helm/helm/pull/7948. Basically, between splitting and sorting manifests -
https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/action/uninstall.go#L179-L180

the manifests associated with hooks would need to be added into the `manifests` slice.

The question that brings up is how does a `post-delete` hook get get handled?

**Comment by tomcruise81** [comment] 2021-01-08 16:41
Nevermind...

https://github.com/helm/helm/blob/6297c021cbda1483d8c08a8ec6f4a99e38be7302/pkg/releaseutil/manifest_sorter.go#L158-L196

Sorting is filtering out any manifests that include a hook. So even if the manifests with hooks are included in the manifests `map`, they won't get included in the sorted manifests `files` slice.

**Comment by tomcruise81** [comment] 2021-01-19 20:55
@bacongobbler - I created a PR to hopefully address this. Anything else that you'd need from me to get someone to take a look?

**Comment by bacongobbler** [comment] 2021-01-25 17:23
It is intentional behavior for hooks to NOT be removed when `helm uninstall` is invoked. From the [documentation](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases):

> Practically speaking, this means that if you create resources in a hook, you cannot rely upon helm uninstall to remove the resources. To destroy such resources, you need to either add a custom helm.sh/hook-delete-policy annotation to the hook template file, or set the time to live (TTL) field of a Job resource.

Because this is documented, intended behavior, I'm closing this as this proposal directly contradicts with the hook system's described behavior, and there is clear recommended paths to move forward should you wish for hooks to be removed.

**Closed** 2021-01-25 17:23 UTC
Labels: question/support

**Comment by tomcruise81** [comment] 2021-01-25 17:38
What about the line that states:

> Garbage collection of hook resources when the corresponding release is deleted may be added to Helm 3 in the future. 

That is also documented. This PR aims to facilitate that...

**Comment by bacongobbler** [comment] 2021-01-25 17:43
While this does indeed introduce that functionality, it does so in a backwards-breaking fashion. Helm 3.5.0 and earlier did not uninstall hooks during a `helm uninstall`. This PR would break that behaviour, and by extension breaking that compatibility guarantee.

If you would like to propose ideas on how to clean up hooks during a `helm uninstall`, I would suggest looking into the HIP process. That way we can discuss the design details first before jumping to a solution. That would save us both time (you from writing a feature that would be closed, and me from having to review and re-state why that PR has to be closed).

https://github.com/helm/community/blob/master/hips/hip-0001.md

**Comment by tomcruise81** [comment] 2021-01-25 17:57
It is not backwards-compatible - correct. However, it is consistent with your documentation - i.e. this doesn't break:

> [so any hook resources that must never be deleted should be annotated with `helm.sh/resource-policy: keep`](https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases:~:text=so%20any%20hook%20resources%20that%20must,should%20be%20annotated%20with%20helm.sh%2Fresource%2Dpolicy%3A%20keep)

And nothing on your https://github.com/helm/helm/blob/master/CONTRIBUTING.md page mentions the need to go through the HIP process.

But you're entitled to run your project how you see fit.

**Comment by bacongobbler** [comment] 2021-01-25 18:05
Thank you for calling that out. We'll get the CONTRIBUTING.md file fixed up to match with the new process.

**Comment by jonnylangefeld** [comment] 2022-03-21 17:33
+1 for this feature. I came here to find out why my hooked resources didn't get cleaned up. We rely on hooks for https://github.com/open-policy-agent/gatekeeper because some custom resources rely on the CRDs created by the binary running in the deployment of the main chart. So we use `"helm.sh/hook": post-install,post-upgrade` but would still like them to be cleaned up if renamed/removed from the chart.
Given the fact that `helm.sh/resource-policy: keep` is mentioned in the relevant docs part I would think that the expected behavior is actually that the resources get cleaned up if one doesn't have the `keep` annotation. So while yes, it changes the behavior, I think it changes it to the actual expected behavior. It wouldn't break anything from previous helm releases, it would just change the behavior (to what I would argue is expected anyway).

**Comment by Ornias1993** [comment] 2023-03-08 13:31
> +1 for this feature. I came here to find out why my hooked resources didn't get cleaned up. We rely on hooks for https://github.com/open-policy-agent/gatekeeper because some custom resources rely on the CRDs created by the binary running in the deployment of the main chart. So we use `"helm.sh/hook": post-install,post-upgrade` but would still like them to be cleaned up if renamed/removed from the chart. Given the fact that `helm.sh/resource-policy: keep` is mentioned in the relevant docs part I would think that the expected behavior is actually that the resources get cleaned up if one doesn't have the `keep` annotation. So while yes, it changes the behavior, I think it changes it to the actual expected behavior. It wouldn't break anything from previous helm releases, it would just change the behavior (to what I would argue is expected anyway).


@bacongobbler Can we simply add a middle ground like:
`helm.sh/resource-policy: delete`

Deleting hooks on uninstall when explicitly set.
It would work-out to be perfectly backwards compatible and offer those options to projects that need it.

**Comment by ruben-gp** [comment] 2023-07-17 15:41
Hi,
I was wondering if there has been any update on this topic so far, or if there will be any change in future releases regarding this.
Thanks in advance!

**Comment by alexnoz** [comment] 2023-08-16 10:13
> > +1 for this feature. I came here to find out why my hooked resources didn't get cleaned up. We rely on hooks for https://github.com/open-policy-agent/gatekeeper because some custom resources rely on the CRDs created by the binary running in the deployment of the main chart. So we use `"helm.sh/hook": post-install,post-upgrade` but would still like them to be cleaned up if renamed/removed from the chart. Given the fact that `helm.sh/resource-policy: keep` is mentioned in the relevant docs part I would think that the expected behavior is actually that the resources get cleaned up if one doesn't have the `keep` annotation. So while yes, it changes the behavior, I think it changes it to the actual expected behavior. It wouldn't break anything from previous helm releases, it would just change the behavior (to what I would argue is expected anyway).
> 
> @bacongobbler Can we simply add a middle ground like: `helm.sh/resource-policy: delete`
> 
> Deleting hooks on uninstall when explicitly set. It would work-out to be perfectly backwards compatible and offer those options to projects that need it.

Hello, I think this approach really could work, can we discuss it further? I could try and put together a PR myself, please let me know if you're interested. This feature would be immensely beneficial to us. AFAIK, currently there are no clean ways to delete hooks during/after `helm uninstall`, I mean the hooks that should have only `before-hook-creation` deletion policy and are not Jobs, so TTL can't be used. Hence it can create a lot of garbage in a dynamic cluster, where many releases with such hooks are created and deleted in a short time, e.g. in a staging environment.

**Comment by alsyia** [comment] 2023-09-19 09:40
Also interested in an update as hook resources deletion when uninstall a release would be really useful for us!

**Comment by SuperSandro2000** [comment] 2023-12-05 11:01
I have a CI for a helm chart which does a full e2e test from helm install to helm uninstall and today I noticed the some hooks are left behind which is not great.

So far my only idea how to properly clean this up and not leave clutter in the k8s cluster is to manually delete the objects after the chart uninstallation. Did anyone come up with a better idea in the meantime because this feels ridiculous.

**Comment by felipecrs** [comment] 2025-04-04 03:33
The lack of this feature doesn't make any sense, nor what the documentation suggests. It doesn't address the issue anyhow.

Why can't we set `helm.sh/hook-delete-policy: before-release-delete`?

The workaround is absurdly complicated: you have to define a post-uninstall job hook that runs kubectl with proper service account and everything to delete these resources.

**Comment by MedianMedusa** [comment] 2026-01-15 08:33
For anyone who gets here: I found a pretty simple workaround on how to delete hook resources. It works in my case, take a look, I feel like it has some tweaking space:
```yaml
{{- range $index, $suffix := .Values.val_list }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Release.Name }}-{{$suffix}}
  annotations:
    helm.sh/hook: 'pre-install, pre-upgrade'
    helm.sh/hook-weight: '-5'
stringData:
  secret_data: donotlook-{{$.Release.Revision}}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $.Release.Name }}-{{$suffix}}
  annotations:
    helm.sh/hook: 'post-delete'
    helm.sh/hook-delete-policy: 'before-hook-creation,hook-succeeded'

{{- end }}
``` 

I included a range to show that even dynamically named resources are deleted. Currently, the behavior is as follows:
1. On `helm install`, the secrets are created with the first hook
2. On `helm upgrade`, the secrets are upgraded. There is an issue though: removed hooks are not deleted from k8s on upgrade. Example:
Values.yaml on first install:
```yaml
val_list:
  - first
  - second
  - third
```
Secrets created (the Chart name is "example"):
example-first (with secret_data == donotlook-1)
example-second (with secret_data == donotlook-1)
example-third (with secret_data == donotlook-1)

Then I change the values to:
```yaml
val_list:
  - first
  - second
  - new
```
Secrets in the cluster after `helm upgrade`:
example-first (with secret_data == donotlook-2)
example-second (with secret_data == donotlook-2)
example-third (with secret_data == donotlook-1)
example-new (with secret_data == donotlook-2)

3. On uninstall, the second hook takes place and the secrets are deleted. However, the issue above persists - helm uses values from the last release (so in the example above, `example-third` will not be deleted)


Right now it works for me as the manifests list is rarely changed, and if it happens, i upgrade my Chart uninstalling it first.
