### ISSUE TITLE
baltocdn serving helm 3.13 with 401 unauthorized bug

### ISSUE THREAD

**Issue by bkochendorfer** [helm/helm#12444] opened 2023-10-02 16:09 UTC
Downgraded so that our build and deploy pipeline can continue but it looks like the CDN is serving up a version of the build which has a `401 unauthorized` error when doing a pull from OCI https://github.com/helm/helm/issues/12423

```bash
$ helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.20.8"}

$ helm pull oci://us-west1-docker.pkg.dev/redacted/redacted/redacted--version 1.8.20 --debug
401 Unauthorized
```

```bash
$ apt-cache policy helm
helm:
  Installed: 3.12.3-1
  Candidate: 3.13.0-1
  Version table:
     3.13.0-1 500
        500 https://baltocdn.com/helm/stable/debian all/main amd64 Packages
```

**Comment by hiddeco** [comment] 2023-10-02 17:26
Duplicate of #12423, #12430, #12439, etc.

**Comment by yxxhero** [comment] 2023-10-03 09:03
@hiddeco thanks for your answer.

**Closed by yxxhero** 2023-10-03 09:03 UTC
