### ISSUE TITLE
Comparing helm charts's contents (md5)

### ISSUE THREAD

**Issue by dcodix** [helm/helm#5575] opened 2019-04-09 22:35 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

Output of `kubectl version`:
Not apply

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Not Apply

PROBLEM:
We were using md5 to compare some helm (tar) charts to decide if they were the same. After this change:
https://github.com/helm/helm/blob/744cd20eab4e0525bccbea957da2047d6b469e61/pkg/chartutil/save.go#L218
It seems now "helm package" is shipping Modification dates, which makes it impossible to compare helm charts using md5 as every single time they will be different.

So, is there any other way to check if 2 helm charts have the same contents? If there is not, are there any plans for that or maybe adding a flag to disable this behaviour?
We thinking on not using "helm package" and instead create the packages ourselves, but we would like a more elegant approach.

Thanks!

**Comment by maorfr** [comment] 2019-04-14 21:14
Maybe this can help:
https://github.com/databus23/helm-diff

**Comment by dcodix** [comment] 2019-04-16 15:18
Thanks maorfr, but for that I need to download the chart. I was trying not to and using S3 Etag to compare the md5 and save time and data transmission.

**Comment by royjs** [comment] 2019-04-18 20:34
I'm having the same exact issue. I would like to compare the file currently in my chart repo to a local package by comparing the checksums.
As dcodix explained, the issue is that even if the chart itself didn't change, the packaged chart (tar) is different every time. I would be really helpful to have a way to compare 2 packaged charts without having to download and extract them to compare the content.

**Comment by bacongobbler** [comment] 2019-04-18 21:08
Should we close this as a duplicate of https://github.com/helm/helm/issues/3612?

**Closed** 2019-12-09 20:21 UTC
Labels: question/support
