### ISSUE TITLE
Install release with go sdk v3.4.2 | Installed release's namespace mismatch

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [helm/helm#9171] opened 2020-12-25 13:44 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubeadm

## Problem
Hi guys, I'm using helm go sdk with version v3.4.2 to install a release to namespace ``helm-test``, but unfortunately, the release has been install in namespace ``default``.
I check helm's source code at <https://github.com/helm/helm/blob/960b3b53c6c30d72c68738fbed3ccf3724b30130/cmd/helm/install.go> to figure the problem out, but not working.

The release successfully installed, but the resouces(such as pod/deployment/services) are in other namespace(default in this case)
![image](https://user-images.githubusercontent.com/39913604/103136280-008de680-46fa-11eb-8d34-8a550b1001a4.png)
![image](https://user-images.githubusercontent.com/39913604/103136293-21563c00-46fa-11eb-8438-35983888196b.png)
![image](https://user-images.githubusercontent.com/39913604/103136302-2dda9480-46fa-11eb-826d-f019dd6284e2.png)

Here is my code:
```golang
helmSetting := cli.New()
actionConfig := new(action.Configuration)

if err := actionConfig.Init(helmSetting.RESTClientGetter(), "helm-test", os.Getenv("HELM_DRIVER"), log.Debugf); err != nil {
	log.Fatal(err)
}

client := action.NewInstall(actionConfig)

name, chart, err := client.NameAndChart([]string{"test", "bitnami/nginx"})
if err != nil {
	return nil, err
}
client.ReleaseName = name

cp, err := client.ChartPathOptions.LocateChart(chart, helmSetting)
if err != nil {
	return nil, err
}

chartRequested, err := loader.Load(cp)
if err != nil {
	return nil, err
}

p := getter.All(helmSetting)
valueOpts := &values.Options{}
vals, err := valueOpts.MergeValues(p)
if err != nil {
	return nil, err
}

client.Namespace = "helm-test"
return client.Run(chartRequested, vals)
```

Any help would be greatly appreciated :)
Thanks for helping!

**Comment by SaigyoujiYuyuko233** [comment] 2020-12-25 13:57
![image](https://user-images.githubusercontent.com/39913604/103136524-100e2f00-46fc-11eb-97e0-504d49ca24dc.png)
Really strange

**Comment by SaigyoujiYuyuko233** [comment] 2020-12-25 14:27
I think I found solution here....
Just set the env ``HELM_NAMESPACE`` to the namespace that you want to use...
![image](https://user-images.githubusercontent.com/39913604/103136995-04bd0280-4700-11eb-9ff9-f231b52397cd.png)
(I want to make some complaintions... why this is private....)
![image](https://user-images.githubusercontent.com/39913604/103137015-4483ea00-4700-11eb-9252-e9cf4cd8c860.png)

**Comment by bacongobbler** [comment] 2021-01-04 16:40
duplicate of https://github.com/helm/helm/issues/8780.

**Closed by bacongobbler** 2021-01-04 16:40 UTC

**Comment by mtiller** [comment] 2021-07-29 12:51
I had written code to extract the current context, change its default namespace and then write a temporary config file with that context and then point to it with `KUBECONFIG`.  But the above solution of just changing `HELM_NAMESPACE` is much simpler and I can confirm it worked in my case.  I have the same question though about why these bits aren't exported.
