### ISSUE TITLE
Question: helm3 test no parallel option anymore

### ISSUE THREAD

**Issue by GianniGiglio** [helm/helm#10921] opened 2022-05-02 07:05 UTC
Question is it still possible to run helm tests in parallel.
Helm2 had the option --parallel but that seems to be gone in helm2

**Comment by bacongobbler** [comment] 2022-05-02 16:34
https://github.com/helm/helm/pull/4144#issuecomment-587094629

Duplicate of #7763. See https://github.com/helm/helm/pull/8946 and the current status of the HIP at https://github.com/helm/community/pull/165#issuecomment-1079402279.

**Closed** 2022-05-02 18:16 UTC
