### ISSUE TITLE
Values file in packaged chart does not include comments

### ISSUE THREAD

**Issue by unguiculus** [helm/helm#7053] opened 2019-11-22 11:46 UTC
The values file in a chart tarball packaged with Helm 3 no longer includes comments.

Here's a diff of the values file in a chart tarball for a chart created with `helm create`, packaged with Helm 2.16.1 and Helm 3. Also, unfortunately, the content is now sorted alphabetically. My expectation would be that Helm simply packages up anything in the chart directory that's not in `.helmignore` without processing the files.

```diff
1,2c1,6
< affinity: {}
< fullnameOverride: ""
---
> # Default values for demo.
> # This is a YAML-formatted file.
> # Declare variables to be passed into your templates.
>
> replicaCount: 1
>
4d7
<   pullPolicy: IfNotPresent
5a9,10
>   pullPolicy: IfNotPresent
>
7,13d11
< ingress:
<   annotations: {}
<   enabled: false
<   hosts:
<   - host: chart-example.local
<     paths: []
<   tls: []
15c13,21
< nodeSelector: {}
---
> fullnameOverride: ""
>
> serviceAccount:
>   # Specifies whether a service account should be created
>   create: true
>   # The name of the service account to use.
>   # If not set and create is true, a name is generated using the fullname template
>   name:
>
17,18c23,24
< replicaCount: 1
< resources: {}
---
>   # fsGroup: 2000
>
19a26,32
>   # capabilities:
>   #   drop:
>   #   - ALL
>   # readOnlyRootFilesystem: true
>   # runAsNonRoot: true
>   # runAsUser: 1000
>
21d33
<   port: 80
23,25c35,63
< serviceAccount:
<   create: true
<   name: null
---
>   port: 80
>
> ingress:
>   enabled: false
>   annotations: {}
>     # kubernetes.io/ingress.class: nginx
>     # kubernetes.io/tls-acme: "true"
>   hosts:
>     - host: chart-example.local
>       paths: []
>   tls: []
>   #  - secretName: chart-example-tls
>   #    hosts:
>   #      - chart-example.local
>
> resources: {}
>   # We usually recommend not to specify default resources and to leave this as a conscious
>   # choice for the user. This also increases chances charts run on environments with little
>   # resources, such as Minikube. If you do want to specify resources, uncomment the following
>   # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
>   # limits:
>   #   cpu: 100m
>   #   memory: 128Mi
>   # requests:
>   #   cpu: 100m
>   #   memory: 128Mi
>
> nodeSelector: {}
>
26a65,66
>
> affinity: {}
```

**Comment by unguiculus** [comment] 2019-11-22 12:47
I just figured its possible to pass values to `helm package` now. This seems to have changed in Helm 3 and probably causes this issue.

Is there a way to retain comments and order in YAML? If not, then processing should only happen if values are specified and only those who need this IMHO questionable feature would have to pay the price of losing comments and order for using it.

**Comment by TBBle** [comment] 2019-11-23 14:07
Duplicate of #6951

**Closed** 2019-11-23 17:04 UTC
Labels: bug, v3.x
