### ISSUE TITLE
Error: UPGRADE FAILED: transport is closing

### ISSUE THREAD

**Issue by varun-da** [helm/helm#4702] opened 2018-09-26 16:54 UTC
This is unrelated to: https://github.com/helm/helm/issues/3140

Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.6", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-16T21:33:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

I am testing upgrade and rollback capabilities of some of my charts. 

```
REVISION        UPDATED                         STATUS                  CHART                   DESCRIPTION
1               Wed Sep 26 16:16:15 2018        SUPERSEDED              test-chart-0.0.1        Install complete
2               Wed Sep 26 16:16:19 2018        SUPERSEDED              test-chart-0.0.1        Upgrade complete
3               Wed Sep 26 16:16:21 2018        SUPERSEDED              test-chart-0.0.1        Upgrade complete
4               Wed Sep 26 16:16:23 2018        SUPERSEDED              test-chart-0.0.1        Upgrade complete
5               Wed Sep 26 16:16:47 2018        SUPERSEDED              test-chart-0.0.1        Rollback to 1
6               Wed Sep 26 16:17:26 2018        SUPERSEDED              test-chart-0.0.1        Upgrade complete
7               Wed Sep 26 16:19:05 2018        FAILED                  test-chart-0.0.1        Upgrade "job" failed: Job.batch "job" is invalid: [spec.s...
8               Wed Sep 26 16:20:38 2018        SUPERSEDED              test-chart-0.0.1        Upgrade complete
9               Wed Sep 26 16:21:01 2018        SUPERSEDED              test-chart-0.0.1        Rollback "job" failed: Job.batch "job" is invalid: [spec....
10              Wed Sep 26 16:21:14 2018        FAILED                  test-chart-0.0.1        Rollback "job" failed: Job.batch "job" is invalid: [spec....
11              Wed Sep 26 16:21:25 2018        PENDING_ROLLBACK        test-chart-0.0.1        Rollback to 6
12              Wed Sep 26 16:22:43 2018        PENDING_ROLLBACK        test-chart-0.0.1        Rollback to 5
13              Wed Sep 26 16:26:58 2018        PENDING_ROLLBACK        test-chart-0.0.1        Rollback to 5
14              Wed Sep 26 16:36:03 2018        PENDING_ROLLBACK        test-chart-0.0.1        Rollback to 5
15              Wed Sep 26 16:37:03 2018        PENDING_ROLLBACK        test-chart-0.0.1        Rollback to 5
```

I am purposefully adding incorrect yaml keys to a job template to produce an error and then attempting to rollback.

The spec of the job is straight forward:

```apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: job-test-chart
    chart: test-chart-0.0.1
    heritage: Tiller
    release: job
  name: job
  namespace: job
spec:
  backoffLimit: 4
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: job-test-chart
        chart: test-chart-0.0.1
        heritage: Tiller
        job-name: job
        release: job
    spec:
      containers:
      - args:
        - "10"
        command:
        - sleep
        image: nginx
        imagePullPolicy: IfNotPresent
        name: job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

I am installing using the command:
```
helm upgrade job /charts/test-chart --install --namespace job --values /charts/test-chart/values.yaml
```

When I attempt a rollback after a failed upgrade, the rollback also fails (I am working towards a resolution):
```
⎈ helm rollback job 5 --force
Error: "job" has no deployed releases
```

However when I try to force upgrade with a correct yaml spec, it returns a unexpected error:
```
⎈ helm upgrade job /charts/test-chart --install --force --namespace job --values /charts/test-chart/values.yaml
Error: UPGRADE FAILED: transport is closing
```

Tiller logs:
```
[tiller] 2018/09/26 16:37:16 getting history for release job
[storage] 2018/09/26 16:37:16 getting release history for "job"
[tiller] 2018/09/26 16:37:16 preparing update for job
[storage] 2018/09/26 16:37:16 getting deployed releases from "job" history
[storage] 2018/09/26 16:37:16 getting last revision of "job"
[storage] 2018/09/26 16:37:16 getting release history for "job"
[storage] 2018/09/26 16:37:16 getting release history for "job"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x12e7028]

goroutine 298 [running]:
k8s.io/helm/pkg/tiller.(*ReleaseServer).performUpdateForce(0xc420602000, 0xc42041a1e0, 0x0, 0x0, 0x17b50a0)
        /go/src/k8s.io/helm/pkg/tiller/release_update.go:166 +0x188
k8s.io/helm/pkg/tiller.(*ReleaseServer).UpdateRelease(0xc420602000, 0x17d5e00, 0xc42179a210, 0xc42041a1e0, 0xc420602000, 0x16b70a5, 0xd)
        /go/src/k8s.io/helm/pkg/tiller/release_update.go:43 +0x245
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler.func1(0x17d5e00, 0xc42179a210, 0x1603f20, 0xc42041a1e0, 0x32, 0xc42041a4b0, 0xc42041a101, 0x0)
        /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1244 +0x86
k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x17d5e00, 0xc42179a210, 0x1603f20, 0xc42041a1e0, 0xc4216860a0, 0xc4216860c0, 0x48, 0xc4217e6120, 0xc4218d3a40, 0x4108c8)
        /go/src/k8s.io/helm/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:86 +0xdb
k8s.io/helm/pkg/tiller.newUnaryInterceptor.func1(0x17d5e00, 0xc42179a210, 0x1603f20, 0xc42041a1e0, 0xc4216860a0, 0xc4216860c0, 0xc420492ab0, 0x4108c8, 0x50, 0x15d6360)
        /go/src/k8s.io/helm/pkg/tiller/server.go:60 +0xab
k8s.io/helm/pkg/proto/hapi/services._ReleaseService_UpdateRelease_Handler(0x163dd60, 0xc420602000, 0x17d5e00, 0xc42179a210, 0xc42041a190, 0x1712cd8, 0x0, 0x0, 0x43317c, 0xc4202ce600)
        /go/src/k8s.io/helm/pkg/proto/hapi/services/tiller.pb.go:1246 +0x167
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4201b4000, 0x17de900, 0xc421776160, 0xc42025a400, 0xc420602090, 0x215fcf0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:826 +0x9c8
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4201b4000, 0x17de900, 0xc421776160, 0xc42025a400, 0x0)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:1023 +0x1318
k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4205be570, 0xc4201b4000, 0x17de900, 0xc421776160, 0xc42025a400)
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:572 +0x9f
created by k8s.io/helm/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/k8s.io/helm/vendor/google.golang.org/grpc/server.go:570 +0xa1```

The force upgrade crashes the tiller pod and it spawns a new replacement pod. Seems like this a bug.

**Comment by bacongobbler** [comment] 2018-09-26 17:11
dupe of https://github.com/helm/helm/issues/4672

**Closed by bacongobbler** 2018-09-26 17:11 UTC
