### ISSUE TITLE
helm 3: allow adding custom template functions to engine

### ISSUE THREAD

**Issue by JeanMertz** [helm/helm#5779] opened 2019-05-22 14:56 UTC
At our company, we're using a custom utility to build/deploy our helm charts:

https://github.com/blendle/kubecrt

I've been experimenting with upgrading this utility to the Helm 3 alpha.

Unfortunately, it seems like v3 no longer provides access to the map of functions that will be used when rendering the charts.

Specifically, we [add (back) the `env` and `expandenv`](https://github.com/blendle/kubecrt/blob/d8602296ef2561632fe58cf45fb96dfbc18265cc/chartsconfig/parser.go#L36-L45) functions, as they provide us with the flexibility needed for our (private) deployment pipeline.

Whereas in 2.x, we could access those functions using `renderer.FuncMap`, it seems like [they are now made private](https://github.com/helm/helm/blob/b9a54967f838723fe241172a6b94d18caf8bcdca/pkg/engine/engine.go#L79-L117), and we're unable to modify them.

Any thoughts on making this use-case possible again?

**Comment by trevex** [comment] 2019-05-27 08:00
I would second this request, we have a similar use case, where we reference secrets from Hashicorp Vault and retrieve them with custom logic.
It would be great to extend the `renderer.FuncMap` via https://github.com/helm/community/blob/master/helm-v3/005-plugins.md

**Comment by bacongobbler** [comment] 2019-08-13 23:25
dupe of #5826

**Closed by bacongobbler** 2019-08-13 23:25 UTC
Labels: question/support, v3
