### ISSUE TITLE
Helm 2.16.0 chart install fails to register Job hook

### ISSUE THREAD

**Issue by relu** [helm/helm#6906] opened 2019-11-07 20:02 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

The error I see in the tiller logs is the following:
```
tiller-deploy-6f549d4774-jnx2m tiller [kube] 2019/11/07 19:42:16 Add/Modify event for prometheus-operator-admission-create: ADDED                                                                     
tiller-deploy-6f549d4774-jnx2m tiller [tiller] 2019/11/07 19:42:16 warning: Release prometheus-operator pre-install prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job
-createSecret.yaml could not complete: no kind "Job" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"                                             
tiller-deploy-6f549d4774-jnx2m tiller [tiller] 2019/11/07 19:42:16 failed install perform step: no kind "Job" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/s
cheme.go:30"
```

The version of the prometheus-operator chart I'm trying to install is `8.1.2`.

I tried to run the installation multiple times and failed every time. After downgrading helm to 2.15.2 it works just fine.

I can provide more details if needed.

**Comment by bacongobbler** [comment] 2019-11-07 20:04
closing as a duplicate of #6894. Thanks!

**Closed by bacongobbler** 2019-11-07 20:04 UTC
