### ISSUE TITLE
Broken links in helm.sh Documentation

### ISSUE THREAD

**Issue by DJPumpkin** [helm/helm#5378] opened 2019-02-28 11:04 UTC
Hi, i tried to lookup the documentation for "TLS/SSL for helm and tiller", but when i go to the documentation on the webside, under "Using Helm", the only link that works in the submenu is "Using helm", all other links references to ID's that isn't on the page.
https://helm.sh/docs/using_helm/
https://helm.sh/docs/using_helm/#using-ssl-between-helm-and-tiller

**Comment by hickeyma** [comment] 2019-02-28 11:27
@DJPumpkin This is a duplicate of #5376 . Can you close this and add any comments to 
helm/helm-www#185 ?

**Closed** 2019-02-28 11:30 UTC
