### ISSUE TITLE
Helm Does Not Show useful error when helm update -i fails

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [helm/helm#5012] opened 2018-12-04 21:47 UTC
I will add more details here shortly, but capturing this issue now before I forget.

Summary: We've run into a few situations where a `helm upgrade` command fails with a very generic error about not being able to overwrite an existing release (that's the whole point of `helm upgrade` to upgrade the named release.  In all of these cases, we've been able to `helm delete --purge` the release and attempt another `helm upgrade -i`  When we do that We get an actual useful error message.  

For instance, we've seen errors like:

- missing required values
- badly formatted yaml

It's really frustrating to not get those errors in the output of `helm upgrade`.  And obviously to be forced to delete and recreate a release is not going to work for us when we get out of dev and into production.

**I promise to add more details here shortly, including a simple test case that reproduces the problem.**

Output of `helm version`:

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by john-mcgowan-wowza** [comment] 2018-12-05 17:19
@bacongobbler, just curious, Why would this be labeled with "question/support".

Isn't this a bug (or at least a "feature request") if it's behaving the way I describe?

**Comment by bacongobbler** [comment] 2018-12-05 17:32
I marked it as a support ticket because there is a lack of details here to confirm whether it's a bug or something in the chart. Once we can reproduce the issue it gets promoted to a bug.

**Comment by AlexandrSemak** [comment] 2018-12-05 19:41
Yep it would be useful because NOW if you want look in REAL reason you must do:
`kubectl logs tiller-pod -n kube-system`

**Comment by john-mcgowan-wowza** [comment] 2018-12-05 20:36
> I marked it as a support ticket because there is a lack of details here to confirm whether it's a bug or something in the chart. Once we can reproduce the issue it gets promoted to a bug.

Thanks for the explanation.  I will hopefully have time to put together a simple test case that shows the difference and highlights what I think the bug is.

**Comment by bacongobbler** [comment] 2019-12-09 20:06
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2019-12-09 20:06 UTC
Labels: question/support
