### ISSUE TITLE
Helm 3 resources apiVersion update 

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#7393] opened 2020-01-13 19:01 UTC
Output of `helm version`:
Helm 3.0.2

Helm 3 doesn't provide any way to recreate resources after update apiVersion.

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Deployment, namespace: dev, name: dummy-dev

helm.go:76: [debug] existing resource conflict: kind: Deployment, namespace: dev, name: dummy-dev
rendered manifests contain a new resource that already exists. Unable to continue with update
```

**Comment by alexandrsemak** [comment] 2020-01-14 01:03
Kubernetes provide `kubectl convert` 
example:
`kubectl convert -f ./my-deployment.yaml --output-version apps/v1`

Is it possible integrate in Helm 3 with additional flag for migration to new apiVersion?

**Comment by alexandrsemak** [comment] 2020-01-14 01:17
Kubernetes suggest use `kubectl convert` but looks like it is show up the same error, testing on kubernetes 1.14.9

**Comment by bacongobbler** [comment] 2020-01-16 17:14
duplicate of https://github.com/helm/helm/issues/6850.

**Closed by bacongobbler** 2020-01-16 17:14 UTC
