### ISSUE TITLE
Helm3: problems with openshift "route" resource

### ISSUE THREAD

**Issue by alitari** [helm/helm#5766] opened 2019-05-20 15:42 UTC
Rendering the [route resource of openshift](https://docs.openshift.com/container-platform/3.9/rest_api/apis-route.openshift.io/v1.Route.html) fails with `Error: apiVersion "route.openshift.io/v1" in route-test/templates/route.yaml is not available`

You can reproduce this with a simple one-template chart with route.yaml:
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-test
spec:
  host: test.com
  to:
    kind: Service
    name: service-name
    weight: 100
  wildcardPolicy: None
```
and call `helm template`. 

Full error message: 
```
helm.go:56: [debug] apiVersion "route.openshift.io/v1" in route-test/templates/route.yaml is not available
helm.sh/helm/pkg/releaseutil.(*manifestFile).sort
        /go/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:133
helm.sh/helm/pkg/releaseutil.SortManifests
        /go/src/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:98
helm.sh/helm/pkg/action.(*Configuration).renderResources
        /go/src/helm.sh/helm/pkg/action/install.go:348
helm.sh/helm/pkg/action.(*Install).Run
        /go/src/helm.sh/helm/pkg/action/install.go:135
main.runInstall
        /go/src/helm.sh/helm/cmd/helm/install.go:212
main.newTemplateCmd.func2
        /go/src/helm.sh/helm/cmd/helm/template.go:70
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:852
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main
        /go/src/helm.sh/helm/cmd/helm/helm.go:55
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

`helm version: v3.0.0-alpha.1`

Output of `kubectl version`:  version.Info{Major:"1", Minor:"14",...} 

Cloud Provider/Platform (AKS, GKE, Minikube etc.): OpenShift 
OpenShift Master: v3.9.0+ba7faec-1
Kubernetes Master: v1.9.1+a0ce1bc657

**Comment by karuppiah7890** [comment] 2019-05-23 18:24
Thanks @alitari for reporting this issue! 😄 

I am able to reproduce the issue. I used this chart to reproduce it : 
[issue-5766.tar.gz](https://github.com/helm/helm/files/3213618/issue-5766.tar.gz)

And I think it's a general issue and not specific to just `Route` CRD of openshift, as I am able to reproduce the issue with a different CRD `ServiceMonitor` from coreos. This is the chart :  
[test-chart.tar.gz](https://github.com/helm/helm/files/3213621/test-chart.tar.gz) and I also ran into the same error when trying to install it, for which I created an issue here #5654 . 

I think we can close issue #5654 as even templating is not working, so installation is out of the question as installation can happen only if templating succeeds, at least that's my understanding.

@alitari @hickeyma what are your thoughts ?

**Comment by alitari** [comment] 2019-05-24 07:28
@karuppiah7890 : i would not close the issue , most probably both issues have the same technical cause, but this must mean that we should have only one issue open. Just my thoughts...anyway good to hear that you could reproduce it , maybe the label "unconfirmed" can be removed...

**Comment by matthiasak** [comment] 2019-06-14 22:07
@karuppiah7890 is there any movement on fixing the issue of using CRDs with Helm 3?

**Comment by karuppiah7890** [comment] 2019-06-15 03:26
@matthiasak I don't know actually, but I see there's a proposal discussion going on for CRDs - https://github.com/helm/helm/issues/5871

**Comment by yhrn** [comment] 2019-07-08 07:33
As I understand it #5871 is a proposal to improve on Helm's CRD management, including and maybe especially, when the CRDs, are/may need to be installed as part of a chart. The problem reported here, and more generically formulated in #5654, is more of a pure regression bug imo - it's no longer possible to include any CRs in a chart, at least if the CRD is not included in the chart but known to be installed in the cluster. It's not even possible to run `helm template`.

To me this seems to break such a fundamental use case that it might be worth addressing it independently of the bigger discussion happening in #5871 since I'm guessing it will block a lot of people from trying out Helm3.

**Comment by ento** [comment] 2019-08-06 00:47
@bacongobbler From what I can tell, #5654, which has been closed, is about the same issue as this. Do you want to close this one as well?

For anyone watching or stumbled upon this issue: adding the `--validate` flag to `helm template` is the workaround for now. More details in the other issue

**Comment by bacongobbler** [comment] 2019-08-06 05:54
Yeah, after looking more closely at OP's and the follow-up commenter's issues, I think they're bumping into the same issues laid out and demonstrated in #5654. I think this can be closed as a duplicate, so I'll do that now. If, however, there's a use case I missed that this issue raises, please do let me know and we can re-open to discuss further. Thanks!

**Closed by bacongobbler** 2019-08-06 05:54 UTC
Labels: bug, unconfirmed, v3
