### ISSUE TITLE
Import-values do not override default values

### ISSUE THREAD

**Issue by pbusko** [helm/helm#11518] opened 2022-11-07 14:47 UTC
Following the import-values example described [on the official website](https://helm.sh/docs/topics/charts/#importing-child-values-via-dependencies), we can't get the result shown on the page. If the parent chart has default values and the same value gets imported from the child chart, it's not overridden. Attached a packaged chart with the example from the documentation.
[test-import-0.1.0.tgz](https://github.com/helm/helm/files/9952674/test-import-0.1.0.tgz)

Expected output:

```console
$ helm template test test-import-0.1.0.tgz 
---
# Source: test-import/templates/test.yaml
myimports:
  mybool: true
  myint: 999
  mystring: helm rocks!
subchart:
  default:
    data:
      mybool: true
      myint: 999
  global: {}
```

Actual output (`myimports.mybool` and `myimports.myint` are kept as defaults):

```console
$ helm template test test-import-0.1.0.tgz 
---
# Source: test-import/templates/test.yaml
myimports:
  mybool: false
  myint: 0
  mystring: helm rocks!
subchart:
  default:
    data:
      mybool: true
      myint: 999
  global: {}
```

Output of `helm version`:
```console
$ helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}
```
Output of `kubectl version`:
```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:13:07Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

**Comment by joejulian** [comment] 2022-11-08 21:48
Nice repro. I get the same with your test chart. I think we'll need input from a @helm/helm-core-maintainers on this one.

**Comment by pbusko** [comment] 2022-11-10 08:55
We've opened a PR with a potential fix at https://github.com/helm/helm/pull/11527

**Comment by yxxhero** [comment] 2022-11-12 09:50
@joejulian I think we need to bring up the issue at the developer meeting.

**Comment by digitalstudium** [comment] 2022-12-17 11:48
I prefer current behavior. The use case is when I import default values from a library chart, and then redefine some of them if needed in parent chart.
Example which works for me today:
library chart `values.yaml`:
```
defaults:
  image:
    registry: quay.io
    name: ""
```
`values.yaml` of a chart which imports library chart:
```
image:
  name: nginx
```

Resulting `values.yaml`:
```
  image:
    registry: quay.io
    name: nginx
 ```
 
So I prefer if you change documentation, not the code. Because I want my library chart to have default values and I want to have a method to redefine some of them.

Side note: the way I import library chart is such:
```
dependencies:
  - name: base
    repository: file://../../libraries/base
    version: "*"
    import-values:
      - child: defaults
        parent: .
```

**Comment by arvidOtt** [comment] 2023-01-24 16:55
I think this is a duplicate of #10899.

**Comment by joejulian** [comment] 2023-01-27 19:41
I agree. Closing this as a duplicate.

**Closed by joejulian** 2023-01-27 19:41 UTC
Labels: in progress, bug
