### ISSUE TITLE
Label selector in list command no longer working

### ISSUE THREAD

**Issue by gakesson** [helm/helm#12517] opened 2023-10-22 13:52 UTC
Hello,

In Helm versions prior to 3.13.1 (for example 3.12.3) it was possible to list Helm releases by label selector, for example by Helm release name.

If I install a simple chart like incubator/raw like this:
```
$ helm repo add incubator https://charts.helm.sh/incubator
"incubator" has been added to your repositories
$ helm upgrade -i raw incubator/raw
Release "raw" does not exist. Installing it now.
WARNING: This chart is deprecated
NAME: raw
LAST DEPLOYED: Sun Oct 22 15:44:47 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

If I then use label selector _name=raw_ using Helm 3.13.1 it does not find any the previously installed raw release:
```
$ helm version
version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}
$ helm list -l name=raw
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
$
```

However if I downgrade Helm to 3.12.3 then the raw release is found:

```
$ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"
$ helm list -l name=raw
NAME	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART    	APP VERSION
raw 	default  	1       	2023-10-22 15:44:47.089882209 +0200 CEST	deployed	raw-0.2.5	0.2.3      
$
```

Is this an intentional change or a bug?

**Comment by z4ce** [comment] 2023-10-23 16:38
It seems like this PR broke this https://github.com/helm/helm/pull/10533 . Specifically this commit 95bb77c261f0965dc4e6ecf938cc754a3006939b.  I have not yet dug into exactly how it broke it. I could imagine that a decent number of people are relying on this functionality. cc @mattfarina @joejulian

**Comment by z4ce** [comment] 2023-10-23 16:50
Also adding in the PR author @dm3ch

It seems that the filterSystemLabels function is stripping away the secrets selector when you use any of "name", "owner", "status", "version", "createdAt", "modifiedAt" as your label selector.

**Comment by mattfarina** [comment] 2023-10-23 16:59
Is this a duplicate of #12435?

**Comment by z4ce** [comment] 2023-10-23 17:01
Yep duplicate. Let's close this one in favor of that one.

**Closed by z4ce** 2023-10-23 17:01 UTC
Labels: bug

**Comment by dm3ch** [comment] 2023-10-24 19:37
jFYI: fix is currently exist in following PR - https://github.com/helm/helm/pull/12447

**Comment by gakesson** [comment] 2023-10-24 19:59
Thanks! Will track the other PR.
