### ISSUE TITLE
Weird behavior when using invalid (non-dns) release name

### ISSUE THREAD

**Issue by McSlow** [helm/helm#4454] opened 2018-08-09 14:26 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", ...
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
baremetal, kubespray

Currently helm acts a little bit weird when you provide a non-dns-valid release name.
If you install a chart like this:
```
helm upgrade --install --namespace bla super_bla local/bla 
```
it will return something like this:
```
Release "super_bla" does not exist. Installing it now.
NAME:   super_bla
Error: getting deployed release "super_bla": release: "super_bla" not found
```
apart from the missleading error helm returns (tiller's logs actually give a clear hint what's going wrong) 
it's even worse, helm will actually create all resources with kubectl, but leaving the release completely broken.

Wouldn't it be better to run naming checks on those input fields before? Or return a better error and not creating anything on the cluster?

regards,
Bjoern

**Comment by fbcbarbosa** [comment] 2018-08-13 17:41
Just experienced the same issue (and lost a lot of time tracking down the reason and deleting every resource Helm created manually). 

For further info, this is what I got when I inspected tiller logs:

```
[storage/driver] 2018/08/13 17:14:49 create: failed to create: Secret "[redacted] is invalid: metadata.name: Invalid value: "[redacted]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Any reason why there's no release name validation in place? Would be happy to contribute with a PR if necessary.

**Comment by jascott1** [comment] 2018-08-27 17:39
I haven't confirmed the bug myself but if thats the case a PR would be welcome @fbcbarbosa

**Comment by fbcbarbosa** [comment] 2019-01-03 12:32
@jascott1 @McSlow I believe this PR should have fixed it: https://github.com/helm/helm/pull/4883

Maybe we can close this?

**Closed** 2019-01-03 15:10 UTC
Labels: bug, unconfirmed
