### ISSUE TITLE
latest helm release is not latest release

### ISSUE THREAD

**Issue by josefschabasser** [helm/helm#7603] opened 2020-02-15 13:55 UTC
https://api.github.com/repos/helm/helm/releases/latest points to version 2.16.3.
https://github.com/helm/helm/releases redirects to 2.16.3.
Both should point to  3.1.0. Our last successful deployment was on 02.02.2020 using helm 3.0.3 (with the same URL as mentioned in the first line).
This breaks our release pipeline in Azure DevOps as this version can't find tiller.

**Comment by bacongobbler** [comment] 2020-02-15 16:27
duplicate of #7598, #7597, #7594, #7592, and #7590. Please see the explanation given here: https://github.com/helm/helm/issues/7597#issuecomment-586424552

**Closed by bacongobbler** 2020-02-15 16:27 UTC
