### ISSUE TITLE
Lint: helm/pkg/lint validation rule mismatch k8s validation rule

### ISSUE THREAD

**Issue by popozy** [helm/helm#9203] opened 2021-01-07 11:37 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
self-building Kubernetes cluster

Reproduce step:
+ get tidb-opeartor.tgz helm package here: http://charts.pingcap.org/tidb-operator-v1.1.5.tgz
+ decompress the archive package
+ helm lint tidb-operato
it shows:
``` shell
==> Linting tidb-operator
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/controller-manager-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:tidb-controller-manager": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/controller-manager-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRole" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRole"
[ERROR] templates/controller-manager-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:tidb-controller-manager": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/controller-manager-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
[ERROR] templates/scheduler-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:tidb-scheduler": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/scheduler-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRole" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRole"
[ERROR] templates/scheduler-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:tidb-scheduler": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/scheduler-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
[ERROR] templates/scheduler-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:kube-scheduler": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/scheduler-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"
[ERROR] templates/scheduler-rbac.yaml: object name does not conform to Kubernetes naming requirements: "test-release:volume-scheduler": invalid metadata name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 253
[ERROR] templates/scheduler-rbac.yaml: the kind "rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 ClusterRoleBinding"

Error: 1 chart(s) linted, 1 chart(s) failed
```

Bug:
I have dig into helm3  implementation and got the pr and backaground of the following code:
pr：https://github.com/helm/helm/pull/8011/files#diff-99d16582249b9bc470365aac41d280cf0bd6a14ccac1a96151b45479e05d2c2bR133
relative issue：https://github.com/helm/helm/issues/7672
``` golang
  if yamlStruct != nil {
	  linter.RunLinterRule(support.ErrorSev, fpath, validateMetadataName(yamlStruct))
	  linter.RunLinterRule(support.ErrorSev, fpath, validateNoDeprecations(yamlStruct))
	  linter.RunLinterRule(support.ErrorSev, fpath, validateMatchSelector(yamlStruct, renderedContent))
  }

  func validateMetadataName(obj *K8sYamlStruct) error {
	  if len(obj.Metadata.Name) == 0 || len(obj.Metadata.Name) > 253 {
		  return fmt.Errorf("object name must be between 0 and 253 characters: %q", obj.Metadata.Name)
	  }
	  // This will return an error if the characters do not abide by the standard OR if the
	  // name is left empty.
	  if err := chartutil.ValidateMetadataName(obj.Metadata.Name); err != nil {
		  return errors.Wrapf(err, "object name does not conform to Kubernetes naming requirements: %q", obj.Metadata.Name)
	  }
	  return nil
  }

  // ValidateMetadataName validates the name field of a Kubernetes metadata object.
  //
  // Empty strings, strings longer than 253 chars, or strings that don't match the regexp
  // will fail.
  //
  // According to the Kubernetes help text, the regular expression it uses is:
  //
  //	[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
  //
  // This follows the above regular expression (but requires a full string match, not partial).
  //
  // The Kubernetes documentation is here, though it is not entirely correct:
  // https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  func ValidateMetadataName(name string) error {
	  if name == "" || len(name) > maxMetadataNameLen || !validName.MatchString(name) {
		  return errInvalidKubernetesName
	  }
	  return nil
  }

// validName is a regular expression for resource names.
//
// According to the Kubernetes help text, the regular expression it uses is:
//
//	[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
//
// This follows the above regular expression (but requires a full string match, not partial).
//
// The Kubernetes documentation is here, though it is not entirely correct:
// https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
var validName = regexp.MustCompile(`^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`)
```
It's clear that helmv3（after release-3.3） check all the name value  under metadata domain with RFC 1123.  It simply assume that  all the kubernetes-object name obey the RFC 1123 rule. However, kubernetes does not require all the object's metadata name obey the RFC 1123. Just like 
[rbac name-ValidateRBACName](https://github.com/kubernetes/kubernetes/blob/585fc57cc7aaf73baf6aef84bf6dab65bde0ef9e/pkg/apis/rbac/validation/validation.go#L32)
[UT](https://github.com/popozy/kubernetes/commit/7a30db1fb52cb2cc9df5ba8dc89b42acf11fb9d6)

I think helmv3 deal with the metadata name too simply and rudely. Shall we keep track of Kubernetes'  step?

**Comment by sbose78** [comment] 2021-01-07 15:49
Thank you for the in-depth analysis @popozy . This was recently reported in https://github.com/helm/helm/issues/9197 as well. 

> rbac name-ValidateRBACName
UT

Links are helpful!

**Comment by bacongobbler** [comment] 2021-01-07 16:16
closing as a duplicate of #9197.

**Closed by bacongobbler** 2021-01-07 16:16 UTC
