### ISSUE TITLE
[Question/Support] Migrating from chart apiVersion v1 to v2

### ISSUE THREAD

**Issue by vivekzhere** [helm/helm#8161] opened 2020-05-19 06:54 UTC
I have a [helm chart](https://github.com/cloudfoundry-incubator/service-fabrik-broker/tree/master/helm-charts/interoperator) which uses chart apiVersion `v1`.  The chart installs some CRDs. When I created the chart, the CRDs were directly added as templates. I did not use the [helm2 best practices](https://v2.helm.sh/docs/chart_best_practices/#custom-resource-definitions) of using `crd-install` hook. 

Now I want to migrate to chart  apiVersion  `v2` and use the the `crds` directory according to the [helm3 best practices](https://helm.sh/docs/chart_best_practices/custom_resource_definitions). But I have existing `releases` running which has many instances of the custom resource already created. So when I try to move the crds to the `crds` folder, the upgrade of the existing release causes problems. The upgrade first tries to delete the crds and then creates them again.

Is there some way I can do the migration so that existing releases can be upgraded?

**Comment by bacongobbler** [comment] 2020-05-19 14:25
Duplicate of #8163.

**Closed by bacongobbler** 2020-05-19 14:25 UTC

**Comment by bacongobbler** [comment] 2020-05-19 15:26
Also found an older set of issues. This is a duplicate of https://github.com/helm/helm/issues/7279. See the following for more information:

https://github.com/helm/helm/issues/7279
https://github.com/helm/helm/pull/7320
https://github.com/helm/helm/issues/7505
https://github.com/helm/helm/pull/7571
