### ISSUE TITLE
Unable to build kubernetes objects from current release manifest

### ISSUE THREAD

**Issue by matfiz** [helm/helm#7361] opened 2020-01-08 21:52 UTC
After upgrading to kubernetes 1.16.3, I am not able to upgrade some of my charts. The regular upgrade command: 
```sh
helm upgrade my-chart .
```
returns:
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

I am not able to delete a chart, is there a way to get rid of this `apps/v1beta2`, that is not supported for `StatefulSet` in 1.16.3 any more?

What I've checked already:
* `helm template .` does not include a string `apps/v1beta2`
* when I `helm install my-chart-copy .`, then it works

Output of `helm version`:
```
Version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Bare metal (Rancher)

**Comment by bacongobbler** [comment] 2020-01-08 23:46
have a look at https://github.com/helm/helm/issues/7219. Closing as a duplicate of that issue. Thanks!

**Closed by bacongobbler** 2020-01-08 23:46 UTC
