### ISSUE TITLE
Dependencies: Resolve version when only URL is known

### ISSUE THREAD

**Issue by mattfarina** [helm/helm#8449] opened 2020-07-14 12:21 UTC
Currently, when is resolving dependencies and a dependency is specified as a URL but it has not been added to Helm via `helm repo add` the dependency is locked to the exact value specified for the requested dependency. If the specified value is a range (e.g., `^1.2.3) the range is the version it is locked to.

The current situation creates a situation where locking isn't really locked to a version.

With more distributed repos that cross link each other this problem has the potential to get worse.

Instead of locking to the range, Helm should work out the version and lock to the version.

I would suggest the steps:

1. If not cached locally via `helm repo add`, create an automated and not-visible to the user cache.
2. Resolve the version from this invisible cache
3. Lock to the version
4. Clean up any invisible caches (periodically?)

**Comment by technosophos** [comment] 2020-07-14 18:30
If we are talking about the lockfile, then I :100: agree. We should NEVER lock to a range, as that makes reproducible builds sketchy at best.

The issue above was one of the reasons why I argued for a long time that all repositories must have a named local repo cache. I did not like the implementation that was merged using URLs directly with no cache.

So this proposal is much closer to the way Helm was intended to work. I am okay with it, and would be even happier if these caches were not invisible. I don't see a reason to hide sources from users. (Other package managers don't do that, so I don't see why we should.)

The push-back I have heard that "helm shouldn't write cache data to the local filesystem" is a non-starter here. That's based on an exceedingly niche use case (CI in which no writable volumes are attached), and we should not design Helm around those cases to the detriment of the vast majority of our user population.

**Comment by mattfarina** [comment] 2020-07-15 15:06
I'm marking this as a bug. A lock file should lock to a specific version. If a range is ending up in the lock file it's not actually locked.

**Comment by bacongobbler** [comment] 2020-07-15 15:12
Apologies for mis-reading the OP. I agree adding a semver range to the lockfile is a bug.

**Comment by mattfarina** [comment] 2020-07-16 17:02
My current working question.... `helm dependency build` causes an error if a repository is specified but has not been set with `helm repo add`. Should `helm dep up` have the same error or should it attempt to get the repo and figure things out?

The reason I'm asking this question is that numerous people using CI will likely run into new failures as they have not run `helm repo add` but it works today.

**Comment by technosophos** [comment] 2020-07-16 17:31
Again, I am going to be bitter and argue that my _intention_ was that repos would always have to be added first. So I _want_ to say that the current behavior is a bug. However, the people who created the feature did intend for the current case to work as it does. So, in good conscience we would have to call it a breaking change. I guess we could silently auto-add repos... maybe?

**Comment by paulczar** [comment] 2020-07-16 17:56
reading through this thread after the call, I'm leaning towards what @technosophos just suggested for silenting adding repo if it can.  We can perhaps add a (better named) `--disable-auto-add-dep-repo` flag that could disable the behavior which would then cause it fall back to throwing an error.

**Comment by mattfarina** [comment] 2020-07-16 19:02
@paulczar I'm hesitant to add more feature flags for less than 1% of users. What's the use case for someone using the flag?

**Comment by hickeyma** [comment] 2020-07-17 07:35
These are other issues related to the repo resolution issue that I can see:
#7214 (PR #7242) [closed as not reproducible until #8036]
#8118 
#8036 (PR #7242 re-opened which seems a fix for this)

From what I have seen, there seems to be a lot of permutations how this issue can occur.

**Closed** 2020-07-23 19:43 UTC
Labels: bug
