### ISSUE TITLE
helm package is returning "Error: Version segment starts with 0"

### ISSUE THREAD

**Issue by paulbsch** [helm/helm#7064] opened 2019-11-25 03:03 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

This is very strange.  The above error suddenly started happening despite not changing the helm v3 binary or the helm chart.  I'm not seeing this issue with helm v2.

**Comment by bacongobbler** [comment] 2019-11-25 03:45
Can you share the package that is causing the failure? We need a way to reproduce the issue in order to test.

**Comment by paulbsch** [comment] 2019-11-25 03:52
Yes.  It can be found here:
https://github.com/nimbix/jarvice-helm

**Comment by paulbsch** [comment] 2019-11-25 03:56
Also, the error does not seem to occur unless I specify version info.  Example:
helm package ./jarvice --app-version 3.0.0 --version 3.0.0-1.20191125.021

**Comment by paulbsch** [comment] 2019-11-25 04:00
More details.  helm package seem to not work when using a --version like:
3.0.0-1.20191125.0210

But it does work with:
3.0.0-1.20191125.2211

The "0210" segment appears to be the problem.

**Comment by bacongobbler** [comment] 2019-11-25 05:15
This appears correct to me. Helm chart versions follow semver 2 for version constraints. According to https://semver.org/#spec-item-9:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by bacongobbler** [comment] 2019-11-25 05:36
Closing as intended according to semver 2.

**Closed by bacongobbler** 2019-11-25 05:36 UTC

**Comment by paulbsch** [comment] 2019-11-25 13:46
What you cited does not say that a "segment" cannot start with a zero.  This isn't a leading zero for the entire version.  As I mentioned, this works with helm v2.  Helm v3 should not change the behavior.  We've been using versioning like this for well over a year.  One would not expect this to suddenly change.

**Comment by oocx** [comment] 2021-02-08 09:50
@bacongobbler 

> Closing as intended according to semver 2.

Semver says "*Numeric* identifiers MUST NOT include leading zeroes. ". For non-numeric identifiers, a leading zero is valid. For example, we use major.minor.patch-commitHash.

The commit hash is not a numeric identifier, it is alphanumeric, so it may contain a leading zero. I just ran into this problem because a commit started with a 0 in the commit hash.

Please reopen and fix the issue.

**Comment by bacongobbler** [comment] 2021-02-08 15:16
Please open a ticket with the masterminds/semver  project. That is the library that checks and enforces this logic.
