### ISSUE TITLE
Helm not upgrading deployments when apiVersion changes

### ISSUE THREAD

**Issue by lbolla** [helm/helm#6685] opened 2019-10-17 15:00 UTC
I just upgraded my k8s to v1.16, and updated my deployment manifests to have `apiVersion: apps/v1` instead of the deprecated `apiVersion: extensions/v1beta1`.

Running `helm upgrade` though doesn't seem to affect the existing deployment manifests. I would expect the new `apiVersion` to show up in production, but it doesn't. I also tried to add a dummy "label" to the deployment, to make sure it was updated, and the new label showed up. So, it's something specific to `apiVersion`.

Maybe I'm using an old version of Helm?

```» helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment] 2019-10-17 15:54
duplicate of https://github.com/helm/helm/issues/6583.

**Closed by bacongobbler** 2019-10-17 15:54 UTC
