### ISSUE TITLE
Linter errors for template yaml files containing nothing but comments

### ISSUE THREAD

**Issue by joejulian** [helm/helm#8947] opened 2020-10-27 16:28 UTC
https://github.com/helm/helm/blob/82f739072cb3c94f26e3103e4524a1f74526342d/pkg/lint/rules/template.go#L118
In the above line linting checks occur if the rendered file is not empty. Some of the checks are invalid if the only content is comments:

```
# Rules for alerting against etcd, without the etcd alerts: etcdHighNumberOfFailedGRPCRequests
# Which at the moment are false positives at a rate of 100%
{{- if and .Values.mesosphereResources.create .Values.mesosphereResources.rules.etcd }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "prometheus-operator.fullname" .) "etcd" | trunc 63 | trimSuffix "-" }}
...
{{-end}}
```
When linting, if the conditional disables the yaml content, the comments remain. This triggers the error:
```
[ERROR] templates/prometheus/rules/mesosphere-rules/etcd-rules.yaml: object name must be between 0 and 253 characters: ""
```
I believe commented lines should be stripped from the test at the line referenced above.

**Comment by bacongobbler** [comment] 2020-10-27 16:45
duplicate of https://github.com/helm/helm/issues/8621.

**Closed by bacongobbler** 2020-10-27 16:45 UTC
