### ISSUE TITLE
helm init failed, i cant add the official stable repo

### ISSUE THREAD

**Issue by louleilei** [helm/helm#4641] opened 2018-09-14 09:08 UTC
i cant add the official repo , though i set the http_proxy and https_proxy. the respose is  
`Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.161.144:443: connect: connection timed out`
And i also cant add repo of Aliyun . 
`Error: Looks like "https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts/" is not a valid chart repository or cannot be reached: Get https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts/index.yaml: dial tcp 183.131.227.235:443: connect: connection timed out`
but,i can curl the url https://kubernetes-charts.storage.googleapis.com/index.yaml and https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts/index.yaml.
so ,it looks like the proxy is not used.
Output of `helm version`:
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:19:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment] 2018-09-14 14:39
Yep, there was a bug in v2.10.0 that caused proxy settings to not be respected.

Closing as a duplicate of #4326 which has been fixed in master and will be available in v2.11.0. There are workarounds described in that ticket for the time being. Thanks!

**Closed by bacongobbler** 2018-09-14 14:39 UTC
