### ISSUE TITLE
Helm3-rc.1 OpenAPI validation mistaking optional for required

### ISSUE THREAD

**Issue by rblaine95** [helm/helm#6830] opened 2019-10-30 09:24 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}
```
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-26T18:51:37Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Self-hosted OKD v3.11
```
» oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://okd.example..net:8443
openshift v3.11.0+fef6f83-275
kubernetes v1.11.0+d4cacc0
```

**Issue:**
When using a Helm Chart that has an OKD route (`apiVersion: route.openshift.io/v1`) that has several optional fields (`spec.host`, `status`, `spec.to.weight`) Helm 3 RC1 will give the following errors:
```
» ./helm template . --validate
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Route.spec.to): missing required field "weight" in com.github.openshift.api.route.v1.RouteTargetReference, ValidationError(Route.spec): missing required field "host" in com.github.openshift.api.route.v1.RouteSpec, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]
```
Referring to the OKD Route [Docs](https://docs.okd.io/3.11/dev_guide/routes.html) and [API](https://docs.okd.io/3.11/rest_api/apis-route.openshift.io/v1.Route.html), the `Route.spec.host`, `Route.status`, and `Route.spec.to.weight` fields are optional.

Is there a way to disable OpenAPI Validation when running `helm install`?
```
» ./helm install chart-with-route .
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Route.spec.to): missing required field "weight" in com.github.openshift.api.route.v1.RouteTargetReference, ValidationError(Route.spec): missing required field "host" in com.github.openshift.api.route.v1.RouteSpec, ValidationError(Route): missing required field "status" in com.github.openshift.api.route.v1.Route]
```
**Edit:**
Maybe `helm install [NAME] [CHART] [flags] --validate=false`

**Comment by bacongobbler** [comment] 2019-10-30 16:54
Looking at the OpenAPI spec for v1.RouteSpec, this seems to be true on their end. I'm curious to know why it's marked as required according to the OpenAPI spec.

Pasting the section of the OpenAPI spec I found from looking under https://raw.githubusercontent.com/openshift/origin/v3.11.0/api/swagger-spec/oapi-v1.json

```
"v1.RouteSpec": {
    "id": "v1.RouteSpec",
    "description": "RouteSpec describes the hostname or path the route exposes, any security information, and one to four backends (services) the route points to. Requests are distributed among the backends depending on the weights assigned to each backend. When using roundrobin scheduling the portion of requests that go to each backend is the backend weight divided by the sum of all of the backend weights. When the backend has more than one endpoint the requests that end up on the backend are roundrobin distributed among the endpoints. Weights are between 0 and 256 with default 1. Weight 0 causes no requests to the backend. If all weights are zero the route will be considered to have no backends and return a standard 503 response.\n\nThe `tls` field is optional and allows specific certificates or behavior for the route. Routers typically configure a default certificate on a wildcard domain to terminate routes without explicit certificates, but custom hostnames usually must choose passthrough (send traffic directly to the backend via the TLS Server-Name- Indication field) or provide a certificate.",
    "required": [
     "host",
     "to"
    ],
    "properties": {
     "host": {
      "type": "string",
      "description": "host is an alias/DNS that points to the service. Optional. If not specified a route name will typically be automatically chosen. Must follow DNS952 subdomain conventions."
     },
```

I would urge you to find out why OKD's OpenAPI spec is marking this field as required. Disabling OpenAPI validation can lead to significant update errors down the road.

**Comment by bacongobbler** [comment] 2019-10-30 19:31
Closing as this is working as intended. This is a bug on OKD's end.

**Closed by bacongobbler** 2019-10-30 19:31 UTC
Labels: question/support, v3.x
