### ISSUE TITLE
icon field in Chart.yaml should support a  base64 encoded string

### ISSUE THREAD

**Issue by elpadrinoIV** [helm/helm#5258] opened 2019-02-04 18:33 UTC
Currently the field `icon` only supports an url.

The proposal is to accept a base64 encoded string with the icon (with length limit).
It could be either the same field or another one.

This will allow to:

 * Version the icon file
 * Allow icons that are not publicly available

**Comment by bacongobbler** [comment] 2019-02-04 18:47
closing as a duplicate of https://github.com/helm/helm/issues/2943

**Closed by bacongobbler** 2019-02-04 18:47 UTC

**Comment by metal3d** [comment] 2019-07-09 16:51
@bacongobbler this is not a "duplicate", to be able to use data url encoded image is not the same as using the string as "image" IMHO

**Comment by bacongobbler** [comment] 2019-07-09 17:08
it's the same use case: the user wants to embed an icon in the chart metadata. Whether that's packaged as part of the chart or base-64 encoded as a string doesn't make much difference from an implementation standpoint.
