### ISSUE TITLE
Helm --dry-run should hide secrets

### ISSUE THREAD

**Issue by gadelkareem** [helm/helm#7399] opened 2020-01-14 14:19 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Kubespray

In jenkins, we usually plan the deployment first using `helm install --dry-run` to debug the deployment before deploy. However, the debug info contains the secrets from the chart which we do not want to store it in Jenkins logs. 

How can we avoid displaying the secrets while running `helm install --dry-run`?

**Comment by hickeyma** [comment] 2020-01-14 14:30
Closing as duplicate of #7275

**Closed** 2020-01-14 14:32 UTC
