### ISSUE TITLE
During `helm upgrade`, Tiller chooses the wrong current revision to generate patches from when the previous upgrade failed

### ISSUE THREAD

**Issue by robinkb** [helm/helm#4045] opened 2018-05-14 09:03 UTC
I typed up a long test rapport to find and reproduce the issue, so I'll just copy-paste the relevant stuff here. I had 4 test cases in total, and case 3 turned out to be the one that reproduces the issue.

# Issue

We started from an existing, successful installation. The next installation failed,
because the wrong values were passed to the Helm chart. The tag of a container image was incorrect,
resulting in an ImagePullBackOff error on a few pods. It took several tries (and failed upgrades)
to get the values right, but they were eventually successfully corrected.

However, when the correct values *were* supplied, the cluster state was not changed
to reflect the expected result. It seemed like Pods were not being redeployed,
despite the Deployment manifests rendering correctly in Tiller.

# Setup

Kubernetes was setup using Minikube. The Kubernetes version is v1.10.0.

```
$ minikube start --kubernetes-version v1.10.0 --cpus 4 --memory 6144
```

Tiller was installed using Helm version 2.9.0.

```
$ helm init --wait --history-max 10
$ helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

We use `helm upgrade` to both install and upgrade charts,
to stay in line with how charts are installed by the CI.

We create a minimal, fresh chart for testing purposes.

```
$ helm create test-chart-2
Creating test-chart-2
$ rm test-chart-2/templates/*
$ truncate -s0 test-chart-2/values.yaml
```

Add a template for an Nginx Deployment. The tag is configurable through the `tag` value.

```yaml
# test-chart-2/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:{{ .Values.tag }}
```

Perform the initial installation, passing the tag as user-supplied value.

```
$ helm upgrade --debug --install --wait test-case-3 test-chart-2/ --set=tag=1.14.0
[debug] Created tunnel using local port: '33497'

[debug] SERVER: "127.0.0.1:33497"

Release "test-case-3" does not exist. Installing it now.

NAME:   test-case-3
REVISION: 1
RELEASED: Fri May 11 12:58:50 2018
CHART: test-chart-2-0.1.0
USER-SUPPLIED VALUES:
tag: 1.14.0

COMPUTED VALUES:
tag: 1.14.0

HOOKS:
MANIFEST:

---
# Source: test-chart-2/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:1.14.0
LAST DEPLOYED: Fri May 11 12:58:50 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta2/Deployment
NAME   DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
nginx  1        1        1           1          4s

==> v1/Pod(related)
NAME                    READY  STATUS   RESTARTS  AGE
nginx-84d47458c6-jmr5g  1/1    Running  0         4s
```

`kubectl` shows the one running Pod.

```
$ kubectl get pods
NAME                     READY     STATUS    RESTARTS   AGE
nginx-84d47458c6-jmr5g   1/1       Running   0          16s
```

`helm history` shows one revision, which deployed successfully.

```
$ helm history test-case-3
REVISION	UPDATED                 	STATUS  	CHART             	DESCRIPTION
1       	Fri May 11 12:58:50 2018	DEPLOYED	test-chart-2-0.1.0	Install complete
```

Upgrade to a second revision, with an invalid tag. The Deployment will get stuck.

```
$ helm upgrade --debug --install --wait --timeout 60 test-case-3 test-chart-2/ --set=tag=1.14.100
[debug] Created tunnel using local port: '42003'

[debug] SERVER: "127.0.0.1:42003"
```

The output of `kubectl` shows the Pod causing the Deployment to be stuck.

```
$ kubectl get pods
NAME                     READY     STATUS             RESTARTS   AGE
nginx-5758bd8dd7-mn88p   0/1       ImagePullBackOff   0          1m
nginx-84d47458c6-jmr5g   1/1       Running            0          4m
```

The status of revision 2 is now marked as FAILED. This is different from when the `--wait` flag is not used.

```
$ helm history test-case-3
REVISION	UPDATED                 	STATUS  	CHART             	DESCRIPTION
1       	Fri May 11 12:58:50 2018	DEPLOYED	test-chart-2-0.1.0	Install complete
2       	Fri May 11 13:02:01 2018	FAILED  	test-chart-2-0.1.0	Upgrade "test-case-3" failed: timed out waiting for the c...
```

Install revision 3 using the very same command used to install revision 1.

```
$ helm upgrade --debug --install --wait test-case-3 test-chart-2/ --set=tag=1.14.0
```

`helm history` shows that Tiller marked revision 3 as failed, even though the supplied values were known to be good, as shown in revision 1.

```
$ helm history test-case-3
REVISION	UPDATED                 	STATUS  	CHART             	DESCRIPTION
1       	Fri May 11 19:43:05 2018	DEPLOYED	test-chart-2-0.1.0	Install complete
2       	Fri May 11 19:43:29 2018	FAILED  	test-chart-2-0.1.0	Upgrade "test-case-3" failed: timed out waiting for the c...
3       	Fri May 11 19:44:36 2018	FAILED  	test-chart-2-0.1.0	Upgrade "test-case-3" failed: timed out waiting for the c...
```

Fetching the Deployment manifest from Kubernetes shows that is has not changed
from the template rendered for revision 2. It still has the wrong Nginx tag.

```yaml
$ kubectl get deployment nginx -o yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/library/nginx:1.14.100
        name: nginx
```

Fetching the generated manifests from Tiller for revision 3 shows that the manifests were rendered correctly, but Tiller failed to generate patches.

```yaml
$ helm get manifests test-case-3 --revision 3

REVISION: 3
RELEASED: Fri May 11 19:44:36 2018
CHART: test-chart-2-0.1.0
USER-SUPPLIED VALUES:
tag: 1.14.0

COMPUTED VALUES:
tag: 1.14.0

HOOKS:
MANIFEST:

---
# Source: test-chart-2/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:1.14.0
```

This is confirmed by Tiller's logs.

```
$ -n kube-system logs tiller-deploy-757f965749-2bklb
...
[tiller] 2018/05/11 17:44:36 getting history for release test-case-3
[storage] 2018/05/11 17:44:36 getting release history for "test-case-3"
[tiller] 2018/05/11 17:44:36 preparing update for test-case-3
[storage] 2018/05/11 17:44:36 getting deployed releases from "test-case-3" history
[storage] 2018/05/11 17:44:36 getting last revision of "test-case-3"
[storage] 2018/05/11 17:44:36 getting release history for "test-case-3"
[tiller] 2018/05/11 17:44:36 rendering test-chart-2 chart using values
[tiller] 2018/05/11 17:44:36 creating updated release for test-case-3
[storage] 2018/05/11 17:44:36 creating release "test-case-3.v3"
[storage] 2018/05/11 17:44:36 getting release history for "test-case-3"
[tiller] 2018/05/11 17:44:36 performing update for test-case-3
[tiller] 2018/05/11 17:44:36 executing 0 pre-upgrade hooks for test-case-3
[tiller] 2018/05/11 17:44:36 hooks complete for pre-upgrade test-case-3

[kube] 2018/05/11 17:44:36 building resources from updated manifest
[kube] 2018/05/11 17:44:36 checking 1 resources for changes
[kube] 2018/05/11 17:44:36 Looks like there are no changes for Deployment "nginx"

[kube] 2018/05/11 17:44:36 beginning wait for 1 resources with timeout of 5m0s
[kube] 2018/05/11 17:44:38 Deployment is not ready: default/nginx
[kube] 2018/05/11 17:44:40 Deployment is not ready: default/nginx
[kube] 2018/05/11 17:44:42 Deployment is not ready: default/nginx
...
```

Running the upgrade again with the exact same command as revision 3 does not fix the issue,
because Tiller keeps comparing the newly supplied manifests to revision 1. Because revision 3
is exactly the same as revision 1, Tiller does not correctly generate the patches for Kubernetes,
even though the state of the cluster does not match revision 1.

Re-running the upgrade with the command used for revision 2 (with the wrong tag), does make Tiller recognize the changes, because revision 2 is indeed different from revision 1. What's funny is that revision 2 is actually the state of the cluster, so from Kubernetes' standpoint, revision 2 *does not* contain changes.

This behaviour does not show up without the `--wait` flag, because Tiller immediately marks any successfully rendered release as `DEPLOYED`, regardless if the installation failed or not. Because of this behaviour, the manifests saved by Tiller actually matches those that are present in Kubernetes.

# Root Cause

Tiller actually does not apply complete manifests to Kubernetes, but uses a Kubernetes library to build patches based on a previous revision.

The following code snippet is the high-level function in Tiller that executes updates of releases.

```go
// helm/pkg/tiller/release_update.go

// UpdateRelease takes an existing release and new information, and upgrades the release.
func (s *ReleaseServer) UpdateRelease(c ctx.Context, req *services.UpdateReleaseRequest) (*services.UpdateReleaseResponse, error) {
	if err := validateReleaseName(req.Name); err != nil {
		s.Log("updateRelease: Release name is invalid: %s", req.Name)
		return nil, err
	}
	s.Log("preparing update for %s", req.Name)
	currentRelease, updatedRelease, err := s.prepareUpdate(req)
	if err != nil {
		if req.Force {
			// Use the --force, Luke.
			return s.performUpdateForce(req)
		}
		return nil, err
	}

	if !req.DryRun {
		s.Log("creating updated release for %s", req.Name)
		if err := s.env.Releases.Create(updatedRelease); err != nil {
			return nil, err
		}
	}

	s.Log("performing update for %s", req.Name)
	res, err := s.performUpdate(currentRelease, updatedRelease, req)
	if err != nil {
		return res, err
	}

	if !req.DryRun {
		s.Log("updating status for updated release for %s", req.Name)
		if err := s.env.Releases.Update(updatedRelease); err != nil {
			return res, err
		}
	}

	return res, nil
}
```

The function where the patches are generated is `prepareUpdate`, seen in the snippet below.

```go
// helm/pkg/tiller/release_update.go
func (s *ReleaseServer) prepareUpdate(req *services.UpdateReleaseRequest) (*release.Release, *release.Release, error) {
	if req.Chart == nil {
		return nil, nil, errMissingChart
	}

	// finds the deployed release with the given name
	currentRelease, err := s.env.Releases.Deployed(req.Name)
	if err != nil {
		return nil, nil, err
	}

	// determine if values will be reused
	if err := s.reuseValues(req, currentRelease); err != nil {
		return nil, nil, err
	}

	// finds the non-deleted release with the given name
	lastRelease, err := s.env.Releases.Last(req.Name)
	if err != nil {
		return nil, nil, err
	}

	// Increment revision count. This is passed to templates, and also stored on
	// the release object.
	revision := lastRelease.Version + 1

	ts := timeconv.Now()
	options := chartutil.ReleaseOptions{
		Name:      req.Name,
		Time:      ts,
		Namespace: currentRelease.Namespace,
		IsUpgrade: true,
		Revision:  int(revision),
	}

	caps, err := capabilities(s.clientset.Discovery())
	if err != nil {
		return nil, nil, err
	}
	valuesToRender, err := chartutil.ToRenderValuesCaps(req.Chart, req.Values, options, caps)
	if err != nil {
		return nil, nil, err
	}

	hooks, manifestDoc, notesTxt, err := s.renderResources(req.Chart, valuesToRender, caps.APIVersions)
	if err != nil {
		return nil, nil, err
	}

	// Store an updated release.
	updatedRelease := &release.Release{
		Name:      req.Name,
		Namespace: currentRelease.Namespace,
		Chart:     req.Chart,
		Config:    req.Values,
		Info: &release.Info{
			FirstDeployed: currentRelease.Info.FirstDeployed,
			LastDeployed:  ts,
			Status:        &release.Status{Code: release.Status_PENDING_UPGRADE},
			Description:   "Preparing upgrade", // This should be overwritten later.
		},
		Version:  revision,
		Manifest: manifestDoc.String(),
		Hooks:    hooks,
	}

	if len(notesTxt) > 0 {
		updatedRelease.Info.Status.Notes = notesTxt
	}
	err = validateManifest(s.env.KubeClient, currentRelease.Namespace, manifestDoc.Bytes())
	return currentRelease, updatedRelease, err
}
```

The problematic line is `currentRelease, err := s.env.Releases.Deployed(req.Name)`, which fetches
the currently deployed release from Tiller's storage.

The `s.env.Releases.Deployed` refers to the snippet below, which in turn uses the `DeployedAll` function.

```go
// helm/pkg/storage/storage.go

// Deployed returns the last deployed release with the provided release name, or
// returns ErrReleaseNotFound if not found.
func (s *Storage) Deployed(name string) (*rspb.Release, error) {
	ls, err := s.DeployedAll(name)
	if err != nil {
		if strings.Contains(err.Error(), "not found") {
			return nil, fmt.Errorf("%q has no deployed releases", name)
		}
		return nil, err
	}

	if len(ls) == 0 {
		return nil, fmt.Errorf("%q has no deployed releases", name)
	}

	return ls[0], err
}

// DeployedAll returns all deployed releases with the provided name, or
// returns ErrReleaseNotFound if not found.
func (s *Storage) DeployedAll(name string) ([]*rspb.Release, error) {
	s.Log("getting deployed releases from %q history", name)

	ls, err := s.Driver.Query(map[string]string{
		"NAME":   name,
		"OWNER":  "TILLER",
		"STATUS": "DEPLOYED",
	})
	if err == nil {
		return ls, nil
	}
	if strings.Contains(err.Error(), "not found") {
		return nil, fmt.Errorf("%q has no deployed releases", name)
	}
	return nil, err
}
```

The function `DeployedAll` is used during the upgrade process to retrieve the currently deployed  release. Because a release that is marked `FAILED` is never retrieved by this function, a failed release can never be used as a comparison point for generating patches, even though a failed release might be what is installed to Kubernetes.

I considered patching this myself, but this seems like an issue that has a lot of pitfalls, and I am familiar with neither Tiller's codebase, nor Golang.

I went through a few other, existing issues, and some of them seem to be caused by this same bug.

For example, the `DeployedAll` function is also why a user cannot upgrade from a failed first installation, but must first run `helm delete`.

**Comment by SlickNik** [comment] 2018-05-16 08:44
Thanks for the write up of the issue and the detailed root-cause analysis, @robinkb!

**Comment by paolomainardi** [comment] 2018-07-17 14:43
Thanks a lot @robinkb for you analysis.
We face randomly this bug and most of the times the thing that just works is to delete (--purge) everything related to that release and starting from scratch, this is becoming very annoying .

**Comment by swistaczek** [comment] 2018-08-04 18:29
This need to be fixed ;(!

**Comment by secat** [comment] 2018-08-08 12:03
As an operator, the current workaround that I have found so far is if an upgrade fails, I cleanup all resources that have the annotation `helm.sh/hook` and I delete the latest release revision configmap (or secret depending of your Tiller deployment) generated by Tiller.

By example, if you have a `foo` release with 3 revisions:
```bash
# we assume that Tiller is installed into kube-system in this example
$ kubectl --namespace=kube-system get cm
[...]
foo.v1
foo.v2
foo.v3
```
In this example, if the latest revision is mark has failed (you could see this by running `helm list --failed`), you can delete the configmap `foo.v3`:
```
$ kubectl --namespace=kube-system delete cm foo.v3
```

If your chart had some bugs, fix them and relaunch the upgrade.

**Comment by Nopik** [comment] 2018-08-12 13:17
I'm getting bitten by this very often, using helm with this bug is pretty frustrating. Every time I make a mistake in chart, and helm fails, I have to delete resources manually. Sometimes the list of resources is pretty long. It finally made me to learn Go basics, compile Tiller myself and play with its internals.

Indeed, it looks like the autorollback feature (discussed on some other issue) would be the solution. Or,  the flag to diff against live cluster could be used as good-enough workaround, as discussed in #4223.

I made my own changes, to automatically re-use existing live resource in case it is not found in old manifest, you can find the code in https://github.com/Nopik/helm/commit/afe6451cc2c6295e71ea2213ccce654ec3f5b686 - but, I do believe, that this behaviour should be behind a flag, so I'm not issuing PR myself (I'm afraid, I'm not familiar with Tiller internals and golang enough to work on it).

**Comment by novas0x2a** [comment] 2019-01-29 08:08
We're also getting bitten by this. I'm trying to understand the logic behind diffing against the most recent DEPLOYED instead of just the most recent chart. So, with that in mind: two different failure scenarios (and for the moment, let's pretend there is only one resource):

Scenario A:
1) Chart is installed and becomes DEPLOYED (v1)
2) Chart is upgraded, live state is applied, Wait fails (release does not become ready by deadline), v2 is FAILED, live state matches v2
3) Chart is rolled back to v1 (generating v3), but the diff is `diff v1 v1` so an empty diff is applied. v3 is FAILED, live state still matches v2.

Scenario B:
1) Chart is installed and becomes DEPLOYED (v1)
2) Chart is upgraded, but kube rejects the change (invalid manifest, say). Release is FAILED, live state matches v1.
3) Chart is rolled back to v1 (generating v3), diff is still `diff v1 v1` so an empty diff is applied, which is fine in this case because the live state was still correct. v3 is DEPLOYED, live state matches v1 (and v3).

In scenario B, "diff against most recent successful deploy" certainly seems like the correct plan. However, in scenario A, that same plan will always fail, and the problem is unrecoverable. Scenario A would prefer that the plan would be "diff against the most recent deploy regardless of status." since "most recent deploy" most likely represents the closest to live state. Unfortunately, these plans conflict :)

#3805 would certainly be the best solution to this (a 3-way merge against live state), but that's in limbo. I'm not sure I see a better way than that, though...

**Comment by nickdgriffin** [comment] 2019-07-31 15:45
I think the same case occurs when it comes to Deployment resources though and failures caused by their ReplicaSets, for example:

1. Helm installs a chart successfully, everything is fine and it gets marked as "DEPLOYED" - the Deployment has maxUnavailable set to 50%
1. An upgrade is carried out which makes changes to both the Deployment to set maxUnavailable to 25% and the Pod template with a new image ID - this fails because of the Pods, causing Helm to time out waiting for the pods and the release to be marked as "FAILED"
1. Another upgrade is carried out, containing an update to the maxUnavailable to set it to 50% again and to the Pod template with another new image ID - but the Deployment resource never gets updated because of the comparison with revision 1 which matches

Doing "helm get" on revision 3 in the above example returns what one would expect the outcome to be, but the actual Deployment resource outside of the Pod template is actually at revision 2 because the diff of v1 to v1 comes out the same.

**Comment by robinkb** [comment] 2019-11-21 08:05
Good news!

I can no longer reproduce this problem with Helm 3. I presume that the implementation of 3-way merge patching has resolved this bug.

@SlickNik Is it okay to close this issue? It is solved in Helm 3, but the problem is still present in Helm 2.16.1. Considering Helm 2 is still supported, it might be good to keep this issue open in case anyone runs into the same problem.

**Comment by bacongobbler** [comment] 2020-05-14 21:34
closing as inactive.

**Closed by bacongobbler** 2020-05-14 21:34 UTC
Labels: bug
