### ISSUE TITLE
helm3.0.0 fetch command produces waste

### ISSUE THREAD

**Issue by jianzzz** [helm/helm#7325] opened 2020-01-02 09:30 UTC
Output of `helm version`:
3.0.0

`helm fetch xxx` produces temporary index.yaml under ~/.cache/helm/repository/, and there was no automatic cleaning of it.

**Comment by bacongobbler** [comment] 2020-01-09 16:37
Can you demonstrate a set of commands to run to reproduce what you are seeing?

**Comment by bridgetkromhout** [comment] 2020-08-25 16:01
Hi, @jianzzz - we need further information before we can try to reproduce this problem. Closing due to lack of reply.

**Closed by bridgetkromhout** 2020-08-25 16:01 UTC
Labels: question/support
