### ISSUE TITLE
Helm package cannot consistently create the same package

### ISSUE THREAD

**Issue by FrenchBen** [helm/helm#10177] opened 2021-09-22 21:45 UTC
When using `helm package` I expect a consistent packaging experience, from the same source. 

Output of `helm version`:
```
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

### Steps to reproduce this

Create a new helm chart, and package it a few times  - I expect the resulting package sha to remain consistent, if no changes are made to the Chart.
```
~ # cd $(mktemp -d)
/tmp/tmp.NnbekK # helm create foo
Creating foo
/tmp/tmp.NnbekK # ls
foo
/tmp/tmp.NnbekK # ls -lah foo/
total 28K
drwxr-xr-x    4 root     root        4.0K Sep 22 21:36 .
drwx------    3 root     root        4.0K Sep 22 21:36 ..
-rw-r--r--    1 root     root         349 Sep 22 21:36 .helmignore
-rw-r--r--    1 root     root        1.1K Sep 22 21:36 Chart.yaml
drwxr-xr-x    2 root     root        4.0K Sep 22 21:36 charts
drwxr-xr-x    3 root     root        4.0K Sep 22 21:36 templates
-rw-r--r--    1 root     root        1.8K Sep 22 21:36 values.yaml
/tmp/tmp.NnbekK # helm package foo
Successfully packaged chart and saved it to: /tmp/tmp.NnbekK/foo-0.1.0.tgz
/tmp/tmp.NnbekK # ls -lah foo-0.1.0.tgz
-rw-r--r--    1 root     root        3.7K Sep 22 21:36 foo-0.1.0.tgz
/tmp/tmp.NnbekK # sha256sum foo-0.1.0.tgz
7390651327b7637b6ca33cc4e8cec954b1469b2773371414e86e0f97321d9f4a  foo-0.1.0.tgz
/tmp/tmp.NnbekK # rm foo-0.1.0.tgz
/tmp/tmp.NnbekK # helm package foo
Successfully packaged chart and saved it to: /tmp/tmp.NnbekK/foo-0.1.0.tgz
/tmp/tmp.NnbekK # sha256sum foo-0.1.0.tgz
40179db700ce551aa92a7aea35768fb778bde0209cf27c54ff0e8d1582e040bb  foo-0.1.0.tgz
```

Meanwhile creating the same via tar, returns a valid-consistent package:
```
/tmp/tmp.NnbekK # tar -zcvf foo-0.1.0.tgz foo/
foo/
foo/templates/
foo/templates/serviceaccount.yaml
foo/templates/deployment.yaml
foo/templates/_helpers.tpl
foo/templates/service.yaml
foo/templates/NOTES.txt
foo/templates/ingress.yaml
foo/templates/hpa.yaml
foo/templates/tests/
foo/templates/tests/test-connection.yaml
foo/charts/
foo/values.yaml
foo/.helmignore
foo/Chart.yaml
/tmp/tmp.NnbekK # sha256sum foo-0.1.0.tgz
62e2671a8830d5c2b86b76ac9bdb46ea162867609170629e9dd5e9ece296cade  foo-0.1.0.tgz
/tmp/tmp.NnbekK # rm foo-0.1.0.tgz
/tmp/tmp.NnbekK # tar -zcvf foo-0.1.0.tgz foo/
foo/
foo/templates/
foo/templates/serviceaccount.yaml
foo/templates/deployment.yaml
foo/templates/_helpers.tpl
foo/templates/service.yaml
foo/templates/NOTES.txt
foo/templates/ingress.yaml
foo/templates/hpa.yaml
foo/templates/tests/
foo/templates/tests/test-connection.yaml
foo/charts/
foo/values.yaml
foo/.helmignore
foo/Chart.yaml
/tmp/tmp.NnbekK # sha256sum foo-0.1.0.tgz
62e2671a8830d5c2b86b76ac9bdb46ea162867609170629e9dd5e9ece296cade  foo-0.1.0.tgz
```

**Comment by bacongobbler** [comment] 2021-09-22 22:31
duplicate of https://github.com/helm/helm/issues/3612.

**Closed by bacongobbler** 2021-09-22 22:31 UTC
