### ISSUE TITLE
[BUG] Helm get script returning incorrect tag

### ISSUE THREAD

**Issue by danyim** [helm/helm#5476] opened 2019-03-20 01:58 UTC
Output of `helm version`:
N/A
Output of `kubectl version`:
N/A
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
N/A

Helm's [`get` script](https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get) captures the incorrect tag from [Github's latest releases page](https://github.com/helm/helm/releases/latest) when `DESIRED_VERSION` isn't specified. This may happen as a result of Github changing their HTML structure.

I am able to reproduce the issue that I see in my CI containers by running the lines found in https://github.com/helm/helm/blob/master/scripts/get#L83 in my shell:
```
$ release_url="https://github.com/helm/helm/releases/${DESIRED_VERSION:-latest}"
$ TAG=$(curl -SsL $release_url | awk '/\/tag\//' | grep -v no-underline | head -n 1 | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}' | awk 'a !~ $0{print}; {a=$0}')
$ echo $TAG
tooltipped-s
```

### See the difference in this partially piped command
**Without DESIRED_VERSION set to a value:**
```
$ release_url="https://github.com/helm/helm/releases/latest"
$ curl -SsL $release_url | awk '/\/tag\//' | grep -v no-underline
      <a class="btn btn-sm btn-with-count tooltipped tooltipped-s" aria-label="You must be signed in to watch a repository" rel="nofollow" data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;notification subscription menu watch&quot;,&quot;repository_id&quot;:null,&quot;auth_type&quot;:&quot;LOG_IN&quot;,&quot;client_id&quot;:null,&quot;originating_request_id&quot;:&quot;F311:0584:4F87D4:796516:5C91A297&quot;,&quot;originating_url&quot;:&quot;https://github.com/helm/helm/releases/tag/v2.13.0&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="dadcffb7ed28f51a4651e553739d24745cdb8a7dbcb2b8382c430ca18d5aa316" href="/login?return_to=%2Fhelm%2Fhelm">
        <a class="btn btn-sm btn-with-count tooltipped tooltipped-s" aria-label="You must be signed in to star a repository" rel="nofollow" data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;star button&quot;,&quot;repository_id&quot;:43723161,&quot;auth_type&quot;:&quot;LOG_IN&quot;,&quot;client_id&quot;:null,&quot;originating_request_id&quot;:&quot;F311:0584:4F87D4:796516:5C91A297&quot;,&quot;originating_url&quot;:&quot;https://github.com/helm/helm/releases/tag/v2.13.0&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="7d63dfdb3d4b5224982da0c572c23d38af355b98d137a3f2e7df72c2e6c91162" href="/login?return_to=%2Fhelm%2Fhelm">
      <a class="btn btn-sm btn-with-count tooltipped tooltipped-s" aria-label="You must be signed in to fork a repository" rel="nofollow" data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;repo details fork button&quot;,&quot;repository_id&quot;:43723161,&quot;auth_type&quot;:&quot;LOG_IN&quot;,&quot;client_id&quot;:null,&quot;originating_request_id&quot;:&quot;F311:0584:4F87D4:796516:5C91A297&quot;,&quot;originating_url&quot;:&quot;https://github.com/helm/helm/releases/tag/v2.13.0&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="64eb711378c8635ef9d94233b2cef6b94916b6bb2139cdd2056675d12482caf5" href="/login?return_to=%2Fhelm%2Fhelm">
          <a class="btn btn-primary" data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;releases signup prompt&quot;,&quot;repository_id&quot;:null,&quot;auth_type&quot;:&quot;SIGN_UP&quot;,&quot;client_id&quot;:null,&quot;originating_request_id&quot;:&quot;F311:0584:4F87D4:796516:5C91A297&quot;,&quot;originating_url&quot;:&quot;https://github.com/helm/helm/releases/tag/v2.13.0&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="76c6b539fe5339efcc2e8d84627d2e56e772691789953e5defdeb220503c97f7" data-ga-click="(Logged out) Sign up prompt, clicked Sign up, text:sign-up" href="/join?source=prompt-releases-show">Sign up</a>
          <a href="/helm/helm/releases/tag/v2.13.0">Helm v2.13.0 - Raspberry Caramel Latte Edition</a>
```

**With DESIRED_VERSION set to a value:**
```
$ release_url="https://github.com/helm/helm/releases/v2.13.0"
$ curl -SsL $release_url | awk '/\/tag\//' | grep -v no-underline
          <a href="/helm/helm/releases/tag/v2.13.0">Helm v2.13.0 - Raspberry Caramel Latte Edition</a>
```

This bug will result in the get script attempting to fetch `https://kubernetes-helm.storage.googleapis.com/helm-tooltipped-s-linux-amd64.tar.gz` as the download, which results in a 404.

**Comment by gleb-britecore** [comment] 2019-03-20 02:30
same for me
```
[Container] 2019/03/20 01:15:21 Running command curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
 % Total % Received % Xferd Average Speed Time Time Time Current
 Dload Upload Total Spent Left Speed
 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
100 7234 100 7234 0 0 566k 0 --:--:-- --:--:-- --:--:-- 588k
 [Container] 2019/03/20 01:15:21 Running command chmod 700 get_helm.sh
 [Container] 2019/03/20 01:15:21 Running command ./get_helm.sh
Downloading https://kubernetes-helm.storage.googleapis.com/helm-tooltipped-s-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-zGJQJl/helm-tooltipped-s-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
 For support, go to https://github.com/helm/helm.
```

**Comment by danyim** [comment] 2019-03-20 02:32
Temporary workaround for us was to add a `DESIRED_VERSION` environment variable in our CI provider.

e.g.:
```
export DESIRED_VERSION=v2.13.0
```

**Comment by danyim** [comment] 2019-03-20 02:51
What would be a better workaround instead of trying to select an HTML value by piping commands together is to read the redirected URL.

For instance, navigating to https://github.com/helm/helm/releases/latest redirects you to https://github.com/helm/helm/releases/tag/v2.13.0

**Comment by danyim** [comment] 2019-03-20 03:05
Not sure if this is possible with `wget`, however.

**Comment by matthalbersma** [comment] 2019-03-20 03:29
Same error on my pipelines.

**Comment by bacongobbler** [comment] 2019-03-20 04:10
dupe of #5477. Please see https://github.com/helm/helm/issues/5477#issuecomment-474677151

**Closed by bacongobbler** 2019-03-20 04:11 UTC
