### ISSUE TITLE
helm del --purge bash: flaghash[${flagname}]: bad array subscript

### ISSUE THREAD

**Issue by davidthewatson** [helm/helm#3669] opened 2018-03-13 19:43 UTC
I'm using helm on MacOS 10.13.3:

    15:38 $ helm version
    Client: &version.Version{SemVer:"v2.3.0", 
    GitCommit:"2342275b61e0539d259590975cfb78f23afcc1e3", GitTreeState:"clean"} 
    Server: &version.Version{SemVer:"v2.3.0", 
    GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:"clean"}

If I type:

    helm del --purge

followed by ```tab```, I get:

    bash: flaghash[${flagname}]: bad array subscript

This seems to only occur with the ```--purge``` flag, it does not occur otherwise.

**Comment by bacongobbler** [comment] 2018-03-13 21:36
Hey, can you possible try something a little more recent, like v2.8.2? There might've been changes between v2.3.0 and v2.8.2 where the autocompletion was fixed in later versions of [cobra](https://github.com/spf13/cobra), which is the library we depend on for autocompletion.

**Comment by davidthewatson** [comment] 2018-03-13 22:05
Sure, can you point me to the upgrade instructions? I looked but didn't find them.

**Comment by davidthewatson** [comment] 2018-03-16 14:40
I did the upgrade you suggested:

    10:37 $ helm version
    Client: &version.Version{SemVer:"v2.8.2", 
    GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.3.0", 
    GitCommit:"d83c245fc324117885ed83afc90ac74afed271b4", GitTreeState:

but the error is the same as reported above.

**Comment by bacongobbler** [comment] 2018-03-16 14:42
Looks like the server side wasn't upgraded for some reason. Can you try

```
$ helm reset
$ helm init
```

?

**Comment by bacongobbler** [comment] 2018-03-16 14:43
Actually I don't think it'll matter all that much since this is all client side, but you should probably get those two to match regardless. :)

**Comment by bacongobbler** [comment] 2018-03-16 14:44
See https://github.com/spf13/cobra/issues/407

**Comment by Nir-Tal** [comment] 2018-09-13 08:16
The issue still exists in 2.10.0

**Comment by bitfield** [comment] 2018-10-01 17:06
Also occurs on 2.10 with `helm upgrade --install <TAB>`.

**Comment by bacongobbler** [comment] 2018-10-01 18:08
If someone wants to bump spf13/cobra to a newer version, the fix has made it upstream.

**Comment by j14s** [comment] 2018-11-08 17:50
Also occurs in 2.11 with any --name_your_switch_here

_helm install --ff -bash: flaghash[${flagname}]: bad array subscript_

**Comment by bacongobbler** [comment] 2018-11-08 19:42
yes, this issue will continue to persist until someone PRs a version bump for spf13/cobra. it shouldn't be more than a few minutes to do, so I've been holding out and letting someone new contribute something to the project. Feel like contributing a fix @j14s?

**Comment by glb** [comment] 2018-11-13 14:03
@j14s @bacongobbler if you want a PR for this I can submit one; if you'd like to take it that's also cool. I can confirm that doing the `spf13/cobra` upgrade fixes the issue.

**Comment by bacongobbler** [comment] 2018-11-13 14:11
yes please; go for it!

**Closed** 2018-11-20 16:54 UTC
Labels: bug, good first issue

**Comment by bd** [comment] 2019-03-19 21:37
I'm still seeing this error when hitting `tab` on `helm install --namespace dev --name local-dev adv-api --values`

```
$ helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

**Comment by carnesen** [comment] 2020-04-03 17:35
Like @bd , I am still encountering this issue too.
```
$ brew info helm
helm: stable 3.1.2 (bottled), HEAD
...
```
A simple workaround is to remove helm bash completion: 
```
rm /usr/local/etc/bash_completion.d/helm
```

**Comment by bitfield** [comment] 2020-04-04 09:41
> I've been holding out so someone new to the community could contribute

Keep holding on, cause you know we'll make it through.

We'll make it through; just stay strong, cause you know I'm here for you.

**Comment by marckhouzam** [comment] 2020-04-04 10:51
@carnesen can you provide the command-line you are using to
reproduce the problem?

Also, please try doing
```
source <(helm completion bash)
```
then trying again.

**Comment by carnesen** [comment] 2020-04-19 21:58
A command-line that invokes the bug is `helm install --upgrade` then hit `Tab` to trigger bash auto-completion
```
~ $ helm install --upgrade -bash: flaghash[${flagname}]: bad array subscript
```
On my system I installed helm and bash completion on MacOS using Homebrew. If I do `source <(helm completion bash)` in a shell with the brew helm bash completions installed, I still see the bug. If I do that in a shell that does _not_ have the brew helm bash completions installed, I do not encounter the bug.

**Comment by marckhouzam** [comment] 2020-04-19 22:43
@carnesen What does `helm version -c` give?

**Comment by carnesen** [comment] 2020-04-19 23:29
```
$ helm version -c
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by marckhouzam** [comment] 2020-04-19 23:33
That's an old version of helm.
Surprisingly you mentioned that brew info showed 3.1.2.

Either way you should upgrade to a more recent version that is compatible with your kubernetes cluster.

**Comment by bitfield** [comment] 2020-04-20 08:41
If the bug hasn't yet been _fixed_ in any version, what good will upgrading do?

**Comment by marckhouzam** [comment] 2020-04-20 12:11
> If the bug hasn't yet been _fixed_ in any version, what good will upgrading do?

It's been fixed for a while in both helm 2 and helm 3.
I just confirmed by doing `helm install --upgrade -[tab][tab]` with Bash 3.2 on MacOS with helm 2.15.2 and the master branch (for helm 3).

BTW there is no flag `--upgrade` to the install command. It's the opposite: an install flag to the upgrade command 😀

If you still see an error please provide the command to reproduce, how you enable the latest completion (maybe a source command) and the output of `helm version`.

Thanks
