### ISSUE TITLE
SIGSEGV when trying to pull an OCI chart

### ISSUE THREAD

**Issue by andresmgot** [helm/helm#9275] opened 2021-01-25 16:08 UTC
I am trying to use the latest version of Helm to pull a chart from my Golang package. This is a simplified version of what I am trying:

```go
package main

import (
	"fmt"

	"helm.sh/helm/v3/pkg/action"
	"helm.sh/helm/v3/pkg/cli"
)

func main() {
	var settings = cli.New()
	client := action.NewPullWithOpts()
	client.Settings = settings
	client.Version = "1.0.0"
	output, err := client.Run("oci://harbor.local/test/jenkins")
	if err != nil {
		panic(err)
	}
	fmt.Printf("Got! %s\n", output)
}
```

But I am getting the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16df136]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc000410820, 0x1ad8bf0, 0x3b, 0x0, 0x0, 0x0, 0x0)
	helm.sh/helm/v3/pkg/action/pull.go:98 +0x2c6
main.main()
	main.go:15 +0xa8
exit status 2
```

Taking a look to the code, I am missing the initialization of `p.cfg.RegistryClient`:

```go
	if strings.HasPrefix(chartRef, "oci://") {
		if p.Version == "" {
			return out.String(), errors.Errorf("--version flag is explicitly required for OCI registries")
		}

		c.Options = append(c.Options,
			getter.WithRegistryClient(p.cfg.RegistryClient),
			getter.WithTagName(p.Version))
	}
```

But all the references I see to instantiate that client, are pointing to an internal package: `	"helm.sh/helm/v3/internal/experimental/registry"`.

Is this possible? Am I missing something?

cc/ @jdolitsky since from this comment https://github.com/helm/helm/issues/9267#issuecomment-766846575 it seems it may be a bug.

Thanks! 

Output of `helm version`: v3.5.0

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `kind`

**Comment by jdolitsky** [comment] 2021-01-25 16:16
Hello! Can you let me know if the env var `HELM_EXPERIMENTAL_OCI=1` is set prior to running this? That should cause the `RegistryClient` to become initialized

**Comment by andresmgot** [comment] 2021-01-25 16:23
Thanks for the quick response! Tried but doesn't seem to affect:

```
▶ export HELM_EXPERIMENTAL_OCI=1 && go run -mod=vendor ./main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16df136]

goroutine 1 [running]:
helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc0004d88f0, 0x1aa2c86, 0x1f, 0x0, 0x0, 0x0, 0x0)
	helm.sh/helm/v3/pkg/action/pull.go:98 +0x2c6
```

**Comment by jdolitsky** [comment] 2021-01-25 16:36
I think I see whats happening. You could try taking the code from internal/ and putting it inline in your project... not an ideal solution, but should work. Then you could use the client directly. While the code is in internal/, I'm not sure there is a way to use this as a library... 

You could also fork Helm, and move the package out of internal. Here is an example of that being done: https://github.com/bloodorangeio/helm-oci-mirror/blob/master/go.mod#L11

**Comment by andresmgot** [comment] 2021-01-25 16:53
mmh, I cannot really copy just the internal package since the registry client is not an interface that I could implement:

```go
./utils.go:308:3: cannot use cli (type *"my-pkg/internal/experimental/registry".Client) as type *"helm.sh/helm/v3/internal/experimental/registry".Client in field value
```

And forking Helm is not something I could maintain. Maybe I could use ORAS directly? https://github.com/deislabs/oras (I am just interested on pulling the chart tarball for the moment).

**Comment by jdolitsky** [comment] 2021-01-27 20:52
Using oras directly would work fine. You can see how helm is doing that here: https://github.com/helm/helm/blob/master/internal/experimental/registry/client.go#L161

The list of media types used can be found here: https://github.com/helm/helm/blob/master/internal/experimental/registry/constants.go#L19

**Comment by jdolitsky** [comment] 2021-01-27 21:28
closing as duplicate of https://github.com/helm/helm/issues/9267

**Closed** 2021-01-27 21:28 UTC
Labels: question/support
