### ISSUE TITLE
Get error message '(or `helm init --client-only` if tiller is already installed)' while pushing chart

### ISSUE THREAD

**Issue by wantdrink** [helm/helm#7150] opened 2019-12-04 17:08 UTC
Hi there,

I was trying to push chart to my local harbor (v1.9.3) repo but get below error message:

> You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
> Error: plugin "push" exited with error.
> 

I installed helm push plugin from https://github.com/chartmuseum/helm-push and add the local Harbor repo. Then try to push a chart for testing as:

> helm push --username test --password Test12345? mysql-1.4.0.tgz myrepo

The error message is:
Error: Couldn't load repositories file (/root/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "push" exited with error

1. Since there is no --client-only and no tiller, this error message may need to be changed right?
2. Not sure why I got this error and have no idea how to init the repositories.yaml locally for a harbor chart repo.

Output of `helm version`:
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

**Comment by bacongobbler** [comment] 2019-12-06 17:48
Hi @wantdrink. Neat handle name. ;)

It looks as though this plugin currently supports Helm 2, and hasn't been updated to support Helm 3 at this time. @jdolitsky may have more context on this particular issue. 

I'm going to go ahead and close this as a duplicate of https://github.com/chartmuseum/helm-push/issues/37. Please go ahead and follow up there. Thanks!

**Closed by bacongobbler** 2019-12-06 17:48 UTC
Labels: question/support

**Comment by wantdrink** [comment] 2019-12-07 17:07
Thanks @bacongobbler  totally understand now.
