### ISSUE TITLE
requirements.lock digest should be based on the actual chart dependency, not the contents of requirements.yaml

### ISSUE THREAD

**Issue by MJBonifacio** [helm/helm#7008] opened 2019-11-19 01:21 UTC
Currently, when `requirements.lock` is generated using `helm dependency update`, it creates a digest from the contents of `requirements.yaml`, see here: https://github.com/helm/helm/blob/84de17e7e5255e5033967f005d4b4c05c024317c/internal/resolver/resolver.go#L151

This causes problems for wildcard versioning, for example, 

```
dependencies:
  - name: my-chart
    version: 0.8.x
    repository: "@repo"
```

So even if the chart dependency changes, when running `helm dependency update`, our chart won't see those patch changes. 

The digest should be based on the actual contents of the chart. As it is now, every "dependency" will share the same digest. It doesn't truly serve its purpose as a lockfile as is.

Output of `helm version`: `2.15.2`

Output of `kubectl version`: `1.16.01

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS, Minikube

**Comment by TBBle** [comment] 2019-11-19 01:43
Duplicate of #2731, fixed in Helm v3.

**Closed** 2019-11-22 20:10 UTC
