### ISSUE TITLE
Upgrading with third party crd

### ISSUE THREAD

**Issue by fifoome** [helm/helm#6132] opened 2019-07-31 16:34 UTC
I have a chart that contains certificates from cert-manager. `helm install` works fine and the certificates are getting installed.
However `helm upgrade` will fail with this error message:  
```
Error: UPGRADE FAILED: unable to decode "": no kind "Certificate" is registered for version "certmanager.k8s.io/v1alpha1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
helm.go:76: [debug] unable to decode "": no kind "Certificate" is registered for version "certmanager.k8s.io/v1alpha1" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
UPGRADE FAILED
main.newUpgradeCmd.func1
	/go/src/helm.sh/helm/cmd/helm/upgrade.go:119
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main
	/go/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:200
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```  

Any ideas that could help me?

Thanks.

Note:
- `oc apply` and `kubectl apply` won't fail.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"8f8d5811499411c75910c78d20450c974adab48e", GitTreeState:"clean", GoVersion:"go1.12.5"}
```
Output of `kubectl version`:  
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+6a6dc36", GitCommit:"6a6dc36", GitTreeState:"clean", BuildDate:"2019-06-27T18:39:06Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+3a25c9b", GitCommit:"3a25c9b", GitTreeState:"clean", BuildDate:"2019-07-18T00:10:31Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
- Openshift 4.1

**Comment by bacongobbler** [comment] 2019-07-31 16:59
duplicate of https://github.com/helm/helm/issues/6123

**Closed by bacongobbler** 2019-07-31 16:59 UTC
Labels: v3
