### ISSUE TITLE
Helm3: Helm Status does not show components of a chart

### ISSUE THREAD

**Issue by Tarkleigh** [helm/helm#6194] opened 2019-08-09 09:43 UTC
Hey guys,

I am testing the latest alpha of Helm 3 and noticed that "Helm Status" now longer shows the status of the kubernetes primitives inside the installed chart. Instead, the output looks like this:

> helm3 status red --namespace redis                                                                                                                        
> NAME: red
> LAST DEPLOYED: 2019-08-09 11:33:36.900216 +0200 CEST
> NAMESPACE: redis
> STATUS: deployed
> 
> NOTES:
> ** Please be patient while the chart is being deployed **
> Redis can be accessed via port 6379 on the following DNS names from within your cluster:
> 
> red-redis-master.redis.svc.cluster.local for read/write operations
> red-redis-slave.redis.svc.cluster.local for read-only operations
> 
> 
> To get your password run:
> 
>     export REDIS_PASSWORD=$(kubectl get secret --namespace redis red-redis -o jsonpath="{.data.redis-password}" | base64 --decode)
> 
> To connect to your Redis server:
> 
> 1. Run a Redis pod that you can use as a client:
> 
>    kubectl run --namespace redis red-redis-client --rm --tty -i --restart='Never' \
>     --env REDIS_PASSWORD=$REDIS_PASSWORD \
>    --image docker.io/bitnami/redis:5.0.5-debian-9-r36 -- bash
> 
> 2. Connect using the Redis CLI:
>    redis-cli -h red-redis-master -a $REDIS_PASSWORD
>    redis-cli -h red-redis-slave -a $REDIS_PASSWORD
> 
> To connect to your database from outside the cluster execute the following commands:
> 
>     kubectl port-forward --namespace redis svc/red-redis 6379:6379 &
>     redis-cli -h 127.0.0.1 -p 6379 -a $REDIS_PASSWORD
> 

Is this by design? The help text of helm status reads like it should give me more information. Am I missing a parameter?

Best regards,
Tarkleigh

> Output of `helm version`:
> version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
> 
> Output of `kubectl version`:
> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:12:47Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.4", GitCommit:"a87e9a978f65a8303aa9467537aa59c18122cbf9", GitTreeState:"clean", BuildDate:"2019-07-08T08:43:10Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
> 
> Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
> AKS

**Comment by bacongobbler** [comment] 2019-08-12 16:50
It looks like `rel.Info.Resources` isn't being populated, as that should display the resources live on the cluster. Marking as a bug.

https://github.com/helm/helm/blob/ac43d9faf23e86185c9256574c63f7c6ccf24927/pkg/action/printer.go#L41-L47

**Comment by karuppiah7890** [comment] 2019-08-16 08:59
I was able to reproduce the issue with this:

```
$ helm version
version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"f73e3235c2ef8931274898588d65b7802b56d265", GitTreeState:"clean", GoVersion:"go1.12.8"}
$ helm install redis stable/redis
$ helm status redis
```

Looking into the issue

**Comment by karuppiah7890** [comment] 2019-08-18 14:35
I checked more into the issue. Some of my findings are -

In v2 , it works by using the release manifest and then doing a kubernetes client get call to get the resources and show them in human readable format and in a sorted manner. This looks almost like what's shown in a `kubectl get <resource>` call with age and stuff

In v3, I'm yet to see any such code for `status` command. And I also haven't seen any code which gets resources from kubernetes and gives it in a human readable format. Still checking out. Looks like that has to be present and has to be wired up with the `status` command for this feature to work

**Comment by karuppiah7890** [comment] 2019-08-31 11:22
Duplicate of #5952

**Comment by hickeyma** [comment] 2019-08-31 11:28
Closing as it is a duplicate of #5952

**Closed by hickeyma** 2019-08-31 11:28 UTC
Labels: bug, v3
