### ISSUE TITLE
Adding icons to helm charts for air-gaped deployments

### ISSUE THREAD

**Issue by rghendrie** [helm/helm#7027] opened 2019-11-20 00:41 UTC
when shipping a helm chart to an air-gapped deployment it is impractical to provide a url for icons..

It would be far more practical to be able to include the icon within the chart itself.

**Comment by bacongobbler** [comment] 2019-11-22 19:44
closing as a duplicate of https://github.com/helm/helm/issues/2943.

**Closed by bacongobbler** 2019-11-22 19:44 UTC
