### ISSUE TITLE
Cannot use Helm to create namespace from template

### ISSUE THREAD

**Issue by gooddalton** [helm/helm#9966] opened 2021-07-22 14:03 UTC
Output of `helm version`: 

```version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}```

Output of `kubectl version`: 

```Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}```

```Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): ``` Docker Desktop ```

I want to define a resource;

```
kind: Namespace
apiVersion: v1
metadata:
  name: my-ns
```

When performing `Helm install my-app . -n my-ns` the error output is; 
`Error: create: failed to create: namespaces "my-ns" not found`

When performing `Helm install my-app . --create-namespace -n my-ns` the error output is;
`Error: namespaces "my-ns" already exists`

I know I can just do `kubectl create ns my-ns` but that half defeats the object of using Helm to create _everything_

**Comment by hickeyma** [comment] 2021-07-22 15:12
@gooddalton First, I'm trying to understand your use case. You want to deploy a Helm chart to a namespace but you are also specifying the namespace in a template file. Would it be better to just use the `--create-namespace` flag to do it?

Re the issue you are having, is the namespace `loqate-verify` referenced somewhere in the chart?

**Comment by gooddalton** [comment] 2021-07-22 15:18
> @gooddalton First, I'm trying to understand your use case. You want to deploy a Helm chart to a namespace but you are also specifying the namespace in a template file. Would it be better to just use the `--create-namespace` flag to do it?
> 
> Re the issue you are having, is the namespace `loqate-verify` referenced somewhere in the chart?

Yes that's correct I want to deploy an application using Helm, to a specific namespace which is defined as a template within the Helm chart. I want to add labels to the namespaces, specifically 

```labels:
     istio-injection: enabled```

Hence the reason for wanting to use a template file rather than allowing Helm to create the namespace using the flags set. I appreciate this is pretty edge case, but I want to make the installation of the Chart as easy as possible with no pre-reqs or minimal pre-reqs. Creating the namespace separately seems to defeat the object of using Helm. 

It would be cool if Helm could look at the resources types and say ah, there's a namespace here, i'll create that resource first and deploy to it.

re; namespace, apologies updated the original ticket.

**Comment by bacongobbler** [comment] 2021-07-22 15:22
I'm confused as well. You're saying you want to deploy a template to create a namespace. in your example you specify `--create-namespace` which creates the namespace ahead of time.

I think what @hickeyma's trying to say is that you should either define a Namespace template in your chart (which isn't totally recommended as a `helm uninstall mychart` can destroy other charts deployed to the same namespace), or use the `--create-namespace` flag. You cannot use both at the same time.

**Comment by bacongobbler** [comment] 2021-07-22 15:24
If you want to inject labels into the namespace, I'd suggest creating the namespace ahead of time and managing it outside the context of a chart because of the reason stated above: if you install two charts into the same namespace (say, `helm install my-app . --foo` and `helm install wordpress bitnami/wordpress --namespace foo`, calling `helm uninstall my-app` will delete the namespace as well as the wordpress chart. Which in most cases is not desirable.

**Comment by hickeyma** [comment] 2021-07-22 15:25
I am wondering is this ticket related to https://github.com/helm/helm/issues/9965? In other words, you want Helm to create namespace from a template within the chart and deploy the chart to that namespace?

**Comment by gooddalton** [comment] 2021-07-22 15:26
> I'm confused as well. You're saying you want to deploy a template to create a namespace. But in your example you specify `--create-namespace` which creates the namespace ahead of time.
> 
> I think what @hickeyma's trying to say is that you should either define a Namespace template in your chart (which isn't totally recommended as a `helm uninstall mychart` can destroy other charts deployed to the same namespace), or use the `--create-namespace` flag. You cannot use both at the same time.

OK let me reiterate.

`Helm install mychart -n my-ns` will not work because it says the namespace doesn't exist.

I appreciate others may not want to manage the namespace as part of the Helm chart but I do.

**Comment by gooddalton** [comment] 2021-07-22 15:27
> I am wondering is this ticket related to #9965? In other words, you want Helm to create namespace from a template within the chart and deploy the chart to that namespace?

Yep that's correct and yes that ticket looks the same.

**Comment by hickeyma** [comment] 2021-07-22 15:31
Ok, @gooddalton do you mind if I sloe this as a duplicate of #9965 as I think that better explains what is being requested?

**Comment by gooddalton** [comment] 2021-07-22 15:52
> Ok, @gooddalton do you mind if I close this as a duplicate of #9965 as I think that better explains what is being requested?

Nope that's fine with me, was never very good with words!

**Comment by hickeyma** [comment] 2021-07-22 15:56
Duplicate of #9965

**Comment by hickeyma** [comment] 2021-07-22 15:57
Closing as its a duplicate of #9965

**Closed by hickeyma** 2021-07-22 15:57 UTC
Labels: question/support
