### ISSUE TITLE
Store reference to the chart location in the release metadata

### ISSUE THREAD

**Issue by jan-hudec** [helm/helm#10930] opened 2022-05-05 12:25 UTC
For environments that don't have strict gitops deployment process always going through some CD mechanism, the most reliable information about what is actually installed is the metadata in the cluster itself. With `helm list` and `helm get` I get the chart name, version, app version and the values, so if the previous person installing something didn't document them, I can still upgrade the release or change the values.

However the source of the chart is not there. So if I have a release that has (in `helm list -oyaml`) written `chart: grafana-6.3.3`, is it the grafana grafana, or the bitnami one?

Could you please add an entry that would contain:

- If the chart was from repository, the repository URL
- If the chart was given as URL the chart URL
- If the chart was given as path, the path

It would be nice, if additionally the `upgrade` command was extended so it would allow calling it without naming a chart and it would use this information to get the chart.

**Comment by bacongobbler** [comment] 2022-05-05 22:37
Duplicate of https://github.com/helm/helm/issues/4256.

**Closed by bacongobbler** 2022-05-05 22:37 UTC
