### ISSUE TITLE
Error: UPGRADE FAILED: no Role with the name ...

### ISSUE THREAD

**Issue by magick93** [helm/helm#4666] opened 2018-09-19 04:27 UTC
I'm getting the following error:

```
 helm upgrade -i myco-product-api . --namespace myco-product-api --set replicaCount=2 --set image.tag=1.0.0-alpha-296
Error: UPGRADE FAILED: no Role with the name "myco-product-api-role" found
```

But, when I use kubectl, I get:

```
kubectl get roles --namespace myco-product-api
NAME                          AGE
myco-product-api-role   28m
```

# Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

# Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

# Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Bare metal

**Comment by bacongobbler** [comment] 2018-09-19 05:27
closing as a duplicate of https://github.com/helm/helm/issues/1193. Thanks!

**Closed by bacongobbler** 2018-09-19 05:27 UTC
