### ISSUE TITLE
--output json is missing from helm dependencies

### ISSUE THREAD

**Issue by survivant** [helm/helm#8065] opened 2020-05-06 14:39 UTC
the option to output to json is not available for helm dep

$ helm dep list
NAME    VERSION REPOSITORY                              STATUS
tomcat  6.3.6   https://charts.bitnami.com/bitnami      ok

$ helm dep list --output json
Error: unknown flag: --output

**Comment by bacongobbler** [comment] 2020-05-06 14:56
Duplicate of #8064.

**Closed by bacongobbler** 2020-05-06 14:56 UTC
