### ISSUE TITLE
install/upgrade/rollback commend support add  label flag 

### ISSUE THREAD

**Issue by Cweiping** [helm/helm#7287] opened 2019-12-22 10:00 UTC
I need to support add labels when I install / upgrade / rollback without modifying the contents of the template in the chart package.
The helm cli does not seem to support  label flag for install or upgrade and rollback.for example:
```
$ helm install release_name ./chart_package --label  key1=vaule1,key2=value2
```
The same as kubectl.
`$ kubectl label pods foo  key1=vaule1,key2=value2
`

**Comment by bacongobbler** [comment] 2019-12-30 16:53
Duplicate of https://github.com/helm/helm/issues/1950. Please check the issue queue before opening a new ticket. Thanks!

**Closed by bacongobbler** 2019-12-30 16:53 UTC
Labels: feature

**Comment by Cweiping** [comment] 2019-12-31 07:38
Sorry,I got it.
