### ISSUE TITLE
bug(pkg/repo/index): --merge flag misbehaves on valid SemVer 2 versions

### ISSUE THREAD

**Issue by consideRatio** [helm/helm#6710] opened 2019-10-19 23:28 UTC
When `helm repo index . --merge other-index.yaml` runs, I expect that entries would append and not override if they had different versions. But, when this index --merge is done with a valid SemVer 2 version such as `0.1.0-alpha.1+001.asdf1234` in one file, and `0.1.0-alpha.1` in the other, they instead override each other in either direction.

## Reproduction

Reproduced with `helm` version 2.15.0, 2.16.1, 3.0.0

```shell
# shell script to reproduce issue
mkdir /tmp/index
cd /tmp/index

cat <<EOF >a.yaml
# a.yaml
apiVersion: v1
entries:
  jupyterhub:
  - apiVersion: v1
    created: "2019-01-01T00:00:00Z"
    digest: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    name: jupyterhub
    urls:
    - https://example.local/0.1.0-alpha.1
    version: 0.1.0-alpha.1
generated: "2019-01-01T00:00:00.00000000Z"
EOF

cat <<EOF >b.yaml
# b.yaml
apiVersion: v1
entries:
  jupyterhub:
  - apiVersion: v1
    created: "2019-01-01T00:00:00Z"
    digest: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    name: jupyterhub
    urls:
    - https://example.local/0.1.0-alpha.1+001.asdf1234
    version: 0.1.0-alpha.1+001.asdf1234
generated: "2019-01-01T00:00:00.00000000Z"
EOF

cp b.yaml index.yaml
helm3 repo index . --merge a.yaml
cp index.yaml a-merged-into-b.yaml

git diff --no-index -- a.yaml a-merged-into-b.yaml > diff.patch

cat diff.patch | grep 0.1.0-alpha.1+001.asdf1234

if [ $? -eq 1 ]; then
  echo "The bug is confirmed for:"
  helm version --client
fi
```

### What went wrong?

In this diff, between the a.yaml file, and the a-merged-into-b.file, we should have seen a lot of added lines for the b.yaml's chart entry. We don't see that, instead we see that the entry of b.yaml was removed.

```diff
# diff.patch
iff --git a/a.yaml b/a-merged-into-b.yaml
index 096da69..8a15498 100644
--- a/a.yaml
+++ b/a-merged-into-b.yaml
@@ -8,4 +8,4 @@ entries:
     urls:
     - https://example.local/0.1.0-alpha.1
     version: 0.1.0-alpha.1
-generated: "2019-01-01T00:00:00.00000000Z"
+generated: "2019-10-20T01:02:56.848195709+02:00"
```

## Preliminary debugging

My current best guess of what goes wrong is that the Get function return without
error when it should actually error, and that leads to Has becoming true, which
leads to Merge not appending.

```go
// Merge merges the given index file into this index.
//
// This merges by name and version.
//
// If one of the entries in the given index does _not_ already exist, it is added.
// In all other cases, the existing record is preserved.
```

The [Merge function](https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L204-L221) relies on the [Has function](https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L130-L134), that in turn will return true or false depending on if the [Get function](https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L148-L191) returns an error or not. I suspect something is wrong here.

## Issue origin

https://github.com/jupyterhub/chartpress/issues/62

**Comment by consideRatio** [comment] 2019-10-20 16:50
## Related - The semver specification

> [Semver Specification $10](https://semver.org/#spec-item-10)
Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

> [Semver Specification $11](https://semver.org/#spec-item-11)
Precedence refers to how versions are compared to each other when ordered. Precedence MUST be calculated by separating the version into major, minor, patch and pre-release identifiers in that order (Build metadata does not figure into precedence). Precedence is determined by the first difference when comparing each of these identifiers from left to right as follows: Major, minor, and patch versions are always compared numerically. Example: 1.0.0 < 2.0.0 < 2.1.0 < 2.1.1. When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version. Example: 1.0.0-alpha < 1.0.0. Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

**Comment by consideRatio** [comment] 2019-10-20 17:00
## Related - The `check` function of masterminds/semver

https://github.com/Masterminds/semver#checking-version-constraints

```go
// Get returns the ChartVersion for the given name.
//
// If version is empty, this will return the chart with the highest version.
func (i IndexFile) Get(name, version string) (*ChartVersion, error) {
	// OBSERVATION 1:
	// All version entries in one index with a given chart name is loaded into vs.
	// "vs" is a short name for "index versions" I assume
	vs, ok := i.Entries[name]
	if !ok {
		return nil, ErrNoChartName
	}
	if len(vs) == 0 {
		return nil, ErrNoChartVersion
	}

	// OBSERVATION 2:
	// Our version won't be empty, it will be 0.1.0-alpha.1+001.asdf1234 for example
	var constraint *semver.Constraints
	if len(version) == 0 {
		constraint, _ = semver.NewConstraint("*")
	} else {
		var err error
		// OBSERVATION 3:
		// 0.1.0-alpha.1+001.asdf1234 is fed to create a constraint
		constraint, err = semver.NewConstraint(version)
		if err != nil {
			return nil, err
		}
	}

	// when customer input exact version, check whether have exact match one first
	// OBSERVATION 4:
	// This will be truthy for us that has passed a specific version to check if it is within the index.
	if len(version) != 0 {
		// OBSERVATION 5:
		// Iterate over all the versions in the index, and check if there the ==
		// operator on these versions return true, since I think version is a
		// string, I don't see how this can become truthy...
		for _, ver := range vs {
			if version == ver.Version {
				return ver, nil
			}
		}
	}

	// OBSERVATION 6:
	// Iterate over all the versions in the index, and create a semver version object from them
	for _, ver := range vs {
		test, err := semver.NewVersion(ver.Version)
		if err != nil {
			continue
		}

		// OBSERVATION 7:
		// Could it be that a constraint, created by passing
		// "0.1.0-alpha.1+001.asdf1234", when Check-ed against a semver Version
		// object, created from a version string being `0.1.0-alpha.1`, would
		// return truthy?
		if constraint.Check(test) {
			return ver, nil
		}
	}
	return nil, fmt.Errorf("No chart version found for %s-%s", name, version)
}
```

**Comment by KreativeKrise** [comment] 2019-10-31 15:26
Same probleme here. I'm currently building a ci pipeline with versions like `app-0.0.0-dev+20191031133535` and the entry in the index.yaml gets always replaced.

**Comment by consideRatio** [comment] 2019-11-26 13:16
@bacongobbler this is also reproduced for the helm CLI v3.0.0 - it is coming from the underlying masterminds/semver library.

**Comment by bacongobbler** [comment] 2019-11-26 16:31
Build metadata is supposed to be ignored when comparing versions as per the spec, so masterminds/semver is working as intended here.

**Comment by bacongobbler** [comment] 2019-11-26 16:32
https://semver.org/#spec-item-10

> Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

**Comment by consideRatio** [comment] 2019-12-17 09:56
This issue should be labeled to be Helm v3 also.

**Comment by consideRatio** [comment] 2020-02-27 13:53
As this has reproduced on Helm v3, could someone help tag this with v3 also?

**Comment by paulczar** [comment] 2020-07-09 16:12
From my reading this appears to be functioning as expected.

`0.1.0-alpha.1` and `0.1.0-alpha.1+001.asdf1234` are the same and therefore match, and therefore according to the helm merge function the existing record is [preserved](https://github.com/helm/helm/blob/9668ad4d90c5e95bd520e58e7387607be6b63bb6/pkg/repo/index.go#L208-L209).

```go
// If one of the entries in the given index does _not_ already exist, it is added.
// In all other cases, the existing record is preserved.
``` 

Therefore this is probably not something to fix, but perhaps we could improve the documentation in the `helm index --help` which currently reads:

```
--merge string   merge the generated index into the given index
```

to be something more descriptive like

```
--merge string   merge the generated index into the given index, existing records will be preserved (matched on semver specification)
```

and/or update the [docs](https://helm.sh/docs/topics/chart_repository/#add-new-charts-to-an-existing-repository) to include more explicit behavior details for the merge function where we could specifically call out this behavior.

**Comment by bacongobbler** [comment] 2020-07-09 17:33
Let's close this out as working as intended. If someone wants to improve the documentation, please feel free. But given that our bugfix support window for Helm 2 is coming to a close in a month, and there doesn't appear to be any action items to take on here, this seems safe to close.

**Closed by bacongobbler** 2020-07-09 17:33 UTC
Labels: bug, v2.x
