### ISSUE TITLE
Helm v3.7.0 OCI Helm push to ecr gives 404 Not found

### ISSUE THREAD

**Issue by ysaakpr** [helm/helm#10169] opened 2021-09-22 04:43 UTC
I was trying to use the OCI chart repo push with the new 3.7 release, and keep getting below error, repository exist.

```
Error: failed commit on ref "manifest-sha256:917752d9a5d35b444079a0179f18a17babe5264248961f86a6e07250c0081833": unexpected status: 404 Not Found
```

Output of `helm version`: 3.7.0

Output of `kubectl version`: NA

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by bacongobbler** [comment] 2021-09-22 15:21
Hi. Can you please provide more information about what commands you were using, and how to reproduce the issue?

**Comment by DarkmatterVale** [comment] 2021-09-22 21:28
I'm getting the same error with helm `3.7.0`. I'm using the following command to push my chart to ECR:

```
helm push ./my-chart-0.1.0.tgz oci://<AWS account number>.dkr.ecr.us-east-1.amazonaws.com/<repo name>:<tag>
```

**Comment by bacongobbler** [comment] 2021-09-22 21:30
Do not append a repository name or a tag. Use the following:

```
helm push ./my-chart-0.1.0.tgz oci://<AWS account number>.dkr.ecr.us-east-1.amazonaws.com/
```

both the repository name and tag are discovered from the chart name and version.

**Comment by DarkmatterVale** [comment] 2021-09-22 21:34
I would like to manually specify the repository name and version. I used to be able to explicitly state that. Is that capability no longer available in Helm?

**Comment by bacongobbler** [comment] 2021-09-22 22:34
No. As this is experimental code, things can change in a breaking manner.

Please see https://github.com/helm/community/blob/main/hips/hip-0006.md for more details. If you have feedback on the HIP, please feel free to discuss it on the mailing list, or submit an alternative proposal.

**Comment by EnlightenedOne** [comment] 2021-09-29 14:48
Azure on "AzureCLI@2" swapped us from 3.5.4 to 3.7 without warning a bunch of pipelines got broken.

I think sourcing from the chart yaml is a fine default but "latest" is a _very_ common standard for docker image snapshots, we know helm supports tagging latest because tons of people do it manually for snapshots. I honestly thought it was a defect in OCI that latest wasn't being auto tagged!

I know OCI is experimental but with Azure threatening to cull the old chart management pathway and encouraging this as a standard for Helm 3 it would be awesome if you could offer tagging options.

Why?
1. Azure already assumes you already do:
Azure pipelines allow manual version selection or provisioning of a specific version or "Latest" when working with an ACR repo. Our QA CI pipeline pulled the artifact "Latest" nightly and then updated our deployed chart.

Our deployment step looked like this (after a dry run using 3.5.4 syntax):
#Azure thinks that the artifact version is the "build number" as it has no handle on acr tags
#Experimental OCI charts dont natively install so we pull, export and then run
helm repo list
helm chart pull x.azurecr.io/y:$(RELEASE.ARTIFACTS._y-helmchart.BUILDNUMBER)
#Export will will unpack the OCI chart tar locally on th build agent
helm chart export x.azurecr.io/y:$(RELEASE.ARTIFACTS._y-helmchart.BUILDNUMBER)
...
helm upgrade y

2. Flexible tag names rule:
Another feature we just lost is that we were able to encode the azure build number and the chart version into our OCI tags:
                CHART_VERSION=$(echo ${FILE="y*.tgz"} | sed 's/.tgz//' | sed 's/.\/y\-//')
                CHART_VERSION=$(echo ${CHART_VERSION} | sed 's/y-//')
                ACR_CHART_BUILD_VERSION=$(build.buildNumber)'v'$CHART_VERSION

It was nice being able to customise tags to include metadata:
latest
153v0.0.12-HELM
153v0.0.12-SNAPSHOT-HELM

Now we are constrainted to boring explicit chart yaml names :(
0.0.13-SNAPSHOT-HELM

**Comment by EnlightenedOne** [comment] 2021-09-29 15:54
As an FYI the above with the new helm looks like this:
#Azure thinks that the artifact version is the "build number" as it has no handle on acr tags
#Experimental OCI charts dont natively install so we pull, explode and then run
helm repo list
helm pull oci://acrservername.azurecr.io/chart-artifact-name/chart-name --version=$(RELEASE.ARTIFACTS._azure-artifact-name.BUILDNUMBER)

#Now we unpack the OCI chart tar locally on the build agent
tar zxvf chartname-*.tgz

Then proceed as normal with your usual install, we explode the tar specifically so we can pass -f defining env specific yaml for a bounded context:
helm install chartname --namespace chartname-dev chartname-*.tgz -f values-dev.yaml

**Comment by bytebae** [comment] 2021-11-17 08:29
@bacongobbler As per the hip you shared (https://github.com/helm/community/blob/main/hips/hip-0006.md) under section 1, how is the root namespace controlled? 

`helm push mychart-0.1.0.tgz oci://example.com/some/root/namespace`

So far I am only able to make something like this work
`helm push mychart-0.1.0.tgz oci://example.com/`

**Comment by scottrigby** [comment] 2021-11-23 18:22
Certain container registry services require you to create the repo namesapce ahead of time. Let's add some docs on this before moving Helm OCI out of experimental. Moving to milestone.

**Comment by scottrigby** [comment] 2021-12-22 17:04
I believe this is closed by https://github.com/helm/helm-www/pull/1249. Please let us know if this needs to be reopened for a different reason. Happy holidays everyone 💖

**Closed by scottrigby** 2021-12-22 17:04 UTC
Labels: question/support, docs

**Comment by arbreezy** [comment] 2022-06-14 12:33
I confirm that I still can't push with `helm push mychart-0.1.0.tgz oci://example.com/some/root/namespace` 
but only using the `helm push mychart-0.1.0.tgz oci://example.com/`
Helm version is v3.9.0.

Would be nice to get a response, if this functionality will be covered in future releases; specifying the target helm registry's repo is quite handy.

**Comment by sabre1041** [comment] 2022-06-14 14:53
@arbreezy I also tested with `v3.9.0` with a registry:2 registry and the OCI chart was able to be pushed successfully

```
$ helm push foo-0.1.0.tgz oci://localhost:5000/test
Pushed: localhost:5000/test/foo:0.1.0
Digest: sha256:666e343afefe30f8b87c265b29845d9a19025cf694deca10bfefbe945fe56771

$ helm push foo-0.1.0.tgz oci://localhost:5000/test/bar
Pushed: localhost:5000/test/bar/foo:0.1.0
Digest: sha256:666e343afefe30f8b87c265b29845d9a19025cf694deca10bfefbe945fe56771

$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

**Comment by vasilispantelisswo** [comment] 2022-06-14 16:37
@arbreezy It seems to be working for Azure ACR as well. Didn't test 3.9.0 but it was working for 3.7.1, I'm assuming it works on later versions.

**Comment by jtyr** [comment] 2022-10-21 23:21
I'm also not able to push into AWS ECR if the repository name contains `/` (e.g. `helm/test`):

```shell
helm push test-0.1.0.tgz oci://123456123456.dkr.ecr.us-east-1.amazonaws.com/helm/test`
```

But if I create ECR repository without `/` (e.g. `test`), it works just fine:

```shell
helm push test-0.1.0.tgz oci://123456123456.dkr.ecr.us-east-1.amazonaws.com/helm`
```

I'm using Helm v3.10.0.

Does somebody know why it doesn't work?

**Comment by aliwo** [comment] 2024-09-18 12:28
> I'm also not able to push into AWS ECR if the repository name contains `/` (e.g. `helm/test`):
> 
> ```shell
> helm push test-0.1.0.tgz oci://123456123456.dkr.ecr.us-east-1.amazonaws.com/helm/test`
> ```
> 
> But if I create ECR repository without `/` (e.g. `test`), it works just fine:
> 
> ```shell
> helm push test-0.1.0.tgz oci://123456123456.dkr.ecr.us-east-1.amazonaws.com/helm`
> ```
> 
> I'm using Helm v3.10.0.
> 
> Does somebody know why it doesn't work?
> 
> **Edit:** Seems to be related to #11017.

Hi @jtyr I have same problem 😢 did you find the solution?

**Comment by DandaRaviteja** [comment] 2024-10-03 13:28
Hi,
I got same issue and resolved by below:
create the repo in ecr manually before pushing ( it should match the chart name which helm is trying to push).
in my case chart name(in Chart.yaml) is splunk-connect-for-kubernetes

**Comment by stephencoe** [comment] 2025-03-27 11:28
If your ECR repo is `oci://000000000.dkr.ecr.eu-west-1.amazonaws.com/example-ns/example-chart-name` then your push command should use `helm push image-1.0.0.tgz oci://215727133225.dkr.ecr.eu-west-1.amazonaws.com/example-ns`

Your Chart.yaml `name` matching the `example-chart-name`

```
apiVersion: v2
name: example-chart-name
type: application
version: 1.0.0
appVersion: 0.0.1
```
