### ISSUE TITLE
Helm 3 secret creation failed: Secret has invalid metadata.name.

### ISSUE THREAD

**Issue by Blokje5** [helm/helm#7475] opened 2020-01-28 10:05 UTC
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

The issue here is that the helm release secret is created based on the release name. The release name could indeed be invalid and the error is not intuitive to why the command fails. See output:

```console
helm install test_app ./helm --debug      install.go:149: [debug] Original chart version: ""
install.go:166: [debug] CHART PATH: /Users/lennardeijsackers/Git/test-app/infra/helm

Error: create: failed to create: Secret "sh.helm.release.v1.test_app.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.test_app.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
helm.go:76: [debug] Secret "sh.helm.release.v1.test_app.v1" is invalid: metadata.name: Invalid value: "sh.helm.release.v1.test_app.v1": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
create: failed to create
helm.sh/helm/v3/pkg/storage/driver.(*Secrets).Create
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/pkg/storage/driver/secrets.go:160
helm.sh/helm/v3/pkg/storage.(*Storage).Create
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/pkg/storage/storage.go:66
helm.sh/helm/v3/pkg/action.(*Install).Run
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/pkg/action/install.go:261
main.runInstall
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/install.go:214
main.newInstallCmd.func1
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/install.go:116
github.com/spf13/cobra.(*Command).execute
        /private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
        /private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
        /private/tmp/helm-20191220-82547-1gmzo4a/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
        /private/tmp/helm-20191220-82547-1gmzo4a/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
        /usr/local/Cellar/go/1.13.5/libexec/src/runtime/proc.go:203
runtime.goexit
        /usr/local/Cellar/go/1.13.5/libexec/src/runtime/asm_amd64.s:1357
```

Helm could replace characters in the Metadata.name of the secret to turn it into a valid DNS Subdomain name.

**Comment by hickeyma** [comment] 2020-01-28 14:46
Duplicate of #3493

**Comment by hickeyma** [comment] 2020-01-28 14:47
Closing as duplicate issue open.

**Closed by hickeyma** 2020-01-28 14:47 UTC
