### ISSUE TITLE
tiller crashes

### ISSUE THREAD

**Issue by mehmetekici** [helm/helm#7922] opened 2020-04-14 19:17 UTC
We have recently upgraded to 2.16.5 version of helm and tiller got started crashing. 

kubernetes version : 1.16.7

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e31de]

goroutine 13149 [running]:
k8s.io/helm/pkg/kube.getSelectorFromObject(0x1c00c00, 0xc00076e480, 0xc00076e480, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:931 +0x2fe
k8s.io/helm/pkg/kube.(*Client).getSelectRelationPod(0xc000491ba0, 0xc0001f6c40, 0xc00086c9c0, 0xc0009010b0, 0x18, 0xc0009e8e48)
        /go/src/k8s.io/helm/pkg/kube/client.go:1104 +0x195
k8s.io/helm/pkg/kube.(*Client).Get.func2(0xc0001f6c40, 0x0, 0x0)
        /go/src/k8s.io/helm/pkg/kube/client.go:366 +0xd1
k8s.io/helm/pkg/kube.batchPerform.func1(0xc000506120, 0xc00086ce70, 0xc000ad8ae0, 0xc0001f6c40)
        /go/src/k8s.io/helm/pkg/kube/client.go:752 +0x30
created by k8s.io/helm/pkg/kube.batchPerform
        /go/src/k8s.io/helm/pkg/kube/client.go:751 +0xb8

**Comment by bacongobbler** [comment] 2020-04-14 19:21
closing as a duplicate of https://github.com/helm/helm/issues/7812.

**Closed by bacongobbler** 2020-04-14 19:21 UTC
