### ISSUE TITLE
helm deploy hpa apiversion not match helm --debug

### ISSUE THREAD

**Issue by k8sre** [helm/helm#5783] opened 2019-05-23 05:59 UTC
kube
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-aliyun.1", GitCommit:"01a904e", GitTreeState:"", BuildDate:"2019-02-28T13:54:16Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
helm 
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

helm templates 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/35365219/58299158-cb7c2c80-7e10-11e9-9f55-0d372f2ba0ea.png">

use helm --debug
<img width="331" alt="image" src="https://user-images.githubusercontent.com/35365219/58299194-f0709f80-7e10-11e9-8e90-e17b13d8583d.png">

use helm template .
<img width="330" alt="image" src="https://user-images.githubusercontent.com/35365219/58299833-f9627080-7e12-11e9-82a3-c3bb63089947.png">

 deployed
<img width="268" alt="image" src="https://user-images.githubusercontent.com/35365219/58299213-07af8d00-7e11-11e9-8dbf-a3f2ad4396a4.png">

I deploy HPA(apiversion autoscaling/v2beta1) using Helm , but actually deployed autoscaling/v1

**Comment by jdolitsky** [comment] 2019-05-23 14:49
@anymb Hi, can you please elaborate? I'm not sure what the issue is.

I see the error in the screenshot, however this may be a kubernetes thing. Can you try `helm template .` first to see in the manifest looks as you expect?

**Comment by anymb** [comment] 2019-05-24 02:55
> @anymb Hi, can you please elaborate? I'm not sure what the issue is.
> 
> I see the error in the screenshot, however this may be a kubernetes thing. Can you try `helm template .` first to see in the manifest looks as you expect?

I'm sorry for the confusion. I updated my issues. The apiversion changed out of expection after I deployed the helm template.

**Comment by Constantin07** [comment] 2019-07-16 12:34
It looks like Kubertnetes does this conversion, not `helm`.
Just deployed an `hpa.yaml` file with CPU resource and `apiVersion: autoscaling/v2beta1` using `kubectl` and got `apiVersion: autoscaling/v1` in the dump of the object back.

**Comment by bacongobbler** [comment] 2019-07-16 14:56
Internally, Kubernetes stores HPA objects in the same way regardless of which apiVersion you used to create them. When you fetch them back from the server, the API server converts the internal representation to the version requested. If no version is specified, the latest is used.

This appears to be a duplicate of https://github.com/helm/helm/issues/4976. Please follow up in that issue. Thanks!

**Closed by bacongobbler** 2019-07-16 14:56 UTC
Labels: question/support
