### ISSUE TITLE
Helm installation failing with sha mismatch

### ISSUE THREAD

**Issue by prashantchari** [helm/helm#5486] opened 2019-03-20 18:18 UTC
Running the get_helm.sh script for 2.11, throws sha sum mismatch. The script from the master branch seems to be working though.

wget -q https://raw.githubusercontent.com/helm/helm/v2.11.0/scripts/get -O get_helm.sh
 ./get_helm.sh
Downloading https://kubernetes-helm.storage.googleapis.com/helm-tooltipped-s-linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-TN4hzI/helm-tooltipped-s-linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
        For support, go to https://github.com/helm/helm.

**Comment by bacongobbler** [comment] 2019-03-20 18:23
Dupe of https://github.com/helm/helm/issues/5477. Please use the install script from master. Thanks!

**Closed by bacongobbler** 2019-03-20 18:23 UTC
