### ISSUE TITLE
Helm status with json output in not well structured

### ISSUE THREAD

**Issue by jikuma** [helm/helm#4487] opened 2018-08-18 00:16 UTC
Output of `helm version`:

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Azure

The output of the command 

_helm --tiller-namespace azds status default-webfrontendchartname-0918702b -o json_

is 

{
	"name": "default-webfrontendchartname-0918702b",
	"info": {
		"status": {
			"code": 1,
			"resources": "==\u003e v1/Service\nNAME      TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE\npingapp   ClusterIP   10.0.81.177   \u003cnone\u003e        80/TCP    37m\nwebfrontendvalue   ClusterIP   10.0.202.157   \u003cnone\u003e    80/TCP    37m\n\n==\u003e v1beta2/Deployment\nNAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE\nwebfrontendvalue   1         1         1            1           37m\n\n==\u003e v1beta1/Deployment\npingapp   1         1         1         1         37m\n\n==\u003e v1beta1/Ingress\nNAME              HOSTS
 ADDRESS   PORTS     AGE\npingapp-ingress   pingapp             80        37m\n\n==\u003e v1/Pod(related)\nNAME                                READY     STATUS    RESTARTS   AGE\nwebfrontendvalue-54d4865c77-b4xxw   2/2       Running   0          37m\npingapp-8ddb66d8c-wgbz6   2/2       Running   0         37m\n\n",
			"notes": "1. Get the application URL by running these commands:\r\n  export POD_NAME=$(kubectl get pods --namespace default -l \"app=webfrontendchartname,release=default-webfrontendchartname-0918702b\" -o jsonpath=\"{.items[0].metadata.name}\")\r\n  echo \"Visit http://127.0.0.1:8080 to use your application\"\r\n  kubectl port-forward $POD_NAME 8080:80\r\n"
		},
		"first_deployed": {
			"seconds": 1534548916,
			"nanos": 275685928
		},
		"last_deployed": {
			"seconds": 1534548916,
			"nanos": 275685928
		},
		"Description": "Install complete"
	},
	"namespace": "default"
}

This output still needs string parsing to get the release details like services. Resources value should be split further into services and other resources.

**Comment by yogeshlonkar** [comment] 2018-08-28 07:43
probably duplicate of https://github.com/helm/helm/issues/3943

**Comment by bacongobbler** [comment] 2020-05-14 22:02
closing as inactive.

**Closed by bacongobbler** 2020-05-14 22:02 UTC
Labels: bug, unconfirmed
