### ISSUE TITLE
Add `--set-value` flag that requires less escaping

### ISSUE THREAD

**Issue by kvolkovich-sc** [helm/helm#4406] opened 2018-07-31 13:32 UTC
Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

---

Hello!

I like Helm, but this issue does not give me rest.

According to: https://docs.helm.sh/using_helm/#the-format-and-limitations-of-set

> Sometimes you need to use special characters in your --set lines. You can use a backslash to escape the characters; --set name="value1\,value2" will become:

```
name: "value1,value2"
```

I can't guarantee that some value contains or not contains the comma.
So I forced to escape each value at my CI.
Its absolutely uncomfortable.

As I understand, you don't want to break compatibility for `2.x`.
You can consider to introduce another CLI parameter.

- `-s`
- `-S`
- `--set-value`
- ... or something like this.

Related issues I found:

- https://github.com/helm/helm/issues/1751
- https://github.com/helm/helm/issues/1556
- https://github.com/helm/helm/issues/4173
- https://github.com/helm/helm/issues/2952

**Comment by technosophos** [comment] 2018-08-03 23:51
I'm re-marking this as a feature request, and re-titling it appropriately.

**Comment by Nowaker** [comment] 2018-08-23 16:29
Or alternatively, make `--set` not treat `,` in a special way when `--disable-the-damn-coma` is passed. One way or another, how things are now is extremely inconvenient. Hope this can get straightened up. :)

CC @bacongobbler

**Comment by bacongobbler** [comment] 2019-08-13 21:56
closing as a duplicate of #4030 so we can keep the conversation all in one place. Thanks!

**Closed by bacongobbler** 2019-08-13 21:56 UTC
Labels: feature, v3
