### ISSUE TITLE
Helm commands use default values even if -f is specified 

### ISSUE THREAD

**Issue by aleerizw** [helm/helm#3689] opened 2018-03-15 10:13 UTC
Helm commands (install, template etc.) merges the values file specified with the -f option with the default values.yaml file if it is present. I am not sure if it an intended feature or a bug.

If this is a feature is there a way to not use the default values.yaml file?

**Comment by bacongobbler** [comment] 2018-03-19 14:42
This is intended and is part of the original design of the project. However, we would be more than happy to introduce a feature flag that changes this behaviour if it makes sense to do so.

**Comment by aleerizw** [comment] 2018-03-19 14:58
Yes, that would be great. In our usecase we have a values file per environment and since helm merges the files anything that is inside the default values gets merged so we have to make sure that the values.yaml is empty.

**Comment by jpatters** [comment] 2018-04-05 00:17
I just got tripped up on this as well. The documentation here https://github.com/kubernetes/helm/blob/master/docs/charts.md#values-files says
> The Helm install command allows a user to **override** values by supplying additional YAML values 

It later states

> When values are passed in this way, they will be **merged** into the default values file

That's where my confusion stems from. It could probably be worded better.

In my case I am trying to override a set of annotations. The chart default values has:
```
annotations:
  annotation1: value
  annotation2: value
```

I was expecting I could remove the default annotations with
```
annotations: {}
```

But instead got the default values. I now understand the intended behaviour but the documentation could be cleared up and possibly add an example showing that nested values will also be merged.

**Comment by bacongobbler** [comment] 2019-12-09 17:24
Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!

**Closed by bacongobbler** 2019-12-09 17:24 UTC
Labels: question/support

**Comment by HarikrishnanBalagopal** [comment] 2025-01-09 10:39
> Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!

@bacongobbler  This issue is still there in Helm 3 and very surprising.

One would expect that if the user is explicit on which values file to use by giving the `--values` flag then ONLY those specified files would be used. Especially bad since often the intent is to NOT use the default `values.yaml` file that is present.

Work around that we have been forced to go with for now is to break with Helm convention and rename the default `values.yaml` file to `default-values.yaml`.

```
$ helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}
```

**Comment by HarikrishnanBalagopal** [comment] 2025-01-09 12:35
Related https://github.com/helm/helm/issues/9597
