### ISSUE TITLE
How do I turn off go templating 

### ISSUE THREAD

**Issue by rohanmohapatra** [helm/helm#8237] opened 2020-06-01 12:03 UTC
I have done this but it gives the error
```
{{`{{ .Values.spec.version | replace "." "-" | lower }}` }}
```

I get this error,
```
 error converting YAML to JSON: yaml: invalid map key:
```

What I want?
I want helm to render it as `{{ .Values.spec.version | replace "." "-" | lower }}` instead of substituting the value

**Comment by bacongobbler** [comment] 2020-06-01 15:36
duplicate of https://github.com/helm/helm/issues/2798. Use `{{ "{{" }}` to escape template syntax.

**Closed by bacongobbler** 2020-06-01 15:36 UTC
