### ISSUE TITLE
Plugins created in user folder even if running as root via `sudo -s`

### ISSUE THREAD

**Issue by MaurGi** [helm/helm#9984] opened 2021-07-28 18:52 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): N/A

repro:
```
azureuser@k8s-infra-1-2vhcwkjt7gpwk000000:~$ sudo -s
root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 plugin list --debug
plugin_list.go:36: [debug] pluginDirs: /home/azureuser/.local/share/helm/plugins
NAME    VERSION DESCRIPTION
root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 plugin install /var/lib/helm/plugins/2to3  --debug
[debug] local_installer.go:49: symlinking /var/lib/helm/plugins/2to3 to /home/azureuser/.local/share/helm/plugins/2to3
plugin_install.go:82: [debug] loading plugin from /home/azureuser/.local/share/helm/plugins/2to3
plugin.go:60: [debug] running install hook: /bin/sh -c cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh
Downloading and installing helm-2to3 v0.9.0 ...
https://github.com/helm/helm-2to3/releases/download/v0.9.0/helm-2to3_0.9.0_linux_amd64.tar.gz
Installed plugin: 2to3
root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 plugin list --debug
plugin_list.go:36: [debug] pluginDirs: /home/azureuser/.local/share/helm/plugins
NAME    VERSION DESCRIPTION
2to3    0.9.0   migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
```

Issue: even if I am root, the plugin is installed in `/home/azureuser/.local`.
Now, if I now run a service with systemd, the plugin does not appear as installed (because in that case, it looks for plugins in `/.local/share/helm/plugins`)

The same is true for the opposite case, if a systemd service installs the plugin, it gets placed into `/.local/share/helm/plugins`, but then if I connect to the host with azureuser and I `sudo -s` I do not see the plugin as installed.

**Comment by bacongobbler** [comment] 2021-07-28 18:58
Can you share the output of `helm env`?

For example here's what I see on my machine.

```
><> su -
Password: 
[root@ultralisk ~]# helm env
HELM_BIN="helm"
HELM_CACHE_HOME="/root/.cache/helm"
HELM_CONFIG_HOME="/root/.config/helm"
HELM_DATA_HOME="/root/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/root/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/root/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/root/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/root/.config/helm/repositories.yaml"
```

**Comment by MaurGi** [comment] 2021-07-28 19:41
```
root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 env
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/kubernetes/admin.conf
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/kubernetes/admin.conf
HELM_BIN="helm3"
HELM_CACHE_HOME="/home/azureuser/.cache/helm"
HELM_CONFIG_HOME="/home/azureuser/.config/helm"
HELM_DATA_HOME="/home/azureuser/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/azureuser/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/azureuser/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/azureuser/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/azureuser/.config/helm/repositories.yaml"
```

**Comment by MaurGi** [comment] 2021-07-28 19:46
interesting: 
`sudo -s` has the problem while `su -` does not - note we do not have the root password on these machines, so to `su -` I need to `sudo -s`, then `su -`

```
azureuser@k8s-infra-1-2vhcwkjt7gpwk000000:~$ helm3 env
HELM_BIN="helm3"
HELM_CACHE_HOME="/home/azureuser/.cache/helm"
HELM_CONFIG_HOME="/home/azureuser/.config/helm"
HELM_DATA_HOME="/home/azureuser/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/azureuser/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/azureuser/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/azureuser/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/azureuser/.config/helm/repositories.yaml"

azureuser@k8s-infra-1-2vhcwkjt7gpwk000000:~$ sudo -s

root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 env
HELM_BIN="helm3"
HELM_CACHE_HOME="/home/azureuser/.cache/helm"
HELM_CONFIG_HOME="/home/azureuser/.config/helm"
HELM_DATA_HOME="/home/azureuser/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/home/azureuser/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/home/azureuser/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/home/azureuser/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/home/azureuser/.config/helm/repositories.yaml"

root@k8s-infra-1-2vhcwkjt7gpwk000000:~# exit
exit

azureuser@k8s-infra-1-2vhcwkjt7gpwk000000:~$ su -
Password:
su: Authentication failure

azureuser@k8s-infra-1-2vhcwkjt7gpwk000000:~$ sudo -s
**root@k8s-infra-1-2vhcwkjt7gpwk000000:~# su -**
**root@k8s-infra-1-2vhcwkjt7gpwk000000:~# helm3 env**
HELM_BIN="helm3"
HELM_CACHE_HOME="/root/.cache/helm"
HELM_CONFIG_HOME="/root/.config/helm"
HELM_DATA_HOME="/root/.local/share/helm"
HELM_DEBUG="false"
HELM_KUBEAPISERVER=""
HELM_KUBEASGROUPS=""
HELM_KUBEASUSER=""
HELM_KUBECAFILE=""
HELM_KUBECONTEXT=""
HELM_KUBETOKEN=""
HELM_MAX_HISTORY="10"
HELM_NAMESPACE="default"
HELM_PLUGINS="/root/.local/share/helm/plugins"
HELM_REGISTRY_CONFIG="/root/.config/helm/registry.json"
HELM_REPOSITORY_CACHE="/root/.cache/helm/repository"
HELM_REPOSITORY_CONFIG="/root/.config/helm/repositories.yaml"

root@k8s-infra-1-2vhcwkjt7gpwk000000:~#
```

**Comment by bacongobbler** [comment] 2021-07-28 19:55
From `man su`:

> For backward compatibility, su defaults to not change the current directory and to only set the environment variables HOME and SHELL (plus USER and LOGNAME if the target user is not root). It is recommended to always use the --login option (instead of its shortcut -) to avoid side effects caused by mixing environments.

Seems like expected behaviour here. So perhaps the recommendation is to use `su -s --login` when attempting to issue `helm` commands as the root user.

**Comment by bacongobbler** [comment] 2021-07-28 19:58
Closing; looks like environment variables are being preserved across logins causing the behaviour seen in the OP. In other words, the issue stems from a localized problem with OP's usage of `sudo`. So this is expected behaviour, to a point.

Thanks for the report!

**Closed by bacongobbler** 2021-07-28 19:58 UTC
Labels: question/support

**Comment by MaurGi** [comment] 2021-07-28 20:09
I accept closing by design, but I feel this is confusing and should be considered for design change. 

Plugins should be installed at a machine level by default and have appropriate rights.

It would be confusing if each user needed to install its own copy of helm, right? 
Then why do this for the plugins?

**Comment by bacongobbler** [comment] 2021-07-28 20:20
I get the difference of opinions here. There are two trains of thought: those that want Helm as a user-level package manager, and those that want Helm as a systems package manager.

I opened a proposal to switch Helm's plugin model to align more closely with the model you're describing, where plugins (and eventually configuration) are configured at the machine level. However it was not a popular opinion and therefore discarded in favour of the current model we have today.

See https://github.com/helm/helm/pull/5514 for more context.

What you can do instead is set your XDG_* environment variables to locations like /etc/, /var/run, etc. to mimic a machine-level design. But as it stands today Helm reads and stores configuration/data at the user scope.

In any case, if you want to make a case for the latter, you can propose a HIP: https://github.com/helm/helm/blob/main/CONTRIBUTING.md#proposing-an-idea

**Comment by MaurGi** [comment] 2021-07-28 20:30
Maybe a `helm plugin install --global` option might do it here? It would serve both multi-user systems as well as auto-install servers (like the one we are setting up here).
