### ISSUE TITLE
include yaml files from other folders other than template

### ISSUE THREAD

**Issue by shubhammicrosoft1** [helm/helm#9757] opened 2021-05-31 10:31 UTC
Can we include yaml files from other folders in helm or is this mandatory to have all yaml under templates for a helm chart.

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Azure

**Comment by bacongobbler** [comment] 2021-05-31 16:28
duplicate of #3276.

**Closed by bacongobbler** 2021-05-31 16:28 UTC
