### ISSUE TITLE
Helm upgrade broken when CRD is missing

### ISSUE THREAD

**Issue by Stono** [helm/helm#5935] opened 2019-06-24 13:58 UTC
Helm `2.14.1`:

Take the following scenario:

`chart1`: 
  - creates `CRD1`
  - creates `CRD2`

`chart2`:
  - creates instance of CRD1, and CRD2

`chart1` deprecates `CRD2`, so the CRD is removed during the `helm upgrade`.  This is fine, however when you come to remove the CR from `chart2`, you'll get an error as it appears helm is trying to do a `GET` first on the resource, but as the CRD has been deleted, it no longer exists on the kubernetes API:

```
  Error: UPGRADE FAILED: failed decoding reader into objects: [unable to recognize "": no matches for kind "kubernetes" in version "config.istio.io/v1alpha2", unable to recognize "": no matches for kind "metric" in version "config.istio.io/v1alpha2"]
```

This mean's you're stuck, the only methods of recovery are to:

  - manually recreate the crd, upgrade chart2, manually delete the crd
  - ensure that chart2 removes the cr first, before running chart 1 (not always possible)

It feels like helm should handle this better, and if the CRD doesn't exist on the kubernetes API, any logic it appears to be doing before the helm delete should just be skipped and the resource should be removed (in truth, it's actually already been removed because it parentRef'd the CRD, so it was deleted when the CRD was).

**Comment by bacongobbler** [comment] 2019-06-24 16:57
#5871 seems relevant to this discussion, as we've talked about whether or not charts should be able to manage resources that can affect other charts (such as CRDs). See https://github.com/helm/helm/issues/5871#issuecomment-502157387.

**Comment by bacongobbler** [comment] 2019-07-03 07:11
closing as a duplicate of #5871.

**Closed by bacongobbler** 2019-07-03 07:11 UTC
Labels: question/support
