### ISSUE TITLE
Helm 3 is truncating appVersion if there is only one dot and 0 at the end.

### ISSUE THREAD

**Issue by TomasKohout** [helm/helm#7262] opened 2019-12-18 12:19 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

When I have appVersion set to 1.0 and try to use this value in templates then it is templated as 1 instead of 1.0. 1.0.0 works as expected.

How to reproduce:

helm create test
change app version to eg. 3.0
helm template test 
check the templated deployment.yaml

**Comment by karuppiah7890** [comment] 2019-12-18 16:36
According to yaml spec, `3.0` and `3` are the same. It was considered as a number. The issue here is that `appVersion` should only be considered as a string, no matter what, we are working on this here #6921 and #7235 (lint errors) 😄 next we will also work on package errors I think

For now, you can put double quotes around the `appVersion` value for it to work, for example `"1.0"`

**Comment by karuppiah7890** [comment] 2019-12-18 16:37
I think we can close this considering it as a duplicate of #6921

**Closed** 2019-12-18 17:07 UTC

**Comment by TomasKohout** [comment] 2019-12-18 17:16
As I thought. THX. :+1:  I tried ' but it didn't worked. Will try the " :smile:
