### ISSUE TITLE
get Files doesn't work in nested templete with subchart

### ISSUE THREAD

**Issue by survivant** [helm/helm#9420] opened 2021-02-26 20:45 UTC
here my particuliar usercase.  I have a chart that have one dependancy : Prometheus.

````
dependencies:
  - name: prometheus
    version: 13.3.1
    repository: "@prometheus-community"
````

in Prometheus chart in a configmap.yaml, there is that section that allow us to add additionnal informations into the configmap

````
{{- if eq $key "prometheus.yml" -}}
{{- if $root.Values.extraScrapeConfigs }}
{{ tpl $root.Values.extraScrapeConfigs $root | indent 4 }}
{{- end -}}
````  

in my values.yaml file I have this
````
prometheus:
    extraScrapeConfigs: |
    patate1111
    {{ include "extraScrapeConfigsFiles" $ }}
````

I added this in _helpers.tlp'

````
{{- define "extraScrapeConfigsFiles" -}}
xxxxxx
{{ $currentScope := .}}
{{ range $path, $_ :=  .Files.Glob  "*" }}
    {{- with $currentScope}}
        {{- $path }}
    {{- end }}
{{ end }}
xxxxxx

{{- $files := .Files.Glob "*" }}
cdcdcd found
{{- if $files }}
{{- range $path, $fileContents := $files }}
{{- $path | toString | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
````

I'm using this command line : 
````
helm --kube-context kubernetes-admin@kubernetes install monitor -n metrics . --dry-run > all.yaml
````

THe output is this : 

````
....
patate1111
    xxxxxx
    
    .helmignore
    README.md
    
    xxxxxx
    cdcdcd found
        .helmignore
        README.md
````

The content of the files are from Prometheus chart.  .Files.Glob "*"    return the files with the root of that chart (excluding helm files.. don't know where either)

![image](https://user-images.githubusercontent.com/191879/109352692-3447d280-7849-11eb-9822-0e0512aea8b4.png)

````
C:\workspace\codec-monitoring\charts\monitoring-stack>tree /F /A
Structure du dossier pour le volume OSDisk
Le numéro de série du volume est EC56-DE6A
C:.
|   .helmignore
|   all.yaml
|   Chart.lock
|   Chart.yaml
|   test.txt
|   values.yaml
|
+---charts
|       grafana-6.3.0.tgz
|       kube-prometheus-stack-13.7.0.tgz
|       prometheus-13.3.1.tgz
|
+---dashboards
|   +---json
|   |   +---custom
|   |   |       k8s-persistence-volumes.json
|   |   |
|   |   \---openebs
|   |           clustervolumesdashboard.json
|   |           cstorvolumereplicasdashboard.json
|   |           localpvdashboard.json
|   |           README.md
|   |           storageclassvolumedashboard.json
|   |           storagepoolclaimdashboard.json
|   |           storagepooldashboard.json
|   |           volumetiledviewdashboard.json
|   |           volumeworkloadreportdashboard.json
|   |
|   \---yaml
|       \---prometheus-operator
|               cm-external-gf-dashboard.yaml
|
+---rules
|   +---openebs
|   |       alerts.yaml
|   |
|   \---prometheus
|           alertmanager-prometheusRule.yaml
|           etcd.yaml
|           kube-prometheus-prometheusRule.yaml
|           kube-state-metrics-prometheusRule.yaml
|           node-exporter-prometheusRule.yaml
|           prometheus-operator-prometheusRule.yaml
|           prometheus-prometheusRule.yaml
|
+---scrapes
|       openebs-scrapeconfig.yaml
|
\---templates
        cm-gf-dashboards-json.yaml
        cm-gf-dashboards-yaml.yaml
        cm-prometheus-alerts.yaml
        cm-prometheus-rules.yaml
        cm-test-template.yaml
        NOTES.txt
        _helpers.tpl


C:\workspace\codec-monitoring\charts\monitoring-stack>


````

How can list the files within the folder : /scrapes/**   ?

**Comment by bacongobbler** [comment] 2021-03-12 15:24
https://helm.sh/docs/chart_template_guide/accessing_files/

Have you tried `.Files.Glob  "scrapes/**"`?

**Comment by survivant** [comment] 2021-03-12 20:45
@bacongobbler yes I tried (and lot of other paths.. like absolute, relative with ../../.../../scrapes ..  .  The problem is that .Files.Glob will return the list of files that are under in chart and not from the root of the project.  I'm using subchart.  The best option could be to have a way to go to the root of the project in the templates.. instead of $.  we could have $$.  and that position the context to the root of the project.  

I saw a issue #8841 that could be a valid option but that make another param to pass to the command line.  An absolute root.. should be the best option for my needs.

**Comment by bacongobbler** [comment] 2021-03-12 20:59
Oh... if you’re referencing files from outside the chart directory then yes you would have to wait until something like #8841 has been implemented. Alternatively you can use symbolic links to reference files outside your chart directory as discussed in other issues.

Closing as a duplicate of #3276.

**Closed by bacongobbler** 2021-03-12 20:59 UTC
Labels: question/support
