### ISSUE TITLE
Mask/Hide sensitive values during "helm get values" or during "helm install/upgrade with --debug".

### ISSUE THREAD

**Issue by rsivakanth** [helm/helm#11834] opened 2023-02-19 20:20 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"f941a31f4515c5ac03f5fc7ccf9a330e3510b80d", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:33Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Cloud Native (services targeted to be deployed on platforms regardless of provider)

Hi,
This is regarding masking/hiding of the sensitive values when 'helm get values' is run.

Is this feature already available or is it under proposal?

The requirement is something like this. If we provide the sensitive values in below format in custom-values.yaml during helm install or hem upgrade, could it be made to mask?

In the custom-values.yaml:

credentials:
      accessId: 'accessID'
      secret: 'mySecret' | sensitive
  
After helm install/upgrade -f custom-values.yaml, and when "helm get values" is done:

credentials:
  secret: [sensitive]

Even during helm install/upgrade --debug option, it could be masked by default unless we set it something like --mask=no. Can this be possible/considered?

Thanks,
Sivakanth.

**Comment by joejulian** [comment] 2023-02-22 00:52
There's been a bit of discussion about this already. I'm going to close this as a duplicate of https://github.com/helm/helm/issues/7275. Thanks!

**Closed by joejulian** 2023-02-22 00:52 UTC
