### ISSUE TITLE
Can't override value in subchart

### ISSUE THREAD

**Issue by o4rz3l** [helm/helm#12522] opened 2023-10-25 12:32 UTC
Output of `helm version`: 3.13.1

Output of `kubectl version`: v1.25.2

Hi, based on the changelog and on some issues (e.g. https://github.com/helm/helm/pull/11440), it should be possible, to remove a value from a subchart by using `value: null`. Unfortunately, this does not work in my case.

Here are some some easy steps to reproduce my issue:
1 `helm create umbrella-chart`
2. remove all templates and the clear values.yaml
3. add the prometheus dependency to the Chart.yaml
  ```
dependencies:
  - name: prometheus
    version: 25.2.0
    repository: https://prometheus-community.github.io/helm-charts
  ```
4. `helm dep update`
5. Add this to values.yaml
  ```
  prometheus:
    server:
      securityContext: null
  ```
6. Run `helm template foo -s charts/prometheus/templates/deploy.yaml . -f values.yaml`

**Expected Result**
The block 
```      
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
``` 
should not be in the deploy.yaml

**Actual Result**
The block `securityContext` with it's subkeys is in the deploy.yaml. No way to remove it.

**Comment by bt909** [comment] 2023-10-25 13:12
I experience the same issue, but if I put my values to override in the values.yaml of my umbrella chart directly and then don't use -f "file" I got my values of my sub chart overwritten. The problem seems to be related to use additional files via -f.

**Comment by rptaylor** [comment] 2023-10-25 19:04
This is another duplicate of https://github.com/helm/helm/issues/12488

**Closed** 2023-10-26 06:52 UTC
