### ISSUE TITLE
Command upgrade with flag --install will not create a new release

### ISSUE THREAD

**Issue by estahn** [helm/helm#4282] opened 2018-06-29 01:28 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
AWS

Description:
```
helm upgrade --install --reset-values cheeky-chick stable/prometheus-cloudwatch-exporter --namespace devops --values /p/prometheus-cloudwatch-exporter-us-east-1/values.yaml
Error: UPGRADE FAILED: "cheeky-chick" has no deployed releases
```

With flag `--install` i would expect it to create the deployment.

**Comment by bacongobbler** [comment] 2018-06-29 17:59
@estahn when you check `cheeky-chick` with `helm status`, was the last release in a FAILED state? If so then this may be a duplicate of https://github.com/kubernetes/helm/issues/3208.

**Comment by estahn** [comment] 2018-06-29 20:53
The release was never created in the first place. It is consistently not
working. I have to run "helm install" instead of "helm upgrade -i".

**Comment by kesselborn** [comment] 2018-07-10 11:56
hey: I just had the same problem and it looks like the problem only exists, if the helm release name has a `-` in its name.

@estahn could you check if changing the name from `cheeky-chick` to `cheekychick` works for you?

**Comment by pv93** [comment] 2018-07-10 20:42
I have a release with no '-' in it, and still have the same problem.

**Comment by kesselborn** [comment] 2018-07-10 20:44
ok ... a colleague of mine had the same problem without a `-` later as well. It's weird. Another thing I noticed was, that the pod at first was crashing -- perhaps that's a lead. I will look into it tomorrow.

**Comment by benweissmann** [comment] 2018-07-25 18:12
I'm also hitting this, in a slightly different scenario: if i create a release (with `helm install` or `helm upgrade -i`), then delete it (without `--purge`), and then try to do a `helm upgrade -i`, I also get `no deployed releases` and have to re-delete with `--purge` to resolve the situation.

**Comment by philipliberato** [comment] 2018-07-27 16:22
Deleting the release with `--purge` works for me too.

**Comment by AndrewMorsillo** [comment] 2018-08-31 16:43
Also running into this trying to deploy with concourse-helm-resource. The release exists and the app is running (I manually installed it) but when concourse-helm-resource runs

```
Running command helm upgrade myapp-prod /tmp/build/put/helm-repo/myapp-0.1.0.tgz --tiller-namespace=kube-system -f /tmp/build/put/chart-source/production.yaml --set image.repository=gcr.io/myapp/myapp-prod --set image.digest=sha256:19e7a021e2d1ab70bb91e16d19c3c0a21b187b29a4a120da40cf036db1b31e95 --install --namespace production | tee /tmp/log
```

This results in ```Error: UPGRADE FAILED: "myapp-prod" has no deployed releases``` when there is most definitely a release.

**Comment by bappr** [comment] 2018-09-15 02:07
Just sharing this good comment: https://github.com/helm/helm/issues/3208#issuecomment-396977351

"With the current stable version, how can I achieve this in an automated script?"

Exactly what I need right now.
So would definitely be a good feature.

**Comment by The-Loeki** [comment] 2018-10-19 12:39
I had the same as @benweissman & @philipliberato.

I think we're just reading the message wrong; 
"Error: UPGRADE FAILED: "myapp-prod" has no **deployed** releases**, only deleted ones**"

**Comment by bacongobbler** [comment] 2019-12-09 17:46
Closing due to inactivity. Please open a new ticket against Helm 3 if this issue persists. Thanks!

**Closed by bacongobbler** 2019-12-09 17:46 UTC
Labels: question/support
