### ISSUE TITLE
Proposal: labeling releases

### ISSUE THREAD

**Issue by krogon** [helm/helm#4111] opened 2018-05-23 09:04 UTC
My proposal is to introduce labels on releases, as similar to kubernetes ecosystem.
This would allow easier filtering the releases or marking as "managed" by 3rd party applications.

### Listing
```
$ helm list
NAME            REVISION    UPDATED                     STATUS      CHART           NAMESPACE
dinky-guppy     1           Mon May  9 12:00:01 2016	DEPLOYED    alpine-0.1.0    default
vetoed-manta    1           Mon May  9 12:00:02 2016	DEPLOYED    jenkins-0.15.1  default

$ helm list --show-labels
NAME            REVISION    UPDATED                     STATUS      CHART           NAMESPACE   LABELS
dinky-guppy     1           Mon May  9 12:00:01 2016	DEPLOYED    alpine-0.1.0    default     local=true,owner=krogon
vetoed-manta    1           Mon May  9 12:00:02 2016	DEPLOYED    jenkins-0.15.1  default     managed-by=cicd
```
### Filtering
```
$ helm list -l local=true
NAME            REVISION    UPDATED                     STATUS      CHART           NAMESPACE
dinky-guppy     1           Mon May  9 12:00:01 2016	DEPLOYED    alpine-0.1.0    default

$ helm list -l owner=krogon,managed-by=cicd
<empty response>
```
### Deleting
```
$ helm delete -l local=true
release "dinky-guppy" deleted
```

**Comment by bacongobbler** [comment] 2018-05-24 18:19
related: https://github.com/kubernetes/helm/issues/2734

**Comment by bacongobbler** [comment] 2018-05-24 18:21
oh, also some other tickets that touch on a similar problem are https://github.com/kubernetes/helm/pull/2907, https://github.com/kubernetes/helm/pull/2631, https://github.com/kubernetes/helm/issues/2450 and https://github.com/kubernetes/helm/pull/2671, which was merged into Helm 2.7.

**Comment by ultimateboy** [comment] 2018-06-18 21:44
@krogon I started this work in the following: PR https://github.com/kubernetes/helm/pull/2907

I didnt get to the point where you could list releases by labels, so feel free to pick it up from where I left off! I would love to see this feature get in!

**Comment by bacongobbler** [comment] 2020-05-14 20:30
duplicate of #2734.

**Closed by bacongobbler** 2020-05-14 20:30 UTC
Labels: feature, proposal
