### ISSUE TITLE
HELM3: namespace flag for scope is not working. default namespace is always used

### ISSUE THREAD

**Issue by CayoM** [helm/helm#5893] opened 2019-06-14 15:08 UTC
Output of `helm version`:
helm version
version.BuildInfo{Version:"v3.0.0-alpha.1", GitCommit:"b9a54967f838723fe241172a6b94d18caf8bcdca", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-28T10:10:11Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Here is the output trying to install an helm chart in a non default namespace:

```
kubectl create namespace test
namespace/test created

helm install --namespace=test mobile-ui deployment/mobile-ui
NAME: mobile-ui
LAST DEPLOYED: 2019-06-14 17:04:19.489065484 +0200 CEST m=+0.070563306
NAMESPACE: default
STATUS: deployed

kubectl get pods -n test
No resources found.

kubectl get pods -n default
NAME                              READY   STATUS             RESTARTS   AGE
mobile-ui-5599988bcf-ztwrr   0/1     ImagePullBackOff   0          21s

```

**Comment by bacongobbler** [comment] 2019-06-14 15:37
duplicate of #5628. Please make sure to search existing issues before opening new ones. Thanks!

**Closed by bacongobbler** 2019-06-14 15:37 UTC
