### ISSUE TITLE
Define JSON schema in YAML format

### ISSUE THREAD

**Issue by j-zimnowoda** [helm/helm#9880] opened 2021-06-28 11:15 UTC
It is much easier to maintain structures in YAML format. 
Can we support `values.schema.yaml` as an alternative to `values.schema.json`?

**Comment by bacongobbler** [comment] 2021-06-28 17:14
duplicate of https://github.com/helm/helm/issues/5812.

**Closed by bacongobbler** 2021-06-28 17:14 UTC

**Comment by armsnyder** [comment] 2021-07-29 17:10
@bacongobbler Can you consider re-opening this please? I also expected Helm to support a yaml format for JSON schemas, as that is the format I am used to seeing for schemas in Kubernetes. (See how custom resource definition schemas work.)
