### ISSUE TITLE
helm del with invalid namespace.

### ISSUE THREAD

**Issue by kgmhk** [helm/helm#5305] opened 2019-02-14 05:45 UTC
Output of `helm version`: 2.12.3

Output of `kubectl version`: 1.12.3

Cloud Provider/Platform (AKS, GKE, Minikube etc.): No

I use  kube config context as follows.

```
$ kubectl config get-contexts
CURRENT   NAME                          CLUSTER      AUTHINFO           NAMESPACE
          dev1                           kubernetes   kubernetes        dev1
          default                       kubernetes   kubernetes
*         dev2                           kubernetes   kubernetes        dev2
```

I change context to dev2  and install chart using the following command..
```
$ kubectl config use-context dev2
Switched to context "dev2"
$ helm install --name=dev2
```
It makes the helm chart with correct namespace.

```
$ helm ls
NAME       	REVISION	UPDATED                 	STATUS  	CHART        	APP VERSION	NAMESPACE
dev2	   1       	Thu Feb 14 09:56:58 2019	DEPLOYED	dev-0.1.0	1.0        	dev2
```

But the problem happens with delete command.
I can delete the chart even though the context is not dev2.

Change the context to dev1

```
$ kubectl config use-context dev1
Switched to context "dev1".
``` 
And delete dev2's charts.

```
$ helm del --purge dev2
release "dev2" deleted
```

It is possible to delete chart from other namespace.
I think that the chart have to be only deleted on current context.

**Comment by bacongobbler** [comment] 2019-02-14 05:48
Hi @kgmhk, I'm not sure what's the issue here as there's not much information to determine what's the issue. Can you please provide the issue you're trying to describe? An example which we can attempt to reproduce would be very helpful. Thanks!

**Comment by kgmhk** [comment] 2019-02-14 06:01
@bacongobbler sorry my mistake. I added much information.

**Comment by bacongobbler** [comment] 2019-02-22 23:47
This is a side-effect of releases being globally namespaced. Closing as a duplicate of #2060.

**Closed by bacongobbler** 2019-02-22 23:47 UTC
Labels: question/support
