### ISSUE TITLE
helm chart pull/push should support --plain-http and --insecure option

### ISSUE THREAD

**Issue by youyongsong** [helm/helm#8464] opened 2020-07-16 03:51 UTC
Output of `helm version`: 3.0.0-rc1

helm only support `--insecure` option in the `helm registry login` command. In some cases we want to push or pull a chart to a insecure registry **anonymously**, currently when we use `helm chart pull` or `helm chart push` to a insecure registry it will return the following error:

```
$ helm chart push 192.168.3.6:5000/ysyou/cert-manager:v2.13
The push refers to repository [192.168.3.6:5000/ysyou/cert-manager]
ref:     192.168.3.6:5000/ysyou/cert-manager:v2.13
digest:  c9d19b41e1e28d59d1da8ccc0dc9078341f46afb300b24f1c9709cb6d790bcf0
size:    57.9 KiB
name:    cert-manager
version: v2.0-b.1
Error: failed to do request: Head "https://192.168.3.6:5000/v2/ysyou/cert-manager/blobs/sha256:6a9498d039faadfaa2e6bec408865a1a83d1f952f85fe431407964c10e9cad18": http: server gave HTTP response to HTTPS clien
```

Hope helm can add `--plain-http` and `--insecure` options in `helm chart push` and `helm chart pull` commands.

**Comment by hickeyma** [comment] 2020-07-16 07:43
@jdolitsky Is this something that would be considered?

**Comment by bacongobbler** [comment] 2020-07-16 13:55
Duplicate of https://github.com/helm/helm/issues/6324.

**Closed by bacongobbler** 2020-07-16 13:55 UTC
Labels: question/support
