### ISSUE TITLE
helm3 status 

### ISSUE THREAD

**Issue by cuisongliu** [helm/helm#7639] opened 2020-02-20 02:10 UTC
installed exec ' helm status aacc -n helm ' use helm3 no has resource of kubernetes,but use helm2 show it . 
Output of `helm version`:
helm3.0.2
Output of `kubectl version`:
1.15.5
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubernetes

**Comment by bacongobbler** [comment] 2020-02-20 07:35
duplicate of #7565 and #5952

**Closed by bacongobbler** 2020-02-20 07:35 UTC
