### ISSUE TITLE
Improve YAML parsing errors like "nil pointer evaluating interface {}"

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/helm#8656] opened 2020-08-26 09:40 UTC
For example, when a required template variable is not found in default or provided values:

```
$ helm template --debug stable/test-chart
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/max.williams/git/helm-charts/stable/test-chart


Error: template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create
helm.go:94: [debug] template: test-chart/templates/serviceaccount.yaml:1:14: executing "test-chart/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: nil pointer evaluating interface {}.create
```

`nil pointer evaluating interface` is not informative. Could we print something like `serviceAccount.create not found in values`?

**Comment by bacongobbler** [comment] 2020-09-01 16:02
closing as a duplicate of #8026.

**Closed by bacongobbler** 2020-09-01 16:02 UTC
