### ISSUE TITLE
Bug: scripts/get not installing latest helm 2.x version

### ISSUE THREAD

**Issue by ashithwilson** [helm/helm#9714] opened 2021-05-18 12:06 UTC
I'm using the script [helm/scripts/get](https://github.com/helm/helm/blob/main/scripts/get) to install latest version of helm2 but it is erroring out as below.

```bash
$ wget -O - https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get 2>/dev/null | bash

Downloading https://get.helm.sh/helm--linux-amd64.tar.gz
SHA sum of /tmp/helm-installer-sWGDPd/helm--linux-amd64.tar.gz does not match. Aborting.
Failed to install helm
	For support, go to https://github.com/helm/helm.
```

Looks like the script is checking the GitHub releases page for a version 2.x but running into error as no release with v2.0 is available at the first page itself. v2.x was pushed out to second page after recent releases.

**Comment by bacongobbler** [comment] 2021-05-18 14:26
Duplicate of #9607.

**Closed by bacongobbler** 2021-05-18 14:26 UTC
