### ISSUE TITLE
Can't upgrade from bare kubernetes to helm

### ISSUE THREAD

**Issue by u05rav** [helm/helm#4737] opened 2018-10-04 23:31 UTC
$ helm version
    Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
    Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}

    $ kubectl version
    Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:52:38Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

We're running kubernetes on our own onprem ubuntu 16.04 servers.

Previously we had a kubernetes deployment for our application which was just managed by deploying from yaml files using kubectl.  We have now moved on to using a helm chart for our deployments.  I have a couple of legacy installs running without helm and I need to migrate them to helm without downtime.

This is what I am seeing.  I start with a kubernetes only install featuring multiple namespaces, deployments, services, daemonsets, configmaps and secrets I try to install my helm chart over the top

    $ helm install /path/to/helm/chart/ -f config.yaml --name=chart-name  
    Error: release chart-name failed: services "service-name" already exists

I read in https://github.com/helm/helm/issues/1999 that I could try installing again but this doesn't work

    $ helm install /path/to/helm/chart/ -f config.yaml --name=chart-name
    Error: a release named chart-name already exists.
    Run: helm ls --all chart-name; to check the status of the release
     Or run: helm del --purge chart-name; to delete it

It thinks my chart is installed but it hasn't updated any of my containers.  Helm ls shows that status failed

    $ helm ls
    NAME 	REVISION	UPDATED                 	STATUS	CHART          	NAMESPACE
    chart-name	1       	Thu Oct  4 15:47:07 2018	FAILED	chart-name-544	default 

So I try to update the chart

    helm upgrade chart-name  /path/to/helm/chart/
    Error: UPGRADE FAILED: "chart-name" has no deployed releases

I get the same thing with --force

    helm upgrade chart-name  /path/to/helm/chart/ --force
    Error: UPGRADE FAILED: "chart-name" has no deployed releases

If there are no deployed resources then I should be able to delete the chart and start again.  

    $ helm delete --purge chart-name
    release "chart-name" deleted

This causes all deployments that were running and had matching deployments in the chart to terminate.  This is not good.

I have tried with various different versions of my helm chart.  Including one where I just dumped all the existing yamls from kubernetes into the templates dir but none of them will install cleanly.

Is there a better way of doing this?

**Comment by bacongobbler** [comment] 2018-10-18 21:47
hey @u05rav, this has already been reported previously so I'm going to close this as a duplicate of https://github.com/helm/helm/issues/3319. Thanks for the report!

**Closed by bacongobbler** 2018-10-18 21:47 UTC
Labels: question/support
