### ISSUE TITLE
--wait returns true when pod cannot start

### ISSUE THREAD

**Issue by Stono** [helm/helm#3296] opened 2017-12-24 12:24 UTC
Hi, 
I've just observed the fact that `helm install --wait`, which resulted in a pod being in an `ImagePullBackOff` state returned true.

Is this expected behaviour?  Because reading the help about wait it doesn't seem so:

"if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment are in a ready state before marking the release as successful."

```
❯ helm version
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
```

**Comment by bacongobbler** [comment] 2017-12-27 23:04
Yes, I believe this is to be expected behavior. IIRC `--wait` was implemented to wait until pods, pvcs, services etc. are all in a non-initial state, whether that be in "ready", "failed" or "errored" states. Feel like making a PR to clarify that assumption?

cc @thomastaylor312, am I right on that assumption?

**Comment by Stono** [comment] 2017-12-28 14:50
If that is the case, it'd be nice from a CI/CD perspective if we could add `wait-until-running` which waits for things to pass their `readinessProbes`

Thoughts?

**Comment by thomastaylor312** [comment] 2018-01-04 07:14
Actually it should be in a Ready state, so this is a bug. If anyone could take a look at this, that would be helpful because I'll be reviewing Helm CFPs 🙂

**Comment by omegarus** [comment] 2018-01-07 08:11
I'am having similar issue with helm v2.7.2 and k8s: 1.8.3. Seems that `--wait` flag doesn't wait for pods to became ready.

**Comment by thomastaylor312** [comment] 2018-01-09 06:32
I think I figured this out. So the `--wait` flag was only checking `extensions` API objects and not the new `apps` objects. We have updated this in helm 2.8, which has an RC available right now. @Stono and @omegarus if either of you want to try the RC out and see if the bug is fixed, that would be helpful

**Comment by thomastaylor312** [comment] 2018-04-11 21:27
@Stono Is this still an issue for you?

**Comment by bacongobbler** [comment] 2018-04-11 21:29
also pinging @kenden. Can you bump the thread with what you're observing in helm 2.9?

**Comment by samchenraising** [comment] 2018-04-25 16:26
I'm experiencing this problem with Helm v2.8.2 on k8s v1.7.12

**Comment by javipolo** [comment] 2018-05-10 14:30
I'm also experiencing this problem with Helm v2.9.0 and k8s v1.8.4:

```
$ helm upgrade --wait --set image.tag=v201 --set namespace=testing --namespace=testing mystuff etc/helm
Release "mystuff" has been upgraded. Happy Helming!

LAST DEPLOYED: Thu May 10 14:21:40 2018
NAMESPACE: testing
STATUS: DEPLOYED

RESOURCES:

==> v1/Service
NAME     TYPE       CLUSTER-IP    EXTERNAL-IP  PORT(S)  AGE
mystuff  ClusterIP  10.200.0.163  <none>       80/TCP   3h

==> v1beta1/Deployment
NAME     DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
mystuff  1        1        1           0          3h

==> v1/Pod(related)
NAME                      READY  STATUS             RESTARTS  AGE
mystuff-6d448567dc-b72rq  0/2    Terminating        0         30m
mystuff-77c77fd76f-6dxbm  0/2    ContainerCreating  0         2s
```

and then helm exits successfuly

**Comment by thomastaylor312** [comment] 2018-05-10 22:11
I believe I found the issue with this. I am trying out a fix right now

**Comment by thomastaylor312** [comment] 2018-05-11 20:59
Ok, update on the issue. Due to the nature of how k8s handles different versions API objects, the fix for this will be non-trivial, hacky, and likely brittle based on all current observations. I'll be bringing this up in the Helm dev call this next week for further discussion and ideas

**Comment by moritzheiber** [comment] 2018-06-08 08:34
This is a real issue, especially in CI/CD environments .. I would love to see this treated with a little more urgency :slightly_smiling_face:

**Comment by thomastaylor312** [comment] 2018-06-21 00:27
I am trying to scrape together the time to do it. Hoping I can get to it next week.

**Comment by bacongobbler** [comment] 2018-06-21 01:18
Might be relevant: https://github.com/kubernetes/helm/issues/4210#issuecomment-398810327

**Comment by javipolo** [comment] 2018-09-12 10:15
Any updates on this?
Thanks a lot for your work on it @thomastaylor312

**Comment by adrian** [comment] 2019-07-25 09:56
Is this still a problem? I've been testing with Helm v2.12.3 and Kubernetes v1.15.0 and haven't seen any issues.

**Comment by thomastaylor312** [comment] 2019-07-25 21:55
I am not sure if it is for Helm 2, but it has been completely fixed in the latest Helm 3 alpha

**Closed** 2020-05-14 20:55 UTC
Labels: bug
