### ISSUE TITLE
[Helm 3] [Bug] New Registry/Chart Commands not pulling

### ISSUE THREAD

**Issue by aperullo** [helm/helm#7981] opened 2020-04-23 17:54 UTC
Output of `helm version`:
`version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
Issue:

I was trying out the experimental `helm registry` and `helm chart` commands and found I was unable to pull charts if I didn't create them. 

```
> helm chart pull private-reg.comp.name/project/mychart:0.1.0
Error: blob sha256:355a6550ed5ec3bca56caac650ef0229f274ea7f4b47e29425b39d0f8cfe254e expected at /home/ant/.cache/helm/registry/cache/blobs/sha256/355a6550ed5ec3bca56caac650ef0229f274ea7f4b47e29425b39d0f8cfe254e: not found
```
Now compare if I first create and push, then pull:

```
> helm chart save mychart/ private-reg.comp.name/project/mychart:1.0.0
ref:     private-reg.comp.name/project/mychart:1.0.0
digest:  13a89143acab2394e5a4b85c1eeea1af412fc07526a3027bf00021cc2c7ede8e
size:    9.5 KiB
name:    my-chart
version: 0.1.0
latest: saved

> helm3 chart push private-reg.comp.name/project/mychart:1.0.0
The push refers to repository [private-reg.comp.name/project/mychart]
ref:     private-reg.comp.name/project/mychart:1.0.0
digest:  13a89143acab2394e5a4b85c1eeea1af412fc07526a3027bf00021cc2c7ede8e
size:    9.5 KiB
name:    my-chart
version: 0.1.0
latest: pushed to remote (1 layer, 9.5 KiB total)

> [clear the cache]
> helm chart pull private-reg.comp.name/project/mychart:1.0.0
latest: Pulling from private-reg.comp.name/project/mychart
ref:     private-reg.comp.name/project/mychart:1.0.0
digest:  13a89143acab2394e5a4b85c1eeea1af412fc07526a3027bf00021cc2c7ede8e
size:    9.5 KiB
name:    my-chart
version: 0.1.0
Status: Chart is up to date for private-reg.comp.name/project/mychart:1.0.0
```

**Comment by aperullo** [comment] 2020-04-23 18:08
Sorry let me clarify, someone else has pushed the chart to the repository in the first example. Its present. I can't pull it.

**Comment by bacongobbler** [comment] 2020-04-23 18:10
Can you demonstrate how that can happen? How did the other user push the chart to the registry? If you can provide more steps to reproduce the issue, that would be most helpful.

**Comment by aperullo** [comment] 2020-04-23 18:16
Yeah we tried both:

```
> helm chart save ./mychart.tgz private-reg.comp.name/project/mychart:0.1.0

> helm chart push private-reg.comp.name/project/mychart:0.1.0
```
and

```
> helm chart save mychart private-reg.comp.name/project/mychart:0.1.0

> helm chart push private-reg.comp.name/project/mychart:0.1.0
```
That is to say, we tried both the raw chart (as folders) and the packaged tar you get from `helm package`

**Comment by bacongobbler** [comment] 2020-04-23 18:21
Can you please provide more system information? What version of Helm were each of you using? What operating system? What chart?

The reason I'm asking is that in order to test and confirm this issue, we need to be able to reproduce the same setup (or someone else from the community has to demonstrate the same symptoms using the asme setup). Please provide as much information as you can so that we have a shot at reproducing the same issue on our end. Operating systems, Helm versions of each system, what registry was used, etc. Reproducing this in a Dockerized environment would be helpful to isolate local setup issues.

Thanks.

**Comment by jdolitsky** [comment] 2020-04-23 19:03
There error message may indicate some corrupted chart cache.. Can you add the output with the `--debug` flag?

You might also try to removing the cache at `/home/ant/.cache/helm`

**Comment by aperullo** [comment] 2020-04-23 19:19
@jdolitsky I think you are correct. I fixed the cache file and now can't seem to reproduce whatever corrupted it.

**Comment by bacongobbler** [comment] 2020-04-23 19:23
Closing for now. Please feel free to reopen if you happen to reproduce it in some other manner.

**Closed by bacongobbler** 2020-04-23 19:23 UTC
Labels: question/support

**Comment by Nek0trkstr** [comment] 2020-05-04 09:53
Happened here, deleting cache helped like a charm but its still annoying. Wasn't able to reproduce...
```
helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Comment by jdolitsky** [comment] 2020-05-05 16:19
@Nek0trkstr just opened this new issue to track: https://github.com/helm/helm/issues/8059
