### ISSUE TITLE
Error: unknown command "chart" for "helm"

### ISSUE THREAD

**Issue by neeharreddy93** [helm/helm#10185] opened 2021-09-26 03:25 UTC
Our Azure DevOps builds suddenly started failing with below error no changes from our end, we are pushing charts to ACR and its been working fine from past 4 months all of sudden builds started failing!! please help 

Error: unknown command "chart" for "helm"

Not sure why we are getting errors suddenly, we are using ubuntu-latest agent and i tried specifying installing latest helm version as well in build pipeline. Looks weird to me ! can someone help helm support team? 

 Commands:

    - bash: |
       export HELM_EXPERIMENTAL_OCI=1
       echo '$(registryPassword)' | helm registry login $(containerRegistry) --username $(registryLogin) --password-stdin
       helm chart save $(System.DefaultWorkingDirectory)/helmchart/ $(containerRegistry)/$(helmRepository):$(tag)
       helm chart push $(containerRegistry)/$(helmRepository):$(tag)

**Comment by yxxhero** [comment] 2021-09-26 05:32
@jdolitsky Can you take a look at this issue? Thanks very much.

**Comment by neeharreddy93** [comment] 2021-09-26 15:35
@yxxhero @jdolitsky I also want to know whether azure supports helm 3.7?

**Comment by faizanf47** [comment] 2021-09-27 06:06
Actually in Helm 3.7.0 chart is not a command at all. Take a look at release page:
https://github.com/helm/helm/releases

**Comment by hickeyma** [comment] 2021-09-27 06:37
Duplicate of #10145

**Comment by hickeyma** [comment] 2021-09-27 06:37
Closing as a duplicate

**Closed by hickeyma** 2021-09-27 06:37 UTC
Labels: question/support
