### ISSUE TITLE
tiller pod keeps crashing

### ISSUE THREAD

**Issue by weinong** [helm/helm#3125] opened 2017-11-10 19:47 UTC
k8s: 1.7.5
helm/tiller: 2.6.0
platform: Azure/acs-engine
```
kubectl get po -n kube-system
NAME                                            READY     STATUS             RESTARTS   AGE
heapster-342135353-v4ffx                        2/2       Running            4          50d
kube-addon-manager-k8s-master-41044328-0        1/1       Running            2          50d
kube-addon-manager-k8s-master-41044328-1        1/1       Running            2          50d
kube-addon-manager-k8s-master-41044328-2        1/1       Running            2          50d
kube-apiserver-k8s-master-41044328-0            1/1       Running            2          50d
kube-apiserver-k8s-master-41044328-1            1/1       Running            2          50d
kube-apiserver-k8s-master-41044328-2            1/1       Running            2          50d
kube-controller-manager-k8s-master-41044328-0   1/1       Running            2          50d
kube-controller-manager-k8s-master-41044328-1   1/1       Running            2          50d
kube-controller-manager-k8s-master-41044328-2   1/1       Running            2          50d
kube-dns-v20-3119293658-ksh3v                   2/3       Running            8          10m
kube-dns-v20-3119293658-sm0c2                   3/3       Running            3          24d
kube-proxy-262pm                                1/1       Running            2          50d
kube-proxy-5g09p                                1/1       Running            2          50d
kube-proxy-7t014                                1/1       Running            2          50d
kube-proxy-95198                                1/1       Running            2          50d
kube-proxy-lghr5                                1/1       Running            3          50d
kube-proxy-lp6bc                                1/1       Running            3          50d
kube-proxy-qxdlp                                1/1       Running            2          50d
kube-proxy-rqwlc                                1/1       Running            2          50d
kube-scheduler-k8s-master-41044328-0            1/1       Running            2          50d
kube-scheduler-k8s-master-41044328-1            1/1       Running            2          50d
kube-scheduler-k8s-master-41044328-2            1/1       Running            2          50d
kubernetes-dashboard-924040265-jz9x7            1/1       Running            374        24d
tiller-deploy-2003435939-qstjt                  0/1       CrashLoopBackOff   45         24d
```
```
kubectl describe po -n kube-system tiller-deploy-2003435939-qstjt
Name:           tiller-deploy-2003435939-qstjt
Namespace:      kube-system
Node:           k8s-agentpool-41044328-2/10.240.0.5
Start Time:     Tue, 17 Oct 2017 19:36:11 +0000
Labels:         app=helm
                name=tiller
                pod-template-hash=2003435939
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"tiller-deploy-2003435939","uid":"28727f3a-9e3e-11e7-a18a-000...
Status:         Running
IP:             10.244.5.4
Created By:     ReplicaSet/tiller-deploy-2003435939
Controlled By:  ReplicaSet/tiller-deploy-2003435939
Containers:
  tiller:
    Container ID:   docker://2d7d532ec6822d53b3df0badcbb5c672250cc00190725f6f4db22dce2cc66a58
    Image:          gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.0
    Image ID:       docker-pullable://gcrio.azureedge.net/kubernetes-helm/tiller@sha256:6f1aef0a851de5bd0abecc8dcd9870c7590f7f995874d9e6010ae9e82e5e0f49
    Port:           44134/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 10 Nov 2017 19:36:58 +0000
      Finished:     Fri, 10 Nov 2017 19:37:17 +0000
    Ready:          False
    Restart Count:  45
    Limits:
      cpu:     50m
      memory:  150Mi
    Requests:
      cpu:      50m
      memory:   150Mi
    Liveness:   http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:  kube-system
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-k839f (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  tiller-token-k839f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-k839f
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     <none>
Events:
  Type     Reason      Age                 From                               Message
  ----     ------      ----                ----                               -------
  Normal   Pulled      1m (x44 over 1h)    kubelet, k8s-agentpool-41044328-2  Container image "gcrio.azureedge.net/kubernetes-helm/tiller:v2.6.0" already present on machine
  Normal   Created     1m (x44 over 1h)    kubelet, k8s-agentpool-41044328-2  Created container
  Normal   Started     1m (x44 over 1h)    kubelet, k8s-agentpool-41044328-2  Started container
  Warning  Unhealthy   1m (x89 over 1h)    kubelet, k8s-agentpool-41044328-2  Readiness probe failed: Get http://10.244.5.4:44135/readiness: dial tcp 10.244.5.4:44135: getsockopt: connection refused
  Normal   Killing     1m (x45 over 1h)    kubelet, k8s-agentpool-41044328-2  Killing container with id docker://tiller:pod "tiller-deploy-2003435939-qstjt_kube-system(6e4c2507-b372-11e7-8aa0-000d3ab1ed58)" container "tiller" is unhealthy, it will be killed and re-created.
  Warning  Unhealthy   1m (x89 over 1h)    kubelet, k8s-agentpool-41044328-2  Liveness probe failed: Get http://10.244.5.4:44135/liveness: dial tcp 10.244.5.4:44135: getsockopt: connection refused
  Warning  FailedSync  13s (x490 over 1d)  kubelet, k8s-agentpool-41044328-2  Error syncing pod
  Warning  BackOff     13s (x488 over 1h)  kubelet, k8s-agentpool-41044328-2  Back-off restarting failed container
```
```
kubectl describe no k8s-agentpool-41044328-2
Name:               k8s-agentpool-41044328-2
Roles:              <none>
Labels:             agentpool=agentpool
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_D3_v2
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=northeurope
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.io/hostname=k8s-agentpool-41044328-2
                    msi-enable=true
                    role=agent
                    storageprofile=managed
                    storagetier=Standard_LRS
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             <none>
CreationTimestamp:  Wed, 20 Sep 2017 20:02:22 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 20 Sep 2017 20:02:37 +0000   Wed, 20 Sep 2017 20:02:37 +0000   RouteCreated                 RouteController created a route
  OutOfDisk            False   Fri, 10 Nov 2017 19:39:19 +0000   Sat, 04 Nov 2017 23:46:49 +0000   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure       False   Fri, 10 Nov 2017 19:39:19 +0000   Sat, 04 Nov 2017 23:46:49 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Fri, 10 Nov 2017 19:39:19 +0000   Sat, 04 Nov 2017 23:46:49 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  Ready                True    Fri, 10 Nov 2017 19:39:19 +0000   Thu, 09 Nov 2017 10:15:53 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  10.240.0.5
  Hostname:    k8s-agentpool-41044328-2
Capacity:
 alpha.kubernetes.io/nvidia-gpu:  0
 cpu:                             4
 memory:                          14359432Ki
 pods:                            110
Allocatable:
 alpha.kubernetes.io/nvidia-gpu:  0
 cpu:                             4
 memory:                          14257032Ki
 pods:                            110
System Info:
 Machine ID:                 833e0926ee21aed71ec075d726cbcfe0
 System UUID:                FF54E8A4-320D-6540-9F50-8FF6F18911DD
 Boot ID:                    1e7574cd-b863-4d74-9c4a-a58e8278db13
 Kernel Version:             4.4.0-98-generic
 OS Image:                   Debian GNU/Linux 8 (jessie)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://1.12.6
 Kubelet Version:            v1.7.5
 Kube-Proxy Version:         v1.7.5
PodCIDR:                     10.244.5.0/24
ExternalID:                  /subscriptions/a6cec963-c286-421a-b449-e842b26cee9a/resourceGroups/acs-prod-europesector-northeurope/providers/Microsoft.Compute/virtualMachines/k8s-agentpool-41044328-2
Non-terminated Pods:         (9 in total)
  Namespace                  Name                                      CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ---------                  ----                                      ------------  ----------  ---------------  -------------
  containerservice           containerservice-1945594285-m6vs3         0 (0%)        0 (0%)      0 (0%)           0 (0%)
  containerservice-async     containerserviceasync-1900242997-hn4g1    0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    mdm-2968816999-rn8qt                      0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    mdsd-p8hk6                                0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    msi-proxy-3096262957-t5msm                0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    omsagent-0bbzc                            0 (0%)        0 (0%)      0 (0%)           0 (0%)
  default                    td-agent-78ncd                            0 (0%)        0 (0%)      0 (0%)           0 (0%)
  kube-system                kube-proxy-rqwlc                          100m (2%)     0 (0%)      0 (0%)           0 (0%)
  kube-system                tiller-deploy-2003435939-qstjt            50m (1%)      50m (1%)    150Mi (1%)       150Mi (1%)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  CPU Requests  CPU Limits  Memory Requests  Memory Limits
  ------------  ----------  ---------------  -------------
  150m (3%)     50m (1%)    150Mi (1%)       150Mi (1%)
Events:         <none>
```
```
kubectl logs -n kube-system tiller-deploy-2003435939-qstjt
[main] 2017/11/10 19:37:00 Starting Tiller v2.6.0 (tls=false)
[main] 2017/11/10 19:37:00 GRPC listening on :44134
[main] 2017/11/10 19:37:00 Probes listening on :44135
[main] 2017/11/10 19:37:00 Storage driver is ConfigMap
```

If I delete the pod, the new one seems to work...

**Comment by thomastaylor312** [comment] 2017-11-11 01:35
Everything you posted makes it seem like it is ok. Were there any other pods running in the cluster that were exhibiting similar issues?

**Comment by davidchua** [comment] 2018-01-22 03:16
Having the same issue here as well.

Similar to OP, except that I'm on

```
Platform: Minikube v0.23.0
Kubernetes: v1.8.0
Helm: v2.7.2
```

It happens usually when I try to do a `helm upgrade` and the `helm upgrade ` will just timeout with a `Error: UPGRADE FAILED: transport is closing`.

When that happens, I will then see that the tiller pod is dead `0/1` and logs on the pod will not show any crash message .

**Comment by thomastaylor312** [comment] 2018-01-23 23:11
@davidchua Did `kubectl logs <tiller_pod> --previous` not show anything either?

**Comment by davidchua** [comment] 2018-02-06 08:49
@thomastaylor312 sorry, my github notifications is wonky.

Nope, it doesn't show anything in particular. No error messages.

**Comment by TomaszUrugOlszewski** [comment] 2018-02-06 08:57
I had exactly same issues in GCP k8s cluster. Nothing in logs, tiller-deploy restarting from time to time. Scaling VMs up for more RAM solved it. Now it's stable as rock.

**Comment by bacongobbler** [comment] 2018-02-06 16:12
The error and behaviour (tiller being evicted from the node) seems like it's the same as what we're seeing in https://github.com/kubernetes/helm/issues/3409. Can anyone take a look and see if we should consolidate these two issues together?

**Comment by benlangfeld** [comment] 2018-02-06 19:10
@bacongobbler #3409 is nothing to do with Tiller being evicted. In that issue, Tiller is running throughout.

**Comment by bacongobbler** [comment] 2018-02-06 19:13
[Some users say otherwise](https://github.com/kubernetes/helm/issues/3409#issuecomment-363305676). Sorry! Just trying to triangulate between the different symptoms of this error.

**Comment by tasiyo7333** [comment] 2018-03-06 06:12
I had the same problem , but I solved it.

In my case , FluentD daemonset also crash many times.

FluentD sends log to Elasticsearch(AWS ES service) , and ES's FreeStorageSpace had been zero.
This had caused FluentD to crash . 
And it also had influenced tiller.

So, I removed some indices in ES.
After that , FluentD and tiller-deploy have not been restarting any more.

My configurations are the followings.

Cloud：AWS

```sh
$ kops version
Version 1.8.1
```
```sh
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:50:44Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

```sh
$ helm version

Client: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.1", GitCommit:"6af75a8fd72e2aa18a2b278cfe5c7a1c5feca7f2", GitTreeState:"clean"}
```

**Comment by sorenmat** [comment] 2018-09-25 07:05
We are seeing the same behaviour as @davidchua just with a newer version of Helm and Tiller.
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

It might happened when i upgrade --wait fails because of the timeout, this is yet to be confirmed though. But all evidence points in that direction

**Comment by mttr** [comment] 2018-10-16 21:44
After experiencing this in the wild myself, I've been able to narrow down an easy way to reliably reproduce this. It looks like tiller crashes when trying to `--force` upgrade a release that is stuck with the status `PENDING_INSTALL`.

1. `helm upgrade --install foo {anychart}` (assumes a release named `foo` does not already exist)
2. `kubectl patch configmap foo.v1 -p '{"metadata":{"labels":{"STATUS": "PENDING_INSTALL"}}}' --namespace kube-system`
3. `helm upgrade --install foo {samechart} --force`

The last command results in: 
`Error: UPGRADE FAILED: transport is closing`
`tiller-deploy-67d8b477f7-brsvb              0/1       CrashLoopBackOff   13         20h`

**Comment by williamchong007** [comment] 2018-11-06 12:53
My tiller-deploy is having a `CrashLoopBackOff` loop due to `Liveness probe failed: getsockopt: connection refused` with `2.11.0`
What can I do to figure out whats what?

**Comment by bacongobbler** [comment] 2018-11-06 17:05
can you check `kubectl describe po <failing tiller pod>`?

**Comment by williamchong007** [comment] 2018-11-07 04:01
```
Name:           tiller-deploy-758ccd65c6-xjqrl
Namespace:      kube-system
Node:           gke-develop-v2-default-pool-ef607479-t3sj
Start Time:     Tue, 06 Nov 2018 20:58:51
Labels:         app=helm
                name=tiller
                pod-template-hash=3147782172
Annotations:    <none>
Status:         Running
IP:             10.28.3.3
Controlled By:  ReplicaSet/tiller-deploy-758ccd65c6
Containers:
  tiller:
    Container ID:   docker://76dcb6bb124ecd11fcb9bfe152f3be773c530e5ad47e581bbbf0007078de503d
    Image:          gcr.io/kubernetes-helm/tiller:v2.11.0
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:f6d8f4ab9ba993b5f5b60a6edafe86352eabe474ffeb84cb6c79b8866dce45d1
    Ports:          44134/TCP, 44135/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 07 Nov 2018 11:53:57
      Finished:     Wed, 07 Nov 2018 11:54:17
    Ready:          False
    Restart Count:  281
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  0
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-9qtg5 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  tiller-token-9qtg5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-9qtg5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                                     Message
  ----     ------     ----                 ----                                                     -------
  Normal   Pulled     26m (x272 over 13h)  kubelet, gke-develop-v2-default-pool-ef607479-t3sj  Container image "gcr.io/kubernetes-helm/tiller:v2.11.0" already present on machine
  Warning  BackOff    6m (x3299 over 13h)  kubelet, gke-develop-v2-default-pool-ef607479-t3sj  Back-off restarting failed container
  Warning  Unhealthy  1m (x495 over 13h)   kubelet, gke-develop-v2-default-pool-ef607479-t3sj  Readiness probe failed: Get http://10.28.3.3:44135/readiness: dial tcp 10.28.3.3:44135: getsockopt: connection refused
```
Extra info: I tried adding 1 more k8s node, the problem goes away; if I remove the extra node, it start crashing again. It seems that it is not being evicted, but it just crashes itself without any log. @bacongobbler

**Comment by bacongobbler** [comment] 2018-11-07 04:55
So if adding a new node to the cluster removes the problem, then perhaps the issue is with the node?

**Comment by williamchong007** [comment] 2018-11-07 09:42
Turns out the problem was other containers in a node burning all CPU resources (some bugged istio mixers in my case), making `tiller-deploy` always not ready for liveness probe, nor commands.

sorry for the dumb question

**Closed** 2018-11-07 15:10 UTC
Labels: question/support
