### ISSUE TITLE
Helm not respecting "--history-max"  setting when upgrading chart revisions

### ISSUE THREAD

**Issue by aric49** [helm/helm#5285] opened 2019-02-08 21:05 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Minikube

It appears that Helm/Tiller is not respecting the `--history-max`  flag in the Tiller deployment. I noticed this behavior in our Non Production K8s cluster and was able to replicate it in MiniKube.   First, I initialize a new tiller instance using the `--history-max` flag:

```
helm init --upgrade --service-account tiller --history-max 3
```

Next, I create a new empty Helm chart (test-chart):

```
helm create test-chart
```

Finally, I run a helm upgrade with the install flag flag, 6 times to create 6 revisions:

```
helm upgrade -i test-chart ./test-chart
```

Checking `helm ls`, I can see that I now have 6 revisions available, when the history-max setting is configured to allow only 3 maximum revisions:

```
$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
test-chart      6               Fri Feb  8 15:09:23 2019        DEPLOYED        test-chart-0.1.0        1.0             default  
```

Inspecting the tiller pod, I can see that the max history flag is displayed as an environment variable:

```
$ kubectl describe pod tiller-deploy-6944dcd6dc-c2cqh -n kube-system
Name:           tiller-deploy-6944dcd6dc-c2cqh
Namespace:      kube-system
Node:           minikube/10.0.2.15
Start Time:     Fri, 08 Feb 2019 15:04:11 -0500
Labels:         app=helm
                name=tiller
                pod-template-hash=2500878287
Annotations:    <none>
Status:         Running
IP:             172.17.0.7
Controlled By:  ReplicaSet/tiller-deploy-6944dcd6dc
Containers:
  tiller:
    Container ID:   docker://3c0501e61579ef1ab0136915f83a2ef8a977aa142e5966d7248feb1524cf6af7
    Image:          gcr.io/kubernetes-helm/tiller:v2.12.0
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:67b4962dd091bfca1398853f55b6414ac433042560c1a163520dd0811c0e2e28
    Ports:          44134/TCP, 44135/TCP
    State:          Running
      Started:      Fri, 08 Feb 2019 15:04:16 -0500
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  3
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-rtl77 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  tiller-token-rtl77:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-rtl77
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              57m   default-scheduler  Successfully assigned tiller-deploy-6944dcd6dc-c2cqh to minikube
  Normal  SuccessfulMountVolume  57m   kubelet, minikube  MountVolume.SetUp succeeded for volume "tiller-token-rtl77"
  Normal  Pulling                57m   kubelet, minikube  pulling image "gcr.io/kubernetes-helm/tiller:v2.12.0"
  Normal  Pulled                 57m   kubelet, minikube  Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.12.0"
  Normal  Created                57m   kubelet, minikube  Created container
  Normal  Started                57m   kubelet, minikube  Started container

```

To my understanding, the `--history-max` flag should be limiting the number of revisions of a given helm chart to 3 only.  Let me know if I am doing something incorrectly, or can provide further output to help with debugging. 

Thanks in Advance!

**Comment by bacongobbler** [comment] 2019-02-08 21:20
certain flags like --history-max are not read in during an upgrade. It's best to perform a `helm reset --force` then `helm init` without the --upgrade flag, then observe the behaviour on the next upgrade.

You can check for yourself if this flag is set by checking `kubectl -n kube-system get deploy tiller-deploy -o yaml`, then looking for the value under TILLER_HISTORY_MAX in the pod spec's environment variables.

**Comment by aric49** [comment] 2019-02-11 19:39
@bacongobbler  -- thanks for the response.  My apologies, I accidentally posed my command with the `--upgrade` flag, which was something I had done testing different scenarios.   I re-created my usecase using the following commands on a fresh Minikube instance:

1) Initialize Helm:   `helm init --service-account tiller --history-max 3`
2) inspect tiller pod and validate `TILLER_HISTORY_MAX` environment variable:

```
$ kubectl describe pod tiller-deploy-6944dcd6dc-src4k -n kube-system
Name:           tiller-deploy-6944dcd6dc-src4k
Namespace:      kube-system
Node:           minikube/10.0.2.15
Start Time:     Mon, 11 Feb 2019 14:32:09 -0500
Labels:         app=helm
                name=tiller
                pod-template-hash=2500878287
Annotations:    <none>
Status:         Running
IP:             172.17.0.7
Controlled By:  ReplicaSet/tiller-deploy-6944dcd6dc
Containers:
  tiller:
    Container ID:   docker://e0a9fb3eb80499848c351b74f7e14ef02b94425b242dad0e3f7eb13b17742c88
    Image:          gcr.io/kubernetes-helm/tiller:v2.12.0
    Image ID:       docker-pullable://gcr.io/kubernetes-helm/tiller@sha256:67b4962dd091bfca1398853f55b6414ac433042560c1a163520dd0811c0e2e28
    Ports:          44134/TCP, 44135/TCP
    State:          Running
      Started:      Mon, 11 Feb 2019 14:32:14 -0500
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:44135/liveness delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:44135/readiness delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment:
      TILLER_NAMESPACE:    kube-system
      TILLER_HISTORY_MAX:  3
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from tiller-token-nm4tj (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  tiller-token-nm4tj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tiller-token-nm4tj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              4m    default-scheduler  Successfully assigned tiller-deploy-6944dcd6dc-src4k to minikube
  Normal  SuccessfulMountVolume  4m    kubelet, minikube  MountVolume.SetUp succeeded for volume "tiller-token-nm4tj"
  Normal  Pulling                4m    kubelet, minikube  pulling image "gcr.io/kubernetes-helm/tiller:v2.12.0"
  Normal  Pulled                 4m    kubelet, minikube  Successfully pulled image "gcr.io/kubernetes-helm/tiller:v2.12.0"
  Normal  Created                4m    kubelet, minikube  Created container
  Normal  Started                4m    kubelet, minikube  Started container
```
3) Run `helm upgrade -i` command 6X to create 6 revisions of the same chart: `helm upgrade -i test-chart ./test-chart`

4) Look at revisions from `helm ls`:

```
$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
test-chart      6               Mon Feb 11 14:34:03 2019        DEPLOYED        test-chart-0.1.0        1.0             default  
```

Do let me know if you have any other suggestions for debugging or getting to the bottom of this.

**Comment by bacongobbler** [comment] 2019-02-11 20:42
What state are the deployments in? Can you show the output of `helm history test-chart`?

**Comment by aric49** [comment] 2019-02-11 21:00
Sure:

```
$ helm history test-chart
REVISION        UPDATED                         STATUS          CHART                   DESCRIPTION     
5               Mon Feb 11 14:34:00 2019        SUPERSEDED      test-chart-0.1.0        Upgrade complete
6               Mon Feb 11 14:34:01 2019        SUPERSEDED      test-chart-0.1.0        Upgrade complete
7               Mon Feb 11 14:34:03 2019        DEPLOYED        test-chart-0.1.0        Upgrade complete
```

Ah!  I think I see it now....   so it's only keeping the last three revisions, even though the revision count is higher than 3?  correct?

**Comment by bacongobbler** [comment] 2019-02-11 21:04
Yes.

**Comment by bacongobbler** [comment] 2019-02-11 21:52
Closing as it's working as intended.

**Closed** 2019-02-11 21:52 UTC
Labels: question/support
