### ISSUE TITLE
new warnings break machine-readable version parsing

### ISSUE THREAD

**Issue by nicks** [helm/helm#8786] opened 2020-09-22 02:37 UTC
Repro steps:

Run:
```
chmod a+r ~/.kube/config
helm version --short
```

Result:

```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/nick/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/nick/.kube/config
v3.3.3+g55e3ca0
```

Expected:
I would expect `helm version --short` to produce a semver string that can be reasonably parsed by machines. 

Possible solutions:
- Warnings should be on stderr (instead of stdout like machine-readable outputs)
- Alternatively, I don't see why `helm version` should be reading the kubeconfig at all

**Comment by bacongobbler** [comment] 2020-09-22 02:51
Duplicate of #8776. See #8779 for a fix. Please make sure to search before opening a new issue. Thanks.

**Closed by bacongobbler** 2020-09-22 02:51 UTC

**Comment by nicks** [comment] 2020-09-22 03:04
thanks! oops, i think i missed that b/c it was tagged "question"
