### ISSUE TITLE
Cannot push chart to 127.0.0.1 OCI registry

### ISSUE THREAD

**Issue by damlys** [helm/helm#7480] opened 2020-01-28 18:18 UTC
Hello :wave: I've found such bug that Helm command is unable to save chart with IP used as OCI registry host. See command below:

```
$ helm chart save . "127.0.0.1:55000/example:0.0.0"
Error: parse 127.0.0.1:55000/example: first path segment in URL cannot contain colon
```

On the other hand it's possible to save it with `localhost` as host, but Docker allows to use DNS as well as IP

```
$ helm chart save . "localhost:55000/example:0.0.0"
ref:     localhost:55000/example:0.0.0
digest:  19c482861b6ad6697666a30dc642d2b8ff1cf6d3e842c1130ad4b01b11d5b963
size:    21.3 KiB
name:    the-web-cloud-platform
version: 0.0.0
0.0.0: saved
```

Output of `helm version`:

```
$ helm version 
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

$ echo $HELM_EXPERIMENTAL_OCI
1
```

**Comment by bacongobbler** [comment] 2020-01-28 19:11
duplicate of https://github.com/helm/helm/issues/6977.

**Closed by bacongobbler** 2020-01-28 19:11 UTC
Labels: bug
