### ISSUE TITLE
https://api.github.com/repos/helm/helm/releases/latest returns helm v2.16.3

### ISSUE THREAD

**Issue by henotecq** [helm/helm#7597] opened 2020-02-14 18:54 UTC
Since this morning, the url https://api.github.com/repos/helm/helm/releases/latest returns helm version v2.16.3. Yesterday, it was returning v3.0.3, which is the actual latest version. 

I work with Azure, and I use the following instruction to install Helm:
steps:
  - task: HelmInstaller@1

The log is:
Downloading: https://api.github.com/repos/helm/helm/releases/latest
Downloading: https://get.helm.sh/helm-v2.16.3-linux-amd64.zip

Yesterday, the log for the same instruction was:
Downloading: https://api.github.com/repos/helm/helm/releases/latest
Downloading: https://get.helm.sh/helm-v3.0.3-linux-amd64.zip

I fixed the problem by specifying the helm version:
steps:
  - task: HelmInstaller@1
    inputs:
      helmVersionToInstall: 3.0.3

Yet, I believe that latest should return version 3.0.3 for now.

**Comment by bacongobbler** [comment] 2020-02-14 19:00
GitHub does not let a project control what is determined as “latest”. “latest” is equivalent to whichever release was most recently published. Azure's HelmInstaller task needs to be updated to use the correct API to determine the "latest" version of Helm themselves.

Here's how our `get-helm-3` script finds the latest release: https://github.com/helm/helm/blob/5ecf3fc09915a0c42027dce749ccbf9a0996353f/scripts/get-helm-3#L79-L89

Closing as a duplicate of #7590, #7592 and #7594.

**Closed by bacongobbler** 2020-02-14 19:00 UTC

**Comment by ozbillwang** [comment] 2020-02-17 10:45
@bacongobbler 

Thanks to point to that script. Since you insist to get the latest release via that script, we have to follow. 

But I do prefer if you can manage the latest release properly in Github release as well. 

To be honest,  when I see the function in this script you highlighted, it is very surprise me, which has so low quality on how to use AWK properly.

**Comment by bacongobbler** [comment] 2020-02-17 15:47
It’s not something we can control. This is the behaviour of github’s /latest API endpoint.
