### ISSUE TITLE
Need a way to order sub charts deployment specified in requirement.yaml

### ISSUE THREAD

**Issue by Dhananjay-J-P** [helm/helm#5955] opened 2019-06-28 08:47 UTC
Is there any way we can set order in which subcharts will be deployed. Currently, I have a chart with some subcharts, lets say chart a, chart b, chart c ... chart n. 

can I set order so that unless until chart a's container is up chart b won't be launched?

**Comment by hickeyma** [comment] 2019-06-28 13:01
Closing as a duplicate of https://github.com/helm/helm/issues/5723.

**Closed by hickeyma** 2019-06-28 13:01 UTC
