### ISSUE TITLE
Will helm template support chart reference or other expressions?

### ISSUE THREAD

**Issue by Lastcysa** [helm/helm#5850] opened 2019-06-06 06:20 UTC
Hi,

Currently `helm template` only supports local chart, which means if I want to `helm template` a chart reference or url, I must `helm fetch` to local first, if I understand correctly.  Will `helm template` support direct access to chart reference? If not, what is the concern?

Thanks!

**Comment by bacongobbler** [comment] 2019-06-06 06:37
This is supported in Helm 3. #5809 addresses this for Helm 2.

Closing as a duplicate of #5773

**Closed by bacongobbler** 2019-06-06 06:37 UTC
