### ISSUE TITLE
lint undefined keys and "and"

### ISSUE THREAD

**Issue by dbainbri-ciena** [helm/helm#6705] opened 2019-10-19 03:39 UTC
defaults:
    image_tag: ~

tag: '{{- if and (hasKey .Values.defaults "image_tag") (.Values.defaults.image_tag){{.Values.defaults.image_tag

The above line, with definition in values, does not pass lint strict because if complains that that the key ".Values.defaults.image_tag" is not defined.

1. It is defined as nil
2. There is a check in the first and term to make sure it is defined before it is referenced

Output of `helm version`:

2.14.3

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by mattfarina** [comment] 2020-06-23 17:40
This is now fixed in Helm v3 but not v2. Does someone want to fix it in Helm v2?

**Comment by bacongobbler** [comment] 2020-07-09 17:34
Gentle reminder that the support window for bugfixes closes in a month. If nobody works on this, we'll have to close this out and consider this as Helm 2's intended behaviour.

**Comment by hickeyma** [comment] 2020-08-11 19:27
#8516 now merged, closing.

**Closed by hickeyma** 2020-08-11 19:27 UTC
Labels: bug, v2.x
