### ISSUE TITLE
helm install --dependency-update doesn't deploy downloaded charts (again)

### ISSUE THREAD

**Issue by walker-tom** [helm/helm#7886] opened 2020-04-07 12:36 UTC
I'm having the same issue as was described in https://github.com/helm/helm/issues/3423. Trying to install a chart using `helm install --dependency-update` with only a `requirements.yaml` file downloads the dependency charts into `charts/` and creates a `requirements.lock` but the install doesn't use these new charts.

Looking at the PR created to resolve the old issue, the fix added to `cmd/helm/install.go` is not present anymore.

Output of `helm version`:
```version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment] 2020-04-07 13:42
Duplicate of https://github.com/helm/helm/issues/7857.

**Closed by bacongobbler** 2020-04-07 13:42 UTC
