### ISSUE TITLE
Unable to --set value which contains &placeholder in values.yaml file

### ISSUE THREAD

**Issue by JaroVojtek** [helm/helm#5589] opened 2019-04-11 13:22 UTC
Hello, I have problem to --set values via helm:
```
helm install my-helm-chart  \
--set apiServerIP=10.2.85.224 \
--set dnsName=server452.customer.com \
--set dockerRegistryIP=10.2.85.224 \
--set grafanaPostgresHost=10.2.85.224
```

particular variables contains &placeholders in value.yaml file, as because they are referenced in multiple places later in values.yaml file:

```
apiServerIP: &apiServerIP 127.0.0.1
dnsName: &dnsName server1.dns.another.com
dockerRegistryIP: &dockerRegistryIP 127.0.01
dockerRegistryPort: &dockerRegistryPort 5000
prometheusVolumeSize: &volumeSize 1Gi
prometheusVolumePath: /opt/kubernetes/data/volumes/prometheus
```

And for example last parameter `prometheusVolumePath` am able to set via `--set prometheusVolumePath=/tmp`

Output of `helm version`:
helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On-premise environment

**Comment by bacongobbler** [comment] 2019-04-11 15:07
this seems like a duplicate of https://github.com/helm/helm/issues/2336. Can you please check?

**Comment by bacongobbler** [comment] 2019-12-09 20:22
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2019-12-09 20:22 UTC
Labels: question/support

**Comment by miraculixx** [comment] 2021-07-01 15:45
I have found a workaround to this problem using a little Python helper program. YMMV

https://gist.github.com/miraculixx/bbba80793895f081204a05fbd5573eda
