### ISSUE TITLE
Best Practices/Docs Question - Specify Namespace in Chart?

### ISSUE THREAD

**Issue by pcfens** [helm/helm#5465] opened 2019-03-18 04:13 UTC
I've found that some charts have a line like `namespace: {{ .Release.Namespace }}` in the metadata of each object, but others (including those in [helm/charts](https://github.com/helm/charts)) don't. Without the namespace specified in the template the command `helm template --namespace not-default --values config.yaml chart/ | kubectl create -f -` installs the chart in the default namespace. For comparison, charts for [GitLab](https://gitlab.com/charts/gitlab) and [Istio](https://github.com/istio/istio/tree/master/install/kubernetes/helm/istio) both specify the namespace on each object.

For rudimentary GitOps workflows without support for Helm integrations, we render the chart, then store the rendered copy in the repository to be applied.

The [best practices docs](https://helm.sh/docs/chart_best_practices/) don't address whether or not namespace should be specified in each object. Should it be discussed there?

**Comment by bacongobbler** [comment] 2019-03-18 14:50
Thank you for pointing that out! Yes, we should address that question in the best practices documentation. In general, templates should not define a namespace. This is because Helm installs objects into the namespace provided with the `--namespace` flag.

The same applies to `kuectl create -f`: by providing a `--namespace`, those resources will be installed there. For example:

```
><> kubectl create namespace ingress-system
namespace/ingress-system created
><> helm template nginx-ingress-1.3.1.tgz | kubectl create --namespace ingress-system -f -
configmap/release-name-nginx-ingress-controller created
serviceaccount/release-name-nginx-ingress created
role.rbac.authorization.k8s.io/release-name-nginx-ingress created
rolebinding.rbac.authorization.k8s.io/release-name-nginx-ingress created
service/release-name-nginx-ingress-controller created
service/release-name-nginx-ingress-default-backend created
deployment.extensions/release-name-nginx-ingress-controller created
deployment.extensions/release-name-nginx-ingress-default-backend created
clusterrole.rbac.authorization.k8s.io/release-name-nginx-ingress created
clusterrolebinding.rbac.authorization.k8s.io/release-name-nginx-ingress created
```

Hope this helps.

**Comment by pcfens** [comment] 2019-03-18 15:28
That makes sense, especially in cases where helm is also applying the rendered manifests.

If that's the recommendation, a note should probably be added to the [template subcommand docs](https://helm.sh/docs/helm/#helm-template) too. Charts that manage RBAC resources (specifically RoleBinding objects) are often rendered in a way that would require helm and kubectl to have the same namespace specified to work as expected.

**Comment by surajssd** [comment] 2019-07-26 06:23
> In general, templates should not define a namespace. This is because Helm installs objects into the namespace provided with the --namespace flag. By omitting this information, it also provides templates with some flexibility for post-render operations (like helm template | kubectl create -f -)

Here are you saying that template should not hardcode a namespace value or it should not use `namespace: {{ .Release.Namespace }}` value?

> The same applies to kubectl create -f: by omitting the namespace field and instead relying on the --namespace flag, those resources will be installed there on-the-fly. For example:

We cannot compare barebones kubernetes omitting namespace value and helm omitting namespace value they are slightly different.

- When you want to define namespace value in kubernetes configs they are hardcoded, they cannot be parameterized, which is not the case with helm templates. We can choose to hardcode it or parameterize it using `namespace: {{ .Release.Namespace }}`.

- Also functionality wise there is little different there. If you have namespace `x` hardcoded in your template and while deploying you provide `y` to the flag `--namespace` then kubectl errors out. But in case of helm when you hardcode `x` namespace value in template and while deploying use some other value for `--namespace` flag, helm doesn't complain.

- Using the helm rendering libraries:

If a template does not define a namespace field, parameterized or not, setting the release object's Namespace field has no effect. The tool deploying the rendered manifests has to take care of that.

- Following two commands may look similar functionality wise they won't work the same for all charts:

```
helm template nginx-ingress-1.3.1.tgz | kubectl create --namespace ingress-system -f -
```

```
helm template --namespace ingress-system nginx-ingress-1.3.1.tgz | kubectl create -f -
```

---

IMHO helm should reduce this confusion and drive a way to do things in only one way. And not mix the declarative and imperative paradigms here. Let helm be declarative only. Namespace being an integral part of kubernetes eco-system by allowing such flexibility to it, this has just induced confusion and frustration among users.

**Comment by HighwayofLife** [comment] 2019-10-12 07:54
> In general, templates should not define a namespace. This is because Helm installs objects into the namespace provided with the --namespace flag. By omitting this information, it also provides templates with some flexibility for post-render operations (like helm template | kubectl create -f -)

This is a really confusing statement, I can't figure out what the `--namespace` flag is fore on the `template` command. It doesn't add the namespace to metadata of resources, which is what I would expect based on the option as well as the documentation, and _require_ this for GitOps and manifest generation automation. It would make better sense for the `--namespace` flag to set the metadata if defined, but omit that field if not defined, that way both paradigms are supported. However currently, a GitOps workflow is not supported properly because of this missing behavior.

**Comment by bacongobbler** [comment] 2019-10-12 15:35
@HighwayofLife see https://github.com/helm/helm/issues/3553#issuecomment-521424132 for a more in-depth explanation of what happens under the hood during a `helm template` and how the `--namespace` flag applies.

The tl;dr is that the `--namespace` flag modifies the behaviour of [the kubernetes client APIs](https://github.com/helm/helm/blob/34b930cb9db8dba90aaba6299200c34664219a57/pkg/kube/client.go#L119) within Helm. It doesn't directly affect the templates themselves. We could remove it, but then users would complain that `helm template` flags don't relate 1:1 to `helm install`.

**Comment by dmyerscough** [comment] 2019-10-12 20:19
I have recently been deploying Helm charts via Spinnaker. However, charts that haven't had the `Release.Namespace` specified always get dumped in the default namespace where Spinnaker is running.

Spinnaker has a hard requirement for Helm charts to include the following [1]:-

```yaml
metadata:
  namespace: {{ .Release.Namespace }}
```


[1] https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/

**Comment by mindw** [comment] 2019-10-29 12:04
Expanding on @surajssd excellent comment, it seems very odd that the only way to capture in git how a chart was deployed/updated (`helm update --wait --namespace kube-system`) is to capture the imperative steps via a script.
a deficiency https://github.com/roboll/helmfile is attempting to address.

**Comment by HighwayofLife** [comment] 2019-10-31 07:31
@bacongobbler I've read that comment, and the design decision for that is very puzzling. It's putting the responsibility on the developer/ops, or an external tool (say a CI/CD) to do something that helm _could_ do out of the box. Which is to declare a state, declare a configuration as code. 

Requiring CLI flags to produce a certain result or state in a cluster breaks the concept of declarative state. What should be the case of "least surprise" in helm should be to declare all values including metadata within the helm chart and values, but helm splits some of that data out into flags and that is what causes not only significant confusion, but requires pretty much every CI process, every ops team, and every declarative/config-as-code tool to build a scaffold on top of helm to do the job that helm could very well do itself. It's not slower to render this because it's simply injecting a value the same as the rest of the template values. Processing yaml is still something that we have to do after the fact because of this missing functionality. So we're not saving anything by having this feature missing.

I hope that this has changed in Helm3?

**Comment by mitar** [comment] 2020-01-10 18:15
> But in case of helm when you hardcode x namespace value in template and while deploying use some other value for --namespace flag, helm doesn't complain.

I think this is the most confusing aspect here. If I provide `--namespace` I would want the chart to be deployed there and just there and nothing else. If chart has a different hard-coded namespace, things should fail. In this way I can know that when I am deploying charts for users, to which namespace I have deployed and setup permissions over namespace correctly. If chart creates some other namespaces, this becomes trickier.

So could this issue also be to make helm stricter if there is a conflict between command line and template? I think then best practice is also easier to define: if you want to use/support `--namespace`, then you use a placeholder in a template, if you want everything to be in a template, gitops style, then you hard-code namespace in a template, and then Helm complains if things do not match, if you do end up using `--namespace` still.

**Comment by bacongobbler** [comment] 2020-01-10 18:28
We tried that for Helm 3 and had to revert it. Users relied on this behaviour to deploy resources across multiple namespaces. like `foo` and `foo-system` when `--namespace foo` was supplied. Suggestions welcome.

See #6046 and #5953.

**Comment by mitar** [comment] 2020-01-10 18:34
OK, then let's add another command line argument like `--restrict-namespace`? So the behavior would be:

* `--restrict-namespace`: if provided, objects can be created only in this namespace, it does not influence template rendering, can be provided multiple times to allow multiple namespaces per call
* `--namespace`: provides a namespace value for any template which has a namespace placeholder, and a default namespace to deploy to, if none is specified

What do you think?

**Comment by rbtcollins** [comment] 2020-04-22 10:33
I think the underlying problem is definitional: helm provides a string interpolation language, and it is tempting to think that therefore the problem is that simple. But the domain it is working is a structured domain, and namespaces are an intrinsic property of some API objects. 

This means that templated output is not portable in the general case, and users expecting it to be portable are using workflows that will break if they try to generalise them.

Consider (from chaos-mesh) 

```kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}:chaos-controller-manager
  labels:
...    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controllerManager.serviceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}:chaos-controller-manager
  apiGroup: rbac.authorization.k8s.io
{{- if (not .Values.clusterScoped) }}
```

Anyhow, I think the users that are expecting namespace-free templates to then use with kubectl --namespace will be horridly surprise when a ClusterRoleBinding or other similar template comes past, because things just won't work. But I also understand that shifting norms takes a while.

So, can I suggest a multi-pronged approach:
 - a CLI option to allow those of us that need completely defined output generated to get it
   - this would:
      - automatically insert release.namespace into metadata for namespaced objects where helm knows that the object is namespaced
      - define a {{- PICKSOMENAME }} variable which would evaluate to the rendering of "{{ Namespace: Release.Namespace }}" - the idea being that it could be used to add a namespace conditionally, only if this CLI option was supplied, for custom API types where helm doesn't know the namespacing rules for whatever reason (if that is a problem, if it isn't ignore this whole bit)
 - in helm 4 make this CLI option the default

**Comment by jhughes2112** [comment] 2020-06-25 06:27
I'd like to give you a specific use-case that I'm currently struggling against, and Helm 3 does not appear to support in any way that I can find:

I have everything as basic .yaml manifests that fully regenerates my cluster config.  I like it that way.  I find the Helm charts handy, but what I really want is to generate the manifests and be done with Helm, as a means of securing the current state of my cluster in a fully declarative sense.  I check my manifests into git and I can thus check to see what things have changed when I want to upgrade versions of packages.  Call it a low trust factor, if you like.

Whether I use `helm template` or `helm upgrade --install --dry-run` or actually install first and pull `helm get manifest`, I always have to know what namespace the thing is in when applying it back to the cluster, because Helm never writes that into any of the objects' yaml.  It's really unfortunate.  So I either have to manually go in and insert namespace declarations, or write a memo on every file what ns to use.  In other words, Helm isn't helping me make a fully declarative production-ready system.

You have three different sets of users.  One that wants help making their job easier generating manifests, and another that wants control over where things get placed, and another that wants the rendered yaml in a fully install-ready form.  I'm guessing the latter is a smaller group of people (like me) but we're very left out here.  Seems like Helm should **think less** (remove the --namespace option entirely and rely on templating) or **think more** (actually substitute namespace declarations in objects that came from them).  But right now it's stuck in between.

**Comment by bacongobbler** [comment] 2020-09-14 15:29
From Helm's perspective, the use cases described here doesn't make sense for a couple reasons. Mostly that the work required to do this would increase performance overhead (make Helm slower) with no real gain to the program.

Templates from helm template can already be installed in a particular namespace (as shown above with `helm template | kubectl apply --namespace foo`).

In addition, injecting metadata into user's objects is a computationally expensive ordeal. There would be a not-insignificant cost factor to render the templates, serialize them into versioned API objects, inject the namespace metadata, then re-serialize them to fire off the API request to Kubernetes. All of which Helm already accomplishes in an optimized manner without the performance overhead.

To answer a few of the questions and concerns raised earlier in this thread:

> I have recently been deploying Helm charts via Spinnaker. However, charts that haven't had the Release.Namespace specified always get dumped in the default namespace where Spinnaker is running.

@dmyerscough see https://spinnaker.io/guides/user/kubernetes-v2/deploy-helm/#configure-the-bake-manifest-stage. There is a "Release namespace" parameter you can set as part of the Bake Configuration for spinnaker.

> OK, then let's add another command line argument like `--restrict-namespace`?

That might make sense, but is not relevant to the discussion at-hand. Please feel free to open a new ticket and a pull request for this feature request.

> Anyhow, I think the users that are expecting namespace-free templates to then use with kubectl --namespace will be horridly surprise when a ClusterRoleBinding or other similar template comes past, because things just won't work.

I'm not sure what you mean by that argument. Even with `kubectl apply --namespace foo`, ClusterRoleBindings are deployed at the cluster level. What do you mean by "things just won't work"? Can you please provide an example?

> Whether I use helm template or helm upgrade --install --dry-run or actually install first and pull helm get manifest, I always have to know what namespace the thing is in when applying it back to the cluster, because Helm never writes that into any of the objects' yaml.

I'm assuming you're describing a workflow commonly used by "gitops". Gitops tools like flux allow you to set a namespace parameter when you set up the project, and will use that namespace to deploy your resources. See the [flux-get-started](https://github.com/fluxcd/flux-get-started/blob/a4bdf4bb92c35cf9e944788368510168ee0bedf4/releases/ghost.yaml#L6) example to see how you can inform the `ghost` chart (one that does not specify a namespace anywhere in their templates) to be deployed to the `demo` namespace.

I will also re-iterate that it is the Kubernetes client which is being modified by flags like `--namespace`; not the templates. Helm is rendering your templates as-is and sending them off to whichever client needs them.

After deliberating over the use cases described earlier, I am certain they can be solved in different manners than the proposal described earlier; either by the tooling they're using (flux and spinnaker allow you to specify the namespace), by injecting the metadata yourself through the templates, or by [using the post-renderer](https://helm.sh/docs/topics/advanced/#post-rendering) introduced in Helm 3.1.

If there are alternative use cases than the ones described earlier, please provide them so we can have a discussion about your use case and how we could solve it. But for now I am closing this as the system is working as the Kubernetes API intends. Thank you all for your input.

**Closed by bacongobbler** 2020-09-14 15:29 UTC
Labels: docs, question/support

**Comment by mitar** [comment] 2020-09-15 02:13
I just opened https://github.com/helm/helm/issues/8732 to track the `--restrict-namespace` command line argument. Please provide feedback there for that suggestion.

**Comment by VGerris** [comment] 2020-10-29 16:05
Apologies for responding to a closed issue, but I was not sure where to post otherwise.
I currently use helm 3 and see this kind of stupidity:

Charts# ../../linux-amd64/helm install --namespace myappns -f values.yaml myapp . 
Error: the namespace from the provided object "myapp" does not match the namespace "default". You must pass '--namespace=qbrickqna' to perform this operation.

If I use: namespace: {{ .Release.Namespace }} in Chart.yaml it always installs in default.
If I created variable namespace in values I get the above.
I read to this whole thread and don't understand how it's in any way not logical to have this install in the provided namespace, just like kubectl does?

I don't care if I need to supply it or set a variable, but I would like it to WORK :).
Is there anything I am missing?
Where do I need to set the namespace to my custom one to make this work?
The documentation sucks on that subject too.

It would be great if anyone can point to the proper way of doing what I would like to do, should I make a new issue?

**Comment by jeantil** [comment] 2020-11-06 15:17
After reading everything, I'm pretty sure that hardcoding a namespace in a chart even if it is parameterized through a value is not considered best practice.

```
# In templates/*.yaml 
metadata: 
    namespace: "mynamespace"
```
or 
```
# In templates/*.yaml 
metadata: 
    namespace: {{ .Values.namespace }}
# In values.yaml
namespace: "mynamespace" 
```
are both incorrect :
- the first one because it doesn't allow overriding the namespace, 
- the second one because it potentially requires chart users provide the same namespace information multiple times  (once for helm's `--namespace` flag and once through a value override such as `--set namespace="other"`)

But I'm still confused over what the actual **best practice** is :

1. use explicit namepace metadata referencing `.Release.Namespace` for all resources that should be namespaced  
```
# In templates/*.yaml 
metadata: 
    namespace: {{ .Release.Namespace }}
```
or 

2. never defining the namespace metadata anywhere
```
# In templates/*.yaml
metadata: 
```

I did recheck the docs and tried to look for a docs update PR/Issue spelling it out but couldn't find anything. 
Analysing some PRs which reference this issue seems to point out that option 1 is the best practice but @bacongobbler's comments seem to contradict this and prefer option 2. ( I could definitely be the one who misunderstood as all this is quite new to me)

**Comment by bacongobbler** [comment] 2020-11-06 15:23
Option 2 is the best practice. You do not need to define namespace metadata in your templates. I [demonstrated in an earlier comment](https://github.com/helm/helm/issues/5465#issuecomment-473942223), but it wasn't explicitly clear that was the case. So thank you for bringing that up.

**Comment by jeantil** [comment] 2020-11-06 15:27
Thanks for the clarification: many (if not most) of the PRs referencing this issue have implemented option 1 instead  which left me confused.

**Comment by jeantil** [comment] 2020-11-06 16:48
>> Anyhow, I think the users that are expecting namespace-free templates to then use with kubectl --namespace will be horridly >> surprise when a ClusterRoleBinding or other similar template comes past, because things just won't work.

> I'm not sure what you mean by that argument. Even with kubectl apply --namespace foo, cluster-level resources are deployed at the cluster level. What do you mean by "things just won't work"? Can you please provide an example?

My previous questions were a prelude to my attempt at removing a `value`-based namespace configuration to instead use the implied `.Release.Namespace` in the apache pulsar helm chart.

That chart describes the complex deployment of pulsar and creates 3  `ClusterRoleBindings` such as in this file :
https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/broker-cluster-role-binding.yaml#L35

I naively tried to remove the `namespace` attribute which results in an error on `helm install` : 
> Error: ClusterRoleBinding.rbac.authorization.k8s.io "pulsar-functions-worker" is invalid: subjects[0].namespace: Required value

Which means that to make the chart work at all, I **must** provide a namespace here. If I use `{{ .Release.Namespace }}`  that works fine with `helm install` but will fail with  `helm template | kubectl create --namespace foo -f -` since the `.Release.Namespace` will either be incorrect (`default`) or undefined,

Other places which are likely to break in such a manner are FQDN definitions where I replaced the initial `.Values.namespace` with `.Release.Namespace`  such as : 
```
{{/*
Define the bookkeeper hostname
*/}}
{{- define "pulsar.bookkeeper.hostname" -}}
${HOSTNAME}.{{ template "pulsar.bookkeeper.service" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
{{- end -}}
```
found in https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/_bookkeeper.tpl#L12 

I'm not entirely sure that dropping the FQDN for  a partial DN will work properly ( the hostnames are used all over the place including to define tls certificates )

**Comment by HighwayofLife** [comment] 2020-11-08 06:14
Jean, you've nailed exactly why some kind of namespace support is needed. I
found that helm template misses some items and they land in default
namespace, so I have to use a combination of helm template with a set
namespace, and Kustomize with a namespace set.

This is a shortcoming in helm that requires us to do this.

**Comment by Imunhatep** [comment] 2020-11-12 12:09
Personally, I'm not sure this is possible at all.  

As `Namespace` resource is the subject of many other use-cases far beyond application chart, like kubernetes operators, rbac, resources, networking, ingress, certificates, csi, e.t.c.  

All this can be lost/corrupted in case chart is managing (especially on delete) namespaces.  e.g. pretty known situation with a stuck `Namespace` in status `Terminating`.. cause of `finalizers`, added e.g. by 3rd party CSI operator for PVCs requested by charts application STS...

In such environment, I wonder if Namespace is really belong to the application?!

P.S. @jeantil 
While there is `kustomize` for `kubectl`, even so `helm template chart_name -n namespace ... | kubectl apply -f` will do the trick, though I find this example out of scope since Helm v3.

**Comment by dnozay** [comment] 2021-07-07 23:04
w.r.t. the discussion,
```
# In templates/*.yaml 
metadata: 
    namespace: {{ .Release.Namespace }}
```
vs
```
# In templates/*.yaml
metadata: 
```

@bacongobbler  mentioned:
> Option 2 is the best practice. You do not need to define namespace metadata in your templates. I demonstrated in an earlier comment why you don't need to define namespace metadata, but it wasn't explicitly clear that was the case. So thank you for bringing that up.


but to add some color, you could have RBAC resources which aren't necessarily going to be in `{{ .Release.Namespace }}`
then it makes sense to me that the namespaces involved are explicit

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: rolebindingname
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: rolename
subjects:
  - kind: ServiceAccount
    name: serviceaccountname
    namespace: {{ .Values.other.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.other.namespace2 }}
  name: rolebindingname2
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: rolename2
subjects:
  - kind: ServiceAccount
    name: serviceaccountname2
    namespace: {{ .Release.Namespace }}
```

**Comment by bacongobbler** [comment] 2021-07-07 23:10
Global (non-namespaced resources) are a bit of a troublesome case as they are not bound to a particular namespace and have the potential to modify and/or affect other charts. We don't really have a great answer here, and is why [HIP 11](https://github.com/helm/community/blob/main/hips/hip-0011.md) is such a hot topic these days.

**Comment by b-jsshapiro** [comment] 2021-07-12 04:24
There are deployment use cases where one would like to make specification of a namespace _mandatory_. For example, if one fails to specify one of 'dev' or 'production', the install should fail.

Similarly, there are use cases where some choice of tags should be mandatory.

This leads me to two questions:

1. Given that --namespace foo has been provided, how does a template reference the namespace name?
2. How does a chart specify sanity conditions like "namespace must be one of x or y" or "one of tags A or B must be set" as a condition of execution?

**Comment by jhughes2112** [comment] 2021-07-12 14:59
I would suggest that tools are meant to succeed.  It is a slippery slope (think xml and the mess that came after with validation templates) to begin down the path of creating failure cases because one engineer thinks something is invalid and another does not (or does not know).  If that becomes Helm's responsibility, you're taking on a huge problem that boils down to communication, not veracity.  I don't think you want that.

**Comment by b-jsshapiro** [comment] 2021-07-12 15:12
I think this has already come up, but it relates to a discussion I’m trying to have on the helm slack group, so it’s appearing in more than one place: there often isn’t a single namespace.

The use case in our situation is a service with multiple components built around a common core and some shared infrastructure. Each component involves multiple pods. We probably want to put each component in its own namespace and the common core in a separate one. They all (unfortunately) need access to a common data set,

My point is that there is a conceptual difference between installing an application or a component (which helm doesn’t do in any case) and installing a subsystem.

I say “which helm doesn’t do” because it makes no sense in helm to talk about installing version X of component Y. Because install time parameters can readily change, two dependencies on version X of Y do not necessarily reference the same artifact.  Helm is a very useful tool, but this distinction between installing applications and installing application instances feels like something that is still evolving. Partly, it reflects the fact that the micro service school of construction has a different pattern than some others, and both are legitimate and appropriate. We dealt with this a lot in KeyKOS (a persistent capability system), but kubernetes hasn’t (yet?) developed the needed patterns for instantiation.

**Comment by QuingKhaos** [comment] 2021-11-02 15:22
I still would prefer 

```metadata:
  namespace: {{ .Release.Namespace }}
```

as a recommendation. Using `helm template` with agent pull based approach and the namespace must be rendered into the manifests. There is no `kubectl apply --namespace` available in this GitOps approach.

**Comment by zappallot** [comment] 2022-01-28 15:43
I landed here while trying to 
`helm template` the current (1.4.0) [Airflow chart](https://github.com/apache/airflow/tree/main/chart).
The chart uses `namespace: {{ .Release.Namespace }}`, but only in _none metadata_ sections of the chart.

So you would have to `helm template --namespace foo | kubectl apply -n foo` to make it work, which is very confusing.
Especially when your other helm chart used `namespace: {{ .Release.Namespace }}` in the _metadata_ section and everything worked like expected.

Since we don't apply the templated .yml file directly, but check it into git to apply it later through a pipeline, I'll have to find a way to patch the namespace into this, because all other manifests so far have a namespace specified in their manifest.yml.

I'd clearly prefer 
```
`namespace: {{ .Release.Namespace }}`
```
That would have saved me hours...

**Comment by andreu7d** [comment] 2023-01-04 16:15
@zappallot THIS! What this guys said!

**Comment by willzhang** [comment] 2023-01-18 08:39
in one word, if you set this in bitnami nginx values.yaml
```
## @param namespaceOverride String to fully override common.names.namespace
##
namespaceOverride: "nginx1"
```
the follow `--namespace ` and `--create-namespace` options will ignored by helm
```
helm install nginx charts/nginx --namespace nginx --create-namespace
```
and the nginx app will install to nginx1 namespace.
