### ISSUE TITLE
Helm registries walkthrough contains deprecated commands

### ISSUE THREAD

**Issue by joelbrandenburg** [helm/helm#10145] opened 2021-09-16 19:07 UTC
I am trying to push my Helm charts to Amazon ECR and the steps outlined in https://helm.sh/docs/topics/registries/ contains deprecated commands as the "chart save" and "chart push" commands no longer work.  Also using "helm push" doesn't appear to support pushing to Amazon ECR.

Output of `helm version`: 3.7.0

Output of `kubectl version`: 19

Cloud Provider/Platform (AKS, GKE, Minikube etc.): ECR/EKS

**Comment by bacongobbler** [comment] 2021-09-16 19:13
Duplicate of https://github.com/helm/helm-www/issues/1196.

**Closed by bacongobbler** 2021-09-16 19:13 UTC
