### ISSUE TITLE
How to modify value of appVersion by helm upgrade

### ISSUE THREAD

**Issue by hillbun** [helm/helm#9809] opened 2021-06-16 03:09 UTC
Output of `helm version`:

v3.5.4

How to modify value of appVersion defined in Chart.yaml by helm upgrade  without modify file of  Chart.yaml?

**Comment by bacongobbler** [comment] 2021-06-16 14:07
duplicate of https://github.com/helm/helm/issues/8194.

**Closed by bacongobbler** 2021-06-16 14:07 UTC
Labels: question/support
