### ISSUE TITLE
Helm hangs when try to deploy, list, or get anything

### ISSUE THREAD

**Issue by jeffmartinxyz** [helm/helm#5505] opened 2019-03-25 20:48 UTC
Output of `helm version`:
2.11.0
Output of `kubectl version`:
1.13 
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Helm hangs indefinitely when running any `deploy`, `list`, or `get` command. Restarting the Tiller Pod resolves the issue temporarily. There is no logging or error message thrown.

**Comment by bacongobbler** [comment] 2019-03-26 17:40
What happens if you run the following?

```
kubectl -n kube-system port-forward svc/tiller-deploy 44134:44134
```

And in another terminal:

```
export HELM_HOST=:44134
helm list
```

**Comment by gcarrarom** [comment] 2019-03-27 16:16
HI, I am just experiencing this issue in a new cluster. Here's the version information and the tests you asked:
### kubectl version
`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`
### helm version
`Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}`
### port-forward test
`Forwarding from 127.0.0.1:44134 -> 44134
Forwarding from [::1]:44134 -> 44134
Handling connection for 44134`
And running the command hangs for 5 minutes before there's an error:
`export HELM_HOST=:44134
helm list
Error: Get https://***.hcp.eastus.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: unexpected EOF`

**Comment by tjk** [comment] 2019-04-28 16:58
I too am experiencing issues with helm hanging on many commands... (mostly followed this setup https://cloud.google.com/community/tutorials/nginx-ingress-gke without rbac).

In one terminal set up port forward:

```
% kubectl -n kube-system port-forward svc/tiller-deploy 44134:44134
Forwarding from [::1]:44134 -> 44134
```

```
% export HELM_HOST=:44134

% kubectl version --short
Client Version: v1.13.4
Server Version: v1.11.8-gke.6

% helm version --short --debug
Client: v2.13.1+g618447c
[debug] Created tunnel using local port: '61498'

[debug] SERVER: "127.0.0.1:61498"

Kubernetes: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
*** HANGS ***

% helm list --debug                                                                                                                                        ✘ 130
[debug] SERVER: ":44134"
*** HANGS ***
```

**Comment by Mogsrees** [comment] 2019-05-08 10:27
Did anyone manage to find a root cause / fix for this? 

Currently experiencing the same issue, tested on both AKS version 1.11.9 and 1.12.6, UK South region. 

`Error: Get https://***.hcp.uksouth.azmk8s.io:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: unexpected EOF`

**Comment by ASfSDlS61TLT6eoP3Qb7** [comment] 2019-05-14 05:08
I am having the same issue. Even I have reinstalled tiller and helm (including deleting the $HELM folder). 

The strange thing is that when I work with the tiller plugin, everything works fine. Now Helm keeps hanging with every command.

`[debug] SERVER: "127.0.0.1:44134"


`

**Comment by jeremych1000** [comment] 2019-05-21 15:37
Are you using any kind of outbound firewall? We had the same problem - turns out TCP port 443 had to be allowed outbound (not HTTPS as helm uses gRPC).

**Comment by shaneramey** [comment] 2019-06-05 17:01
I was getting this error until I signed the Tiller server cert with the IP SAN 127.0.0.1.

**Comment by bacongobbler** [comment] 2019-06-05 17:09
I'm closing this issue as the original submitter has not provided any follow-up information to assist them in this matter. An issue like "Helm hangs indefinitely" can be a number of things, and as we've seen in the comments it's ranged from incorrect TLS setup, improper RBAC permissions or outbound network conditions. ;)

If others are having issues, please open a new ticket so we can track that discussion separately. Thanks.

**Closed by bacongobbler** 2019-06-05 17:09 UTC
Labels: question/support

**Comment by itaimalek** [comment] 2020-03-02 19:09
Hi,
@bacongobbler I'm experiencing the exact same issue, any help is appriciated

**Comment by bacongobbler** [comment] 2020-03-02 19:13
Sorry to hear that. Can you please open a new ticket describing the issue you're experiencing as well as a way to help reproduce the issue so we can test on our end? Thanks!
