### ISSUE TITLE
Creating namespaces with custom labels

### ISSUE THREAD

**Issue by bgehman** [helm/helm#4178] opened 2018-06-05 18:43 UTC
Is it possible to create a namespace, and add our own custom labels to that namespace?  We are in the process of migrating our JINJA based templates over to Helm and having issues...

YAML:
```
apiVersion: v1
kind: Namespace
metadata:
   name: {{ .Release.Namespace }}
   labels:
       app_name: core
```

Errors running `helm install`:
```
$ helm install --namespace core --name core core 
Error: release core failed: namespaces "core" already exists
```

Output of `helm version`:
```
$ helm version --short=true
Client: v2.9.1+g20adb27
Server: v2.9.1+g20adb27
```

Output of `kubectl version`:
```
$ kubectl version --short=true
Client Version: v1.9.6
Server Version: v1.9.6
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
docker-edge

**Comment by munnerz** [comment] 2018-06-16 17:05
Possible dupe of #3503?

**Comment by dstockton** [comment] 2018-09-26 10:40
👍

**Comment by bacongobbler** [comment] 2019-10-30 19:10
dupe of #3503.

**Closed by bacongobbler** 2019-10-30 19:10 UTC
Labels: question/support
