### ISSUE TITLE
[feature] helm install --wait does not wait for storageclass

### ISSUE THREAD

**Issue by staticdev** [helm/helm#5958] opened 2019-06-30 14:54 UTC
Output of `helm version`: 2.14.1

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kubeadm

To reproduce just try the script:
```sh
helm repo add storageos https://charts.storageos.com
helm install storageos/storageos-operator --namespace storageos-operator --wait
kubectl patch storageclass fast -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

It installs a apiVersion: apps/v1 Deployment.
https://github.com/storageos/charts/blob/master/stable/storageos-operator/templates/operator.yaml

According to the documentation, the --wait has a limited scope:

>     Waits until all Pods are in a ready state, PVCs are bound, Deployments have minimum (Desired minus maxUnavailable) Pods in ready state and Services have an IP address (and Ingress if a LoadBalancer) before marking the release as successful

**Comment by bacongobbler** [comment] 2019-07-02 19:49
I'm missing the context here. Is this an ask for the `--wait` flag to wait for storage classes to become available?

@thomastaylor312 what do you think about this?

**Comment by staticdev** [comment] 2019-07-02 20:16
@bacongobbler Exactly! I am running into problems for automating helm installations that create storageclasses. Because I set --wait and can't patch the class for example to be default after this scripted installation.

**Comment by thomastaylor312** [comment] 2019-07-02 22:57
@staticdev to clarify, is this needed because your chart _also_ has a PVC that is using the newly created storage class or is it creating the storage class as a pre-req before running other steps/releases down the road?

**Comment by staticdev** [comment] 2019-07-02 23:28
@thomastaylor312 second option: it creates a storage class that is needed for next steps.

**Comment by thomastaylor312** [comment] 2019-07-03 15:24
Hmmm...that is interesting. I'll take a look at possibly adding it. To be honest, I might add it just to Helm 3 because the logic has been completely cleaned up there and is still a bit of a mess in Helm 2

**Comment by staticdev** [comment] 2019-07-03 20:43
@thomastaylor312 I see no problem at all. I am pretty enthusiastic about Helm 3 and looking forward for stable version ASAP =)

**Comment by waveywaves** [comment] 2019-08-12 16:50
@staticdev I ran the commands for reproducing this.
```
helm repo add storageos https://charts.storageos.com
helm install storageos/storageos-operator --namespace storageos-operator --wait
```
I got the below error
```
helm install storageos-operator storageos/storageos-operator --namespace storageos-operator --wait
manifest_sorter.go:181: info: skipping unknown hook: "crd-install"
manifest_sorter.go:181: info: skipping unknown hook: "crd-install"
Error: apiVersion "storageos.com/v1" in storageos-operator/templates/storageoscluster_cr.yaml is not available
```
I am trying to work with `Kind`s on this one to get the storage class APIs. As only k8s.io/api/storage/v1beta1 is vendored in and I don't want to increase the vendoring unnecessarily, so I am trying to write in such a way that we can support storage classes dynamically from certain APIs such as this one. What do you guys this would be a better way to implement this ? 

cc @bacongobbler @thomastaylor312

**Comment by thomastaylor312** [comment] 2019-08-15 20:14
@staticdev After looking at this more (in conjunction with @waveywaves' PR), I don't think this would be something we could bring into Helm directly. There are two main reasons for this:

1. There is nothing in the `StorageClass` spec or documentation that indicates anything to wait for on a storage class.
2. Based on the example chart you gave, it looks like the desired functionality is to watch if the provisioners themselves are ready because there are no definitions for a storage class in chart. Waiting for a provisioner to be ready is something more in the scope of a pre or post install hook.

Because of this, I am going to close the issue. If I got something wrong, please let me know and feel free to re-open

**Closed by thomastaylor312** 2019-08-15 20:14 UTC
Labels: feature, v3
