### ISSUE TITLE
Error: could not ping Tiller: context deadline exceeded

### ISSUE THREAD

**Issue by vzabawski** [helm/helm#8217] opened 2020-05-28 15:52 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:33:14Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.9", GitCommit:"2e808b7cb054ee242b68e62455323aa783991f03", GitTreeState:"clean", BuildDate:"2020-01-18T23:24:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): Openstack-based private cloud

I was planning to upgrade to Helm3, but when I'm initializing Helm, it fails with `Error: could not ping Tiller: context deadline exceeded`. Tiller pod is running (recreation didn't help) and `nc` shows that network connection is present.
Helm init logs: https://gist.github.com/vzabawski/77f7b52bc05e5a9e4de2d8b7cfa96bb2

How can I make Helm 2 work in order to migrate to Helm 3?

**Comment by bacongobbler** [comment] 2020-05-28 19:06
Hi @vzabawski. I notice there are several issues in the ticket queue referencing that same error message. Have you had a chance to look at those and see if they provided more information to help you diagnose your issue?

**Comment by bacongobbler** [comment] 2020-05-28 19:07
looks like a duplicate of https://github.com/helm/helm/issues/5997.

**Comment by bacongobbler** [comment] 2020-05-28 19:08
Yep. You appear to be using the TLS flags for `helm init`. Closing as a duplicate of #5997. In the future, please make sure to search for open issues before opening one. Thanks.

**Closed by bacongobbler** 2020-05-28 19:08 UTC
Labels: question/support

**Comment by vzabawski** [comment] 2020-05-29 09:05
@bacongobbler I'm sorry, but there's no solution in the issue you've mentioned. I've checked other issues as well as Stackoverflow and some other sources, but couldn't find the working solution or at least some explanation why it happens so. Most of the issues are abandoned. The issue persists on Helm 2.14.1 and 2.16.7 (versions I've checked).
