### ISSUE TITLE
Tag for "latest" points to v2.x instead of v3.1.0

### ISSUE THREAD

**Issue by zehicle** [helm/helm#7606] opened 2020-02-16 22:19 UTC
The install routines rely on the "latest" tag from github redirecting to the latest version.  In this case, it should be v3.1.0 but instead is pointing to v2.x.  This breaks any installers which use the latest link to find the current release version.

Output of `helm version`:
n/a - this is a github tag issue

Output of `kubectl version`:
n/a - this is a github tag issue

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
n/a - this is a github tag issue

**Comment by bacongobbler** [comment] 2020-02-17 01:26
duplicate of #7603, #7598, #7597, #7594, #7592, and #7590. See https://github.com/helm/helm/issues/7597#issuecomment-586424552 for more information.

**Closed by bacongobbler** 2020-02-17 01:26 UTC
