### ISSUE TITLE
Umbrella chart/ sub-chart CRDs not installed

### ISSUE THREAD

**Issue by fmarceau-imagia** [helm/helm#9538] opened 2021-03-25 19:05 UTC
Hello dear Helm community,

Today I've ran into an issue while trying to deploy a chart that has requirements/ sub-charts which have CRDs in them ("/crd" folder). It turns out the CRDs of the sub-chart don't get deployed if you try to upgrade an existing release of the chart which in the past didn't have this dependency.

The only way to get the CRDs created is by deleting the whole release and re-installing the chart from scratch. I also noticed that once everything is installed as expected, if you delete a CRD it won't get recreated on the next "upgrade" of the release.

To reproduce the issue, simply add the following requirements.yaml file to a chart that's already deployed/ already has a release in a cluster (https://github.com/minio/operator/tree/master/helm/minio-operator):
```
dependencies:
- name: minio-operator
  version: 4.0.3
  repository: file://../minio-operator
```

Output of `helm version`:
```
➜ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Output of `kubectl version`:
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): RKE

**Comment by fmarceau-imagia** [comment] 2021-03-25 19:18
Relates to https://github.com/helm/helm/issues/6581 (found it afterward).

**Comment by bacongobbler** [comment] 2021-03-25 19:24
closing as a duplicate of #6581.

**Closed by bacongobbler** 2021-03-25 19:24 UTC
