### ISSUE TITLE
Invalid kubectl context results in helm3 commands failing without output.

### ISSUE THREAD

**Issue by gmaghera** [helm/helm#7130] opened 2019-12-02 22:20 UTC
If the current Kubernetes context is set to something invalid, helm commands silently fail, even `helm version`.

> [root@bf0a9f1ee606 build]# kubectl config current-context
> frodo
> [root@bf0a9f1ee606 build]# kubectl config get-contexts | grep -c frodo
> 0
> [root@bf0a9f1ee606 build]# helm version
> [root@bf0a9f1ee606 build]# echo $?
> 1

I though there was a problem with my helm3 installation, based on the lack of output from `helm version`.  We should be able to query helm for its version regardless of what kubectl context is set to.

**Comment by marckhouzam** [comment] 2019-12-03 01:29
Thanks for the report.
Duplicate of #6863
There is an attempt at a fix in #6915

**Closed** 2019-12-03 06:37 UTC
