### ISSUE TITLE
template recursion bug

### ISSUE THREAD

**Issue by danielchengibm** [helm/helm#7559] opened 2020-02-07 23:31 UTC
Recursion in template functions is not properly detected. The count is never decremented after the template executes which results in a false positive. Link to the PR which fixes this: https://github.com/helm/helm/pull/7558

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```
Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

With a function defined as follows:
```
{{- define "test.nonRecursive" -}}
{{- printf "this is fine" -}}
{{- end -}}
```
And a template file with
```
{{- $ok := include "test.nonRecursive" . -}}
```
repeated several thousand times, the recursion detection kicks in and returns the error
```
Error: template: ibm-dlaas/templates/test.yaml:1002:11: executing "ibm-dlaas/templates/test.yaml" at <include "test.nonRecursive" .>: error calling include: rendering template has a nested reference name: test.nonRecursive: unable to execute template
```
even though there is no recursion involved.

**Comment by bacongobbler** [comment] 2020-02-07 23:39
Duplicate of #7439?

**Closed** 2020-02-11 20:13 UTC
Labels: bug
