### ISSUE TITLE
pre-install annotations sync issues with argocd

### ISSUE THREAD

**Issue by ayushi-inno** [helm/helm#9590] opened 2021-04-12 06:40 UTC
Hey, we are using helm charts behind argo application , and we have some dependencies between the subcharts, for example a schema migration or mongo pod to run before any other applications.
To solve this we used helm pre-install annotations like -
annotations:
    "helm.sh/hook": "pre-install"
This is working fine when we are launching a new application , but when a new sync is detected on an existing application , all of the resources with this annotations are first getting deleted and then again created , because of which sync time is also increasing as well as the apps stop responding because these are base resources.
Can this auto deletion or re-syncing of those resources with pre-install hook annotations  be stopped in some manner?

Output of `helm version`:
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
EKS

**Comment by bacongobbler** [comment] 2021-04-15 15:24
Hi @ayushi-inno. It's unclear whether it's argo deleting the hooks or there's a bug in Helm causing this behaviour. We need more information before we can determine a root cause.

For more information on pre-install hooks, please refer to the documentation: https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle

Hope this helps.

**Comment by scalen** [comment] 2021-07-08 11:19
This is an issue with how ArgoCD uses Helm: ArgoCD uses Helm for templating only, then translates many features (such as Helm Hooks) into their own comparable mechanisms.  There is a [page detailing the mapping](https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks).

The pertinent information here is:
> **'install' vs 'upgrade' vs 'sync'**
> Argo CD cannot know if it is running a first-time "install" or an "upgrade" - every operation is a "sync'. This means that, by default, apps that have pre-install and pre-upgrade will have those hooks run at the same time.

**Comment by bacongobbler** [comment] 2021-07-08 13:47
Thanks for the info.

Closing this issue as answered. Please feel free to comment here and let us know if you have further questions. Thanks!

**Closed by bacongobbler** 2021-07-08 13:47 UTC
Labels: question/support
