### ISSUE TITLE
[Helm3] helm template fails for custom resources

### ISSUE THREAD

**Issue by yhrn** [helm/helm#5977] opened 2019-07-04 20:04 UTC
Output of `helm version`:
`version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"8d1590016c847f1ae8aa4e0c0ff8c7cc37789896", GitTreeState:"clean"}`

Output of `kubectl version`: 
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

`helm template` fails with the following message for my chart only containing a custom resource:
`Error: apiVersion "myorg.com/v1" in mychart/templates/myresource.yaml is not available`

I also get the same error if I try to run `helm install --dry-run` against a cluster where the CRD is already installed.

Using the latest stable Helm version this works.

**Comment by karuppiah7890** [comment] 2019-07-06 04:34
Duplicate of #5766 and #5754

**Closed** 2019-07-06 04:50 UTC
Labels: v3
