### ISSUE TITLE
Updating the value of a computed environment variable did not take

### ISSUE THREAD

**Issue by krishicks** [helm/helm#3701] opened 2018-03-16 18:49 UTC
I had a working chart and template that I accidentally broke; The problem was that an environment variable for a pod contained an incorrect value. "Break" here is taken to mean the pod could no longer start; its configuration, which it takes from environment variables, was broken.

This chart was deployed previously many times, and when this broken version was `helm upgrade`d, it was clear that the environment variable was incorrect. Maybe notable here is that we're using `--wait`, and the deploy failed.

We fixed it and did another `helm upgrade`, but found the fixed environment variable was not present. The old, broken value was still there.

To test a theory, I added a new environment variable to the (fixed) template to see what would happen. The new environment variable was present, *but so was the old, broken one*. I ended up deleting the (fixed) environment variable, purposely breaking it further. I then `helm upgrade`d, put the environment variable back, did another `helm upgrade`, and saw it fixed.

I surmise there's some kind of diffing going on that is broken.

More about this value:

The environment variable is supposed to be a computed value, but this was what was broken, and so it became a static value. The fix was to switch it back to a computed value. Only when the environment variable was completely removed and replaced did it start working again.

**Comment by krishicks** [comment] 2018-03-16 21:26
The above was done with 2.7.2.

I'm also finding similar behavior occurring for values that I want to remove entirely, except I can't figure out how to remove them. The environment variables were added accidentally, but now cannot be removed. New environment variables appear, but old ones don't go away.

**Comment by DanielCorral** [comment] 2018-03-23 22:34
this may be related (helm-users slack conversation from earlier today):
```
ben.podoll [Today at 9:44 AM]
in #helm-users
has anyone else seen this behavior before when running `helm upgrade`?
1. I can run the dry-run and debug option to see the deployment yaml as it should be (with all the secrets refs defined)
2. I can run the actual deploy (also w/ debug on to see them all correctly again)
3. I can see that helm has everything properly by looking at it via helm (`helm get myapp`)
…but when I look at the deployment yaml by asking kubectl (`kubectl get deployment -o yaml myapp`) things get weird…
upon a new deploy, the correct docker image is specified, but the env vars section is stale/old and is never updated.
I can reproduce this over and over, and it’s as though the deployment yaml is partially updated by helm
…any ideas (cause/solution)?


8 replies
ben.podoll [5 hours ago]
cc: @bacongobbler


Dco [4 hours ago]
Im facing this exact same issue actually, which k8s version are you on?


Dco [4 hours ago]
my env: k8s 1.7.3, helm 2.8.2


ben.podoll [4 hours ago]
my env: k8s 1.6.4 and we were on helm 2.6.2 (and then upgraded helm to 2.8.2 and still had the problem)


ben.podoll [4 hours ago]
side note: when we delete the deployment with helm, the situation is obviously fixed, but the weird thing is that the first `helm upgrade` after that (updates the deployment env section correctly, and doesn’t exhibit this bug). I’m going to try to do a bunch more `helm upgrade`s and add env vars to see if there is a point when it breaks…


Dco [3 hours ago]
I tried again on k8s 1.8.8 with helm 2.8.2 and it is upgrading as expected. I do remember testing upgrades with k8s 1.7.3 with helm 2.8.1 working correctly however


ben.podoll [1 hour ago]
final thought: so after I did a bunch more `helm upgrade`s my deployment’s `env:` section was properly being updated (no sign of the problem). So it must be some weird situation where this occurs…as it is seemingly intermittent.


Dco [< 1 minute ago]
yea I'm facing similar intermittent issues as well, it worked on a second test on k8s 1.7.3 and helm 2.8.2, whereas before it kept hitting this issue..
```

**Comment by AndrewDryga** [comment] 2018-06-17 13:29
Same here

**Comment by victorcete** [comment] 2018-07-03 17:09
+1 here

kubernetes v1.9.6
helm v2.9.1

Helm looks correct,
```
$ helm get foo --tls | grep -A1 REMOTE_URL
          - name: REMOTE_URL
            value: https://myservice.example.com
```

but the Deployment in Kubernetes is not reflecting the same variable value:
```
$ kubectl get deployment -o yaml fool | grep -A1 REMOTE_URL
        - name: REMOTE_URL
          value: http://localhost
```

**Comment by bacongobbler** [comment] 2018-07-03 17:21
@victorcete any chance you can supply the templates and the command used to install the project? THat would help identify the bug, if any. :)

**Comment by victorcete** [comment] 2018-07-03 17:22
@bacongobbler definitely! I need to obfuscate the template a bit but I'll share the timeline of events, the commands and a more detailed explanation of the problem in a bit

**Comment by ksemaev** [comment] 2018-08-22 14:37
@bacongobbler 
template:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
    spec:
      containers:
      - name: {{ $.Chart.Name }}
        imagePullPolicy: Always
        image: "image:tag"
        env:
        {{- range $key, $value := index .Values "daemon" "env" }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := index .Values "daemon-two" "env" }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        command:
{{ index .Values "daemon-two" "command" | toYaml | indent 12 }}
        resources:
{{ index .Values "daemon-two" "resources" | toYaml | indent 12 }}
        ports:
{{ index .Values "daemon-two" "ports" | toYaml | indent 12 }}
```

values:
```
daemon:
  env:
    OPTIONS: "--max-old-space-size=2048"
    POSTGRES_POOL_SIZE: "20"
    PROMETHEUS: "true"
    LISTEN_TCP: "0.0.0.0:8548"


daemon-two:
  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: 1000m
      memory: 3Gi
  ports:
    - containerPort: 8548
      protocol: TCP
      name: http
    - containerPort: 8547
      protocol: TCP
      name: client
  serviceports:
    - name: http
      protocol: TCP
      port: 8548
      targetPort: http
    - name: client
      protocol: TCP
      port: 8547
      targetPort: client
  command:
    - arg1
    - arg2
  env:
    SAVE_EXTRA_DATA: "true"
    STAGE2_THREADS: "8"
    CLIENTS: "0.0.0.0:8547"
    SYNC_WORKERS: "1"
```

command:
`helm upgrade -i --wait app app/ -f values.yaml --debug`

**Comment by ksemaev** [comment] 2018-08-22 14:42
@bacongobbler did `helm get RELEASE_NAME`  as you asked in https://github.com/helm/helm/issues/2647
and I can see the changes
but kubectl still does not see them

**Comment by DBarthe** [comment] 2019-03-18 18:32
I faced similar issue using helm v2.12.3 and k8s v1.11.4.
I had to manually edit the deployment yaml.
 The problem seems to occur only with environments, image name and other settings are correctly updated.

**Comment by kmurthy0** [comment] 2019-06-10 18:04
I'm running into this issue as well - helm 2.10.0 and k8s 1.11.6. One of the environment variables in deployment doesn't get updated. The workaround I've found is to do `helm delete` followed by a `helm upgrade --install` again. Has anyone found a workaround that doesn't require `helm delete` ?

**Comment by kmurthy0** [comment] 2019-06-10 19:09
Answering my own question, the workaround I've found to work is to manually edit deployment following which, `helm upgrade` appears to work correctly.

**Comment by ygnr** [comment] 2019-08-20 01:37
I ran into this as well, any better solutions other than deleting the chart?

**Comment by HassanHashemi** [comment] 2019-09-10 20:32
@bacongobbler is this identified as a bug or question?
We are facing similar issue.

**Comment by cuotos** [comment] 2019-09-23 14:26
This still appears to be an issue over a year later!?

Helm doesn't appear to notice changes in environment variables. I can remove them from the chart and they remain in our deployment. I can also manually edit an env var in a k8s deployment and expect a helm deployment to revert it to match the chart, but doesn't.

helm: 
  client 2.13.1
  server: 2.14.1

k8s:
  client: 1.13
  server: 1.13

**Comment by bacongobbler** [comment] 2019-09-23 14:52
this appears at first glance to be related to #3805 which was fixed in Helm 3 (see [the Helm 3 FAQ topic](https://v3.helm.sh/docs/faq/#improved-upgrade-strategy-3-way-strategic-merge-patches) for a good write-up on the behaviour). It's hard to tell though because there are many reports here without much information on how to reproduce the issue on their end... If y'all wouldn't mind demonstrating the issue, that would be more helpful to triage.

**Comment by cuotos** [comment] 2019-09-24 09:05
You're right. As it affects a number of our clusters and multiple releases, I assumed it would be a bigger issue, and easy to replicate. But when I tried to in isolation with a vanilla chart and just a deployment, I was unable. I will keep digging and try and find something.
But the symtoms are that changing an env variable in a Deployment and running an upgrade replaces the pods, but the env variables of the Deployment are not updated. 

The configmap of the release in kube-system shows the expected values, but the deployment doesn't.

**Comment by jlcrow** [comment] 2020-05-04 14:53
I've seen this same behavior with anything passed into an array in the deployment - having the same trouble with hosts.hostAliases array not picking up changes in the deployment when the values changed with Helm 3.2 on k8s 1.15.11

`  spec:
      hostAliases:
      {{- toYaml .Values.global.hosts.hostAliases | nindent 8 }}`

**Comment by bacongobbler** [comment] 2020-08-14 17:33
I'm going to assume @krishicks' original issue has been fixed for Helm 3 as identified in my earlier comment with the changes to a 3-way merge patch strategy. @krishicks, if you're still experiencing the same issue on Helm 3, please let us know. For everyone else, please open a new ticket.

@jlcrow in your particular case, please open a ticket with a better explanation on how we can reproduce your issue. That does not appear to be the same error case that @krishicks originally mentioned in the OP, and we're trying to avoid conflating multiple issues together into one ticket. Thanks!

**Closed by bacongobbler** 2020-08-14 17:33 UTC
Labels: question/support
