### ISSUE TITLE
Helm release version contains README.md

### ISSUE THREAD

**Issue by naveen-adisesha** [helm/helm#10764] opened 2022-03-13 07:42 UTC
We noticed during general upgrade that configmap size exceeded for the umbrella chart. 
on further investigation found that README files in main chart directory were part of the helm release. Note that this file is required to aid the user for chart installation. So it cannot be part of .helmignore. So would it be a good option to 
1. extend .helmignore to include an option such as "partofpackagebutnotpartofrelease" to indicate  as name suggests
2. or create separate cm/secret per sub chart to avoid resource crunch. 

If there is already such an option, please guide me to the same.

Output of `helm version`: 3.x

Output of `kubectl version`: Not Applicable

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Not Applicable

**Comment by bacongobbler** [comment] 2022-03-16 14:49
duplicate of https://github.com/helm/helm/issues/10308.

**Closed by bacongobbler** 2022-03-16 14:49 UTC
