### ISSUE TITLE
Provide alpha release of helm 3 for alpha testing

### ISSUE THREAD

**Issue by Alphapage** [helm/helm#4581] opened 2018-09-03 17:54 UTC
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

Hello,

It would be great to be able to download an alpha release of helm 3 in the release section and issue problems during testing (for installation, migration,...).

It seems there is no timeline for helm 3. Can we expect to switch to helm 3 quickly or wait for a year ?

Thank you in advance for your answers.

**Comment by bacongobbler** [comment] 2018-09-03 18:16
Hey @Alphapage! Please see my comment in #4112 to download an alpha release of Helm 3.

Please keep in mind that we are not looking at, accepting, or triaging any issues or PRs raised against the Helm 3 branch until all of the main refactoring work is done. This is to avoid any interference while refactors are in-flight and to make sure we have a stable foundation on which to build/accept issues and PRs against.

If you're interested in hearing more about ongoing development, please come to the [weekly public helm dev calls](https://github.com/helm/community/blob/master/communication.md#weekly-meeting) where we're discussing in-flight work.

Closing as a dupe of #4112 and #4363. Thanks!

**Closed by bacongobbler** 2018-09-03 18:16 UTC
