### ISSUE TITLE
Unable to upgrade HELM with new kubernetes kind

### ISSUE THREAD

**Issue by rrajadevops** [helm/helm#5230] opened 2019-01-30 05:43 UTC
Output of `helm version`:

Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

AKS

Hi Team,

I am using helm to upgrade my kubernetes Deployment. I am planning to add some existing Configmaps with this upgrade but I could upgrade. I got the below error.

Error: UPGRADE FAILED: no ConfigMap with the name "app-conf" found

The command I tried:

helm upgrade releasename .

helm upgrade --install releasename .

Can someone suggest how to add existing kind in existing helm release without deleting helm release.

**Comment by bacongobbler** [comment] 2019-01-30 06:14
Looks to me like a duplicate of https://github.com/helm/helm/issues/4423. Are you okay with me closing this in favour of that ticket?

**Closed** 2019-02-06 15:59 UTC
