### ISSUE TITLE
Files Get and Glob add new lines. Impossible to use as documented for secrets.

### ISSUE THREAD

**Issue by michaelajr** [helm/helm#3410] opened 2018-01-28 18:04 UTC
This will not work:

```
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
{{ (.Files.Glob "bar/*").AsSecrets | indent 2 }}
```

A new line is added to the contents of the file by `Glob` (and `Get` for that matter). Lost 4 hours of my life debugging this.

**Comment by bacongobbler** [comment] 2018-01-31 09:39
I was able to confirm this with a basic chart.

```
><> cat mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
{{ (.Files.Glob "foo.txt").AsSecrets | indent 2 }}
><> cat mychart/foo.txt
hi
><> helm template ./mychart/
---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
  foo.txt: aGkK


```

However, I found out that this can be mitigated by using a trailing dash to trip all trailing whitespace.

```
{{ (.Files.Glob "foo.txt").AsSecrets | indent 2 -}}
```

Does that solve your issue?

**Comment by bacongobbler** [comment] 2018-01-31 09:42
After experimenting I think this has something to do with `.AsSecrets` as opposed to `.Files.Glob` or `.Files.Get` though. Those seem to work as intended.

**Comment by bacongobbler** [comment] 2018-01-31 09:44
e.g. using .Files.Get directly works just fine for me.

```
><> helm template ./mychart/
---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
  - foo.txt: aGkK
  - bar.txt: YnllCg==

><> cat mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
  - foo.txt: {{ b64enc (.Files.Get "foo.txt") }}
  - bar.txt: {{ b64enc (.Files.Get "bar.txt") }}
><> helm template ./mychart/
---
# Source: mychart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
  - foo.txt: aGkK
  - bar.txt: YnllCg==

```

**Comment by michaelajr** [comment] 2018-01-31 13:53
Thanks for looking into this.Pretty sure I tried the `-` at the end. It just trimmed the resulting base64 string not the contents of the "get file". Will test again.

**Comment by michaelajr** [comment] 2018-01-31 13:55
Btw, I worked around this my getting each file individually and trimming the `\n` BEFORE base64 encoding. ```username: {{ .Files.Get "secrets/username" | trimSuffix "\n" | b64enc }}
  password: {{ .Files.Get "secrets/password" | trimSuffix "\n" | b64enc }}```

**Comment by consideRatio** [comment] 2018-04-05 23:04
Submitted PR to fix this, input appreciated!

**Comment by bacongobbler** [comment] 2018-04-30 12:50
We've reverted this change due to breaking the Prometheus charts that expected this behaviour. Because this is expected behaviour we cannot change this, so we're gonna have to keep this one closed as intentional for Helm 2, but keep it open for Helm 3.

**Comment by bacongobbler** [comment] 2019-10-11 18:50
fixed in Helm 3: https://github.com/helm/helm/blob/da729446116954bcb074bd4da742c3e9593f1f10/pkg/engine/files_test.go#L42-L67

**Closed by bacongobbler** 2019-10-11 18:50 UTC
Labels: bug, v3.x

**Comment by ronaldpetty** [comment] 2020-10-07 22:27
I seem to be having a related issue in 3.  When using `--set-file`, it appears to append a newline, file does not have it.

**Comment by hickeyma** [comment] 2020-10-08 09:57
@ronaldpetty It might be worth raising a new issue describing your issue.
