### ISSUE TITLE
Proposal: Add --app-version flag to 'helm upgrade/install' commands

### ISSUE THREAD

**Issue by asetty** [helm/helm#4793] opened 2018-10-17 18:31 UTC
Our current workflow for deploying helm charts involves ansible tasks that call the `helm upgrade` CLI command and it would be nice to be able to pass a flag to set the appVersion when revising a release for the same chart version.

It may be a little weird conceptually because an appVersion is associated with a chart rather than release, but in our case we are just updating the image tag used for some containers and our workflow hasn't come to incorporate chart version and/or chart repositories yet. This may change in the future, but for now I don't see any issue with adding a flag for `--app-version` on install and upgrade as the field is purely informational.

I'm interested to hear other opinions and thoughts on this proposal. :)

**Comment by bacongobbler** [comment] 2018-10-18 21:39
dupe of https://github.com/helm/helm/issues/3555

**Closed by bacongobbler** 2018-10-18 21:39 UTC
Labels: feature
