### ISSUE TITLE
[helm3] Could not get apiVersions from Kubernetes

### ISSUE THREAD

**Issue by tinyzimmer** [helm/helm#6991] opened 2019-11-17 14:18 UTC
Output of `helm version`:

```
$> helm version
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

Output of `kubectl version`:

```
$> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Only tested in `kind`, seems the type of thing that would happen elsewhere though. 

---

This feels racey, but the behavior occurs with using `--wait` also sometimes. Basically, I used the helm chart to install `stable/metrics-server`, and then for anywhere from 10-30 seconds after that chart is installed, helm becomes temporarily unusable. 

I'll go to install a second (unrelated) chart and `helm` immediately returns:

```
Error: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```

After waiting a bit, I'll eventually be able to continue with other charts.

I assume helm3 is trying to validate the APIs it has available to itself instead of letting the API servers just refuse something they can't make. If that's the case, would it be able to ignore APIs it is not concerned with at that moment? Or does it need to actually attempt to interact with an API instead of just ensuring it is present?

Or is there something I haven't thought of 😛

**Comment by marckhouzam** [comment] 2019-11-17 14:44
Thanks for the report.
I believe it's a duplicate of #6361

**Comment by tinyzimmer** [comment] 2019-11-17 14:47
Ah, indeed it is. My bad 😄

**Closed** 2019-11-17 15:59 UTC
