### ISSUE TITLE
Subchart dependencies ignored?

### ISSUE THREAD

**Issue by jkroepke** [helm/helm#4263] opened 2018-06-24 20:57 UTC
HI,

currently I'm start playing today with helm. I'm start using a vendor charts which I want to extent (for example use route.openshift.io/v1.Route instead Ingress objects.

So I create a _umbrella chart_ with follow dependencies:

```
dependencies:
- name: harbor
  version: "0.2.0"
  repository: "file://../../upstream/harbor/"
- name: mailout
  version: "1.0.0"
  repository: "file://../mailout/"
```

I noticed that the subchart harbor has a own requirements, too:

```
$ cat ../../upstream/harbor/requirements.yaml 
dependencies:
- name: postgresql
  version: 0.9.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: redis
  version: 3.2.5
  repository: https://kubernetes-charts.storage.googleapis.com
```

Running `helm dep up` and `help dep ls` results into this:

```
$ helm dep up
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: connect: connection refused
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Deleting outdated charts

$ helm dep ls
NAME   	VERSION	REPOSITORY                   	STATUS
harbor 	0.2.0  	file://../../upstream/harbor/	ok
mailout	1.0.0  	file://../mailout/           	ok
```

Now if I run `helm template` or `helm install --dry-run` i would miss the object that would be created by the `redis` or `postgresql` chart.

I can't find something in the documentation that this should not work .. or should work. But I found a testcase similiar to this https://github.com/kubernetes/helm/tree/master/pkg/chartutil/testdata/subpop so probably it should work, not?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://example.com:443
openshift v3.9.0+46ff3a0-18
kubernetes v1.9.1+a0ce1bc657
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
```
Openshift
```

**Comment by jkroepke** [comment] 2018-06-24 21:00
Maybe https://github.com/kubernetes/helm/issues/2247

**Comment by bacongobbler** [comment] 2018-07-26 23:08
Yes this is definitely a duplicate of #2247. Thank you for identifying that! Let's keep the discussion in a single ticket for tracking purposes. Thanks!

**Closed by bacongobbler** 2018-07-26 23:08 UTC
Labels: question/support
