### ISSUE TITLE
Helm init and helm version error

### ISSUE THREAD

**Issue by kaushalrai7797** [helm/helm#6476] opened 2019-09-23 14:31 UTC
Hi! I was trying to setup my minikube environment using helm. After installing helm once i run Helm init it says error installing: server could not find the requested resource. Helm version command runs for client but shows error could not find tiller

Output of `helm version`:
Client version details (v2.13.0) and an error could not find tiller
Output of `kubectl version`: shows output for both server and client

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment] 2019-09-23 14:31
duplicate of #6374

**Closed by bacongobbler** 2019-09-23 14:31 UTC
