### ISSUE TITLE
Pinned dependency failing to download

### ISSUE THREAD

**Issue by lewiscowleschipuk** [helm/helm#10012] opened 2021-08-09 10:48 UTC
Output of `helm version`: v2.16.1-linux-amd64

Output of `kubectl version`: 1.14.9

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

https://kubernetes-helm.storage.googleapis.com/helm-v2.16.1-linux-amd64.tar.gz is saying the key does not exist.

v2.16.12 does exist. Is this following SEMVER? I know https://helm.sh/docs/chart_best_practices/conventions/ mentions SEMVER, but it is unclear if this applies to HELM or just the versions of upstream images pulled.

**Comment by hickeyma** [comment] 2021-08-09 10:56
Duplicate of #10005

**Comment by hickeyma** [comment] 2021-08-09 11:03
Closing as related issues: #10005 #10004 #10003 #10011

**Closed by hickeyma** 2021-08-09 11:03 UTC

**Comment by lewiscowleschipuk** [comment] 2021-08-09 17:38
Thank you and my apologies. We wound up pinning to a newer tagged version, but I also see https://github.com/helm/helm/issues/10005 references a script. I'll see if our platform team can get it into the backlog. I'd probably just tried to alter some old code, but the frustration came from helm deploying Friday and not today without code changes our-side.

**Comment by bacongobbler** [comment] 2021-08-09 18:26
> but I also see #10005 references a script.

Which script? I don’t see one referenced in the comments.
