### ISSUE TITLE
Bug when failed deployment that adds new resources

### ISSUE THREAD

**Issue by timgentonzo** [helm/helm#5956] opened 2019-06-28 14:08 UTC
The bug is a little obscure. You can reproduce easily with instructions in this repo - https://github.com/timgent/helm-bug-demo - it also gives a full description of what happens

Broadly the bug occurs if you new resources get added during a deployment that fails. When you then fix the reason for that failure it will fail to roll out the new fix.

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Home baked kubernetes on AWS EC2

**Comment by bacongobbler** [comment] 2019-07-02 19:44
Pretty sure this is a duplicate of #1193 which was fixed with the `--cleanup-on-fail` flag added in Helm 2.14.0. Please upgrade to the latest release and use that flag going forward when adding new resources to your chart. See #1193 for more information on the bug and its behaviour. Thanks!

**Closed by bacongobbler** 2019-07-02 19:44 UTC
Labels: question/support
