### ISSUE TITLE
Does Helm release stores the sub-chart's chart in the Secret/Configmap?

### ISSUE THREAD

**Issue by anemade** [helm/helm#8501] opened 2020-07-22 11:30 UTC
This is not an issue. It's a help request.
I am wondering if helm stores the sub-chart's charts in the secret/configmap. As far as I have debugged, I don't think so. I tried debugging the Run method in https://github.com/helm/helm/blob/master/pkg/action/install.go

While processing the release in the Run, I can see the sub-chart present in the parent chart and in the release object throughout the Run method. But, while creating secret/configmap, it is marshaling the release object and parent chart dependencies i.e. sub-chart's chart is not getting marshaled in this process and I believe the reason is that in the Chart struct, dependencies is the non-exported field and without JSON tag and that's why it's not getting marshaled.

```
type Chart struct {
	// Raw contains the raw contents of the files originally contained in the chart archive.
	//
	// This should not be used except in special cases like `helm show values`,
	// where we want to display the raw values, comments and all.
	Raw []*File `json:"-"`
	// Metadata is the contents of the Chartfile.
	Metadata *Metadata `json:"metadata"`
	// LocK is the contents of Chart.lock.
	Lock *Lock `json:"lock"`
	// Templates for this chart.
	Templates []*File `json:"templates"`
	// Values are default config for this chart.
	Values map[string]interface{} `json:"values"`
	// Schema is an optional JSON schema for imposing structure on Values
	Schema []byte `json:"schema"`
	// Files are miscellaneous files in a chart archive,
	// e.g. README, LICENSE, etc.
	Files []*File `json:"files"`

	parent       *Chart
	dependencies []*Chart
}
```
`My use case is`:  I am trying to get the helm release by running `Run` method from install.go using charts from existing deployed release and different release name and because of the sub chart, it's breaking while rendering the templates. I am expecting the manifests generated with a new release name.
Is there any way that I can use to get the parent chart and sub-chart from the release secret/configmap?

`helm version`: v3.0.0

`kubectl version`: v1.18.4

`k8s version`: v1.16.10

**Comment by anemade** [comment] 2020-07-22 11:36
I believe the secret/configmap size limitations can be the reason for not storing the sub chart's templates.

**Comment by bacongobbler** [comment] 2020-07-22 13:51
The templates are not saved in the release object. The templates run through the template engine, and the output of the rendering engine is saved for later reference (`helm rollback`). We do not save subchart metadata to save space, and because helm does not need to use the templates after they’ve been rendered.

See also #8480, which appears this may be a duplicate of that same issue.

Hope this helps.

**Closed by bacongobbler** 2020-07-22 13:51 UTC
