### ISSUE TITLE
helm deployment yaml ignoring lifecycle postStart hook code for Windows AKS

### ISSUE THREAD

**Issue by nreddipalle** [helm/helm#8301] opened 2020-06-12 02:22 UTC
my deployment yaml looks like this:
```containers:
        - name: newsite
          image: acr.azurecr.io/ios:site20200611-195229
          lifecycle:
            postStart:
              exec:
                command:
                  - "powershell.exe"
                  - "-command"
                  - " Write-Output "Hello World" ; "
          ports:
          - containerPort: 85
          imagePullPolicy: Always```

This works fine when deploying directly using kubectl apply.. 
but the same code is not getting deployed correctly while using helm deploy

```containers:
        - name: {{ .Values.os.deployment.name }}
          image: "{{ .Values.os.image.repository }}:{{ .Values.os.image.tag }}"
          {{- if eq (default .Values.env "prod") "stg" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "powershell.exe"
                  - "-command"
                  - " Write-Output "Hello World" ; "
          {{- end }}
          ports:
          - containerPort: 85
          imagePullPolicy: {{ .Values.os.image.pullPolicy }}```

Post deployment, the lifecycle part is completely missing from the deployment yaml file when checked from AKS.. so my postStart events are not running via helm package..

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

Anybody faced similar issue or anything wrong above in the code. please suggest..

**Comment by bacongobbler** [comment] 2020-06-12 06:29
> while using helm deploy

Helm deploy doesn’t exist as a command. Did you mean helm upgrade?

Can you please share what version of helm and kubernetes you’re using?

Can you please share a full deployment template as well? We won’t be able to reproduce the issue without a full template.

**Comment by nreddipalle** [comment] 2020-06-12 06:44
yes its helm upgrade. helm 2.11 and Windows AKS 1.15.10
Here is the deployment yaml.. 

```apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.senseios.deployment.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    helm.sh/chart: {{ include "senseios.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Values.senseios.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.senseios.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.senseios.deployment.name }}
    spec:
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      nodeSelector:
        "kubernetes.io/os": windows
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
    {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.senseios.deployment.name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Values.senseios.deployment.name }}
          image: "{{ .Values.senseios.image.repository }}:{{ .Values.senseios.image.tag }}"
          {{- if eq (default .Values.env "prod") "stg" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "powershell.exe"
                  - "-command"
                  - "Invoke-WebRequest '{{ .Values.senseios.config.connectionstringsasurl }}' -OutFile 'c:\\www\\sensei\\web\\ConnectionStrings.config' ; Invoke-WebRequest '{{ .Values.senseios.config.appsettingsasurl }}' -OutFile 'c:\\www\\sensei\\web\\AppSettings.config';"
          {{- end }}
          ports:
          - containerPort: 85
          imagePullPolicy: {{ .Values.senseios.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /manifest.json
              port: 85
            failureThreshold: 1
            periodSeconds: 10
          #startupProbe:
          #  httpGet:
          #    path: /manifest.json
          #    port: 85
          #  failureThreshold: 30
          #  periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 85
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          {{- if eq (default .Values.spot "false") "true" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
          {{- end }}
              - key: kubernetes.azure.com/scalesetpriority
                operator: In
                values:
                - spot
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"```

**Comment by bacongobbler** [comment] 2020-06-12 06:49
helm 2.11 was released in 2018. Can you please try to reproduce this with a more recent version? Helm 2.16.8 is the latest helm 2 release. Thanks.

**Comment by nreddipalle** [comment] 2020-06-12 06:53
Ok. Thanks. Will check and update.

**Comment by nreddipalle** [comment] 2020-06-12 17:28
tried with helm 2.16.8 and still the lifecyclehook didn't get deployed after helm upgrade..

**Comment by mattfarina** [comment] 2020-06-24 15:53
@nreddipalle I think there is a problem in your template. It says `eq (default .Values.env "prod") "stg"`. They will never equal. The value to evaluate needs to be the last one. This is always reduced to `eg "prod" "stg"` which is false. The arguments to `default` are transposed.

**Comment by bacongobbler** [comment] 2020-06-24 21:36
That does indeed to be the issue. Good catch @mattfarina.

Let us know if that fixes your issue, @nreddipalle.

From [sprig's documentation on default](http://masterminds.github.io/sprig/defaults.html):

> To set a simple default value, use default:

>     default "foo" .Bar

> In the above, if .Bar evaluates to a non-empty value, it will be used. But if it is empty, foo will be returned instead.

**Comment by nreddipalle** [comment] 2020-06-26 15:34
Just to confirm, my values.yaml contains env: prod and while deploying this value can be overwritten to set as stg..
and I want to include the postStart hook only when env is set as stg.

Values.yaml:
```
# Default values for senseios.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
spot: false
env: prod
```
Set Values as part of azure devops task: 
`resources.limits.memory=500Mi,env=stg`

Correct me if my syntax is still wrong..

**Comment by bacongobbler** [comment] 2020-06-26 15:39
The issue isn't with your values. You values are fine here. It's your templates. More specifically it's anywhere you're calling `default`. Your arguments are in reverse order.

Try using the following instead and see if your chart no longer ignores your lifecycle PostStart hook code.

```
          {{- if eq (default "prod" .Values.env) "stg" }}
```

```
          {{- if eq (default "false" .Values.spot) "true" }}
```

**Comment by nreddipalle** [comment] 2020-06-26 16:05
Thanks. I will update and check.

**Comment by nreddipalle** [comment] 2020-06-29 07:19
I tried with the above syntax, It keeps failing during helm deploy step.. 
```
nodeAffinity:
          {{- if eq (default "false" .Values.spot) "true" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
          {{- end }}
              - key: kubernetes.azure.com/scalesetpriority
                operator: In
                values:
                - spot
```
```
 {{- if eq (default "prod" .Values.env) "stg" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - "powershell.exe"
                  - "-command"
```

Error:

 ```
2020-06-26T20:32:15.5446831Z [command]C:\hostedtoolcache\windows\helm\2.16.8\x64\windows-amd64\helm.exe upgrade --tiller-namespace kube-system --namespace newsite-stg --install --force --set os.deployment.name=newsite,service.name=newsite,ingress.name=newsite,ingress.namespace=newsite-stg,os.image.tag=newsite20200626-153314,replicaCount=1,spot=true,ingress.hosts[0]=newsite-staging.com,ingress.tls[0].host=newsite-staging.com,resources.limits.memory=500Mi,env=stg --wait --version 20200626-153314 newsite-stg acr/os
2020-06-26T20:32:17.0862755Z UPGRADE FAILED
2020-06-26T20:32:17.0863317Z Error: UPGRADE FAILED: a release named newsite-stg is in use, cannot re-use a name that is still in use
2020-06-26T20:32:17.0863772Z Error: a release named newsite-stg is in use, cannot re-use a name that is still in use
2020-06-26T20:32:17.0908217Z ##[error]Error: UPGRADE FAILED: a release named newsite-stg is in use, cannot re-use a name that is still in use
```

**Comment by mattfarina** [comment] 2020-06-29 21:15
@nreddipalle I see two things...

1. "false" and "true" in this case are strings instead of bool. That's fine if that's what you want but I wanted to point that out. If the value is not quoted in your `values.yaml` file you will have an issue because it would be a bool there and a string in the template.

2. The issue is not longer a template issue. It seems you have a version of the application installed. You could use `helm list` to see it and `helm delete` to remove it, if you want. It's now saying it can't install something with the same name in the same namespace.

**Comment by bridgetkromhout** [comment] 2020-08-20 23:27
Hi, @nreddipalle - as we have not heard more from you, I hope that your issues are resolved. As we were discussing Helm 2, I do want to let you know that Helm 2 support is ending in November. You will want to move to Helm 3: https://helm.sh/blog/helm-v2-deprecation-timeline/ - thanks, and please let us know if you have further questions.

**Closed by bridgetkromhout** 2020-08-20 23:27 UTC
Labels: question/support
