### ISSUE TITLE
Helm v3 support adding/referencing Azure container registry as repository

### ISSUE THREAD

**Issue by ben-kletzine-jdas** [helm/helm#8094] opened 2020-05-11 21:56 UTC
I would like to store my helm chart in Azure container registry using Helm 3. There is existing documentation on how to do this:
[https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#use-the-helm-3-client](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos#use-the-helm-3-client
)

I am pulling in all the helm charts i need to deploy via dependencies block in Chart.yaml. How do i reference an ACR repository? I don't see any example of ACR in [https://helm.sh/docs/topics/chart_repository/](https://helm.sh/docs/topics/chart_repository/)

Here is an example of what I want to do:
**Run**
```
 helm repo add acr https://my-acr.azurecr.io
```
**In chart.yaml**
```
dependencies:
- name: my-helm-chart
  repository: '@acr'
  version: 1.0.0
```

Related azure issue:
[https://github.com/MicrosoftDocs/azure-docs/issues/32165](https://github.com/MicrosoftDocs/azure-docs/issues/32165)

**Comment by bacongobbler** [comment] 2020-05-11 22:18
An Azure Container Registry is referred to as an OCI Registry, and this is an experimental feature. Documentation for what's supported with OCI registries can be found here: https://helm.sh/docs/topics/registries

Support for referencing OCI repositories as a dependency is still a work-in-progress. See #7613.

Closing as a duplicate of #6593. Thank you for your question.

**Closed by bacongobbler** 2020-05-11 22:18 UTC
