### ISSUE TITLE
helm v2.14.0 - does not recognize 'release' & 'heritage' in metadata

### ISSUE THREAD

**Issue by vishiy** [helm/helm#5782] opened 2019-05-22 19:05 UTC
Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"} 
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.7", GitCommit:"b30876a5539f09684ff9fde266fda10b37738c9c", GitTreeState:"clean", BuildDate:"2018-01-16T21:59:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

I see an error if i have 'release' or 'heritage' in metadata :-
example : https://github.com/helm/charts/blob/164ee72d34f9f8e7888c0619186983d108019165/incubator/azuremonitor-containers/templates/omsagent-rs-configmap.yaml#L227

Error: validation failed: error validating "": error validating data: [ValidationError(ConfigMap.metadata): unknown field "chart" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(ConfigMap.metadata): unknown field "heritage" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta, ValidationError(ConfigMap.metadata): unknown field "release" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta]

Is this deprecated ? I dont see any breaking changes in v2.14.0 release notes.

All works when using v2.13.1

**Comment by mattfarina** [comment] 2019-05-23 15:08
I had to look at this for a moment to figure it out. The problem is with the chart. It looks like there have been validation improvements in a dependency.

In a bunch of places there are things like...
```yaml
name: omsagentclusterrolebinding
chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
release: {{ .Release.Name }}
heritage: {{ .Release.Service }}
```

That should instead be...
```yaml
name: omsagentclusterrolebinding
labels:
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
```

Notice how `labels` is missing.

**Comment by bacongobbler** [comment] 2019-05-29 15:55
Also see https://github.com/helm/helm/issues/5750 for context. We're planning on backing this out for Helm 2 in 2.14.1.

This issue can occur due to two different situations:

- the chart being submitted via `helm upgrade` fails object validation, as @mattfarina pointed out. Reporting validation errors for this is a GOOD thing; it informs the user that they need to fix their chart so that the object being installed conforms to the API.
- poorly-formed charts installed using an older version of Helm may fail validation during a `helm upgrade`. This is because prior to 2.14, no validation occurred and the objects were silently accepted. Once `helm upgrade` is invoked, Helm fetches the older object metadata to perform a diff and validates the objects. This is a BAD thing, as in this case, `helm upgrade` will always fail validation, preventing upgrades.

Either situation can trigger this issue. In Helm 3, we're planning to force validation to occur from day one so you cannot install invalid objects into Kubernetes, but due to backwards compatibility issues we'll continue to accept invalid chart metadata for Helm 2.

**Comment by bacongobbler** [comment] 2019-05-29 15:55
closing as a duplicate of #5750. Thanks!

**Closed by bacongobbler** 2019-05-29 15:55 UTC
Labels: question/support
