### ISSUE TITLE
helm uninstall  command force to delete release when occur errors for deleting k8s resource object

### ISSUE THREAD

**Issue by idealceo** [helm/helm#9226] opened 2021-01-13 09:22 UTC
helm uninstall return informations: uninstallation completed with 1 error(s): etcdserver: request timed out ,but release is deleted,not founded, k8s resource for the deleted release still  exist in k8s cluster

**Comment by bacongobbler** [comment] 2021-01-13 15:13
duplicate of #9201?

**Comment by mikeshng** [comment] 2021-01-15 18:44
@bacongobbler Yes, the crux of the problem is the same. I updated https://github.com/helm/helm/issues/9201 to mention the fact that I had to use the `--keep-history` to leave behind the uninstall record.

In this case, the user didn't use the keep history flag so the release record is gone completely making it even harder to perform another helm uninstall / cleanup.

I made a post to the mailing list https://lists.cncf.io/g/cncf-helm/message/351 to talk about introducing a new flag `--fail-on-error` to helm uninstall as well as a new release status `failed-uninstall` which should help with the problem without changing the current default behaviour.

**Closed** 2021-01-15 19:17 UTC
Labels: question/support
