### ISSUE TITLE
upgrade apiVersion in k8s from 1.14 to 1.16 FAILED

### ISSUE THREAD

**Issue by alexandrsemak** [helm/helm#7604] opened 2020-02-15 19:01 UTC
We use kubernetes cluster 1.14 and planning to upgrade 1.16 but deprecated API removed in 1.16 as `extensions/v1beta1, apps/v1beta1, and apps/v1beta2` to `apps/v1`. After upgrade to 1.16 whole deprecated deployment api still serve but you have to use in subsequent release `apps/v1` for deployment and helm (2.16.1) throw following error:

```
UPGRADE FAILED
Error: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2" 
```

ATTENTION if you are trying use `--force` your release would be deleted with error:
```
UPGRADE FAILED
Error: Upgrade --force successfully deleted the previous release, but encountered 1 error(s) and cannot continue: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
Error: UPGRADE FAILED: Upgrade --force successfully deleted the previous release, but encountered 1 error(s) and cannot continue: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
```

Output of `helm version`:
2.16.1

**Comment by alexandrsemak** [comment] 2020-02-16 19:35
The same for Helm 3:
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
helm.go:76: [debug] unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
unable to build kubernetes objects from current release manifest
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:195
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/home/circleci/helm.sh/helm/pkg/action/upgrade.go:88
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:134
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
UPGRADE FAILED
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:136
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
```
After update cluster 1.14 to 1.16 deployment `extensions/v1beta1` works fine with `apps/v1`

**Comment by hickeyma** [comment] 2020-02-17 08:15
Duplicate of #7219

**Comment by hickeyma** [comment] 2020-02-17 08:16
Closing as duplicate

**Closed by hickeyma** 2020-02-17 08:16 UTC

**Comment by dguyhasnoname** [comment] 2020-04-26 14:43
Script to find deprecated objects: https://github.com/dguyhasnoname/k8s-day2-ops/blob/master/upgrade/k8s-deprecations.sh

**Comment by hickeyma** [comment] 2020-04-27 08:28
@dguyhasnoname Refer to #7219 fr more details on docs and tools.
