### ISSUE TITLE
Chart.dependencies is nil for chart with several known dependencies

### ISSUE THREAD

**Issue by arianaw66** [helm/helm#7847] opened 2020-03-31 21:42 UTC
`dependencies` field of helm Chart (https://github.com/helm/helm/blob/master/pkg/chart/chart.go#L52) is nil when it has several known dependencies.
Chart object was created using NewList constructor (https://github.com/helm/helm/blob/master/pkg/action/list.go#L132) and Run (https://github.com/helm/helm/blob/master/pkg/action/list.go#L140).
Then `releases[0].Chart.dependencies` was nil (where `releases, _ := lister.Run()`).

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Minikube

**Comment by bacongobbler** [comment] 2020-03-31 21:59
As implied by the [JSON meta tags](https://blog.golang.org/json) present in the Chart struct, the `Dependencies` is not saved when the chart is saved in the release object. It is therefore impossible to fetch the dependency tree using `helm list`.

This was intended as a way to save space in the release object. Kubernetes only allows 1MB of metadata to be stored in each object, and Helm requires all of the rendered output as part of [the `Manifest`](https://github.com/helm/helm/blob/06b43f63c30334a2825eb7e90da137d850ca20e3/pkg/release/release.go#L33) to perform its three-way diff functionality as part of `helm upgrade`. Adding the dependency tree to the release metadata would break several cases where the chart templates go well above the 1MB limit.

To determine a chart's dependency tree, you will need to load the chart from disk. That is the only time where the dependency tree is resolved and loaded into memory.

Hope this helps.

**Comment by bacongobbler** [comment] 2020-03-31 22:05
closing as a wontfix. This is an intentional design decision to work around Kubernetes' limitation of 1MB storage space. Thanks.

**Closed by bacongobbler** 2020-03-31 22:05 UTC
Labels: question/support
