### ISSUE TITLE
use helm uninstall --keep-history then helm rollback but status is "pending-rollback"

### ISSUE THREAD

**Issue by diaoyongbao** [helm/helm#7366] opened 2020-01-09 08:49 UTC
```
[root@master helm]# ./helm ls
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
consul-1576463223	default  	1       	2019-12-16 10:27:04.985083 +0800 CST   	deployed	consul-3.9.3       	1.5.3      
nginx            	default  	1       	2020-01-09 16:39:29.988269664 +0800 CST	deployed	nginx-example-1.0.0	           
[root@master helm]# ./helm uninstall nginx --keep-history
release "nginx" uninstalled
[root@master helm]# ./helm ls
NAME             	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART       	APP VERSION
consul-1576463223	default  	1       	2019-12-16 10:27:04.985083 +0800 CST	deployed	consul-3.9.3	1.5.3      
[root@master helm]# ./helm ls -a
NAME             	NAMESPACE	REVISION	UPDATED                                	STATUS     	CHART              	APP VERSION
consul-1576463223	default  	1       	2019-12-16 10:27:04.985083 +0800 CST   	deployed   	consul-3.9.3       	1.5.3      
nginx            	default  	1       	2020-01-09 16:39:29.988269664 +0800 CST	uninstalled	nginx-example-1.0.0	  
```

```
[root@master helm]# ./helm rollback nginx 1
Error: "nginx" has no deployed releases
[root@master helm]# kubectl get pods
NAME                             READY   STATUS              RESTARTS   AGE
consul-client-25ckh              1/1     Running             0          3d1h
consul-client-7lds7              1/1     Running             1          6d3h
consul-client-99pfb              1/1     Running             0          6d3h
consul-client-jsvr7              1/1     Running             0          6d3h
consul-client-kvsk6              1/1     Running             0          6d3h
consul-client-l6zlc              1/1     Running             0          6d3h
consul-client-l9rjc              1/1     Running             0          6d3h
consul-client-lcxzw              1/1     Running             0          6d3h
jenkins-5ff8bcccf-wnnw6          1/1     Running             0          16d
nginx-example-688b6bc778-btms7   0/1     ContainerCreating   0          2s
nginx-example-688b6bc778-w5bbp   1/1     Running             0          2s
sartorial-iguana-consul-0        1/1     Running             0          16d
sartorial-iguana-consul-1        1/1     Running             1          24d
sartorial-iguana-consul-2        1/1     Running             0          24d
ubuntu-7ffdf98498-ts4h7          1/1     Running             1          16d
[root@master helm]# ./helm ls
NAME             	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART       	APP VERSION
consul-1576463223	default  	1       	2019-12-16 10:27:04.985083 +0800 CST	deployed	consul-3.9.3	1.5.3      
[root@master helm]# 
[root@master helm]# 
[root@master helm]# ./helm ls -a
NAME             	NAMESPACE	REVISION	UPDATED                               	STATUS          	CHART              	APP VERSION
consul-1576463223	default  	1       	2019-12-16 10:27:04.985083 +0800 CST  	deployed        	consul-3.9.3       	1.5.3      
nginx            	default  	2       	2020-01-09 16:40:45.07583178 +0800 CST	pending-rollback	nginx-example-1.0.0	
```
Output of `helm version`:
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
kubeadm

**Comment by bacongobbler** [comment] 2020-01-09 16:38
duplicate of https://github.com/helm/helm/issues/6978.

**Closed by bacongobbler** 2020-01-09 16:38 UTC
Labels: bug
