### ISSUE TITLE
Helm Lint error

### ISSUE THREAD

**Issue by ushabapat** [helm/helm#10149] opened 2021-09-17 07:09 UTC
[ERROR] templates/aad-identity.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: "aadpodidentity.k8s.io/v1

when template has  --- separator, helm lint is failing with above error. After removing the separator (---) from the yaml , it works.  But our template file that consists of two YAML blocks wrapped into conditions that are separated with 3 dashes. We cant separate the yaml file for aad identity and binding.  Can you please check on this part.

It works if we change the helm version to 3.6.3

Output of `helm version`: 3.7.0

Output of `kubectl version`:  v1.18.0"

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AKS

**Comment by zonggen** [comment] 2021-09-17 19:05
Can reproduce:
```bash
$ helm create issue-10149 
```
`templates/serviceaccount.yaml`:

```yaml
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "issue-10149.serviceAccountName" . }}
  labels:
    {{- include "issue-10149.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "issue-10149.fullname" . }}
  labels:
    {{- include "issue-10149.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "issue-10149.selectorLabels" . | nindent 4 }}

{{- end }}

```
```
$ helm lint issue-10149

==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/serviceaccount.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1

Error: 1 chart(s) linted, 1 chart(s) failed
```

```
$ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

Also tried same chart with`v3.6.3`:
```
$ helm lint issue-10149
==> Linting issue-10149
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

One thing to note is that for both `v3.7.0` and `v3.6.3`, I can `helm install` without Error:

```
$ helm install hello-world issue-10149
NAME: hello-world
LAST DEPLOYED: Fri Sep 17 15:04:14 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=issue-10149,app.kubernetes.io/instance=hello-world" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

```

**Comment by eytanhanig** [comment] 2021-09-20 18:32
We've experienced the same issue. I believe this is confined to the `helm lint` command since `helm template` successfully generates valid YAML that can be deployed without issue.

**Comment by czenker** [comment] 2021-09-28 13:22
@zonggen I guess your problem is the leading dash at the second document that strips all the whitespace. Remove it and `helm lint` should be happy again.

```
[...]
{{- end }}
---
{{ if .Values.service.create -}}
apiVersion: v1
kind: Service
[...]
```

From [go template](https://pkg.go.dev/text/template)'s point of view, you want to generate a document that looks like this and obviously causes issues.

```
apiVersion: v1
kind: ServiceAccount
[...]
---apiVersion: v1
kind: Service
[...]
```

Admittedly, it is a bit strange that `helm lint` and `helm template` behave differently. As this has changed from last release it might be something to look into. But I am not sure if this whitespace control anomaly has ever been considerd a feature.

**Comment by bacongobbler** [comment] 2021-11-26 18:09
Yeah, this seems odd but it does appear to be capturing a valid error where the user has accidentally added metadata on the same line as a line break. I have a feeling this might've changed with an update to the YAML parser libraries Helm uses.

I'm going to close this as an unintended feature as it appears to be capturing a valid error case, but if there's something legitimately wrong with the parser then we can investigate this further.

**Closed by bacongobbler** 2021-11-26 18:09 UTC
Labels: question/support
