### ISSUE TITLE
Helm templating error: can't give argument to non-function with helm v3.5.2

### ISSUE THREAD

**Issue by abdelmonem17** [helm/helm#9424] opened 2021-02-27 13:02 UTC
Hello every one I am not expert on helm and I am using a lib which use helm and when I use it, it reports helm error as following :
template: base/templates/service.yaml:19:7: executing "base/templates/service.yaml" at <(.Values.health.port) and (not (eq .Values.health.port .Values.httpPort))>: can't give argument to non-function .Values.health.port 

so what is the problem in this line and thank you in advance.

**Comment by bridgetkromhout** [comment] 2021-03-05 21:26
Hi, @abdelmonem17 - This may be a go templating issue like you can see in https://github.com/helm/helm/issues/7711.

**Comment by bacongobbler** [comment] 2021-03-06 00:14
To close this out...

In text/template, `and` is a function call that accepts two arguments. It cannot be used in-between two arguments. If you change that line to `if and (...) (...)`, it should work as expected.

closing as a duplicate of #7711.

**Closed by bacongobbler** 2021-03-06 00:14 UTC
