### ISSUE TITLE
Upgrade fails when trying to --set a value's key written in camel-case 

### ISSUE THREAD

**Issue by masterdrdark** [helm/helm#4759] opened 2018-10-11 14:41 UTC
Output of `helm version`: 
```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS with KOPS

In my helm chart I had this `values.yaml`:
```
initContainers:
  - name: somename
    image:
      repository: xxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com/repo/app
      tag: latest
```

Notice the camel-case in `initContainers`.

When trying to run `helm upgrade my-release . --set initContainers.image.tag=mytag  -f values-staging.yaml` the upgrade would fail with this error:
```
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).key(0xc420ac5868, 0xc4209a5f50, 0x70, 0x1504c40)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:171 +0xe0a
k8s.io/helm/pkg/strvals.(*parser).parse(0xc420ac5868, 0xc420302cb0, 0x21)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:97 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7ffe11d850a4, 0x21, 0xc4209a5f50, 0x0, 0x0)
	/go/src/k8s.io/helm/pkg/strvals/parser.go:71 +0xbe
main.vals(0xc4209a2840, 0x2, 0x2, 0xc4209a2820, 0x2, 0x2, 0x20d01b0, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/helm/cmd/helm/install.go:364 +0x3d0
main.(*upgradeCmd).run(0xc4205cfb80, 0x0, 0x1772780)
	/go/src/k8s.io/helm/cmd/helm/upgrade.go:198 +0x221
main.newUpgradeCmd.func2(0xc4209b3200, 0xc4209c1e00, 0x2, 0xa, 0x0, 0x0)
	/go/src/k8s.io/helm/cmd/helm/upgrade.go:113 +0x141
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4209b3200, 0xc4209c1cc0, 0xa, 0xa, 0xc4209b3200, 0xc4209c1cc0)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:599 +0x3db
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42090e900, 0xc4209c2d80, 0xc4209c2fc0, 0xc4209c3200)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:689 +0x2d4
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42090e900, 0xb, 0xb)
	/go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/go/src/k8s.io/helm/cmd/helm/helm.go:160 +0x75
```

Only when I changed `initContainers` to `initcontainers` the chart was upgraded successfully

**Comment by hickeyma** [comment] 2018-10-11 15:51
FYI, it works on v2.11. Would need to test on 2.9 and 2.10. Didn't see any issue raised.

As an aside, would you be able to upgrade client and server to 2.11?

**Comment by sam-cogan** [comment] 2019-03-31 18:17
This issue seems to be occuring in 2.13.0. I am attempting to override a value in the format of valueName.settings[0].value=test and get the same panic: interface conversion error. If I change "valueName" to "valuename" the issue goes away.

**Comment by hickeyma** [comment] 2019-04-03 10:00
@sam-cogan I have been unable to reproduce this. Here are the findings of my investigation.

```console
$ cat chrt-4759/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range .Values.valueName.settings }}
  value: {{.value}}
  {{- end }}

$ cat chrt-4759/values.yaml 
valueName:
  settings:
    - value: val1
    - value: val2
```
```console
$ helm install --debug --dry-run chrt-4759/
[debug] Created tunnel using local port: '44053'

[debug] SERVER: "127.0.0.1:44053"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/chrt-4759

NAME:   jolly-whale
REVISION: 1
RELEASED: Wed Apr  3 10:52:33 2019
CHART: chrt-4759-0.1.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
valueName:
  settings:
  - value: val1
  - value: val2

HOOKS:
MANIFEST:

---
# Source: chrt-4759/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jolly-whale-configmap
data:
  value: val1
  value: val2
```
```console
$ helm install --debug --dry-run chrt-4759 --set valueName.settings[0].value=test,valueName.settings[1].value=prod,valueName.settings[2].value=dev
[debug] Created tunnel using local port: '36277'

[debug] SERVER: "127.0.0.1:36277"

[debug] Original chart version: ""
[debug] CHART PATH: /home/usr1/test/helm-charts/chrt-4759

NAME:   original-pika
REVISION: 1
RELEASED: Wed Apr  3 10:51:58 2019
CHART: chrt-4759-0.1.0
USER-SUPPLIED VALUES:
valueName:
  settings:
  - value: test
  - value: prod
  - value: dev

COMPUTED VALUES:
valueName:
  settings:
  - value: test
  - value: prod
  - value: dev

HOOKS:
MANIFEST:

---
# Source: chrt-4759/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: original-pika-configmap
data:
  value: test
  value: prod
  value: dev
```

**Comment by hickeyma** [comment] 2019-04-03 10:00
Let me know if you can provide me with more details to help reproduce this.

**Comment by hickeyma** [comment] 2019-06-26 08:04
Ping @masterdrdark @sam-cogan. Any update on this?

**Comment by masterdrdark** [comment] 2019-06-26 10:37
I'm sorry for the late reply, I totally missed the updates on the issue.

As of today we're using helm 2.14.1 and I wasn't able to reproduce this behavior.

Thank you!

**Comment by hickeyma** [comment] 2019-06-26 10:41
Thanks for feedback @masterdrdark. I will close the issue then.

**Closed by hickeyma** 2019-06-26 10:41 UTC
Labels: question/support

**Comment by erikanderson** [comment] 2022-01-04 20:11
Fwiw we had a similar issue and could reliably reproduce it in jenkins

```
15:02:44  + helm version
15:02:44  version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Doesn't work
```
15:02:47  + helm upgrade 2.0.0-0 ****** --set imagePullSecrets.username="****" --wait -f charts/****.yaml
15:02:47  + grep -v skipping loading invalid
[Pipeline] echo
15:03:20  [ERROR] The helm deployment failed because: Error: failed parsing --set data: unable to parse key: interface conversion: interface {} is []interface {}, not map[string]interface {}
```

Works
```
15:08:59  + helm upgrade 2.0.0-0 *******c --set imagepullsecrets.username=**** --wait -f charts/*******yaml
15:08:59  + grep -v skipping loading invalid
```

**Comment by quetzalcoatl** [comment] 2022-02-28 11:59
For anyone that may google out this issue by the error message text `Error: failed parsing --set data: unable to parse key: interface conversion` pasted earlier by **erikanderson**

My exact error was somewhat similar:

    Error: failed parsing --set data: unable to parse key: interface conversion: interface {} is nil, not map[string]interface {}

However, the issue **was not in the command line**, and no camel-case issues.  
Problem was in **values.yaml**.  
I was commenting out a piece of old configuration, and ended up with:

    foo:
        #bar: baz
        #bam: wham 
        #bag: 123

You may notice that `foo:` was left, and had no value, this its value is `nil`, and it should be an key-map-object, hence the error message. Either removing/commenting out `foo:` completely, or adding value (`foo:{}`) helped.
