### ISSUE TITLE
Why the default function still takes effect when the parameter exists

### ISSUE THREAD

**Issue by moluzhui** [helm/helm#10482] opened 2021-12-18 05:46 UTC
I have a parameter `shared` in two yamls, and used in different yamls through a `switch parameter`, and set the default value, as shown below
```
# values.yaml

replicaCount: 5

image: test/pause:3.2

crd:
  enabled: false
  ....
```
```
# crd1.yaml
...
spec: 
    name: crd1
    {{- if not .Values.crd.enabled }}
    partition: {{ .Values.parm | default 0 }}
    {{- end }}
```
```
# crd2.yaml
...
{{- if .Values.crd.enabled -}}
...
spec:
  # Add fields here
  name: crd2
  partition: {{ .Values.parm | default -1 }}
{{- end -}}
```
For the first time, I used the `helm upgrade release1 test.tgz -f values.yaml`, and then I updated again. **The only difference between the two updates is the presence or absence of parm parameters**
```
replicaCount: 5

# Second addition
parm: 0

crd:
  enabled: true
```
However, as a result, **crd2.yaml still uses the default -1**. 

If I change parm to `1` the `second time`, it seems to be ok. May I ask what is the reason for this

Output of `helm version`: 2.17

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by zonggen** [comment] 2021-12-20 15:34
I could not reproduce the issue. I `helm install` a test chart with `helm upgrade` twice as the given instructions. After the first upgrade, it shows the default value since the `param` is not given and the second release shows the `param` in the `values.yaml` file.

Though I was using helm `v3.7+unreleased`. Could you verify if it works on the latest Helm release with your workflow? Just a friendly reminder: https://helm.sh/blog/helm-v2-deprecation-timeline/

**Comment by moluzhui** [comment] 2021-12-21 03:26
I've solved this problem because **default** seems to have the same criteria for `nil and 0`, so I distinguish between the two in the following way
```
{{- if kindIs "invalid" .Values.parm }} # 
  partition: -1
{{- else }}
  partition: {{ .Values.parm }}
{{- end }}
```

**Comment by zonggen** [comment] 2021-12-21 14:56
Ah, thanks for explaining, I was using default `parm: 1` in the values file during my experiment, therefore didn't catch the behavior. I'm going to close this issue if there's no further concerns.

**Closed by zonggen** 2021-12-21 14:56 UTC
Labels: question/support
