### ISSUE TITLE
helm release metadata doesn't have repo/chart-url information

### ISSUE THREAD

**Issue by sbose78** [helm/helm#7544] opened 2020-02-06 19:33 UTC
Hi,

If I did a 
```
helm install https://redhat-developer.github.com/redhat-helm-charts/charts/nodejs-ex-k-0.1.0.tgz 
```
without adding a new repo, I was looking at the release metadata and I see the repo or the full chart url missing. 

As an enhancement, could we please have this information?

```
[
  {
    "name": "foo3",
    "info": {
      "first_deployed": "2020-01-22T13:59:18.293548246+01:00",
      "last_deployed": "2020-01-22T13:59:18.293548246+01:00",
      "deleted": "",
      "description": "Install complete",
      "status": "deployed",
      "notes": "1. Get the application URL by running these commands:\n  export POD_NAME=$(kubectl get pods --namespace foo -l \"app=foo3-mink\" -o jsonpath=\"{.items[0].metadata.name}\")\n  echo \"Visit http://127.0.0.1:8080 to use your application\"\n  kubectl port-forward $POD_NAME 8080:80\n"
    },
    "chart": {
      "metadata": {
        "name": "mink",
        "version": "0.1.0",
        "description": "A Helm chart for Kubernetes",
        "apiVersion": "v1"
      },
      "lock": null,
      "templates": [
        {
          "name": "templates/NOTES.txt",
          "data": "MS4gR2V0IHRoZSBhcHBsaWNhdGlvbiBVUkwgYnkgcnVubmluZyB0aGVzZSBjb21tYW5kczoKe3stIGlmIGNvbnRhaW5zICJOb2RlUG9ydCIgLlZhbHVlcy5zZXJ2aWNlLnR5cGUgfX0KICBleHBvcnQgTk9ERV9QT1JUPSQoa3ViZWN0bCBnZXQgLS1uYW1lc3BhY2Uge3sgLlJlbGVhc2UuTmFtZXNwYWNlIH19IC1vIGpzb25wYXRoPSJ7LnNwZWMucG9ydHNbMF0ubm9kZVBvcnR9IiBzZXJ2aWNlcyB7eyB0ZW1wbGF0ZSAiZnVsbG5hbWUiIC4gfX0pCiAgZXhwb3J0IE5PREVfSVA9JChrdWJlY3RsIGdldCBub2RlcyAtLW5hbWVzcGFjZSB7eyAuUmVsZWFzZS5OYW1lc3BhY2UgfX0gLW8ganNvbnBhdGg9InsuaXRlbXNbMF0uc3RhdHVzLmFkZHJlc3Nlc1swXS5hZGRyZXNzfSIpCiAgZWNobyBodHRwOi8vJE5PREVfSVA6JE5PREVfUE9SVC9sb2dpbgp7ey0gZWxzZSBpZiBjb250YWlucyAiTG9hZEJhbGFuY2VyIiAuVmFsdWVzLnNlcnZpY2UudHlwZSB9fQogICAgIE5PVEU6IEl0IG1heSB0YWtlIGEgZmV3IG1pbnV0ZXMgZm9yIHRoZSBMb2FkQmFsYW5jZXIgSVAgdG8gYmUgYXZhaWxhYmxlLgogICAgICAgICAgIFlvdSBjYW4gd2F0Y2ggdGhlIHN0YXR1cyBvZiBieSBydW5uaW5nICdrdWJlY3RsIGdldCBzdmMgLXcge3sgdGVtcGxhdGUgImZ1bGxuYW1lIiAuIH19JwogIGV4cG9ydCBTRVJWSUNFX0lQPSQoa3ViZWN0bCBnZXQgc3ZjIC0tbmFtZXNwYWNlIHt7IC5SZWxlYXNlLk5hbWVzcGFjZSB9fSB7eyB0ZW1wbGF0ZSAiZnVsbG5hbWUiIC4gfX0gLW8ganNvbnBhdGg9J3suc3RhdHVzLmxvYWRCYWxhbmNlci5pbmdyZXNzWzBdLmlwfScpCiAgZWNobyBodHRwOi8vJFNFUlZJQ0VfSVA6e3sgLlZhbHVlcy5zZXJ2aWNlLmV4dGVybmFsUG9ydCB9fQp7ey0gZWxzZSBpZiBjb250YWlucyAiQ2x1c3RlcklQIiAgLlZhbHVlcy5zZXJ2aWNlLnR5cGUgfX0KICBleHBvcnQgUE9EX05BTUU9JChrdWJlY3RsIGdldCBwb2RzIC0tbmFtZXNwYWNlIHt7IC5SZWxlYXNlLk5hbWVzcGFjZSB9fSAtbCAiYXBwPXt7IHRlbXBsYXRlICJmdWxsbmFtZSIgLiB9fSIgLW8ganNvbnBhdGg9InsuaXRlbXNbMF0ubWV0YWRhdGEubmFtZX0iKQogIGVjaG8gIlZpc2l0IGh0dHA6Ly8xMjcuMC4wLjE6ODA4MCB0byB1c2UgeW91ciBhcHBsaWNhdGlvbiIKICBrdWJlY3RsIHBvcnQtZm9yd2FyZCAkUE9EX05BTUUgODA4MDp7eyAuVmFsdWVzLnNlcnZpY2UuZXh0ZXJuYWxQb3J0IH19Cnt7LSBlbmQgfX0K"
        },
        {
          "name": "templates/_helpers.tpl",
          "data": "e3svKiB2aW06IHNldCBmaWxldHlwZT1tdXN0YWNoZTogKi99fQp7ey8qCkV4cGFuZCB0aGUgbmFtZSBvZiB0aGUgY2hhcnQuCiovfX0Ke3stIGRlZmluZSAibmFtZSIgLX19Cnt7LSBkZWZhdWx0IC5DaGFydC5OYW1lIC5WYWx1ZXMubmFtZU92ZXJyaWRlIHwgdHJ1bmMgMjQgLX19Cnt7LSBlbmQgLX19Cgp7ey8qCkNyZWF0ZSBhIGRlZmF1bHQgZnVsbHkgcXVhbGlmaWVkIGFwcCBuYW1lLgpXZSB0cnVuY2F0ZSBhdCAyNCBjaGFycyBiZWNhdXNlIHNvbWUgS3ViZXJuZXRlcyBuYW1lIGZpZWxkcyBhcmUgbGltaXRlZCB0byB0aGlzIChieSB0aGUgRE5TIG5hbWluZyBzcGVjKS4KKi99fQp7ey0gZGVmaW5lICJmdWxsbmFtZSIgLX19Cnt7LSAkbmFtZSA6PSBkZWZhdWx0IC5DaGFydC5OYW1lIC5WYWx1ZXMubmFtZU92ZXJyaWRlIC19fQp7ey0gcHJpbnRmICIlcy0lcyIgLlJlbGVhc2UuTmFtZSAkbmFtZSB8IHRydW5jIDI0IC19fQp7ey0gZW5kIC19fQo="
        },
        {
          "name": "templates/deployment.yaml",
          "data": "YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgbmFtZToge3sgdGVtcGxhdGUgImZ1bGxuYW1lIiAuIH19CiAgbGFiZWxzOgogICAgY2hhcnQ6ICJ7eyAuQ2hhcnQuTmFtZSB9fS17eyAuQ2hhcnQuVmVyc2lvbiB9fSIKc3BlYzoKICByZXBsaWNhczoge3sgLlZhbHVlcy5yZXBsaWNhQ291bnQgfX0KICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgYXBwOiB7eyB0ZW1wbGF0ZSAiZnVsbG5hbWUiIC4gfX0KICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgIC0gbmFtZToge3sgLkNoYXJ0Lk5hbWUgfX0KICAgICAgICBpbWFnZTogInt7IC5WYWx1ZXMuaW1hZ2UucmVwb3NpdG9yeSB9fTp7eyAuVmFsdWVzLmltYWdlLnRhZyB9fSIKICAgICAgICBpbWFnZVB1bGxQb2xpY3k6IHt7IC5WYWx1ZXMuaW1hZ2UucHVsbFBvbGljeSB9fQogICAgICAgIHBvcnRzOgogICAgICAgIC0gY29udGFpbmVyUG9ydDoge3sgLlZhbHVlcy5zZXJ2aWNlLmludGVybmFsUG9ydCB9fQogICAgICAgIGxpdmVuZXNzUHJvYmU6CiAgICAgICAgICBodHRwR2V0OgogICAgICAgICAgICBwYXRoOiAvCiAgICAgICAgICAgIHBvcnQ6IHt7IC5WYWx1ZXMuc2VydmljZS5pbnRlcm5hbFBvcnQgfX0KICAgICAgICByZWFkaW5lc3NQcm9iZToKICAgICAgICAgIGh0dHBHZXQ6CiAgICAgICAgICAgIHBhdGg6IC8KICAgICAgICAgICAgcG9ydDoge3sgLlZhbHVlcy5zZXJ2aWNlLmludGVybmFsUG9ydCB9fQogICAgICAgIHJlc291cmNlczoKe3sgdG9ZYW1sIC5WYWx1ZXMucmVzb3VyY2VzIHwgaW5kZW50IDEyIH19Cg=="
        },
        {
          "name": "templates/service.yaml",
          "data": "YXBpVmVyc2lvbjogdjEKa2luZDogU2VydmljZQptZXRhZGF0YToKICBuYW1lOiB7eyB0ZW1wbGF0ZSAiZnVsbG5hbWUiIC4gfX0KICBsYWJlbHM6CiAgICBjaGFydDogInt7IC5DaGFydC5OYW1lIH19LXt7IC5DaGFydC5WZXJzaW9uIH19IgpzcGVjOgogIHR5cGU6IHt7IC5WYWx1ZXMuc2VydmljZS50eXBlIH19CiAgcG9ydHM6CiAgLSBwb3J0OiB7eyAuVmFsdWVzLnNlcnZpY2UuZXh0ZXJuYWxQb3J0IH19CiAgICB0YXJnZXRQb3J0OiB7eyAuVmFsdWVzLnNlcnZpY2UuaW50ZXJuYWxQb3J0IH19CiAgICBwcm90b2NvbDogVENQCiAgICBuYW1lOiB7eyAuVmFsdWVzLnNlcnZpY2UubmFtZSB9fQogIHNlbGVjdG9yOgogICAgYXBwOiB7eyB0ZW1wbGF0ZSAiZnVsbG5hbWUiIC4gfX0K"
        }
      ],
      "values": {
        "image": {
          "pullPolicy": "IfNotPresent",
          "repository": "nginx",
          "tag": "stable"
        },
        "replicaCount": 1,
        "resources": {
          "limits": {
            "cpu": "100m",
            "memory": "128Mi"
          },
          "requests": {
            "cpu": "100m",
            "memory": "128Mi"
          }
        },
        "service": {
          "externalPort": 80,
          "internalPort": 80,
          "name": "nginx",
          "type": "ClusterIP"
        }
      },
      "schema": null,
      "files": [
        {
          "name": ".helmignore",
          "data": "IyBQYXR0ZXJucyB0byBpZ25vcmUgd2hlbiBidWlsZGluZyBwYWNrYWdlcy4KIyBUaGlzIHN1cHBvcnRzIHNoZWxsIGdsb2IgbWF0Y2hpbmcsIHJlbGF0aXZlIHBhdGggbWF0Y2hpbmcsIGFuZAojIG5lZ2F0aW9uIChwcmVmaXhlZCB3aXRoICEpLiBPbmx5IG9uZSBwYXR0ZXJuIHBlciBsaW5lLgouRFNfU3RvcmUKIyBDb21tb24gVkNTIGRpcnMKLmdpdC8KLmdpdGlnbm9yZQouYnpyLwouYnpyaWdub3JlCi5oZy8KLmhnaWdub3JlCi5zdm4vCiMgQ29tbW9uIGJhY2t1cCBmaWxlcwoqLnN3cAoqLmJhawoqLnRtcAoqfgojIFZhcmlvdXMgSURFcwoucHJvamVjdAouaWRlYS8KKi50bXByb2oK"
        }
      ]
    },
    "manifest": "---\n# Source: mink/templates/service.yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: foo3-mink\n  labels:\n    chart: \"mink-0.1.0\"\nspec:\n  type: ClusterIP\n  ports:\n  - port: 80\n    targetPort: 80\n    protocol: TCP\n    name: nginx\n  selector:\n    app: foo3-mink\n---\n# Source: mink/templates/deployment.yaml\napiVersion: extensions/v1beta1\nkind: Deployment\nmetadata:\n  name: foo3-mink\n  labels:\n    chart: \"mink-0.1.0\"\nspec:\n  replicas: 1\n  template:\n    metadata:\n      labels:\n        app: foo3-mink\n    spec:\n      containers:\n      - name: mink\n        image: \"nginx:stable\"\n        imagePullPolicy: IfNotPresent\n        ports:\n        - containerPort: 80\n        livenessProbe:\n          httpGet:\n            path: /\n            port: 80\n        readinessProbe:\n          httpGet:\n            path: /\n            port: 80\n        resources:\n            limits:\n              cpu: 100m\n              memory: 128Mi\n            requests:\n              cpu: 100m\n              memory: 128Mi\n",
    "version": 1,
    "namespace": "foo"
  }
]
```

**Comment by mattfarina** [comment] 2020-02-07 21:12
Charts are a little like container images. The same chart can come from or be stored in multiple locations. The hash would be the same (that would be good to have in here).

What is your use case for this?

I wonder how we would handle having the same chart in twoor more repos/locations and then knowing which to list in here.

**Comment by sbose78** [comment] 2020-03-19 04:54
Thank you @mattfarina and sorry for the slow response: 

> What is your use case for this?


My use case is that:
- I have a helm service for listing/upgrading releases, which talks to the API server for doing helm operations.
- The service lists releases which may or may not have been installed using the helm service
- Now, I would like to support "upgrade to a newer version" even for charts whose repo url the service is not aware of ( because the helm service wasn't used to install the chart in the first place, the chart was probably installed from the CLI )

I was hoping the service could figure out which is the repo the chart came from, and then the service could look up if the a newer version of the chart is present in the repo.

> I wonder how we would handle having the same chart in twoor more repos/locations and then knowing which to list in here.

Even if multiple repos have the same chart, during installation, the chart tar would be pulled from any _one_  of those locations/repos, and therefore we could deterministically store that information in the release information in-cluster?

**Comment by technosophos** [comment] 2020-04-21 22:05
Helm does not assume that a direct URL to a chart is backed by a full repo. (In other words, Helm is totally cool with people passing a direct URL to a chart that is not in a repo.) So as things stand now, there is no mechanism to infer a repository from a URL.

**Comment by bacongobbler** [comment] 2020-09-14 15:37
duplicate of https://github.com/helm/helm/issues/4256.

**Closed by bacongobbler** 2020-09-14 15:37 UTC
Labels: question/support
