### ISSUE TITLE
[Helm 3] helm install --atomic deletes existing resources on failure

### ISSUE THREAD

**Issue by jlegrone** [helm/helm#6407] opened 2019-09-10 19:09 UTC
When `helm install --atomic` encounters an error, any resources that already existed in the cluster and conflict with resources which would be created by `helm install` are deleted during rollback. The `--atomic` argument should allow existing resources to be left intact instead of deleting them.

Output of `helm version`:

`version.BuildInfo{Version:"v3.0+unreleased", GitCommit:"d285097f58818533bb20eb8dff1cfb0a88e1878f", GitTreeState:"clean", GoVersion:"go1.12.9"}`

**Comment by hickeyma** [comment] 2019-09-18 13:45
@thomastaylor312 Is this the expected behaviour for `--atomic`?

**Comment by thomastaylor312** [comment] 2019-09-18 17:26
Nope, that is definitely a bug. Good catch on this @jlegrone. I'll take a look at the code when I am in there tomorrow working on porting some stuff

**Comment by bacongobbler** [comment] 2019-09-23 18:44
After pairing on this issue, @thomastaylor312 and I identified a bigger design issue. For `--atomic`, we just need `pkg/kube` to return the results of the install/upgrade - including what resources failed to create - then reconcile those resources.

However, there's a similar case where we want to reconcile a failed `helm install/upgrade`. Because Helm doesn't know the resources that Helm failed to create, a `helm delete` results in deleting all resources the release was tracking (see #3319).

It'd be great if we can identify a fix that addresses both issues at the same time.

**Comment by thomastaylor312** [comment] 2019-10-01 19:42
Closed in #6542

**Closed by thomastaylor312** 2019-10-01 19:42 UTC
Labels: bug, v3.x
