### ISSUE TITLE
Helm Rest Http API

### ISSUE THREAD

**Issue by phcollignon** [helm/helm#7057] opened 2019-11-22 21:42 UTC
Hello,

Helm has a CLI interface but a "Http REST" interface would also be useful for dynamic Chart installation from other kind  of clients.

I managed to get a simple example working (see below or [here](https://github.com/phcollignon/helm-httpapi/blob/master/cmd/helm/helm-api.go) ) but as functions like client.runInstall are private, I have to duplicate code .. and call client.Run

Also should be improved with features implemented in runInstall like locating chart, getting values, check dependencies .. also a registry configuration before... What about the XDG database ?

I can contribute if such a feature is implemented (but my go knowledge is very new ..)

```
func main() {

	router := httprouter.New()
	router.GET("/install/:chart/:name", install)
	log.Fatal(http.ListenAndServe(":8080", router))

}

func install(res http.ResponseWriter, req *http.Request, params httprouter.Params) {
	fmt.Println(path.Base(req.RequestURI))

	actionConfig := new(action.Configuration)
	if err := actionConfig.Init(settings.RESTClientGetter(), settings.Namespace(), os.Getenv("HELM_DRIVER"), debug); err != nil {
		json.NewEncoder(res).Encode(fmt.Sprint(err))
		return
	}

	client := action.NewInstall(actionConfig)

	chart, err := loader.Load(params.ByName("chart"))
	if err != nil {
		json.NewEncoder(res).Encode(fmt.Sprint(err))
	}

	vals := map[string]interface{}{
		"name": "value",
	}

	client.ReleaseName = params.ByName("name")
	release, err := client.Run(chart, vals)

	if err != nil {
		json.NewEncoder(res).Encode(fmt.Sprint(err))
	}
	if release != nil {
		json.NewEncoder(res).Encode(release)
	}

}
```

**Comment by bacongobbler** [comment] 2019-11-23 00:19
Closing as a duplicate of https://github.com/helm/helm/issues/6938. In the future, please make sure to search for existing issues before creating a new one. Thanks!

**Closed by bacongobbler** 2019-11-23 00:19 UTC
