### ISSUE TITLE
Using --wait suppresses debug logs

### ISSUE THREAD

**Issue by theangrydev** [helm/helm#3020] opened 2017-10-10 09:51 UTC
This makes it very hard to investigate what is going on with a bad helm upgrade

**Comment by thomastaylor312** [comment] 2017-10-11 00:24
@theangrydev Can you give a few more details? Helm and k8s versions, logs without and with `--wait`, etc. will all be helpful

**Comment by theangrydev** [comment] 2017-10-12 15:52
helm version:
```
Client: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.4.1", GitCommit:"46d9ea82e2c925186e1fc620a8320ce1314cbb02", GitTreeState:"clean"}
```

docker --version:
```
Docker version 1.12.6, build 78d1802
```

Logs with --wait and --debug:
```
[debug] Created tunnel using local port: '43762'

[debug] SERVER: "localhost:43762"

Error: UPGRADE FAILED: timed out waiting for the condition
```

Logs without --wait and with --debug:
```
REVISION: 17
RELEASED: Wed Oct 11 16:33:29 2017
CHART: chart-name
USER-SUPPLIED VALUES:
<snip>
COMPUTED VALUES:
<snip>
HOOKS:
MANIFEST:
<snip>
Release "chart-name" has been upgraded. Happy Helming!
```

This was happening when the deployed container was in a CrashLoopBackOff state.

**Comment by thomastaylor312** [comment] 2017-10-13 01:33
Ok, that is much clearer, thank you for the details!

**Comment by splisson** [comment] 2017-11-01 16:18
What error do you put in the helm upgrade to have it fail and reproduce the bug?

**Comment by theangrydev** [comment] 2017-11-21 11:02
The error could be e.g. an unknown host specified for the `spec.template.spec.containers.image` in a `kind: Deployment` which could lead to a `ImagePullBackOff` state. Alternatively, the application in the container itself could be misconfigured and crash, leading to a `CrashLoopBackOff` as the readiness/liveness probes fail to respond properly.

**Comment by splisson** [comment] 2018-01-31 21:55
Looking into the code: When using --wait and the update fails (timeout), the wait function returns an error code then Tiller does not return the Release in the response to the client which cannot log it. When not using wait, there is no error on Tiller side so the Release is returned in the response. I believe returning an error on timeout is intended and expected, so I'm not sure how to modify the code to allow an error and a response.

**Comment by jeremygaither** [comment] 2019-02-12 00:58
also see this lack of output on helm 2.8

**Comment by timm088** [comment] 2019-03-26 23:03
https://github.com/helm/helm/pull/5024 Should fix this, when /if it gets merged...

**Comment by bacongobbler** [comment] 2020-05-14 20:40
closing as inactive.

**Closed by bacongobbler** 2020-05-14 20:40 UTC
Labels: bug
