### ISSUE TITLE
Error: create: failed to create: Request entity too large: limit is 3145728

### ISSUE THREAD

**Issue by KubeLouis** [helm/helm#9284] opened 2021-01-27 02:45 UTC
helm version：v3.5.0
kubectl version：v1.16.6
Cloud Provider/Platfor：TKE Stack

I was using helm to deploy project as usual, but it returned 'Error: create: failed to create: Request entity too large: limit is 3145728', then I checked the logs, and I found that resources were not created and showed 404 status. here are the logs:

```
I0127 10:43:07.401485    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/serviceaccounts/che-keycloak 404 Not Found in 2 milliseconds
I0127 10:43:07.402953    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/serviceaccounts/che 404 Not Found in 1 milliseconds
I0127 10:43:07.403988    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/configmaps/che-devfile-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.405001    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/configmaps/che-plugin-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.405937    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/configmaps/che 404 Not Found in 0 milliseconds
I0127 10:43:07.406918    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/persistentvolumeclaims/keycloak-data 404 Not Found in 0 milliseconds
I0127 10:43:07.407878    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/persistentvolumeclaims/keycloak-log 404 Not Found in 0 milliseconds
I0127 10:43:07.408908    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/cide-che-clusterrole-binding 404 Not Found in 0 milliseconds
I0127 10:43:07.409910    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1/namespaces/cide/roles/che-endpoints-monitor 404 Not Found in 0 milliseconds
I0127 10:43:07.410891    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/rbac.authorization.k8s.io/v1beta1/namespaces/cide/rolebindings/cide-keycloak-role-binding 404 Not Found in 0 milliseconds
I0127 10:43:07.411804    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/services/devfile-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.412777    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/services/keycloak 404 Not Found in 0 milliseconds
I0127 10:43:07.413712    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/services/plugin-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.414702    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/services/che-dashboard 404 Not Found in 0 milliseconds
I0127 10:43:07.415627    8501 round_trippers.go:445] GET https://127.0.0.1:6443/api/v1/namespaces/cide/services/che-host 404 Not Found in 0 milliseconds
I0127 10:43:07.416600    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/apps/v1/namespaces/cide/deployments/devfile-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.417599    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/apps/v1/namespaces/cide/deployments/keycloak 404 Not Found in 0 milliseconds
I0127 10:43:07.418559    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/apps/v1/namespaces/cide/deployments/plugin-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.419522    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/apps/v1/namespaces/cide/deployments/che-dashboard 404 Not Found in 0 milliseconds
I0127 10:43:07.420405    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/apps/v1/namespaces/cide/deployments/che 404 Not Found in 0 milliseconds
I0127 10:43:07.421373    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/extensions/v1beta1/namespaces/cide/ingresses/devfile-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.422508    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/extensions/v1beta1/namespaces/cide/ingresses/keycloak-ingress 404 Not Found in 1 milliseconds
I0127 10:43:07.423473    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/extensions/v1beta1/namespaces/cide/ingresses/plugin-registry 404 Not Found in 0 milliseconds
I0127 10:43:07.424419    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/extensions/v1beta1/namespaces/cide/ingresses/che-dashboard-ingress 404 Not Found in 0 milliseconds
I0127 10:43:07.425380    8501 round_trippers.go:445] GET https://127.0.0.1:6443/apis/extensions/v1beta1/namespaces/cide/ingresses/che-ingress 404 Not Found in 0 milliseconds
I0127 10:43:07.937705    8501 round_trippers.go:445] POST https://127.0.0.1:6443/api/v1/namespaces/cide/secrets 413 Request Entity Too Large in 6 milliseconds
Error: create: failed to create: Request entity too large: limit is 3145728
```
I tried to deploy these charts in different servers and different platform (kind) and different helm version (v3.3.4) but they are the same, so it may be sth wrong with helm charts itself, but im not sure wt happened

**Comment by jdolitsky** [comment] 2021-01-27 21:26
The chart is likely too large, and maybe contains files you dont need. You can prevent them from being packaged using a `.helmignore` file (see docs here: https://helm.sh/docs/chart_template_guide/helm_ignore_file/)

Closing this as duplicate of https://github.com/helm/helm/issues/8281

**Closed by jdolitsky** 2021-01-27 21:26 UTC
