### ISSUE TITLE
helm upgrade --install works on windows but not on linux

### ISSUE THREAD

**Issue by Filipedguy** [helm/helm#5312] opened 2019-02-14 17:08 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.11", GitCommit:"1bfeeb6f212135a22dc787b73e1980e5bccef13d", GitTreeState:"clean", BuildDate:"2018-09-28T21:35:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
`AKS`

---

I'm trying to automate the ingress creation through a Azure DevOps pipeline. I'm trying to execute this command on the helm:

```
helm upgrade --namespace kube-system --install --set rbac.create=false,rbac.createRole=false,rbac.createClusterRole=false --wait ingress stable/nginx-ingress
```

In the Linux agent and in my Linux machine I get the same error:

```
Error: UPGRADE FAILED: Service "ingress-nginx-ingress-controller" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

But when I run the command from a Windows machine using the same client version, It works:

```
Release "ingress" has been upgraded. Happy Helming!
LAST DEPLOYED: Thu Feb 14 12:39:39 2019
NAMESPACE: kube-system
STATUS: DEPLOYED

...
```

Does anyone has the same error or another way of making this work?

**Comment by hickeyma** [comment] 2019-02-15 14:11
I wonder is it because of this bug with the chart: https://github.com/helm/charts/issues/9227

**Comment by bacongobbler** [comment] 2019-02-25 21:17
yeah, this looks like a duplicate of https://github.com/helm/charts/issues/9227 which was apparently fixed with https://github.com/helm/charts/pull/10993. Would you mind testing that out?

**Comment by bacongobbler** [comment] 2019-12-09 20:13
I'm going to close this ticket due to inactivity, but please re-open if this still needs to be addressed. Thanks!

**Closed by bacongobbler** 2019-12-09 20:13 UTC
Labels: question/support
