### ISSUE TITLE
Allow for setting dependency version and repo via --set and with values files

### ISSUE THREAD

**Issue by gmorse81** [helm/helm#3598] opened 2018-03-02 22:13 UTC
Hello, 

I am working on a CD project that is composed of a number of subcharts that are separate projects. When one of the subcharts gets a version bump, I'd like to update my umbrella chart to use that new version for testing in an automated fashion. 

Currently, there is no way to dynamically set the dependencies[x].version value that i can tell. 

First, i was wondering if there is a way to accomplish this with helm natively that I'm not finding in the docs. 
Second, if this is currently not possible, i would love to see a new feature where version numbers (and possibly the repo value) could by dynamically set via the `helm upgrade/install --set` option as well as  via a values file. 

Having it available through --set would allow for the CI server to deploy to test.  Having it available through a values file would allow an easy way for developers to change versions of dependencies locally (or default the local run to version 'x').

I appreciate any feedback on this matter. Thanks!

**Comment by gmorse81** [comment] 2018-03-02 22:19
As an additional note, i found this issue that went stale and closed. its seems pretty close to what i am suggesting here. #2205

**Comment by cmeury** [comment] 2018-03-22 20:48
Another use case I've just encountered: A public chart uses an old version as a dependency and you need to upgrade it. This forces me to copy the whole chart code instead of using requirements file.

**Comment by bacongobbler** [comment] 2020-05-14 21:08
duplicate of #2205.

**Closed by bacongobbler** 2020-05-14 21:08 UTC
Labels: feature
