### ISSUE TITLE
Helm doesn't validate pattern correctly

### ISSUE THREAD

**Issue by cwrau** [helm/helm#9651] opened 2021-04-27 09:43 UTC
Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Output of `kubectl version`:

Does not apply

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

Does not apply

Using the following `values.schema.json`, which can be validated on https://www.jsonschemavalidator.net, `helm lint .` fails

```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "properties": {
    "ip": {
      "type": "string",
      "pattern": "^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$"
    }
  }
}
```

Helms error message is;

```
pattern must be a valid regex
```

The pattern itself can be verified online; https://regexr.com/5rmoo

**Comment by bacongobbler** [comment] 2021-04-28 16:50
Helm utilizes https://github.com/xeipuuv/gojsonschema/ as the JSON Schema library used to load and validate JSON Schemas. If there are issues with loading and validating certain schemas, I would suggest opening tickets there.

https://github.com/xeipuuv/gojsonschema/issues/93 might be relevant to your issue, for example.

For reference, here is the extent of Helm's schema validation code: https://github.com/helm/helm/blob/43853ea772e779b617b011a8d4e69205636fa4f9/pkg/chartutil/jsonschema.go#L70-L73

**Comment by cwrau** [comment] 2021-04-28 17:41
Mh, that's unfortunate, especially because the other issue is so old

**Comment by cndoit18** [comment] 2021-05-12 02:30
xeipuuv/gojsonschema#232
This is the reason for the regular library, I think it is not a bug
If you use Golang's Standard Library, you will get an error.

``` golang
_, err := regexp.Compile("^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])(\\.(?!$)|$)){4}$")
// err.Error():
// error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

@bacongobbler what do you think

**Comment by bacongobbler** [comment] 2021-06-26 02:20
Please file tickets upstream. Once a fix has been applied we can fetch the fix in the next update with go.mod. Thanks!

**Closed by bacongobbler** 2021-06-26 02:20 UTC
Labels: bug
