### ISSUE TITLE
Have "helm uninstall" optionally also delete persistent volume claims

### ISSUE THREAD

**Issue by JaapHaitsma** [helm/helm#8644] opened 2020-08-23 19:38 UTC
I am quite new to helm and k8s but I found it very confusing. For example I would expect this to work
```
helm install my-release bitnami/wordpress
helm uninstall my-release
helm install my-release bitnami/wordpress
```
I would expect this to work but since the bitnami/wordpress chart has persistent volumes it does not. With the second helm install the pods go to a state of crashloopbackoff. What solves it is to manually delete the the persistent volumes after the helm uninstall. It would be good to have an option to also delete those with helm uninstall

**Comment by bacongobbler** [comment] 2020-08-23 23:33
Duplicate of #5156.

**Closed by bacongobbler** 2020-08-23 23:33 UTC
