### ISSUE TITLE
Helm upgrade with --install option

### ISSUE THREAD

**Issue by Yannig** [helm/helm#7843] opened 2020-03-31 09:52 UTC
Output of `helm version`:

    version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

I think all versions (confirmed on EKS/Kops/AKS/Minikube)

I'm using `helm upgrade` with the `--install` option to use the same command in any case to install or upgrade packages on my cluster (`helm upgrade --install`). in order not to create temporary files, I use the `-f` option followed by a dash (`-`). In this way, I pass the configuration directly through standard input.

The problem comes from the fact that at the initial installation, it seems that the command completely ignores this setting. At the first installation, the configuration of the chart is therefore always the default. Once the installation has taken place, following updates accept the passage of parameters.

I think the problem here is that the configuration options are readed twice when installing with the upgrade option.

**Comment by hickeyma** [comment] 2020-03-31 11:52
@Yannig I have been unable to reproduce this issue with the latest code in master. I tested as follows with a simple chart:

```console
$ cat prod.yaml 
drink: RedBull

$ cat chrt-7843/values.yaml 
drink: coffee

$ cat chrt-7843/templates/configmap.yaml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.drink }}

$ helm upgrade --install chrt-7843 chrt-7843/ -f prod.yaml 
Release "chrt-7843" does not exist. Installing it now.
NAME: chrt-7843
LAST DEPLOYED: Tue Mar 31 11:43:44 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$ helm get all chrt-7843
NAME: chrt-7843
LAST DEPLOYED: Tue Mar 31 11:43:44 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
drink: RedBull

COMPUTED VALUES:
drink: RedBull

HOOKS:
MANIFEST:
---
# Source: chrt-7843/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-7843-configmap
data:
  myvalue: "Hello World"
  drink: RedBull
```

Do you mind showing an example of the issue to get a better understanding of the problem?

**Comment by Yannig** [comment] 2020-03-31 14:10
Using your example, can you try to launch the helm deployment using the following command:

    cat prod.yaml | helm upgrade --install chrt-7843 chrt-7843/ -f -

**Comment by hickeyma** [comment] 2020-03-31 15:37
@Yannig Thanks for the update on the issue. I can reproduce it now:

```console
$ cat prod.yaml | helm3 upgrade --install chrt-7843-1 chrt-7843/  -f -
Release "chrt-7843-1" does not exist. Installing it now.
NAME: chrt-7843-1
LAST DEPLOYED: Tue Mar 31 15:36:20 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

$  helm get all chrt-7843-1
NAME: chrt-7843-1
LAST DEPLOYED: Tue Mar 31 15:36:20 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
null

COMPUTED VALUES:
drink: coffee

HOOKS:
MANIFEST:
---
# Source: chrt-7843/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrt-7843-1-configmap
data:
  myvalue: "Hello World"
  drink: coffee
```

**Comment by hickeyma** [comment] 2020-03-31 15:43
Duplicate of #7002

**Comment by hickeyma** [comment] 2020-03-31 15:44
@Yannig While digging around, I found that this issue was already opened. So, closing as a duplicate of #7002. You can add any extra comments to that issue.

**Closed by hickeyma** 2020-03-31 15:44 UTC
Labels: bug, v3.x

**Comment by Yannig** [comment] 2020-04-01 07:36
@hickeyma Thanks for your feedback.
I did a small PR to fix this issue. https://github.com/helm/helm/pull/7851
