### ISSUE TITLE
matched no packages

### ISSUE THREAD

**Issue by qiyongxiao** [helm/helm#6317] opened 2019-08-29 22:27 UTC
When I make on mips64 platform, I meet some errors:

```
##Installed glide
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>glide 
NAME:
   glide - Vendor Package Management for your Go projects.

##Check GOPATH
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>echo $GOPATH/src/k8s.io/helm
/Users/miyamoto/go/src/k8s.io/helm

##Checkout release
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>git checkout release-2.14 
Already on 'release-2.14'
Your branch is up to date with 'origin/release-2.14'.
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>make
GOBIN=/Users/miyamoto/go/src/k8s.io/helm/bin go install  -tags '' -ldflags '-w -s -X k8s.io/helm/pkg/version.Version=v2.14.3 -X k8s.io/helm/pkg/version.BuildMetadata= -X k8s.io/helm/pkg/version.GitCommit=0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085 -X k8s.io/helm/pkg/version.GitTreeState=dirty' k8s.io/helm/cmd/...
go: warning: "k8s.io/helm/cmd/..." matched no packages
```
I modified the makefile:
```
    GOBIN=$(BINDIR) $(GO) install $(GOFLAGS) -tags '$(TAGS)' -ldflags '$(LDFLAGS)' k8s.io/helm/cmd/helm 
    GOBIN=$(BINDIR) $(GO) install $(GOFLAGS) -tags '$(TAGS)' -ldflags '$(LDFLAGS)' k8s.io/helm/cmd/tiller 
    GOBIN=$(BINDIR) $(GO) install $(GOFLAGS) -tags '$(TAGS)' -ldflags '$(LDFLAGS)' k8s.io/helm/cmd/rudder
```
When excute make build,it shows:
```
.......
go: finding k8s.io/apimachinery v0.0.0
go: k8s.io/apimachinery@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/api v0.0.0
go: k8s.io/api@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/cli-runtime v0.0.0
go: k8s.io/cli-runtime@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/client-go v0.0.0
go: k8s.io/client-go@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/apiserver v0.0.0
go: finding k8s.io/csi-translation-lib v0.0.0
go: finding k8s.io/component-base v0.0.0
go: finding k8s.io/kube-scheduler v0.0.0
go: finding k8s.io/cloud-provider v0.0.0
go: finding k8s.io/kube-controller-manager v0.0.0
go: finding k8s.io/kube-aggregator v0.0.0
go: finding k8s.io/code-generator v0.0.0
go: finding k8s.io/legacy-cloud-providers v0.0.0
go: finding k8s.io/sample-apiserver v0.0.0
go: k8s.io/csi-translation-lib@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-scheduler@v0.0.0: unknown revision v0.0.0
go: k8s.io/legacy-cloud-providers@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/apiextensions-apiserver v0.0.0
go: k8s.io/apiextensions-apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/cloud-provider@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-controller-manager@v0.0.0: unknown revision v0.0.0
go: k8s.io/component-base@v0.0.0: unknown revision v0.0.0
go: k8s.io/code-generator@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/cluster-bootstrap v0.0.0
go: finding k8s.io/metrics v0.0.0
go: finding k8s.io/kubelet v0.0.0
go: finding k8s.io/kube-proxy v0.0.0
go: k8s.io/kube-aggregator@v0.0.0: unknown revision v0.0.0
go: finding k8s.io/cri-api v0.0.0
go: k8s.io/sample-apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/apiserver@v0.0.0: unknown revision v0.0.0
go: k8s.io/cluster-bootstrap@v0.0.0: unknown revision v0.0.0
go: k8s.io/kubelet@v0.0.0: unknown revision v0.0.0
go: k8s.io/kube-proxy@v0.0.0: unknown revision v0.0.0
go: k8s.io/cri-api@v0.0.0: unknown revision v0.0.0
go: k8s.io/metrics@v0.0.0: unknown revision v0.0.0
go: error loading module requirements
make: *** [build] Error 1
...............

###make build-cross
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>git checkout -b v2.14.3 -f
fatal: A branch named 'v2.14.3' already exists.
miyamoto@macbookpro:/Users/miyamoto/go/src/k8s.io/helm>>make build-cross    19-08-31 6:22
go get -u github.com/golang/dep/cmd/dep
go: finding github.com/golang/dep/cmd/dep latest
go: finding github.com/golang/dep/cmd latest
# github.com/golang/dep/gps
../../../pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
```
Please help me

**Comment by markmssd** [comment] 2019-09-01 04:08
Similar to my previous issue here: https://github.com/helm/helm/issues/6318

**Comment by bacongobbler** [comment] 2019-09-02 02:39
Dupe of #6318

**Closed by bacongobbler** 2019-09-02 02:39 UTC

**Comment by qiyongxiao** [comment] 2019-09-03 13:57
> 与我之前的问题类似：[＃6318](https://github.com/helm/helm/issues/6318)

I'm sorry. I am  not understand your issue

**Comment by bacongobbler** [comment] 2019-09-03 13:59
I'm sorry. That was slang for "this ticket is similar to #6318. Because it is a duplicate of that ticket, in closing this."

Does that make more sense?

**Comment by qiyongxiao** [comment] 2019-09-03 14:06
> I'm sorry. That was slang for "this ticket is similar to #6318. Because it is a duplicate of that ticket, I'm closing this."
> 
> Does that make more sense?

我用make bootstrap安装编译时需要的依赖包，在当前目录下有go.mod这个文件。这个用的应该就是使用go.mod模块安装吧
