### ISSUE TITLE
Helm 3 AWS ECR Image Pull Error

### ISSUE THREAD

**Issue by kavirajan2** [helm/helm#7080] opened 2019-11-26 07:52 UTC
Hi Team,

I have configured helm3 in my local system and using AWS EKS service. From Kubectl I am able to create pods using ECR images.

I have created a new chart and used the ECR repository as shown below. But image not pull from the ECR repository.
repository: 95398xxxxxxx.dkr.ecr.ap-southeast-1.amazonaws.com/apache:v1

![untitled](https://user-images.githubusercontent.com/5094964/69609439-8949d700-104f-11ea-8220-33c54ffd5bbe.png)

**Comment by karuppiah7890** [comment] 2019-11-26 14:48
This is more of a Kubernetes level issue. It's not a Helm bug. So we can close this

Regarding the issue - Please use `kubectl describe pod <podname>` to debug further using the events information.

**Comment by karuppiah7890** [comment] 2019-11-26 14:50
The issue is - for some reason, image is not valid / not being recognized / not pulled. Not sure why.

**Comment by bacongobbler** [comment] 2019-11-26 16:36
Please inspect why your pod has an invalid image name. There's nothing on our end here to resolve this ticket, so I'm closing it.

**Closed by bacongobbler** 2019-11-26 16:36 UTC

**Comment by kavirajan2** [comment] 2019-11-26 17:34
From helm 2 and kubectl I can able to deploy the pod from ECR. But from helm 3 I am not able to pull images.

**Comment by karuppiah7890** [comment] 2019-11-27 00:00
@kavirajan2 image name / pulling issue is surely a Kubernetes level issue. If helm v2 worked for you, but v3 doesn't, the cause for image issue could be helm only if some image name rendering issue happened while rendering templates with image name. 

The only way to verify this is - tell us the helm v2 version you used before and check the difference between the rendered templates for v2 and v3 and let us know if you find any difference for image name. Use helm template command to do the checking
