### ISSUE TITLE
Incorrect regex in linting error message

### ISSUE THREAD

**Issue by maximestevenot** [helm/helm#8876] opened 2020-10-12 16:32 UTC
The lint correctly identifies an invalid name because of uppercase in the name. Howevere, the error message is incorrect as it specifies the wrong regex expression. It should be `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`

```console
❯ helm lint mychart-3.0.0.tgz 
==> Linting mychart-3.0.0.tgz
[ERROR] templates/configmap.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/deployment.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253
[ERROR] templates/service.yaml: object name does not conform to Kubernetes naming requirements: "appName-v1": invalid metadata name, must match regex ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not longer than 253

Error: 1 chart(s) linted, 1 chart(s) failed
```
-----
Output of `helm version`: 
```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Output of `kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  EKS

**Comment by hickeyma** [comment] 2020-10-12 16:39
@maximestevenot Thanks for raising. This is a duplicate of #8596

**Comment by hickeyma** [comment] 2020-10-12 16:40
Closing as a duplicate. Please add any further comments to #8596.

**Comment by maximestevenot** [comment] 2020-10-12 19:02
Hi @hickeyma,

I've just cross-checked in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names) and indeed Kubernetes resource names must be lowed case.  

But as I mentioned in the description, the regex displayed in the error message matches with my resource name (look deeper the `A-Z`)

In this case, we were wrong about the resource name, the error is justified, the issue you mentioned as duplicate deals about warning instead of errors for this scenario. 

As a conclusion I rephrase the title of this issue as: **Incorrect regex in linting error message**

**Comment by hickeyma** [comment] 2020-10-13 07:35
@maximestevenot Thanks for the feedback. I understand the issue better now as initially it seemed that you had an issu with the lint result. I will re-open this and have pushed #8879 to fix it.

**Closed** 2020-11-02 12:27 UTC
Labels: bug
