### ISSUE TITLE
How can I tell what chart a release was installed from?

### ISSUE THREAD

**Issue by davidham** [helm/helm#7479] opened 2020-01-28 18:05 UTC
Output of `helm version`: 
`version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}`

Output of `kubectl version`:
```
Client Version: v1.15.3
Server Version: v1.13.12-eks-eb1860
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS EKS

If I installed `prometheus-operator`, for example, how would another developer be able to tell whether I installed from `stable` or `bitnami` or somewhere else?

**Comment by hickeyma** [comment] 2020-01-28 18:30
@davidham It could be garnered from the chart version if chart maintainer updates it when moving host repo.

@mattfarina @scottrigby @unguiculus Would this be practice for chart maintainers to update the chart version when moving to another host repo?

**Comment by davidham** [comment] 2020-01-28 18:49
I don't think that's true? Let's say I installed `prometheus-operator` from `stable` at version 0.34.0, and I check my values.yaml file into Github. Then another developer joins my team. How does he know, from looking at the output of `helm list`, which repo I got it from?

**Comment by bacongobbler** [comment] 2020-01-28 19:09
is this a duplicate of https://github.com/helm/helm/issues/6464?

**Comment by bacongobbler** [comment] 2020-01-28 19:14
yep, after taking a closer look, this is a duplicate request for #6464. Please feel free to chime in there and work on a PR once the design has been agreed upon. Thanks!

**Closed by bacongobbler** 2020-01-28 19:14 UTC
Labels: question/support
