### ISSUE TITLE
Error: Can't give argument to non-function .Values.admin.recovery

### ISSUE THREAD

**Issue by zodiac182** [helm/helm#8311] opened 2020-06-15 03:14 UTC
Output of `helm version`:
helm-v2.16.8

Output of `kubectl version`:
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openstack

Issue:
Get following error when installing my application with helm-v2.16.8, but no problem with helm-v2.16.7
`"Error: render error in \"cmdb/templates/admin-event-configmap.yaml\": template: cmdb/templates/admin-event-configmap.yaml:12:11: executing \"cmdb/templates/admin-event-configmap.yaml\" at <(.Values.admin.recovery) and contains \":\" .Values.admin.recovery>: can't give argument to non-function .Values.admin.recovery"
`

**Comment by P1ng-W1n** [comment] 2020-06-15 14:11
This is a result of the uplifted go version (1.14) in helm-v2.16.8. 
With that a [https://go-review.googlesource.com/c/go/+/217978/3/doc/go1.14.html#831] new checker has been introduced that could break previously working charts. 
In your case, the (.Values.admin.recovery) should not be in parentheses if I would have to guess.

**Comment by bacongobbler** [comment] 2020-06-15 14:47
duplicate of https://github.com/helm/helm/issues/7711.

**Closed by bacongobbler** 2020-06-15 14:47 UTC
