### ISSUE TITLE
On upgrade, removing a serviceAccount from a deployment template does not get applied to kubernetes deployment object

### ISSUE THREAD

**Issue by randude** [helm/helm#5473] opened 2019-03-19 07:10 UTC
I'm having similar issues that are displayed here:
https://github.com/helm/helm/issues/4429
However, this is a BUG and not a question. Helm breaks my deployment.

I installed a deployment which was added a serviceAccountName. Then when I tried to install a version that doesnt use the serviceAccountName, the pod couldn't load. 
What happened is that the serviceAccount was deleted as expected BUT the serviceAccountName was NOT removed from my deployment. So the pod couldnt load and my deployment was broken. 
I had to manually edit the deployment and remove the serviceAccountName entry. This solved the issue.
Can you please fix this? 
Thanks.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
On premise kubeadm -
kubeadm version -
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:35:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yaaragrad** [comment] 2019-03-19 07:19
What a terrible bug!
We have the same issue in our production environment.
We really need it to be fixed ASAP!

**Comment by hickeyma** [comment] 2019-03-19 13:43
@randude, would you be able to attach you deployment template and the changes you make for the upgrade?

**Comment by noamgu** [comment] 2019-03-20 07:16
+1

**Comment by randude** [comment] 2019-03-20 07:28
> @randude, would you be able to attach you deployment template and the changes you make for the upgrade?

This is basically the file without the more company specific volumes/secrets.
All we did is add the serviceAccountName and another yaml where the service account was . Once we installed the previous version which didnt have the serviceAccountName entry and the service account yaml, all hell broke lose. The pod didnt load as K8s was looking for the serviceaccount which was deleted by Helm.


{{- if .Values.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.global.namespace }}
{{- end -}}


{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels: 
    app: {{ .Values.global.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontline
spec: 
  minReadySeconds: 5
  strategy:
  # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
      release: {{ .Release.Name }}
  template: 
    metadata: 
      labels: 
        app: {{ .Values.global.name }}
        release: {{ .Release.Name }}
        tier: frontline
    spec:
      serviceAccountName: {{ .Values.serviceAccount}}
      containers:
      - name: xxx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
          name: xxx-port
          protocol: TCP
{{- end -}}

**Comment by randude** [comment] 2019-03-28 07:20
@hickeyma did you have some time to take a look at this?

**Comment by hickeyma** [comment] 2019-04-03 09:19
@randude Thanks for the details.

I have verified that this is a bug. It can be reproduced as follows:

1. Install a chart which contains deployment which references a service account. Easiest to add service account resources in the chart.
2. Upgrade the release where the deployment no longer references the service account and the service account has been removed (for example, remove the service account resource from the chart before upgrade). Need to pass `--recreate-pods` with `helm upgrade`.
3. The pod should terminate and fail to restart.

On upgrade, Helm recognises that the service account resource has been removed from the chart and subsequently calls Kubernetes API to remove the resource from the cluster. However, the issue here seems to be that Helm does not update the pod to no longer reference the service account. The pod will therefore fail (because it still references the service account which is now unavailable) when you force a restart.

**Comment by randude** [comment] 2019-04-03 09:29
@hickeyma  Do you know when will it be fixed?

**Comment by hickeyma** [comment] 2019-04-04 16:04
@randude Will let you know when I track down the cause.

**Comment by hickeyma** [comment] 2019-04-05 13:30
The reason for the issue is that when the `serviceAccountName` in the pod specification is modified and an upgrade is called, the upgrade does not update the deployed pod. Hence, the deployed pod still has the same specification which references the previous (or in this case, deleted) service account.

This is happening because when Helm does an upgrade, it uses the Kubernetes [Patch API](https://github.com/kubernetes/cli-runtime/blob/master/pkg/resource/helper.go#L141). However, the `serviceAccountName` [field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core) is not handled by patch, and therefore it thinks that no change has occurred and does not update the pod.

One way around this is to delete the pod and recreate it with the updated manifest.

**Comment by randude** [comment] 2019-04-05 14:17
@hickeyma I see. Seems like an exception eh. Would you say then that is a K8s issue and not Helm?

**Comment by bacongobbler** [comment] 2019-04-05 14:57
Yes.

**Comment by bacongobbler** [comment] 2019-04-05 15:32
Closing this as an upstream issue with cascading updates. Please open a new issue upstream with Kubernetes to determine what's the correct path forward when deleting a service account. Thanks!

**Closed by bacongobbler** 2019-04-05 15:32 UTC
Labels: question/support

**Comment by randude** [comment] 2019-04-10 06:47
@hickeyma 
FYI
https://github.com/kubernetes/kubernetes/issues/76367

**Comment by hickeyma** [comment] 2019-04-10 06:55
Thanks @randude
