### ISSUE TITLE
error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by papanito** [helm/helm#6376] opened 2019-09-06 14:34 UTC
I have a chart template which contains this line

```yaml
  {{- if eq $.Values.global.environment "dev" }}
```

When running `helm lint` this fails:

```bash
> helm lint my-services/
==> Linting my-services/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "my-services/templates/istio-gateway.yaml": template: acquiring-services/templates/istio-gateway.yaml:64:9: executing "my-services/templates/istio-gateway.yaml" at <eq $.Values.global.e...>: error calling eq: invalid type for comparison
```

Interestingly I have the same comparison  - just with another string - in line 8, which is not a problem at all. Removing the erronous line makes lint passing successfully

```bash
helm lint my-services/
==> Linting my-services/
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

Here the relevant `yaml`-file:

```yaml
kind: VirtualService
metadata:
  name: acquiring-gateway-virtualservice
  namespace: {{ default $.Release.Namespace }}
spec:
  hosts:
  {{- if eq $.Release.Namespace $.Values.global.defaultNamespace }}
  {{- if eq $.Values.global.environment "prd" }}
  - {{ $.Values.global.ingressName }}.{{$.Values.global.environment}}.sc.intra
  {{- else }}
  - {{ $.Values.global.ingressName }}.svc.{{$.Values.global.environment}}.sc.intra
  {{- end }}
  {{- else }}
  - {{ $.Values.global.ingressName }}-{{ default $.Release.Namespace }}.svc.{{$.Values.global.environment}}.sc.intra
  {{- end }}
  gateways:
  - acquiring-gateway
  http:
  - match:
    - uri:
        prefix: /uaa

        prefix: /uaa/
    route:
    - destination:
        port:
          number: 80
        host: auth-server.{{ $.Release.Namespace }}.svc.cluster.local
    corsPolicy:
      allowOrigin:
      - '*'
      allowMethods:
      - OPTIONS
        - GET
        - PUT
        - POST
        - PATCH
      allowHeaders:
      - authorization

  {{- if eq $.Values.global.environment "dev" }}
  - match:
```

Also following the suggestion under [#2979](https://github.com/helm/helm/issues/2979) does not help

Output of `helm version`:

```json
Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}
```

Output of `kubectl version`:

N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

On-Premise

**Comment by bacongobbler** [comment] 2019-09-06 15:28
When `global.environment` is unset, it is set to the `nil` value. A string and a `nil` value are incompatible types and therefore cannot be compared for equality.

What you probably want is the following:

```
{{- if eq (default $.Values.global.environment "prod") "dev" }}
```

That way if `global.environment` is unset, it is still being compared against a default value.

If values are considered "optional", the chart should check and determine if the value is unset first.

Does that help?

**Comment by papanito** [comment] 2019-09-07 08:25
@bacongobbler helps partly. I see the point, however why the comparison with the same string value is fine in one line and fails in another?

**Comment by bacongobbler** [comment] 2019-09-07 15:08
My assumption of text/template's evaluation logic would be that If the first `if` statement is evaluated as false then the branch is short-circuited.

**Comment by papanito** [comment] 2019-09-09 07:30
Well, if I do this

```yaml
    #{{- if eq $.Release.Namespace $.Values.global.defaultNamespace }}
    {{- if eq $.Values.global.environment "prd" }}
    - {{ $.Values.global.ingressName }}.{{$.Values.global.environment}}.sc.intra
    {{- else }}
    - {{ $.Values.global.ingressName }}.svc.{{$.Values.global.environment}}.sc.intra
    {{- end }}
    #{{- else }}
    #- {{ $.Values.global.ingressName }}-{{ default $.Release.Namespace }}.svc.{{$.Values.global.environment}}.sc.intra
    #{{- end }}
```
lint does not complain.

**Comment by technosophos** [comment] 2020-05-01 22:13
Did `helm template` also complain? I am also curious whether this can still be reproduced now that we are compiling with Go 1.14, as this is almost 100% certainly an issue with the Go `text/template` way of evaluating a conditional.

If we can get it down to a minimal reproducible case, I might be able to track it further. And this is far more interesting if `lint` fails but `template` does not.

**Comment by bclouser** [comment] 2020-08-13 19:54
For what it's worth. I am seeing what i believe to be the exact same issue:
`Error: UPGRADE FAILED: template: ota-tdx/templates/kong-consumers.yaml:30:44: executing "ota-tdx/templates/kong-consumers.yaml" at <eq .Values.app.configMap.DEMO_MODE "1">: error calling eq: incompatible types for comparison`

My helm template
```
{{- if and (.Values.app.configMap.DEMO_MODE) (eq .Values.app.configMap.DEMO_MODE "1") }}
```
Helm version
```
version.BuildInfo{Version:"v3.3.0", GitCommit:"8a4aeec08d67a7b84472007529e8097ec3742105", GitTreeState:"dirty", GoVersion:"go1.14.7"}
```
Workaround (SUPER UGLY NESTED!!!! :sob:  )
```diff
-{{- if (.Values.app.configMap.DEMO_MODE) and eq .Values.app.configMap.DEMO_MODE "1" }}
+{{- if .Values.app.configMap.DEMO_MODE }}
+{{- if eq .Values.app.configMap.DEMO_MODE "1" }}
...
-{{- end }}
+{{- end }}
+{{- end }}
```

**Comment by phillycheeze** [comment] 2020-11-05 20:30
@bclouser I ran into this as well. Looks like Helm (or Go I assume) doesn't have short circuiting available. The single line `if` statement combined with `and` would work in most languages, but I'm unsure if it's Helm or Go at fault here.

**Comment by bacongobbler** [comment] 2020-11-05 20:33
This would be a restriction set in place with `text/template`, which is the template language used by Helm to render templates. So this would be a limitation set by the Go developers.

https://golang.org/pkg/text/template/

**Comment by bacongobbler** [comment] 2020-11-05 20:57
Closing as this is something we cannot change... Rather this is a design decision made by the Go authors. I suggested [a workaround](https://github.com/helm/helm/issues/6376#issuecomment-528900695) which is about all we can do at this point. If others have found other solutions, please post them here. Thanks!

**Closed by bacongobbler** 2020-11-05 20:57 UTC
Labels: question/support

**Comment by phillycheeze** [comment] 2020-11-05 21:28
Thanks for the link @bacongobbler.

Indeed the excerpt from the documentation for `and` reads:

```
Returns the boolean AND of its arguments by returning the
	first empty argument or the last argument, that is,
	"and x y" behaves as "if x then y else x". All the
	arguments are evaluated.
```

I can confirm the workaround of `if eq (default <.variable> <fallback_value>) <comparison_value>` works.

**Comment by sabi0** [comment] 2021-01-07 16:27
The recommended workaround is wrong as far as I can see. `default` accepts the fallback value as the first argument, not the second:
> One function frequently used in templates is the `default` function: `default DEFAULT_VALUE GIVEN_VALUE`.

https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function

I.e. it should be:
```
{{- if eq (default "prod" $.Values.global.environment) "dev" }}
```
and not:
```
{{- if eq (default $.Values.global.environment "prod") "dev" }}
```

Another (more intuitive) syntax is:
```
{{- if eq ($.Values.global.environment | default "prod") "dev" }}
```

P.S. I do not understand how the `if eq (default <.variable> <fallback_value>) <comparison_value>` option could possibly work in the @phillycheeze 's test.

**Comment by KeithTt** [comment] 2021-04-28 06:58
This reply saved me: 

> You are comparing "string" with a variable .Values.favorite.drink of some unknown type. How about casting that variable to string ?
> 
> `{{if eq (.Values.favorite.drink | toString) "coffee"}}`

https://github.com/helm/helm/issues/2979#issuecomment-681015535

**Comment by alam0rt** [comment] 2021-05-17 01:58
I had a fun one where running  `helm lint ...` would cause a failure on a comparison between what was normally 2 int64s

```
{{- if ge .Values.deployment.replicaCount 2 -}}
```

`helm lint` was making `replicaCount` nil, so to fix, we need another nested if (sadface) to check if it's the right type.

```
{{- if kindIs "int64" .Values.deployment.replicaCount -}}
{{- if ge .Values.deployment.replicaCount 2 -}}
```

**Comment by rehevkor5** [comment] 2022-09-29 15:06
Would be nice if this was mentioned in the docs. This situation makes it rather mysterious to do things like support both `"true"` and `true` in values (eg. for backward compatibility).

**Comment by ferm10n** [comment] 2024-08-12 23:43
For me the issue was caused by a subchart so I couldn't implement the mentioned workaround.

For future people hitting this issue, upgrade helm. Pre helm v3.8.0, `{{ eq nil "some text" }}` will cause `error calling eq: incompatible types for comparison`. Future versions don't have a problem. Couldn't find what changed in the release notes.
