### ISSUE TITLE
helm template `int value` makes `0` in 2.15

### ISSUE THREAD

**Issue by kimxogus** [helm/helm#6735] opened 2019-10-22 01:42 UTC
Output of `helm version`: both `2.15.0` in client(from homebrew) and server, I immediately rollbacked to 2.14.3 to recover deploy failure, I can't get 2.15 again and run `helm version`. sorry

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): aws with kops

I was trying to update my helm chart [redis-ha](https://github.com/helm/charts/tree/master/stable/redis-ha) with 2.15.0 and I found that there are no announce services generated even there is `.Values.replicas` as 3 (https://github.com/helm/charts/blob/master/stable/redis-ha/templates/redis-ha-announce-service.yaml).
While investigating this issue, I found that helm 2.15 translates `{{ int .Values.replicas }}` as `0` even `.Values.replicas` is `3` https://github.com/helm/charts/blob/master/stable/redis-ha/templates/redis-ha-announce-service.yaml#L2 .
You can reproduce this issue with
1. checkout https://github.com/helm/charts
2. add following code at the top of `stable/redis-ha/templates/redis-ha-announce-service.yaml`
```
{{ .Values.replicas }}
{{ int .Values.replicas }}
```
3. `helm template ./stable/redis-ha -x templates/redis-ha-announce-service.yaml`
4. Templating output will show
```
3
0
```

**Comment by bacongobbler** [comment] 2019-10-22 01:59
Dupe of #6708.

**Closed by bacongobbler** 2019-10-22 01:59 UTC
