### ISSUE TITLE
Consider types in yaml when rendering charts

### ISSUE THREAD

**Issue by jan25** [helm/helm#5929] opened 2019-06-23 08:43 UTC
Helm render uses `yaml.Unmarshal` to read yaml files, and then we manually traverse the yaml structure to convert to `chartutil.Values` which is of type `map[string]interface{}`. So any float64 values in yaml will be stringified as is without looking at their types.

PR https://github.com/helm/helm/pull/5928 breaks a test to reproduce this issue.

This issue manifested from https://github.com/bookingcom/shipper/issues/102

Previously reported issue https://github.com/helm/helm/issues/1707 tried to address the issue in values passed via cli, it solved through patching the cli values parser, I think.

**Comment by karuppiah7890** [comment] 2019-06-23 11:17
Check https://github.com/helm/helm/issues/5768 . I think this can be closed. I also commented in https://github.com/bookingcom/shipper/issues/102 about a similar solution

**Comment by jan25** [comment] 2019-06-24 10:56
@karuppiah7890 hey thanks!
I still think this is a bug we should fix and not stringify unmarshalled values as is. Lets wait for one of members to comment

**Comment by hickeyma** [comment] 2019-06-24 16:25
Hey @bacongobbler, you might be best to respond as you have provided an insight in #1707.

**Comment by bacongobbler** [comment] 2019-06-24 16:41
Yeah, given this is the same point being made in #1707 I think this is a duplicate of the same issue.

As @technosophos mentioned in #1707, during the conversions to and from JSON done by `ghodss/yaml`, integers are being cast into float64s to represent Javascript's numeric type. This is causing all integers above a certain value to be represented in scientific notation.

Closing as a duplicate.

**Closed by bacongobbler** 2019-06-24 16:41 UTC
Labels: question/support
