### ISSUE TITLE
how to label namespace with helm

### ISSUE THREAD

**Issue by wukaiying** [helm/helm#6828] opened 2019-10-30 08:36 UTC
Here is my case:
1.if namespace does not exist, using helm to create the namespace and label it.
2.if namespace does exist, using helm label the namespace.

Here is my ns.yaml 
![image](https://user-images.githubusercontent.com/7676297/67841691-9dbfb000-fb33-11e9-9734-c7bed0a2c63f.png)

When i try to use helm install, if the target namespace do not exist, helm will create the namesapce and label it. But, when the target namespace already exist,helm install will show this error
`Error: release eskort-webhook failed: namespaces "test" already exists`.
I find a workaround :https://gist.github.com/kvudata/12ba57ae1e7f01799aaa7f36350a9b2e
Does helm have a commod like `kubectl apply`?

Output of `helm version`:
Client: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.1", GitCommit:"5270352a09c7e8b6e8c9593002a73535276507c0", GitTreeState:"clean"}
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:53:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by bacongobbler** [comment] 2019-10-30 19:09
duplicate of https://github.com/helm/helm/issues/4178.

**Closed by bacongobbler** 2019-10-30 19:09 UTC
