### ISSUE TITLE
Helm 3 template throwing error

### ISSUE THREAD

**Issue by anusreePrakash** [helm/helm#6267] opened 2019-08-22 12:54 UTC
Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0-alpha.2", GitCommit:"97e7461e41455e58d89b4d7d192fed5352001d44", GitTreeState:"clean", GoVersion:"go1.12.7"}
```

Issue: this issue is related to https://github.com/helm/helm/issues/6116

```
$ helm template issue-6116 --namespace default --set "dashboards.clustersmonitoringjson.select[0][0].params[0]=status" --set "dashboards.clustersmonitoringjson.select[0][0].type=field" --debug

printer.go:84: [debug] Original chart version: ""
printer.go:84: [debug] CHART PATH: /Users/anusree/projects/helm-issues/issue-6116

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
helm.sh/helm/pkg/strvals.(*parser).listItem(0xc0007dbaf8, 0xc0003a8ae0, 0x1, 0x1, 0x0, 0x0, 0x5b, 0x0, 0x0, 0xc0007db520)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:246 +0xcc0
helm.sh/helm/pkg/strvals.(*parser).listItem(0xc0007dbaf8, 0xc0003a8ae0, 0x1, 0x1, 0x0, 0x1, 0xc00000005b, 0x0, 0x0, 0x0)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:240 +0x3e9
helm.sh/helm/pkg/strvals.(*parser).key(0xc0007dbaf8, 0xc0001f29c0, 0xc0007db810, 0x16)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:140 +0xa9e
helm.sh/helm/pkg/strvals.(*parser).key(0xc0007dbaf8, 0xc0001f2960, 0xc0007db9a0, 0xa)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:174 +0x1a7
helm.sh/helm/pkg/strvals.(*parser).key(0xc0007dbaf8, 0xc0001f28d0, 0x30, 0x2354fa0)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:174 +0x1a7
helm.sh/helm/pkg/strvals.(*parser).parse(0xc0007dbaf8, 0xc0001f2c00, 0x39)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:96 +0x38
helm.sh/helm/pkg/strvals.ParseInto(0x7ffeefbff6e2, 0x39, 0xc0001f28d0, 0x0, 0x0)
	/go/src/helm.sh/helm/pkg/strvals/parser.go:70 +0xcc
helm.sh/helm/pkg/action.(*ValueOptions).MergeValues(0xc0004b4a90, 0xc0001d33a0, 0x14, 0x7ffeefbff68e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
	/go/src/helm.sh/helm/pkg/action/install.go:716 +0x25e
main.runInstall(0xc00067e300, 0x1, 0x8, 0xc0004b4a00, 0x27106c0, 0xc0000c6000, 0x249ffd5, 0x4, 0x11aabb0)
	/go/src/helm.sh/helm/cmd/helm/install.go:174 +0x28e
main.newTemplateCmd.func1(0xc00047d400, 0xc00067e300, 0x1, 0x8, 0x0, 0x0)
	/go/src/helm.sh/helm/cmd/helm/template.go:53 +0xb5
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00047d400, 0xc00067e200, 0x8, 0x8, 0xc00047d400, 0xc00067e200)
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762 +0x465
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00041b180, 0x2710600, 0xc0000c6000, 0xc0000c8010)
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850 +0x2fc
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/helm.sh/helm/cmd/helm/helm.go:75 +0xd2
```

**Comment by bacongobbler** [comment] 2019-10-30 20:51
closing as a duplicate of #6116 so we can keep the conversation going on in the same ticket. Thanks!

**Closed by bacongobbler** 2019-10-30 20:51 UTC
Labels: bug, v3.x
