### ISSUE TITLE
support the helm command can be directly imported externall

### ISSUE THREAD

**Issue by xcbeyond** [helm/helm#10788] opened 2022-03-18 16:01 UTC
To enable external programs to directly manage helm commands, it is recommended that function [newRootCmd](https://github.com/helm/helm/blob/974a6030c8514591ab0b0f0c898d37f816f698f6/cmd/helm/root.go#L86) be exposed, which can be modified to `NewRootCmd`.

**Comment by bacongobbler** [comment] 2022-03-21 14:48
duplicate of https://github.com/helm/helm/pull/10412.

**Closed by bacongobbler** 2022-03-21 14:48 UTC
