### ISSUE TITLE
helm 3.0.0-beta4: ca-file does not work for helm repo add/update

### ISSUE THREAD

**Issue by pkoehlers** [helm/helm#6635] opened 2019-10-10 15:32 UTC
We are using an internal helm repository with a certificate signed by our internal company CA.
When using this repository in helm 3.0.0-beta4 I get this x509 error:

```
$ helm repo add name https://repourl --ca-file /path/to/ca.pem
Error: looks like "https://repourl" is not a valid chart repository or cannot be reached: Get https://repourl/index.yaml: x509: certificate signed by unknown authority
```

The same happens when I migrate my existing helm v2 repository config and call `helm repo update`.

Executing the exact same commands in helm v2.14.3 with the same repository configuration and same ca.pem file is working fine.

Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.0-beta.4", GitCommit:"7ffc879f137bd3a69eea53349b01f05e3d1d2385", GitTreeState:"dirty", GoVersion:"go1.13.1"}
```

**Comment by chipzoller** [comment] 2019-10-17 14:51
+1 on this. Exact same sequence works in helm2 but not helm3-beta4. `--ca-file` appears to not be passed.

**Comment by chipzoller** [comment] 2019-10-24 18:34
Is this addressed in beta 5?

**Comment by bacongobbler** [comment] 2019-10-24 18:37
Feel free to check, but not that I'm aware, no. Feel like taking a crack at fixing it?

**Comment by karuppiah7890** [comment] 2019-10-25 17:12
I'm taking a look at this. Starting with reproducing the issue. Will post updates 😄

**Comment by karuppiah7890** [comment] 2019-10-25 17:38
I'm able to reproduce the issue using [`mkcert`](https://github.com/FiloSottile/mkcert) and a local chart repository hosted with [`serve`](https://www.npmjs.com/package/serve). Digging into it now

**Comment by karuppiah7890** [comment] 2019-10-26 05:24
Okay, I found the issue. Yes, CA file input is not being used. Reason - 

When we create http client using this
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/httpgetter.go#L77

we don't give it options. The flow is, 
there's ca file value here - 
https://github.com/helm/helm/blob/4d6a2461f394f171d871e4680b4dfd439c97961e/cmd/helm/repo_add.go#L122

then we create a chart repo struct 
https://github.com/helm/helm/blob/4d6a2461f394f171d871e4680b4dfd439c97961e/cmd/helm/repo_add.go#L125

in which we create a simple http client
https://github.com/helm/helm/blob/704133ddd540eb9c3a49f973d4c00fc12910eb34/pkg/repo/chartrepo.go#L66
while creating http client, we don't pass any options
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/getter.go#L114

the constructor is here
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/getter.go#L122

the constructor does have code to support cert file and related things when given options
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/httpgetter.go#L83

but there's still a bug in the if condition as it checks only for cert (public key) and key (private key) file, it should check for ca file too
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/httpgetter.go#L83

in helm 2 it's there
https://github.com/helm/helm/blob/6b5ab08a61d73980ca6f84ccdb3f6b996d950cae/pkg/getter/httpgetter.go#L88

back to helm3,
we do pass tls config actually, over here while downloading
https://github.com/helm/helm/blob/704133ddd540eb9c3a49f973d4c00fc12910eb34/pkg/repo/chartrepo.go#L124

but the problem is, while downloading, the `get` method uses the options for username and stuff over here
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/httpgetter.go#L58

but there's no code to use the options like ca file, which will be basically the duplicate of whatever code is here
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/httpgetter.go#L84

I was first wondering what can be done, as I can see multiple ways to fix this. In helm2, we actually create the http client with all the configs
https://github.com/helm/helm/blob/519ccac2949695ad54a8f8b159b353b998462e03/pkg/repo/chartrepo.go#L66

this way, we don't have to pass it every time we do a `Get`. Also, I felt `get` should still work as it's ca file etc options are set similar to username, password (basic auth) options, but we would be changing the http client's transport field during the `Get`. Actually, if I think about it now, if we change the transport field during `Get`, it's a mutation that will affect anyone else using the client later. 

Now what do we do? Should we create http client with tls config already? or just change in `Get` based on options

In any case, I think `ByScheme` should support taking options
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/getter.go#L111

as `Constructor` does take options
https://github.com/helm/helm/blob/9bc7934f350233fa72a11d2d29065aa78ab62792/pkg/getter/getter.go#L84

so it can be just passed through

@bacongobbler what do you think is a good approach?

**Comment by bacongobbler** [comment] 2019-10-31 22:25
FYI I have a PR ready for this issue. I'm just unable to submit a PR at this time due to spurious HTTP 500 internal errors from GitHub when opening a PR against helm/helm.

In the meantime, here's the development branch if anyone wants to take a look and give it a spin: https://github.com/bacongobbler/helm/tree/fix-6635

**Comment by karuppiah7890** [comment] 2019-11-01 02:09
Oh. Cool. I was planning to work on it 🙈 Anyways, I'll take a look at the code 👍

**Comment by pkoehlers** [comment] 2019-11-07 11:09
Thanks for taking a look at this and sorry for just reviewing it now (I'm not a go dev and have no go env set up...).

Unfortunately, it looks like my use case is still not working in the newest release, containing your PR.

The behaviour is exactly the same as in my first post.

Output of ```helm version```
```
version.BuildInfo{Version:"v3.0.0-rc.3", GitCommit:"2ed206799b451830c68bff30af2a52879b8b937a", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

**Comment by bacongobbler** [comment] 2019-11-07 17:49
You need to provide both a CA file as well as the key file for the TLS certs to be passed along:

https://github.com/helm/helm/blob/43acbfe86d2228134a5f3478e97cae433ca33fb2/pkg/getter/httpgetter.go#L92

So, at a minimum, you need to pass along `--cert-file` and `--key-file` for the TLS options to be propagated. Perhaps there's a use case here we can improve upon.

Demoting from a bug to a question/support as the original issue has been fixed. This now looks to be a usability question.

**Comment by karuppiah7890** [comment] 2019-11-07 18:11
I'm actually not sure about what the `--cert-file` and `--key-file` is for. I mean, I'm assuming `key` means private key, and `cert` means public key. And I'm assuming these are related to the repo endpoint. Public key of the endpoint can be obtained by hitting the https endpoint. We usually cannot obtain the private key, and usually need not obtain as a client.

I think here, the user is trying to pass `--ca-file`, the Certificate Authority's (CA) public key, to verify if the public key (ssl cert) of the repo endpoint is valid, as it's possible that the ssl certificate was signed by a CA who's not trusted by the system. For example, an internal CA.

In helm 2, the code is like this : 

https://github.com/helm/helm/blob/6b5ab08a61d73980ca6f84ccdb3f6b996d950cae/pkg/getter/httpgetter.go#L88

It looks for (cert and key file) or CA file. May be we need to do the same here? @bacongobbler

**Comment by bacongobbler** [comment] 2019-11-07 18:23
Yes.

**Comment by pkoehlers** [comment] 2019-11-08 12:56
> I think here, the user is trying to pass `--ca-file`, the Certificate Authority's (CA) public key, to verify if the public key (ssl cert) of the repo endpoint is valid, as it's possible that the ssl certificate was signed by a CA who's not trusted by the system. For example, an internal CA.

This is exactly what I am trying to do. I don't have access to the private key for that cert.

So I would really appreciate the suggested change for that condition.

**Comment by chipzoller** [comment] 2019-11-08 13:12
Yes, without this working flag, a custom chart repo cannot be added. The private key is not needed.

**Comment by bacongobbler** [comment] 2019-11-08 15:34
see #6913.

**Closed** 2019-11-12 16:18 UTC
Labels: question/support, v3.x

**Comment by pkoehlers** [comment] 2019-11-13 08:14
works as expected in rc4, thanks.

**Comment by johnnyjeannatasha** [comment] 2023-08-08 14:56
$ helm repo add name https://repourl --ca-file /path/to/ca.pem
Error: looks like "https://repourl" is not a valid chart repository or cannot be reached: Get https://repourl/index.yaml: x509: certificate signed by unknown authority
