### ISSUE TITLE
<nil> string values

### ISSUE THREAD

**Issue by gillesdemey** [helm/helm#5049] opened 2018-12-12 12:04 UTC
We've seem to have encountered either a regression in `v2.12.0` or at least some behaviour that was recently changed.

Our values file contains the following:
```yaml
some_key: 
```

And we're using those values in our environment variables:
```yaml
env:
  - name: SOME_KEY
    value: {{ .Values.some_key | quote }}
```

In `v2.11.0` this would evaluate to:

```yaml
              - name: SOME_KEY
                value:
```

In `v2.12.0` however it shows the following diff if we upgrade our helm deployments:

```diff
              - name: SOME_KEY
-               value:
+               value: "<nil>"
```

This is causing quite a few  of our deployments to fail since we're trying to pass the string `"<nil>"` as a configuration option instead of an empty string value.

Is this a bug or a new feature where empty values are interpreted as `<nil>`?

Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
```
Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.18", GitCommit:"5796233393d7bc034428de15191ad3d2eaff95fb", GitTreeState:"clean", BuildDate:"2018-11-08T20:49:08Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by mortent** [comment] 2018-12-17 04:06
I am able to reproduce this. The cause looks to be a change in how nil values are handled in the text/template package between version 1.10 and 1.11 of golang. Building Helm 2.11 with go 1.10 results in `value:`, but building Helm 2.11 with go 1.11 results in `value: "<nil>"`.
I'm working on a fix.

**Comment by mortent** [comment] 2018-12-18 05:17
This is caused by a change in Go 1.11, where untyped nil values are now passed in to template functions when using the text/template package as described [here](https://golang.org/doc/go1.11#text/template). Unfortunately, some of the template functions in the sprig library are not expecting nil values and that is why you are seeing the `"<nil>"` output.

I think this needs to be fixed in sprig, and I have a PR that at least addresses this for some of the string functions https://github.com/Masterminds/sprig/pull/133.

**Comment by AnatolyRugalev** [comment] 2018-12-20 09:54
Does anyone came up with workaround for this? Downgrade is a bad option for us. Thanks

**Comment by okgolove** [comment] 2019-01-11 12:47
Same problem.

**Comment by hickeyma** [comment] 2019-02-25 17:32
@gillesdemey Can you test if this is now fixed? @mortent provided a fix https://github.com/Masterminds/sprig/pull/133, which was pulled into Helm via #5300.

**Comment by bacongobbler** [comment] 2019-02-25 17:37
I think we can safely close this issue for now as this issue was referenced directly in the report. Please re-open if this persists. Thanks!

**Closed by bacongobbler** 2019-02-25 17:37 UTC
Labels: bug
