### ISSUE TITLE
UPGRADE FAILED: rendered manifests contain a new resource that already exists

### ISSUE THREAD

**Issue by fr0der1c** [helm/helm#7697] opened 2020-02-27 16:29 UTC
I have a release of stable/wordpress which is deployed by Helm 2. Earlier I followed the instructions to migrate to Helm 3. Now I want to make some changes in values.yaml and apply it to the release as I always do in the time of helm 2, but I run into: 

`Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: default, name: [deployment name], existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment`

I'm confused. I tried to search this error message on Google and got the idea that "if the Kind is changed, it cannot be automatically upgraded". But I'm using the exactly the same version of Chart so there shouldn't be any difference. Also, from the error message the `existing_kind` and `new_kind` are the same.

My command is : `helm upgrade [release name] stable/wordpress --version 8.1.1 -f values.yaml`

Output of `helm version`: version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.3-tke.9", GitCommit:"0a5b3103ef7653b37fdff6fc19a72a509e5f2698", GitTreeState:"clean", BuildDate:"2020-01-07T02:21:33Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.3-tke.9", GitCommit:"0a5b3103ef7653b37fdff6fc19a72a509e5f2698", GitTreeState:"clean", BuildDate:"2020-01-07T02:21:45Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  Tencent Cloud

Is this a bug or I missed some information? I'm not a Kubernetes expert but I'll try to solve if I can get some clue. Thanks.

**Comment by mattfarina** [comment] 2020-02-27 17:05
I have a couple questions that might help us all find out what's going on.
* What version of the chart were you running before the upgrade and which version after? This sounds like it could be a problem moving from `apps/vibeta2` to `apps/v1` and some information would help track that down.
* Can you share what you change in the values?

**Comment by fr0der1c** [comment] 2020-02-28 01:56
The deployed chart version is 8.1.1. I'm using `helm upgrade [release name] stable/wordpress --version 8.1.1 -f values.yaml` so I think all the Chart manifest should be exactly the same. 

Also, the error message `existing resource conflict: namespace: default, name: [deployment name], existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment` says the existing kind is the same as new kind. So I think this is not a problem moving from `apps/v1beta2` to `apps/v1`.

I only changed the `ingress` part. Added a few domains to the `ingress.hosts` and `ingress.tls`. Also added some rewrite rule to `ingress.annotations`.

**Comment by vinayus** [comment] 2020-02-28 05:45
I'm seeing the same issues as well.

Adding a note is that, for same set of charts if there is clusterrole or any rolebinding included then they are not deleted during chart deletion.

**Comment by americans007** [comment] 2020-02-28 07:13
+1 to the problem:
╰─ helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Release "travel-front" does not exist. Installing it now.
+ helm upgrade travel-front --install --namespace dev --force --atomic --timeout 120s -f helm/dev/values.yaml --set image.tag=3.0.65.262-SNAPSHOT --set image.repository=my.reg.local/travel-front goharbor/allinone
Release "travel-front" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: dev, name: travel-front, existing_kind: /v1, Kind=ConfigMap, new_kind: /v1, Kind=ConfigMap
```

**Comment by fr0der1c** [comment] 2020-02-29 12:47
@mattfarina Hi. It looks like a common issue. Is there anything we can do to solve this?

**Comment by nvanheuverzwijn** [comment] 2020-03-06 22:02
I have this exact same issue.
If you change the apiVersion of a kind say Deployment, helm won't be able to change it because it will "already exists". If you deploy a chart with a Deployment on apiVersion "apps/v1beta2" and then, you update the chart to change the apiVersion to "apps/v1", you will get this exact bug.

**Comment by fr0der1c** [comment] 2020-03-07 01:31
> I have this exact same issue.

Actually it is different. In my case, I even didn't change the apiVersion. I tried to upgrade from apps/v1 Deployment to apps/v1 Deployment and failed.

**Comment by teoincontatto** [comment] 2020-03-11 23:25
Same issue here, and seems reproducible:

``` 
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: xxx, name: yyy, existing_kind: /v1, Kind=Secret, new_kind: /v1, Kind=Secret
```

**Comment by teoincontatto** [comment] 2020-03-12 10:54
A possible workaround is to play with including or removing `--reuse-values`, depending on some helm internal state that seems to make the upgrade working.

**Comment by zeroisme** [comment] 2020-03-18 08:19
I have this exact same issue. 
```
# helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}

Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: dev01, name: xxx-deployment, existing_kind: apps/v1beta2, Kind=Deployment, new_kind: apps/v1beta2, Kind=Deployment
```

**Comment by teoincontatto** [comment] 2020-03-18 10:12
After more digging in issues, posts and documentation seems like a normal behavior of helm.

When helm upgrade create a resource that did not existed between the resources created by the previous revision of the chart release and a resource with same kind, namespace and name exists in kubernetes then this error is thrown.

In my case I had a secret with a certificate that could be passed using values or created by a job. This secret was then created directly by helm or indirectly by the job. If the chart was installed and the secret was created indirectly with the job helm saw that as not included in the resources created by the chart. Later when the secret was added as part of the chart by an upgrade helm throw the error. The solution was to create the secret always and make the job patch it.

**Comment by archonic** [comment] 2020-03-26 00:30
I've hit this error without changing my deploy script or any charts. I thought it might be related to a gcloud component upgrade but I downgraded and I'm still getting the same error. I have no idea how my helm app got into this state and I'm also not sure how to remedy it. I believe I could delete the ingress (the resource it's complaining about) and re-run the script, but I would want to be sure of that since it would cause production downtime. Any hints would be appreciated @teoincontatto.

**Comment by kristoflemmens** [comment] 2020-03-27 14:20
Hi,

We have the same problem when upgrading the stable/sysdig chart. in version 1.7.6 there is a change of apiVersion: rbac.authorization.k8s.io/v1beta1 to apiVersion: rbac.authorization.k8s.io/v1.
We get this message:
> Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: , name: sysdig, existing_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole, new_kind: rbac.authorization.k8s.io/v1, Kind=ClusterRole

Helm version: 3.1.2

**Comment by teoincontatto** [comment] 2020-03-27 16:10
@archonic The only approach I know is to actually delete the existing resource that is referenced in the error and upgrade.

Maybe some core maintainer (@bacongobbler?) can point out if a `--overwrite-existing-resource <kind>:<namespace>:<name>` parameter or something like that can be implemented or if there is some existing workaround to this problem.

**Comment by archonic** [comment] 2020-03-27 20:44
I was actually wrong about not changing the apiVersion. I didn't do it deliberately but this was in my ingress yaml:
```
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```
Upgrading my gcloud components ended up upgrading my kubectl gitversion and downgrading did not downgrade my kubectl gitversion. I commented out the if statement there and the deploy worked. I'll delete the ingress and recreate it when I can afford the downtime.

**Comment by framled** [comment] 2020-03-30 16:23
I have the same issue, I change the apiVersion of istio virtualService and get the same issue.

The only approach is like @teoincontatto says, delete the pods and deploy again.

**Comment by Jeskz0rd** [comment] 2020-04-07 23:13
I'm facing the same issue mentioned by @framled while updating istio objects. Noticed that behaviour with different objects, VirtualService, Policies, AuthorizaitonPolicies.

```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists.
Unable to continue with update: existing resource conflict: namespace: jeskz0rd,
name: jeskz0rd-dotnet-test, existing_kind: security.istio.io/v1beta1, Kind=AuthorizationPolicy, 
new_kind: security.istio.io/v1beta1, Kind=AuthorizationPolicy
```

As a workaround, I have to delete the deployed chart (`helm delete -n`...) and redeploy it right after. When I clean up the deployed chart (that shows the error above) then I don't face this issue anymore. 

I couldn't find any evidence that helps even enabling debug mode. Helm template shows the expected yaml as the result, no changes if I compare the deployed objects and those "new" generated by the template that I aim to deploy.

**Comment by KOSSOKO** [comment] 2020-04-14 12:26
So what is the actual workaround ?

**Comment by bacongobbler** [comment] 2020-04-14 13:54
Closing as a duplicate of #7219.

**Closed by bacongobbler** 2020-04-14 13:54 UTC
Labels: question/support

**Comment by teoincontatto** [comment] 2020-04-14 15:48
IMHO #7219 does not seems to be a duplicate of this issue.

Also IMHO #7649 seems to be a valid solution to this issue.

**Comment by bacongobbler** [comment] 2020-04-14 16:10
Apologies, you are right. @fr0der1c's issue in the OP has been solved with #7649.

The issue described in https://github.com/helm/helm/issues/7697#issuecomment-595984123 is a duplicate of #7219.

Once Helm 3.2.0 has been merged, attach the following annotations to any resource you wish to adopt into the release:

```
KIND=deployment
NAME=my-app-staging
RELEASE=staging
NAMESPACE=default
kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm
```

Once #2730 is implemented, the process to adopt existing resources into a release will be drastically simpler.

In any case, it looks like this has been resolved and this issue can now be closed.

**Comment by ryaneorth** [comment] 2020-04-22 23:01
@bacongobbler - Perhaps I'm misunderstanding, but I'm not seeing the annotations added in the following scenario:

1. Original release performed using Helm < 3.2.0
2. Update (via `helm upgrade --install` ) the release is made using Helm 3.2.0

In this scenario, I do not see the annotations added automatically. Is this expected behavior? Or do we have to manually annotate all resources that were originally created via a release prior to Helm 3.2.0?

**Comment by casey-robertson** [comment] 2020-06-17 19:23
> Apologies, you are right. @fr0der1c's issue in the OP has been solved with #7649.
> 
> The issue described in [#7697 (comment)](https://github.com/helm/helm/issues/7697#issuecomment-595984123) is a duplicate of #7219.
> 
> Once Helm 3.2.0 has been released, attach the following annotations to any resource you wish to adopt into the release:
> 
> ```
> KIND=deployment
> NAME=my-app-staging
> RELEASE=staging
> NAMESPACE=default
> kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
> kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
> kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm
> ```
> 
> Note that these annotations and labels are attached to all resources after Helm 3.2.0. This workaround is necessary for those deploying resources with older versions of Helm.
> 
> Once #2730 is implemented, the process to adopt existing resources into a release will be drastically simpler.
> 
> In any case, it looks like this has been resolved and this issue can now be closed.

Doesn't seem to be working for me.  Updated our helm deploy container to use 3.2.3 and added the annotations to the offending deployment.  Same error.

**Comment by Jeskz0rd** [comment] 2020-06-17 19:52
> > Apologies, you are right. @fr0der1c's issue in the OP has been solved with #7649.
> > The issue described in [#7697 (comment)](https://github.com/helm/helm/issues/7697#issuecomment-595984123) is a duplicate of #7219.
> > Once Helm 3.2.0 has been released, attach the following annotations to any resource you wish to adopt into the release:
> > ```
> > KIND=deployment
> > NAME=my-app-staging
> > RELEASE=staging
> > NAMESPACE=default
> > kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
> > kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
> > kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm
> > ```
> > 
> > 
> > Note that these annotations and labels are attached to all resources after Helm 3.2.0. This workaround is necessary for those deploying resources with older versions of Helm.
> > Once #2730 is implemented, the process to adopt existing resources into a release will be drastically simpler.
> > In any case, it looks like this has been resolved and this issue can now be closed.
> 
> Doesn't seem to be working for me. Updated our helm deploy container to use 3.2.3 and added the annotations to the offending deployment. Same error.

I can confirm this behaviour too.

**Comment by djg2018** [comment] 2020-07-15 19:00
i've got the same issue while deploying Istio. So i did 
"kubectl get clusterrole "
"kubectl get clusterrolebinging "
kubectl delete mutatingwebhookconfiguration istio-sidecar-injector
kubectl delete validatingwebhookconfiguration istio-galley
kubectl delete namespace <istio-namespace>
  and when deleted all and started, it working

**Comment by Jeskz0rd** [comment] 2020-08-17 14:42
> > > Apologies, you are right. @fr0der1c's issue in the OP has been solved with #7649.
> > > The issue described in [#7697 (comment)](https://github.com/helm/helm/issues/7697#issuecomment-595984123) is a duplicate of #7219.
> > > Once Helm 3.2.0 has been released, attach the following annotations to any resource you wish to adopt into the release:
> > > ```
> > > KIND=deployment
> > > NAME=my-app-staging
> > > RELEASE=staging
> > > NAMESPACE=default
> > > kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
> > > kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
> > > kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm
> > > ```
> > > 
> > > 
> > > Note that these annotations and labels are attached to all resources after Helm 3.2.0. This workaround is necessary for those deploying resources with older versions of Helm.
> > > Once #2730 is implemented, the process to adopt existing resources into a release will be drastically simpler.
> > > In any case, it looks like this has been resolved and this issue can now be closed.
> > 
> > 
> > Doesn't seem to be working for me. Updated our helm deploy container to use 3.2.3 and added the annotations to the offending deployment. Same error.
> 
> I can confirm this behaviour too.

Hey @bacongobbler , I can confirm the same issue with helm 3.3.0 👍

**Comment by sjdweb** [comment] 2020-10-02 22:00
Workaround does not work for me either, still results in:

```
upgrade failed: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: default, name: debug-apiupgrade, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
```

I am getting this specifically when switching from `apiVersion: extensions/v1beta1` to `apiVersion: apps/v1` on a Deployment. Is the only way to upgrade before 1.16 to delete these deployments?

**Comment by hickeyma** [comment] 2020-10-05 09:29
@sjdweb Might be worth looking at https://helm.sh/docs/topics/kubernetes_apis/

**Comment by nvanheuverzwijn** [comment] 2020-10-05 14:09
@hickeyma This _really_ _*really*_ works well.

**Comment by sjdweb** [comment] 2020-10-05 17:03
Thanks @hickeyma upgrading the release manually referencing the existing chart with new apiVersions worked, it seems the issue is probably with FluxCD using an older version of Helm under the hood.

**Comment by lucascicco** [comment] 2022-08-15 19:08
> ```
> kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm
> ```

It worked like a charm, 

thanks xD
