### ISSUE TITLE
docs.helm.sh Sidebar Does Not Scroll

### ISSUE THREAD

**Issue by caleblloyd** [helm/helm#4428] opened 2018-08-03 14:03 UTC
The Sidebar does not scroll on the Docs site.  Can't navigate to any help item that is off-screen.  Happening on both Firefox and Chrome on Ubuntu 18.04.

Firefox 61.0.1 on Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/2414837/43646932-2dd4fee2-9704-11e8-8061-6ce1e3bebe9c.png)

Chrome 67.0.3396.99 on Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/2414837/43646960-4451db2c-9704-11e8-9115-9aa50781f93d.png)

**Comment by bacongobbler** [comment] 2018-08-03 14:27
Dupe of https://github.com/helm/helm-www/issues/130

**Closed by bacongobbler** 2018-08-03 14:27 UTC
