### ISSUE TITLE
The required function fails when lookup field is more than 1 level deep

### ISSUE THREAD

**Issue by samirshaik** [helm/helm#8716] opened 2020-09-10 22:03 UTC
Output of `helm version`:
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-08-01T23:56:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openshift 3.11

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  name: {{ required "this value is required" .Values.configmap.name }}
```

If we use the required function as shown in above example, helm 3 throws following exception when required field is more than 1 level deep. Note that we have intentionally not provided the value for the required field in values.yaml to assert that required function works. Instead of ".Values.configmap.name", if we declare ".Values.name" it returns expected error that the value is required.

`Error: template: first-chart/templates/configmap.yaml:6:52: executing "first-chart/templates/configmap.yaml" at <.Values.configmap.name>: nil pointer evaluating interface {}.name`

**Comment by bacongobbler** [comment] 2020-09-15 17:27
This is a duplicate of https://github.com/helm/helm/issues/8026.

**Closed by bacongobbler** 2020-09-15 17:27 UTC
Labels: question/support
