### ISSUE TITLE
Proposal: Option to mask credentials on generated YAML secrets when debug enabled

### ISSUE THREAD

**Issue by bibliobeam** [helm/helm#7705] opened 2020-02-28 16:18 UTC
Output with debug flag prints as expected. Generated YAML shows secrets with crednetials. There sohlud be an option to disable the credentials display and still take advantage of debug feature.

Output of `helm version`:
v3.0.1
Output of `kubectl version`:
v1.16.6
Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
Openstack

**Comment by jdolitsky** [comment] 2020-02-28 20:28
@bibliobeam thanks for opening - can you suggest how you'd like this implemented? (i.e. name of flag, or just does this by default, etc)

**Comment by bacongobbler** [comment] 2020-02-28 22:17
Duplicate of https://github.com/helm/helm/issues/7275.

**Closed by bacongobbler** 2020-02-28 22:17 UTC
Labels: proposal

**Comment by bibliobeam** [comment] 2020-03-01 18:16
#7275 already has a backward compatible solution, of adding an additional flag "sanitize", proposed for a similar issue. I'll look at contributing the fix as part of that issue.
