### ISSUE TITLE
helm does not reliably detect the completion of jobs/pods

### ISSUE THREAD

**Issue by tsuna** [helm/helm#8999] opened 2020-11-08 11:27 UTC
Output of `helm version`:
on Linux:
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```
on macOS (install via `brew`):
```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```
(issue is platform independent)

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

We have various helm charts that are upgraded regularly as part of our CD pipeline and that use job/pod pre/post install hooks. Helm waits for these pods/jobs to complete but often does not seem to see them complete, causing the upgrade to time out. We've seen an increasing number of spurious timeouts ever since upgrading to k8s 1.16.x although I believe the issue was already there in 1.14.x and earlier.

Here's a typical example:

```
$ helm3 upgrade --install --wait --debug --timeout 15m --kube-context xxx foo <chart> --namespace=xxx -f values.yaml
history.go:53: [debug] getting history for release foo
show.go:173: [debug] Original chart version: ""
upgrade.go:121: [debug] preparing upgrade for foo
coalesce.go:199: warning: destination for peer_clusters is a table. Ignoring non-table value <nil>
upgrade.go:129: [debug] performing update for foo
upgrade.go:301: [debug] creating upgraded release for foo
client.go:255: [debug] Starting delete for "foo-init" Job
client.go:284: [debug] jobs.batch "foo-init" not found
client.go:109: [debug] creating 1 resource(s)
client.go:464: [debug] Watching for changes to Job foo-init with timeout of 15m0s
client.go:492: [debug] Add/Modify event for foo-init: ADDED
client.go:531: [debug] foo-init: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:492: [debug] Add/Modify event for foo-init: MODIFIED
client.go:531: [debug] foo-init: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
upgrade.go:360: [debug] warning: Upgrade "foo" failed: pre-upgrade hooks failed: timed out waiting for the condition
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
helm.go:81: [debug] pre-upgrade hooks failed: timed out waiting for the condition
UPGRADE FAILED
main.newUpgradeCmd.func2
	/private/tmp/helm-20201027-30538-ndhvcx/cmd/helm/upgrade.go:156
github.com/spf13/cobra.(*Command).execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/private/tmp/helm-20201027-30538-ndhvcx/cmd/helm/helm.go:80
runtime.main
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/proc.go:204
runtime.goexit
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/asm_amd64.s:1374
```

So here the upgrade started this `foo-init` job, which allegedly timed out after 15 minutes. Yet the job completed in 3 seconds. Here's the output of `kubectl --context=xxx -n xxx get po -w` with timestamps added:

```
Nov 08 02:49:25,066 foo-init-xrf9j                               0/2     Pending     0          0s
Nov 08 02:49:25,086 foo-init-xrf9j                               0/2     Pending     0          0s
Nov 08 02:49:25,157 foo-init-xrf9j                               0/2     Init:0/1    0          0s
Nov 08 02:49:26,069 foo-init-xrf9j                               0/2     Init:0/1    0          1s
Nov 08 02:49:27,026 foo-init-xrf9j                               0/2     PodInitializing   0          1s
Nov 08 02:49:27,978 foo-init-xrf9j                               1/2     Running           0          2s
Nov 08 02:49:29,010 foo-init-xrf9j                               0/2     Completed         0          3s
```

We have seen so many cases of this, and the issue is to easily reproduced now with k8s 1.16 that I am convinced there is a bug in Helm. We even hacked the code in `pkg/kube/client.go` (see aristanetworks/helm@bc4fa156cf1df9ad617aefff0ac05e283639e7af) to poll the k8s apiserver instead of using a watch, and this made the problem reliably go away. You'll see that our hack only kicks in when `if kind == "Job"` and we recently added a post upgrade hook in one of our charts that's a `Pod` instead, and boom the problem is back reliably. So I can create a fork of the release 3.4 branch and port our patch over there and change our hack to kick in regardless of whether `kind` is `Job` or `Pod`, but we may as well just figure out what the bug is and fix it once and for all.

**Comment by tsuna** [comment] 2020-11-08 11:39
Just wanted to add that the issue isn't specific to helm3, we had it with helm2 as well. With helm2 we could pass `--debug -v 9` and get the super verbose logs from the k8s client but I don't know how to get those with helm3. The logs would show typically a watch firing upon completion of the job, just like in the output above helm3 logs `Add/Modify event for foo-init: MODIFIED` when the first pod in the job completes (happens simultaneously with to the line `1/2     Running` from the `kubectl` pod watch output) but it doesn't react when the job completes (at least not reliably, sometimes it does work, but more often than not it doesn't).

**Comment by mattfarina** [comment] 2020-11-09 11:52
Is this the same issue as #5948? There is a PR in for it at #8363.

**Comment by bacongobbler** [comment] 2020-11-12 18:30
ping

**Comment by bacongobbler** [comment] 2020-12-01 18:05
Closing with the assumption that this is a duplicate of #5948. Thanks for hunting that down @mattfarina.

**Closed by bacongobbler** 2020-12-01 18:05 UTC
