### ISSUE TITLE
helm install does not print resources installed

### ISSUE THREAD

**Issue by moficodes** [helm/helm#7565] opened 2020-02-09 21:14 UTC
Output of `helm version`:
```
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10+IKS", GitCommit:"18e8565daf60eb3a20c0ac29a7d3a93622659e4d", GitTreeState:"clean", BuildDate:"2020-01-16T04:08:27Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
IKS

In all the docs where I see helm installed I see it shows the resources that was installed. For some reason when I do
```
helm install bee-helm .
```

 ```
NAME: bee-helm
LAST DEPLOYED: Sun Feb  9 16:12:17 2020
NAMESPACE: bee-travels
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing bee-travels.

Your release is named bee-helm.

To learn more about the release, try:

  $ helm status bee-helm
```

The package is situated in 

https://github.com/bee-travels/config/tree/master/helm/bee-travels

Not sure if I am missing anything.

**Comment by hickeyma** [comment] 2020-02-10 09:07
@moficodes Thanks for raising this.

It seems that showing the state of resources was removed in Helm 3. Refer to https://github.com/helm/helm/issues/5952#issuecomment-542786862 for nan explanation and #5952 for more details and background on this.

In the meantime, you can get the resources by:

- Running `helm get manifest <release> | kubectl get -f -` OR
- Using plugin: https://github.com/marckhouzam/helm-fullstatus

**Comment by bacongobbler** [comment] 2020-02-20 07:35
closing as a duplicate of #5952 so we can track the discussion in a single ticket. Thanks!

**Closed by bacongobbler** 2020-02-20 07:35 UTC
Labels: question/support
