### ISSUE TITLE
can't read repositories.yaml when add a repo

### ISSUE THREAD

**Issue by 474846718** [helm/helm#6770] opened 2019-10-24 03:10 UTC
C:\Users\Administrator>helm repo add jenkins-x https://storage.googleapis.com/chartmuseum.jenkins-x.io
Error: read C:\Users\Administrator\.helm\repository\repositories.yaml: The process cannot access the file because another process has locked a portion of the file.

My OS is win10. I do it after helm init and before that I didn't do any thing.
So what's go wrong?

**Comment by bacongobbler** [comment] 2019-10-24 06:36
Can you please share your version of Helm?

**Comment by zak13362** [comment] 2019-10-24 17:13
Mine is
Client: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

I also have this issue. I saw that you fixed the flock bug with the dangling file lock. Not sure if it's in there yet.

**Comment by bacongobbler** [comment] 2019-10-24 17:37
Weird... This was fixed in #6692 and #6694, but the patch for #6694 is not present in either 2.15.0 or 2.15.1.

https://github.com/helm/helm/blob/v2.15.0/cmd/helm/repo_add.go#L139
https://github.com/helm/helm/blob/v2.15.1/cmd/helm/repo_add.go#L139

It is present in the `dev-v2` branch, however.

https://github.com/helm/helm/blob/0a9bf4f966726f0bb0faa6a82db29909abe16126/cmd/helm/repo_add.go#L143

This fix will be released in 2.15.2. Sorry about that!

**Comment by bacongobbler** [comment] 2019-10-24 19:13
closing as a duplicate of #6682.

**Closed by bacongobbler** 2019-10-24 19:13 UTC
Labels: question/support
