### ISSUE TITLE
Valid v3.2.4 chart broken after v3.3.1 - can't give argument to non-function empty

### ISSUE THREAD

**Issue by myuseridbws** [helm/helm#9796] opened 2021-06-11 17:13 UTC
Output of `helm version`:

> helm324 version:
> ```sh
> version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
> ```
> 
> helm331 version:
> ```sh
> version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
> ```
>
> helm360 version:
> ```sh
> version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
> ```

Output of `kubectl version`:

```sh
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS

### Summary
I have a chart that has been working fine with v3.2.4 and I am trying to upgrade to later versions of helm (tested 3.3.1 & 3.6.0), but the chart is failing when I run the following command:

```sh
helm install ./test-chart -g -n foobar -f ./custom-values.yaml --dry-run --debug
```
with the following output:
**v3.3.1:**
`Error: template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType`
`helm.go:94: [debug] template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType
`

**v3.6.0:**
`Error: template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType`
`helm.go:81: [debug] template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType`

The output that I get when I run using **v3.2.4** is the following:
```sh
NAME: test-chart-1623430114
LAST DEPLOYED: Fri Jun 11 19:48:36 2021
NAMESPACE: foobar
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: test-chart/templates/configmap.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: test-chart-1623430114-0
  data:
    foo1.yaml: |-
      foo1x: foo1-xValue
      foo1y: foo1-yValue
    bar1.yaml: |-
      bar1x: bar1-xValue
      bar1y: bar1-yValue
- apiVersion: v1
  kind: Secret
  metadata:
    name: test-chart-1623430114-1
  data:
    foo2.yaml: Zm9vMng6IGZvbzIteFZhbHVlCmZvbzJ5OiBmb28yLXlWYWx1ZQ==
    bar2.yaml: YmFyMng6IGJhcjIteFZhbHVlCmJhcjJ5OiBiYXIyLXlWYWx1ZQ==
```

_NOTE:  My original chart is much larger.  I have pared it down to the minimum configuration that still reproduces the problem._

### Chart Source Files
**Chart.yaml:**
```sh
apiVersion: v2
name: test-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
```
**templates/configmap.yaml:**
```sh
{{- $releaseName := .Release.Name -}}
{{- $values := .Values -}}
{{- $configVars := $values.aaa.bbb -}}
{{- if $configVars }}
apiVersion: v1
kind: List
items:
{{- range $index, $configObj := $configVars }}
{{- $configMapName := ( default ( printf "%s-%d" $releaseName $index ) $configObj.bindingRef ) }}
- apiVersion: v1
{{- if or ( ( empty $configObj.bindingType ) ( eq $configObj.bindingType "configmap" ) ) }}
  kind: ConfigMap
{{- else }}
  kind: Secret
{{- end }}
  metadata:
    name: {{ $configMapName }}
  data:
  {{- $helmDataVars := ( $configObj.ccc ) }}
  {{- if not ( empty $helmDataVars ) }}
  {{- range $dataVarIdx, $dataVarObj := $helmDataVars }}
  {{- $dataVarObjName := $dataVarObj.name }}
  {{- $helmDataType := ( default "yaml" $dataVarObj.dataType ) }}
  {{- $helmDataVarData := (index $values $dataVarObjName) }}
{{- if or ( ( empty $configObj.bindingType ) ( eq $configObj.bindingType "configmap" ) ) }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: |-
{{ toYaml $helmDataVarData | indent 6 }}
{{- else }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: {{ toYaml $helmDataVarData | b64enc }}
{{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
```

**values.yaml:**
```sh
---
aaa:
  bbb:
```

### Custom Values YAML file from helm command line

**custom-values.yaml:**
```sh
---
aaa:
  bbb:
    -
      ccc:
        -
          description: "My foo1 description"
          name: foo1
        -
          description: "My bar1 description"
          name: bar1
    -
      bindingType: Secret
      ccc:
        -
          description: "My foo2 description"
          name: foo2
        -
          description: "My bar2 description"
          name: bar2

foo1:
  foo1x: foo1-xValue
  foo1y: foo1-yValue

bar1:
  bar1x: bar1-xValue
  bar1y: bar1-yValue

foo2:
  foo2x: foo2-xValue
  foo2y: foo2-yValue

bar2:
  bar2x: bar2-xValue
  bar2y: bar2-yValue
```

**Comment by bacongobbler** [comment] 2021-06-11 18:02
More recent versions of Go now error out when a non-function is provided arguments. See the explanation in https://github.com/helm/helm/issues/9424#issuecomment-791805455 and https://github.com/helm/helm/issues/7711#issuecomment-593113347 for more details. It is possible that you have a syntax error causing something to pass an argument to `empty $configObj.bindingType` as the error suggests.

Duplicate of #9424.

**Closed by bacongobbler** 2021-06-11 18:02 UTC

**Comment by adamreese** [comment] 2021-06-11 18:03
I can't seem to replicate the issue.

```
~gosrc/helm.sh/helm/_scratch/issues/9796 tags/v3.2.4
❯ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.16.4"}

~gosrc/helm.sh/helm/_scratch/issues/9796 tags/v3.2.4
❯ helm install ./test-chart -g -n foobar -f ./custom-values.yaml --dry-run --debug
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: /Users/areese/p/go/src/helm.sh/helm/_scratch/issues/9796/test-chart

Error: template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType
helm.go:84: [debug] template: test-chart/templates/configmap.yaml:11:12: executing "test-chart/templates/configmap.yaml" at <(empty $configObj.bindingType) (eq $configObj.bindingType "configmap")>: can't give argument to non-function empty $configObj.bindingType
```

**Comment by adamreese** [comment] 2021-06-11 18:05
@bacongobbler beat me to it.  I had the same result because I built from the same go version

**Comment by myuseridbws** [comment] 2021-06-11 22:46
@bacongobbler & @adamreese - Thank you so much for reviewing and responding so quickly to my submission.

Respectfully (and at the risk of being 'that guy' who opens his first ever Github issue only to make a fool of himself), I don't believe my issue is completely the same as the cited duplication (  https://github.com/helm/helm/issues/9424  ).

The code causing the problem does not put the 'or' operator "in-between two arguments", the 'or' precedes the two arguments as such:

```yaml
{{- if or ( ( empty $configObj.bindingType ) ( eq $configObj.bindingType "configmap" ) ) }}
```

Having said that, I tried to workaround the problem by defining a local helm variable to replace the call to 'empty' using 'kindIs' instead.  So, I replaced the above 'if' statement with the following:

```yaml
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $bindingIsConfigMap := and ( ( $bindingTypeExists ) ( eq $configObj.bindingType "configmap" ) ) }}
{{- if $bindingIsConfigMap }}
```
_NOTE:  I have pasted the full change to the configmap.yaml file below._

This code now defines **$bindingIsConfigMap** using the 'and' operator (_again, not "in-between two arguments"_) and I also print the value of **$bindingTypeExists** as a '#' comment for good measure.

This change again succeeds in v3.2.4 and fails in later helm versions.  The v3.6.0 failure is shown here:

**v3.6.0 OUTPUT:**
`Error: template: test-chart/templates/configmap.yaml:13:33: executing "test-chart/templates/configmap.yaml" at <($bindingTypeExists) (eq $configObj.bindingType "configmap")>: can't give argument to non-function $bindingTypeExists`
`helm.go:81: [debug] template: test-chart/templates/configmap.yaml:13:33: executing "test-chart/templates/configmap.yaml" at <($bindingTypeExists) (eq $configObj.bindingType "configmap")>: can't give argument to non-function $bindingTypeExists`

and the successful ouptut as such:

**v3.2.4 OUTPUT:**
```yaml
NAME: test-chart-1623447826
LAST DEPLOYED: Sat Jun 12 00:43:46 2021
NAMESPACE: foobar
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: test-chart/templates/configmap.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  #bindingTypeExists =false
  kind: Secret
  metadata:
    name: test-chart-1623447826-0
  data:
    foo1.yaml: |-
      foo1x: foo1-xValue
      foo1y: foo1-yValue
    bar1.yaml: |-
      bar1x: bar1-xValue
      bar1y: bar1-yValue
- apiVersion: v1
  #bindingTypeExists =true
  kind: ConfigMap
  metadata:
    name: test-chart-1623447826-1
  data:
    foo2.yaml: Zm9vMng6IGZvbzIteFZhbHVlCmZvbzJ5OiBmb28yLXlWYWx1ZQ==
    bar2.yaml: YmFyMng6IGJhcjIteFZhbHVlCmJhcjJ5OiBiYXIyLXlWYWx1ZQ==
```

==============================================================================

With the above change, I would have expected the following 'if' statement to be _'short-circuited'_ when the first of the two arguments (provided to the 'and') was 'false':

`{{- $bindingIsConfigMap := and ( ( $bindingTypeExists ) ( eq $configObj.bindingType "configmap" ) ) }}`

NOTE:  According to my knowledge, go supports _'short-circuiting'_ conditionals in this fashion (ref:  https://stackoverflow.com/questions/53722288/short-circuit-evaluation-in-go )

The error message itself also seems strange to me:
```sh
can't give argument to non-function $bindingTypeExists
```
since **$bindingTypeExists** is a local variable and I am not trying to 'give an argument' to it.

==============================================================================

Given that it does not look like there will be any type of 'fix' to make my chart compatible with the current released versions any time soon, I continued to try to find a workaround and ultimately came up with replacing the one-lined 'if' condition with 10 lines of code that include a local dictionary definition to hold the value I want to inspect as such:

```yaml
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $myDict := dict "bindingTypeValue" "" }}
{{- if $bindingTypeExists }}
{{- $_ := set $myDict "bindingTypeValue" $configObj.bindingType }}
{{- else }}
{{- $_ := set $myDict "bindingTypeValue" "configmap" }}
{{- end }}
{{- $bindingIsConfigMap := get $myDict "bindingTypeValue" }}
{{- if $bindingIsConfigMap }}
```

_NOTE:  The full working **configmap.yaml** file can be found below_

It is not as pretty as it was before, but I guess I can't complain too much since it is now working.

**Thanks again for your comments, analysis and time!**

==============================================================================

### FIRST ATTEMPT TO FIX -- Still fails
**templates/configmap.yaml:**
```yaml
{{- $releaseName := .Release.Name -}}
{{- $values := .Values -}}
{{- $configVars := $values.aaa.bbb -}}
{{- if $configVars }}
apiVersion: v1
kind: List
items:
{{- range $index, $configObj := $configVars }}
{{- $configMapName := ( default ( printf "%s-%d" $releaseName $index ) $configObj.bindingRef ) }}
- apiVersion: v1
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $bindingIsConfigMap := and ( ( $bindingTypeExists ) ( eq $configObj.bindingType "configmap" ) ) }}
{{- if $bindingIsConfigMap }}
  kind: ConfigMap
{{- else }}
  kind: Secret
{{- end }}
  metadata:
    name: {{ $configMapName }}
  data:
  {{- $helmDataVars := ( $configObj.ccc ) }}
  {{- if not ( empty $helmDataVars ) }}
  {{- range $dataVarIdx, $dataVarObj := $helmDataVars }}
  {{- $dataVarObjName := $dataVarObj.name }}
  {{- $helmDataType := ( default "yaml" $dataVarObj.dataType ) }}
  {{- $helmDataVarData := (index $values $dataVarObjName) }}
{{- if or ( ( empty $configObj.bindingType ) ( eq $configObj.bindingType "configmap" ) ) }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: |-
{{ toYaml $helmDataVarData | indent 6 }}
{{- else }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: {{ toYaml $helmDataVarData | b64enc }}
{{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
```


### WORKAROUND - Successful in v3.24 - v3.6.0
**templates/configmap.yaml:**
```yaml
{{- $releaseName := .Release.Name -}}
{{- $values := .Values -}}
{{- $configVars := $values.aaa.bbb -}}
{{- if $configVars }}
apiVersion: v1
kind: List
items:
{{- range $index, $configObj := $configVars }}
{{- $configMapName := ( default ( printf "%s-%d" $releaseName $index ) $configObj.bindingRef ) }}
- apiVersion: v1
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $myDict := dict "bindingTypeValue" "" }}
{{- if $bindingTypeExists }}
{{- $_ := set $myDict "bindingTypeValue" $configObj.bindingType }}
{{- else }}
{{- $_ := set $myDict "bindingTypeValue" "configmap" }}
{{- end }}
{{- $bindingIsConfigMap := get $myDict "bindingTypeValue" }}
{{- if $bindingIsConfigMap }}
  kind: ConfigMap
{{- else }}
  kind: Secret
{{- end }}
  metadata:
    name: {{ $configMapName }}
  data:
  {{- $helmDataVars := ( $configObj.ccc ) }}
  {{- if not ( empty $helmDataVars ) }}
  {{- range $dataVarIdx, $dataVarObj := $helmDataVars }}
  {{- $dataVarObjName := $dataVarObj.name }}
  {{- $helmDataType := ( default "yaml" $dataVarObj.dataType ) }}
  {{- $helmDataVarData := (index $values $dataVarObjName) }}
{{- if $bindingIsConfigMap }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: |-
{{ toYaml $helmDataVarData | indent 6 }}
{{- else }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: {{ toYaml $helmDataVarData | b64enc }}
{{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
```

**Comment by bacongobbler** [comment] 2021-06-11 22:58
While I sympathize with your problem, there's not much we can do here. The error is being reported from text/template while the templates are being rendered, so it's more of a Go issue than something we can fix in Helm.

I have seen a few tickets attempt to fix a similar issue where a null value surrounded by brackets (`( $bindingTypeValue )`) can trip this error. https://github.com/helm/charts/pull/23967 alludes to this. Perhaps you can start your investigation there.

In any case, if you think you can isolate the issue, please file a ticket with [the Go team](https://github.com/golang/go). Thanks!

**Comment by myuseridbws** [comment] 2021-06-11 23:19
> In any case, if you think you can isolate the issue, please file a ticket with [the Go team](https://github.com/golang/go). Thanks!

Okay!   Thanks so much for your timely assistance and analysis.

==========================================================================

For those who are interested, I am including the workaround I came up with here.

I replaced the following line:

```yaml
{{- if or ( ( empty $configObj.bindingType ) ( eq $configObj.bindingType "configmap" ) ) }}
```

with:
```yaml
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $myDict := dict "bindingTypeValue" "" }}
{{- if $bindingTypeExists }}
{{- $_ := set $myDict "bindingTypeValue" $configObj.bindingType }}
{{- else }}
{{- $_ := set $myDict "bindingTypeValue" "configmap" }}
{{- end }}
{{- $bindingTypeValue := get $myDict "bindingTypeValue" }}
{{- if eq $bindingTypeValue "configmap" }}
```

And now, v3.6.0 produces the following OUTPUT:
```yaml
NAME: test-chart-1623453127
LAST DEPLOYED: Sat Jun 12 02:12:08 2021
NAMESPACE: foobar
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: test-chart/templates/configmap.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  #bindingTypeExists =false
  kind: ConfigMap
  metadata:
    name: test-chart-1623453127-0
  data:
    foo1.yaml: |-
      foo1x: foo1-xValue
      foo1y: foo1-yValue
    bar1.yaml: |-
      bar1x: bar1-xValue
      bar1y: bar1-yValue
- apiVersion: v1
  #bindingTypeExists =true
  kind: Secret
  metadata:
    name: test-chart-1623453127-1
  data:
    foo2.yaml: Zm9vMng6IGZvbzIteFZhbHVlCmZvbzJ5OiBmb28yLXlWYWx1ZQ==
    bar2.yaml: YmFyMng6IGJhcjIteFZhbHVlCmJhcjJ5OiBiYXIyLXlWYWx1ZQ==
```

======================================================================

The full file now looks like this:

**template/configmap.yaml**
```yaml
{{- $releaseName := .Release.Name -}}
{{- $values := .Values -}}
{{- $configVars := $values.aaa.bbb -}}
{{- if $configVars }}
apiVersion: v1
kind: List
items:
{{- range $index, $configObj := $configVars }}
{{- $configMapName := ( default ( printf "%s-%d" $releaseName $index ) $configObj.bindingRef ) }}
- apiVersion: v1
{{- $bindingTypeExists := not ( kindIs "invalid" $configObj.bindingType ) }}
  #bindingTypeExists = {{- $bindingTypeExists }}
{{- $myDict := dict "bindingTypeValue" "" }}
{{- if $bindingTypeExists }}
{{- $_ := set $myDict "bindingTypeValue" $configObj.bindingType }}
{{- else }}
{{- $_ := set $myDict "bindingTypeValue" "configmap" }}
{{- end }}
{{- $bindingTypeValue := get $myDict "bindingTypeValue" }}
{{- if eq $bindingTypeValue "configmap" }}
  kind: ConfigMap
{{- else }}
  kind: Secret
{{- end }}
  metadata:
    name: {{ $configMapName }}
  data:
  {{- $helmDataVars := ( $configObj.ccc ) }}
  {{- if not ( empty $helmDataVars ) }}
  {{- range $dataVarIdx, $dataVarObj := $helmDataVars }}
  {{- $dataVarObjName := $dataVarObj.name }}
  {{- $helmDataType := ( default "yaml" $dataVarObj.dataType ) }}
  {{- $helmDataVarData := (index $values $dataVarObjName) }}
{{- if eq $bindingTypeValue "configmap" }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: |-
{{ toYaml $helmDataVarData | indent 6 }}
{{- else }}
    {{ printf "%s.%s" $dataVarObjName $helmDataType }}: {{ toYaml $helmDataVarData | b64enc }}
{{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
```
