### ISSUE TITLE
Errors after upgrading to 3.3.4

### ISSUE THREAD

**Issue by pieterv-icloud-com** [helm/helm#8792] opened 2020-09-23 04:50 UTC
This is related to #8776

Just upgraded to 3.3.4 and it looks like the warnings are now being pushed to error stream causing all our pipelines to fail with this:

2020-09-23T04:37:17.5225159Z ##[section]Starting: helm list
2020-09-23T04:37:17.5234692Z ==============================================================================
2020-09-23T04:37:17.5235057Z Task         : Package and deploy Helm charts
2020-09-23T04:37:17.5235503Z Description  : Deploy, configure, update a Kubernetes cluster in Azure Container Service by running helm commands
2020-09-23T04:37:17.5235832Z Version      : 0.175.4
2020-09-23T04:37:17.5236061Z Author       : Microsoft Corporation
2020-09-23T04:37:17.5236351Z Help         : https://aka.ms/azpipes-helm-tsg
2020-09-23T04:37:17.5236659Z ==============================================================================
2020-09-23T04:37:17.7716777Z [command]/workspace/_tool/helm/3.3.4/x64/linux-amd64/helm ls --namespace cib-k8-magic-dev --output json
2020-09-23T04:37:17.9788806Z WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config
2020-09-23T04:37:17.9789681Z WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config
2020-09-23T04:37:17.9792110Z [{"name":"dadjokes-gradle-sbt2-jre11-api","namespace":"cib-k8-magic-dev","revision":"1","updated":"2020-07-14 14:30:57.805873782 +0000 UTC","status":"failed","chart":"dadjokes-gradle-sbt2-jre11-api-0.0.2-63254193faa65349a32fb7e791f472107a5d19e0","app_version":"1.16.0"},{"name":"fluentd","namespace":"cib-k8-magic-dev","revision":"6","updated":"2020-09-21 08:54:04.668049177 +0000 UTC","status":"deployed","chart":"fluentd-1.9.1","app_version":"v2.4.0"},{"name":"hello-world-api","namespace":"cib-k8-magic-dev","revision":"419","updated":"2020-09-23 04:32:11.059193346 +0000 UTC","status":"deployed","chart":"hello-world-api-0.0.538","app_version":"1.16.0"}]
2020-09-23T04:37:17.9827315Z ##[error]WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config

2020-09-23T04:37:17.9839718Z ##[section]Finishing: helm list

You can see the behaviour here:

2020-09-23T04:37:17.9827315Z ##[error]WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /workspace/_temp/helmTask/1600835837733/config

**Comment by bacongobbler** [comment] 2020-09-23 05:17
Azure Devops bash tasks treats warning messages on stderr as errors, which is incorrect behaviour.

However, there is a feature flag in Azure Devops bash tasks that will prevent builds from failing when there's output present on STDERR. If you enable that feature, the issue will go away.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops#yaml-snippet

From that example, you should have

```
- task: Bash@3
  inputs:
    failOnStderr: false
```

closing as a duplicate of #6461.

**Closed by bacongobbler** 2020-09-23 05:17 UTC

**Comment by pieterv-icloud-com** [comment] 2020-09-23 05:21
Hi, we are using the built in azure DevOps helm task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops and not the bash task. 

This option is not available on the helm task.

**Comment by pieterv-icloud-com** [comment] 2020-09-23 05:29
Hi, we are using the built in azure DevOps helm task https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops <https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops> and not the bash task.

This option is not available on the helm task.

**Comment by bacongobbler** [comment] 2020-09-23 05:34
Please file an issue upstream with Azure DevOps. There's nothing we can do here. Helm is correctly reporting a warning. It is Azure DevOps that is handling the log output incorrectly.

An alternative option would be to fix the permissions of your kubeconfig file within the devops task. I assume this may also be set up by azure devops, which I would again urge you to file an issue there.

**Comment by pieterv-icloud-com** [comment] 2020-09-23 05:35
Will do
