### ISSUE TITLE
change HELM_PLUGINS and then install failed

### ISSUE THREAD

**Issue by wang007** [helm/helm#9946] opened 2021-07-15 14:20 UTC
first. already install push plugin.
```
helm plugin install https://e.coding.net/coding-public/helm-push
```

1. export HELM_PLUGINS=${HOME}/.cache/helm/plugins

2. helm plugin list,  not any plugin
```
NAME    VERSION DESCRIPTION
```

3.  install plugin.
```
helm plugin install https://e.coding.net/coding-public/helm-push
```
print error: 
```
Error: plugin already exists
```
That is, the meta information for list and install does not come from the same place.

run on debug mode and print error
```
helm.go:81: [debug] plugin already exists
helm.sh/helm/v3/pkg/plugin/installer.Install
        /private/tmp/helm-20210414-19290-19pumva/pkg/plugin/installer/installer.go:53
main.(*pluginInstallOptions).run
        /private/tmp/helm-20210414-19290-19pumva/cmd/helm/plugin_install.go:78
main.newPluginInstallCmd.func3
        /private/tmp/helm-20210414-19290-19pumva/cmd/helm/plugin_install.go:59
github.com/spf13/cobra.(*Command).execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /private/tmp/helm-20210414-19290-19pumva/cmd/helm/helm.go:80
runtime.main
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/proc.go:225
runtime.goexit
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371

```

Output of `helm version`:
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mattfarina** [comment] 2021-07-15 19:56
This is a duplicate of #9814. There is a bug around the plugins location for install.

**Closed by mattfarina** 2021-07-15 19:56 UTC
