### ISSUE TITLE
Json Schema validation is not friendly when used with chart dependencies

### ISSUE THREAD

**Issue by howardjohn** [helm/helm#10392] opened 2021-11-23 16:50 UTC
Currently, if you use a json schema with Chart.yaml `dependencies`, you will run into `- (root): Additional property global is not allowed`.

This can be reproduced with a Chart.yaml like

```yaml
apiVersion: v2
name: istio-gateway
version: 0.0.1
appVersion: 1.12.0
description: "This Helm chart is an installation of istio-gateway, with additional components."
home: https://istio.io/latest/docs/setup/install/helm/

dependencies:
- name: gateway
  version: 1.12.0
  repository: https://istio-release.storage.googleapis.com/charts
```

Then we will see:
```
$ helm template .
Error: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- (root): Additional property global is not allowed
```

This is because the helm chart does not define `global` in the json schema. This seems reasonable from the chart point of view - when used as-is, `global` is not a valid.

Its not clear how either a chart author should accommodate for this, or how a a chart consumer should account for this.

**Comment by zonggen** [comment] 2021-11-23 18:33
I can reproduce this behavior in v3.7.0:
```
$ helm install issue-10392 . --dry-run

Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- (root): Additional property global is not allowe
```

**Comment by lerrigatto** [comment] 2021-11-25 17:41
I am facing the same issue.

```version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}```

**Comment by kvendingoldo** [comment] 2021-11-30 12:10
The same for me
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

**Comment by dmavrommatis** [comment] 2021-12-14 14:01
I had to download the chart, unzip it and add the `global` field inside the `values.schema.json` file.

Now I include the dependency as a local folder to get around this issue but I would prefer a more clean solution from the chart itself.

**Comment by nc-ruth** [comment] 2021-12-23 10:07
I just took a look at Bitnami's way of handling this. [Bitnami's Apache chart](https://github.com/bitnami/charts/blob/master/bitnami/apache/values.schema.json)
They are omitting to set the `"additionalProperties"` property in the values.schema.json, which defaults to `"additionalProperties": true` where in the Istio gateway chart it is set as: `"additionalProperties": false` ([Code reference](https://github.com/istio/istio/blob/7ab13d9a13e338bec31c00fe36f95bdbddc1f640/manifests/charts/gateway/values.schema.json#L4)).

I just tested the istio gateway chart as a subchart where it works by omitting `"additionalProperties"` or setting `"additionalProperties": true` in values.schema.json in the gateway chart. 

This means that it is possible to supply any additional properties (whether it is .global or .gateway-subchart-name.whatever), which I don't know whether if it is a benefit or a disbenefit. If `"additionalProperties": true` is set, Helm only verifies that any overriding property value set by people is following the definitions defined in values.schema.json (defined by the chart owner). So people won't be able to set an array where the property value should be a string.

I don't know whether a chart owner should be strict or be lenient in regards of supplying undefined properties in a subchart.

**Comment by digihunch** [comment] 2021-12-29 00:40
+1 on the issue.  Helm version:
```sh
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```
This keeps many charts from being referenced as dependency if the comment above is true.

**Comment by energy2522** [comment] 2022-03-23 21:35
any update on this? It is still reproducible  with 
`version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}
`

**Comment by Xitric** [comment] 2022-04-07 12:27
We have run into this issue as well, but I guess it is both expected and surprising depending on how you look at it. It seems that when you reference a subchart, the `global` section from the parent chart is _implicitly_ injected into the subchart's `values.yaml` file for validation. After all, the global section is shared among all subcharts.

Furthermore, if you reference a subchart (even a library chart), an implicit entry is made into the parent chart's `values.yaml` file for the subchart's configuration, such as:

```yaml
global:
  ...

some: "config"

subchart: # This is implicitly injected
  child: "Config"
```

So, if you have not taken into account this implicit sections in your `values.yaml` file, and set `"additionalProperties": false` in the root of `values.schema.yaml`, you will run into similar trouble. In this case where we reference a subchart, it is easily handled since we are the author's of the parent chart and can change the schema.

However, in the former case, I guess it is just a matter of explicitly permitting the global keyword in your schema files if you really wish to set `"additionalProperties": false`. I am not sure that I would say this is necessarily Helm's issue, but rather improper use of `values.schema.json` files by chart authors being a little too strict. I cannot come up with a case where including a subchart forces any other section than `global` to be injected, so it seems like a fairly general case to cover. When not permitting the `global` keyword, your schema file is essentially stating that global values are _explicitly not permitted_ - and I don't know why you would want to enforce that.

You could say this is just a quirk of writing JSON schemas for Helm?

**Comment by Divyakhatnar** [comment] 2022-05-04 16:52
Hi @howardjohn,

While doing canary upgrade from 1.11 to 1.12, for Istio ingress, I observed similar error:

$ helm upgrade istio-ingress istio-1.12.4/manifests/charts/gateway -n istio-system
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
gateway:
- (root): Additional property gateways is not allowed
- (root): Additional property global is not allowed
- (root): Additional property defaultConfig is not allowed
- (root): Additional property meshConfig is not allowed

Is the error resolved yet, if not when can we expect it to be resolved?

**Comment by howardjohn** [comment] 2022-05-04 16:54
@Divyakhatnar that is istio specific, but only `global` has been fixed/mitigated - the rest are legitimately invalid keys that are not used in the chart.

**Comment by howardjohn** [comment] 2022-09-03 14:57
This is still an issue, would be great to have open

**Comment by Apollorion** [comment] 2022-11-17 19:10
This should still be open, I too am running into this problem.

**Comment by omniproc** [comment] 2022-12-28 14:20
As @nc-ruth wrote, this is by design. The JSON schema spec. defines how a JSON schema Interpreter - such as the one Helm is using - should handle [additionalProperties](https://json-schema.org/draft/2020-12/json-schema-core.html#additionalProperties).
Helm simply sticks to the spec. here.

The problem seems to be that the authors of your chart - in Ops case the Istio chart - have defined the `additionalProperties` setting in their chart, essentially telling Helm - or really any JSON schema validator - that it's not allowed to have any additional properties defines besides those defined in their JSON schema. You should discuss the reasoning behind that decission with the chart authors.

A temporary workaround could be to disable chart validation when running Helm against a chart you don't control which has that property defined. That said it's arguably better to create a fork of such a chart and remove that  `additionalProperties` since you probably want to keep chart validation.

**Comment by joejulian** [comment] 2023-01-19 08:51
Thank you for that answer, @omniproc. That is correct and answer's the OP's question. Since this is not a helm issue, but rather an issue with how the chart validation is defined, I'm going to close this as completed.

**Closed by joejulian** 2023-01-19 08:51 UTC
Labels: help wanted, feature

**Comment by ogarciacar** [comment] 2023-04-18 14:29
I am adding `global` to my sub chart json validation schema and keeping `additionalProperties=false`. WDYT?

```
      "additionalProperties": false,
      "properties": {
       "global": {
            "type": "object",
            "description": "Define global in subchart json schema",
            "default": {}
        },
```
