### ISSUE TITLE
Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.chart-name.v20" is invalid: data: Too long: must have at most 1048576 characters

### ISSUE THREAD

**Issue by SpamapS** [helm/helm#7126] opened 2019-12-02 15:24 UTC
Output of `helm version`: `version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-afa464", GitCommit:"afa464ce9760bd08a53a207f505b133b93366ea3", GitTreeState:"clean", BuildDate:"2019-10-22T21:42:57Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.):  AWS EKS (Kubernetes v1.12)

Today we tried to update our app using helm v3, which we've been using with the betas/rcs, it would not update, because we added a few more fields, which took it beyond this limit, which I understand is a hard limit enforced deep inside kubernetes (at etcd I think?).

For our use-case, we can work-around it by breaking things up into separate charts, there are about 6 configuration maps and secrets contained in the chart, but meanwhile, it would make a lot of sense if helm just overflowed in to another secret object with a pointer at the end of the data to the overflow, so that nobody gets a deploy-surprise. :)

**Comment by bacongobbler** [comment] 2019-12-02 17:43
duplicate of https://github.com/helm/helm/issues/6711.

**Closed by bacongobbler** 2019-12-02 17:43 UTC
