### ISSUE TITLE
how to add description to upgrade on helm 3?

### ISSUE THREAD

**Issue by horacimacias** [helm/helm#7717] opened 2020-03-02 10:37 UTC
I've been using helm 2 and the description flag when upgrading.
I now see helm 3 does not have such flag and I get a _Error: unknown flag: --description_

Is there any way to specify some description/message on a helm upgrade so that it shows on the _helm history_ command?

**Comment by hickeyma** [comment] 2020-03-02 11:16
Duplicate of #7033

**Comment by hickeyma** [comment] 2020-03-02 11:18
This was fixed in #7074 and released in [Helm 3.1.0](https://github.com/helm/helm/releases/tag/v3.1.0)

**Closed by hickeyma** 2020-03-02 11:18 UTC

**Comment by horacimacias** [comment] 2020-03-02 11:31
thanks! 

sorry, for some reason I couldn't find the previous issue although I searched ¬_¬'
