### ISSUE TITLE
Helm v3 beta -- Wait for CRDs to be created

### ISSUE THREAD

**Issue by thequailman** [helm/helm#6316] opened 2019-08-29 18:52 UTC
When deploying CRDs with Helm v3, the rest of the chart deployment occurs _immediately_ after a CRD is installed.  This can cause the chart deployment to fail if the CRDs are not yet available.  Helm should wait until the CRD is deployed before continuing with the chart.

**Comment by hickeyma** [comment] 2019-08-29 20:25
@mattfarina @technosophos What do you think?

**Comment by technosophos** [comment] 2019-08-30 23:26
So the problem isn't actually the amount of time that passes. It's that the local cache (`~/.kube/...`) is not updated. We need to find a way to invalidate that cache, and then things should work. I believe @thomastaylor312 has looked into this as well.

**Comment by bacongobbler** [comment] 2019-09-04 14:33
Fixed in #6332

**Closed by bacongobbler** 2019-09-04 14:33 UTC
Labels: bug, v3
