### ISSUE TITLE
Naming convention of Release and Chart

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [helm/helm#2062] opened 2017-03-03 16:21 UTC
I'm having difficulties understanding naming convention in Helm.

I've setted up Helm on my CI/CD pipeline to handle deployments, called my Chart ```mysite``` and Release ```dev``` so the fullname comes out ```dev-mysite```, everything was good and the application worked like a charm.
Then i needed to setup another application, i named Chart ```mysite2```, Release ```dev``` and after the deploy ```mysite``` disappeared.
After some research i found out that Helm use only the Release name for all the operations and requires it to be unique across the entire cluster.

So now i'm forced to call the Release ```mysite-dev``` or ```dev-mysite``` and obtain an ugly fullname ```mysite-dev-mysite``` or ```dev-mysite-mysite```
I don't understand how Helm suppose i should handle naming of resources.

**Comment by technosophos** [comment] 2017-03-07 22:58
Helm itself does not require any particular naming scheme, but only places the restraint that a _release name is globally unique_ (just as the name of a namespace).

Other than that, it's up to you. There is, for example, no requirement that you include the `.Chart.Name` in your `fullname` field. That convention is largely driven by the Kubernetes Charts repository, and many people prefer to do that. But it's not required.

**Comment by xcompass** [comment] 2017-05-10 04:10
We ran into the exact same issue. Usually the chart name is your app name. Because the release name has to be unique and if you are deploying multiple apps in the cluster, you will almost need to include the app name in the release name, e.g. myapp-dev, myapp-v1. However nearly all of the official stable charts are using `.Release.Name $name` as the full name (I assume this is the best practice for the full name.), which means the k8s resource names will be something like this: `myapp-dev-myapp-xxx`. (so the app name appears twice in the name). I know you can change the `_helper.tpl` for your own customization. But I wonder how people get around with this double names problem. Thanks.

**Comment by whithajess** [comment] 2017-10-23 22:40
I really think the release name should respect `--namespace` and let you deploy the same name under two seperate namespaces.

**Comment by bacongobbler** [comment] 2017-10-23 22:43
slating this as a good discussion point for Helm 3.

**Comment by tuannvm** [comment] 2017-12-06 16:01
@so0k you might be a great help here :)

**Comment by delcon** [comment] 2018-01-18 10:03
I think administrators should be able to have full control over naming of releases and resources by option.

**Comment by bacongobbler** [comment] 2018-04-24 22:57
I feel like this is a duplicate of #2060 which is being addressed in Helm 3: https://github.com/kubernetes/helm/commit/19398a2ef13d191bf6c1cd9a367278389540b0fd

**Comment by techdragon** [comment] 2018-06-26 09:03
@bacongobbler Scoping is just a partial fix, @xcompass laid things out pretty well, and scoping to be namespace unique, instead of cluster unique, doesn't actually fix the issue, just reduces its impact slightly.

**Comment by bacongobbler** [comment] 2019-02-08 18:41
@techdragon I assume you're referring to this:

> However nearly all of the official stable charts are using `.Release.Name $name` as the full name (I assume this is the best practice for the full name.), which means the k8s resource names will be something like this: `myapp-dev-myapp-xxx`. (so the app name appears twice in the name)

That was a convention set up by the chart maintainers to work around the issue of Helm scoping release names cluster-wide. Now that Helm 3 scopes release names to the namespace, the convention can be changed in the charts repository to accommodate this change, removing the confusion around having service names called `myapp-dev-myapp` and just refer to them as the same release name provided on `helm install`.

Once a stable release of Helm 3 is out, we can work with the chart maintainers to change that convention to accommodate this new change. However, that's a change in chart conventions than Helm. Because of that, I'm going to close this as a duplicate of #2060 which has been fixed in Helm 3 as seen [here](https://github.com/helm/helm/issues/2060#issuecomment-461877394).

Thanks!

**Closed by bacongobbler** 2019-02-08 18:41 UTC
Labels: question/support
