### ISSUE TITLE
package not working with --version and no metadata version

### ISSUE THREAD

**Issue by zekth** [helm/helm#9952] opened 2021-07-19 11:35 UTC
When creating a package with `helm package ./ --version 1337` in a chart without a version the cli outputs:
```
Error: validation: chart.metadata.version is required
```

In a sense it's right to fit the helm charts specs on the other hand when adding the `--version` argument you assume that the version number comes from somewhere else, eg: jenkins/github actions etc.

In my case the version number is set from a composition of corporate version file and a ci build number. Having this current problem i need to either inject the version number in the chart at each version bump, or having a fake version number in the chart and use the `--version` argument.

I'd rather not check the `chart.metadata.version` property if the `--version` argument is passed. 

Output of `helm version`: 
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

**Comment by hickeyma** [comment] 2021-07-20 09:18
@zekth You raise a good point about why the need for the version property when you are passing the version.

Looking at the bigger picture, there are a number of requirements for a chart to be valid.  [The Chart.yaml file](https://helm.sh/docs/topics/charts/#the-chartyaml-file) specified what is required and `version` property is required.  It is in this context that when running the `package` command it needs to validate the chart first and therefore requires the property.

**Comment by zekth** [comment] 2021-07-20 15:56
@hickeyma what about taking the `--version` argument while validating the chart in prior to the package?

**Comment by bacongobbler** [comment] 2021-07-20 17:28
I'm closing this as a duplicate of https://github.com/helm/helm/issues/9298, which reports and discusses the exact issue described in this thread.

**Closed by bacongobbler** 2021-07-20 17:28 UTC
Labels: question/support
