### ISSUE TITLE
Helm3: Fails to install Istio 1.3.0

### ISSUE THREAD

**Issue by KieranP** [helm/helm#6467] opened 2019-09-20 07:50 UTC
Looks like Helm3 is stricter on apiVersion and causing issues:

Commands:
```bash
ISTIO_VERSION=1.3.0
curl -LO https://git.io/getLatestIstio | sh -
INSTALL_DIR=istio-$ISTIO_VERSION/install/kubernetes/helm
kubectl create namespace istio-system
helm3 upgrade -i istio-init $INSTALL_DIR/istio-init --namespace istio-system
helm3 upgrade -i istio $INSTALL_DIR/istio --namespace istio-system \
  --values $INSTALL_DIR/istio/values-istio-demo.yaml
kubectl label namespace default istio-injection=enabled
```

Result:
```
% ISTIO_VERSION=1.3.0
% curl -LO https://git.io/getLatestIstio | sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2802  100  2802    0     0   2047      0  0:00:01  0:00:01 --:--:-- 2736k
% INSTALL_DIR=istio-$ISTIO_VERSION/install/kubernetes/helm
% kubectl create namespace istio-system
namespace/istio-system created
% helm3 upgrade -i istio-init $INSTALL_DIR/istio-init --namespace istio-system
Release "istio-init" does not exist. Installing it now.
NAME: istio-init
LAST DEPLOYED: 2019-09-20 19:45:55.037234 +1200 NZST m=+0.081714680
NAMESPACE: istio-system
STATUS: deployed
% helm3 upgrade -i istio $INSTALL_DIR/istio --namespace istio-system \
  --values $INSTALL_DIR/istio/values-istio-demo.yaml
Release "istio" does not exist. Installing it now.
NAME: istio
LAST DEPLOYED: 2019-09-20 19:46:40.514938 +1200 NZST m=+0.106486861
NAMESPACE: istio-system
STATUS: failed
Error: apiVersion "config.istio.io/v1alpha2" in istio/charts/mixer/templates/config.yaml is not available
```

**Comment by bacongobbler** [comment] 2019-09-20 09:46
Closing as a duplicate of #6451. See explanation at  https://github.com/helm/helm/issues/6451#issuecomment-532855139

**Closed by bacongobbler** 2019-09-20 09:46 UTC
