### ISSUE TITLE
The command `helm template` is missing `--app-version` flag

### ISSUE THREAD

**Issue by dsaydon90** [helm/helm#9876] opened 2021-06-28 08:55 UTC
Output of `helm version`: `version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`

Output of `kubectl version`: `Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

I'm using `helm template` command in order to debug my helm chart. and I'm using the var `.Chart.AppVersion` in order to set my container image tag. 
Currently, I can set the var `.Chart.AppVersion` only with `helm package --app-version ...` 

The thing is that `helm template` command has the `--version` flag but not  `--app-version` 

any chance to add this flag  `--app-version`  also to the `helm template` command?

**Comment by bacongobbler** [comment] 2021-06-30 17:17
I updated the title, because the issue is actually asking for `helm template --app-version`, not `helm package --app-version` which already exists.

duplicate of https://github.com/helm/helm/issues/8194 (`helm install` and `helm template` share the same APIs).

**Closed by bacongobbler** 2021-06-30 17:17 UTC
