### ISSUE TITLE
helm list releases should show repo the chart is installed from

### ISSUE THREAD

**Issue by prashantkalkar** [helm/helm#8238] opened 2020-06-01 14:52 UTC
Output of `helm version`: v3.2.1

Output of `kubectl version`: v1.16.0

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS.

Currently, the `helm list` command lists releases and chart names, but it does not provide the name of the repo from which the chart is installed. 

It is really difficult to find the repository for an installed chart, especially a lot of different repositories are used. 

I feel this information should be readily available for use.

**Comment by bacongobbler** [comment] 2020-06-01 15:32
duplicate of #4256.

**Closed by bacongobbler** 2020-06-01 15:32 UTC
