### ISSUE TITLE
map has no entry for key "fullnameOverride"

### ISSUE THREAD

**Issue by przemolb** [helm/helm#4066] opened 2018-05-16 06:17 UTC
Output of `helm version`: v2.9.0

Output of `kubectl version`: v1.10.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

```
:> helm create test
Creating test
:> helm lint --strict test
==> Linting test
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: render error in "test/templates/service.yaml": template: test/templates/_helpers.tpl:15:14: executing "test.fullname" at <.Values.fullnameOver...>: map has no entry for key "fullnameOverride"

Error: 1 chart(s) linted, 1 chart(s) failed
:> helm version
Client: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.0", GitCommit:"f6025bb9ee7daf9fee0026541c90a6f557a3e0bc", GitTreeState:"clean"}
```

**Comment by przemolb** [comment] 2018-05-16 06:29
I have just upgraded my helm to v2.9.1 but still have the same error.

**Comment by tomislater** [comment] 2018-05-17 15:13
It only occurs if I use `helm lint --strict`. Without `--strict` flag it works fine.

**Comment by przemolb** [comment] 2018-05-17 15:45
Ok - will try without `--strict` then. But shouldn't it pass all the tests  even with `--strict` ;-)

**Comment by tomislater** [comment] 2018-05-17 15:49
If you use `--strict` flag it will fail on lint warnings. I assume that it is a warning.

**Comment by jfillo** [comment] 2018-05-23 14:37
I just ran into this as well with helm version 2.9.0.

The log line from przemolb's original report indicates that this is an error, not a warning.

**Comment by seglo** [comment] 2018-07-10 15:56
Unless there's another way to check if a variable is defined, then this shouldn't fail lint with `--strict` IMO.

**Comment by cmeury** [comment] 2018-07-17 10:17
I can reproduce this with v2.9.1. I suggest to treat this as a bug rather than a support question, because the default chart created by helm should pass the strict linter.

**Comment by qiangli** [comment] 2018-08-07 18:02
helm 2.9.1/ kubectl v1.11.1

Helm lint is failing for the chart it just created as is: Error: 1 chart(s) linted, 1 chart(s) failed

**Comment by bacongobbler** [comment] 2018-08-07 18:36
Thanks for the feedback. The default example chart should definitely pass the linter spec. Promoting to a bug.

**Comment by s4nk** [comment] 2018-08-27 14:33
wasn't the default example chart fixed by https://github.com/helm/helm/pull/3824? I agree with @seglo - being able to check if a property is defined and set inside if statements is quite useful, it used to be allowed with older versions of Helm (e.g., 2.7.2). Is there another way of doing it now without having to explicitly define them with null defaults?

**Comment by cmeury** [comment] 2018-08-28 06:40
Confirm, I cannot reproduce this anymore with `2.10.0`:

```
$ helm version --client
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}

$ helm create foo
Creating foo

$ helm lint --strict foo
==> Linting foo
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, no failures
```

**Closed** 2018-08-28 13:51 UTC
Labels: bug

**Comment by liulangwa** [comment] 2021-01-08 10:00
get .mymap "mapkey1"
