### ISSUE TITLE
Negations in .helmignore cannot be used effectively

### ISSUE THREAD

**Issue by misberner** [helm/helm#8688] opened 2020-09-02 14:10 UTC
With the current semantics of negated rules in `.helmignore`, it is very hard to use them effectively. The existing implementation treats a negated and a non-negated rule in almost the same fashion - whatever matches/doesn't match gets ignored, and the remaining files are evaluated against other rules.
This makes it straight up impossible to have a negated rule where the (non-negated) pattern does NOT match `Chart.yaml` etc., as otherwise I get `chart.metadata is required`. In fact, I cannot think of any other reasonable negated ignore rule other than `!*.yaml` (and even that will strip `NOTES.txt`) -- even `!*/*.yaml` produces the above error (note that `filepath.Match` does not support `{a,b}` style matches), and this cannot be remediated by adding an explicit `!Chart.yaml` either above or below.

Given that helm has no concept of "default" ignores (at least in the presence of a `.helmignore` file), I would have expected negated ignore rules to be evaluated _relative_ to the existing non-negated rules. Something that can be used for things like:
```
mostly-unneeded/
!mostly-unneeded/this-is-important
```
There are obviously some nuances here: what if a file matches both a negated and a non-negated pattern? Do negated patterns always win, or does the order matter in some way? Are directory and file matches treated differently?
However, these can be sorted out, and looking at how git does it might provide some good hints.

When thinking about changing the semantics, is backwards-compatibility a concern here? The way I see it, I would be surprised if anyone currently relies on negated patterns, but maybe there is something I am missing.

**Comment by bacongobbler** [comment] 2020-09-02 15:19
duplicate of https://github.com/helm/helm/issues/3622.

**Closed by bacongobbler** 2020-09-02 15:19 UTC
