### ISSUE TITLE
Error: incompatible versions client[v2.9.1] server[v2.8.2]

### ISSUE THREAD

**Issue by ajindal3** [helm/helm#4547] opened 2018-08-28 11:07 UTC
Output of `helm version`: client - v2.9.1, server v2.8.2

Output of `kubectl version`: client :- v1.11.2, server:- v1.9.7
Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

when I am trying with `helm ls --tiller-namespace=<namespace>` getting error like `Error: incompatible versions client[v2.9.1] server[v2.8.2]`. I am a mac book user (installed via brew) and not sure how to downgrade my client version of helm since could not get much help onto it through online. Kindly advise.

**Comment by bacongobbler** [comment] 2018-08-28 15:20
@ajindal3 with homebrew, you can downgrade to a previously installed version of helm via `brew switch`, or you can upgrade tiller to v2.9.1 via `helm init --upgrade`.

**Comment by technosophos** [comment] 2018-08-28 16:00
I left a long explanation for why we don't currently do this on #4549.

**Comment by bacongobbler** [comment] 2018-08-28 16:02
this is also a dupe of https://github.com/helm/helm/issues/1523, so closing this. Thanks @technosophos for the detailed response!

**Closed by bacongobbler** 2018-08-28 16:02 UTC
Labels: question/support

**Comment by ajindal3** [comment] 2018-09-06 15:09
I can see that issue has been closed but I am still struggling to find the brew formula to install a specific helm version i.e., `2.8.2`. Since when I do `brew install kubernetes-helm`, by default it installs the latest version and I don't know how to downgrade my local helm version.

Also, I don't have permission to upgrade tiller.

**Comment by bacongobbler** [comment] 2018-09-06 15:16
https://stackoverflow.com/a/4158763

**Comment by bacongobbler** [comment] 2018-09-06 15:18
If you're having trouble with Homebrew, older releases of Helm are available on [the releases page](https://github.com/helm/helm/releases). Specifically Helm 2.8.2 can be found here: https://github.com/helm/helm/releases/tag/v2.8.2

**Comment by ahaurat** [comment] 2018-09-20 19:55
@ajindal3 I was having the same issue as you:
```
$ helm list
Error: incompatible versions client[v2.10.0] server[v2.9.1]
```
I hadn't previously installed client[v2.9.1] and thus couldn't just `brew switch` as suggested by @bacongobbler nor did the SO answer linked above have a solution for that situation. I ended up having to follow the steps in a different answer on that SO question: https://stackoverflow.com/a/17757092/2356383

Which basically says

- Search on Github for the correct `kubernetes-helm.rb` file for the version I wanted (2.9.1 in my case): https://github.com/Homebrew/homebrew-core/search?q=kubernetes-helm&type=Commits
- Click the commit hash button (`78d6425`)
- Click the "View" button
- Click the "Raw" button
- And copy the url: https://raw.githubusercontent.com/Homebrew/homebrew-core/78d64252f30a12b6f4b3ce29686ab5e262eea812/Formula/kubernetes-helm.rb

Then I ran the following once I had the url for the correct `kubernetes-helm.rb` file
```
$ brew unlink kubernetes-helm
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/78d64252f30a12b6f4b3ce29686ab5e262eea812/Formula/kubernetes-helm.rb
$ brew switch kubernetes-helm 2.9.1
```

Hope this helps someone.

**Comment by germanattanasio** [comment] 2018-09-25 15:59
@ahaurat you are the real MVP

**Comment by kevinhcross** [comment] 2019-02-21 14:27
In case is anyone ends up on this ticket after searching and wants a better solution than Homebrew to manage Helm installations I recently came across [asdf](https://github.com/asdf-vm/asdf) which has a [helm plugin](https://github.com/Antiarchitect/asdf-helm). `asdf` will let you install and switch between any version of Helm. It will even let you create a `.tool-versions` file in a directory so that the Helm version used in that tree will be different from the global version.

**Comment by TJM** [comment] 2019-11-11 15:37
Why doesn't this just work like `brew install kubernetes-helm@v2.9.1` or whatever target version you desire? Is this an issue with homebrew, or helm or _____ ?
