### ISSUE TITLE
Non-backwards compatible change in v3.3.2 ?

### ISSUE THREAD

**Issue by Dunning-Kruger** [helm/helm#8769] opened 2020-09-18 17:15 UTC
# v3.3.1 - Working
```shell
~$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
~$ helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
"azure-marketplace" has been added to your repositories
```

# v3.3.2 - Not working
```shell
~$ helm version
version.BuildInfo{Version:"v3.3.2", GitCommit:"e5077257b6ca106d1f65652b4ca994736d221ab1", GitTreeState:"clean", GoVersion:"go1.14.9"}
~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"f862ce9a809b9832be36717bfc4efae470f59fbf", GitTreeState:"clean", BuildDate:"2020-08-24T18:41:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
~$ helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo --debug
Error: looks like "https://marketplace.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
helm.go:94: [debug] error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"
looks like "https://marketplace.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached
main.(*repoAddOptions).run
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:142
main.newRepoAddCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/repo_add.go:71
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

**Comment by bacongobbler** [comment] 2020-09-18 17:32
duplicate of #8761.

**Closed by bacongobbler** 2020-09-18 17:32 UTC
