### ISSUE TITLE
Helm upgrade with --force fails with possibly incorrect error message

### ISSUE THREAD

**Issue by antonosmond** [helm/helm#4862] opened 2018-10-31 10:02 UTC
Output of `helm version`:
```
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.5", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-02T23:42:40Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

I'm trying to upgrade a helm release using the `--force` flag as there's resources which I know already exist (not part of the original release) but I want helm to delete and recreate them so they become part of the new release. Is this how the force flag works?

Either way, the upgrade fails but the error message is strange. The first time we ran it we got:
```
Error: UPGRADE FAILED: no Service with the name "notifications" found
```
Obviously I went to our cluster to check if the service existed and as expected it, it did exist.
We re-ran the upgrade and then we got a different message:
```
Error: UPGRADE FAILED: no Secret with the name "notifications" found
```
This time for the secret instead of the service and again we checked and the secret definitely exists.
Is the actual problem that `--force` doesn't work as I expected and the release is failing because the resources *DO* exist rather than don't exist but helm showing us the wrong error message?

**Comment by mattfarina** [comment] 2018-10-31 13:49
I have a couple questions:

* Can you share the chart that's causing the problem?
* You say there are assets not part of the original release? How were they added for helm to notice them?
* Is the name in the chart template for these the exact same as what you see?

Usually the name is set to something related to the release so that multiple versions of a chart can be installed. This is often the `fullname`...

```
{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

**Comment by antonosmond** [comment] 2018-10-31 13:58
@mattfarina the chart templates are custom charts but I'm fairly confident the issue is simply an incorrect error message. As an example, if I create a secret named `blah` (outside of helm using kubectl or something) and then create a chart which includes a secret for the same namespace with with the same name i.e. `blah`, when I try to install the chart it should fail saying that it can't create the secret because a secret of the same name already exists.
Instead we're seeing this:
```
Error: UPGRADE FAILED: no Secret with the name "blah" found
``` 
But the secret does exist i.e. we created it outside of helm and it's still there now. And the fix is to remove the existing secret so the secret in the helm chart doesn't have a name collision.

Let me get an example together which I can post here

**Comment by antonosmond** [comment] 2018-10-31 15:35
It was a bit more difficult to reproduce than I first thought but here's how to reproduce the problem.

Clone the example repo:
```sh
git clone https://github.com/antonosmond/helm-example.git
cd helm-example
```

The chart has 2 secrets. The first is purely so we can deploy an initial
release successfully. The bug only appears when there has been a successful 
release previously. The second secret is initially commented out and will
be used to demonstrate the bug after the initial release.

Install the chart which should be successful:
```sh
helm upgrade --install example . --force
```

Create a secret outside of helm named `example` e.g.
```sh
kubectl create secret generic example --from-literal=password=password
```

Now uncomment the second secret in the chart at templates/secret-2.yaml

At this point we have created a secret named `example` outside of helm so
if we try to run helm upgrade (now that we've uncommented the second secret)
it should try and create a secret named `example` in the new release but 
should fail telling us it can't create the secret because a secret with 
the same name already exists:
```sh
helm upgrade --install example . --force
```

Instead, the output I see from the final command says:
```
Error: UPGRADE FAILED: no Secret with the name "example" found
```

**Comment by bacongobbler** [comment] 2018-10-31 15:54
I think this might be related to/is a duplicate of #3785 and #1193. Can you check and confirm, or is there something else at play?

**Comment by antonosmond** [comment] 2018-10-31 16:11
@bacongobbler I believe there are 2 separate problems. In [#1193](https://github.com/helm/helm/issues/1193) there's a lot of talk about helm not cleaning up resources following a failed install/upgrade. While it's true that this would cause resources created by the failing install to become orphaned and cause a name collision during a subsequent upgrade, that is separate from the issue about the misleading error. In my example, there's no previously failed deployment.

**Comment by tarrall** [comment] 2018-11-07 21:48
I can confirm that the issue in #1193 is one way this can happen.  Someone has submitted #4871 which looks like a good fix for that situation (which is how this happened to me).

The error message makes a **little** more sense in context:
https://github.com/helm/helm/blob/d5c183e297aa0c445c4eca4ff4e6ebc3f44bc333/pkg/kube/client.go#L280-L284

Perhaps "no %s with the name %q found in previous release" would be slightly improved wording for that error message?

**Comment by bacongobbler** [comment] 2020-05-14 22:20
closing as inactive.

**Closed by bacongobbler** 2020-05-14 22:20 UTC
Labels: question/support
