### ISSUE TITLE
Helm upgrade not patching deployment

### ISSUE THREAD

**Issue by eroji** [helm/helm#5430] opened 2019-03-11 19:09 UTC
I am running the following helm and tiller versions. I created a custom helm chart that I am attempting to deploy an application with.

```
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
```

As a test, I manually made a change to the deployment manifest after helm had deployed the application. After that, I tried to perform a 'helm upgrade --force' to see if it will patch the existing deployment and undo the manual change I made. It did not.

I then tried to increment the chart version and repeat the same step. It updated the revision count and 'helm list' shows the chart version updated, however, the deployment manifest still did not update. Running a '--dry-run --debug' shows the correct yaml output without the manually added label. Is my expectation wrong of how the upgrade should work? I can't imagine the workflow is supposed to be having to run 'helm del --purge' every time if I want to upgrade a deployment if there were manual changes made.

**Comment by hickeyma** [comment] 2019-03-11 22:43
@eroji Did you make the change directly to the deployment manifest deployed in the cluster i.e. not using Helm e.g. `kubectl edit deployment` ?

If so, when you `upgrade` using Helm, it will check its state against its release configmaps and it will consider that nothing has changed since the previous release.  It is not checking what is deployed on the cluster but the chart templates between install/upgrade (i.e. release states).

**Comment by eroji** [comment] 2019-03-11 23:08
> @eroji Did you make the change directly to the deployment manifest deployed in the cluster i.e. not using Helm e.g. `kubectl edit deployment` ?
> 
> If so, when you `upgrade` using Helm, it will check its state against its release configmaps and it will consider that nothing has changed since the previous release. It is not checking what is deployed on the cluster but the chart templates between install/upgrade (i.e. release states).

Right, I did a `kubectl edit`. Can you clarify what you mean by release state and release configmaps? Perhaps my expectation on how it's diffing and patching the changes is not quite how it actually works. In my example, I manually changed the metadata label. Using `helm upgrade` after that did not revert the deployment back to the way it was. However, if I manually `kubectl edit` the deployment and alter the spec, then `helm upgrade --force` did force the correct manifest to deploy. My understanding is that it was actually doing a `helm del && helm install` under the hood.

It's really exercises to understand how exactly helm is performing the deploys so that I can work with it for production release deployments.

**Comment by hickeyma** [comment] 2019-03-13 14:43
@eroji I will try and explain this as best I can. 

Helm stores it data in Kubernetes ConfigMaps to track releases. For each install and subsequent upgrades (which are different  releases),  Helm will store the chart, values, and state-tracking information in a ConfigMap. This means that it can provide history, rollback etc. on each release of a chart. Refer to [How Helm Uses ConfigMaps to Store Data](http://technosophos.com/2017/03/23/how-helm-uses-configmaps-to-store-data.html) for more details.

This is also how it performs delta checks when upgrading. If it finds changes between the chart you are currently trying to install and the current release details in the release ConfigMap, then it will deploy these changes/deltas to the cluster.  Otherwise, no changes will be deployed.

Helm is not a Kubernetes resource lifecycle controller. It does not manage/monitor your cluster lifecycle. It does something only when it is invoked essentially. Therefore, if you make changes to the cluster that is not through the chart and Helm, then Helm is unaware of the changes. Therefore, when you upgrade in between changes applied directly to the cluster, it still does the delta with the release ConfigMap only.

Re `helm upgrade --force`, not sure how this worked for you. My understanding is that this should only work when the first release has failed. More details [here](https://github.com/helm/helm/pull/3597).

Hope this helps.

**Comment by jeremyxu2010** [comment] 2019-03-14 08:30
@hickeyma 

So after I use `kubectl edit deploy xxxx`, the `helm upgrade` DO NOT work anymore!

if I want use `helm upgrade` to upgrade a release, I must `helm delete --purge xxxx; helm install xxxx` again? 

So bad this design! Reinstall a release usually means pv data lost!

**Comment by hickeyma** [comment] 2019-03-14 09:46
@jeremyxu2010 Doing a direct change to your environment should not usually result in an `helm upgrade` failing. I think this depends on the changes that are done that could potentially cause this. Usually it just ignores those changes as mentioned in comment above.

I agree with you that having to delete and re-install is not a great approach but this is to deal with the scenario when the install is hosed and a last resort.

**Comment by jeremyxu2010** [comment] 2019-03-15 03:08
@hickeyma

**Comment by jeremyxu2010** [comment] 2019-03-15 03:09
@hchauvin I use `helm upgrade --install --recreate-pods --force test xxx.tgz` to upgrade

**Comment by jeremyxu2010** [comment] 2019-03-15 03:26
@hickeyma In my scenario， I change `appVersion` and `image.tag` in chart's tgz file, then use `helm upgrade --install --recreate-pods --force xxx xxx-1.0.0.tgz`  to upgrade a release. `helm list` shows the release has upgraded to the new `appVersion`， but the image in deployment DOES NOT change.

I review helm's code, and found codes below:

```golang
// reuseValues copies values from the current release to a new release if the
// new release does not have any values.
//
// If the request already has values, or if there are no values in the current
// release, this does nothing.
//
// This is skipped if the req.ResetValues flag is set, in which case the
// request values are not altered.
func (s *ReleaseServer) reuseValues(req *services.UpdateReleaseRequest, current *release.Release) error {
	if req.ResetValues {
		// If ResetValues is set, we comletely ignore current.Config.
		s.Log("resetting values to the chart's original version")
		return nil
	}

	// If the ReuseValues flag is set, we always copy the old values over the new config's values.
	if req.ReuseValues {
		s.Log("reusing the old release's values")

		// We have to regenerate the old coalesced values:
		oldVals, err := chartutil.CoalesceValues(current.Chart, current.Config)
		if err != nil {
			err := fmt.Errorf("failed to rebuild old values: %s", err)
			s.Log("%s", err)
			return err
		}
		nv, err := oldVals.YAML()
		if err != nil {
			return err
		}
		req.Chart.Values = &chart.Config{Raw: nv}

		reqValues, err := chartutil.ReadValues([]byte(req.Values.Raw))
		if err != nil {
			return err
		}

		currentConfig := chartutil.Values{}
		if current.Config != nil && current.Config.Raw != "" && current.Config.Raw != "{}\n" {
			currentConfig, err = chartutil.ReadValues([]byte(current.Config.Raw))
			if err != nil {
				return err
			}
		}

		currentConfig.MergeInto(reqValues)
		data, err := currentConfig.YAML()
		if err != nil {
			return err
		}

		req.Values.Raw = data
		return nil
	}

	// If req.Values is empty, but current.Config is not, copy current into the
	// request.
	if (req.Values == nil || req.Values.Raw == "" || req.Values.Raw == "{}\n") &&
		current.Config != nil &&
		current.Config.Raw != "" &&
		current.Config.Raw != "{}\n" {
		s.Log("copying values from %s (v%d) to new release.", current.Name, current.Version)
		req.Values = current.Config
	}
	return nil
}
```
It is clear that the second `if logic` caused problem. I think this is not necessary, it should be deleted.

1. If I upgrade with a new chart file, without additional values file, the `ResetValues` logic is right.
2. If I want used original values with a new chart file, the `ReuseValues` logic is right.

So in which scenario, the code should use the second `if` logic below?

```golang
	// If req.Values is empty, but current.Config is not, copy current into the
	// request.
	if (req.Values == nil || req.Values.Raw == "" || req.Values.Raw == "{}\n") &&
		current.Config != nil &&
		current.Config.Raw != "" &&
		current.Config.Raw != "{}\n" {
		s.Log("copying values from %s (v%d) to new release.", current.Name, current.Version)
		req.Values = current.Config
	}
```

**Comment by jeremyxu2010** [comment] 2019-03-15 03:31
In my scenario， I use helm upgrade --install --recreate-pods --force --reset-values xxx xxx-1.0.0.tgz to upgrade a release now.

**Comment by hickeyma** [comment] 2019-03-19 16:11
@jeremyxu2010 I created a scaffold chart using `helm create` and tested as follows.

Install:

```console
$ cat testchart2/templates/deployment.yaml 
[....]
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
[...]

$ helm install tstchart2/
NAME:   agile-robin
LAST DEPLOYED: Tue Mar 19 14:20:02 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                   READY  UP-TO-DATE  AVAILABLE  AGE
agile-robin-tstchart2  0/1    0           0          0s

==> v1/Pod(related)
NAME                                   READY  STATUS   RESTARTS  AGE
agile-robin-tstchart2-895b5945f-w2q9j  0/1    Pending  0         0s

==> v1/Service
NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
agile-robin-tstchart2  ClusterIP  10.100.117.225  <none>       80/TCP   0s

$ helm list
NAME       	REVISION	UPDATED                 	STATUS  	CHART          	APP VERSION	NAMESPACE
agile-robin	1       	Tue Mar 19 14:20:02 2019	DEPLOYED	tstchart2-0.1.0	1.0        	default  

$ kubectl get pods/agile-robin-tstchart2-895b5945f-w2q9j -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-03-19T14:20:02Z"
  generateName: agile-robin-tstchart2-895b5945f-
  labels:
    app.kubernetes.io/instance: agile-robin
    app.kubernetes.io/name: tstchart2
    pod-template-hash: 895b5945f
  name: agile-robin-tstchart2-895b5945f-w2q9j
 [...]
spec:
  containers:
  - image: nginx:stable
[...]
```

**Comment by hickeyma** [comment] 2019-03-19 16:15
Upgrade worked as expected with the image updated.

```console
$ cat testchart2/values.yaml 
[...]
image:
  repository: nginx
  tag: 1.15
  pullPolicy: IfNotPresent
[...]

$ helm upgrade agile-robin tstchart2/
Release "agile-robin" has been upgraded. Happy Helming!
LAST DEPLOYED: Tue Mar 19 14:29:54 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME                   READY  UP-TO-DATE  AVAILABLE  AGE
agile-robin-tstchart2  1/1    0           1          9m53s

==> v1/Pod(related)
NAME                                    READY  STATUS   RESTARTS  AGE
agile-robin-tstchart2-5489bc9dcc-s9lx6  0/1    Pending  0         0s
agile-robin-tstchart2-895b5945f-w2q9j   1/1    Running  0         9m53s

==> v1/Service
NAME                   TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)  AGE
agile-robin-tstchart2  ClusterIP  10.100.117.225  <none>       80/TCP   9m53s

$ kubectl get deployment.apps/agile-robin-tstchart2 -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2019-03-19T14:20:02Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: agile-robin
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tstchart2
    helm.sh/chart: tstchart2-0.2.0
  name: agile-robin-tstchart2
  [...]
    spec:
      containers:
      - image: nginx:1.15
[...]

$ helm history agile-robin
REVISION	UPDATED                 	STATUS    	CHART          	DESCRIPTION     
1       	Tue Mar 19 14:20:02 2019	SUPERSEDED	tstchart2-0.1.0	Install complete
2       	Tue Mar 19 14:29:54 2019	DEPLOYED  	tstchart2-0.2.0	Upgrade complete
```

**Comment by hickeyma** [comment] 2019-03-19 16:17
@jeremyxu2010 I wonder is the issue with chart or the tarball. Could you test it with your chart extract out and then do an install and upgrade?

**Comment by jeremyxu2010** [comment] 2019-03-24 04:53
@hickeyma 
I think it is not an issue with chart or the tarball.
I CAN NOT reproduct this issue with the simple chart.
I will try to reproduct the issue with the complex chart soon.

I install the simple chart as follows :
```bash
$ cd docs/examples/alpine
$ helm package .
$ helm install --name alpine ./alpine-0.1.0.tgz
$ helm list
NAME  	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE
alpine	1       	Sun Mar 24 04:01:04 2019	DEPLOYED	alpine-0.1.0	3.3        	default
$ kubectl describe pod alpine-alpine |grep Image:
    Image:         alpine:latest
# modify appVersion
$ sed -i -e 's/^appVersion:.*$/appVersion: 3.4/' Chart.yaml
# modify image tag
sed -i -e 's/tag:.*$/tag: 3.8/' values.yaml
# repackage the chart
$ helm package .
$ helm install --name alpine ./alpine-0.1.0.tgz
$ helm list
NAME  	REVISION	UPDATED                 	STATUS  	CHART       	APP VERSION	NAMESPACE
alpine	2       	Sun Mar 24 04:03:48 2019	DEPLOYED	alpine-0.1.0	3.4        	default
$ helm history alpine
REVISION	UPDATED                 	STATUS    	CHART       	DESCRIPTION
1       	Sun Mar 24 04:45:20 2019	SUPERSEDED	alpine-0.1.0	Install complete
2       	Sun Mar 24 04:46:48 2019	DEPLOYED  	alpine-0.1.0	Upgrade complete
$ kubectl describe pod alpine-alpine |grep Image:
    Image:         alpine:3.8
```

**Comment by gogineni99** [comment] 2019-03-25 15:27
I have a similar issue.
1) Installed a similar chat sample-project (Image Id: 1 and has and has one environment variable). 
2) Used kubectl edit to remove the environment variable (outside of helm)
3) Upgrade the Image id to 2 in values.yml
4) Performed helm upgarde

My expectation was the new image would be deployment along with then environment variable restored and it is part of the same deployment resource.

Actual: Image got updated, but the environment variable did not get restored.

I thought if there is a delta in a resource (deployment), the whole manifest would be applied again. Is that not how it is supped to work ?

**Comment by cheddarwhizzy** [comment] 2019-04-01 19:22
What's the disadvantage of having helm generate the yaml and just `kubectl apply -f` all the generated files under the hood? Patch doesn't seem to be ideal here since anything added or removed via `kubectl edit` isn't added or removed after `helm upgrade`. 

This is easily reproducible
```
helm create test-chart
helm install --name test --set replicaCount=2 ./test-chart
kubectl edit deploy test-test-chart
(add an environment variable to the deployment spec and watch rolling update)
helm upgrade test --set image.tag=latest,replicaCount=2 ./test-chart
(describe pods, env var is still there)
```

**Comment by bacongobbler** [comment] 2019-04-01 19:26
@cheddarwhizzy see #3805

**Comment by hickeyma** [comment] 2019-04-02 13:55
@gogineni99 Have a look at description in https://github.com/helm/helm/issues/5430#issuecomment-472451791

**Comment by hickeyma** [comment] 2019-04-02 13:56
@jeremyxu2010 Let me know if you can reproduce it

**Comment by hickeyma** [comment] 2019-04-02 13:57
@eroji Did https://github.com/helm/helm/issues/5430#issuecomment-472451791 answer you issue?

**Comment by 4ndr4s** [comment] 2019-04-15 12:43
hey @hickeyma I'm having the same issue I'm trying to upgrade nginx-ingress I upgrade the chart values and all references to previous version and use helm upgrade, I saw the configmap using the new chart version, but others resources are using the previous one, deployment, services and pods are pointing to the previous one if I use helm history I can see the release version change

`47      	Mon Apr 15 07:13:28 2019	SUPERSEDED	barkly-base-3.5.0-dev	Upgrade complete
48      	Mon Apr 15 07:36:54 2019	DEPLOYED  	barkly-base-4.0.0-dev	Upgrade complete`

any ideas?

**Comment by 4ndr4s** [comment] 2019-04-15 19:32
nvm is fixed, didn't update in one file. (facepalm)

**Comment by hickeyma** [comment] 2019-04-25 15:48
@eroji @jeremyxu2010 any update on this?

**Comment by agill17** [comment] 2019-05-24 22:14
I am also running into a similar issue... 

I am upgrading a release with an umbrella chart from a helm repo. One of its dependency version has changed ( the image tag in values file ) but the umbrella chart version has not. 

However when my helm upgrade runs it **fails** to detect that has changed… as a result one of the dependency never gets upgraded…

I have tried downloading the umbrella chart using helm fetch and in the `charts` dir where all my dependencies are stored, I can see the tag in values file has changed but when I use that downloaded chart to run helm upgrade, it **STILL** does not detect that as a change and no upgrades happen…

This does not make any sense :confused: (edited)

**Comment by hickeyma** [comment] 2019-05-27 07:17
@agill17 This is a separate issue. Can you open an issue for this?

**Comment by agill17** [comment] 2019-05-28 16:44
@hickeyma Yes, I believe its this one? Can we move this discussion there if there are any possible workarounds? https://github.com/helm/helm/issues/3702#issuecomment-495809248

**Comment by hickeyma** [comment] 2019-05-28 17:04
@agill17 Little unsure what you mean. This discussion described more what happened when you do changes directly to the cluster and then try to upgrade. Helm support only 2-way merge. That is the answer for here.

#3703 seems more related to an update not being picked up when doing an upgrade using Helm. Maybe I misunderstand?

**Comment by agill17** [comment] 2019-05-28 18:06
@hickeyma yes I found #3703 later after posting my comments here and that issue ( #3703 ) is more related to my issue. You may ignore my comment(https://github.com/helm/helm/issues/5430#issuecomment-495802082).

**Comment by hickeyma** [comment] 2019-05-29 07:33
Closing this issue as explanation given in https://github.com/helm/helm/issues/5430#issuecomment-472451791 and also issue open on 3-way merge at #3805. The conclusion is that because Helm does not support 3-way merge then if changes are made directly to the cluster will not be picked up on an upgrade.

**Closed by hickeyma** 2019-05-29 07:33 UTC
Labels: question/support

**Comment by amir-hadi** [comment] 2019-05-30 17:01
@hickeyma I understand that helm does not support a 3 way merge, but maybe you can give advise of how we can get back to the state, where `helm upgrade` works?

I did a quick fix using `kubectl edit` once to see if the change is helping (it was) and now would like to put it back into my helm chart and deploy using CI / CD. Will now future changes now be picked up by helm and applied properly or not?

**Comment by hickeyma** [comment] 2019-05-31 08:19
@amir-hadi `helm upgrade` is not broken by this. It's just that changes you made directly in the cluster and not through Helm, will not be picked up on the next upgrade. Therefore, the delta when the upgrade runs is against what was last updated by Helm i.e. the state stored by Helm, and not the changes you made to the cluster directly.

**Comment by amir-hadi** [comment] 2019-05-31 08:22
Ok now I finally understood the core problem, but I still don't know how I can get back to "all-helm-mode"? When we upgrade, the values are not updated anymore. I basically want to revert to helm is the single source of truth for the YAMLs and all helm manifests are in git.

**Comment by hickeyma** [comment] 2019-05-31 08:32
In your case, Helm doesn't see any changes from the chart you are upgrading now against what was last deployed. Nothing has changed as the chart hasn't changed. It doesn't know the cluster has changed. It only knows its state.

If you want to reverse the changes you made directly to the cluster, then you need to reverse them directly yourself.

**Comment by amir-hadi** [comment] 2019-05-31 08:36
Ok thank you for trying to help. Thats exactly what I did, I reverted the changes that I did directly one the deployment, but currently didn't test if those changed values would now reapply.

My helm chart also creates HPAs though (those were edited directly as well): I deleted them completely and hoped that now `helm upgrade` would recreate them. Somehow it did recreate them with old values again.

**Comment by wu105** [comment] 2019-08-02 03:11
I have a similar problem with helm v2.14.1: deployed prometheus, then upgraded to the same version with one additional --set, which resulted in a different deployment manifest among other changes.  The desired change is reported by the 'helm get' command, but k8s still use the old definition.  There was no 'kubectl edit' on any related resources.

Here is the new deployment reported by helm, with the last args line new:
```
# Source: prometheus-operator/templates/prometheus-operator/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-prometheus-oper-operator
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-5.12.4
    release: "prometheus"
    heritage: "Tiller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: "prometheus"
  template:
    metadata:
      labels:
        app: prometheus-operator-operator
        
        chart: prometheus-operator-5.12.4
        release: "prometheus"
        heritage: "Tiller"
    spec:
      containers:
        - name: prometheus-operator
          image: "quay.io/coreos/prometheus-operator:v0.30.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --kubelet-service=kube-system/prometheus-prometheus-oper-kubelet
            - --logtostderr=true
            - --crd-apigroup=monitoring.coreos.com
            - --localhost=127.0.0.1
            - --prometheus-config-reloader=quay.io/coreos/prometheus-config-reloader:v0.30.1
            - --config-reloader-image=quay.io/coreos/configmap-reload:v0.0.1
            - --config-reloader-cpu=1
          ports:
            - containerPort: 8080
              name: http
          resources:
            {}
            
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        
      serviceAccountName: prometheus-prometheus-oper-operator
```
