### ISSUE TITLE
In the same namesapce, deleting a release that has the same deployment name as an existing one will delete it even its from a different release

### ISSUE THREAD

**Issue by iftachsc** [helm/helm#5363] opened 2019-02-26 12:20 UTC
This is not a bug i guess, but a serious improvement needed in the shape of protection is needed here.

Output of `helm version`:
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 
GKE

given is a namespace x that has an install release prod-micro1 with deployment name micro1 ( we set fullnameOverride in all releases in different environment to keep objects, service discovery etc the same) 

if i now mistakenly deploy the same chart with release name staging-micro1 it will fail on deployment/other object already exist which make sense. now release staging-micro1 is in failed.
if i delete/purge it - it will delete the existing deployment that belongs to prod -micro1
because they are on the same name resulting in loosing the deployment and its pods.
 
is there no protection from this? do i really have to have all the objects in the deployment contain the release name or any unique string in the name of all objects? this is many times not good since serivcenames for example must be the same between environments.

doesnt helm keep track which resources belong to which release and not according to rendered templates?

any help would be great!
thanks in advanced.

**Comment by hickeyma** [comment] 2019-02-26 13:46
This is a good description on how Helm operates [globally](https://github.com/helm/helm/issues/2060#issuecomment-287463126) in the Kubernetes cluster. A Helm releases creates resource(s) with given name(s).  Once the resource is requested to be created by Helm, it is then managed by the cluster. Helm knows it resources by their names which need to be unique to Helm.  

In your situation this works as expected because Helm removes the release by asking the Kubernetees API server to remove the following resources by name.

**Comment by iftachsc** [comment] 2019-02-26 21:26
Thanks. So helm doesn’t have a way of protecting against it? There are labels on the resources which the associated release name. Can’t it use that for protection knowing he is about to delete resource with a different release label than the one being deleted.


Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by bacongobbler** [comment] 2019-02-26 21:30
Seems like a duplicate of https://github.com/helm/helm/issues/3319. Can you check and see if the two use cases align? If so, we should close this ticket to keep the conversation in a single ticket. Thanks.

**Comment by bacongobbler** [comment] 2019-10-09 16:09
fixed in #6542

**Closed by bacongobbler** 2019-10-09 16:09 UTC
Labels: question/support
