### ISSUE TITLE
helm warns on kubernetes configuration in current directory for all commands

### ISSUE THREAD

**Issue by chrisdoherty4** [helm/helm#11782] opened 2023-02-01 15:37 UTC
```
$ helm help         
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: <replaced>
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: <replaced>
```

The file warned on ends in `.kubeconfig`.

It seems like a bug particularly as the output comes from any command including things like `help`. What's the intended behavior?

Output of `helm version`:

```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}
```

**Comment by joejulian** [comment] 2023-02-01 18:08
Duplicate of #11083

**Closed by joejulian** 2023-02-01 18:08 UTC
