### ISSUE TITLE
Tiller makes unnecessary outbound connections to storage.googleapis.com

### ISSUE THREAD

**Issue by frolickingferret445** [helm/helm#5724] opened 2019-05-14 00:03 UTC
I am currently seeing an issue where tiller is unnecessarily making outbound connections to storage.googleapis.com.  This outbound traffic only occurs when helm init is run (specifically while creating a tiller deployment, AKA without the “--client-only” flag).  For security reasons, I would like to avoid this outbound traffic and am having issues configuring IP tables to block outbound traffic from tiller since the IP is dynamically generated.  While running wireshark, I noticed this outbound traffic when I called helm init.  I initially tried to fix this by adding the ‘--skip-refresh’ flag and then hard-coding a stable-index.yaml file with no entries to the helm root’s “repository/cache/” folder.  I was still seeing this issue, so I tried overriding the default stable-repo-url with “https://localhost”.  This also failed to stop outbound traffic to storage.googleapis.com.

Output of `helm version`:

Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

Output of `kubectl version`:

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

I’d like to make sure that this is an issue that others are seeing, and either understand the configuration changes I need to make (if there is a fix), or request that this is fixed.

**Comment by bacongobbler** [comment] 2019-05-14 05:57
I think there may be some confusion in terminology here, and I'd like to clear some things up. :)

When `helm init` is invoked, Helm creates a Tiller instance in your Kubernetes cluster. Additionally, it adds the `stable` repository to your list and refreshes your local index cache, making the outbound connection to storage.googleapis.com (where the stable chart repository is hosted).

In other words, the outbound connections are coming from the Helm client, not Tiller. Hope that clears things up a little.

Now, to disable this functionality, you many use the `--skip-refresh` flag. That will prevent the Helm CLI from fetching the stable chart's index (and therefore, prevent it from establishing a connection to Google Cloud Storage).

Hope this makes sense.

**Comment by bacongobbler** [comment] 2019-05-14 05:58
Closing as a duplicate of https://github.com/helm/helm/issues/2235. Thanks!

**Closed by bacongobbler** 2019-05-14 05:58 UTC
Labels: question/support
