### ISSUE TITLE
Need option to "assimilate" objects on upgrade/install

### ISSUE THREAD

**Issue by SpamapS** [helm/helm#7223] opened 2019-12-13 14:19 UTC
Output of `helm version`:  version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

In some cases we find our CI/CD pipeline failing to upgrade or install because, for whatever reason, there's already an object present with a name the helm chart specifies.

This fails with:

`Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: Service, namespace: foo, name: someservice`

I'd like to just tell helm to replace any resources like that, rather than fail, effectively allowing me to assimilate them.

**Comment by bacongobbler** [comment] 2019-12-13 15:49
Duplicate of #2730

**Comment by bacongobbler** [comment] 2019-12-13 15:50
Also see #7082

**Closed by bacongobbler** 2019-12-13 15:49 UTC
