### ISSUE TITLE
Why value: "" is gone?

### ISSUE THREAD

**Issue by innerpeacez** [helm/helm#7895] opened 2020-04-09 10:07 UTC
Output of `helm version`:
v3.0.2
Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

values.yaml 
```
env:
  xx: ""
```
deployment.yaml
```
env:
      {{- range $key, $value :=  .Values.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
      {{- end }}
```
do `helm template` result
```
env:
  - name: xx
    value: ""
```
do `helm install` result
```
env:
  - name: xx
```
why -value is gone? Help please.

**Comment by hickeyma** [comment] 2020-04-09 13:24
I tried to reproduce this issue with latest code in master but could not reproduce. I tested it as follows by creating a scaffold chart and adding your template code and values from the description:

```console
$ helm3 create issue-7895
Creating issue-7895

$ cat issue-7895/templates/deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "issue-7895.fullname" . }}
[...]
securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- range $key, $value :=  .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
[...]

$ cat issue-7895/values.yaml 
# Default values for issue-7895.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
[...]
env:
  xx: ""

$ helm3 template issue-7895 issue-7895/
---
# Source: issue-7895/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
[...]
---
# Source: issue-7895/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-7895
[...]
  serviceAccountName: issue-7895
      securityContext:
        {}
      containers:
        - name: issue-7895
          env:
            - name: xx
              value: ""
          securityContext:
[...]

$ helm3 install issue-7895 issue-7895/ --dry-run
NAME: issue-7895
LAST DEPLOYED: Thu Apr  9 12:33:52 2020
NAMESPACE: default
STATUS: pending-install
REVISION: 1
HOOKS:
---
[...]

---
# Source: issue-7895/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-7895
[...]
spec:
      serviceAccountName: issue-7895
      securityContext:
        {}
      containers:
        - name: issue-7895
          env:
            - name: xx
              value: ""
          securityContext:
[...]
```

Do you mind testing with the latest version [v3.1.2](https://github.com/helm/helm/releases/tag/v3.1.2) to see if you can reproduce?

**Comment by technosophos** [comment] 2020-04-09 23:39
Also, update your `kubectl` command. You are 9 versions behind your server version, and 11 versions behind current latest.

**Comment by innerpeacez** [comment] 2020-04-10 08:35
Thank you for your reply. @technosophos @hickeyma . I tested it and found that although there is no value: "", the environment variable is still set successfully. I guess it may just be a display problem. I will upgrade the version later and test again.

**Comment by bacongobbler** [comment] 2020-04-10 13:55
Closing for now. Please feel free to reopen if necessary. Thanks.

**Closed by bacongobbler** 2020-04-10 13:55 UTC
Labels: question/support
