### ISSUE TITLE
"helm del --purge release" does not remove "release-rabbitmq" Stateful Sets

### ISSUE THREAD

**Issue by mouradmourafiq** [helm/helm#3889] opened 2018-04-13 11:03 UTC
Chart: rabbitmq

Output of `helm version`:

```bash
helm version

Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```

Output of `kubectl version`:
```bash
kubectl version

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): 

`Minikube`

Command:

```bash
helm del --purge release

release "release" deleted
```

Dependency:

```
- name: rabbitmq
    version: 0.7.5
    repository: https://kubernetes-charts.storage.googleapis.com/
```

Values:

```
rabbitmq:
  rbacEnabled: false
  rabbitmq:
    username: my-user
    password: my-password
  persistence:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 300m
  replicas: 1
```

Problem:

running the helm delete command `helm del --purge release` does not remove the statful set.

Everything gets removed but the `release-rabbitmq` Stateful Sets and the pod related to it `release-rabbitmq-0`

Outputs:
```
[kube] 2018/04/13 10:53:43 Starting delete for "release-rabbitmq-config" ConfigMap
...
[kube] 2018/04/13 10:53:43 Starting delete for "release-docker-registry-secret" Secret
[kube] 2018/04/13 10:53:43 Starting delete for "release-postgresql" Secret
[kube] 2018/04/13 10:53:43 Starting delete for "release-rabbitmq" Secret
[tiller] 2018/04/13 10:53:44 error: no kind "GetOptions" is registered for version "apps/v1"
[tiller] 2018/04/13 10:53:44 executing 6 post-delete hooks for release
[tiller] 2018/04/13 10:53:44 hooks complete for post-delete release
[tiller] 2018/04/13 10:53:44 purge requested for release
[storage] 2018/04/13 10:53:44 deleting release "release.v1"
```

**Comment by tomhau01** [comment] 2018-04-26 11:29
Im getting the same behavior with helm-2.9.0rc4 with a slightly different error:

```
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 uninstall: Deleting monitoring-grafana
--
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 executing 2 pre-delete hooks for monitoring-grafana
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 hooks complete for pre-delete monitoring-grafana
tiller-deploy-5768cddf85-srhcr tiller [storage] 2018/04/25 10:44:23 updating release "monitoring-grafana.v1"
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Starting delete for "monitoring-grafana" Ingress
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Starting delete for "monitoring-grafana-cluster" Service
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Starting delete for "monitoring-grafana" Service
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Starting delete for "monitoring-grafana" StatefulSet
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Using reaper for deleting "monitoring-grafana"
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 the server could not find the requested resource
tiller-deploy-5768cddf85-srhcr tiller [kube] 2018/04/25 10:44:23 Starting delete for "grafana-secrets" Secret
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 executing 2 post-delete hooks for monitoring-grafana
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 hooks complete for post-delete monitoring-grafana
tiller-deploy-5768cddf85-srhcr tiller [tiller] 2018/04/25 10:44:23 purge requested for monitoring-grafana
tiller-deploy-5768cddf85-srhcr tiller [storage] 2018/04/25 10:44:23 deleting release "monitoring-grafana.v1"

```

**Comment by tomhau01** [comment] 2018-04-27 12:36
Kubernetes version used:
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:24:03Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.11", GitCommit:"1df6a8381669a6c753f79cb31ca2e3d57ee7c8a3", GitTreeState:"clean", BuildDate:"2018-04-05T17:16:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mhenniges** [comment] 2018-05-02 13:52
I am seeing this as well with the 2.9.0 release. This behavior was worked properly in 2.8.1.

**Comment by bacongobbler** [comment] 2018-05-03 00:34
@mhenniges do you have possibly any repro steps/error logs or container (tiller) logs available to demonstrate what issue you're seeing?

**Comment by svidrascu** [comment] 2018-05-16 08:30
This is still happening in 2.9.1

Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.2-eks.1", GitCommit:"e6c42d312ce5a80461ce10e6543e8fe0346bf065", GitTreeState:"clean", BuildDate:"2018-02-16T21:41:28Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:17:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

Steps to reproduce:

```bash
export statefullsetdeploy=$(helm install stable/rabbitmq-ha --set rbac.create=false  --namespace=sergiuv --wait | grep "NAME:   " | sed 's/NAME:   //')
helm delete --purge $statefullsetdeploy
kubectl get sts --namespace=sergiuv | grep $statefullsetdeploy
```
```bash
#logs for creation in tiller

[tiller] 2018/05/16 08:21:19 performing install for 
[tiller] 2018/05/16 08:21:19 executing 0 pre-install hooks for guilded-robin
[tiller] 2018/05/16 08:21:19 hooks complete for pre-install guilded-robin
[storage] 2018/05/16 08:21:19 getting release history for ""
[storage] 2018/05/16 08:21:19 creating release "guilded-robin.v1"
[kube] 2018/05/16 08:21:19 building resources from manifest
[kube] 2018/05/16 08:21:19 creating 6 resource(s)
[kube] 2018/05/16 08:21:19 beginning wait for 6 resources with timeout of 5m0s
[kube] 2018/05/16 08:21:21 Pod is not ready: sergiuv/guilded-robin-rabbitmq-ha-0
[tiller] 2018/05/16 08:22:09 executing 0 post-install hooks for guilded-robin
[tiller] 2018/05/16 08:22:09 hooks complete for post-install guilded-robin
[storage] 2018/05/16 08:22:09 updating release "guilded-robin.v1"
[storage] 2018/05/16 08:22:09 getting last revision of "guilded-robin"
[storage] 2018/05/16 08:22:09 getting release history for "guilded-robin"
[kube] 2018/05/16 08:22:09 Doing get for Secret: "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/Secret/guilded-robin-rabbitmq-ha
[kube] 2018/05/16 08:22:09 Doing get for ConfigMap: "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/ConfigMap/guilded-robin-rabbitmq-ha
[kube] 2018/05/16 08:22:09 Doing get for ServiceAccount: "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/ServiceAccount/guilded-robin-rabbitmq-ha
[kube] 2018/05/16 08:22:09 Doing get for Service: "guilded-robin-rabbitmq-ha-discovery"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/Service/guilded-robin-rabbitmq-ha-discovery
[kube] 2018/05/16 08:22:09 Doing get for Service: "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/Service/guilded-robin-rabbitmq-ha
[kube] 2018/05/16 08:22:09 Doing get for StatefulSet: "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:22:09 get relation pod of object: sergiuv/StatefulSet/guilded-robin-rabbitmq-ha

# logs for deleting the release :

[storage] 2018/05/16 08:23:24 getting release history for "guilded-robin"
[tiller] 2018/05/16 08:23:24 uninstall: Deleting guilded-robin
[tiller] 2018/05/16 08:23:24 executing 0 pre-delete hooks for guilded-robin
[tiller] 2018/05/16 08:23:24 hooks complete for pre-delete guilded-robin
[storage] 2018/05/16 08:23:24 updating release "guilded-robin.v1"
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha-discovery" Service
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha" Service
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha" StatefulSet
[kube] 2018/05/16 08:23:24 Using reaper for deleting "guilded-robin-rabbitmq-ha"
[kube] 2018/05/16 08:23:24 the server could not find the requested resource
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha" ServiceAccount
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha" ConfigMap
[kube] 2018/05/16 08:23:24 Starting delete for "dangling-swan-alfresco-keycloak" Deployment
[kube] 2018/05/16 08:23:24 Using reaper for deleting "dangling-swan-alfresco-keycloak"
[kube] 2018/05/16 08:23:24 Starting delete for "guilded-robin-rabbitmq-ha" Secret
[tiller] 2018/05/16 08:23:24 executing 0 post-delete hooks for guilded-robin
[tiller] 2018/05/16 08:23:24 hooks complete for post-delete guilded-robin
[tiller] 2018/05/16 08:23:24 purge requested for guilded-robin
[storage] 2018/05/16 08:23:24 deleting release "guilded-robin.v1"
```

The relevant piece seems to be 

[kube] 2018/05/16 08:23:24 the server could not find the requested resource

**Comment by svidrascu** [comment] 2018-05-16 08:47
Seems the problem arises when using helm 2.9.1 with a kubernetes cluster older than 1.10.

The deletion worked fine when doing it on a 1.10.2 cluster.

**Comment by meeech** [comment] 2018-07-09 14:42
Can anyone from helm team comment on possibility of this being fixed for clusters older than 1.10?

**Comment by bacongobbler** [comment] 2018-07-09 14:49
Maybe? The kubernetes resource reaper is purely client-side. They've been changing APIs every release so it's possible there was a regression introduced upstream. In 1.11 the client-side reaper is gone in favour of a server-side reaper. We don't have support for 1.11 yet due to how many breaking changes were made in the client APIs, but if the reaper is server-side then the situation should be better.

**Comment by bacongobbler** [comment] 2018-09-05 22:56
I confirmed this has been fixed in later releases as @svidrascu mentioned. Thank you for the tip! I'm going to close this but please feel free to re-open if this isn't the case and we'll take a look into it. Thanks!

**Closed by bacongobbler** 2018-09-05 22:56 UTC
Labels: question/support
